### ISSUE TITLE
Snippets 404

### ISSUE THREAD

**Issue by cookieguru** [eclipsesource/tabris-js#1000]
After 5cb59e00316e0baa5935f19092f8f70480315e3d the snippet links in the online documentation no longer work.  In addition, the snippets in the repo target Tabris.js 2.0 and don't function with 1.x.  Perhaps the online docs could be updated to point to the 1.x branch?

**Comment by ralfstx** [comment]
Fixed in f043d0f. The fix will be rolled out shortly with Tabris 0.10.
