### ISSUE TITLE
selectedImage does not work

### ISSUE THREAD

**Issue by newhow** [eclipsesource/tabris-js#1001]
selectedImage for tabs does not work on ios 10, Tabris 1.9.0

Help please.

**Comment by cookieguru** [comment]
Can you post the code you're using?

**Comment by newhow** [comment]
tabris.ui.set({
    background: mainBackgroundColor,
    statusBarTheme:'dark',
    textColor:'white'
})

var drawer = new tabris.Drawer()
    .on("open", function () {
        console.log('open')
    })
    .on("close", function () {
        console.log('close')
    });
var page = new tabris.Page({
    topLevel: true
})

var navTabFolder = new tabris.TabFolder({
    layoutData: {left: 0, right: 0, top: 0,bottom:0},
    paging: true,
    tabBarLocation:'bottom'
}).appendTo(page);

var tabSchdedule = new tabris.Tab({
    title: "我的日程",
    image:{src:'images/cal50.png',width:25,height:25},
    selectedImage:{src:'images/cal50filled.png',width:25,height:25},
}).appendTo(navTabFolder);

var tabAccount = new tabris.Tab({
    //title: "账号",
    image:{src:'images/cal6.png',width::25,height::25},
    selectedImage:{src:'images/home.png',width::25,height::25},
}).appendTo(navTabFolder);

page.open()

**Comment by cookieguru** [comment]
I was able to replicate your issue in iOS 9 (by replacing the paths to images hosted on the internet).  The same code worked fine on Android.

![screenshot](https://cloud.githubusercontent.com/assets/1888809/19226640/87c10a4c-8e62-11e6-8004-788badb128d9.png)

**Comment by newhow** [comment]
Thank you. Hope the tabris team could check this issue.

**Comment by gosia-eclipsesource** [comment]
Thanks for reporting, and thanks @cookieguru for also checking on iOS 9.
@pmol Could you have a look?

**Comment by ralfstx** [comment]
@newhow Do your images have any transparent parts? It seems that the opaque regions are tinted.

**Comment by ralfstx** [comment]
@newhow Could you try with some images from http://ionicons.com/ and see if the problem persists?

**Comment by newhow** [comment]
@ralfstx Tried using icons from http://ionicons.com/ as you suggested. The problem persists. Unlike @cookieguru 's test result, selectedImage does not work on my Android cellphone.

**Comment by mpost** [comment]
I have tested the example on android and it works as expected:

![screenshot_1476109694](https://cloud.githubusercontent.com/assets/73655/19239496/97fa2bd8-8f06-11e6-8525-9d3b675748a7.png)

```js
tabris.ui.set({
  background: "green",
  statusBarTheme:'dark',
  textColor:'white'
})

var drawer = new tabris.Drawer()
  .on("open", function () {
    console.log('open')
  })
  .on("close", function () {
    console.log('close');
  });
var page = new tabris.Page({
  topLevel: true
})

var navTabFolder = new tabris.TabFolder({
  layoutData: {left: 0, right: 0, top: 0,bottom:0},
  paging: true,
  tabBarLocation:'bottom'
}).appendTo(page);

var tabSchdedule = new tabris.Tab({
  title: "我的日程",
  image:{src:'images/card.png',width:25,height:25},
  selectedImage:{src:'images/card-filled.png',width:25,height:25},
}).appendTo(navTabFolder);

var tabAccount = new tabris.Tab({
  title: "账号",
  image:{src:'images/cart.png',width:25,height:25},
  selectedImage:{src:'images/cart-filled.png',width:25,height:25},
}).appendTo(navTabFolder);

page.open();
```

**Comment by newhow** [comment]
on my Android:
![s61010-225313](https://cloud.githubusercontent.com/assets/8915742/19241493/797c836e-8f41-11e6-92c0-74f275d51736.jpg)

**Comment by cookieguru** [comment]
@newhow What image were you expecting on the 我的日程 tab?

**Comment by newhow** [comment]
@cookieguru I'm expecting card-filled.png, like the one shown by @mpost when the 我的日程 tab is selected.

**Comment by cookieguru** [comment]
@newhow Just as a sanity check, if you use the same image string (`image:{src:'images/cal50.png',width:25,height:25},`) in an `ImageView` does the image show up?

I tested @mpost's snippet above on iOS 9 and Android 6.0.1.  Still seeing the same things--only placeholders on iOS with everything working normally on Android.  I've only been testing with images not bundled with the app but I've noticed that the iOS client is definitely downloading images (checked access logs on the server).  It's also "decoding" them correctly--I used images (png and jpg) of different ratios and the image's bounding box has the same ratio as the source image.  When swiping between tabs it would correctly alternate between square/rectangle etc.  Also tried top/bottom/auto and the behavior was the same.

One inconsistency between platforms: if the height and width are omitted Android resizes the image to a maximum size while iOS displays them at their native size.  For example, a 500x400 image is resized to a small thumbnail on Android but on iOS it takes up about a third of the screen.


Am I correct in assuming that images are not supported on iOS when `tabBarLocation` is set to `top`?

**Comment by mpost** [comment]
@cookieguru Yes you are correct about

    Am I correct in assuming that images are not supported on iOS when tabBarLocation is set to top?

Besides i concur with the comments from your previous post.

Regarding the sizes... You should be using images with the correct size according to your target platform.

**Comment by newhow** [comment]
@cookieguru  Yes: "Just as a sanity check, if you use the same image string (image:{src:'images/cal50.png',width:25,height:25},) in an ImageView does the image show up?"

Agree that there are lots of  inconsistency between platforms. It's a huge challenge to write code once and use it everywhere.

**Comment by jokorivai** [comment]
@cookieguru and @mpost is it a must that the PNG is 24bit format? Just to make sure. I tested 24bit PNG as tab image (both normal and selected) on Android and they works, though.

**Comment by cookieguru** [comment]
@jokorivai 32 bit PNGs work; [eclipsesource/tabris-con](https://github.com/eclipsesource/tabris-con/) uses them.

**Comment by jokorivai** [comment]
Thank you @cookieguru

**Comment by newhow** [comment]
Sorry, it's my fault that I did not really update tabris to version 1.9.0. The lesson I got is that just changing version number in package.json is not  enough. You have to run **npm install** again to update tabris module. I feel so sorry my low-level mistake wasted your time @cookieguru @mpost @ralfstx. After running npm instal， selectedImage works like a charm.

**Comment by cookieguru** [comment]
Interesting; I was using the scratchpad with my local app (1.9.0) and this is what the served `package.json` looks like:
```json
{
	"dependencies": {
		"tabris": "https://tabrisjs.com/downloads/1.9.0/tabris.tgz"
	},
	"title": "My Scratchpad",
	"description": "A playground application",
	"main":"app.js"
}
```

**Comment by newhow** [comment]
I manually edited my package.json:
`{
  "main": "indexios.js",
  "dependencies": {
    "tabris": "^1.9.0"
  }
}`
and  run code in the tabris developer app. As I reported above, version-bump in package.json is not enough for upgrading. I had to run npm install to make it really happened.

**Comment by cookieguru** [comment]
@newhow Right, upgrading to 1.9 on the JS side fixed it for you, but here I am running 1.9 on both and I see the issue.

**Comment by mpost** [comment]
Great to see this figured out. Thanks @cookieguru for the support.

**Comment by newhow** [comment]
@cookieguru please try these images:  https://icons8.com/web-app/23264/user and https://icons8.com/web-app/23264/user#filled. Also, make sure you are **really** on Tabris 1.9.0.

**Comment by cookieguru** [comment]
@newhow Yes, the client is 1.9.0.  The scratchpad always serves up the latest stable version of the JS library regardless of what version the client is running.
