### ISSUE TITLE
open or close event of drawer do not work

### ISSUE THREAD

**Issue by newhow** [eclipsesource/tabris-js#1002]
open or close event of drawer do not work on ios 10, Tabris 1.9.0

Help please.

**Comment by cookieguru** [comment]
Can you post the code you're using?

**Comment by newhow** [comment]
nice to see you here again:

tabris.ui.set({
background: mainBackgroundColor,
statusBarTheme:'dark',
textColor:'white'
})

var drawer = new tabris.Drawer()
.on("open", function () {
console.log('open')
})
.on("close", function () {
console.log('close')
});
var page = new tabris.Page({
topLevel: true
})

var navTabFolder = new tabris.TabFolder({
layoutData: {left: 0, right: 0, top: 0,bottom:0},
paging: true,
tabBarLocation:'bottom'
}).appendTo(page);

var tabSchdedule = new tabris.Tab({
title: "我的日程",
image:{src:'images/cal50.png',width:25,height:25},
selectedImage:{src:'images/cal50filled.png',width:25,height:25},
}).appendTo(navTabFolder);

var tabAccount = new tabris.Tab({
//title: "账号",
image:{src:'images/cal6.png',width::25,height::25},
selectedImage:{src:'images/home.png',width::25,height::25},
}).appendTo(navTabFolder);

page.open()

**Comment by cookieguru** [comment]
You have several syntax errors in your code on lines 32 and 33

![untitled](https://cloud.githubusercontent.com/assets/1888809/19226379/5d882524-8e5f-11e6-9a2f-0befa5f8114d.png)

**Comment by newhow** [comment]
Thank you but double : is just a mistake I made when I posted the code here. The original code in IDE is correct. So, the problem should not be caused by them.

**Comment by newhow** [comment]
Tested on a custom Android 5.1, did not work. Thank you for your information.

**Comment by newhow** [comment]
Sorry, it's my fault that I did not really update tabris to version 1.9.0. The lesson I got is that just changing version number in package.json is not enough. You have to run npm install again to update tabris module. I feel so sorry my low-level mistake wasted your time @cookieguru. After running npm instal，all drawer events work like a charm.
