### ISSUE TITLE
Where To Post Sample Code

### ISSUE THREAD

**Issue by jokorivai** [eclipsesource/tabris-js#1004]
Hi @mpost (sorry I mentioning you), where can we post sample code to? For example, I have JS code to create card view (using composite), where do I post it so other may use it? I Think using issue will not be appropriate.

Thanks.

**Comment by mpost** [comment]
@jokorivai You could create a gist and link it here so google will pick it up when people search for "card" and "tabris".

In addition you could "pin" your snippet on the scratchpad and make it publicly available so that other people can find it: https://tabrisjs.com/<your-username>/scratchpad/

**Comment by mpost** [comment]
![image](https://cloud.githubusercontent.com/assets/73655/19265284/d586d37c-8fa4-11e6-9b7b-ace5d58a6c5c.png)

**Comment by jokorivai** [comment]
ok thankyou @mpost

**Comment by cookieguru** [comment]
For anyone keeping score at home, the link to publicly available scripts is at https://tabrisjs.com/public/scripts
