### ISSUE TITLE
webview on Android does not render some pages

### ISSUE THREAD

**Issue by newhow** [eclipsesource/tabris-js#1007]
On Android, Tabris webView widget does not display some special pages, e.g. [http://m.sui.taobao.org/demos/](url), while the page can be correctly rendered on the android phone's own browser. Also, on ios, that page can be rendered by Tabris webView. Here is my code:

var page = new tabris.Page({
    title: "webview test",
    topLevel: true
});

new tabris.WebView({
    left: 0, top: 0, right: 0, bottom: 0,
    url: 'http://m.sui.taobao.org/demos', 
}).appendTo(page)

page.open()

**Comment by mpost** [comment]
Opening that page in Chrome or Tabris WebView only shows a blank gray screen.

**Comment by newhow** [comment]
@mpost 

> Tabris WebView only shows a blank gray screen. 
that's the issue.But windows PC chrome browser shows:
![2](https://cloud.githubusercontent.com/assets/8915742/19342199/561be92c-9163-11e6-849a-a012b614be6a.png)

**Comment by mpost** [comment]
Ok. I see the Page now in the Chrome Browser (Desktop). Could you inspect the WebView on the Tabris device to narrow down why it is not showing? Navigate your Desktop Browser to: chrome://inspect/#devices

**Comment by newhow** [comment]
@mpost  Tried to debug as you suggested, but saw no error or waning. The console tab shows 
"Welcome to Tabris.js
Attached to com.eclipsesource.tabris.js"
That's it.

**Comment by newhow** [comment]
I'm wondering if Tabris webview on Android supports CSS3 well? If I exclude the css3 files from the above-mentioned website, then Tabris webview on Android could at least show HTML elements, without any styling of course.

**Comment by mpost** [comment]
From my knowledge the WebView is powered by the same engine that runs inside chrome on Android. Creating a minimal native Android app with only one WebView inside should tell us.

**Comment by cookieguru** [comment]
https://play.google.com/store/apps/details?id=com.google.android.webview

**Comment by newhow** [comment]
@cookieguru Did you mean simply installing that app? I did installation, but no help. I doubt Tabris webview on Android supports CSS3 well. 

Can any one confirm that Tabris webview on Android does not show http://framework7.io/kitchen-sink-ios/ ? This webpage uses css3 heavily.

**Comment by cookieguru** [comment]
@newhow I can confirm that link loads fine in a Tabris.js WebView on iOS 9 but does not on Android 4.4 or 6.0.

I offered the link to the webview app without comment as I'm not entirely sure what it does.  It was preinstalled on one of my devices but not on others.

So far as I can tell based on the User-agent strings sent by requests from the WebView they use the native [WebView](https://developer.android.com/reference/android/webkit/WebView.html) and [UiWebView](https://developer.apple.com/reference/uikit/uiwebview) controls.

**Comment by newhow** [comment]
@cookieguru  Thank you for your information. The reason I need webview is to use the calendar and datetime picker written in html5.  The Android webview is really a headache for me.

**Comment by cookieguru** [comment]
@newhow Did you try [eclipsesource/tabris-calendar](https://github.com/eclipsesource/tabris-calendar) for Android?

**Comment by newhow** [comment]
@cookieguru Yes. I know there is a cordova calendar plugin working for both platforms.  But I need to mark some special days(e.g. holidays) with special styling, not just to pick a date.

**Comment by cookieguru** [comment]
[tabris-calendar](https://github.com/eclipsesource/tabris-calendar/) is just a minimal implementation of Android's [CalendarView](https://developer.android.com/reference/android/widget/CalendarView.html).  While CalendarView doesn't have many styling abilities, [this article](https://www.toptal.com/android/android-customization-how-to-build-a-ui-component-that-does-what-you-want) details ways to style it.  You could also look at creating your own custom widget with another library such as [this one](https://github.com/square/android-times-square) which has a plethora of styling abilities.

**Comment by newhow** [comment]
@cookieguru appreciate your information. But the ideal solution is to improve compatibility of webview on Android, so that we can use tons of HTML5 UI components.

**Comment by cookieguru** [comment]
@newhow Not really sure I follow.  If you just want to use HTML, why not just build everything with Cordova?

@mpost This appears to be a Tabris-sepecific issue; I was able to view the aforementioned kitchen sink link in [austindavidbrown/WebView-Developer-Browser](https://github.com/austindavidbrown/WebView-Developer-Browser) while it does not render at all in a debug version of a Tabris.js app (did not try a release build).

**Comment by mpost** [comment]
@cookieguru Good to know. We would be happy to provide a WebView configuration that is more supporting. I'll have a look at the linked project.

**Comment by newhow** [comment]
@cookieguru "why not just build everything with Cordova?" -- tradeoff between performance(native) and development cost(existing html5 UI that native does not provide)

**Comment by mpost** [comment]
We have looked into the Issue and found that there is a bug in the way the Android `RelativeLayout` and the `WebView` interact. The `RelativeLayout` is what we are using as a `Composite`.

Why this only happens on this particular `WebView` content from_http://m.sui.taobao.org/demos_ is not clear atm.

Adding a `WebView` to a `RelativeLayout` with width and height set to `WRAP_CONTENT` causes this particular website to not show up, even when spanning up the `WebView` by attaching its four sides to the parents sides. It can easily reproduced by eg:

```xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                android:layout_width="match_parent"
                android:layout_height="match_parent">

    <WebView
        android:layout_height="wrap_content"
        android:layout_width="wrap_content"
        android:layout_alignParentLeft="true"
        android:layout_alignParentTop="true"
        android:layout_alignParentRight="true"
        android:layout_alignParentBottom="true" />
    
</RelativeLayout>
```

This is the equivalent of doing the following in Tabris.js:

```js
new tabris.WebView({
  left: 0, top: 0, right: 0, bottom: 0
}).appendTo(parent);
```

However, specifying concrete `width` and `height` works around this issue. You can either set a concrete size during the `WebView` creation or set it during the `WebView` parent `resize` callback:

```js
webView.parent().on('resize', function(widget, bounds) {
  webView.set({
    width: bounds.width, height: bounds.height
  });
});
```

Hope this helps. We will continue to look into the issue but for now you should apply this workaround.

**Comment by newhow** [comment]
@mpost thanks for your tips. Works on my Android phone.

**Comment by mpost** [comment]
With Tabris.js 2.x we have migrated to the `ConstraintLayout` on Android where the layout issue is resolved. The following snippet shows the website on Android:

```js
new tabris.WebView({
  left: 0, top: 0, right: 0, bottom: 0,
  url: 'http://m.sui.taobao.org/demos',
}).appendTo(tabris.ui.contentView);
```

![screenshot_1497447386](https://user-images.githubusercontent.com/73655/27134853-3e472464-5117-11e7-9976-399adb23f539.png)
