### ISSUE TITLE
ios CollectionView's refreshEnabled property issue

### ISSUE THREAD

**Issue by newhow** [eclipsesource/tabris-js#1008]
`refreshEnabled: false,` can not disable ios CollectionView's refreshing. But on Android, it works.

**Comment by patrykmol** [comment]
I cannot reproduce it. Can you provide a snippet with this problem?

**Comment by newhow** [comment]
@patrykmol  Let's use the official example [https://tabrisjs.com/examples/#reddit-pet-pictures](url). By simply switching the refreshEnabled to false (line 12), you will be able to see the inconsistency between two platforms: on Android, no spinner will show when you try to refresh, but on ios 10, a spinner will show up.
