### ISSUE TITLE
Remove workaround for Android layout bug in Tabris.js 2.0

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1011]
Tabris.js 2.0 we will raise the minimum required Android version to 4.2 (Api Level 17). This means the layout workaround in Tabris.js for a layout problem on Android is not required anymore and can be removed: https://github.com/eclipsesource/tabris-js/blob/master/src/tabris/Widget.js#L234

**Comment by cookieguru** [comment]
On that note it would be great to document the minimum and maximum supported versions of each platform.

**Comment by newhow** [comment]
@mpost Is it possible that https://github.com/eclipsesource/tabris-js/issues/1007 could be also resolved as a byproduct of version bump?

**Comment by cookieguru** [comment]
@newhow This has more to do with the internals of the JS framework.  That said, if you think a higher `minSdkVersion` would solve #1007 you can try that out by [building locally](https://tabrisjs.com/documentation/latest/local-build).

**Comment by ralfstx** [comment]
@mpost the workaround is required for (`version <= 17`), so we can only remove it when the minimum version is raised to 18 (Android 4.3) or higher.

**Comment by mpost** [comment]
@ralfstx You are right. We removed some code not related to this workaround in tabris-android. I'll close this issue for now.
