### ISSUE TITLE
Cordova FCM plugin

### ISSUE THREAD

**Issue by Gregivy** [eclipsesource/tabris-js#1013]
Hi! I'm trying to use Cordova FCM plugin with my tabris app. This plugin requires google-services.json file to be in the android specific folder. According to the error log, this is the right folder in tabris /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/. I was trying to use cordova hook before build, but not sure whether it's my error in hook script or somewhere else. Here is the hook source https://github.com/Gregivy/quiz/blob/master/cordova/before_build.js

**Comment by cookieguru** [comment]
Can you post the build log?

**Comment by Gregivy** [comment]
I'm using cloud building.

**Comment by Gregivy** [comment]
https://tabrisjs.com/Gregivy/apps/580522a89b51b0e4872d0c96/3/log

**Comment by cookieguru** [comment]
@Gregivy That link is only accessible by you; you'll need to post the contents to a Gist, pastebin, or similar and link it here.

**Comment by Gregivy** [comment]
@cookieguru http://pastebin.com/66HzESrJ

**Comment by mpost** [comment]
@Gregivy Not sure why the build hook is not working as expected but the folder you want to copy in is correct.

**Comment by mpost** [comment]
When creating build hooks you can also test those in a regular cordova build environment on your local machine. Usually a faster turnaround than to use the tabris build service.

**Comment by Gregivy** [comment]
I'll try before prepare hook and add some console log in the script, may be it will help to figure out what's going on.

**Comment by Gregivy** [comment]
It didn't help. Actually nothing even appeared in the log, may be I don't understand some fundamental things about cordova hooks. Are you sure that it is written correctly? The hook script I mean.

**Comment by Gregivy** [comment]
It was a hook error as I expected. Now I have a different kind of error:

Parsing json file: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/google-services.json
:processDebugGoogleServices FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> No matching client found for package name 'com.quizez'

I suspect that the problem could be with copying google-services file, perhaps it's empty.

**Comment by Gregivy** [comment]
I have finally managed to compile the app. The problem was with the difference in package names in google console and cordova config file. I'll test the plugin and write here the review.

**Comment by mpost** [comment]
@Gregivy Good to hear. Let us know how you progress.

**Comment by Gregivy** [comment]
@mpost I have tested the plugin. The app receives notifications. Both tokens and topics methods are working. But the onNotification event never starts in app itself because the plugin uses javascript protocol to talk with app. I think its ok for webviews but I don't know is there any workaround for tabris.

**Comment by Gregivy** [comment]
I found about javascript protocol here: https://github.com/fechanique/cordova-plugin-fcm/issues/23

**Comment by cookieguru** [comment]
>  the plugin uses javascript protocol to talk with app. I think its ok for webviews but I don't know is there any workaround for tabris.
Tabris.js uses JavaScript as well so I'm not sure what the issue would be.

**Comment by Gregivy** [comment]
@cookieguru I checked the java source of the plugin and saw that the plugin tries to find webview in the app and if found it sends data to this webview by modifying the url. Like this `javascript:someFunction(..)`

**Comment by cookieguru** [comment]
Ah yes I see that now--it depends on CordovaWebView and fails if the view is null.  Are you dependent on FCM or can you use `phonegap-plugin-push`? #989

If you need FCM you might be able to fork this and tweak the way it works.  Tabris.js supports the DOM events API so you can emit an event and have your JS code listen to that.

**Comment by Gregivy** [comment]
@cookieguru Yes, I need a FCM push plugin. I have tried another firebase plugin https://github.com/arnesson/cordova-plugin-firebase. It works but notification event doesn't fire either. When I have more time I will try to make a tabris specific version of one of these plugins.

**Comment by cookieguru** [comment]
Can you do your own notifications with the Firebase plugin?  With today's release of Tabris.js 1.10 Websocket support is official, and the Firebase plugin should work with a minor tweak; see #823

**Comment by mpost** [comment]
The plugin https://github.com/arnesson/cordova-plugin-firebase recently has an update to 0.1.18. You should try with that one again as it has an interesting PR merged that could solve your issue: https://github.com/arnesson/cordova-plugin-firebase/commit/437b228c1e19518e6ec83f1c24326c04fb80adc4

**Comment by Gregivy** [comment]
It works on android now, however there was problem with receiving notifications in background, callback didn't fire. Found solution here https://github.com/arnesson/cordova-plugin-firebase/issues/86. I used tabris onResume event to call onNotification function again.

**Comment by mpost** [comment]
@Gregivy That is 90% good to hear. Hope they fix the issue with the `onResume` as well.

**Comment by Abichai** [comment]
From what I've seen this issue is because when having a background notification the notificationCallbackContext is lost thus you will never have the javascript called again. I solved the issue by saving the notificationCallbackContext as a CallbackContext so the garbage collector doesn't delete it as soon the application is in background. Now it works for background notification. I don't really understand the need to have it as a WeakReference so maybe check the memory usage of the application.

**Comment by iteearmah** [comment]
Google Firebase Cloud Messaging
Any help in implementing it for push notifications.
A step by step tutorial will be very appreciated. :-)

**Comment by mpost** [comment]
We have open sourced a newly created Tabris.js firebase plugin with cloud messaging support for Android: https://github.com/eclipsesource/tabris-plugin-firebase

The plugin requires Tabris.js 2 but should serve all your cloud messaging needs. Usage instructions are in the README. Issue and PRs are welcome. We also plan to add support for more of the various firebase features (like analytics and crash reporting) in the future.

**Comment by ralfstx** [comment]
With the tabris-plugin-firebase in place, I think this issue can be closed.
