### ISSUE TITLE
Destroy/Delete/Remove a Page

### ISSUE THREAD

**Issue by jabedbd** [eclipsesource/tabris-js#1015]
Is there any way to destroy/remove a page in tabris. 

for example i create a page with 
var page = new tabris.Page({
  title: "Page",
  topLevel: true
});

i need to  completely remove it when click a button.

i try with page.destroy; but its not work.

**Comment by cookieguru** [comment]
`page.[dispose](https://tabrisjs.com/documentation/latest/api/Widget#dispose)()`

**Comment by jabedbd** [comment]
its show me "Error! Can not close the last page"
but i have 2 page and i only destroy one of them (this is not the last page).

**Comment by cookieguru** [comment]
If one is a top level page and the other isn't, you can't close the top level page.

Also feel free to post a code snippet

**Comment by jabedbd** [comment]
my first page is 
var about = new tabris.Page({
  title: "About Us",
  topLevel: true
});
Second page is: 
var login = new tabris.Page({
  title: "Login",
  topLevel: true
});

And add this to Login page: 

new tabris.Button({
  layoutData: {left: 10, top: 10},
  text: "Login"
}).on("select", function() {
  localStorage.setItem('Login', "1".toString()); 
   login.dispose();  
}).appendTo(login);

**Comment by ralfstx** [comment]
You should use `page.close()` to close and dispose the stacked page.

**Comment by jabedbd** [comment]
`new tabris.Button({
layoutData: {left: 10, top: 10},
text: "Login"
}).on("select", function() {
localStorage.setItem('Login', "1".toString());
login.close();

}).appendTo(login); `
Still show me the error :(

**Comment by cookieguru** [comment]
This snippet works for me:
```js
var about = new tabris.Page({
title: "About Us",
topLevel: true
});

var login = new tabris.Page({
title: "Login",
topLevel: true
});
new tabris.Button({


layoutData: {left: 10, top: 10},
text: "Login"
}).on("select", function() {
localStorage.setItem('Login', "1".toString());
login.close(); //dispose also works
}).appendTo(login);

about.open();
login.open();
```

---
If you open login before about, login will be on the bottom of the stack and can't be closed until about is closed.

[This article](https://tabrisjs.com/documentation/latest/ui) explains the page stack in detail.

**Comment by jokorivai** [comment]
And your error is.....?

**Comment by mpost** [comment]
Closing this issue for now. @jabedbd Fell free to reopen if you still have a problem.
