### ISSUE TITLE
Support widget border

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1016]
Styling sometimes involves borders. Currently a border can be achieved by e.g. nesting [`Composite`](https://tabrisjs.com/documentation/latest/api/Composite#composite)s in each other or drawing the border in a [`Canvas`](https://tabrisjs.com/documentation/latest/api/Canvas#canvas).

It would be handy to have an API on `Widget` to configure drawing a border with at least a certain width and color.

**Comment by mpost** [comment]
A general border on widgets is not very common on mobile platforms. Closing this for now.

**Comment by fax1ty** [comment]
Any news?

**Comment by mpost** [comment]
@fax1ty There is nothing to report and there are no plans to support this feature. It can be mimicked by other means if necessary.
