### ISSUE TITLE
Support widget padding

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1017]
In some layouts it is useful to offset the widget content inside it. Currently this can be done by wrapping the widget in a composite and adjusting the margins of the widget. Padding would be a more efficient way to achieve that, because it would involve a flatter layout and would require less code. This would also make layouts involving margins and padding more comprehensible because of the distinction between the two concepts.

**Comment by mpost** [comment]
We have discussed to add support for padding via a protocol property `padding`:

```js
padding: {
  left: number,
  top: number,
  right: number,
  bottom: number
}
```

The object always provides all sites that should be set. If a side is missing its value should remain unchanged. 

Getting the `padding` property returns a padding object containing all 4 sites with their current values as present on the native side.

**Comment by cpetrov** [comment]
Composite padding supported as of 2.1
