### ISSUE TITLE
Support hot replacement of code during development

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1018]
It would be useful to quickly be able to see consequences of code changes in the developer app without having to restart it. Such a feature would involve dynamically pushing changed code to the client and reloading only e.g. the currently shown screen. This can improve development experience for complex apps, where a long chain of interactions with the UI has to be executed before the target state being worked on is reached.

See also:
- [React Native: Hot Reloading](https://facebook.github.io/react-native/blog/2016/03/24/introducing-hot-reloading.html)
- [Android: Instant Run](https://developer.android.com/studio/run/index.html#instant-run)

**Comment by mpost** [comment]
Reloading an app after save is something that makes a lot of sense. We have a few ideas around it and want to bring that functionality into the https://github.com/eclipsesource/tabris-js-cli in the future.

**Comment by mpost** [comment]
While hot replacement is interesting, we can provide several app dev cycle improvements once we have a standing connection to the dev machines.
