### ISSUE TITLE
Passing intent extras through to a plugin (Android)

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#1019]
So I am having an issue with the plot projects plugin, a geofencing app, starting the app with extras in an intent. You can see the code here (https://github.com/Plotprojects/plot-phonegap-plugin/blob/master/src/android/PlotCordovaNotificationOpenReceiver.java#L12-L18). This code executes successfully and starts the app, problem is the extras never make it to the plugin for some reason. 

https://github.com/Plotprojects/plot-phonegap-plugin/blob/master/src/android/PlotCordovaPlugin.java#L495 This hits, but the intent "originalPlotIntent" is not in the bundle.

Its pretty hard to test independently because you need a plot account and a lot of configuration to get it to trigger, I was just wondering if you had any input on either the issue on your side, or how I can modify the plugin to play nice with tabris.

Thanks!

**Comment by mpost** [comment]
Am i correct in assuming that the BroadcastReceiver is invoked and than opens the Activity/Tabris app?

I think the catch is that while cordova only has one single activity, in Tabris.js we actually use that one activity to launch a second activity (the `TabrisActivity`) that hosts the Tabris app.

The intent passed to the initial activity is not passed along to the `TabrisActivity` to be consumed in https://github.com/Plotprojects/plot-phonegap-plugin/blob/master/src/android/PlotCordovaPlugin.java#L26.

In our `cordova-android` platform we ship a modified cordova class: bin/templates/project/Activity#startTabrisActivity The launch intent of that class should be merged with the newly created launch intent for the `TabrisActivity`.

**Comment by mpost** [comment]
With the above analysis in place we have update the `cordova-platform` to base the intent starting the `TabrisActivity` on the `Bundle` extras passed to the initial cordova `Activity`:

```java
Intent intent = new Intent( this, TabrisActivity.class );
intent.putExtras( getIntent().getExtras() );
...
```

We have updated the nightly build. Please give it a try and let us know if that helps you out.

**Comment by mpost** [comment]
Closing this as "fixed". Feel free to reopen if you still have problems.
