### ISSUE TITLE
Online build for 1.10.0 failed. Duplicate entry: okhttp3/internal/ws/WebSocketProtocol.class

### ISSUE THREAD

**Issue by sand123** [eclipsesource/tabris-js#1020]
Hi, I'm trying to build (online) app with 1.10.0 and got this error. Just changing to 1.9.0 - and build successfully

FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':transformClassesWithJarMergingForDebug'.
com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: okhttp3/internal/ws/RealWebSocket$1.class

I'd appreciate any help

**Comment by mpost** [comment]
We are shipping okhttp 3 with the tabris-android client already. Seams as if one of your plugins also ships the okhttp 3 library. Maybe even as "jar" and not as a maven dependency?

**Comment by sand123** [comment]
```xml
<plugin name="de.appplant.cordova.plugin.local-notification" />
<plugin name="uk.co.workingedge.phonegap.plugin.launchnavigator" />
<plugin name="com.peerio.cordova.plugin.clipboard" />
<plugin name="cordova-plugin-geolocation" />
<plugin name="cordova-plugin-x-toast" />
<plugin name="cordova-plugin-badge" />
<plugin name="cordova-plugin-vibration" />
<plugin name="cordova-plugin-network-information" />
<plugin name="cordova-plugin-actionsheet" />
<plugin name="cordova-plugin-dialogs" />
<plugin name="cordova-plugin-android-permissions" />
<plugin name="cordova-plugin-appversion" />
<plugin name="cordova-plugin-sim" />
<plugin name="cordova-plugin-file" />
<plugin name="cordova-plugin-email-composer" />
<plugin name="call-number" />
```

Well, I'll try to figure out which plugin exactly, but it seems very strange to me because they all not network connection related

**Comment by sand123** [comment]
This error caused by `uk.co.workingedge.phonegap.plugin.launchnavigator`
Looking for alternatives
