### ISSUE TITLE
When a web page is loaded in a web view, links with "target" attributes in the html open in default browser instead of the app.

### ISSUE THREAD

**Issue by newmediaone** [eclipsesource/tabris-js#1021]
I would like the ability to override opening links in a browser, so I can keep the user in the app. My preference would be to just open new window targeted links in the current web view.

To duplicate, cereals a simple app with a web view, then load a site that includes links with target tags, that open in a new browser window.  Clinking one of those links from within a tabris.js web view will open that link in the device's default browser instead of in the app's web view.

**Comment by cookieguru** [comment]
I believe [cordova-plugin-inappbrowser](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-inappbrowser/) has the ability to keep everything in the same WebView

**Comment by mpost** [comment]
The plugin linked by @cookieguru might help you there. In addition you could use the `WebView` `navigate` event to intercept page loading and set the url on the `WebView` directly.

https://tabrisjs.com/documentation/latest/api/WebView#navigate-widget-event

**Comment by mpost** [comment]
Closing this for now as several solutions have been outlined. Feel free to reopen if required.
