### ISSUE TITLE
Patch not being overwritten when redeploying

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#1023]
If I patch my app using the patch api, and then I subsequently redeploy the app using cordova run android, I noticed it does not overwrite the patch. The www seems to be the version in the patch rather than the version I just deployed. Now in practice this is not a problem, if its a known issue that you need to uninstall/clear app data for cordova run android/ios to work, so be it. My concern is with regards to the app store. If the user has a patched version, is it known whether or not an app store update will obliterate the patch properly? My fear is it does not do a full uninstall/clear app data before installing the new version, which will make it victim of the same issue. 

Any thoughts on this?

**Comment by mpost** [comment]
In general the patch mechanism is tied to the app version iirc. So a new update of the app itself should contain the latest version of your "patch app".

**Comment by dested** [comment]
Ah, this worked perfectly. 

Thanks!
