### ISSUE TITLE
is TabrisJs.com offline?

### ISSUE THREAD

**Issue by jokorivai** [eclipsesource/tabris-js#1024]
I visit tabrisjs.com and eclipsesource.com on daily basis, today I can't open bith of them? Are they offline? I am asking this to make sure no site is being blocked on my internet line. Thank you.

**Comment by dested** [comment]
I can access them from my location. A great site to ping to see the status is something like http://downforeveryoneorjustme.com/

**Comment by jokorivai** [comment]
Thanks @dested
I just tested and they are both online.
I opened them from my browser as usual and they work too. Thank you again.
