### ISSUE TITLE
Change event on transform

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#1025]
This is a bit of a duplicate of #627, but it would be extremely convenient to get the change event for transform property changes.

**Comment by mpost** [comment]
@dested Since the `transform` can only be changed by the developer you should be able to always intercept changes on it.

**Comment by mpost** [comment]
@dested That makes sense. We will consider this for a future update.

**Comment by cpetrov** [comment]
A change event is fired now (tested with Tabris.js 2.1) when animating a transformation: 

```js
const {Composite, ui} = require('tabris');

let composite = new Composite({centerX: 0, centerY: 0, width: 100, height: 100, background: 'red'})
  .on('transformChanged', ({value}) => {
    console.log(JSON.stringify(value));
  })
  .appendTo(ui.contentView);
composite.animate({transform: {rotation: Math.PI / 4}}, {duration: 1000});
```
