### ISSUE TITLE
Trigger App Reload From Server

### ISSUE THREAD

**Issue by newmediaone** [eclipsesource/tabris-js#1027]
This may sound incredibly lazy, but it could really save time and would be great if we could trigger an app reload from the server side.  NativeScript has a "Live Reload" option, which reloads the app anytime a JS file within the project is updated.  Fusetools does this by default.

Picture you are editing an app while testing on 4 devices.  An Android phone, an Android Tablet, an iPhone and an iPad.  Currently after making a change, to see your changes, you'd have to go to each device and swipe from the right, then hit the reload button.  If those apps would auto reload on file changes, that would save having to pick up and manually reload each device to see the changes.

It would also be helpful to monitor the progress of developers.  I could have the same 4 devices on my desk, and they would reload whenever the developer saved a file in the other room.  As the company owner, I could literally watch the dev process happening on my desk on 4 devices without having to touch a thing.

So, I know it's not about the competition, but this is a feature I miss from other platforms, and would love to see this option added.

**Comment by cookieguru** [comment]
See #1018

**Comment by mpost** [comment]
Reloading an app after save is something that makes a lot of sense. We have a few ideas around it and want to bring that functionality into the https://github.com/eclipsesource/tabris-js-cli in the future.

**Comment by dalisoft** [comment]
@mpost @eclipsesource Is this feature implemented?

**Comment by dalisoft** [comment]
I am starting learn tabris.js and it's amazing even i use `JSX`. I need live-reload because in minute i change(add,remove) 10+ line of code and tired from reload from server on every update

**Comment by cookieguru** [comment]
@dalisoft No, live reload is not currently implemented

**Comment by ralfstx** [comment]
Closing as dup of #1018.
