### ISSUE TITLE
Build jobs are all stalled

### ISSUE THREAD

**Issue by irbull** [eclipsesource/tabris-js#1030]
Currently, all build jobs on tabrisjs.com (both our production and staging servers) are stalled. This is due to a change in the travis-ci Webhook API. https://blog.travis-ci.com/2016-08-31-webhook-delivery-changes 

I'm filing this bug to track this issue.

**Comment by jonek** [comment]
For the moment we found a workaround. The builds should be working as expected again. Particularly the notifications should change the status of a build from "running" to "passed" again.

**Comment by jonek** [comment]
There are probably some builds that are stuck in state "running". If you have such builds that never stop, please report them here.

**Comment by Gregivy** [comment]
I have. Do I need to tell app IDs?

**Comment by mpost** [comment]
@Gregivy They ids are only accessible for you so it is safe to post them here.

**Comment by mknauer** [comment]
@fwaibel Isn't it possible to go through the database and look for all "still running" builds and mark them as failed?

**Comment by fwaibel** [comment]
@mknauer Yes, I marked all builds failed.

**Comment by mpost** [comment]
Problem has been resolved with an improved travis integration
