### ISSUE TITLE
Patching doesnt work on iOS with Tabris 1.10.0

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#1031]
I am unable to patch my app on ios using 1.10.0. Calling `tabris.app.installPatch` with a url that works on android never files a callback on iOS. I am testing on iOS 10. Nothing is outputted to either the tabris or xcode console.

**Comment by patrykmol** [comment]
Hello. Unfortunately we had to remove zip library that we used internally. This library was also used for patch feature which is the reason why it does not work. We will look into restoring this.

**Comment by dested** [comment]
Hey guys, just pinging on this one. Is this still on track to be reimplemented in some form, either with or without compression?

**Comment by patrykmol** [comment]
Hello. We have restored this functionality. It is available in nightly.
