### ISSUE TITLE
Ability to scroll tabs titles on Multiple tabs

### ISSUE THREAD

**Issue by iteearmah** [eclipsesource/tabris-js#1032]
I will like to be able to scroll the title often the tabs in the tabfolder when I have lots of tabs.

**Comment by cookieguru** [comment]
Just to confirm, you're referring to this behavior?

https://material-design.storage.googleapis.com/publish/material_v_9/0B6Okdz75tqQscHVOR1FVV2JjQms/components-tabs-typesoftabs_scrollable_tabs_01_xhdpi_003.mp4

**Comment by iteearmah** [comment]
Yes that's it.

**Comment by iteearmah** [comment]
hi...any input on the above issue

**Comment by mpost** [comment]
@iteearmah yes. we will introduce an Android only property that allows you to switch between the "fixed" and "scrollable" mode.

**Comment by jokorivai** [comment]
@mpost sounds great!

**Comment by mpost** [comment]
We have implemented a property `tabMode` on the `TabFolder` that can have the values `fixed` (default) and `scrollable` for the 2.0 release.
