### ISSUE TITLE
Migrate Video widget API introduced in 1.10 to the 2.x stream

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1035]

**Comment by cpetrov** [comment]
Implemented in Android and JS. iOS pending.

**Comment by natanraj** [comment]
@cpetrov  Does it have relation to the issue #1221

**Comment by mpost** [comment]
@natanraj no. the api is consistent for both releases.

**Comment by ralfstx** [comment]
The new Video API is available in 2.0.
