### ISSUE TITLE
Question: How to use underscore in tabris?

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1037]
Tried this in scratchpad app... 

var _ = require('underscore'); 
says 'Cannot find module underscore'

**Comment by gosia-eclipsesource** [comment]
@natanraj This can't be done with the scratchpad, but you can set up and run a project as described [here](https://tabrisjs.com/documentation/latest/getting-started) and include a dependency of the npm module (e.g. `"underscore": "^1.8.3"`) in the package.json before running `npm install`.

**Comment by cookieguru** [comment]
Sounds the same as #1026

**Comment by cpetrov** [comment]
Integration with [RunKit](https://runkit.com/home) may be possible

**Comment by ralfstx** [comment]
The scratchpad is meant for beginners to try out simple code snippets. We currently don't have plans to turn it into an online Tabris IDE (although that would be nice).
