### ISSUE TITLE
ScrollView with direction "both"

### ISSUE THREAD

**Issue by ungerenne** [eclipsesource/tabris-js#1039]
The ScrollView allows its content to overflow either vertically or horizontally.
Is it possible to have both at the same time?
I would like to zoom into a canvas by using touch gestures to resize it and scroll in all directions.

**Comment by cookieguru** [comment]
Currently it is not possible to do both.  The only workaround is to put one inside another.  However with this approach it is only possible to scroll in one direction at a time; i.e. not diagonally.  Panning in both directions at a time is possible but must be done in an "L" motion.

There's a decent workaround in https://github.com/eclipsesource/tabris-con/commit/1415e66edece1698a940745f90708e260c93db13

Zooming on an `ImageView` is tracked in #775

**Comment by mpost** [comment]
@ungerenne When you want to pinch to zoom on a canvas you can create a custom implementation for that base on touch events.

**Comment by tbuschto** [comment]
There are quite a few ways around this:
 * ScrollView-in-ScrollView
 * Create an image and place it in a zoom enabled ImageView
 * use a web view

I will therefore close this issue due to inactivity. Please re-open if you disagree.
