### ISSUE TITLE
Some values for "keyboard" in a TextInput of type "password" result in incorrect behaviour

### ISSUE THREAD

**Issue by dbuschtoens** [eclipsesource/tabris-js#1040]
With keyboard set to "ascii" or "url", there are no word suggestions, but the text on the input remains visible.
With keyboard set to "e-mail", the text is correctly hidden, but word suggestions appear on the keyboard.

Tested on: Galaxy Tab A, Android 6.0.1

**Comment by mpost** [comment]
@dbuschtoens  I don't fully understand the issue. Could you please provide a snippet?

**Comment by avianey** [comment]
```javascript
const {TextInput, ui} = require('tabris');

new TextInput({
  top: 25, left: '20%', right: '20%',
  message: 'default'
}).appendTo(ui.contentView);

['ascii', 'decimal', 'number', 'numbersAndPunctuation', 'phone', 'email', 'url'].forEach((mode) => {
  new TextInput({
    top: 'prev() 10', left: '20%', right: '20%',
    keyboard: mode,
    message: mode,
    type: 'password'
  }).appendTo(ui.contentView);
});
```

when using `type:'password'` along with `keyboard:'ascii'||'url'` then the text is not hidden using bullet like a regular password field...

enforcing `setType` after `setKeyboard` fix things but then we lost the `monospace` text formatting for the url and ascii `message` placeholder.

![screenshot_20170901-202113](https://user-images.githubusercontent.com/1625652/29982822-8767de48-8f53-11e7-8c44-03bc7b74bc40.png)

**Comment by irbull** [comment]
This has been fixed in the android client by @avianey
