### ISSUE TITLE
local build iOS Xcode fails SRWebSocket _innerPumpScanner 

### ISSUE THREAD

**Issue by frh3ddy** [eclipsesource/tabris-js#1041]
Im using Tabris.js 1.10.0 Cordova Platform
and Xcode 8.1

Im not using web sockets 

![screen shot 2016-11-17 at 2 05 05 pm](https://cloud.githubusercontent.com/assets/7991939/20404034/26c3b6c6-acd1-11e6-858c-a236f708f5e5.png)

**Comment by patrykmol** [comment]
Try adding `icucore` library to the project.

**Comment by frh3ddy** [comment]
thanks @patrykmol it works now

**Comment by mpost** [comment]
Closing as "resolved".
