### ISSUE TITLE
Question  - how to do intents launch?

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1042]
If i have to launch a browser or call or Message intent.. how to do it .on('tap', .. )event?

**Comment by cookieguru** [comment]
Use [cordova-plugin-inappbrowser](https://github.com/apache/cordova-plugin-inappbrowser) with `http(s):` `tel:` or `sms:` links.

**Comment by natanraj** [comment]
sorry, i didn't understand this better. Can you please give a small sample ? 

I heard inapp browser is to open the app within same hybrid webview.

**Comment by cookieguru** [comment]
#716
