### ISSUE TITLE
Notifications when app is neither in background nor running

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1044]
Hi. not sure, if it is a tabris.js issue. When i am running a app to show local / push notification, it is able to show up that notification. (I use Cordova plugin for both). But when the app is forceclosed / not-running, the scheduled notification / push notification doesn't popup. Is it something you heard across ? How to prevent this issue?
(Android 6 on Xiaomi Device)

**Comment by mpost** [comment]
@natanraj which plugin are you using?

**Comment by jokorivai** [comment]
@natanraj  CMIIW. Cordova Notification plugin use service to handle notification. If your app was forced close, so was the service. On Xiaomi devices (MIUI, as I one use), forced apps (along with their servics) will not be restarted unless you enable them to be autostarts.

Check for them in MIUI Security App, 
![mi_20161122_181044](https://cloud.githubusercontent.com/assets/11798147/20519832/6fc47560-b0df-11e6-8534-54158a9783e1.jpg)
 here:

**Comment by natanraj** [comment]
@jokorivai Thanks for this. I went and checked this settings. You are right, all of them are turned off except Whatsapp. Any idea how to manifest level changes will ensure than we expect the end user to change it himself ?

**Comment by natanraj** [comment]
@mpost I use both the cordova plugins from cordova-plugin-local-notifications & phonegap-plugin-push from official directory.

**Comment by jokorivai** [comment]
@natanraj this is MIUI custom ROM feature, not androids, so there is no other way to handle this I'm afraid. 
May be useful to inform your user about this.

**Comment by natanraj** [comment]
@jokorivai so sad.. How do then other apps receive notification even when they're not set. For example. All the mail clients receive notification though they don't have this permission turned on..

**Comment by jokorivai** [comment]
Mail daemons are system service, they cannot be disabled by MIUI. So are SMS/Text and Phone service. 
You can chech [here](http://en.miui.com/forum.php) for more info.

**Comment by natanraj** [comment]
@jokorivai Does it mean in Business to Customer type of apps, aren't there any other workaround ?

**Comment by mpost** [comment]
Closing this issue for now as it likely not relates to tabris.js directly. Please reopen if the problem remains.
