### ISSUE TITLE
WebSocket is missing EventTarget API

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#1047]
The W3C spec (https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) says that WebSocket inherits from EventTarget (https://developer.mozilla.org/en-US/docs/Web/API/EventTarget), adding addEventListener, etc. Right now we don't do that, only the 'onxxx' listener fields are supported.

I consider this a bug since it is highly unexpected.

**Comment by ralfstx** [comment]
Fixed in 7090d788d39d76b4b8a609e7b0b5490110e34d08
