### ISSUE TITLE
Question : How to change the color of RadioButton and border of TextInput on focus

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1048]
Default it is showing material green color, though i tested with tabris.ui.set('background', 'red'); also tried textColor on radioButton.

**Comment by mpost** [comment]
Currently you can not set the color of the RadioButton. Only of its background. If you want to colorize the items globally you can create a custom theme that applies colors to the views. See http://eclipsesource.com/blogs/2015/07/03/tabris-js-1-1-sneak-peak-custom-themes-on-android/

**Comment by natanraj** [comment]
@mpost Thanks for the info ...I will try this soon.
