### ISSUE TITLE
Question - Info on cordova version used now

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1049]
For fixing a force-start  issue in Push Notification, i am referring here. It  mentions about this fix is available post cordova 6.0 onwards [https://github.com/phonegap/phonegap-plugin-push/blob/256f28fa08da4aab9691d628a3150022b67da02d/docs/PAYLOAD.md#application-force-closed](https://github.com/phonegap/phonegap-plugin-push/blob/256f28fa08da4aab9691d628a3150022b67da02d/docs/PAYLOAD.md#application-force-closed)

Any help on how can I know the cordova version used in our Cloud build is very much appreciated

**Comment by jonek** [comment]
@natanraj go to one of your cloud builds, click on the link the one of the build (build number, timestamp) and then follow the "Detailed Log" button. In the output you can look for "npm install -g cordova" which will tell you something like:
```$ npm install -g cordova@6.2.0```

**Comment by natanraj** [comment]
@jonek   Thanks Johannes. It helps
