### ISSUE TITLE
Prevent the white screen on App Load

### ISSUE THREAD

**Issue by iteearmah** [eclipsesource/tabris-js#1051]
Is there a way to prevent the first white screen the appears when the App is launched

**Comment by mpost** [comment]
Currently this is the screen you see when first launching the app and the js vm loads. What would you like to do with it?

**Comment by iteearmah** [comment]
to customize it like a splash screen

**Comment by cookieguru** [comment]
https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-splashscreen/

**Comment by iteearmah** [comment]
it seems the splashscreen loads when the app is already loaded.

**Comment by iteearmah** [comment]
I wish we can add an image property to that particular white screen.

**Comment by mpost** [comment]
Rather without a plugin similar to how the ios cordova build allows to provide splash screens.

**Comment by iteearmah** [comment]
Yeah....something without a plugin

**Comment by iteearmah** [comment]
Or is there a way to hide that white screen?

**Comment by mpost** [comment]
the white screen is the apps actvity while your the js vm and your app get loaded so showing a custom icon in the style of https://material.google.com/patterns/launch-screens.html makes sense.

**Comment by iteearmah** [comment]
Hoping the Team added that function soon...really need it.

**Comment by mpost** [comment]
@iteearmah In general, if your load times are so long that you see the white screen for a long time (in a production app where the sources are bundled) you should consider to modularize  your app more.

**Comment by iteearmah** [comment]
Ok....Will do that then

**Comment by mpost** [comment]
We have added Android support for the `<splash ..>` element in the `config.xml`. Here is how you can use it:

```xml
<platform name="android">
  <splash src="res/android/drawable-xxxhpdi/splash.png" density="xxxhdpi"/>
  <splash src="res/android/drawable-xxhpdi/splash.png" density="xxhdpi"/>
  ...
</platform>
```

The `src` path and file name is relative to the `config.xml`. It can be any arbitrary path and file name. The `density` attribute has to be the name of an Android [drawable bucket](https://developer.android.com/guide/practices/screens_support.html#qualifiers) (without the leading `drawable-`). The image you provide is actually shown as a "type of app icon". See [material guidelines ](https://material.google.com/patterns/launch-screens.html) for further styling details.

The image you provided is shown on a light background. This can currently not be shown in the Tabris.js 1.x stream. In the Tabris.js 2.x stream you are able to provide a custom theme in the `config.xml` that controls the splash screen appearance. being able to configure your theme also allows you to create a splash screen with a dark background:

```xml
<platform name="android">
  <!-- Set dark splash screen -->
  <preference name="ThemeSplash" value="@style/Theme.Tabris.SplashScreen" />
</platform>
```

The available splash base themes in Tabris.js 2 are:
- `@style/Theme.Tabris.SplashScreen` (dark theme)
- `@style/Theme.Tabris.Light.SplashScreen` (light theme)

Support for the `<splash .. />` Is available in the 1.x and 2.x nighties. Please let us know how it works out for you.

**Comment by mpost** [comment]
Closing as implemented

**Comment by maoamid** [comment]
@mpost this implementation require `cordova plugin add cordova-plugin-splashscreen` for android and ios?

**Comment by cookieguru** [comment]
@maoamid No
