### ISSUE TITLE
Page icon does not auto resize

### ISSUE THREAD

**Issue by iteearmah** [eclipsesource/tabris-js#1052]
var page = new tabris.Page({
  title: 'App Title',
  icon:'images/icon.png',
  topLevel: true
});

**Comment by mpost** [comment]
The page icon is not supposed to be confined to the Toolbar height. You should provide a fitting icon.

**Comment by iteearmah** [comment]
Just hoping the height of the toolbar is the same on most screens

**Comment by iteearmah** [comment]
I get you now..
