### ISSUE TITLE
Support native resolution for drawing in canvas

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#106]
[There are ways](http://www.html5rocks.com/en/tutorials/canvas/hidpi/) to support drawing in native pixels in HTML5 canvas. [Chart.js](https://raw.githubusercontent.com/nnnick/Chart.js/master/Chart.js) includes the following function that is now executed due to the availability of `window.devicePixelRatio`:

``` javascript
var ctx = chart.ctx,
    width = chart.canvas.width,
    height = chart.canvas.height;
if (window.devicePixelRatio) {
  ctx.canvas.style.width = width + "px";
  ctx.canvas.style.height = height + "px";
  ctx.canvas.height = height * window.devicePixelRatio;
  ctx.canvas.width = width * window.devicePixelRatio;
  ctx.scale(window.devicePixelRatio, window.devicePixelRatio);
}
```

**Comment by tbuschto** [comment]
The windows client already supports this. Here is an example how to use it:

```
new tabris.Canvas({
  left: 10, top: 10, right: 10, bottom: 10
}).on('resize', function({target, width, height}) {
  var contextWidth = tabris.device.scaleFactor * width;
  var contextHeight = tabris.device.scaleFactor * height;
  var ctx = target.getContext('2d', contextWidth, contextHeight);
  draw(ctx);
}).appendTo(page);
```

The difference is in the interpretation of `target.getContext('2d', contextWidth, contextHeight)`. 

On iOS and Android these last two properties only limit the drawing area on screen, and the context coordinate system always maps to 1:1 to DIPs. However, the actual rendering is then in native pixels, which looks good on screen most of the time.

On Windows the the on screen drawing area is only limited by the size of the canvas widget. The `contextWidth`and `contextHeight` are used to define how the context coordinate system maps to DIPs. To put it another way, the canvas size defines what visual size the drawing area has, and the context size defines what numeric size it has.

The benefit of this approach is that you can draw on different resolutions that the screen. You could draw at lower resolution to speed up performance and save memory, but you could also draw on higher resolutions to get bigger `ImageData` or "zoom-in" the canvas with `transform`.

**Comment by capotti** [comment]
put this in the docu - that's great!

**Comment by mpost** [comment]
As an addition to the above statement: This updates _canvas.js_ snippet should draw the same content as before but the copy/pasted image data graphics should now be rendered crisp:

```js
const {Canvas, ui} = require('tabris');

// Draw shapes on a canvas using HTML5 Canvas API

const density = tabris.device.scaleFactor;

new Canvas({
  left: 10, top: 10, right: 10, bottom: 10,
}).on('resize', ({target: canvas, width, height}) => {
  let contextWidth = density * width;
  let contextHeight = density * height;
  let ctx = canvas.getContext('2d', contextWidth, contextHeight);
  ctx.strokeStyle = 'rgb(78, 154, 217)';
  ctx.lineWidth = 10 * density;
  ctx.moveTo(20 * density, 20 * density);
  ctx.lineTo(contextWidth - 40 * density, contextHeight - 40 * density);
  ctx.stroke();

  // draw image
  ctx.putImageData(createImageData(80 * density, 40 * density), 100 * density, 100 * density);

  // copy region
  let data = ctx.getImageData(0, 0, 100 * density, 100 * density);
  ctx.putImageData(data, 180 * density, 100 * density);

}).appendTo(ui.contentView);

function createImageData(width, height) {
  let array = [];
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      let alpha = x % (20 * density) > y % (20 * density) ? 255 : 0;
      array.push(200, 0, 0, alpha);
    }
  }
  return new ImageData(new Uint8ClampedArray(array), width, height);
}

```

**Comment by mpost** [comment]
The Android client has a change standing by but we need to push the update together with ios.

**Comment by tougbia09** [comment]
Hi, is it possible to draw image on tabris canvas ?
i still trying to use local .svg image as pattern to fill a canvas portion with this snippet(works in browser)  

           `var img = new Image();  
            img.src = 'assets/imagename.svg';  
            var pattern = ctx.createPattern(img, 'no-repeat');
            ctx.fillStyle = pattern;
            ctx.fillRect(x, y, width, height);`
and i get this --- ReferenceError: Image is not defined .
And I guess that createPattern function will don't  work either.

some snippet to display png,jpeg or base64 local image in tabris.canvas will be useful
any help please!!!

**Comment by ralfstx** [comment]
@tougbia09 This is the wrong place to ask questions. You can ask on [StackOverflow](https://stackoverflow.com/questions/ask?tags=tabris) or [Slack](https://tabrisjs.herokuapp.com/).

**Comment by mpost** [comment]
iOS has implemented proper context size fitting to the canvas. Closing this issue as this behavior is aligned throughout the platforms.
