### ISSUE TITLE
'Back' button text not localized

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1061]
On iOS, when the title of the previous page is too long, the text _Back_ is shown instead of the page title. We should provide a way to localize this text.

![img_0944](https://cloud.githubusercontent.com/assets/2341769/20899644/829634ac-bb2b-11e6-9e94-8c7c4c1868e7.PNG)

**Comment by karolszafranski** [comment]
Buttons "Done", "Back", "Cancel", etc. are coming (almost always) from native UI controls, and this strings are not customizable, it's not possible to change them (directly).

However those strings are localizable, and localization have to be done by specifying languages supported by app. This are build time parameters, and can be specified using a plugin like this: https://github.com/escapedcat/cordova-plugin-localization-ios

If you add german as one of the languages supported by your app, and user running your app will have german language set on his iOS device, "Back" will be automatically changed to "Zurück".
