### ISSUE TITLE
How to  Use  2.x nightly in local builds

### ISSUE THREAD

**Issue by iteearmah** [eclipsesource/tabris-js#1066]
How do I set my package.json file to Use 2.x nightly

**Comment by mpost** [comment]
You can use:

```js
  "dependencies": {
    "tabris": "https://tabrisjs.com/downloads/nightly-2.x/tabris.tgz"
  }
```

but the apis are still in flux.

**Comment by iteearmah** [comment]
I want to use the tabFolder scroll badly :-)

**Comment by mpost** [comment]
rightly so 👍

**Comment by mpost** [comment]
We have not migrated the examples yet but the snippets are compatible with the current 2.x state in `master`.

**Comment by maoamid** [comment]
there are some native tabris platform for use on cordova platform add?

**Comment by mpost** [comment]
`cordova platform add tabris-android` will work the same way in 2.x as it did in 1.x. Please stay tuned for a 2.x beta release shortly.

**Comment by maoamid** [comment]
@mpost Great news, appreciate your work. 

Just for the state, on local build I got:
Version mismatch: JavaScript module "tabris" (version 2.0.0) is incompatible with the native tabris platform. Supported module versions: 1.0 to 1.10
and then a bunch of warnings on create tabris objects(UI, Composite etc.) and error:
TypeError: tabris.registerType is not a function at ./cordova.js:1555:14 at Tabris.Object.assign etc...

**Comment by mpost** [comment]
@maoamid That is expected since we haven't published any official 2.x platforms to download. If you are curious you can use the tabrisjs.com build service to create a 2.x build from nightly.

**Comment by maoamid** [comment]
@mpost  This is how I use now, thank you for the hint, no problem.
