### ISSUE TITLE
Canvas Test is slow on iOS 9.3.3

### ISSUE THREAD

**Issue by LiuHongtao** [eclipsesource/tabris-js#1067]
We create an app to test canvas apis. Its fine on HM Note 1S with Android 4.4.4, but is slow on iPhone 6 with iOS 9.3.3. 

The test code.

```
var example = new Example();

var page = new tabris.Page({
  topLevel: true,
  title: "my app
});

new tabris.Canvas({
	layoutData: {left: 10, top: 10, right: 10, bottom: 10}
}).on("resize", function(canvas, bounds){
  	var ctx = canvas.getContext("2d", bounds.width, bounds.height);
  	example.init(cox);
}).appendTo(page);

new tabris.Button({
  layoutData: {left: 10, top: 10},
  text: "Button"
}).on("select", function() {
  	var start = new Date().getTime(); 
	example.draw();
	var end = new Date().getTime(); 
	console.log(end - start);
}).appendTo(page);

page.open();

function Example(){
	var ctx, width, height, cx, cy, unit;
	this.init = function(newCtx){
		ctx = newCtx;
		width = ctx.canvas.width;
		height = ctx.canvas.height;
		ctx.font = "18px sans-serif";
		cx = Math.floor(width / 3);
    	cy = Math.floor(height / 2);
    	unit = width / 12;    	
	}

	function mRandom(num){
    	return parseInt(Math.random()*num+1);
	}

	this.draw = function draw(){
		ctx.clearRect(0, 0, width, height);

		for(var i = 0; i < 1000; i ++){
			var x = mRandom(width);
		    var y = mRandom(height);

		    ctx.beginPath();
		    ctx.moveTo(x, y);
		    ctx.lineTo(x + 300, y);
		    ctx.closePath();
		    ctx.rect(x, y, 20, 20);
		    ctx.arc(x, y, 2, 0, 360, false);
		    ctx.stroke();
		}
	}
}
```

**Comment by mpost** [comment]
There are some known performance limitations on ios in regards to canvas operations. calling many distinct operations can lead to performance degradation. We have solved these issues on Android and will also remedy them on iOS.

**Comment by mpost** [comment]
Tabris.js uses j2v8 on Android but on iOS the internal JSCore library is used in Tabris.js. V8 does not run on iOS due to some limitations when running native code on iOS.

What JNI problem are you referring to?

**Comment by LiuHongtao** [comment]
In my framework, each JS Canvas method invocation will call a Java method via JNI, which slow down the process. As code below, it makes 7000 times JNI call. 

```
for(var i = 0; i < 1000; i ++)  {
    var x = mRandom(width);
    var y = mRandom(height);

    ctx.beginPath();
    ctx.moveTo(x, y);
    ctx.lineTo(x + 300, y);
    ctx.closePath();
    ctx.rect(x, y, 20, 20);
    ctx.arc(x, y, 2, 0, 360, false);
    ctx.stroke();
}
```

Maybe my design problems. "Batch callbacks for better JNI performance" were mentioned in [J2V8-A Highly Efficient JS Runtime For Java](https://www.eclipsecon.org/na2015/sites/default/files/slides/J2V8_0.pdf), so I thought it was figured out in Tabris.js or J2V8.

**Comment by mpost** [comment]
That is correct. On Tabris.js Android we batch the calls together, reducing the number of JNI calls. On iOS that is not (yet) happening.
