### ISSUE TITLE
Keyboard popup performance

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#1071]
I am experiencing my app crawling on android when I pop open the keyboard. I believe this is due to the number of widgets I have on the page, all forcing the resize event at once. It just so happens on this page I do not want to redraw anything on resize. What are your thoughts on a page/widget level property to disable reflow in the event of a resize. It may not be the desired behavior in all cases, but in this one it definitely is.

Thoughts?

**Comment by mpost** [comment]
The Android client behaves differently when your content is inside a scroll view. Maybe you could try that.

Also when layouting is slow, that is usually due to the fact that you are nesting your layouts very deeply. Try to avoid that if possible.

**Comment by mpost** [comment]
Closing this one as we know always resize the tabris.ui.contentView when the keyboard opens.
