### ISSUE TITLE
Nested composites produce wrong layouts on android

### ISSUE THREAD

**Issue by dbuschtoens** [eclipsesource/tabris-js#1074]
When two composites are nested and the inner composite defines its layout using the margin properties top, left, right or bottom to set the margin relative to the outer composite, any margin property that is used on the inner composite but not on the outer causes the outer composite to be laid out as if it were set to 0.
The following snippet shows that behaviour:
```
var outer = new tabris.Composite({
  left: 50, top: 50, background: "rgba(255,0,0,0.1)"
}).appendTo(page);
 var inner = new tabris.Composite({
   top: 5, left: 5, right: 5, bottom: 5, background: "rgba(0,0,255,0.1)",
 }).appendTo(outer);
var textbox = new tabris.TextView({
  left: 5, right: 5, top: 5, bottom: 5,
  text: "asdf"
}).appendTo(inner);
```
The intended layout is a text with two colored squares that are just big enough for the text to fit into with the outer square being 5 dips larger in every direction. The actual result has the text and the upper left corner of the squares in the desired location with the lower right corner of the outer square extended into the lower right corner of the page because right and bottom are defined on the inner composite but not on the outer.
On iOS the layout works as desired.

**Comment by mpost** [comment]
Interestingly this bug applies only to composites nested in composites. Another view type inside a composite does not make the parent composite span the available width.

**Comment by mpost** [comment]
Works as intent on Tabris.js RC2.

**Comment by mpost** [comment]
![screenshot_1497442989](https://user-images.githubusercontent.com/73655/27131890-0419d944-510d-11e7-9a90-6c041b0000a1.png)
