### ISSUE TITLE
android video fullscreen not working

### ISSUE THREAD

**Issue by gacal** [eclipsesource/tabris-js#1076]
hi
android video fullscreen mode not working

![screenshot_20161227-003025](https://cloud.githubusercontent.com/assets/3254134/21487157/9bb7d6e2-cbcb-11e6-9c87-9b8b21b2cdb2.png)

**Comment by mpost** [comment]
The video widget does not have a fullscreen mode. If you want your video to be fullscreen you will have to lay it out to cover the entire screen.

**Comment by gacal** [comment]
this screen layoutData:{left:0:right:0:top:0:bottom:0}
How should I set it up? @mpost

**Comment by cookieguru** [comment]
[`tabris.ui.displaymode`](https://tabrisjs.com/documentation/latest/api/ui#displaymode)

**Comment by gacal** [comment]
When I add the video object to the page, the full screen feature is distorted
```javascript
tabris.ui.set("displayMode", "fullscreen");
tabris.ui.set("toolbarVisible", false); // hide original actionbar

var page = new tabris.Page({
    title: 'Paging',
    topLevel: true,
    style: ["FULLSCREEN"]
});
var video = new tabris.Video({
    url: 'MP4 file',
    controlsVisible: true,
    layoutData: {left: 0, right: 0, top: 0, bottom: 0}
}).appendTo(page);

page.open();
```
![screenshot_20161229-120148](https://cloud.githubusercontent.com/assets/3254134/21540288/020020e8-cdb7-11e6-811a-fb2b2d653d2e.png)

**Comment by gacal** [comment]
deleted style flag but not working
Same screen

**Comment by maoamid** [comment]
Hi @mpost. In v2.x is planned a full screen future on video widget? I tried to implement that too using layouts, but is so unnaturally.

**Comment by cookieguru** [comment]
@maoamid Do you have a snippet of your implementation?

**Comment by maoamid** [comment]
right now no, because I quit trying on december 2016. I still need it for a foundation I work for. For them the video assets is a key one in their app, and a big part of theirs videos are store on youtube, so also without a youtube api integration I choose to delayed it that work to a upcoming version on my app. So long story short, for now I use a jwplayer iframe in a webview. Maybe I find time in a few days to try again, and post a snippet here to discuse. One note: the other problem I had was that the custom controls cannot be set as a "child" widget on video one, so on different layouts, the controls was misplaced, because the video size was mostly dynamic.

**Comment by mpost** [comment]
@maoamid a snippet showing your problem would definitely be helpful.

With the upcoming Tabris.js 2 release creating fullscreen UIs will also be simplet as we decouple the tabris.ui concept into a standalone widget.

**Comment by maoamid** [comment]
It is possible for tabris.device to have a set orientation property? if we I want to force a reorientation? or the contentView can be rotate?

**Comment by mpost** [comment]
You can fix your apps orientation via the cordova preference `Orientation`. https://cordova.apache.org/docs/en/latest/config_ref/index.html

**Comment by maoamid** [comment]
is the possible to make the [https://github.com/apache/cordova-plugin-screen-orientation](https://github.com/apache/cordova-plugin-screen-orientation) to work in tabris?
In v2 beta is not working, it seems not read/set properly to window.screen object

**Comment by mpost** [comment]
@maoamid While quickly looking over the code of the `cordova-plugin-screen-orientation` plugin, i don't see a reason why it shouldn't work. Do you see any errors?

**Comment by maoamid** [comment]
no, I got no errors on build, but screen.orientation return always unknown.

**Comment by mpost** [comment]
That would imply that the plugin is not properly registered. Is the `screen` object or the `orientation` object _undefined_? Could you show your config.xml entry where you include the plugin?

**Comment by maoamid** [comment]
<plugin name="cordova-plugin-screen-orientation" spec="~1.4.2" />

**Comment by maoamid** [comment]
yes, the screen object is undefined,
in cordova .xml I just include the plugin with:
<plugin name="cordova-plugin-screen-orientation" spec="~1.4.2" />

**Comment by mpost** [comment]
That means the plugin is not available during runtime. Do you get any errors in your build output log? It might be related to the `~` in your spec.

You could also try the concrete latest version:

```xml
<plugin name="cordova-plugin-screen-orientation" spec="1.4.3" />
```

**Comment by maoamid** [comment]
`<plugin name="cordova-plugin-screen-orientation" />` build without error only if no spec defined at all but the screen object remain undefined.

**Comment by mpost** [comment]
@maoamid In general you should provide a version to not break on updates of the plugin. Since 1.4.3 is on npm that should be picked up as expected. At that point we would need to try it out ourselves to see if it works or not.

**Comment by maoamid** [comment]
@mpost thank you for helping me. I tested using spec in clear, and the result is the same: orientation is unknown (v2 beta1 and nightly )

**Comment by maoamid** [comment]
about screen object on v2 beta1 version:
propertyName in screen return: lockOrientation, unlockOrientation and orientation.
working: `screen.lockOrientation('landscape');`
working: `screen.unlockOrientation();`
not woking: `screen.orientation return always unknown

Notice: On cordova screen orientation readme [https://github.com/apache/cordova-plugin-screen-orientation/blob/master/README.md](url) the methods names changed a few weeks ago:
`// set to either landscape`
`screen.orientation.lock('landscape');`

`// allow user rotate`
`screen.orientation.unlock();`

**Comment by Liberateur** [comment]
Install doesn't work for me :(... Do you have ideas ?
```
$ cordova plugin add cordova-plugin-screen-orientation
> Installing "cordova-plugin-screen-orientation" for android
> ANDROID_HOME=/Users/xxx/Library/Android/sdk
> JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home
> Failed to install 'cordova-plugin-screen-orientation':Error
>     at Object.module.exports.check_gradle (xxx/cordova/platforms/android/cordova/lib/check_reqs.js:90:25)
>     at GradleBuilder.prepEnv (xxx/cordova/platforms/android/cordova/lib/builders/GradleBuilder.js:161:23)
>     at Api.module.exports.runClean (xxx/cordova/platforms/android/cordova/lib/build.js:131:20)
>     at xxx/cordova/platforms/android/cordova/Api.js:394:50
>     at _fulfilled (xxx/cordova/platforms/android/cordova/node_modules/q/q.js:834:54)
>     at self.promiseDispatch.done (xxx/cordova/platforms/android/cordova/node_modules/q/q.js:863:30)
>     at Promise.promise.promiseDispatch (xxx/cordova/platforms/android/cordova/node_modules/q/q.js:796:13)
>     at xxx/cordova/platforms/android/cordova/node_modules/q/q.js:604:44
>     at runSingle (xxx/cordova/platforms/android/cordova/node_modules/q/q.js:137:13)
>     at flush (xxx/cordova/platforms/android/cordova/node_modules/q/q.js:125:13)
> Error: Could not find gradle wrapper within Android SDK. Might need to update your Android SDK.
> Looked here: /Users/xxx/Library/Android/sdk/tools/templates/gradle/wrapper
```

**Comment by cookieguru** [comment]
@Liberateur Are you using Cordova to do a [local build](https://tabrisjs.com/documentation/latest/local-build)?  If so, I would heed the error and update your Android SDK.

If you are using the Tabris.js cloud build, just add the following to your [`config.xml`](https://tabrisjs.com/documentation/latest/build#the-configxml) and run a build:
```xml
<plugin name="cordova-plugin-screen-orientation" version="1.4.3" />
```

**Comment by Liberateur** [comment]
I use cordova for build and right i just update Android SDK, really thanks ! <3

**Comment by mpost** [comment]
Closing this one as resolved. Please reopen if necessary.
