### ISSUE TITLE
Getting Access Denied from AWS when attempting to download build

### ISSUE THREAD

**Issue by wilsonna** [eclipsesource/tabris-js#1080]
I'm getting the following error after clicking on the download links for my cloud builds which I did today. I'm still able to download past builds.

```
<Error>
    <Code>AccessDenied</Code>
    <Message>Access Denied</Message>
    <RequestId>B30A0F85611B7101</RequestId>
    <HostId>
         L7oQptwXE00fagcDY97m5pcygdjCCGBwYndWUks14KmPTicm/fTaAZGBNfKz/pYIsSe2YjgFvXg=
    </HostId>
</Error>

```

**Comment by fwaibel** [comment]
@wilsonna Did you change the cordova widget.id lately?

**Comment by wilsonna** [comment]
You're right @fwaibel, I did change the widget.id. I deleted my app and recreated it and it's now working. Thanks for the tip!
