### ISSUE TITLE
tabris.ui.set not working in Tabris.js 2.x nightly 

### ISSUE THREAD

**Issue by iteearmah** [eclipsesource/tabris-js#1082]
tabris.ui.set("background", "#D71A21");

not working .

Any tmp documentation to read on 2.x

**Comment by mpost** [comment]
@iteearmah Your observation is correct. As of now you would have to read the tabris-js sources to gather the changes in the 2.x stream.

In short: we have replaced the `tabris.ui` with a new view called `NavigationView`. This view as a similar behavior to `tabris.ui` but can be instantiated multiples times and be treated like any other widget. As you are probably aware already the `tabris.ui.contentView` is now the root node of the widget hierarchy.

Regarding the `background` property you are referring to, you will now set the `toolbarBackground` color: https://github.com/eclipsesource/tabris-js/blob/master/src/tabris/widgets/NavigationView.js#L25

**Comment by ralfstx** [comment]
Closing as it appears to work as expected.
