### ISSUE TITLE
admob and FCM gradle conflict local build

### ISSUE THREAD

**Issue by iteearmah** [eclipsesource/tabris-js#1083]
````
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/firebase/FirebaseApiNotAvailableException.class

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED


````

**Comment by mpost** [comment]
Sounds like multiple cordova plugins are bundling the firebase library. Probably a plugin is adding the dependency as a regular jar/aar instead of a maven dependency (that would be resolved properly).

Which plugins are you using?

**Comment by iteearmah** [comment]
admob 5.5.0 "Admob Plugin" https://github.com/admob-google/admob-cordova.git and tabris firebase plugin https://github.com/eclipsesource/tabris-plugin-firebase.git

**Comment by mpost** [comment]
@iteearmah As expected the `admob-cordova` plugin simply copies (outdated) bundled jars into the app resulting in a conflict. https://github.com/admob-google/admob-cordova/blob/master/plugin.xml#L42 (and below)

You could fork the `admob-cordova` plugin and remove those copied dependencies and instead add

```xml
<framework src="com.google.firebase:firebase-ads:10.0.1" />
```

**Comment by iteearmah** [comment]
hmmm...did not work. any alternative firebase admob cordova plugin?

**Comment by cookieguru** [comment]
@iteearmah What error are you seeing now?

**Comment by mpost** [comment]
@iteearmah As stated above... what error are you seeing now?

We want to extend the `tabris-plugin-firebase` to also supports ads in the future but that will be some time out. PRs are welcome though.

**Comment by iteearmah** [comment]
@cookieguru no error; it does not show the ads, as if its not there

**Comment by cookieguru** [comment]
@iteearmah If you remove `tabris-plugin-firebase` do your ads show up?  If so, can you re-add it and check logcat for errors?

**Comment by mpost** [comment]
Closing this one as resolved. Please target the firebase plugin when issue persist.
