### ISSUE TITLE
Hide page from the Drawer topeLevel: false?

### ISSUE THREAD

**Issue by camstuart** [eclipsesource/tabris-js#1084]
Making a page 'not top level' removes it from the Drawer (Burger Menu) which is what I want:

```
new tabris.Page({
    id: 'signInPage',
    title: "Sign In",
    topLevel: false
  });
```

 but I load the page first, and I get the following error in the console:

`Could not load main module: Error: Opened page without a top-level page`

How can I hide my signInPage from the menu?

I imagine the technique will be the same to dynamically hide the logout navigation menu item until the user is logged in

**Comment by cookieguru** [comment]
Instantiate your `Drawer` after the user is logged in

**Comment by camstuart** [comment]
Thanks @cookieguru

**Comment by mpost** [comment]
Closing as fixed. Please reopen if you still have issues.
