### ISSUE TITLE
Update App events foreground and resume to fire on app cold start

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1085]
Currently the App events `foreground` -> `resume` only fire when the app has been brought back into view after being send to the back (eg. by pressing the home button). To better support certain cordova plugins on Android we should fire those events also during app (cold) start.

Having the life-cycle callbacks readily available in js will also make it simpler to activate/deactivate certain app features depending on the app state.

The js docu needs to be adjusted accordingly: https://tabrisjs.com/documentation/latest/api/app#foreground-app

**Comment by ralfstx** [comment]
May be related to #1295. `foreground` seems to fire on cold start unless the code is loaded by the developer app.

**Comment by mpost** [comment]
Closing as resolved.
