### ISSUE TITLE
Question - How do I identify cordova plugin versions

### ISSUE THREAD

**Issue by camstuart** [eclipsesource/tabris-js#1088]
In `cordova/config.xml` I am adding permissions for the barcode scanner:

```
  <plugin name="cordova-plugin-barcodescanner" version="?.?.?" />
```

What is the recommended way to determine the correct plugin version?
Am I ok to simply use the NPM version, eg: 6.0.5 (from https://www.npmjs.com/package/phonegap-plugin-barcodescanner)

Thanks

**Comment by mpost** [comment]
@camstuart Yes, the npm version should be given in the `spec` attribute.

**Comment by camstuart** [comment]
Ahh `spec`. I was using `version` as suggested here:

https://tabrisjs.com/documentation/latest/build#adding-plugins

**Comment by cookieguru** [comment]
@camstuart Both `spec` and `version` work

**Comment by mpost** [comment]
Closing as "resolved". Please reopen if you have any more problems.
