### ISSUE TITLE
Barcode Scanner working in dev, not built apps

### ISSUE THREAD

**Issue by camstuart** [eclipsesource/tabris-js#1089]
While developing (serving locally and viewing on the Tabris developer app) my app's barcode scanner works fine. For both iOS and Android.

However, when I build and deploy (with or without debug mode enabled) to my devices, the barcode scanner does not work.

This is the error message in the debug console:
```
undefined is not an object (evaluating 'cordova.plugins.barcodeScanner')
```

I have 2 cordova plugins registered in `cordova/config.xml` like so:

```
<plugin name="cordova-plugin-barcodescanner" spec="6.0.5" />
<plugin name="cordova-plugin-x-toast" spec="2.5.2" />
``` 
See also #1088 for how I determined version/spec

The toast plugin is working fine.
The code to trigger to barcode scanner is based on the Tabris examples, here is my implementation:

```
var ScanProductPage = function () {

  this.page = new tabris.Page({
    id: 'scanProductPage',
    title: "Scan Product",
    image: './assets/icons/barcode.png',
    topLevel: true
  });

  new tabris.Button({
    layoutData: {left: 10, top: 10, right: 10},
    text: "Scan Barcode"
  }).on("select", scanBarcode).appendTo(this.page);

  var resultView = new tabris.TextView({
    layoutData: {top: "prev() 20", left: 20, right: 20},
    markupEnabled: true
  }).appendTo(this.page);

  function scanBarcode() {
    cordova.plugins.barcodeScanner.scan(function (result) {
        resultView.set("text", result.cancelled ?
          "<b>Scan cancelled</b>" :
          "<b>Scan result:</b> " + result.text + " (" + result.format + ")");
      }, function (error) {
        resultView.set("text", "<b>Error:</b> " + error);
      },
      {
        preferFrontCamera : false,
        showFlipCameraButton : true,
        showTorchButton : true,
        prompt : "Place a barcode inside the scan area"
      });
  }

};

module.exports = ScanProductPage;
```

I tried rolling back to an earlier version of the barcodescanner plugin (6.0.3) to no avail.

**Comment by mpost** [comment]
Do you see the error on iOS and Android?

**Comment by camstuart** [comment]
Yes, same on both

**Comment by mpost** [comment]
when the error is on both devices i would think that you are not building the app with the plugins included. have you run the build with the plugins on tabrisjs.com?

**Comment by camstuart** [comment]
Yes, I am building on tabrisjs. I wondered the same, that's why I tried toasts, which seem to be OK.

**Comment by cookieguru** [comment]
[`cordova-plugin-barcodescanner`](https://www.npmjs.com/package/cordova-plugin-barcodescanner)'s highest version is `0.7.0`.  Did you mean [`phonegap-plugin-barcodescanner`](https://www.npmjs.com/package/phonegap-plugin-barcodescanner) which has a version `6.0.5`?

Also, I'm curious to what your build log looks like.  I would have expected it to fail with cordova 6.0.5.

**Comment by camstuart** [comment]
You have an excellent eye for details @cookieguru the build UI reports the build has passed, and artifacts are constructed :1st_place_medal: 

But as you suspected, within the build log (a happy green color I might add) I see:

```
iOS project created with cordova-ios@4.1.1
Discovered plugin "cordova-plugin-barcodescanner" in config.xml. Adding it to the project
Fetching plugin "cordova-plugin-barcodescanner@6.0.3" via npm
Failed to restore plugin "cordova-plugin-barcodescanner" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin cordova-plugin-barcodescanner@6.0.3 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: version not found: cordova-plugin-barcodescanner@6.0.3
Discovered plugin "cordova-plugin-x-toast" in config.xml. Adding it to the project
Fetching plugin "cordova-plugin-x-toast@2.5.2" via npm
Installing "cordova-plugin-x-toast" for ios
Running "writefile:tabrisBuildConfig" (writefile) task
```

I just did a build right now with version `0.7.0` in the `cordova/config.xml`:

```
<plugin name="cordova-plugin-barcodescanner" spec="0.7.0" />
```
And it works.

So it appears I was getting confused between cordova and phonegap barcode scanner packages on NPM :(

I wonder if it would be possible to simply take the latest version of the requested npm package if the spec/version defined is not available? Or even fail the build? Probably best to fail the build I think. Or allow the plugin to be specified without `spec` or `version` and take the latest stable

**Comment by cookieguru** [comment]
I agree-my vote would be to fail the build if a plugin can't be downloaded.

According to the [Cordova spec](https://cordova.apache.org/docs/en/latest/config_ref/#plugin) the `spec` attribute is required but will defer to "the latest plugin version published to npm" [if it can't figure out the version based on other criteria](https://cordova.apache.org/docs/en/latest/reference/cordova-cli/index.html#algorithm-for-resolving-plugins).  I just learned it'll also take semver strings, so that's pretty cool.

**Comment by cpetrov** [comment]
@camstuart @cookieguru Thanks for the input! I've opened #1148 and am closing this issue.
