### ISSUE TITLE
CollectionView change:item (scroll) duplicate request!!!

### ISSUE THREAD

**Issue by gacal** [eclipsesource/tabris-js#1090]
i'm using collectionView change:item remote image but It sends a request to the server repeatedly every time it scrolls.
This situation is disrupting the optimization. The separate picture is sending requests many times.

Is there a way to do this? (ios no problem but android problem)

**Comment by cookieguru** [comment]
As mentioned in https://github.com/eclipsesource/tabris-js/issues/1078#issuecomment-269444788 Android uses a `RecyclerView` so the various cells are reused as you scroll up and down.  You should cache the response locally and pull from the cache when possible rather than making a web request for every `change:item` event.

**Comment by gacal** [comment]
I also studied the project. There is a similar problem there

**Comment by cookieguru** [comment]
The main difference is that all the data is loaded beforehand.  If you're going to do lazy loading, you're going to need to cache your data locally.

**Comment by gacal** [comment]
please sample code

**Comment by mpost** [comment]
When providing the image url on an `ImageView` in the `CollectionsViews`s `change:item` it will download and cache the image. The next time you set the image it will be taken from the cache.

Please also make sure that your images are not to large so that they are not evicted from the cache.

**Comment by gacal** [comment]
@mpost  20-30kb ?

**Comment by mpost** [comment]
@gacal that should be okay. (it is more about resolution since the image will be inflated in memory (32bit)

**Comment by cpetrov** [comment]
As @mpost stated, the remote image resource of an `ImageView` should get cached. When providing an URL of an image, which has been loaded before, the image should be retrieved from the cache and no second request should be sent to the server.

I tested this with our reddit example and couldn't observe additional requests when setting images which have been loaded before when scrolling through the list.

If you still have this problem, please provide a snippet and reopen the issue.
