### ISSUE TITLE
TextInput clear button not working properly with password fields

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1091]
Upon tapping on the button, nothing happens. The text input field is cleared when tapping on the clear button and then on the field again.

Example: 

```js
new tabris.TextInput({
  type: 'password',
  left: 20, top: 20, right: 20,
  message: 'Type here'
}).appendTo(tabris.ui.contentView);
```

**Comment by karolszafranski** [comment]
fixed here: eclipsesource/tabris-ios#852
