### ISSUE TITLE
Broken link in documentation 

### ISSUE THREAD

**Issue by camstuart** [eclipsesource/tabris-js#1094]
The documentation page:
https://tabrisjs.com/documentation/latest/api/Page

Has a link to the github snippet:
https://github.com/eclipsesource/tabris-js/tree/v1.10.0/snippets/page-fullscreen/page-fullscreen.js

But this URL gives a 404

I was hoping to see an example of a full screen page. To use on my login page (no menu or title needed)

Thanks

**Comment by mpost** [comment]
Thanks for the heads up. We will adjust accordingly.

**Comment by cookieguru** [comment]
In case you didn't find it @camstuart the link is https://github.com/eclipsesource/tabris-js/blob/1.x/snippets/ui-fullscreen/ui-fullscreen.js

f043d0f3b3ac77282e24f566fcbd3c7baabef094 was supposed to fix this but needs some tweaking.

**Comment by ralfstx** [comment]
Thanks for reporting. I've just fixed a ton of broken links, including this one. The changes are not live yet, but committed to the docs repository.
