### ISSUE TITLE
ScrollView Reverse Vertical or Horizontal

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#1095]
What are your thoughts on adding the ability to reverse the flow of widgets in a ScrollView, adding to the bottom and appending up, rather than adding to the top and appending down.

**Comment by cookieguru** [comment]
```js
var children = parent.children();
if(children.length) {
	newWidget.insertBefore(children[0]);
} else {
	parent.append(newWidget);
}
```
Or if you're looping you can always store a reference to the previous element:
```js
var last;
for( ... ) {
	if(last) {
		currentIteration.insertBefore(last);
	} else {
		currentIteration.appendTo(parent);
	}
	last = currentIteration;
}
```

I imagine the `children` call is somewhat expensive, so if the latter doesn't work a pseudo [selector](https://tabrisjs.com/documentation/latest/types#selector) for "first" or an integer index could speed things up.

If you had an `insertAt()` method where you could provide an integer index it would probably be faster on the native side.  But then you'd have to marshal all the tree updates across the JS bridge, so I'm not sure if that's much of a performance improvement over doing it all in JS land.

Kinda curious what your use case is and how you're dealing with the x/y scroll position.

**Comment by dested** [comment]
This is a very interesting solution to insert the widgets in reverse order in a more elegant way, but the ideal goal would allow me to append elements in a way that forced the scrollview to pin to the bottom without having to muck with scrollY along the way. Thinking about it a little more I may be able to fake it with the tools at my disposal, just wondering if there was any appeal to having it baked in. 

The use case is a simple chat app where the new messages always appear pinned to the bottom, the the previous messages scrolling upwards. I am not certain if I can append an element to a ScrollView with bottom 0 and have it pin properly, which may preclude me from implementing it with just trickery.

**Comment by cookieguru** [comment]
I was going to suggest a `CollectionView` since `insert()` will automatically append to the end, and then you could `reveal()` the last element, but in order to properly calculate the size of the `Cell` you'd have to first create the widget, get its height, and then use the `itemHeight` property to make sure its bounding box is large enough.  When your dataset grows to a substantial size this will noticably degrade performance as pointed out in #511

**Comment by mpost** [comment]
Using a `CollectionView` sounds like a reasonable approach for a chat style list where you likely have many entries. At the moment we don't have any support to stack items from the bottom but it would be a reasonable addition.

**Comment by mpost** [comment]
@tbuschto has some experience with creating chat style `CollectionView` entries. Maybe he could share some best practices there.

**Comment by cookieguru** [comment]
Check out a19ec7dd63038ca0b22fcda0965bf9b859ca45ae, there's now an index property.

**Comment by dested** [comment]
Great, thanks for the support. 

For future reference, I ended up adding a scrollview with a 10,000px composite in it and set the scrollY to the bottom. From there I appended the chat messages and manipulated the translateY by hand when a new message came in. It worked for my problem.
