### ISSUE TITLE
Cannot create a basic Tabris 2.x app with Drawer and pages

### ISSUE THREAD

**Issue by bdjibril** [eclipsesource/tabris-js#1096]
The below helloWorld snippet is returning the following error in tabrisjs 2.0. 

>  **page.open** is not a function

``` javascript
var page = new tabris.Page({
  title: "Hello, World!",
  topLevel: true
});

var button = new tabris.Button({
  text: "Native Widgets",
  layoutData: {centerX: 0, top: 100}
}).appendTo(page);

var textView = new tabris.TextView({
  font: "24px",
  layoutData: {centerX: 0, top: [button, 50]}
}).appendTo(page);

button.on("select", function() {
  textView.set("text", "Totally Rock!");
});

page.open();
```

Is there an example project for tabrisjs 2.x I can refer to?

**Comment by mpost** [comment]
If you want to use pages in 2.x we introduced the `NavigationView` along with it in 2.x. Please have a look at the snippet: https://github.com/eclipsesource/tabris-js/blob/master/snippets/page-stacked.js

**Comment by mpost** [comment]
Note that the API for the `NavigationView` is still in flux and subject to change.

**Comment by bdjibril** [comment]
@mpost thanks so much for your response. I was able to add pages now and everything works fine.
However I was unable to add a drawer to the UI using the code below.

```javascript
tabris.ui.drawer.append(new tabris.PageSelector());
```

**Comment by mpost** [comment]
the `PageSelector` will be removed in 2.x

**Comment by bdjibril** [comment]
Thank you @mpost I will close this now.
