### ISSUE TITLE
console log - question

### ISSUE THREAD

**Issue by maoamid** [eclipsesource/tabris-js#1097]
On production build, the console.log code are removed automatically?
(I read somewhere that grunt can do this on minify.)

**Comment by mpost** [comment]
If you are app is not build in "debug" mode in the tabrisjs.com build settings the console will not be shown. You can however reenable it in that mode via the `config.xml` preference `EnableDeveloperConsole`: https://tabrisjs.com/documentation/latest/build#preferences

**Comment by maoamid** [comment]
thank you @mpost for clarification. I was interested mode in how the online build threat the code, specially if it is commented or disabled, or just ignored. If you did this before me, is a solution to clean the code before build it manually, or it doesn't matter, and let all that "dev code" where it is

**Comment by mpost** [comment]
For now you can not determine if you are in "dev mode" or not inside the app. This could be a useful distinction though and we could integrate it in the future.

**Comment by cookieguru** [comment]
@maoamid Your code is packaged as-is in a release build.  No minification of any sort is performed.  Comments, whitespace, and all commands are preserved and packaged as-is.  APK and IPA are just zip files; you can open either of them in an unzipper and see your code in `assets/www` and `Payload/x.app/www`.

**Comment by ralfstx** [comment]
See #874 for the discussion on a "dev mode" flag.
