### ISSUE TITLE
InAppBrowser failed to work in iOS 10.1 and 10.2

### ISSUE THREAD

**Issue by wilsonna** [eclipsesource/tabris-js#1098]
I'm not sure if this is related to tabris.js, but since my app is developed in tabris.js, I thought I'd first check to see if anyone else is facing the same issue. I was previously on iOS 10.0.1 and I had no issue launching a website in the cordova InAppBrowser plugin. But since upgrading the 10.2, instead of loading the webpage, it loads the source code in InAppBrowser. Anyone facing this same problem?

**Comment by mpost** [comment]
We haven't heard of the problem before. You could consider using a `WebView` in place.

**Comment by wilsonna** [comment]
Unfortunately, the app is unable to obtain the secure cookie from outside the WebView. Authentication is done via a third party website within the WebView and I need the cookie value that is returned by this site in order to use it in my app subsequently. If you can recall, this problem was discussed at length in #638. Using the InAppBrowser was the only way for it to work in both Android and iOS. But it just broke in iOS.

**Comment by mpost** [comment]
I remember the issue you had. We will look into the problem.

**Comment by wilsonna** [comment]
Just another update on this particular issue. I stripped my application down to the bare minimum and still the InAppBrowser shows the source (well, not exactly. I don't see the HTML tags, but I see the javascript and css, plus the text content) instead of the rendered page in iOS. Android loaded fine. I am currently testing with the Developer app, but the built app has the same problem as well. However, I don't see any resources online saying that the InAppBrowser had any issue with IOS 10.1+, so I'm not sure whether the problem the problem lies with my coding (which is not much since it's basically stripped bare) or configuration, broken Tabris.js compatibility with InAppBrowser, or simply InAppBrowser itself. Or maybe even some settings in iOS?

**Comment by mpost** [comment]
With the upcoming Tabris.js 2.1 release we have new feature called `app.launch(<url>)`. This should be a good substitute for the cordova plugin.

**Comment by ralfstx** [comment]
I'd hope that `app.launch()` is a sufficient replacement for the InAppBrowser plug-in. @wilsonna Could you give it a try and reopen if it does not cover your case?

**Comment by wilsonna** [comment]
@ralfstx I've since changed the app to not use the InAppBrowser due to the above issue. But I've give this a try when I implement the next app that requires launching a browser. Thanks!
