### ISSUE TITLE
Set image from Blob

### ISSUE THREAD

**Issue by cookieguru** [eclipsesource/tabris-js#1100]
I have a use case where I'm loading images from a remote server and I need to display some additional metadata about the image.  Currently, this requires performing two requests--one to load the image and another to fetch the metadata.  Since I control the remote host, I'd like to send additional HTTP headers with the image that contain the metadata.  With the `fetch` API, I can [get the image data as a blob](https://developer.mozilla.org/en-US/docs/Web/API/Body/blob) and [retrieve the custom headers as text](https://developer.mozilla.org/en-US/docs/Web/API/Headers/get).  From there, it would be great to be able to set the `ImageView`'s source to that blob data and (for example) a `TextView` with the value of the custom header.

Alternatively, if there was a way I could access the `okhttp` response object (and its equivalent on other platforms), that would work too.

**Comment by mpost** [comment]
@cookieguru With Tabris.js 2.x we will support the XHR/fetch response to be of type `arraybuffer`. Therby you can get the binary data of your image (still compressed as jpg/png) and the headers.

On iOS the ImageView also supports to set the image as a base64 encoded string: `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIA...`. This could be something we could also add on Android.

**Comment by mpost** [comment]
Support for data uris has landed on Android (Tabris.js 2.x) with the closing of https://github.com/eclipsesource/tabris-js/issues/884. See https://en.wikipedia.org/wiki/Data_URI_scheme for more details.

**Comment by cookieguru** [comment]
That will work nicely.  Thanks for the quick turnaround @mpost!

**Comment by mpost** [comment]
`arraybuffer` `responseType` is merged on Android. You could try the turnaround with a nightly build. iOS support coming in the next few days.

**Comment by capotti** [comment]
I cannot find a code snippet to understand your solution.
How to get a xhr.resonse into the required base64data for a imageView source?

fetch data with 
```javascript
var xhr = new tabris.XMLHttpRequest();
xhr.responseType = "arraybuffer";
```

xhr.response has to be converted into variable "base64data"
```javascript
image: {src: "data:image/png;base64," + base64data}
```

**Comment by cookieguru** [comment]
Why don't you just set the image's source to the URL that you request with XMLHttpRequest?

**Comment by capotti** [comment]
your so speedy ;-)
cause I have to login with user and password
