### ISSUE TITLE
Any way to catch uncaught exceptions?

### ISSUE THREAD

**Issue by patbenatar** [eclipsesource/tabris-js#1103]
In the browser, we have `window.onerror`, but that doesn't seem to work in Tabris.js apps. Is there an equivalent method for capturing uncaught exceptions in a Tabris app in order to setup exception notifications with a service like Rollbar/Airbrake/etc.

Couldn't find anything in the documentation about exception handling, so forgive me if I'm asking an already answered question.

**Comment by cookieguru** [comment]
I think a master try/catch would be the only way.

**Comment by patbenatar** [comment]
Yeah I'll give that a shot. 

It's my understanding that `window.onerror` works in Cordova; any idea why it wouldn't work in Tabris built on top of Cordova?

**Comment by cookieguru** [comment]
Cordova leverages the device's WebView and since it's operating in a browser it has all the capabilities of a browser.  Tabris.js uses a JavaScript engine for all commands, so all the browser-specific elements have to be re-implemented.

**Comment by patbenatar** [comment]
What would it take to re-implement root-level uncaught exception handling using Tabris' JS engine? The master try/catch would work for simple programs but anything that goes async wouldn't be caught by that.

**Comment by mpost** [comment]
A request for the global error event handler has already been made here. https://github.com/eclipsesource/tabris-js/issues/1033. Unfortunately we haven't gotten around to it yet.

**Comment by ralfstx** [comment]
Right, so let's close it as a dup.

**Comment by patbenatar** [comment]
Sounds good thanks all. I'll track it on the other issue.
