### ISSUE TITLE
Multiple composites stacked with tap (iOS)

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#1105]
On android, when multiple composites overlay each other, each with their own tap event, only the top one fires when tapped. On iOS all composites in the line of the tap fire the event. Is this a bug, or at least preventable?

**Comment by mpost** [comment]
@dested The behavior you describe on Android is the expected behavior. A tab listener intercepts the event so that views underneath do not receive the event. Could you provide a snippet to replicate the issue?

**Comment by mpost** [comment]
The issue remains on ios. The snippet here can be used to replicate the problem: https://github.com/eclipsesource/tabris-js/issues/1357#issuecomment-305441845

**Comment by karolszafranski** [comment]
Fixed in: https://github.com/eclipsesource/tabris-ios/commit/e6dd506d0f2a97afcc121858ae8b6985669d85ad
