### ISSUE TITLE
ScrollView scroll events are not properly passed to listener

### ISSUE THREAD

**Issue by dbuschtoens** [eclipsesource/tabris-js#1109]
The documentation states that the following for the parameters for the events scrollX and scrollY:
```
      "parameters": [
        {"name": "widget", "type": "this"},
        {"name": "offset", "type": "number", "description": "Indicates the current horizontal scrolling position."}
      ],
```
however, `offset` is actualy an object `{offsetY: number}` on Android, as can be seen with the following snippet:

```
`var scrollView = new tabris.ScrollView({
  left: 0, right: 0, top: 0, bottom: 0
}).appendTo(tabris.ui.contentView);

for (var i = 0; i <= 200; i++) {
  new tabris.TextView({
    top: i * 30 + 20, centerX: 0, width: 30,
    text: i + '°'
  }).appendTo(scrollView);
}

scrollView.on('scrollY', function(widget, offset) {console.log('offset = ' + JSON.stringify(offset));});
```

**Comment by mpost** [comment]
A couple of things are not in synch here:

* On iOS the event `scrollX`/`scrollY` are not yet implemented. @karolszafranski will take care of this.
* On Android we will change the event key from `offsetY` to be just `offset`.
* On js the the protocol needs to be updated to account for the event object here: https://github.com/eclipsesource/tabris-js/blob/master/src/tabris/widgets/ScrollView.js#L28. The trigger function receives an event object and not the offset value. therefore the `offset` has to be extracted from the event and passed on. In addition the `change:offsetY` alias should be `change:scrollY`.

**Comment by mpost** [comment]
Closing as "adjusted" as expected.
