### ISSUE TITLE
Allow label to limit its number of shown lines when wrapping

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#111]
It would be great if we could only show x number of lines from a label. Eg when you want to preview a block of text.

**Comment by ralfstx** [comment]
How should this property be called? `maxLines`?

**Comment by jkrause** [comment]
+1

**Comment by mpost** [comment]
+1

**Comment by ralfstx** [comment]
We need to agree on a value to reset the property. In Android, `Integer.MAX_VALUE` is used to reset `maxLines`, which is not an option for us. I'd suggest to use `null`.

**Comment by mpost** [comment]
+1 for null

**Comment by jordiboehmelopez** [comment]
On iOS it’s the integer value 0.
But null is fine for me.

Jordi

**Comment by ralfstx** [comment]
Implemented on both clients. Now there is an inconsistency when `maxLines` is set to `0`: iOS displays all lines, Android none. We should map `0` -> `null` in JS.
