### ISSUE TITLE
How to download tabris cordova platform?

### ISSUE THREAD

**Issue by FrencoJobs** [eclipsesource/tabris-js#1111]
Where?I didn't find it.

**Comment by cookieguru** [comment]
https://tabrisjs.com/documentation/latest/local-build#adding-tabrisjs-platforms

**Comment by FrencoJobs** [comment]
I mean I didn't find download link on tabris download page.
Please,give me download link.

**Comment by cookieguru** [comment]
Make sure you're signed in on tabrisjs.com

**Comment by FrencoJobs** [comment]
I'm sure.

**Comment by FrencoJobs** [comment]
@cookieguru Sorry I'm Wrong.I get it.Thanks..
