### ISSUE TITLE
tabris.ui.contentView doesn't fire 'resize'

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1112]
`tabris.ui.contentView` doesn't fire a `resize` event when its bounds change. It is expected to be fired when the snippet's widgets are laid out the first time (on start) and each time the screen orientation is changed.

Reproducible in the `layout-dynamic` snippet.

**Comment by mpost** [comment]
This issue has not been resolved yet. Reopening it.

**Comment by cpetrov** [comment]
`ui.contentView` does not fire resize initially anymore with the latest 2.0.0 nightly (18.05.2017). Reproducible in the _layout-dynamic_ snippet.

**Comment by mpost** [comment]
@cpetrov Are you seeing the problem on iOS or Android? Or both?

**Comment by cpetrov** [comment]
@mpost iOS, couldn't test Android.

**Comment by ralfstx** [comment]
@cpetrov @mpost That's because the boot.js has changed. I will provide a JS fix today, the clients don't need to update.

**Comment by ralfstx** [comment]
The current issue should be resolved with e3f8231. Tested the *layout-dynamic* snippet in the Android dev app and it works as expected.

**Comment by mpost** [comment]
@ralfstx To verify that it is working on Android you have to test in a cordova based app.

**Comment by cpetrov** [comment]
Current test results with latest nightly:

|Android Dev App|Android Play Store App|iOS App Store App|
|---|---|---|
| ✔ | ✘ | ✔ |

**Comment by tbuschto** [comment]
Same issue on windows unless cordova is not loaded.

**Comment by mpost** [comment]
The problem only occurs on Android when an app is started from the launcher app. When an app is bundled inside a Tabris.js app (eg a production build is used) the `resize` event is fired as expected.

**Comment by mpost** [comment]
Since we do not ship development apps with the tabris launcher anymore. The problem can not be recreated.
