### ISSUE TITLE
Disable ScrollView animation

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#1113]
I am having a bit of an issue with setting the scroll position of a scroll view. I want to **start** the scrollview at a certain scrollX without scrolling to this position. This does not currently seem possible as the scrollX can't be set at construction since it has no content yet, and if I set it at any point after I get the animation. What are your thoughts on a solution to this problem?

**Comment by mpost** [comment]
You are right and your voice is beeing heard. In Tabris.js 2.x we have added a boolean `animate` property when setting the scroll position,

https://github.com/eclipsesource/tabris-js/blob/master/doc/api/widgets/ScrollView.json#L54

**Comment by dested** [comment]
Thank you for the update :-)
