### ISSUE TITLE
Home and refresh console buttons don't have margins

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1114]
They are too near to the developer console container edges.

| Now | Before |
| --- | --- |
| ![simulator screen shot 31 jan 2017 17 23 20](https://cloud.githubusercontent.com/assets/2341769/22473766/34f3f4a6-e7da-11e6-84ff-035c5e0ab918.png) | <img alt="screen shot 2017-01-31 at 17 22 17" src="https://cloud.githubusercontent.com/assets/2341769/22473672/e6ddcc4c-e7d9-11e6-8034-7284c2ec0aec.png"> |

**Comment by karolszafranski** [comment]
eclipsesource/tabris-ios 97b8667946a887d1fac31ae12e7696f6990ddbf8
