### ISSUE TITLE
Setting tintColor to null

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#1115]
It is currently not possible to reset the value of tintColor as setting it to null emits a warning about an invalid value. (tested on android)

**Comment by cookieguru** [comment]
Which Tabris.js version?  [Docs](https://tabrisjs.com/documentation/latest/api/ImageView#tintcolor) say that's the right value to remove the effect, but you might try `'initial'` as well.

**Comment by dested** [comment]
1.10 currently. I will give that a try.

**Comment by dested** [comment]
Initial does work.  If this is the intended behavior it should be noted.

Thanks!

**Comment by mpost** [comment]
Thanks for pointing the documentation discrepancy out. We will update the docs to correctly state `initial`.
