### ISSUE TITLE
Build Service - iOS debug key selected for release job

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#1116]
is this new? did something change on the build server recently for iOS release builds?

how would you setup an AdHoc build now?

**Comment by fwaibel** [comment]
I triggered and checked the certificate with one of our `release` builds and I cannot reproduce this.

Can you provide an error message? Thanks.

**Comment by bFlood** [comment]
this is all that appears in the build log:
![image](https://cloud.githubusercontent.com/assets/404991/22648707/d9e3eb6e-ec45-11e6-8811-edb38fe4475a.png)

previously, we created Ad-Hoc builds so we could test on developer devices before building the production release. In tabris, this was always done with the Debug option turned off (it would appear as Release in the tabris list of builds).  Maybe we were doing something wrong and this is now fixed on your servers?

either way, how would you create an AdHoc build (with device UDIDs for testing embedded) from Tabris now?

**Comment by karolszafranski** [comment]
We overlooked this possibility, but we will make it possible soon. Already working on that change.

**Comment by bFlood** [comment]
great, thank you!

**Comment by fwaibel** [comment]
@bFlood Did the change work for you? Can we close this ticket?

**Comment by bFlood** [comment]
I don't think so, when I switched back to the ad-hoc signing key/provisioning file and click Save, I still get this error up top:
![image](https://cloud.githubusercontent.com/assets/404991/22691263/a2b4d55a-ed07-11e6-8242-376af1a87916.png)

**Comment by bFlood** [comment]
this seems fixed now, closing
