### ISSUE TITLE
Question: how to use .children selector

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1117]
I am planning to get list of widgets who has class : 'PICKUPCOMBO' in a page. Any idea how to do it?

i tried page.children({class:'PICKUPCOMBO'}); page.children().find({class:'PICKUPCOMBO'}); .. Am i missing something.

page.children() returns all the children correctly.

**Comment by cpetrov** [comment]
Use `page.children('.PICKUPCOMBO')`.
Am 04.02.2017 um 10:23 schrieb natanraj <notifications@github.com<mailto:notifications@github.com>>:


I am planning to get list of widgets who has class : 'PICKUPCOMBO' in a page. Any idea how to do it?

i tried page.children({class:'PICKUPCOMBO'}); page.children().find({class:'PICKUPCOMBO'}); .. Am i missing something.

page.children() returns all the children correctly.

**Comment by cookieguru** [comment]
From [Working with Selectors](https://tabrisjs.com/documentation/latest/selector#working-with-selectors), the `find` and `children` methods take a Selector _string_, not an object.  Use this:
```js
page.children('.PICKUPCOMBO');
```

**Comment by natanraj** [comment]
ok, thanks. 

If i have to use some other customer property, how to do it ? by id ? .children('#idValue')?

**Comment by cookieguru** [comment]
Check out [Selector Strings](https://tabrisjs.com/documentation/latest/selector#selector-strings).  You can select by class, ID, or widget type, but not by other properties.

**Comment by natanraj** [comment]
Thanks. It helps...
