### ISSUE TITLE
How to make an animation between 2 pages

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1118]
Hello everyone please i want to know(with a snippet if it's possible) how to make a animation between two pages A et B and how to reverse the animation when the back button is pressed
Thank You

**Comment by cookieguru** [comment]
Are you looking for something like this?

https://developer.android.com/training/animation/anim_screenslide.mp4

That's currently not possible.  Depending on what type of animation you want, you may be able to accomplish the same task with other widgets, assuming you don't require the second visible item to be a `Page`.  For example, if you want to directly recreate the above video, you can use a [`TabFolder`](https://github.com/eclipsesource/tabris-js/blob/v1.10.0/snippets/tabfolder/tabfolder.js) to provide the swiping motion, and calling `tabFolder.set('selection', someOtherTab);` to advance to a different tab.

**Comment by ishigo1987** [comment]
if i understood right it's not possible right now to have something like a flip transition between two page A and B.so by default tabrisJs comes with no transition between the pages?except the tabfolder?

**Comment by cookieguru** [comment]
If you mean a flip transition like [this](https://davidwalsh.name/demo/css-flip.php) then no, it is not currently possible.  There are animations between pages but it is the system default transition (which can be disabled in Android).

**Comment by ishigo1987** [comment]
Ok I hope that better transitions will come soon.In tabris 2.0 perhaps

**Comment by mpost** [comment]
@ishigo1987 Good news for you. In Tabris.js 2 we have indeed improved the animation support for Pages, by turning them off.

Well the default transitions are still available by default but you can set the property `animated` on the new `NavigationView` to `false` which will turn all page animations off (making the transition instant). You could now use the regular Tabris.js animations API to create your custom transition.

https://github.com/eclipsesource/tabris-js/blob/master/doc/api/widgets/NavigationView.json#L32

**Comment by ishigo1987** [comment]
Great!!! good news how can i use Tabris.js 2 now have you a link or a node command to install?

**Comment by ralfstx** [comment]
Tabris 2.0.0-beta1 has just been published: `npm install tabris@2.0.0-beta1`.

**Comment by mpost** [comment]
We have created a blog post showings several of the new Tabris.js 2 features. http://eclipsesource.com/blogs/2017/02/08/tabris-js-2-0-beta-1-is-here/

For a more detailed description check the release notes:
https://github.com/eclipsesource/tabris-js/releases/tag/v2.0.0-beta1

**Comment by mpost** [comment]
Closing this as resolved. Please reopen if you have any more issues.
