### ISSUE TITLE
Online environment experiencing multiple problems

### ISSUE THREAD

**Issue by camstuart** [eclipsesource/tabris-js#1119]
@cookieguru and I have noticed a number of issues with the online environment:

- Scratchpad failing to run scripts in the developer app: `Cannot find module 'tabris'`
- Snippets missing from `https://tabrisjs.com/snippets/`
- Online build fails with: `The command "wget -q $TABRIS_URL --no-check-certificate" failed and exited with 8 during`

Seems like some type of environment problems

**Comment by natanraj** [comment]
ScratchPad shows warning at the bottom as given. The scratchpad is bound to the latest release: 2.0.0-beta1 . Should we have to do anything from our end ?

**Comment by mpost** [comment]
Thanks for the heads-up. We have solved the issue and everything should be back to normal. Please let us know if you have any more problems.

**Comment by fwaibel** [comment]
I switched back the scratchpad to `1.10.0` for now.

A bit of background: 

We are currently preparing `2.0.0-beta1`. Once the Tabris.js 2 clients are available we will switch the scratchpad to `2.0.0-beta1` again.

Just a heads-up: Depending on your snippets you should reserve some cycles to update your snippets to the new APIs.

**Comment by camstuart** [comment]
Ok, looks like I will need some updates to my scratchpad.... But some unusual console errors and odd behavior just rendering the page

<img width="956" alt="screen shot 2017-02-07 at 10 25 02 pm" src="https://cloud.githubusercontent.com/assets/3146022/22689339/9e584898-ed84-11e6-8569-ee76927f5bba.png">

**Comment by camstuart** [comment]
I can confirm builds are working now, thanks guys!

**Comment by cookieguru** [comment]
@fwaibel Since the Tabris.js client sends the version as part of the `User-Agent` header, would it be possible to serve up a tarball that matches the client version rather than the same one on every request?

**Comment by fwaibel** [comment]
@cookieguru Sounds like a good idea. I will look into that.
