### ISSUE TITLE
Version Mismatch error

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1122]
My scratchpad code was working until yesterday.. and today onwards i am getting this error. 

`Version mismatch: Javascript module "tabris" (version 2.0.0) is incompatible with the native tabris platform....`

Anything recently changed ?

**Comment by mpost** [comment]
@natanraj we have just released Tabris.js 2.0.0-beta1. This means that the scratchpad will serve Tabris.js 2.x snippets only. You will have to update you snippets to be compatible with 2.x. Please see https://github.com/eclipsesource/tabris-js/releases/tag/v2.0.0-beta1 for details. Sorry for any inconvenience. 

You can get the freshly launched dev app for ios and android from the download links (here)[https://tabrisjs.com/download]

**Comment by natanraj** [comment]
@mpost I am using my own app in developer / debug mode.. Should that have to be rebuilt for me to use it app and ScratchPad ?

**Comment by natanraj** [comment]
And do i have to change the cloud build version ?

**Comment by mpost** [comment]
@natanraj yes, please switch to `2.0.0-beta1` in your build config and rebuild the app.

![image](https://cloud.githubusercontent.com/assets/73655/22733503/51bebca6-edf2-11e6-9876-98dc51cbf9ae.png)

**Comment by natanraj** [comment]
Getting lot of build errors iwth this.

`home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/src/com/eclipsesource/tabris/maps/MapPropertyHandler.java:14: error: cannot find symbol
import com.eclipsesource.tabris.android.TabrisWidgetPropertyHandler;
                                       ^
  symbol:   class TabrisWidgetPropertyHandler
  location: package com.eclipsesource.tabris.android
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/src/com/eclipsesource/tabris/maps/MapPropertyHandler.java:28: error: cannot find symbol`

**Comment by mpost** [comment]
@natanraj you will have to switch to the master branch of the `tabris-plugin-maps` repo. We will update the   maps npm release when Tabris.js 2.x is stable.

**Comment by natanraj** [comment]
@mpost  Currently i have this config.xml as below..

`<plugin name="tabris-plugin-maps" spec="2.0.1" >
        <variable name="ANDROID_API_KEY" value="XYZ" />
    </plugin>`

What way should i change ?

**Comment by mpost** [comment]
To consume the plugin from the github repo (master) use:

```xml
<plugin name="tabris-plugin-maps" spec="https://github.com/eclipsesource/tabris-plugin-maps.git">
  <variable name="ANDROID_API_KEY" value="..." />
</plugin>
```

**Comment by mpost** [comment]
We have created a blog post showings several of the new Tabris.js 2 features. http://eclipsesource.com/blogs/2017/02/08/tabris-js-2-0-beta-1-is-here/

For a more detailed description check the release notes:
https://github.com/eclipsesource/tabris-js/releases/tag/v2.0.0-beta1

**Comment by natanraj** [comment]
Now the build is going successful, scratchpad is going fine.. but the app i developed earlier is failing.

Am i supposed modify any on the package.json ? If yes, what has to be used ?

`"dependencies": {
    "tabris": "^1.9.0"
  }`

**Comment by cookieguru** [comment]
Update your dependency to `2.0.0-beta1`

**Comment by natanraj** [comment]
something like this ? 

`"dependencies": {
    "tabris": "2.0.0-beta1"
  }`

**Comment by cookieguru** [comment]
Yes, and then run `npm update`

**Comment by natanraj** [comment]
@cookieguru  I am doing cloud build...

**Comment by cookieguru** [comment]
Sure, but you'll still need the updated dependency to test your code locally.

**Comment by natanraj** [comment]
ok. Now i am able to get past that issue. All the page variables i developed in my App. are they going to fail ? Do we have backward compatibility for using page variables?

**Comment by cookieguru** [comment]
Check out the [Migration Guide](https://github.com/eclipsesource/tabris-js/blob/master/doc/migration-guide.md)

**Comment by natanraj** [comment]
@cookieguru  What are the android versions it is supporting. My previous tabris app was working in my android4. devices but now the newly built app gets "there-is-a-problem-parsing-the-package".

**Comment by cookieguru** [comment]
From the [Release notes](https://github.com/eclipsesource/tabris-js/releases/tag/v2.0.0-beta1):
> Minimum support Android version raised to API level 17 (Android 4.2)

**Comment by natanraj** [comment]
Closing this...

**Comment by ohenepee** [comment]
Does anyone know exactly why the minimum SDK version for Android is now 4.2+? Could it have anything to do with a particular Android component?

I am developing for users who will mostly be using 4.0+ devices, but I also want the awesomeness of v2.x as well
