### ISSUE TITLE
v1 to v2 migration guide

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#1123]
will there be a guide describing the main differences between v1 and v2?
will v1 apps run under v2 without any modifications? I'm guessing no since Page does not even have an open method in v2
a lot of the widgets looks the same but what are the main changes for people with larger v1 apps that will eventually need to port over to v2?

thanks!

**Comment by mpost** [comment]
We have started a migration guide but it is not complete yet https://github.com/eclipsesource/tabris-js/blob/master/doc/migration-guide.md

**Comment by ralfstx** [comment]
Yes, we will complete the migration guide for the next beta. Until then, the [release changelog](https://github.com/eclipsesource/tabris-js/releases/tag/v2.0.0-beta1) might be helpful.
