### ISSUE TITLE
Remove a page from the nav stack

### ISSUE THREAD

**Issue by patbenatar** [eclipsesource/tabris-js#1124]
Is it possible to remove a previous page from the nav stack such that hitting back from the current page would skip it?

Ideal scenario:

1. User navigates page A -> B -> C
1. Remove B from nav stack
1. User hits back from C and lands on A

**Comment by cookieguru** [comment]
You can call [`dispose()`](https://tabrisjs.com/documentation/2.0/api/Widget#dispose) on page B

**Comment by patbenatar** [comment]
Thanks @cookieguru

**Comment by ralfstx** [comment]
Because it's a stack, removing page B would automatically remove C.

**Comment by patbenatar** [comment]
@ralfstx ah well that's not what I'm going for.. in native iOS NavigationController, you can remove a ViewController at any index. Is there an equivalent in Tabris 1? Perhaps Tabris 2 which looks to introduce a structural equivalent NavigationController?

**Comment by ralfstx** [comment]
@patbenatar I understand the scenario, we'll discuss your proposal.

**Comment by cookieguru** [comment]
The code is a little messy, but here is code that works in Tabris.js 2.0 based on my understanding of @patbenatar's description:

```js
var navigationView = new tabris.NavigationView({
	left: 0, top: 0, right: 0, bottom: 0
}).appendTo(tabris.ui.contentView);

var a, b, c;

a = new tabris.Page({
	title: 'Page A'
}).appendTo(navigationView);

new tabris.Button({
	centerX: 0, centerY: 0,
	text: 'Create B'
}).on('select', function() {
	b = new tabris.Page({
		title: 'Page B'
	}).appendTo(navigationView);

	new tabris.Button({
		centerX: 0, centerY: 0,
		text: 'Create C'
	}).on('select', function() {
		c = new tabris.Page({
			title: 'Page C'
		}).on('dispose', function() {
			b.dispose();
		}).appendTo(navigationView);
	}).appendTo(b);
}).appendTo(a);
```

Note that steps 2 and 3 from the ideal scenario are swapped.

**Comment by ralfstx** [comment]
As of a53514e, you can remove pages from the middle of the stack. Removing a page that is not the topmost page will no longer auto-remove pages on top. So the scenario described in the original post is now possible:

> 1. User navigates page A -> B -> C
> 2. Remove B from nav stack
> 3. User hits back from C and lands on A

**Comment by ralfstx** [comment]
The change didn't make it into 2.0.0-beta2, but it will be included in RC1.
