### ISSUE TITLE
Online Build Fails: No valid iOS Development signing identities belonging to team 

### ISSUE THREAD

**Issue by camstuart** [eclipsesource/tabris-js#1126]
My Apps have started failing to build:
```
Error Domain=IDEDistributionErrorDomain Code=1 "No valid iOS Development signing identities belonging to team 5XXXXXX35H were found." UserInfo={NSLocalizedDescription=No valid iOS Development signing identities belonging to team 5XXXXXX35H were found.}
error: exportArchive: No valid iOS Development signing identities belonging to team 5XXXXXX35H were found.
Error Domain=IDEDistributionErrorDomain Code=1 "No valid iOS Development signing identities belonging to team 5XXXXXX35H were found." UserInfo={NSLocalizedDescription=No valid iOS Development signing identities belonging to team 5XXXXXX35H were found.}
** EXPORT FAILED **
```

The Apple certs were created only recently, and builds have been working ok.

**Comment by bFlood** [comment]
my iOS build has been going for over an hour, something seems wrong on the build servers

**Comment by camstuart** [comment]
I changed my tabris build settings to 1.10 instead of latest. Since the upgrade 'latest' is to new.

But my build has been running for 11 hours, and re-validating my other project has been running as long

**Comment by gosia-eclipsesource** [comment]
Issue solved, a new provisioning profile was required with push notification entitlement. We also identified an issue that caused the build job to be stuck in validating.

@bFlood please let us know If you are still experiencing build delays or unfinished builds.

**Comment by bFlood** [comment]
no, there are no more delays. it just happened that once last week
