### ISSUE TITLE
animate is throwing Promise is not defined error

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1128]
```
var comp = new tabris.Composite({......}).appendTo(page);

comp.animate({opacity:1}, {duration:200, delay:200, easing:'linear'});

```

This comp.animate is throwing 'Promise is not defined' in scratchPad dev.. Am I missing something ?

I am using cloud build and have added the dependency for Promise & whatwg-fetch

**Comment by cookieguru** [comment]
I'm guessing it's the same problem as #1129

**Comment by cpetrov** [comment]
@cookieguru You are right :+1: 

Polyfills now get served correctly, so closing this issue.
