### ISSUE TITLE
fetch is not working

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1129]
My earlier code developed never expected whatwg-fetch be in the dependencies. Now it fails

I added promise and whatwg-fetch in the dependencies as given in http://eclipsesource.com/blogs/2015/04/24/tabris-js-examples-network-access/ and even rebuilt the app.

The app is not booting up now. Also couldn't still get fetch working.

**Comment by cpetrov** [comment]
It seems we have a problem with our playground not delivering a module providing polyfills. Can you confirm you have this problem in the playground (https://tabrisjs.com/playground)?

By the way, the article you have referenced is outdated. Fetch and Promise are now available as part of Tabris.js, so you don't have to depend on external modules.

**Comment by natanraj** [comment]
Yes, i am unable to get fetch working in playground / scratchpad itself

**Comment by cookieguru** [comment]
I wonder if @ralfstx's 2e03c19a58961e2e081e2e49f5676f78cfc63479 is related.

**Comment by ralfstx** [comment]
@cookieguru Good catch. Chances are that the portal needs to be adjusted. I'll check with the connect guys.

**Comment by natanraj** [comment]
@ralfstx Any idea when can we expect the Fetch is working on Playground?

**Comment by ralfstx** [comment]
@natanraj We're looking into it right now and hope to have it fixed today.

**Comment by cpetrov** [comment]
The issue has been fixed.
