### ISSUE TITLE
WebView should allow to intercept page loads

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#113]
For the tabris-connect launcher we need to intercept a page load in the browser widget and extract a token from the url.

After we have handled the url we need to pass something back to the native client to indicate that we have handled the url. eg:

<pre lang="javascript">
browser.on("pageload", function(e) {
  if (handleUrl(e.url)) {
    return true;
  }
  return false;
});
</pre>

Currently tabris.js is not able to return any values from a "notify" operation.

**Comment by ralfstx** [comment]
I'd suggest to call the event `request`. Optionally, we could also introduce an event named `response`. The life cycle would be:

- request (the request is about to be sent)
- response (the response has been received)
- load (the page has been loaded)

Should these events also be triggered for background (ajax) requests?

**Comment by tbuschto** [comment]
Windows WebView does not provide events for XHR.

**Comment by mpost** [comment]
The agreed upon solution is to have a `navigate` notify operation on the client that returns a boolean value indicating to load the url. A value of `true` means to suppress the request.

JS Example:

```js
var webview = tabris.create("WebView", {
  layoutData: {left: 0, top: [urlInput, 8], right: 0, bottom: 0}
}).on("navigate",function (view, event) {
  if (event.url == "http://some-url.com") {
    event.preventDefault()
  }
}).appendTo(page);
```

**Comment by ifurnadjiev** [comment]
Intercepting "navigate" event works fine on both platforms now.
