### ISSUE TITLE
tabris kills self.commandDelegate.settings in cordova

### ISSUE THREAD

**Issue by ethanj** [eclipsesource/tabris-js#1131]
It seems that when building with tabris 1.x, ios plugins self.commandDelegate.settings does not correctly represent the 'preference' values in the config.xml file.

A simple way to see this is to build a minimal tabris app, and add the cordova-plugin-appsettings plugin. This plugin relies on self.commandDelegate.settings to retrieve the config values, and it is always empty.

Note that cordova-plugin-appsettings works correctly with a minimal cordova app not using tabris.

**Comment by ethanj** [comment]
@mpost any chance of getting this fixed in a nightly build?

**Comment by patrykmol** [comment]
Hello @ethanj. We will take a look at this and let you know when it's done.

**Comment by patrykmol** [comment]
@ethanj Hi. I have fixed the problem in 1.x and 2.x. Please give it a try.

**Comment by ethanj** [comment]
@patrykmol 
Hey there.

So the fix works, thanks!
However, it seems the nightly build has introduced some sort of bug... when i add in the platform using:

cordova platform rm ios
cordova platform add /..../tabris-ios

it gets close to complete, but then errors with:

Updating ios build to use workspace.
Adding schemes
Error: EEXIST: file already exists, mkdir '/..../platforms/ios/Pongalo.xcworkspace/xcshareddata'

This does not happen with the previous versions.

**Comment by patrykmol** [comment]
Those are Xcode temp data files. You can remove them safely. If this doesn't work can you try removing `platforms` and `plugins` (or at least `platforms/ios`) directories from Cordova project and the install platform again?

**Comment by ethanj** [comment]
@patrykmol 
if you notice, i mentioned that before adding the platform i removed it first, so this is starting from that whole directory not existing. It is definitely something in the tabris platform payload.

Also, what about the second issue of it not working on Android?

**Comment by ethanj** [comment]
@patrykmol Hey there.. I am hoping there is some progress on this? Any chance of getting a nightly that fixes the payload issue, and the Android issue?

**Comment by ethanj** [comment]
@patrykmol Sorry to keep pinging you, but I am blocked on this issue... any progress?
