### ISSUE TITLE
drawerAction dissapears after clicking "< Back" on iOS

### ISSUE THREAD

**Issue by bev-on** [eclipsesource/tabris-js#1132]
``tabris.ui.drawer.enabled = true;`` and ``drawerActionVisible: true`` on ``NavigationView`` is set and Drawer works perfectly (drawerAction is visible) until I open any page and click "< Back". After this, drawerAction icon is diapered.

If I close page using ``page.dispose()``, there is no problem and drawerAction is still visible. Only problem is with "< Back" button and only on iOS.

![untitled-1](https://cloud.githubusercontent.com/assets/11978242/22928841/897622ac-f2c9-11e6-944c-4d79ada1dd8f.png)

**Comment by karolszafranski** [comment]
Thanks, we're looking into this

**Comment by karolszafranski** [comment]
@bev-on I tried to reproduce the issue you described with the snippet I post below, and I'm unable to. Any additional configuration or actions are required?

```
tabris.ui.drawer.enabled = true;

var pageId = 0;

var navigationView = new tabris.NavigationView({
  left: 0, top: 0, right: 0, bottom: 0,
  drawerActionVisible: true,
}).appendTo(tabris.ui.contentView);

var appendNewPage = function() {
	var page = new tabris.Page({
	  title: 'Page ' + pageId
	}).appendTo(navigationView);

	new tabris.Button({
		text: 'Append new page'
	}).on('select', function() {
		appendNewPage();
	}).appendTo(page);

	new tabris.Button({
		text: 'Dispose this page',
		top: 'prev() ' + 20,
	}).on('select', function() {
		page.dispose();
	}).appendTo(page);

	pageId++;
}

appendNewPage();
```

**Comment by bev-on** [comment]
@karolszafranski your code works fine for me as well... 

After some tests, finally find what causes this behavior. I have ``tabris.Action`` added on main page, but this action should be active only on main page and not on another pages.

My solution was to set ``visibility: true`` when home page appeared and  ``visibility: false`` when home page disappeared on this Action.

Looks like if you set ``visibility: false`` to other actions, it doesn't affects drawerAction visibility, but when you set ``visibility: true`` again to this hidden action, drawerAction disappears  for some weird reason.

If you run following code, you can simulate this behavior:
```
tabris.ui.drawer.enabled = true;

var navigationView = new tabris.NavigationView({
    left: 0, top: 0, right: 0, bottom: 0,
    drawerActionVisible: true
}).appendTo(tabris.ui.contentView);

function loginPage(){
    return new tabris.Page({
        title: "Login",
        topLevel: false
    });
}

var testAction = new tabris.Action({
    id: "test_action",
    title: "test",
    placementPriority: "high"
}).appendTo(navigationView);

var homePage = new tabris.Page({
    title: "Home Page"
}).on("appear", function() {
    testAction.visible = true;
}).on("disappear", function() {
    testAction.visible = false;
});

new tabris.Button({
	text: 'Login Page',
    layoutData: {left: 20, top: 50}
}).on('select', function() {
	loginPage().appendTo(navigationView);
}).appendTo(homePage);

homePage.appendTo(navigationView);
```

Current workaround is to hide and show drawerAction as well with other action and it will fix this issue:
```
var homePage = new tabris.Page({
    title: "Home Page"
}).on("appear", function() {
    testAction.visible = true;
    navigationView.drawerActionVisible = true; // drawerAction visibility fix
}).on("disappear", function() {
    testAction.visible = false;
    navigationView.drawerActionVisible = false; // drawerAction visibility fix
});
```
if someone have same problem they can use this workaround temporarily.

**Comment by bev-on** [comment]
@review-squirrel is this issue solved? Changing visibility of another Action shouldn't be affecting Drawer Action. I can't see any reason why you closed this issue.

**Comment by cookieguru** [comment]
@bev_on: review-squirrel is a bot.  Best to check with @karolszafranski

**Comment by mpost** [comment]
@bev-on the issue has been fixed in ios. could you try the latest nightly build to see if it works our for you?

**Comment by bev-on** [comment]
@mpost @karolszafranski Thanks guys, this issue is fixed in latest nightly.
