### ISSUE TITLE
iOS Release builds failing again

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#1136]
iOS Release builds failing again - anyone else?

**Comment by fwaibel** [comment]
@bFlood Just a heads-up: Both of you jobs exited with:
```
The command "travis_wait grunt build deploy" exited with 137.
```
This exit code indicates someone sent a `kill -9`[1]. So nothing wrong with your build.
I'll restart one of your builds now.

[1] http://tldp.org/LDP/abs/html/exitcodes.html

**Comment by bFlood** [comment]
thanks, I was able to build another version successfully.
