### ISSUE TITLE
tabFolder tab selection

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1137]
Hello
How can i set the selected tab of tabFolder Widget
By example i have 3 tabs into my tabFolder but i want that my tabFolder start by the second Tab like whatsapp

**Comment by sand123** [comment]
I guess you should switch tab manually
```javascript
var tabFolder = new tabris.TabFolder({
    left: 0,
    top: 0,
    right: 0,
    bottom: 0
});

var tab1 = new tabris.Tab({
    title: "tab1"
}).appendTo(tabFolder);

var tab2 = new tabris.Tab({
    title: "tab2"
}).appendTo(tabFolder);

tabFolder.set("selection", tab2)

```
See [docs](https://tabrisjs.com/documentation/latest/api/TabFolder#select-widget-selection-options)

**Comment by ishigo1987** [comment]
thank you very much

**Comment by mpost** [comment]
I think @ishigo1987 is experimenting with the 2.0.0-beta1 where you could just write:

```js
tabFolder.selection = tab2;
```
