### ISSUE TITLE
problem with tabrisJsCard plugin on tabris 2.0.1 beta

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1139]
Hello i have a problem with this plugin
https://github.com/jokorivai/cordova-plugin-tabrisjs-card
i followed the syntax for a manualy import but i have this error
![screenshot_2017-02-15-19-10-13](https://cloud.githubusercontent.com/assets/12398336/22988554/d1260fb0-f3b2-11e6-9526-c07a6f581b50.png)

this is my code i have no problem with the require()
 let initializeCard = require('../modules/tabrisjscard.js').createCard;
   let card1 = initializeCard('Card1 Content', 'Card1 Title').appendTo(tabLesson);

**Comment by cookieguru** [comment]
Looks like the plugin isn't properly handling a missing options parameter.  Try passing `{}` as the third parameter or use [one of the other examples](https://github.com/jokorivai/cordova-plugin-tabrisjs-card#4-usage).

CC @jokorivai

**Comment by ishigo1987** [comment]
it's work thank you you save my night

**Comment by mpost** [comment]
Thanks @cookieguru. Closing this one.

**Comment by jokorivai** [comment]
@ishigo1987 this issue has been fixed and available on npm. Just update it.
