### ISSUE TITLE
drawer - visual issue v2.0.0beta1

### ISSUE THREAD

**Issue by maoamid** [eclipsesource/tabris-js#1140]
Hi,
Drawer had a strange border, I think is not hard to fix it as the 'drawer' from the right side looks fine.   
![screenshot_2017-02-16-09-54-22](https://cloud.githubusercontent.com/assets/15086210/23012346/70f15452-f42e-11e6-99e3-89da2ed563d4.png)
![screenshot_2017-02-16-09-56-20](https://cloud.githubusercontent.com/assets/15086210/23012345/70f02c58-f42e-11e6-85ae-3bc4351f0ac6.png)

**Comment by mpost** [comment]
@maoamid thanks for the report. What Android version is the lenovo phone running on?

**Comment by mpost** [comment]
We could reproduce the problem and will fix it asap.

**Comment by mpost** [comment]
We have fixed the issue and it will be available in the next nightly build.

**Comment by maoamid** [comment]
The Android version is 4.4.2
On note: I don't know if is a bug or not but, like in my screenshots, the tabris.device show me a lower resolution than this testing device (480x854 @ 218 ppi). It's true that if a multiply the values from tabris.device.get("screenHeight/") && tabris.device.get("screenWidth") I got the same resolution, but I suspect that the overall visual quality isn;t the best? (Sorry if i'm wrong, I didn't understand very well the dpi/ppi concept and how is implemented in tabris)

**Comment by mpost** [comment]
The device resolution is the resolution in pixels whereas the the scale factor allows you to scale your dimensions to be device density independent.
