### ISSUE TITLE
How to set drawer panel background color

### ISSUE THREAD

**Issue by FrencoJobs** [eclipsesource/tabris-js#1141]
...

**Comment by cookieguru** [comment]
The [`Drawer`](https://tabrisjs.com/documentation/latest/api/Drawer) extends [`Composite`](https://tabrisjs.com/documentation/latest/api/Composite), which extends [`Widget`](https://tabrisjs.com/documentation/latest/api/Widget) which has a [`background`](https://tabrisjs.com/documentation/latest/api/Widget#background) property.
```js
tabris.ui.drawer.background = 'blue';
```

**Comment by FrencoJobs** [comment]
Thanks.
