### ISSUE TITLE
Allow to set color with alpha component as "#aarrggbb"

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1142]
Currently you can not set a color with the # short form and a alpha channel.

It would be nice to set `#aarrggbb` (prefered) or `#rrggbbaa`

**Comment by ralfstx** [comment]
Why do you prefer the order ARGB instead of RGBA? That seems counter intuitive.

**Comment by cookieguru** [comment]
@mpost Can we close this one?

**Comment by mpost** [comment]
I haven't tested it personally yet but if @ralfstx concurs i would say we can close it.

**Comment by ralfstx** [comment]
So did you give up on this change? As far as I can see, this request is still unresolved.

**Comment by cookieguru** [comment]
@ralfstx I saw the PR was closed so I thought it was merged.  I don't remember closing it.

**Comment by ralfstx** [comment]
But it seems you did: https://github.com/eclipsesource/tabris-js/pull/1143
> cookieguru closed this 2 days ago

**Comment by cookieguru** [comment]
Probably happened automagically when I hosed my local git report and then pushed it.   The reopen button is disabled on my end.  I'll submit a new PR.

**Comment by ralfstx** [comment]
Implemented in #1179. Will be included in 2.0 RC1.

**Comment by mpost** [comment]
Happy to have the change included. :)
