### ISSUE TITLE
Change ActivityIndicator color on Android

### ISSUE THREAD

**Issue by iteearmah** [eclipsesource/tabris-js#1145]
Any way to change the color of the ActivityIndicator on Android?

**Comment by cookieguru** [comment]
Currently this is not possible, though it looks like it [could be added](http://stackoverflow.com/a/29451519/6771274).  Android superstar @mpost should be able to comment further.

**Comment by cookieguru** [comment]
I forgot, this was already answered in #986

+1 for `Canvas`, but you could do it just as well with an animated GIF.

**Comment by mpost** [comment]
The answer from @cookieguru is correct and so is my comment in the linked issue #986. The only way right now is to customize your app theme on Android.

https://tabrisjs.com/documentation/latest/build#android-specific-preferences

**Comment by mpost** [comment]
We could introduce new API to change the indicator color with a `tintColor`. Would also be supportable on ios.

**Comment by mpost** [comment]
Did not mean to close. Reopening.

**Comment by cpetrov** [comment]
Since Tabris.js 2.1, changing the color of the activity indicator is now supported on iOS and Android through the property [_tintColor_](https://tabrisjs.com/documentation/latest/api/ActivityIndicator.html#tintcolor).
