### ISSUE TITLE
Hide TextInput border or allow transparent borderColor (Android)

### ISSUE THREAD

**Issue by bev-on** [eclipsesource/tabris-js#1146]
If ``TextInput`` borderColor is set to ``transparent`` or ``rgba(0, 0, 0, 0)``, alpha value is ignored and borderColor is still visible (black color).

This is very annoying because default behavior looks ugly in many cases and prevents customization of UI.

There is no problem in iOS, transparent color actually hides border... Only problem is Android TextInput.

```
new tabris.TextInput({
  top: 20, left: '20%', right: '20%',
  message: 'Test Message',
  borderColor: 'transparent'
}).appendTo(tabris.ui.contentView);
```

Technically it's possible and it shouldn't be hard thing to do since many apps are using transparent border to customize UI.

WhatsApp for example:
![index](https://cloud.githubusercontent.com/assets/11978242/23100137/f4733234-f689-11e6-9c12-744fd619ca45.png)

**Comment by ishigo1987** [comment]
i try to do the same thing too like whatsapp.how can i achieve that

**Comment by bev-on** [comment]
@ishigo1987 this is not 100% same but you can use it as quick example...

```
var navigationView = new tabris.NavigationView({
  left: 0, top: 0, right: 0, bottom: 0,
  titleTextColor: '#fff',
  toolbarColor: '#087'
}).appendTo(tabris.ui.contentView);

var newPage = new tabris.Page({
  title: 'New message',
  background: '#eed'
}).appendTo(navigationView);

var newMessage = new tabris.Composite({
  left: 10, bottom: 10, right: 70, height: 48,
  background: '#fff',
  cornerRadius: 5,
  elevation: 1
}).appendTo(newPage);

var inputText = new tabris.TextInput({
  top: 0, left: 48, right: 48,
  message: 'Type a message',
  borderColor: 'transparent'
}).appendTo(newMessage);

new tabris.ImageView({
  left: 12, top: 12, width: 24, height: 24,
  image: {src: 'http://i.imgur.com/pZA7mUN.png'}
}).appendTo(newMessage);

new tabris.ImageView({
  right: 12, top: 12, width: 24, height: 24,
  image: {src: 'http://i.imgur.com/iYUv6Lp.png'}
}).appendTo(newMessage);

var voiceRecorder = new tabris.Composite({
  bottom: 10, right: 10, height: 48, width: 48,
  background: '#087',
  cornerRadius: 24,
  elevation: 1
}).appendTo(newPage);

new tabris.ImageView({
  centerX: 0, centerY: 0, width: 24, height: 24,
  image: {src: 'http://i.imgur.com/fjKW8dg.png'}
}).appendTo(voiceRecorder);
```
Result:
![new](https://cloud.githubusercontent.com/assets/11978242/23115143/07dc1c6c-f754-11e6-908c-228ce13f38da.png)

**Comment by mpost** [comment]
@bev-on you are right that this behavior is counter-intuitive to the users expectation. We will look into it. As a workaround you can set the `backgroundImage` to _null_ on the InputText. This will hide the underline (which is in fact the background image of the view on Android).

**Comment by ishigo1987** [comment]
ok thank you @bev-on  and @mpost

**Comment by mpost** [comment]
@bev-on @ishigo1987 We have fixed the issue in the latest nightly build for the 2.x stream. You could rebuild your app to make use of transparency in the `TextInput` (and `Picker`) `background` property.

**Comment by ishigo1987** [comment]
ok that's cool thank you @mpost
