### ISSUE TITLE
log messages on the 'server' side

### ISSUE THREAD

**Issue by camstuart** [eclipsesource/tabris-js#1149]
Is there a way to log messages in the nodejs output as opposed to the developer companion app?

Currently we can see GET requests like so:

```bash
[Fri Feb 24 2017 15:35:07 GMT+1100 (AEDT)] "GET /app.js" "Tabris.js/1610131019 CFNetwork/808.3 Darwin/16.3.0"
[Fri Feb 24 2017 15:35:07 GMT+1100 (AEDT)] "GET /modules/SignInPage.js" "Tabris.js/1610131019 CFNetwork/808.3 Darwin/16.3.0"
```

But it would be very helpful to output messages from application code here, as well as in the developer companion app with `console.log()`

**Comment by cookieguru** [comment]
http://eclipsesource.com/blogs/2015/04/17/debugging-tabris-js/

If you're using an Android device you can also do this with the Chrome Developer Tools.

**Comment by mpost** [comment]
In addition to the chrome dev tools (which is the easiest way) the console log output is also printed to the logcat console on Android when your app is build in debug mode.

**Comment by camstuart** [comment]
Thanks guys. I like the sound of breakpoints. Sounds like an android device is in order. Next stop..... eBay 😬

**Comment by cookieguru** [comment]
You can do it with Eclipse on iOS

**Comment by ralfstx** [comment]
Independent from the solutions presented here, it sounds like a useful and viable feature for the CLI / developer app. The developer app could call a logging endpoint provided by the CLI.

**Comment by ralfstx** [comment]
Now covered by https://github.com/eclipsesource/tabris-js-cli/issues/8
