### ISSUE TITLE
How to Build a Private repository

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1150]
Is there a way we can build the private repositories on Tabris Cloud Build ?

**Comment by natanraj** [comment]
I guess it is not possible..

**Comment by cookieguru** [comment]
Of course it's possible!  Taking a look at the [https://tabrisjs.com/pricing](Pricing) page it notes that the free Developer account comes with unlimited cloud builds for 1 private repo.  If you upgrade to the Pro plan you'll get unlimited cloud builds for all private repos.

The private repo should be seen in your list of repos when you click "Create App".  Try hitting the refresh button at the bottom of the list if you don't see it.  If you still don't see it, read through #917

**Comment by natanraj** [comment]
Yeah. I agree. I will go for Pro Plan soon..

**Comment by sand123** [comment]
Hi, guys! Any chances to get this fixed? I've tryed every suggested option and still see only public repoes

**Comment by mpost** [comment]
@sand123 Can you describe in more detail what you did and what you see?

**Comment by mpost** [comment]
If this is not related to the topic above please reopen a new issue.

**Comment by sand123** [comment]
I'm on developer plan and I cannot add private repo from Github in app.
I've revoked access in github account for tabris, granted again, deleted app and still - in repo list there're public repos only. Refresh list doesn't help

**Comment by ishigo1987** [comment]
Hello it's still not currently possible to see a private repository in the cloud build when you have a free account on Tabris.

**Comment by bezkel** [comment]
Same Problem here. Looks like this problem exists since four years.
Please fix this. Or take it away from freeplan. This was one of the points I choose this frameworks for testing.
