### ISSUE TITLE
Create App - Options

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1151]
How to build two separate apps one from Master and another from its own branch (I guess we can add only 1 repo against a app), Once created app that same repo couldn't be used for another app... 

Idea is i want to create a debug app from feature branch and production version from Master Branch

**Comment by mknauer** [comment]
I have the same problem in one of my projects, and the branches differ in only a few, but very important details (e.g. different URLs, some debug code removed, other little changes that should not be available in the production version, etc.).

We solved this by creating two build jobs, and I don't think there is a technical reason that prevents you from doing this. Maybe you have to specify the Git repository in the second build job manually, but I'm sure that it is doable.

One pitfall could be the build number in case you are using it somewhere in your version string. It _can_ be a problem in case you are running two different, independent build jobs.

**Comment by cookieguru** [comment]
@mknauer It's not possible to add a second:

![image](https://cloud.githubusercontent.com/assets/1888809/23297118/0d23aa60-fa2d-11e6-9cc5-a76374a56d50.png)

**Comment by natanraj** [comment]
@mknauer  @cookieguru I guess we can differentiate this only through 2 different build jobs (in settings we have a Branch field). I used this to differentiate that as totally as two apps though both of same repository

**Comment by mknauer** [comment]
We'll be looking into this issue.
Right now I would guess that it has to do with the _free_ versus _pro_ plan.

**Comment by cpetrov** [comment]
@natanraj @cookieguru Can you try creating the job by entering the repository URL on the _Git URL_ tab? For this configuration an SSH private key has to be additionally provided though.

<img width="864" alt="screen shot 2017-02-24 at 11 59 01" src="https://cloud.githubusercontent.com/assets/2341769/23301083/b16828b6-fa88-11e6-9e03-7d2d70e734c0.png">

**Comment by gosia-eclipsesource** [comment]
@natanraj Sorry, the above procedure described by @cpetrov won't work when you are on the Developer plan, as setting repository by Git URL is only available on Pro.
