### ISSUE TITLE
illegal config option: 0

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1153]
I recently added Tabris plugin for firebase and built it. Build is successful, but the app fails on launch.

Gives a the below error

```
Error : Illegal Config option: 0 at 
Function.extend(....tabris.js)
at .plugins/tabris-plugin-firebase/www/Messaging.js: 10:37
```

**Comment by cpetrov** [comment]
We have introduced breaking changes to make the Firebase plugin compatible with the current Tabris.js 2.x nightly. 

You could consume the plugin from a commit id if you are using Tabris.js 2.0.0-beta1:

```
<plugin name="tabris-plugin-firebase" spec="https://github.com/eclipsesource/tabris-plugin-firebase.git#3fa165fe072752391ad899716073a210e1bd63be" />
```

**Comment by natanraj** [comment]
@cpetrov so if i need to build for tabris2.0.0-beta1 i need to use the above spec ? Also is there any changes done on tabris-map too ? I see that is also failing after I totally removed the above firebase plugin..

**Comment by cpetrov** [comment]
Yes, for tabris-plugin-maps please use this commit ID:

```
<plugin name="tabris-plugin-maps" spec="https://github.com/eclipsesource/tabris-plugin-maps.git#7070770a64df5d6c90756999500a9497b42f3540" />
```

**Comment by mpost** [comment]
Once Tabris.js 2 goes stable we will publish final version of the `tabris-plugin-maps` and `tabris-plugin-firebase` to npm.

**Comment by maoamid** [comment]
I got the same error using `<plugin name="cordova-plugin-network-information" />`
(it worked until last week with tabris v2 nightly)

**Comment by cpetrov** [comment]
@maoamid Are you using other Cordova plugins as well?

**Comment by maoamid** [comment]
@cpetrov Yes, I use 3: 
`  <plugin name="cordova-sqlite-storage" spec="~1.5.3" /> `
 `  <plugin name="cordova-plugin-network-information" spec="1.3.1" /> `
  ` <plugin name="cordova-plugin-screen-orientation" spec="1.4.2" />`

**Comment by cpetrov** [comment]
@maoamid If you are using Tabris.js 2.x nightly, please make sure you have a dependency on the 2.x nightly module in your package.json:

```
  "dependencies": {
    "tabris": "https://tabrisjs.com/downloads/nightly-2.x/tabris.tgz"
  }
```

... and that you have selected `2.x-nightly` in the _Tabris.js Client Version_ job setting on http://tabrisjs.com

**Comment by maoamid** [comment]
Here is the complet error: 
> Error: Illegal config option: 0
Error: Illegal config option: 0
    at Function.extend (./node_modules/tabris/tabris.js:309:17)
    at getPlugin (./cordova.js:1002:40)
    at Object.cordovaBridge.exec (./cordova.js:1016:20)
    at tabrisExec (./cordova.js:1062:17)
    at NetworkConnection.getInfo (./plugins/cordova-plugin-network-information/www/network.js:49:5)
    at .<anonymous> (./plugins/cordova-plugin-network-information/www/network.js:60:8)
    at Channel.fire (./cordova.js:822:23)
    at ./cordova.js:1213:28
    at f (./cordova.js:694:33)
    at Channel.fire (./cordova.js:822:23)
deviceready has not fired after 5 seconds.
Channel not fired: onCordovaConnectionReady

**Comment by cookieguru** [comment]
@maoamid Are you still using 1.3.1 of cordova-plugin-network-information?  [Line 49](https://github.com/apache/cordova-plugin-network-information/blob/0079edbaa5e24419ea383d918cbe960d3d4cae99/www/network.js#L49) has no code on it.

**Comment by maoamid** [comment]
@cookieguru this are the specs I use.
Below are part of build log
> Discovered plugin "cordova-plugin-network-information" in config.xml. Adding it to the project
Fetching plugin "cordova-plugin-network-information@1.3.1" via npm
Installing "cordova-plugin-network-information" for android
ANDROID_HOME=/usr/local/android-sdk/
JAVA_HOME=/usr/lib/jvm/java-8-oracle
Subproject Path: CordovaLib
Incremental java compilation is an incubating feature.
:clean
:CordovaLib:clean
BUILD SUCCESSFUL
Total time: 1.535 secs
Discovered plugin "cordova-plugin-screen-orientation" in config.xml. Adding it to the project
Fetching plugin "cordova-plugin-screen-orientation@1.4.2" via npm
Installing "cordova-plugin-screen-orientation" for android

**Comment by natanraj** [comment]
@cookieguru i could get past the illegal option issue, though i didn't get any cordova error as @maoamid  mentioned.

But now my scratchpad is not working. It is not able load the scripts when I click the scratchpad row ont he dev app... Has something gone wrong in beta ?

**Comment by cookieguru** [comment]
@natanraj What error are you getting with the scratchpad?

**Comment by natanraj** [comment]
@cookieguru When i click the scratch pad on My Scripts tab -- it says - Couldn't establish connection - 
Couldn't find file https://preproduction..../package,json

Recently from backend my plan was moved from Dev to Pro. Is it a cause ?

**Comment by mpost** [comment]
@maoamid As @cpetrov suggested if you are on 2.x nightly you have to make sure that you are using the 2.x nightly tgz in your package.json and build with with the _2.x-nightly_ on tabrisjs.com.

@natanraj Is the preproduction url in your last comment the entire url you are seeing? That is of course not expected. We will look into it.

**Comment by natanraj** [comment]
@mpost since i was lazy to type the entire URL, i just provided start and end..

**Comment by maoamid** [comment]
@mpost, this is how I tested, using 2.x nightly tgz in your package.json

**Comment by natanraj** [comment]
@mpost in case you are interested, this is the full URL --  https://preproduction.tabrisjs.com/api/v1/me/scratchpad/natanraj/package.json

And when i traverse this on browser, getting this.. 
{"dependencies":{"tabris":"https://tabrisjs.com/downloads/2.0.0-beta1/tabris.tgz"},"title":"My Scratchpad","description":"A playground application","main":"app.js"}

Two days back, i was upgraded to Pro Plan.

**Comment by natanraj** [comment]
When i downloaded the fresh Dev app from PlayStore it works... But not the Developer mode of my own app. What could be the issue for scratchPad ?

**Comment by cookieguru** [comment]
@natanraj Build your Dev app again

**Comment by natanraj** [comment]
i built just as it was yesterday (without any settings change), still the issue continues.

**Comment by irbull** [comment]
@natanraj Can you copy any content you have on your scratchpad to another file, then try "Restore Default" at the bottom of the scratchpad. This will restore the default "Hello, World" script, but it will also reset the deploy defaults. Then copy your code back.

I wonder if there is something out of sync.

Again, make sure you copy any code you have in the scratchpad before restoring defaults.

**Comment by irbull** [comment]
@natanraj Also, were did "preproduction" come from? AFAIK, we don't use that (expect for testing). Did you enter that?

**Comment by natanraj** [comment]
@irbull , i still get the same issue. 'the preproduction' still comes by itself. I didn't enter any...

**Comment by cpetrov** [comment]
@natanraj The scratchpad should be working now. Please open a new issue if you still have this problem.

**Comment by natanraj** [comment]
i am moving to 2.0.0-beta2 in Cloud Build settings. Also changed by package.json to reflect this dependencies.
```
"dependencies": {
    "tabris": "2.0.0-beta2",
    "underscore": "^1.8.3"
  }
```
Upon successful Debug build, the app is installed. but it doesn't run. The console shows
```
 deviceReady has not fired after 5 seconds.
channel not fired: onCordovaaInfoReady
```

What is the way around ?

**Comment by cookieguru** [comment]
`package.json`:
```json
"dependencies": {
  "tabris": "nightly",
}
```
Build settings:
* Tabris.js Client Version: `2.x-nightly`

**Comment by natanraj** [comment]
@cookieguru : the build is failing on tabris-maps. what repo i need to use for this?  I have this below plugin per suggestion sometime back when working for beta1

`<plugin name="tabris-plugin-maps" spec="https://github.com/eclipsesource/tabris-plugin-maps.git#7070770a64df5d6c90756999500a9497b42f3540">
        <variable name="ANDROID_API_KEY" value="mykey" />
    </plugin>`

**Comment by cookieguru** [comment]
@natanraj `HEAD` works great with `2.x-nightly` and `nightly`; just drop the SHA off your spec.
