### ISSUE TITLE
video widget always displayed on background of others (Tabris-js 2.0 nightly)

### ISSUE THREAD

**Issue by maoamid** [eclipsesource/tabris-js#1155]
Possible case: in a Composite, if there is a video widget and another one, video Z-index is always lower (maybe) cause the second widget always is up over video, no matter the order they are declared

**Comment by mpost** [comment]
What platform are you seeing this behavior on? The video widget should adhere to the the same child order than regular views.

**Comment by maoamid** [comment]
I saw this behaviour when in this situation, but maybe my conclusion was wrong:
in a widget full layout (top, bottom, left, right: 0) on upper section a video widget, and in lower section page a tabFolder. Tested on beta 1 is ok, on nightly buid, the tabfolder is displayed over the video.

**Comment by cpetrov** [comment]
@maoamid Please reopen if configuring `elevation` didn't solve your problem.
