### ISSUE TITLE
Does sessionStorage really serve no purpose?

### ISSUE THREAD

**Issue by wilsonna** [eclipsesource/tabris-js#1157]
The documentation states

> The `sessionStorage `is not supported, as it would serve no purpose in a non-browser environment.

However, I am currently encountering a situation where the session created by a WebView persists even after I've terminated and relaunched the app, resulting in an invalidated login. Doing `localStorage.clear()` does not clear the cookie, and I have to go to the app settings to clear the data before I can login again.

I notice this problem only happens in Android and not iOS. I'm curious if `sessionStorage.clear` would help to resolve this problem.

**Comment by mpost** [comment]
The `sessionStorage` would be the equivalent of the `localStorage`. This `localStorage` is separate from the `WebView` widget. The `WebView` should maintain its own cache of cookies which should persist beyond app restarts.

If the cookies are not maintained on iOS across app restarts that would be an issue.

**Comment by wilsonna** [comment]
In that case, is there any avenue to clear the cookies intentionally? CookieMaster plugin appears to work, but I would like to know if there are other ways without having to use a plugin.

**Comment by mpost** [comment]
@wilsonna Cookie handling in the WebView follows the regular browser mechanism to always send to cookies matching the same request domain.

**Comment by mpost** [comment]
Closing this issue for now.
