### ISSUE TITLE
app.js created with tabris init non-compliant with Tabrisv2

### ISSUE THREAD

**Issue by derFaizio** [eclipsesource/tabris-js#1160]
The default app.js file created with tabris init is still creating a file with 1.x API with 
`page.open()` and `topLevel: true`

**Comment by mpost** [comment]
We have verified the correct behaviour of the cli. Please make sure that you are using the latest version (`0.2.0`): https://www.npmjs.com/package/tabris-cli

```shell
npm install -g tabris-cli
```

**Comment by derFaizio** [comment]
Working as expected after I uninstalled the generator-tabris-js package.
