### ISSUE TITLE
Can I do a local build to without a MAC machine?

### ISSUE THREAD

**Issue by iteearmah** [eclipsesource/tabris-js#1161]
Can I Use this [https://tabrisjs.com/api/v1/downloads/2.x-nightly/ios](url) to build an IOS .ipa file?

**Comment by mpost** [comment]
Local builds for iOS are only possible with an Apple mac computer.

**Comment by maoamid** [comment]
@mpost can you guide me how to test a build(.ipa file) . It can't be installed on a iphone even if is build with a dev profile. I need a build cause I use cordova plugins.

**Comment by gosia-eclipsesource** [comment]
@maoamid You need to transfer the .ipa to your device using iTunes or Xcode. iTunes is available for Mac and Windows.
There may be other ways e.g. using a service like https://www.diawi.com/ (I haven't tried it)

**Comment by cookieguru** [comment]
[TestFlight](https://developer.apple.com/testflight/) works great too, but a Mac is required.

**Comment by maoamid** [comment]
@gosia-eclipsesource I tried this and it's not working with iTunes. It doesn't throw any error, just keep instaling status. On iOS 5 and 6, both, the icon apear and disappear suddenly. (Build with production and devel provision). I know is not a problem on tabris, I just wanna know how other people do this, how they work. Xcode? I will try to find a mac a few days. (diawi not worked for me yesterday). Thank you

**Comment by maoamid** [comment]
@cookieguru I need Xcode for this right?

**Comment by cpetrov** [comment]
@maoamid If you have issued your Apple certificate and provisioning profile with a free developer account, installation by clicking on the .ipa download link on https://tabrisjs.com or by installing the .ipa through iTunes is not possible. If you have a free Apple developer account, you can only install the .ipa using Xcode or with [libimobiledevice](http://www.libimobiledevice.org).

**Comment by maoamid** [comment]
@cpetrov thank you for pointing that so clear.

**Comment by cookieguru** [comment]
@maoamid Xcode is not required to use TestFlight

**Comment by maoamid** [comment]
@cookieguru @gosia-eclipsesource thank for helping me. I managed to publish, test .ipa files using ApplicationLoader and TestFlight. It's super easy this way for me, maybe this info can help others, without using Xcode
