### ISSUE TITLE
How can I use box shadow?

### ISSUE THREAD

**Issue by FrencoJobs** [eclipsesource/tabris-js#1162]
I didn't find documentation about this.I just want to create a card with box shadow.Tell me ,if someone know.

**Comment by cookieguru** [comment]
https://github.com/jokorivai/cordova-plugin-tabrisjs-card

**Comment by mpost** [comment]
You can also just use `elevation` and `cornerRadius`.

Note that on Android your "card" has to have a background set to apply the elevation shadow.
