### ISSUE TITLE
Setting font on canvas save/restore

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#1169]
I am seeing behavior on iOS related to save and restore when setting font

```
context.font='13px';
context.save();
context.font='12px';
context.restore();
assert(context.font==='13px')//false
```

It seems it does not restore the font value from the stack properly. I am on tabris 1.10, not sure if its an issue on android as well. 

It also seems that setting font size is ignored when actually drawing.

**Comment by mpost** [comment]
I can also confirm the same issue under Android

**Comment by ralfstx** [comment]
Actually, the `CanvasContext` does not yet support the `font` property.

**Comment by ralfstx** [comment]
Depends on #84.

**Comment by mpost** [comment]
Closing since #84 has been implemented.
