### ISSUE TITLE
(Bug?) 2.0 Developer app does not support localStorage

### ISSUE THREAD

**Issue by nozomi199** [eclipsesource/tabris-js#1170]
I have tried to perform this function by following these code like:
let ds = localStorage;
ds.setItem("timezone",8);
console.log(ds.getItem("timezone"));

but it also returns null or undefined value, it let me to perform wrong calculation result when taking value from localStorage

in developer apps 1.0, it will no storage value when each startup my test app, but it can perform localStorage correctly.

-------- update on 2017/03/04 22:13 GMT+8/HKT --------
I have tried on cordova run android --release
localStorage storage is worked
platform: cordova 6.5.0, tabris 1.1.0 using local build

Is tabris does not support localStorage in debug mode?
-------- update on 2017/03/05 18:50 GMT+8/HKT --------
Tested on 2.0 beta release build, it works successfully, but.....
it tabris developer apps does not support localStorage?
and cordova build does not support user input passphase when release-key.properties file(does not contains any password) is placed in platform/android folder

**Comment by nozomi199** [comment]
In addition, my test result is tabris 1.10 release/debug build also does not support localStorage but developer apps does.

**Comment by ralfstx** [comment]
Tested your snippet in the developer app with Tabris.js 1.10 and latest 2.0.0-beta version. In both versions, it correctly prints "8" to the console:
```js
let ds = localStorage;
ds.setItem("timezone", 8);
console.log(ds.getItem("timezone"));
```

**Comment by cookieguru** [comment]
@ralfstx Console in release builds?

**Comment by ralfstx** [comment]
@cookieguru Not sure what you mean. Can you reproduce the issue? The presence of localStorage is unrelated to the build type.

**Comment by cookieguru** [comment]
@ralfstx Haven't tried to reproduce the issue but @nozomi199 notes the issue does not occur in a debug build.

**Comment by ralfstx** [comment]
@cookieguru No, if I understand correctly, he said it would work with `--release` but not in debug mode.

However, as we've release apps running that use `localStorage`, I'm convinced that the problem was in the application code. Please reopen if you can reproduce the issue.
