### ISSUE TITLE
Server Sent Event

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1171]
Hi i have a question can i use a server-sent-event Api with tabris?
i'm currently building an chat app and i don't want to use websocket(too hard to implement with php)

**Comment by cookieguru** [comment]
Server Sent Events are not currently supported.  You could set up [Ratchet](http://socketo.me/) or just use a Node.js server.  [Here's a tutorial](http://web.archive.org/web/20160723055059/http://www.technology-ebay.de/the-teams/mobile-de/blog/connecting-php-and-node-with-redis-pub-sub-and-sockjs.html#blog_indicator) (albeit an old one) for setting up a Node server and using Redis' PubSub functionality to get data from your PHP app over Web Sockets.

**Comment by ralfstx** [comment]
We don't have plans to support server sent events. WebSockets are the way to go.
