### ISSUE TITLE
Question: Plans for Firebase features support

### ISSUE THREAD

**Issue by derFaizio** [eclipsesource/tabris-js#1174]
Are there any plans in the near future to support the following Firebase features?

1. Authentication
2. Real-time database
3. Remote Config

**Comment by mpost** [comment]
We are currently supporting Firebase Cloud Messaging with the plugin https://github.com/eclipsesource/tabris-plugin-firebase on Android. We want to extend its capabilities in the future to cover a brought range of firebase features. PRs are welcome. :)

**Comment by mpost** [comment]
Closing this issue for now. Please target any further questions towards the https://github.com/eclipsesource/tabris-plugin-firebase repo.
