### ISSUE TITLE
App crash reporting

### ISSUE THREAD

**Issue by iteearmah** [eclipsesource/tabris-js#1176]
Any way to get crash reports?

**Comment by iteearmah** [comment]
Is Firebase recommended?

**Comment by iteearmah** [comment]
Want a way to intercept crashes and forward them and store the data to a server

**Comment by cookieguru** [comment]
There are a couple of suggestions in #1103 and there are dozens of other solutions that will provide the same service. 

If you're looking for a solution to catch native errors rather than JavaScript errors you'll need to look for a Cordova plugin.  Let us know what you find and how it works out.

**Comment by mpost** [comment]
Normal crash reports from an Android app are reported in the Play Store console. Besides that you can use other crash reporting tools like @cookieguru suggested. Firebase analytics being one of them.

**Comment by cpetrov** [comment]
@iteearmah Please reopen if the proposed solutions don't work for your requirements.
