### ISSUE TITLE
ios release build failed - v beta

### ISSUE THREAD

**Issue by maoamid** [eclipsesource/tabris-js#1178]
`Warning: Command failed: cordova build --verbose --device --buildConfig=tabrisBuildConfig.json --release`
`* ARCHIVE FAILED *`
`The following build commands failed:`
`	Check dependencies`
`(1 failure)`
`Error: Error code 65 for command: xcodebuild with args:...`

and:
`Done. Your build exited with 1.
/Users/travis/build.sh: line 159: shell_session_update: command not found`

**Comment by maoamid** [comment]
something similar?!: [https://community.citra-emu.org/t/why-is-there-no-more-macos-builds-for-citra-recently/771](url)

**Comment by patrykmol** [comment]
Error 65 usually means mismatch of provisioning profile and signing certificate. Can you provide a link to full build log?

**Comment by maoamid** [comment]
@patrykmol oh, I see, let me remake my provisioning profile, I set a passwd for it, maybe it shouldn't, and if is not working I will try to send you the log.

**Comment by maoamid** [comment]
@patrykmol full log details: [https://drive.google.com/open?id=0Bx63vznYsBdIR0dTaVM3NTU0dHc](url)

**Comment by patrykmol** [comment]
Here's the problem:
```
Provisioning profile "FundatiaAlfaOmegaAppStore" doesn't include the aps-environment entitlement.
Code signing is required for product type 'Application' in SDK 'iOS 10.0'
```
You need to enable push notification in developer portal for your app bundle id. Then you have regenerate provisioning profile and update them on tabrisjs.com

**Comment by maoamid** [comment]
@patrykmol thank you, I missed that
