### ISSUE TITLE
build service - error 137

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#1181]
I have an app that takes awhile to compile, is there an arbitrary limit on how long build processes run on the tabris servers? I'm getting error 137 (Kill process?) a lot more these days

``` log The command "travis_wait grunt build deploy" exited with 137.```

**Comment by bFlood** [comment]
I get a lot of these now, what does this error mean?

**Comment by jonek** [comment]
We just increased the default timeout (20 minutes) of Travis builds to 40 minutes. Please let us know if this lets more of your builds succeed.

**Comment by jonek** [comment]
Please watch out for a line like this in your future detailed logs:
`travis_wait 40 grunt build deploy`

**Comment by jonek** [comment]
Almost all of your iOS builds exceeded the former default timeout of 20 minutes. Is there anything special in your builds that makes them run so long?

**Comment by bFlood** [comment]
thank you, that seems to have helped. the app has a lot of plugins (one of which is huge) so I'm assuming that's why the build process takes so long

on another note, I'm experimenting with the cordova-HTTP plugin to move all http requests to a background thread (note - Does the native tabris http support run on the main thread? it seems to). On Android, cordova-HTTP has helped, the app feels more responsive. The only issue is I can't get the iOS version to build. The issue is cordova-HTTP uses AFNetworking, which is used by the tabris native client. When I compile, it throws duplicate symbol errors. If I remove AFNetworking from the plugin, then it fails to compile. Cordova seems to deal with this issue in between plugins but I'm not sure what happens when the tabris native code uses them as well. Any help here would be appreciated. 
https://github.com/wymsee/cordova-HTTP
