### ISSUE TITLE
Web Assembly supports by TabrisJS

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1184]
Hello everyone
Is it possible to have WebAssembly in Tabris in the near future?

**Comment by ralfstx** [comment]
Tabris executes application code in a JavaScript VM. Given that WebAssembly is not yet supported by Safari, my guess is that *native* support for WebAssembly is rather unlikely to be possible in the near future. You may still be able to run WebAssembly code on asm.js.

**Comment by ishigo1987** [comment]
safari is for ios....on android it's not possible to execute web assembly?

**Comment by mpost** [comment]
@ishigo1987 You can find out which browsers support WebAssembly here: http://caniuse.com/#feat=wasm

**Comment by cookieguru** [comment]
Android uses [J2V8](https://github.com/eclipsesource/J2V8) which does not currently support WebAssembly

**Comment by ishigo1987** [comment]
Do you know if j2v8 has planned a possible support of webAssembly?

**Comment by ishigo1987** [comment]
hold on....according to this link 
http://eclipsesource.com/blogs/2015/05/28/implementing-webworkers-with-j2v8/
j2v8 support web workers!!! is it possible to use web Workers in tabrisJS?

**Comment by cookieguru** [comment]
A "C" VM for a JavaScript VM for Java?

You could do [JNI](https://en.m.wikipedia.org/wiki/Java_Native_Interface) with J2V8, but given that there's a huge overhead with JNI the performance of going from JS to Java to something else would be abysmal.

I think your best be would be to take a look at [custom widgets](https://tabrisjs.com/documentation/latest/custom-widgets-android#building-upon-cordova-infrastructure) since support exists on Android and iOS _today_.

**Comment by ishigo1987** [comment]
Do you know if j2v8 has planned a possible support of webAssembly?

**Comment by ishigo1987** [comment]
hold on....according to this link
http://eclipsesource.com/blogs/2015/05/28/implementing-webworkers-with-j2v8/
j2v8 support web workers!!! is it possible to use web Workers in tabrisJS?

**Comment by mpost** [comment]
@ishigo1987 WebWorkers are not the same as WebAssembly. WebWorkers are supported by J2V8 as started in the blog post but not yet exposed in Tabris.js.

**Comment by ishigo1987** [comment]
yes @mpost  i know that webWorker are not the same as WebAssembly don't worry!!
I have two questions please
1)Do you planed to support WebWorkers in Tabris.Js in the near future?
2)Do you planed to support WebAssembly in Tabris.js in the near future?

**Comment by mpost** [comment]
WebWorkers are a freature that is on our list of things to add in the near future. WebAssembly is a rather new technology so it is not high priority just yet.

Could you tell us what you try to achieve?

**Comment by ishigo1987** [comment]
with webWorkers i want to make some task like multiple ajax request or with ServiceWorkers a background synchronization.
with webAssembly nothing for now it was just a question

**Comment by cookieguru** [comment]
@ishigo1987 If you want to run multiple asynchronous web requests, you can use [fetch](https://tabrisjs.com/documentation/latest/w3c-api#fetch) with [`Promise.all`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all):
```js
let urls = ['http://tabrisjs.com', 'http://eclipsesource.com/'];
Promise.all(urls.map(url => fetch(url)))
.then(resp => Promise.all(resp.map(r => r.text())))
.then(result => {
    // ...
});
```

**Comment by ralfstx** [comment]
This is out of scope for now. Once WebAssembly is supported on iOS and Apple terms allow the use of it apps, we can re-evaluate.
