### ISSUE TITLE
Support JSX for JS (Babel)

### ISSUE THREAD

**Issue by nozomi199** [eclipsesource/tabris-js#1188]
In traditional tabris development cycle, we may create many component from scratch. 
We may  need a better method to improve these job.
From react and nativescript, they used JSX to slove the proble, but tabris not.
I hope tabris js can support smarter solution (eg. JSX options) in future.

Currently, I have found a alternative solution(but not smart) for using JSX in tabrisjs.

First, install babel js transcripter
[https://babeljs.io/docs/setup/](https://babeljs.io/docs/setup/)
> npm install --save-dev babel-cli babel-preset-es2015

Second, install jsx transcripter plugin(i'm not sure use both or transform-h-jsx only)
[https://babeljs.io/docs/plugins/syntax-jsx/](https://babeljs.io/docs/plugins/syntax-jsx/) , [https://www.npmjs.com/package/babel-plugin-transform-h-jsx
](https://www.npmjs.com/package/babel-plugin-transform-h-jsx)
> npm install --save-dev babel-plugin-syntax-jsx babel-plugin-transform-h-jsx

Third, setup .babelrc like following(may be different):
```javascript
{ 
	"presets": ["es2015"],
	"plugins": ["transform-es2015-modules-commonjs",
		"transform-h-jsx",
		"syntax-jsx"]
}
```

Then, we need to add a module to export a method called "h":
```javascript
import tabris from "tabris";
export default function h(obj,param, child = []) {
    let o = new obj(param)
    if(child.length > 0) o.append(child);
    return o;
}
```

After all , in your main development, before you using JSX, you may include the module which includes the h method, and the following sample program will help you to study this alternative method.
In this case, the module h is stored in the lib folder.

```javascript
import 'tabris';
import h from "./lib/h";
let items = [
	{id:0, name:"a"},
	{id:1, name:"b"},
	{id:2, name:"c"},
]
let a = 
	<tabris.Composite id="scroll" left="0" top="0" >
		<tabris.TextView id="lblA" left="10" top="10" text="Title A" />
		<tabris.TextView id="lblB" left="10" top="prev()" text="Title B"/>
		<tabris.TextView id="lblC" left="10" top="prev()" text="Title C" />
		<tabris.Picker id="picker" left="10" top="prev()" items={items} itemText={(i)=>i.name} />
	</tabris.Composite>;
a.appendTo(tabris.ui.contentView);
```

**Comment by cookieguru** [comment]
Check this out:

http://eclipsesource.com/blogs/2016/02/29/tabris-js-declarative-ui-in-100-lines-of-functional-programming/

**Comment by nozomi199** [comment]
Like this?
I will update the event handle support in later.
```JavaScript
const t = require("tabris");

/**
 * transform module tree
 */
function C(b) {
	return h(b.o, b.p, b.c);
}
/**
 * Main function to transform Component from param's object
 */
function h(o,p={},c=[]) {
	if(typeof p !== "object") p = {};
	let obj =( typeof o === "object") ? o : new o(p);
	if(Array.isArray(c) && c.length > 0) {
		obj.append(
			c.map(function(_p) {
				if(
					_p.hasOwnProperty("o") &&
					_p.hasOwnProperty("p") &&
					_p.hasOwnProperty("c") 
					)
					return h(_p.o, _p.p, _p.c);
				return _p;
			})
		);
	}
	return obj;
}
/**
 * predefined component based transform
 */
const COMP = (param, child=[]) => h(t.Composite, param, child);
const TEXT = (param) => h(t.TextView, param);
/**
 * param tree example
 */
C(
	{o:t.Composite, p:{id:"c1",centerX:0,top:10},c:[
		{o:t.TextView, p:{id:"lbl1", top:0, centerX:0, text:"lbl1"},c:[]},
		{o:t.TextView, p:{id:"lbl2", top:"prev()", centerX:0, text:"lbl2"},c:[]},
		{o:t.TextView, p:{id:"lbl3", top:"prev()", centerX:0, text:"lbl3"},c:[]},
		TEXT({id:"lbl4", top:"prev()", centerX:0, text:"lbl4"})
	]}
).appendTo(tabris.ui.contentView);
/**
 * Component tree example
 */
COMP({centerX:0, bottom:10}, [
	TEXT({text:"Line 1", top: 0, centerX:0}),
	TEXT({text:"Line 2", top: "prev()", centerX:0}),
	TEXT({text:"Line 3", top: "prev()", centerX:0}),
	TEXT({text:"Line 4", top: "prev()", centerX:0}),
]).appendTo(tabris.ui.contentView);
```

**Comment by ralfstx** [comment]
With many code editors coming with JSX support, that sounds like an interesting idea. What does the babel plugin produce?

Chances are that JSX support can be implemented outside of Tabris.js, either as a shim for the output of the babel plugin, or as a custom babel plugin...

**Comment by ralfstx** [comment]
Tabris.js 2.0 RC2 supports JSX, but currently only with typescript.

**Comment by tbuschto** [comment]
It technically also works with JS via babel or tsc, we would just have to document the setup. Not sure why one would use it without TypeScript though.

**Comment by tbuschto** [comment]
We have documented now how to use it with JavaScript vis the TypeScript compiler. I would consider this fixed, since the result is the same. If there is a definite need to use Babel, please re-open.
