### ISSUE TITLE
ImageView w/ scale: image position inconsistent between iOS and Android (v1.10)

### ISSUE THREAD

**Issue by patbenatar** [eclipsesource/tabris-js#1190]
I'm trying to create an animation where the image is much wider than the viewport and using translateX we pan the image through the viewport (from left: 0 to a negative left offset). Works great on iOS where it draws the image starting from top/left, but on Android it draws the image as if it's center X, like so:

![tabris-issue](https://cloud.githubusercontent.com/assets/453695/24014550/a537f58e-0a42-11e7-884d-f996eccd57ee.gif)

The area to the left is just getting cropped on Android. (Even if I try moving the ImageView to the right with a positive left offset, it doesn't reveal more of the image — just cropped)

Code is basically this:

```typescript
background = new tabris.ImageView({
    image: {
        src: "image.jpg",
    },
    scaleMode: "fill",
    layoutData: {
        top: 0,
        bottom: 0,
        left:  0,
        width: computedBackgroundImageWidth
    }
}).appendTo(rootComposite);

background.animate({
    transform: {
        translationX: (computedBackgroundImageWidth - screen.width) * -1
    }
}, {
    delay: 0,
    duration: 40000,
    repeat: 1000,
    reverse: true,
    easing: "linear"
});
```

Thanks!

**Comment by patbenatar** [comment]
Hmm it seems that the right side is also getting cropped.. as if on Android, it won't allow me to draw an ImageView that is larger than the viewport.

**Comment by cpetrov** [comment]
This is an issue of the 1.x Android client, which has been fixed in 2.x. As a workaround in 1.x, you can set a negative `right` margin instead of `width` on the `ImageView`, i.e.:

```js
[...]
background = new tabris.ImageView({
    image: {
        src: "image.jpg",
    },
    scaleMode: "fill",
    top: 0,
    bottom: 0,
    left:  0,
    right: -computedBackgroundImageWidth + screen.width
}).appendTo(rootComposite);
[...]
```

**Comment by patbenatar** [comment]
Thanks! That worked. 

2.0 seems to be a major improvement but my initial look at it makes me think the migration path for existing apps is pretty painful. Is that right?

**Comment by cookieguru** [comment]
@patbenatar It depends on your codebase.  There's a [migration guide](https://github.com/eclipsesource/tabris-js/blob/master/doc/migration-guide.md) that spells out all the breaking changes.

If you developed against <1.7.0 then you will for sure have to migrate all your `tabris.create()` calls to `new tabris.x`.  Otherwise the biggest hurdle will be the new navigation changes.

**Comment by patbenatar** [comment]
This is great, thanks! The NavigationView was my biggest worry but it looks like there's an easy polyfill for that. Cheers.

**Comment by mpost** [comment]
Closing this issue as resolved. Please reopen of you have any more problems.
