### ISSUE TITLE
XML

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1191]
is it possible to parse a xml with tabris?parse a xml rss flux by example

**Comment by cookieguru** [comment]
No, but there are plenty of packages on npm that will.  Take a look at the [tabris-js-template-app](https://github.com/eclipsesource/tabris-js-template-app/) for another implementation.

**Comment by ishigo1987** [comment]
do you have an example of npm package?

**Comment by cookieguru** [comment]
No, but [this](https://www.npmjs.com/search?q=xml) should get you started.

**Comment by ishigo1987** [comment]
thank you

**Comment by cpetrov** [comment]
A few modules I've tested which should work with Tabris.js: 
* [`xmldom`](https://www.npmjs.com/package/xmldom)
* [`xml-js`](https://www.npmjs.com/package/xml-js) 
* [`sax`](https://www.npmjs.com/package/sax)

**Comment by ishigo1987** [comment]
thank you

**Comment by cpetrov** [comment]
:+1: Please reopen if these don't work for you.
