### ISSUE TITLE
Scratchpad of tabris.js 2 is failing on 'Cannot find module polyfills'.

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1194]
I am seeing issues post tabris.js beta 2 is shown in the scratchpad. Though i restored default, it doesn't help me. I even installed the latest tabris.js 2 app from Playstore..

Any suggestions

**Comment by mpost** [comment]
@natanraj Thanks for the heads up. We have fixed the scratchpad.

**Comment by natanraj** [comment]
thanks. it works.

**Comment by natanraj** [comment]
The below code was working earlier. But not any more. Here container is a cell

 ```
container.on('change:item', function(target, item){
        target.find('#ceremonySlot').first().text = item.when + '\n'+item.ceremony;
      });
```

it says target.find is not a function

**Comment by natanraj** [comment]
this is on my scratchpad

**Comment by ralfstx** [comment]
@natanraj Your code needs to be adjusted to the changes to the event listener API in 2.0.0.beta2. Sorry for the inconvenience.

See https://github.com/eclipsesource/tabris-js/blob/master/doc/migration-guide.md

**Comment by natanraj** [comment]
It is a big change in most of my code.

**Comment by mpost** [comment]
@natanraj The scratchpad represents the latest developmentstream of Tabris.js. You can still build and run your app against 1.x if you choose to.

**Comment by ralfstx** [comment]
@natanraj Again, sorry for the inconvenience. We didn't take this decision easy. However, this change allows us to provide more information on events, like type, timeStamp, additional parameters etc. without introducing further breakage, so we decided to make this change before 2.0.

**Comment by natanraj** [comment]
I understand. May I know what was the earlier API reference for Video (or in general all widgets) ?

**Comment by cookieguru** [comment]
@natanraj https://tabrisjs.com/documentation/1.10/api/Video

**Comment by natanraj** [comment]
I am seeing this issue now. polyfill.js error thrown. Sometime back it was going with tabris.js unable to be found..

Is any backend changes going on

**Comment by cookieguru** [comment]
@natanraj You've posted about this three times.  One post is sufficient.
