### ISSUE TITLE
how to know app name mentioned in config.xml

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1195]
May be a tricky question. I am toggling my Test & Prod build using config.xml and want certain properties be changed between test & prod mode. Is there a way tabris framework can provide readonly property of package name in config.xml

**Comment by cookieguru** [comment]
[`tabris.app.id`](https://tabrisjs.com/documentation/latest/api/app#id)?

**Comment by mpost** [comment]
Snippet: https://github.com/eclipsesource/tabris-js/blob/master/snippets/app.js#L5

**Comment by natanraj** [comment]
Cool. Could have been better if Docs mentioned this. No issues..

**Comment by cookieguru** [comment]
@natanraj What is missing in the docs?

**Comment by mpost** [comment]
The docs could state that the id is the app id, as used on the device. "unique" could be ambiguous.
