### ISSUE TITLE
iOS Bug: content can overlap or be detached from top bar after screen rotate

### ISSUE THREAD

**Issue by scmorse** [eclipsesource/tabris-js#1197]
So if you start your app in portrait mode, it looks fine:

<img src="https://cloud.githubusercontent.com/assets/4519249/24324719/c4a6cdf2-1161-11e7-8c1c-cde76d9ca758.PNG" width="400">

And then you rotate it:

![img_2632 2](https://cloud.githubusercontent.com/assets/4519249/24324727/dcc30694-1161-11e7-8cbe-1fad7677b5a1.PNG)

Now the band at the top overlaps with the content of the app by a few pixels.

Whereas if you start the app in landscape mode:

![img_2634 2](https://cloud.githubusercontent.com/assets/4519249/24324733/f9baff54-1161-11e7-9d70-a7f63995e608.PNG)

And then rotate to portrait: 

<img src="https://cloud.githubusercontent.com/assets/4519249/24324742/18db6702-1162-11e7-90a3-08b0dc5c4fb2.PNG" width="400">

Now there is a gap between the navigation bar at the top and the content of the app. 

In my app, I am using different layouts in portrait and landscape modes, but I don't think this is particular to my code, it happens in every snippet I've looked at. The tabris.js Book Store app, for example, has this problem. 

I am using the Tabris.js 2 iOS app on an iPhone 6, with tabris package version 2.0.0-beta2.

**Comment by karolszafranski** [comment]
@scmorse do you use Tabris.js developer app from AppStore? Which version?

You said that it happens in every snippet, but I'm not able to reproduce it.

**Comment by scmorse** [comment]
Yes, using the developer app from the AppStore. The About page of the app says version 2.0.1 (1703150847), Tabris.js: 2.0.0. 

In my project's package.json, I am using tabris version 2.0.0-beta2. 

My iPhone 6 is on iOS version 10.0.1. 

And I see this issue right in the bookstore example app. This is the difference between starting in portrait mode and starting in landscape and then rotating to portrait:

<img src="https://cloud.githubusercontent.com/assets/4519249/24464738/cc398f18-1478-11e7-88b7-bd35a1e3f103.gif" width="250"/>

This is the difference between starting in landscape and starting in portrait and then rotating to landscape:

<img src="https://cloud.githubusercontent.com/assets/4519249/24464757/e0f2ad5e-1478-11e7-84e4-8b44beaf25a2.gif" width="400" />

By start, I mean hit the 'refresh' button to reload the app.

It seems to just be the height of the bar at the top that is inconsistent.

**Comment by karolszafranski** [comment]
Same state as https://github.com/eclipsesource/tabris-js/issues/1198
