### ISSUE TITLE
iOS Bug: Start to swipe back to prev screen but cancel leads to inability to get back to prev screen

### ISSUE THREAD

**Issue by scmorse** [eclipsesource/tabris-js#1198]
This happens in every app with a drawer I've tried it in, I'm just using the bookstore app as an example.

So if you start to swipe from the left to get back to the previous page:

<img src="https://cloud.githubusercontent.com/assets/4519249/24324849/348ef3c2-1164-11e7-83de-3bd51129b0d3.PNG" width="400" />

But you change your mind, and instead of releasing you swipe it back to the left to stay on the page you're on. 

<img src="https://cloud.githubusercontent.com/assets/4519249/24324859/5e360774-1164-11e7-8277-fd00ee042651.PNG" width="400" />

Now you cannot swipe from the left anymore, and pressing the '< Book Store' action in the top nav opens the drawer:

<img src="https://cloud.githubusercontent.com/assets/4519249/24324868/81a14cb4-1164-11e7-87a9-7c9796a65ebb.PNG" width="400" />

Using the bookstore example on an iPhone 6 within the Tabris.js 2 app.

**Comment by karolszafranski** [comment]
@scmorse thanks for reporting the issue, you're using developer app from AppStore, right?

This issue was fixed, if you want you can try nightly tabris.js builds.

**Comment by scmorse** [comment]
Yes, using the developer app from the AppStore. The about page of the app says version 2.0.1 (1703150847), Tabris.js: 2.0.0.

In my project's package.json, I am using tabris version 2.0.0-beta2.

**Comment by karolszafranski** [comment]
Unfortunately I'm unable to say when AppStore app will be updated. At this moment the only possible way to use fixed version is using the build service.
