### ISSUE TITLE
Question: Compatibility with IPv6 DNS64/NAT64

### ISSUE THREAD

**Issue by maoamid** [eclipsesource/tabris-js#1199]
My app was rejected due the incompatibility with with IPv6 DNS64/NAT64 on appStore (android is fine). My simple app just connect to an API and parse the received JSON with fetch in some lists, and play a live stream on native player. From where should I start to fix this?

**Comment by karolszafranski** [comment]
@maoamid do you use IP Address Literals?

Did you try to test your app in IPv6 environment like described in here: https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html ?

If it's running fine, you should try to submit again, and in case of rejection ask Apple for technical assistance on the issue, explaining what exactly is incompatible with IPv6 DNS64/NAT64.

**Comment by maoamid** [comment]
@karolszafranski No, I don't use IP adresses literals. I will try to create a IPv6 environment, (uff I need an El Capitan :( )
Thanks

**Comment by maoamid** [comment]
@karolszafranski I resolved my issue, using only https urls (on my API, even the server has only ipv4 support). Thanks

**Comment by karolszafranski** [comment]
thanks for sharing, it's good to know that
