### ISSUE TITLE
Local build re-evaluating native module sources is not supported. If you are using the graceful-fs module

### ISSUE THREAD

**Issue by iteearmah** [eclipsesource/tabris-js#1200]
tabris build android
exec [./] npm run --if-present build:android
exec [./] npm run --if-present build
create build folder build/cordova
exec [build/cordova/www] npm install --production
soccer@0.1.0 /home/itee/Mobile/soccer/build/cordova/www
└── tabris@2.0.0-beta2 

exec [build/cordova] cordova platform add /home/itee/tabris-android
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms/android
        Package: com.soccer
        Name: Soccer
        Activity: MainActivity
        Android target: android-25
Subproject Path: CordovaLib
Android project created with cordova-android@6.1.0
(node:24993) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
exec [build/cordova] cordova build
(node:25005) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

my node --version
v6.10.1

**Comment by ralfstx** [comment]
What is your npm version? What does `npm info graceful-fs -v` yield?

Could [this advise](http://stackoverflow.com/questions/37346512/how-to-fix-fs-re-evaluating-native-module-sources-is-not-supported-graceful) help?

**Comment by iteearmah** [comment]
npm info graceful-fs -v yields 3.10.10

**Comment by ralfstx** [comment]
@iteearmah Did you solve this problem meanwhile?

**Comment by ralfstx** [comment]
Closer now. Please reopen if you need further help.
