### ISSUE TITLE
Scroll Event on WebView

### ISSUE THREAD

**Issue by jeffmikels** [eclipsesource/tabris-js#1203]
It seems the scroll event is fired on scrolling a ScrollView or CollectionView widget but not a WebView widget. Is this intentional or a bug?

**Comment by ralfstx** [comment]
As a scroll event is [not documented for WebView](https://tabrisjs.com/documentation/latest/api/WebView#events) this is not a bug. It may be a missing feature, though I'm not sure if it's technically possible to get scroll events on a WebView.

Could you describe your use case a bit to help us understand the requirement? What would you like to do on scroll?

**Comment by cookieguru** [comment]
If you control the webpage, you can also use [`postMessage`](https://tabrisjs.com/documentation/latest/api/WebView#postmessagemessage-targetorigin) to communicate events between the app and the webpage.

**Comment by jeffmikels** [comment]
What I want to do is to have a parallax scrolling page with a textview that
has better HTML rendering. The default TextView is too limited in its
markup rendering.

**Comment by mpost** [comment]
@jeffmikels what type of markup support are you looking for?

**Comment by jeffmikels** [comment]
I'm producing a blog reader, so the html might be anything. Specifically, I
expect to need to handle styles inside blockquotes, lists, or paragraphs.
Simply put, I need nested tag support.

*Jeff Mikels*
Pastor, Lafayette Community Church
helping people find full life in Christ
http://jeff.mikels.cc
http://lafayettecc.org
765-404-0807

Jesus: "I have come that they may have life, and have it to the full."
-- John 10:10 --

**Comment by cookieguru** [comment]
I'd inject the HTML in to a [`WebView`](https://tabrisjs.com/documentation/latest/api/WebView) and use the aforementioned `postMessage` to notify the app of scroll events.
