### ISSUE TITLE
Can't build my app!

### ISSUE THREAD

**Issue by FrencoJobs** [eclipsesource/tabris-js#1204]
When i build my app on tabrisjs online building service,it showed me an error `fail`.
How can i do ?

**Comment by cpetrov** [comment]
Is `fail` the only thing shown in the build log (shown when clicking on the build number)?

**Comment by FrencoJobs** [comment]
It's OK while debugging mode on. But it's not after i disable debugging mode and saved.

**Comment by mpost** [comment]
@FrencoJobs Building "none debug" app works as expected. Could you provide some more details about your versions used in the build configuration? Could you post the build log?

**Comment by FrencoJobs** [comment]
@mpost It's the latest,with `default`signing key.

**Comment by FrencoJobs** [comment]
@mpost It's without release key.Is it need?

**Comment by cookieguru** [comment]
@FrencoJobs Yes, you need a key to build a non-debug version

**Comment by FrencoJobs** [comment]
@cookieguru Thanks.Now I get it.

**Comment by FrencoJobs** [comment]
As it's solved.I CLOSED this issue!
