### ISSUE TITLE
Sequentional tap events are sometimes omitted on Android

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#1206]
When a widget is tapped on repeatedly in a fast pace, some of the tap events are omitted.
To reproduce the issue, use the snippet below, quickly tap the screen, e.g. 5 times, and notice that the counter is not always incremented as expected.

```
var count = 0;

var textView = new tabris.TextView({
  left: 10, top: 10, right: 10, text: 0
}).appendTo(tabris.ui.contentView);

tabris.ui.contentView.on('tap', function() {
  textView.text = ++count;
});

tabris.ui.contentView.on('longpress', function() {
  count = 0;
  textView.text = count;
});
```

**Comment by mpost** [comment]
that is expected behavior. the tap event is from the gesture family and represents a confirmed tap. what you want to use is `touchstart`/`touchend`.

**Comment by ralfstx** [comment]
Ok, in this case we should adjust the doc:

> Fired once when a finger briefly touched the widget.

How would you explain the process of "confirmation"?

**Comment by mpost** [comment]
A tap is something that is not a double click, longpress or moving gesture.

**Comment by mpost** [comment]
Closing this issue as "works as expected".
