### ISSUE TITLE
Problem when removing multiple pages

### ISSUE THREAD

**Issue by elshadsm** [eclipsesource/tabris-js#1208]
When remove multiple pages that having same class names from NavigationView, gray page content is appeared. However the latest existing page content had to be shown.

```
import {Page, Composite, NavigationView, ui} from 'tabris';
let pageNavigation = new NavigationView({
  left: 0, top: 0, right: 0, bottom: 0
}).appendTo(ui.contentView);
new Page({class: 'first'}).append(
  new Composite({left: 0, top: 0, right: 0, bottom: 0, background: 'yellow'})
).appendTo(pageNavigation);
new Page({class: 'second'}).append(
  new Composite({left: 0, top: 0, right: 0, bottom: 0, background: 'red'})
).appendTo(pageNavigation);
new Page({class: 'second'}).append(
  new Composite({left: 0, top: 0, right: 0, bottom: 0, background: 'red'})
).appendTo(pageNavigation);
new Page({class: 'second'}).append(
  new Composite({left: 0, top: 0, right: 0, bottom: 0, background: 'red'})
  .on('tap', () => pageNavigation.find('.second').dispose())
).appendTo(pageNavigation);
```

We have one yellow page and three red pages.
When I tap on latest red page, due to `pageNavigation.find('.second').dispose()` all the `second` class pages must be disposed, then yellow page must be shown.
However, instead of yellow page,  gray page content is shown.

![screenshot_20170331-160007](https://cloud.githubusercontent.com/assets/13982125/24550911/611b6818-1631-11e7-8d1f-b016acf04f1f.png)

**Comment by cpetrov** [comment]
For me (using Tabris.js 2.x nightly) it behaves as expected, i.e. after tapping on the red composite, the page with the yellow composite is shown. Which Tabris.js version are you using?

**Comment by elshadsm** [comment]
I use same (Tabris.js 2.x nightly) version as well and with the latest Android Tabris.js developer app.

**Comment by ralfstx** [comment]
@cpetrov Really? I could reproduce the issue with nightly.

**Comment by cpetrov** [comment]
I had an older Tabris.js npm module version. I can confirm this issue is reproducible with `tabris` 2.x nightly. However, this works as expected with `tabris@2.0.0-beta2`, so it must be a regression.

**Comment by mpost** [comment]
I will look into the issue on the native side.

**Comment by mpost** [comment]
Fix is incoming pending review.

**Comment by cpetrov** [comment]
Fix should be available in the next nightly.
