### ISSUE TITLE
Slider should fire selection change events continuously

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#121]
Currently the Slider widget fires selection events only on touchend. It's not possible to respond to changes immeidately.

https://github.com/eclipsesource/tabris-ios/issues/543
https://github.com/eclipsesource/tabris-android/issues/640

**Comment by mpost** [comment]
Hasn't that been fixed already?

**Comment by ralfstx** [comment]
Implemented in iOS and Android. The existing `Selection` event is now fired continuously .
