### ISSUE TITLE
When running a remote app, images can be loaded using invalid paths

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1210]
Image paths must be given relative to the location of `package.json` in order to be resolved in a built app.

When an app is loaded remotely (when entering a script URL in the developer app), image paths can also be successfully resolved when given relative to the location of the module in which the `ImageView` is instantiated. This leads to confusion, since when building an app with such image paths, images would not be resolved (see #1205). 

Resolving images should also fail for remotely loaded apps when the image path is not relative to `package.json`.

**Comment by tbuschto** [comment]
@cpetrov I don't see how this is possible, since the client can't know which module instantiated the ImageView. On which platform did you observe this behavior?

**Comment by cookieguru** [comment]
@tbuschto Give the following project structure:
```
.
├── images
│   └── logo.png
├── node_modules
│   └── tabris
│       └── (snip)
├── package.json
└── src
    └── app.js
```
`app.js`:
```js
new tabris.ImageView({
  centerX: 0, centerY: 0,
  image: '../images/logo.png'
}).appendTo(tabris.ui.contentView);
```
The result on Android is an image centered on the screen.

Changing the `image` property to `'./images/logo.png'` or `'images/logo.png'` also shows the image (expected behavior)

**Comment by ralfstx** [comment]
Thanks @cookieguru. I'd consider this a bug. We should check the file path in JS already and prevent `..` segments.
