### ISSUE TITLE
android video plugin streaming urls not playing anymore

### ISSUE THREAD

**Issue by maoamid** [eclipsesource/tabris-js#1211]
With beta1 video plugin played well .mp4 file and streaming http urls (like .m3u8 from wowza), but with beta2 the .mp4 files plays fine but the streaming url doesn't play at all (black screen on video widget no error)
I notice that on iphone with native player nothing changed, it plays well both type of streams.

**Comment by mpost** [comment]
@maoamid what environment are you seeing the problem on?

**Comment by maoamid** [comment]
Android 4.4 and Android 6 the same.

**Comment by mpost** [comment]
Could you provide a url that does not play as expected?

**Comment by maoamid** [comment]
@mpost my bad, it seems a problem with our wowza server provider. Some streams works, some not, I had to figure with them, and if problem persist I will write here. ( I'm so sorry about confusion, i had to check that before, working ios app me me confused about the source of the problem).

**Comment by mpost** [comment]
Thanks for the info. Closing this for now.
