### ISSUE TITLE
Support for sourcemaps in exceptions

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#1214]
I'm not sure of the feasibility of this, but it would be nice if the exception details supported sourcemaps in the way that chrome dev tools does. Again, I'm not sure if the tooling you're using to execute the javascript has this capabilities, but if it's possible I would like to put it on your radar.

**Comment by ralfstx** [comment]
Yes, I thought about that too. For Node.js, there is the [source-map-support](https://github.com/evanw/node-source-map-support) module that works with the V8 stack track API, so it should be doable for Android at least.

**Comment by cpetrov** [comment]
It is quite common to compile TypeScript and JavaScript code. I think we should look into this issue again.
