### ISSUE TITLE
Suggestion: implement .back() and .forward() methods for WebView widget

### ISSUE THREAD

**Issue by jeffmikels** [eclipsesource/tabris-js#1219]
I want to have a simple browser in my app, but I require basic browser navigation functionality. Since users may end up on an arbitrary site by following links, I can't implement back and forward navigation using `window.postMessage().`

We need to have a `back` and `forward` method implemented on the WebView widget itself.

**Comment by mpost** [comment]
Sounds like a valuable addition.

**Comment by mpost** [comment]
Both Android an iOS support the methods 

 * `goBack()`
 * `goForward()`
 * `canGoBack()`
 * `canGoForward()`

@ralfstx @patrykmol Should we add those methods on the `WebView`?

**Comment by patrykmol** [comment]
Yes. Are we ok with the existing naming scheme?

**Comment by mpost** [comment]
One could argue to use the `navigate` prefix instead of `go` since we also have the `navigate` event.

**Comment by patrykmol** [comment]
That's fine with me as well.

**Comment by ralfstx** [comment]
I'd prefer to stick with the shorter names that are already established on the native APIs.
