### ISSUE TITLE
Suggestion: WebView option to handle links with System Intents

### ISSUE THREAD

**Issue by jeffmikels** [eclipsesource/tabris-js#1220]
The WebView widget should have a boolean option to open links externally. On Android, this would be implemented by passing the url to an associated Intent.

**Comment by cookieguru** [comment]
This works well in conjunction with [cordova-plugin-inappbrowser](https://github.com/apache/cordova-plugin-inappbrowser):
```js
webView.on('navigate', function(widget, event) {
	if(event.url.substr(0, 4) !== 'http') {
		return;
	}
	if(cordova.InAppBrowser) {
		cordova.InAppBrowser.open(event.url, '_system');
		event.preventDefault();
	}
});
```
This is for the 1.x branch; [adjust accordingly](https://github.com/eclipsesource/tabris-js/blob/master/doc/migration-guide.md) if you're on 2.0.
