### ISSUE TITLE
WebView events aren't firing on 2.0 branch

### ISSUE THREAD

**Issue by jeffmikels** [eclipsesource/tabris-js#1222]
The following code puts nothing in the console when links are clicked:

```javascript
let wv = new tabris.WebView({
	top:0,left:0,right:0,bottom:0,
	background:config.colors.body.background,
	id: 'wv',
	html: html
}).appendTo(this.uipage);

wv.on('navigate', function(event){
	console.log('made it here');
})
```

**Comment by cookieguru** [comment]
I can confirm the `navigate` event is fired in 2.0.0-beta2 on Android with _remote_ URLs.  Which platform are you using, and does your html link to external sites or other files you have bundled with your app?

**Comment by jeffmikels** [comment]
Turns out the HTML I used had some empty links in it. I was using the 'navigate' event to do some debugging of my links, but it was never firing.
