### ISSUE TITLE
action bar

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1223]
how to achieve this with tabrisJS
![screenshot_2017-04-07-12-02-54](https://cloud.githubusercontent.com/assets/12398336/24798415/beb98ffc-1b8d-11e7-83ed-9d9bb53b5496.png)
![screenshot_2017-04-07-12-03-02](https://cloud.githubusercontent.com/assets/12398336/24798414/beb91f86-1b8d-11e7-809f-136eec56c887.png)

**Comment by natanraj** [comment]
have you tried..below ?

placementPriority

Type: string, supported values: low, high, normal, default: normal

Actions with higher placement priority will be placed at a more significant position in the UI, e.g. low priority actions could go into a menu instead of being included in a toolbar.

**Comment by ishigo1987** [comment]
i know but how to have the dropdow menu with items like the second picture?

**Comment by mpost** [comment]
@ishigo1987 the answer @natanraj provided is correct. the actions should have low placement priority.

**Comment by ishigo1987** [comment]
ok and how to handle click on the different menu?

**Comment by mpost** [comment]
@ishigo1987 Have a look at this snippet: https://github.com/eclipsesource/tabris-js/blob/master/snippets/navigationview-action.js

**Comment by ishigo1987** [comment]
I think that you did not understand my problem.i want to know when i'm select a specific menu for exemple i want to know if i'm select "Effacer Journal" and run a callback

**Comment by ishigo1987** [comment]
i found the way to do that thank you
