### ISSUE TITLE
InsertBefore and InsertAfter simply append

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#1224]
```
        var el = new tabris.Composite({
            layoutData: {
                left: 0, right: 0, top: 30, height: 100
            }, background: 'green'
        });
        el.appendTo(tabris.ui.contentView);

        new tabris.Composite({
            layoutData: {
                left: 0, right: 0, top: 0, height: 100
            },
            background: 'purple'
        }).insertBefore(el);

```

The anticipated behavior would be for the Purple composite to be drawn **behind** the green one, but the green one is drawn **behind** the purple one. This has been tested on Tabris 2, as well as 1.10 on both Android and iOS.  

Am I thinking about this incorrectly or is it an actual issue.

**Comment by mpost** [comment]
unfortunately your observation is correct. currently the only solution to order elements visually is to remove them from the parent and add them again.

**Comment by tbuschto** [comment]
Requires support in all 3 native clients.

**Comment by ralfstx** [comment]
The current approach is to replace the native property `parent` with a method call. The native method `insertChild` would be called on the parent whenever a widget is appended. We'll also need a method to call when a widget is detached.

**Comment by ralfstx** [comment]
Unfortunately, the Android implementation won't be complete for 2.0. Removing target milestone.

**Comment by cpetrov** [comment]
Related: https://github.com/eclipsesource/tabris-js/issues/1604
