### ISSUE TITLE
ActivityIndicator

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1225]
How to resize the activity Indicator

**Comment by mpost** [comment]
It is always drawn in its intrinsic size.

**Comment by ishigo1987** [comment]
accordind to this guy @natanraj it's possible
he said "I just wanted to change color. I am able to change the size etc."
https://github.com/eclipsesource/tabris-js/issues/986

**Comment by cookieguru** [comment]
You can change the size of the widget itself, but the spinning wheel renders as large as it can based on the size of the animation that is available on the device.

Changing the size is necessary, for example, to center the widget within the bounds of a UI element.

**Comment by ishigo1987** [comment]
is it possible to only change the size of the spinning wheel?if yes how can i do that?

**Comment by cookieguru** [comment]
No, as @mpost mentioned, it is always drawn in its intrinsic size.

It will scale down to fit smaller elements (for example, a Cell inside a CollectionView).

**Comment by ishigo1987** [comment]
ok
