### ISSUE TITLE
HELP: How do I use a local image (png) in a canvas context?

### ISSUE THREAD

**Issue by jeffmikels** [eclipsesource/tabris-js#1226]
I'm trying to create a simple game, but I can't figure out how to get my local image (ball.png) into the imageData required for putting into a canvas context. What am I missing?

**Comment by cookieguru** [comment]
Paths are resolved relative to your `package.json` file.

Do you have a snippet that can reproduce the problem?

**Comment by jeffmikels** [comment]
Which canvas method will load the image from a filename? Once I have the image data, I know how to draw it.

**Comment by cookieguru** [comment]
It's not part of `Canvas` but you could use `FileReader`.
