### ISSUE TITLE
HELP: Suggestions for Improving Canvas Performance in 2.0

### ISSUE THREAD

**Issue by jeffmikels** [eclipsesource/tabris-js#1227]
In the Tabris Developer App v. 1, the Canvas animation demo gets a solid 60 fps on my One Plus Three, but the 2.0 Developer App only gets 30.

In the little game I'm developing, I am drawing a maximum of 35 circles on the screen at once and my frames drop down below 30.

Is there something I can do to improve Performance of the Canvas widget, or is this a limitation of the Tabris Framework?

**Comment by ralfstx** [comment]
There was an issue that affected canvas performance. This issue has been fixed in 7c21525e00d9d3d513715b78c4444d26705630c4 and the fix will be included in RC1. With this fix we're back to the performance of 1.10.

The canvas performance depends heavily on the size of your canvas, so you should test on different devices.

**Comment by jeffmikels** [comment]
Excellent, thank you.

*Jeff Mikels*
Pastor, Lafayette Community Church
helping people find full life in Christ
http://jeff.mikels.cc
http://lafayettecc.org
765-404-0807

Jesus: "I have come that they may have life, and have it to the full."
-- John 10:10 --

**Comment by jeffmikels** [comment]
Can I switch my project to use the current master branch instead of 2.0.0-beta2?

**Comment by cookieguru** [comment]
Yes, update the `tabris` dependency in `package.json` to
```
https://tabrisjs.com/downloads/nightly/tabris.tgz
```

**Comment by ralfstx** [comment]
Since last week, the nightly builds are available on npm. So instead of the URL above, you can set your depencency to
```json
  "tabris": "nightly"
```
