### ISSUE TITLE
Any way to integrate React Native components?

### ISSUE THREAD

**Issue by bev-on** [eclipsesource/tabris-js#1229]
Tabris.js is amazing, but only reason I'm considering to use React Native instead of Tabris.js is their powerful Text component.

TextView in Tabris.js is very basic widget compared to React Native Text component. In React Native we can add images (including animated gifs) and other components inside Text component and it makes it very useful. For my current project I really need animated gifs inside text and I even write custom widget for Android and I'm able to include Drawable Animations inside text but I have no idea how to write custom widget/plugin for iOS with same features :/

Considering everything mentioned above, my question is if we can somehow use React Native only for specific pages? Or if there is any planned feature to support animated images or images in general inside TextView?

Also if you can write some very basic tutorial about how to write custom widgets for iOS. I try to use tabris-plugin-maps as example but it's very complicated for someone who has never written anything in Objective C. For Android I use tabris-plugin-calendar and modify it to make custom TextView with animation support and it was easy for me to understand. We need something like this easy to understand iOS example :)

**Comment by mpost** [comment]
As of right now it is not possible. We would be interested in outside contributions to make that possible.

**Comment by mpost** [comment]
Support for react native plugins is currently not planned.
