### ISSUE TITLE
Use webpack in typescript project generated by cli

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#1231]
has anyone tried using webpack (or similar) to bundle tabris.js app into a single file?

**Comment by ralfstx** [comment]
I can highly recommend [rollup](https://www.npmjs.com/package/rollup). We use it to package up tabris.js itself and also for apps built with tabris. Rollup works on ES6 `import` / `export` statements (instead of `require` and `module.exports`) and creates a single output file. It walks through the source code, starting at a given entrypoint and includes only those methods that are actually used.

**Comment by cookieguru** [comment]
@ralfstx How does it affect app startup times and memory usage?

**Comment by ralfstx** [comment]
@cookieguru That depends on the app. Apps that would load most modules on startup anyway will obviously benefit from a single file. For apps that would load many modules on demand, you should experiment which different combinations. You can also use rollup to create multiple bundles.

**Comment by bFlood** [comment]
thanks for all the info, webpack works well for require/module.exports apps.

**Comment by TheLarkInn** [comment]
@bFlood Is there an official example repo that we (the webpack organization) can reference from our [documentation](webpack.js.org)

**Comment by ralfstx** [comment]
@TheLarkInn Webpack is a valuable tool to package up npm modules for Tabris.js apps. There no official example that uses webpack yet, but it seems like a good thing to provide. We let you know when we have something.

**Comment by bFlood** [comment]
@TheLarkInn the repo where we are using webpack and tabris is private, sorry. it does work well though, thanks!

**Comment by mpost** [comment]
We are planning to include webpack in the typescript projects generated by the tabris cli. We will also mention that in the docs.

**Comment by tbuschto** [comment]
@mpost Can we close this? I'm no longer in favor of using webpack, it can add a lot of complexity to the setup and is insufficient for large projects (I know this from experience) where a reload may still take more than 10 seconds. I think we need module caching and possibly hot module replacement, and WebPack can not provide this for Tabris.js (It has these features, but they don't work with Tabris.js at all.) We need to implement this directly in to the CLI.

**Comment by mpost** [comment]
Agreed. If it doesn't add any value we close the issue.
