### ISSUE TITLE
Attach arbitrary property to the widget

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1232]
hello
I see In tabris documentation that it's possible to attach an arbitrary property to a widget
```js
let ImgShare = new tabris.ImageView({
  image:{src:"icons/android/share_1.png"},
  scaleMode:"fill",
  width:24,
  height:24,
  textToShare:"blablabla"
}).on("tap", function()
  let textToShare = this.get("textToShare");
}).appendTo(tabris.ui.contentView);
```
when i write something like that i have an exception like unexpected identifier `let textToShare = this.get("textToShare");`
Why?

**Comment by ralfstx** [comment]
In Tabris 1.x, it was possible to attach custom properties to widgets. This is not supported in 2.x anymore.

You can either create a custom widget that extends ImageView and add a getter and a setter for your custom property:
```js
class ImageShare extends ImageView {
  get textToShare() {
    ...
  }
  set textToShare(text) {
    ...
  }
}
```
or simply attach your property to the widget without using `get()` and `set()`:
```js
imageView.textToShare = "blablabla";
...
let textToShare = this.textToShare;
```

**Comment by ishigo1987** [comment]
Please look at this where i'm wrong?
let img = new tabris.ImageView({
    image:{src:"https://image.freepik.com/free-vector/abstract-background-with-a-watercolor-texture_1048-2144.jpg"},
    scaleMode:"fill"
 }).appendTo(tabris.ui.contentView);
img.randomValue = "blablabla";
img.on("tap", function({
    let t = this.randomValue;
  console.log(t);
});

**Comment by ralfstx** [comment]
@ishigo1987 Could you please [format your code](https://guides.github.com/features/mastering-markdown/) to make it more readable?

**Comment by ralfstx** [comment]
You have a syntax error in your listener function as far as I can see.

**Comment by ishigo1987** [comment]
Yes
My apologies I just copied it from my scratchpad
let img = new tabris.ImageView({
               image:{src:"https://image.freepik.com/free-vector/abstract-background-with-a-watercolor-
              texture_1048-2144.jpg"},
              scaleMode:"fill"
             }).appendTo(tabris.ui.contentView);
img.randomValue = "blablabla";
img.on("tap", function({
      let t = this.randomValue;
      console.log(t);
});

**Comment by ishigo1987** [comment]
i need to install markdown

**Comment by ishigo1987** [comment]
I saw my error thank you very much

**Comment by mpost** [comment]
@ishigo1987 Btw... Github supports source code markup: https://help.github.com/articles/creating-and-highlighting-code-blocks/ It makes the snippets more readable.

**Comment by ishigo1987** [comment]
thank you

**Comment by cookieguru** [comment]
> I need to install markdown

There's nothing you need to install; just hit the preview button before you submit
