### ISSUE TITLE
problem with localStorage

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1233]
I have this code in app.js
If(localStorage.id === undefined)
 {
     // ConnectionView(into another navigationView)
     // Into the connectionView i make an ajax request 
    // And i store the result into the localStorage.id
 }
Else
 {
      // HomeView(into another navigationView)
 }
The problem is after closing app localStorage.id return to undefined

**Comment by ishigo1987** [comment]
Sorry I'm writing on my phone i can use identation

**Comment by mpost** [comment]
Have a look at https://github.com/eclipsesource/tabris-js/blob/master/snippets/local-storage.js

**Comment by ishigo1987** [comment]
I'm afraid I do not understand
localStorage work perfectly my problem is that when i closing the application all the localStorage become empty(in my case localStorage.id become empty and when the app restart the connectionView appear instead of homeView)

**Comment by cookieguru** [comment]
@ishigo1987 Does your app have the Storage permission granted?  Is this a Xiaomi device?

**Comment by ishigo1987** [comment]
no motorolla E2 Android 5.1 
Perhaps i need to enter something in the config xml????

**Comment by cookieguru** [comment]
@ishigo1987 
>Does your app have the Storage permission granted?
This is in Android Settings -> Applications

**Comment by ishigo1987** [comment]
i think yes

**Comment by ishigo1987** [comment]
do you think that the problem can be the fact that i use localStorage.id instead of localStorage.getItem("id");

**Comment by cookieguru** [comment]
@ishigo1987 Sorry I hadn't looked at your code, but that would do it.  The example that @mpost shows the proper way to do it.

`localStorage` implements the [Storage API](https://developer.mozilla.org/en-US/docs/Web/API/Storage) which does not support direct property access.  You must use the getters and setters defined in the aforementioned link.

**Comment by ishigo1987** [comment]
ok i will try it i'm little confuse with the mpost example how can i declare localStorage before i use it?
const localStorage = require('tabris') before any use? or simply localStorage.getItem('id');

**Comment by cookieguru** [comment]
From [the docs](https://tabrisjs.com/documentation/latest/w3c-api#persistent-storage):
> Tabris.js supports the global object `localStorage`

Since it is a global object there is nothing you need to import.

**Comment by ishigo1987** [comment]
ok i try to do that

**Comment by ishigo1987** [comment]
it's work thank you
