### ISSUE TITLE
Ios toolbarVisible doesn't update correctly.

### ISSUE THREAD

**Issue by troyamelotte** [eclipsesource/tabris-js#1236]
When navigating from a page with the opposite toolbarVisible setting as the previous one it retains the previous setting on ios. For example on out home page we set this:`tabris.ui.set("toolbarVisible", true);`. 
Then when the user navigates to another page we have: `tabris.ui.set("toolbarVisible", false);`
However when you load the new page the toolbar is still visible. This code works exactly as intended on android however on ios it does not remove the toolbar. If I wrap the `tabris.ui.set("toolbarVisible", false);` in a setTimeout of 0 it works as intended.

```var tabris = require("tabris");

function main(){
    var page = new tabris.Page({
        topLevel: true,
        title: "myapp"
    });
    tabris.ui.set("toolbarVisible", true);
    new tabris.TextView({
        layoutData: {centerX: 0, centerY: 0},
        text: "click me to navigate to the other page",
        textColor: "black"
    }).on("tap",function(){
        other();
    }).appendTo(page);
    page.open();
}
main();
function other(){
    var page = new tabris.Page({
        topLevel: true,
        title: "myapp"
    })
    tabris.ui.set("toolbarVisible", false);
    new tabris.TextView({
        layoutData: {centerX: 0, centerY: 0},
        text: "other page",
        textColor: "black"
    }).appendTo(page);
    page.open();
}
```

**Comment by mpost** [comment]
@troyamelotte Thanks for your feedback. In the upcoming Tabris.js 2 release we have separated out the tabris ui concept into its own widget called `NavigationView`. Would you be able to  migrate your app to the new format and check if https://tabrisjs.com/documentation/latest/api/NavigationView#toolbarvisible works as expected for you?

**Comment by ralfstx** [comment]
I can reproduce the issue on 1.10. It works as expected on 2.0.0-rc1 using the `toolbarVisible` property on `NavigationView`.

As a workaround exists (use `setTimeout`), we probably won't fix it in the 1.x branch. Sorry.
