### ISSUE TITLE
Borders

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1238]
hello is it possible to have  a border on the widget(border-top,border-bottom,border-left,border-right)?

**Comment by cookieguru** [comment]
Duplicate of #1016

**Comment by ishigo1987** [comment]
ok it's not really obvious right now

**Comment by ralfstx** [comment]
Closing as dup of #1016. Thanks, @cookieguru.

@ishigo1987 It's not yet possible. The request is tracked by issue #1016. BTW, you might want to join our [slack channel](https://tabrisjs.herokuapp.com/) to ask further questions.
