### ISSUE TITLE
How to animate between pages

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1239]
Hello
When TabrisJs Predicts to support the custom transitions between navigationViews or page inside navigationView? like NativeScript or React Native.
i think that the lack of Predefined transitions(flip,slide...ect) between pages is one of the weaknesses of tabris
By example something like that
let pageVerifNumber = new tabris.Page({
        title: `Verification Number`,
        background:`#fafafa`,
        animation:"slide" // just  an example
     }).appendTo(executeNavigationView);

**Comment by mpost** [comment]
@ishigo1987 It is possible already. Just Disable the default animation with https://tabrisjs.com/documentation/latest/api/NavigationView#animated and use what ever animation you want on the Page.

**Comment by ishigo1987** [comment]
i know that @mpost  I've talked about it recently it is not possible to properly animate the transition between two pages located in the same navigation.If it is possible tell me how to do with a snippet please

**Comment by ishigo1987** [comment]
i need help please...

**Comment by mpost** [comment]
The following snippet demonstrates how a custom animation can be achieved. Be aware however that in this snippet the pages are not disposed automatically but that could be added.

```js
let pageCount = 1;

let navigationView = new tabris.NavigationView({
  left: 0, top: 0, right: 0, bottom: 0,
  animated: false
}).appendTo(tabris.ui.contentView);

new tabris.Action({title: 'Add page'})
  .on('select', () => createPage(pageCount))
  .appendTo(navigationView);

function createPage(title) {
  new tabris.Page({
    title,
    autoDispose: false
  }).on('appear', ({target: page}) => {
    let composite = new tabris.Composite({
      id: 'content',
      background: 'green',
      left: 0, top: 0, right: 0, bottom: 0,
      transform: {translationX: -100},
      opacity: 0
    }).appendTo(page);
    new tabris.TextView({
      left: 16, top: 16, right: 16,
      text: title,
      alignment: 'center',
      font: 'bold 48px'
    }).appendTo(composite);
    composite.animate({transform: {translationX: 0}, opacity: 1});
  }).on('disappear', ({target: page}) => {
    let content = page.find('#content').first();
    content.appendTo(tabris.ui.contentView);
    content.transform = {translationX: 0};
    content.opacity = 1;
    content.layoutData = {left: 0, right: 0, bottom: 0, height: content.bounds.height};
    content.animate({transform: {translationX: 100}, opacity: 0});
  }).appendTo(navigationView);
  pageCount++;
}

createPage(pageCount);
createPage(pageCount);
```

**Comment by ishigo1987** [comment]
ok thank you

**Comment by cookieguru** [comment]
> i think that the lack of Predefined transitions(flip,slide...ect) between pages is one of the weaknesses of tabris

I think it's great, because unlike Tabris.js they do not seem to respect Android's Transition Animation Scale.  On my devices I have that setting at 0 to achieve a snappier UI.  Having an app disobey this system-wide setting is pretty annoying.

**Comment by mpost** [comment]
Closing this issue for now. Extendending the `animated` property is still on the roadmap.
