### ISSUE TITLE
native components are closed source

### ISSUE THREAD

**Issue by cordovapolymer** [eclipsesource/tabris-js#1240]
Tabris.js looks nice, but unfortunately native components are closed source.
Any hope for full open source?

**Comment by cookieguru** [comment]
Native sources are _shared_ source and are available with an [Organization plan](https://tabrisjs.com/pricing)

**Comment by cordovapolymer** [comment]
@cookieguru , that's great and certainly fits some corps, but for organizations relying on completely open source stack it's not a feasible option

**Comment by mpost** [comment]
@cordovapolymer Thanks for your interest in the native components. What kind of use would you want to make of the native parts?

**Comment by cordovapolymer** [comment]
@mpost , just have it available in opensource under a sensible license. It would be acceptable even in the way like Red Hat does.
Such licensing gives several benefits, first of them is possibility to control the build process, being sure that the project may be forked, in case of lack of development or abandonment of the upstream, is also very important, last but not least is being able to contribute to the project and help solving issues.

**Comment by cookieguru** [comment]
> possibility to control the build process

While you don't have full control over the Cordova platform that is added, performing a [local build](https://tabrisjs.com/documentation/latest/local-build) already provides quite a bit of control.

**Comment by cordovapolymer** [comment]
@cookieguru , of course, but if Tabris is a only closed component in the project(of over 50 open source), it's wiser to avoid it. I found tabris from Microsoft Ace issues page,, which is abandoned now, but it gave more freedom because it was almost open source, only requiring Windows for declarative syntax, maybe it will be forked, or maybe a new project will appear.

**Comment by ralfstx** [comment]
We're discussing this topic internally. Closing this issue, as it's not a technical problem. Feel free to join the discussion on [Slack](https://tabrisjs.herokuapp.com/) to follow up.

**Comment by cordovapolymer** [comment]
@ralfstx , any updates on this?
