### ISSUE TITLE
Text becomes invisible if event listener is attached to imageView in the drawer

### ISSUE THREAD

**Issue by jeffmikels** [eclipsesource/tabris-js#1241]
I thought it was a problem with the collectionView in iOS, but after further testing, I determined that when I attach a longpress listener on an imageView in the drawer, the text in every widget disappears. My workaround was to create a Composite widget in the drawer, put the imageView in that, and attach the listener to the Composite widget instead of the imageView.

**Comment by karolszafranski** [comment]
@jeffmikels can you share a snippet reproducing the issue?
