### ISSUE TITLE
Check markup text when markupEnabled - was: Undocumented FEATURE? markupEnabled on Android TextViews

### ISSUE THREAD

**Issue by jeffmikels** [eclipsesource/tabris-js#1242]
Apparently, Android TextViews with markupEnabled can handle way more html tags than iOS can. That will teach me not to develop on Android first!

**Comment by cookieguru** [comment]
Can you provide some examples?

**Comment by jeffmikels** [comment]
Android can handle nested tags, like `<b>` inside `<p>`
Android can handle `<h1>`

**Comment by maoamid** [comment]
@jeffmikels  I experiment the similar results like you. For example, I take an html article (from a joomla cms database in my case) and in Android the html is rendered fine, acceptable, but on iOS the same article isn't parse in the right way, so it display the html source code in webview widget body, so unpleasant. I prefer less html tags and rendered without style

**Comment by iteearmah** [comment]
Is there a way to render <img> and also make links clickable in the textView?
I'm loading html from the main site to the mobile app.

**Comment by cookieguru** [comment]
#286

You'll either have to register a tap handler on the entire `TextView` or use a `WebView`

**Comment by iteearmah** [comment]
I tried the webview....it renders the text too small and image boxes show but the images don't load

**Comment by mpost** [comment]
@jeffmikels You are right in the divergent support of Android an iOS. That is why we have white listed a set of tags that are guaranteed to work cross platform: https://tabrisjs.com/documentation/latest/api/TextView#markupenabled

**Comment by ralfstx** [comment]
We may be able to check the markup on the JS side and print at least a warning for unsupported input.

**Comment by mpost** [comment]
When using jsx/tsc you get only the supported elements.

**Comment by mpost** [comment]
We will continue to support platform specific tags but only support the ones mentioned in the docs.
