### ISSUE TITLE
animationstart or animationend not fired

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1245]
home --> is a textview;

home.animate(
  {opacity: 0.5}, {duration: 5000}
);

home.once("animationstart", function() {
    console.log("animated started");
});

**Comment by cookieguru** [comment]
Assuming you're on 2.0 beta:

> The events animationstart and animationend have been removed, use the Promise returned by animate()

You can read more in the [Migration Guide](https://github.com/eclipsesource/tabris-js/blob/master/doc/migration-guide.md)

**Comment by natanraj** [comment]
My bad.. i checked it now. it works, but one query ;  how can i know the widget which is getting animated ? (The promise argument seems undefined).


function startSiblingsAnimation(event){
    console.log('Have i come here'+event);
    
  };

home.animate({},{}).then(startSiblingsAnimation);

**Comment by ralfstx** [comment]
`event.target` always refers to the widget that received the event, that is, the widget that is being animated.

**Comment by natanraj** [comment]
@ralfstx i too thought so. But that event is coming undefined. that is my query.

**Comment by ralfstx** [comment]
Right, the promise argument is not an event, but `undefined`. Is this really a problem? You can pass the widget to the function call as shown above.

**Comment by natanraj** [comment]
@ralfstx  yeah . i sort out that.

**Comment by ralfstx** [comment]
Closing as the issue seems resolved. Please reopen if needed.
