### ISSUE TITLE
Prevent new instance of app notification tap

### ISSUE THREAD

**Issue by iteearmah** [eclipsesource/tabris-js#1246]
Any way to prevent new instance on notification tap

**Comment by mpost** [comment]
You need to provide more context on that question.

**Comment by iteearmah** [comment]
I mean when you receive a notification, while the app is opened in the background or foreground; you tap on the notification, it should not open a another instance of the app (having two instances when U press the back key )

**Comment by mpost** [comment]
What kind of notification are you taping on?

**Comment by sand123** [comment]
@iteearmah  I used https://github.com/katzer/cordova-plugin-local-notifications
And it has `click` event that handles user tap on notification. According to docs
```javascript
cordova.plugins.notification.local.on("click", function (notification) {
    joinMeeting(notification.data.meetingId);
});
```
But in this case app launches again, no matter if it is already running in background or foreground. Do you mean the same plugin?

**Comment by mpost** [comment]
A quick fix would be to change https://github.com/katzer/cordova-plugin-local-notifications/blob/master/src/android/notification/AbstractClickActivity.java#L107 to https://github.com/eclipsesource/tabris-plugin-firebase/blob/master/src/android/com/eclipsesource/firebase/messaging/NotificationOpenedReceiver.java#L39

**Comment by ishigo1987** [comment]
@mpost how can make this change since the app and the plugins are added in the build phase

**Comment by mpost** [comment]
@ishigo1987 you need to fork the katzer plugin and make the adjustments

**Comment by ishigo1987** [comment]
great I did not think about it
Thank you
