### ISSUE TITLE
CLoud build is failing.

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1248]
Built the following apk(s): 
	/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build/outputs/apk/android-release-unsigned.apk
Running "create-artifacts" task
Running "shell:sign_apk" (shell) task
 updating: META-INF/MANIFEST.MF
jarsigner: unable to sign jar: java.net.SocketException: Connection reset.

**Comment by fwaibel** [comment]
The TSA (Time Stamping Authority) we use (https://timestamp.geotrust.com/tsa) is currently down.
`
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -J-Dhttps.protocols=TLSv1.2,TLSv1.1 -tsa https://timestamp.geotrust.com/tsa -keystore ~/.android/debug.keystore -storepass android -keypass android -signedjar /tmp/test-signed.jar /tmp/test.jar androiddebugkey
 updating: META-INF/MANIFEST.MF
jarsigner: unable to sign jar: java.net.SocketException: Connection reset
`

**Comment by fwaibel** [comment]
@natanraj We changed the TSA as suggested by Symantec. Please try again.

**Comment by natanraj** [comment]
Working. Closing now
