### ISSUE TITLE
pass data between pages

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1249]
Hello
How I can pass data from one page to another?because something like that doesn't work
page one
let searchResultsPage = require("./searchResultsView.js")(e.text);

page two(the page searchresultsView.js)
exports.create = (searchQuery) =>
 {
    "use strict";
    console.log(searchQuery);
    return searchResultsView;
 };
The console says: TypeError: require(...) is not a function

**Comment by mpost** [comment]
In general you can create a new property on a page to attach some random data to it. `new Page().myCustomData = 'data';`

**Comment by ishigo1987** [comment]
I'm a little bit confused.
i want to make something like that 
this page(page 1) receive a data
exports.create = (searchQuery) =>
 {
    "use strict";
    let searchResultsView = new tabris.Page({
         title: searchQuery,
    }).appendTo(whatever);
  return searchResultsView;
 };
from this page(2) like that
let searchResultsPage = require("./searchResultsView.js")(data);
According to your explication how can i send data to page(1)?

**Comment by cookieguru** [comment]
@mpost provides a great way to do it if you are creating the page in the same code that needs to pass in the variables.  You didn't mention that your page is instantiated in a different module.

In that case, your question isn't specific to `Page`s or Tabris.js.  You can check out [the Cordova sample project](https://github.com/eclipsesource/tabris-js/tree/master/examples/cordova) which does exactly what you are looking for.  Also check out [https://toddmotto.com/mastering-the-module-pattern/](Mastering the Module Pattern).

Also if you could surround your code blocks with  ` ```js ` and ` ``` ` it would immensely help with readability.

**Comment by ishigo1987** [comment]
I don't understand how to use the way that @mpost provide.the twoo pages is instantiated in a different module

**Comment by cookieguru** [comment]
Did you try the line of code he provided?

**Comment by ishigo1987** [comment]
No because i don't know where to add it

**Comment by cookieguru** [comment]
Wherever you create the new page

**Comment by ishigo1987** [comment]
I call the new page inside the other module with require where can i add new Page().mycustomData = 'data'

**Comment by cookieguru** [comment]
If you are exporting the page in `searchResultsView.js`, you can reference it as the same variable.  Read through the code of the [Cordova Sample Project](https://github.com/eclipsesource/tabris-js/tree/master/examples/cordova) to get a sense of how this works.

**Comment by ishigo1987** [comment]
Ok i will do that

**Comment by ralfstx** [comment]
To summarize, you can add custom properties to widgets - because it's JavaScript. Example:
```js
let page = new tabris.Page();
page.myCustomProperty = 23;
```
@ishigo1987 Could you resolve your problem?

**Comment by ishigo1987** [comment]
I could tell you in a few hours
