### ISSUE TITLE
ImageView ScaleMode Fill on Android 5.1.0

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#1252]
Is scalemode fill supported on older versions of android? The following code below does not show an image on nexus 5x 

```
var background = new tabris.ImageView({
  layoutData: {left: 0, top: 0, bottom: 0, right: 0},
  image: 'backgrounds/blur.png',
  scaleMode: 'fill'
}).appendTo(this.page);
```

**Comment by cookieguru** [comment]
Which Android version?

**Comment by dested** [comment]
Nexus 5, 5.1.0 - API22 1080x1920

**Comment by mpost** [comment]
@dested The `scaleMode` is supported on all Android version that tabris supports (Android 4.1 for 1.x and 4.2 for 2.x).

**Comment by mpost** [comment]
@dested Could you also post the "blur.png" image here?

**Comment by mpost** [comment]
Closing this one as resolved. @dested Please reopen if you still have problems.
