### ISSUE TITLE
Introduce a tap event on status bar

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1254]
It is a common pattern to scroll a list to the top on iOS when tapping on the status bar.

**Comment by mpost** [comment]
It works on some CollectionViews (eg collectionview.js snippet) but it should be made to work more consistent.

**Comment by patrykmol** [comment]
Tap event has been implemented in this change https://github.com/eclipsesource/tabris-js/commit/f1f1bce99a773e673af6622e4d5a4662b6cd661a.
