### ISSUE TITLE
video widget dispose problem

### ISSUE THREAD

**Issue by maoamid** [eclipsesource/tabris-js#1255]
In a stack of pages, with autodispose:
On Android 4.x video widget is disposed on back navigation or dispose all,
On iphone 4 and 6 & Android 6 video widget in not disposed on back navigation or dispose all

**Comment by mpost** [comment]
Thanks for your report. What exactly do you mean by the widget is not disposed? Is the the widget on js not [diposed](https://tabrisjs.com/documentation/latest/api/Widget#isdisposed) or is the video widget still visible/playing?

**Comment by maoamid** [comment]
@mpost the video widget is still playing after a supposed dispose. if I leave the page the sound can be still heard, and if I recreate the page, two sounds are played.

**Comment by mpost** [comment]
@maoamid thanks for the info. Will look into the issue.

**Comment by mpost** [comment]
With the upcoming 2.0 RC1 one we have removed the `autoDispose` property on the `NavigationView`. You know would simply dispose a page or a set of pages to remove them from the navview. In such a scenario diposing a page properly destroys and stops a video widget while playing.

Could you provide a snippet to reproduce the problem in a tabris nightly environment?

**Comment by mpost** [comment]
Snippet showing how to dispose pages: https://github.com/eclipsesource/tabris-js/blob/master/snippets/navigationview-page-stacked.js

**Comment by maoamid** [comment]
@mpost I confirm that the problem is solved in nightly build (I adjusted my code using the snippet from RC version). Thank you.

**Comment by maoamid** [comment]
Please test the folowing snippet again in iOS (on Android is OK):

````javascript
const { Button, Composite, NavigationView, Page, Video, ui } = require('tabris');

let pageCount = 0;

let navigationView = new NavigationView({
    left: 0, top: 0, right: 0, bottom: 0
}).appendTo(ui.contentView);

createPage();

function createPage(title) {
    let page = new Page({
        title: title || 'Initial Page'
    }).appendTo(navigationView);
    new Button({
        left: 16, top: 16, right: 16,
        text: 'Create another page'
    }).on('select', () => createPage('Page ' + (++pageCount)))
        .appendTo(page);
    new Button({
        left: 16, top: 'prev() 16', right: 16,
        text: 'Go back'
    }).on('select', () => page.dispose())
        .appendTo(page);
    new Button({
        left: 16, top: 'prev() 16', right: 16,
        text: 'Go to initial page'
    }).on('select', () => {
        navigationView.pages().dispose();
        createPage();
    }).appendTo(page);
    let videoComposition = new Composite({
        left: 16, top: 'prev() 16', right: 16, bottom: 0,
        background: 'black'
    });
    if (page.title !== 'Initial Page') {

        videoComposition.appendTo(page);
        let button = new Button({
            id: 'button',
            centerX: 0, bottom: 16,
            text: '❚❚'
        }).on('select', () => video.state === 'play' ? video.pause() : video.play())
            .appendTo(videoComposition);

        let video = new Video({
            left: 0, top: 0, right: 0, bottom: '#button 16',
            url: 'http://peach.themazzone.com/durian/movies/sintel-1280-stereo.mp4',
            controlsVisible: false
        }).on('stateChanged', event => button.text = event.value !== 'pause' ? '❚❚' : '▶')
            .appendTo(videoComposition);
    
    }

    return page;
}
`
