### ISSUE TITLE
Changing Button's corner radius

### ISSUE THREAD

**Issue by Tilesentik** [eclipsesource/tabris-js#1259]
how do i go about changing the button radius

**Comment by cookieguru** [comment]
There's the [`cornerRadius`](https://tabrisjs.com/documentation/latest/api/Widget#cornerradius) property but that provides a halo-like effect which is probably not what you're after.  This is definitely possible so it looks like a bug at the moment.

**Comment by mpost** [comment]
It is is not a bug as such but rather the behavior of the Button in conjunction with the cordner radius. If you want to create a custom button i suggest looking at the snippet posted in this blog post:

http://eclipsesource.com/blogs/2016/04/07/creating-the-floating-action-button-in-tabris-js/

It can be adapted to work for normal (or flat) buttons as well.

**Comment by ralfstx** [comment]
I think it is a bug, as it does not behave as documented. We should mention it in the doc, or ignore the property for Button, or both.
