### ISSUE TITLE
Navigation in animation example does not work properly

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1261]
Opening page and navigating back with edge gesture does not allow to reopen the page again (going back with back button in navview works as expected).

**Comment by karolszafranski** [comment]
@mpost issue:
```
* Animation
  + [iOS] Opening page and navigating back with edge gesture does not allow to reopen the page again (going back with back button in navview works as expected)
```
has been fixed here:
https://github.com/eclipsesource/tabris-ios/commit/592bfb562fd0d2a3cd9a8598fee150d60282dbf4

Please re-check or close
