### ISSUE TITLE
Chart example layout is inconsitent

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1265]
The button "draw graph" and the checkbox "animate" have unexpected layout. The button stretches although the combobox should stretch.

**Comment by mpost** [comment]
This is likely similar to https://github.com/eclipsesource/tabris-js/issues/1436

**Comment by patrykmol** [comment]
Closing since it seems to be no longer a case.
![img_0009](https://user-images.githubusercontent.com/12428999/30476437-54b541e0-9a0a-11e7-87b4-f4b7de650622.PNG)
