### ISSUE TITLE
Parallax example can be made to not show any content

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1268]
Example has problems when scrolling all the way up and than rotating device. Content can disappear.

**Comment by jokorivai** [comment]
Seems like the layout need to be recalculated on screen rotation event.
I had my own app crashed on screen rotation, and the easisest way for me was to disable screen rotation using cordova plugin.

**Comment by ralfstx** [comment]
@mpost Is that iOS or Android, or both?

**Comment by mpost** [comment]
@ralfstx Can be seen on both platforms

**Comment by mpost** [comment]
Issue is not relevant anymore.
