### ISSUE TITLE
Picker can instantly close when opening

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1281]
Occasionally the picker auto closes instantly when opening by tapping on it on iPhone.

@cpetrov Is able to demonstrate the behavior.

**Comment by cookieguru** [comment]
Is this the same as #1291?

**Comment by cpetrov** [comment]
No - this issue is related to the picker overlay sometimes closing after being opened. #1291 is about the picker being rendered without any items.

**Comment by patrykmol** [comment]
@cpetrov Can you post reproduction steps?

**Comment by cpetrov** [comment]
@patrykmol It can be reproduced with the `picker.js` snippet. For me, it could be only reproduced on phones (i.e. not tablets), where the picker is rendered as a sheet, sliding from the bottom.

Keep opening and closing the picker. At some point, it will close just after being opened. It happens rarely, but sometimes this behaviour can be reproduced several times in a row.
