### ISSUE TITLE
Widget should clamp opacity smaller 0 and larger 1

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1284]
Opacity smaller than 0 and larger than 1 should be clamped to the given 0/1. Currently the opacity is ignored leading to multiple images shining through. Seen in tabfolder-swipe-parallax.js snippet.

Additionally the iOS client currently shows log message about the range. These message should not be shown.

**Comment by ralfstx** [comment]
That's probably a JS issue.

JS rejects out-of-range values for opacity with a warning "'Number is out of bounds: ..". We can change this behavior in JS.

**Comment by cookieguru** [comment]
I liked the warning.  If you forgot to reduce the value to [0...1] at least you got a message as to why it wouldn't work.

**Comment by ralfstx** [comment]
Now it works without a warning. That's sort of how opacity works in a browser as well. When you supply a value of an invalid type, you still get a warning.
