### ISSUE TITLE
cordova-plugin-file-opener2 with TypeScript

### ISSUE THREAD

**Issue by shomeier** [eclipsesource/tabris-js#1294]
Hello together,

I am using Tabris.js 2 (beta2) with TypeScript (and btw. I am pretty impressed so far ;) ).
I want to download a file and display it on the device.

To download the file I was able to successfully use _cordova-plugin-file-transfer_:
I used `declare var FileTransfer: any;` and could successfully access the `FileTransfer` object.

Now I am having problems to open the file via _cordova-plugin-file-opener2_.
I found an old JavaScript example here: https://github.com/eclipsesource/tabris-js-file-open-example

It seem the fileOpener2 is expected to be available at `cordova.plugins.fileOpener2`.
I used `declare var cordova: any;` but during runtime on the Tabris.js 2 Developer App
the `cordova.plugins` object only contains a `diagnostic` object. No `fileOpener2` object.

**iOS:**
> TypeError: undefined is not an object (evaluating 'cordova.plugins.fileOpener2.open')

**Android:**
> TypeError: Cannot read property 'open' of undefined

Actually I am not yet very familiar with TypeScript and do not know how to solve this problem.
I do not know the mechanism how the fileOpener2 plugin is attached/resolved during runtime.
I would appreciate any help ;)

I include the plugin like this in cordova/config.xml file:
`<plugin name="cordova-plugin-file-opener2" spec="~2.0.15" />`

My package.json:
```
{
  "name": "shorty.cmis.tabris",
  "version": "0.1.0",
  "main": "dist/app.js",
  "private": true,
  "scripts": {
    "test": "tslint 'src/**/*.ts'",
    "build": "tsc -p .",
    "start": "tabris serve"
  },
  "dependencies": {
    "tabris": "^2.0.0-beta2",
    "cordova": "^7.0.0",
    "cordova-js": "^4.2.1",
    "cordova-plugin-file-transfer": "^1.6.3",
    "cordova-plugin-file-opener2": "^2.0.15"
  },
  "devDependencies": {
    "@types/node": "^7.0.18",
    "es6-promise": "^4.1.0",
    "tslint": "^5.2.0",
    "typescript": "^2.3.2"
  }
}
```

tia
Sascha Homeier

**Comment by shomeier** [comment]
**Update:**
As the _file-transfer_ plugin was running out-of-the-box in the developer app I was assuming this should also be true for the _file-opener2_ plugin. But it turned out it is not:

I now build my app locally on Mac for iOS and now the _file-opener2_ plugin works 👍 
But it is very time-consuming to always do a local build for development testing.
I build my app via _"tabris build ios --debug"_ and set the _"EnableDeveloperConsole"_ property to true. So I have the console embedded in my app.
Is there a way to build a Tabrisjs2 Developer App with the functionality to update the sources on-thy-fly like with "tabris serve" and connecting to the Server URL in the app?

tia

**Comment by cookieguru** [comment]
Yes, jump over to the URL tab of your newly-built app.

**Comment by shomeier** [comment]
Sry, there is no URL tab.
I do not have the "Entry Page" with the three tabs "My Sripts", "Examples" and "URL" in my app.
I just have the "Console" which opens when I swipe from right to left.
When I open click on the "Home"-Icon on the upper left of the console drawer I land on the entry page of my app not on the one of the Developer App.

**Comment by cookieguru** [comment]
>  When I click on the "Home"-Icon on the upper left of the console drawer I land on the entry page of my app not on the one of the Developer App.
There's a 50/50 shot I'm wrong on this, but you need to do a cloud build instead of a local build to get those tabs.

**Comment by mpost** [comment]
@shomeier If your app is build with the "debug" switch enabled on tabrisjs.com it will contain the launcher app with the three tabs. If you are building from 2.x-nightly you can actually just use the developer console. It contains the ability to enter an url directly.

**Comment by shomeier** [comment]
Thx for the info.
Unfortenately I am not able to get rid of the following message for an online build:

> Provisioning profile "iOS-AdHoc-dist" doesn't include the aps-environment entitlement.
> Code signing is required for product type 'Application' in SDK 'iOS 10.0'

Could you give me a hint how to set up my Apple Developer Certificate/Provisioning file to solve this?

**Comment by cookieguru** [comment]
https://github.com/eclipsesource/tabris-js/issues/1178#issuecomment-285319627

**Comment by shomeier** [comment]
ok, great. Works as a charme ;)

But one little thing: My app is a browsing app which can connect to different urls (entered by user, so not known in advance). Afaik I need to set the following in Info.plist:

```
<key>NSAppTransportSecurity</key>
<dict>
  <!--Include to allow all connections (DANGER)-->
  <key>NSAllowsArbitraryLoads</key>
      <true/>
</dict>
```
Can I somehow control this in online build?

**Comment by cookieguru** [comment]
@shomeier You shouldn't need to whitelist any URLs.  Unless you are referring to the ability to load content from domains with invalid certificates, which is controlled by the `UseStrictSSL` flag as documented in the [build docs](https://tabrisjs.com/documentation/latest/build#preferences).

**Comment by shomeier** [comment]
@cookieguru Thx for the info.
I hereby close this issue.
