### ISSUE TITLE
Error: Could not find gradle wrapper within Android SDK

### ISSUE THREAD

**Issue by capotti** [eclipsesource/tabris-js#1296]
Build Process "tabris run android" under OSX ->
Error: Could not find gradle wrapper within Android SDK. Might need to update your Android SDK. Looked here: /Users/dirk/Library/Android/sdk/tools/templates/gradle/wrapper 

Environment: I installed Android Studio with SDK r26 with all components, incl. gradle.

But in fact - there is no "template"-folder any longer within "tools".

Workaround:
I had to download Android SDK r25 manually
You can get it from https://dl.google.com/android/repository/tools_r25.2.3-macosx.zip
and copied the template-Folder into my sdk-tools-folder.

node 6.10.3
cordova 7.0.0
tabris 0.4.0

**Comment by mpost** [comment]
This is a bug in older versions of the cordova platform. It is not able to cope with directory changes in the Android sdk. It has been fixed in the latest cordova platform and we have adopted those changes in Tabris 2.x-nightly tabris android platform.

**Comment by capotti** [comment]
perfect!
