### ISSUE TITLE
Support FormData / multipart requests

### ISSUE THREAD

**Issue by shomeier** [eclipsesource/tabris-js#1298]
Is it somehow possible to use multipart forms in Tabris.js 2 beta2?
Either via Fetch API or XMLHttpRequest?

For the following code snippet:
```
let formData = new FormData();
formData.append('content', new Blob(content));
```

... I get the exception:
> Reference Error: Can't find variable: FormData

tia
Cheers
Sascha

**Comment by mpost** [comment]
Since you can perform POST requests with any body you can also construct a form data request.

**Comment by ralfstx** [comment]
[FormData](https://developer.mozilla.org/en/docs/Web/API/FormData) is not yet available in Tabris.js, so you have to assemble the body yourself. You could also try a polyfill such as [formdata-polyfill](https://www.npmjs.com/package/formdata-polyfill).

**Comment by shomeier** [comment]
Thank you both for the info.
I never digged that deep in that layer but it does not seem to be too complicated to write the body myself.
I close the issue.

**Comment by guymeaker** [comment]
I tried to use this solution, formdata-polyfill, but installing the module gave me the following error:
Could not load main module: ReferenceError: Blob is not defined.

Instead I just posted the information as JSON in the body option property.

**Comment by ralfstx** [comment]
Apparently, all available modules build either on browser APIs or on Node APIs. None of them just assembles the multipart message.

I guess we'd have to implement FormData for Tabris.js to support multipart requests.

**Comment by josiahking** [comment]
I ran into an issue whereby i needed to use the formdata object in other to upload file to the server.
Is there a roadmap to adding support for this feature?

**Comment by jokorivai** [comment]
Thank you @mpost for added this to the milestone. While we are waiting, as I am, here is my sample app demonstrating uploading files to server. PHP and NodeJS server code samples are included.

[https://github.com/jokorivai/tabrisjs-upload-file](https://github.com/jokorivai/tabrisjs-upload-file)

**Comment by mpost** [comment]
@jokorivai Hey that is pretty cool. thanks for sharing. 👍
