### ISSUE TITLE
Native bridge cleanup: foreground property

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#1302]
Proposal for Tabris 2.0:

Rename property `foreground` to `textColor` for these widgets:
- Button
- CheckBox
- Picker
- RadioButton
- TabFolder
- TextInput
- TextView
- ToggleButton

**Comment by mpost** [comment]
The property `foreground` is as applied on _TabFolder_, _Slider_ and _ProgressBar_. In these instances the `foreground` property does a different meaning. We should consider renaming the `foreground` as well to fit the usecase.

**Comment by mpost** [comment]
The _Action_ and _SearchAction_ don't have a foreground property but are controlled by the `actionColor` on the _NavigationView_.

**Comment by ralfstx** [comment]
**Update**:
- Removed `Action` and `SearchAction` from the list. They don't support textColor.
- Added `TabFolder` which currently applies the textColor on different visual elements. We should add extra properties for the non-text parts.

For `Slider` and `ProgressBar`, we need to come up with a different property name, `textColor` doesn't have any meaning as they don't have text.

**Comment by ralfstx** [comment]
Implemented on all platforms.
