### ISSUE TITLE
cordova module.exports ok, cordova exports missing

### ISSUE THREAD

**Issue by capotti** [eclipsesource/tabris-js#1305]
Try to export test value within cordova module fails.

`exports.test = 1;`
I would expect `cordova.plugins.test` to be 1.

(Just `module.exports` becomes available in `cordova.plugins`)

**Comment by ralfstx** [comment]
I'd assume that when you export a variable named `test` in a plug-in that is also named `test`, it would be available as `cordova.plugins.test.test`.

However, that looks more like a cordova question than a tabris one.

**Comment by ralfstx** [comment]
This doesn't seem to be a tabris issue. @capotti Feel free to reopen when you need more help.
