### ISSUE TITLE
tabris init -> creates incomplete cordova folder

### ISSUE THREAD

**Issue by capotti** [eclipsesource/tabris-js#1306]
After
`tabris init`
I tried to add a plugin
```
cd cordova
cordova plugin add my-plugin-name
```
But cordova failed with error
`**Error: Current working directory is not a Cordova-based project.**`

I searched for a solution. Solution is just to create an empty www folder. So cordova-folder became a valid "Cordova-based project".

Suggestion:
Let tabris init create an empty www  folder within cordova folder.

**Comment by ralfstx** [comment]
Why don't you just add the plugin to your `config.xml`? For example,

```xml
<plugin name="cordova-plugin-touch-id" spec="3.2.0" />
```

The idea of the CLI is that you shouldn't need to run `cordova`. Adding a `www` folder might also cause confusion. Some folks will start to put content in it that would conflict with the app's content...

**Comment by capotti** [comment]
ok I understand.
(something went wrong with tabris-maps-plugin installation during installation with tabris cli.
so I testet the "alternative way", described in the tabris-plugin-maps documentation
The preferred method is tarbris cli build. I see.
Close the issue.
