### ISSUE TITLE
Build fails to trigger when using non-default signing keys

### ISSUE THREAD

**Issue by cookieguru** [eclipsesource/tabris-js#1307]
### Problem description
After creating an app on the Tabris.js cloud build service, building fails immediately after triggering if using the non*default signing keys.  The keystore was generated and uploaded today.

- Actual Behavior: `ERROR: Failed to trigger build.`
- Expected Behavior: Successful build

**Comment by fwaibel** [comment]
@cookieguru I just checked the logs. Do you use "long" (>117 bytes) secure environment variables or passwords for your keystore?

**Comment by cookieguru** [comment]
@fwaibel It wasn't _that_ long, but I generated a new key that was shorter and it works!  :)

However I'm now seeing the build get cut off at 20 minutes:

```plain
Running "create-artifacts" task
Running "shell:sign_apk" (shell) task
 updating: META-INF/MANIFEST.MF
   adding: META-INF/ANDROIDD.SF
requesting a signature timestamp
TSA location: http://sha256timestamp.ws.symantec.com/sha256/timestamp
   adding: META-INF/ANDROIDD.RSA
  signing: AndroidManifest.xml
  signing: assets/www/LICENSE
...
jar signed.
Running "shell:zipalign_apk" (shell) task
Verifying alignment of com.timbond.seattle.fire.dispatch.apk (4)...
      50 META-INF/MANIFEST.MF (OK - compressed)
  155722 META-INF/ANDROIDD.SF (OK - compressed)
  311660 META-INF/ANDROIDD.RSA (OK - compressed)
  315125 AndroidManifest.xml (OK - compressed)
  317075 assets/www/LICENSE (OK - compressed)
  317832 assets/www/Readme.md (OK - compressed)
...
 4682531 assets/www/node_modules/moment/src/lib/utils/some.js (OK - compressed)
 4682834 assets/www/node_modules/moment/src/lib/utils/to-int.js (OK - compressed)
 4683099 assets/www/node_modules/moment/src/lib/utils/zero-fill.js (OK - compressed)
 4683394 assets/www/node_modules/moment/src/locale/af.js (OK - compressed)
 4684378 assets/www/node

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```
Output is indeed truncated at `assets/www/node`.  I do have a *lot* of files; `node_modules` contains 4,272 files, there are over 4,000 json files and the whole thing tips the scale at about 8,400 files/588 folders.  I could rework those JSON files and get them to about 300, and have future plans to eliminate some of the node dependencies but in the meantime would it be possible to increase the build timer?

**Comment by cookieguru** [comment]
Reducing the number of files cured the timeout issue
