### ISSUE TITLE
use tabris objects within module.exports

### ISSUE THREAD

**Issue by capotti** [eclipsesource/tabris-js#1309]
Try to use tabris objects within own module creates error
`this._cache ist not an Object.`

module:
```javascript
MyModule = function() {
	// ...
};
MyModule.prototype.alert = function (text) {
	new tabris.AlertDialog({ message: text, buttons: { 'ok': 'Ok' }}).open();
};
module.exports = MyModule;
```

call:
```javascript
var m = new require('./mymodule')();
m.alert("ok");
```

**Comment by cookieguru** [comment]
Try this:

```js
class Alert extends tabris.AlertDialog {
	constructor(options, message) {
		options.message = message;
		options.buttons: { ok: 'OK' };
		super(options);
		this.open();
	}
}
```

```js
let Alert = require('Alert');
new Alert({}, 'Foo');
```

Or abbreviate it even more to eliminate the `options` variable.

**Comment by ralfstx** [comment]
The error message `this._cache is not an object` is most likely not related to Tabris.js.

You can have a look at [tabris-plugin-maps](https://github.com/eclipsesource/tabris-plugin-maps) as an example for a Cordova plugin that accesses tabris.

**Comment by capotti** [comment]
@cookieguru Thank you! I understand the principle!!
for reproducers: options.buttons = { ok: 'OK' };

@ralfstx I suppose you're right. My javascript understanding is limited... I try to analyse your sample code.
