### ISSUE TITLE
Enable debug console on iOS

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1310]
I have built the iOS app, on debug mode. Looking for help  to have debug console facility 
- Actual Behavior: not able to swipe left like i do in android
- Expected Behavior: Expected to swipe left to see the console.

### Environment

- Device (name and OS version): iPhone 6
- Tabris.js version: tabris.2.0.0.beta1

**Comment by cookieguru** [comment]
Try swiping from the lower right corner

**Comment by ralfstx** [comment]
Try a four-finger double tap.

**Comment by natanraj** [comment]
@cookieguru Thanks. it worked..
