### ISSUE TITLE
Video not loading with realtive path

### ISSUE THREAD

**Issue by adineag** [eclipsesource/tabris-js#1312]
### Problem description

- Actual Behavior: The video widget is not loading a video defined by a relative path in the url property. It only works when given the full URL, or like this `url: app.getResourceLocation('path/to/video.mp4')`
- Expected Behavior: The video widget should also load a video like this `url: 'path/to/video.mp4'`

### Environment

- Device (name and OS version): Samsung Galaxy Note 4, Android 6.0.1
- Tabris.js version: 2.0.1-20170309-1418

**Comment by mpost** [comment]
@adineag Your expected behavior is correct. We will also allow the Video widget to load local video files with a relative url.

**Comment by mpost** [comment]
The issue has been fixed.
