### ISSUE TITLE
Scratchpad of tabris.js 2 is failing on 'Cannot find module polyfills

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1314]
### Problem description : scratchPad is not working.

- Actual Behavior: cannot find module polyfills is shown
- Expected Behavior: scratchpad is supposed to work

### Environment

- Device (name and OS version): Xiomi, android 6
- Tabris.js version: 2.x nightly

### Code snippet

```javascript
// A minimal, *self-contained* code snippet to reproduce the problem:

```

**Comment by cookieguru** [comment]
Confirmed that the scratchpad does not work after downloading Tabris.js 2.0-rc1 (2.0.2.20170505-1053)

**Comment by ralfstx** [comment]
We're aware of the issue and will fix it in the next days. It's not as simple as it appears, unfortunately. Sorry for the inconvenience.

**Comment by natanraj** [comment]
@ralfstx We are eagerly awaiting this.

**Comment by ralfstx** [comment]
The scratchpad should work again with the latest Developer App.

@natanraj Could you give it another try?

**Comment by cookieguru** [comment]
Working great for me 🙂

**Comment by ralfstx** [comment]
Thanks for testing!

**Comment by natanraj** [comment]
Working. Thanks
