### ISSUE TITLE
problem with the new api for collectionview

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1317]
TabrisJs Version 2.0 RC1
Moto E2 Android 5.1
Hello everyone
By following the new API of collectionview and by using the bookstore example of the application tabris js 2.0 rc1 I wrote this collectionview but nothing is displayed.

 let drawer = tabris.ui.drawer;
        drawer.enabled = true; 
 
 let compositeDrawer = new tabris.Composite({ left: 0, top: 0, height:70, right:0, }).appendTo(drawer);
    
    let textViewCompositeIdentifiant = new tabris.TextView({left:15, top:14, text:"bla bla"
     }).appendTo(compositeDrawer);
    
    let textViewCompositeEmail = new tabris.TextView({left:15, top:30,text:"bla bla"
    }).appendTo(compositeDrawer);
      
    let itemConfig = [{
        title:"examination",
        image:"icons/android/exams_concours.png"
     },
     {
        title:"Planning",
        image:"icons/android/planning_cours.png"
     }];
    
    let drawerCollectionView = new tabris.CollectionView({
        itemCount:itemConfig.length,
        cellHeight:64,
        createCell: () =>{
          let cell = new tabris.Composite({right:0, bottom:0, top: 100, });
          let imageViewCell = new tabris.ImageView({centerY:0, id:"imageViewCell" }).appendTo(cell);
          let textViewCell = new tabris.TextView({centerX:0,id:"textViewCell" }).appendTo(cell);
           return cell;
         },
       updateCell: (view,index) =>{
         let page = itemConfig[index]; 
         view.find("#imageViewCell").set("image",page.image);
         view.find("#textViewCell").set("text", page.title);
        }
        }).on("select", ({index}) =>
          {
           let indexItem = itemConfig.index;
           drawer.close();
        }).appendTo(drawer);

Hope that my snippet is clear

**Comment by cookieguru** [comment]
Try the [Drawer Pages snippet](https://github.com/eclipsesource/tabris-js/blob/master/snippets/drawer-pages.js); it sounds like it's exactly what you're looking for.

**Comment by ishigo1987** [comment]
ok

**Comment by cookieguru** [comment]
I think the main problem is that you aren't setting a height or width for the `CollectionView` which does not have its own intrinsic height/width.

**Comment by ralfstx** [comment]
@ishigo1987 Did this advice help to resolve your problem?

**Comment by ishigo1987** [comment]
yes thank you very much
