### ISSUE TITLE
Native bridge cleanup: Animation

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#1320]
Proposal for 2.0: In `tabris.Animation`, rename the event `Completion` to `completed`.

**Comment by mpost** [comment]
The animation also has a "Start" event that should be lowercase.

**Comment by ralfstx** [comment]
Actually, the JS code doesn't listen to `Start` anymore. That was changed in 9c85bedf633ef675833211019e1244bf7d6ca0d5. Should we remove it from the clients?

**Comment by mpost** [comment]
That could very well be. We should than remove the code from the clients.

**Comment by ralfstx** [comment]
Implemented on all platforms.
