### ISSUE TITLE
bug with highlightOnTouch on widget like collectionView

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1323]
TabrisJs 2.0 RC 1
Android 5.1 Moto E2
highlightOnTouch on the cell of collectionView crash the app

**Comment by cookieguru** [comment]
Can you provide a snippet that reproduces the crash?

**Comment by ishigo1987** [comment]
my own code is too long but i have the same issue when i use the highlightOnTouch, try the bookstore app into the tabris developper app You will see the application crash

**Comment by cookieguru** [comment]
> my own code is too long

A snippet is not your entire code.  A snippet is the fewest number of lines that it takes to reproduce the problem.

> try the bookstore app into the tabris developper app You will see the application crash

The Bookstore example works fine on my Android devices.  Could you post the logcat output from the crash?

**Comment by ishigo1987** [comment]
A snippet is not your entire code. A snippet is the fewest number of lines that it takes to reproduce the problem 
I know that lol
ok tomorrow i will do that

**Comment by mpost** [comment]
The crash has been fixed as described here: https://github.com/eclipsesource/tabris-js/issues/1339#issuecomment-302663555. Please read the comment for steps necessary.

**Comment by mpost** [comment]
The issue has been fixed.
