### ISSUE TITLE
"tabris init" (rc1) still creates package.json "dependencies": { "tabris": "^2.0.0-beta2" }

### ISSUE THREAD

**Issue by capotti** [eclipsesource/tabris-js#1324]

**Comment by cookieguru** [comment]
This belongs in https://github.com/eclipsesource/tabris-js-cli

**Comment by cookieguru** [comment]
Even then, https://github.com/eclipsesource/generator-tabris-js/blob/master/app/generator.js#L132 points to rc1.  Are you certain your `tabris-cli` is up to date?

**Comment by capotti** [comment]
npm update tabris
node@0.1.0 /Users/dirk/Documents/workspace/apps/node
└── tabris@2.0.0-rc2-dev.20170516 
macbook-air:apps dirk$ tabris --version
0.4.0
macbook-air:apps dirk$ mkdir newapp
macbook-air:apps dirk$ cd newapp
macbook-air:newapp dirk$ tarbis init
...
macbook-air:newapp dirk$ less package.json
...
  "dependencies": {
    "tabris": "^2.0.0-beta2"
  },
...

**Comment by cookieguru** [comment]
`tabris` != `tabris-cli`

**Comment by capotti** [comment]
big oooh

**Comment by capotti** [comment]
`npm update -g tabris-cli`
should help?
no change in behaviour

**Comment by cookieguru** [comment]
What does
```bash
npm ls -g | grep generator-tabris-js
```
show?  If you don't see `generator-tabris-js@2.0.0-rc1` you may have a conflicting depdenency.  I just did a fresh install of `tabris-cli` and got this `package.json`:
```json
{
  "name": "x",
  "version": "0.1.0",
  "main": "src/app.js",
  "private": true,
  "scripts": {
    "test": "eslint .",
    "start": "tabris serve"
  },
  "dependencies": {
    "tabris": "^2.0.0-rc1"
  },
  "devDependencies": {
    "eslint": "^3.19.0"
  }
}
```

**Comment by capotti** [comment]
I get this output:
```
macbook-air:~ dirk$ npm ls -g | grep generator-tabris-js
  ├─┬ generator-tabris-js@2.0.0-rc1
```

**Comment by capotti** [comment]
I completely removed tabris-cli and added again.
But additionally I had to restart my computer. Now I get
```
"dependencies": {
    "tabris": "^2.0.0-rc1"
  }
```
(There seems to be an internal caching for node modules...)
Thanks for helping me

**Comment by ralfstx** [comment]
See also https://github.com/eclipsesource/tabris-js-cli/issues/7
