### ISSUE TITLE
Unwanted bottom bar appears in navigation view when toolbar is visible

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1325]
### Problem description

- Actual Behavior: when `toolbarVisible` is set to `true`, an unexpected gray bar appears on the bottom of the navigation view (possibly the bar for actions with low priority).
- Expected Behavior: no gray bar should not appear on the bottom of the navigation view when `toolbarVisible` is set to `true`.

### Environment

- Device (name and OS version): iPad Air, iOS 10.3.1
- Tabris.js version: 2.0.0-nightly; not reproducible with 2.0.0-rc1

### Code snippet

```javascript
let navigation = new tabris.NavigationView({left: 0, top: 0, right: 0, bottom: 0, toolbarVisible: true})
  .appendTo(tabris.ui.contentView);

new tabris.Page({background: 'red'})
  .appendTo(navigation);
```

**Comment by mpost** [comment]
Closing this issue as resolved.
