### ISSUE TITLE
Cannot find module 'crypto'.

### ISSUE THREAD

**Issue by scottie** [eclipsesource/tabris-js#1326]
If i understand correctly crypto is a standard nodejs module that comes with node?
I am trying to transfer a node application to mobile, everything was going great.
a npm install -save crypto doesn't fix this issue, crypto comes with nodejs standard there is no need to install normally.

 I get the error:
"Error: Cannot find module 'crypto' at Module.findNodeModule"

Is this my issue or a tabris issue? I was under the understanding we can use npm modules with tabris.

**Comment by ralfstx** [comment]
Some of the built-in node modules are available from [tabris-js-node](https://www.npmjs.com/package/tabris-js-node). However, `crypto` is not included because it's based on native code that does not run on the mobile device.

There are JS-based crypto libraries out there that work with tabris. We've successfully used [node-forge](https://www.npmjs.com/package/node-forge) in some projects.

**Comment by scottie** [comment]
Thanks kindly, i understand now :) utils will be in tabris-js-node ?

**Comment by scottie** [comment]
Thanks kindly , I understand now,
common utils and such are there.

**Comment by scottie** [comment]
What about standard stuff like net, url ?
I see util is covered by doing:
npm install --save tabris-js-node
require("tabris-js-node");
var path = require("util");

Same goes for net / url ?

**Comment by scottie** [comment]
For future reference, http://eclipsesource.com/blogs/2015/04/24/tabris-js-examples-network-access/

**Comment by ralfstx** [comment]
Unfortunately, `net` and `url` are also not included. `net` includes native code, `url` has some dependencies (such as punycode), but most of [the original code](https://github.com/nodejs/node/blob/master/lib/url.js) should work with tabris. So it may be an option to make at least a subset available.

**Comment by cookieguru** [comment]
> For future reference, http://eclipsesource.com/blogs/2015/04/24/tabris-js-examples-network-access/

IMHO [fetch](https://tabrisjs.com/documentation/latest/w3c-api#fetch) is better
