### ISSUE TITLE
Markup not working on IOS

### ISSUE THREAD

**Issue by scottie** [eclipsesource/tabris-js#1329]
Simple markup works fine on Android, `<b></b>` but does not work on IOS.
HTML markup for text, only using the supported 

`<b></b>.`

https://tabrisjs.com/documentation/latest/api/TextView
> Allows for a subset of HTML tags in the text. Supported tags are: a, del, ins, b, i, strong, em, big, small, br. All tags must be closed (e.g. use <br/> instead of <br>). Nesting tags is currently not supported.
This property can only be set on widget creation. Once set, it cannot be changed anymore.

Would be best to change "Nesting tags currently not supported" to "Markup only supported on Android"?

**Comment by ralfstx** [comment]
@scottie Could that be related to #1242?

**Comment by scottie** [comment]
I spose but the tags are not nested, the documentation says its a supported tag, seems to me in the other issue the user is trying to use not supported tags. Seems that iOS has ZERO markup support as it currently stands, not limited.

**Comment by ralfstx** [comment]
[This snippet](https://github.com/eclipsesource/tabris-js/blob/master/snippets/textview-markupenabled.js) works for me on iOS with the latest Developer App.

Which iOS version / device do you use?

**Comment by capotti** [comment]
Just for completeness: there is an error in the docu
https://tabrisjs.com/documentation/latest/types#font

"bold 24px" won't work - try:

new tabris.TextView({
	left: 10, top: 'prev() 30', right: 10,
	font: "bold 24px",
	text: "bold 24px",
	markupEnabled: false
}).appendTo(tabris.ui.contentView);

new tabris.TextView({
	left: 10, top: 'prev() 30', right: 10,
	font: "bold 24px sans-serif",
	text: "bold 24px sans-serif",
	markupEnabled: false
}).appendTo(tabris.ui.contentView);

**Comment by patrykmol** [comment]
I have checked this issue with all of the snippets in here. All of them work properly. Font doesn't seem to be problem in any scenario. `<b></b>` tags are also working correctly. Tested on iOS 10.3. Closing.
