### ISSUE TITLE
ImageView image scale not reapplied on collection view cell update

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1334]
### Problem description

- Actual Behavior: when the provided code snippet is loaded, the first collection view cell image (cog icon) appears small as expected (scale factor `3`). When scrolling down and then up again (cell is updated), the image appears bigger (as if it would have scale factor `1`).
- Expected Behavior: the collection view cell images should have their scale factors always applied on cell update.

### Environment

- Device (name and OS version): iPad Air, iOS 10.3.1
- Tabris.js version: 2.0.0 nightly (18.05.2017)

### Code snippet

See https://github.com/eclipsesource/tabris-js/blob/b761eb18f32891d35bad3d520eaadebd86ebdbb2/snippets/collectionview-celltype.js

**Comment by 3to1null** [comment]
A similar thing happens when drawing on a canvas in a cell from the 'change:item' function.
