### ISSUE TITLE
NavigationView.pages() should accept a selector

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1341]
### Problem description

- Actual Behavior: `pages()` does not accept a [Selector](https://tabrisjs.com/documentation/latest/types#selector) argument.
- Expected Behavior: `pages()` is documented as behaving similarly to `children()`, thus it should accept a selector argument for convenience.

### Environment

- Tabris.js version: 2.0.0-nightly (19.05.2017)

### Code snippet

```javascript
navigationView.pages(page => page.id !== 'firstPage').dispose(); // should work
```

**Comment by ralfstx** [comment]
Why not `navigationView.pages('#pageId').dispose()`?

**Comment by cpetrov** [comment]
IMO all kinds of [selectors](https://tabrisjs.com/documentation/latest/types#selector) should be supported.
