### ISSUE TITLE
Question about transitions between pages

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1343]
Hello I read in your documentation that the (animate) property of NavigationView has been replaced by pageAnimation and you added that  to prepare the fact that soon we will have custom animations for the transitions between pages.
I would like to know if you mean that we can have something like
PageAnimation: "slide", or pageAnimation: "flip" ect ...
If yes it will be possible when please?

**Comment by mpost** [comment]
@ishigo1987 You are right about the various types of animations. We have no concrete timeline as of right now but it will be after the 2.0 release.

**Comment by ishigo1987** [comment]
ok thank you

**Comment by ishigo1987** [comment]
@mpost any news about page Animation transition?

**Comment by mpost** [comment]
No immediate news but as before you can disable the animation of the page and create a custom animation of your content.

**Comment by ishigo1987** [comment]
Ok thank you, just to be really sure, animations with animate method is done natively and not on the js part right?

**Comment by cookieguru** [comment]
Yes

**Comment by mpost** [comment]
That is correct 👍 .

**Comment by ishigo1987** [comment]
Thank you both of you
