### ISSUE TITLE
BorderColor support for all widgets

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1345]
Hello has when borderColor support for widgets ca becomes urgent because for a collectionView by example it's not possible for cells to have border bottom

**Comment by cookieguru** [comment]
It's already possible.  Just append a 1px high `Composite` to the bottom of your cell.

**Comment by ishigo1987** [comment]
thank you it's work

**Comment by mpost** [comment]
Closing this for now. Please comment if you have any more issues.
