### ISSUE TITLE
Compress javascript code with Google Closure compiler

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1346]
Hello
I want like to know if i can have a bug in my code if i compress it with Google closure compile before to put  my application in production

**Comment by capotti** [comment]
You should test it extensively before production use anyway.
If you use the option "simple" - then it's just minified - this should work well.
But this makes more sence to downloaded scripts to reduce download time.
I have no experience if Closure Compiler can handle node.js modules in "advanced" use.

**Comment by ishigo1987** [comment]
ok

**Comment by cookieguru** [comment]
See also #1231

**Comment by ralfstx** [comment]
As stated before, you can use any JS compressor that works for you, but you should test the results.

**Comment by ishigo1987** [comment]
ok thank you
