### ISSUE TITLE
Cannot set TextInput fill and border color to 'initial'

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1351]
### Problem description

- Actual Behavior: Setting fill and border color to `initial` has no effect.
- Expected Behavior: Setting fill and border color to `initial` should reset those colors to their platform-dependent defaults.

### Environment

- Device (name and OS version): Nexus 5X API 25 emulator/Android 7.1.1; iPhone 5S/iOS 10.2.1
- Tabris.js version: 2.0.0-nightly

### Code snippet

```javascript
const {Button, TextInput, ui} = require('tabris');

let input = new TextInput({
  top: 0, left: 16, right: 16,
  message: 'just a text input',
  borderColor: 'red',
  fillColor: 'green'
}).appendTo(ui.contentView);

new Button({centerX: 0, centerY: 0, text: 'reset input colors'})
  .on('select', () => {
    input.borderColor = 'initial';
    input.fillColor = 'initial';
  })
  .appendTo(ui.contentView);
```

**Comment by karolszafranski** [comment]
iOS client when you set "blue" receives `set` with arguments: 
```
{
    borderColor =     (
        0,
        0,
        255,
        255
    );
}
```

when you set "initial" `set` method is called with argument:
```
{
}
```

@ralfstx Isn't it so that when you set `undefined` as a value than you're removing the key from dictionary/object?

**Comment by ralfstx** [comment]
@karolszafranski No, when you set `obj.foo = undefined` on and empty object, you end up with `{foo: undefined}`. To remove an element you'd have to `delete obj.foo`.

**Comment by ralfstx** [comment]
We currently set the native property to `undefined` in case of `initial` but it should be `null`. See also aa0d6faf2df03ee652eaf6787fbc37ba67a9c93d.
