### ISSUE TITLE
write local file

### ISSUE THREAD

**Issue by capotti** [eclipsesource/tabris-js#1352]
plugin `cordova-plugin-file` does not work.
I added `<plugin name="cordova-plugin-file" spec="~4.3.3" />` to config.xml

and tried
`var reader = new FileReader();`

does not work.
nor
`var reader = new cordova.plugins.FileReader();`

nor
`var reader = new cordova.plugins.FileReader.FileReader();`

I cannot find any other way to write files. Pleas help.

**Comment by cookieguru** [comment]
Sounds like this belongs [here](https://issues.apache.org/jira/browse/CB-5020?jql=project%20%3D%20CB%20AND%20text%20~%20%22plugin%22%20AND%20text%20~%20%22file%22)

**Comment by capotti** [comment]
I do not understand. Sorry, users are not always intelligent ;-)

After integration of the plugin
window.`requestFileSystem` should be available and
`FileReader()` should be global.

but it's both undefined.

**Comment by cookieguru** [comment]
Probably the plugin failed to install; check your build output.

**Comment by capotti** [comment]
no warnings on build

… -c /Users/dirk/Documents/workspace/apps/write/build/cordova/platforms/ios/Write/Plugins/**cordova-plugin-file**/CDVFile.m -o /Users/dirk/Library/Developer/Xcode/DerivedData/Write-fhrgulqlvcdfkbhalangqrdcujwr/Build/Intermediates/Write.build/Debug-iphonesimulator/Write.build/Objects-normal/x86_64/CDVFile.o

CompileC /Users/dirk/Library/Developer/Xcode/DerivedData/Write-fhrgulqlvcdfkbhalangqrdcujwr/Build/Intermediates/Write.build/Debug-iphonesimulator/Write.build/Objects-normal/x86_64/CDVLocalFilesystem.o Write/Plugins/**cordova-plugin-file**/CDVLocalFilesystem.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler …

…

**Comment by capotti** [comment]
successful build.
I need an answer if anybody ever wrote local files with tabris.js - if it is possible with current version or not. Thank you!

**Comment by ralfstx** [comment]
FYI We have plans to include a basic, simple file system API in the upcoming 2.0 release.

**Comment by ralfstx** [comment]
A basic FileSystem API has been introduced in 93d5c80. It will be included in 2.0 RC2 and extended over time.
