### ISSUE TITLE
simple but important webView feature request

### ISSUE THREAD

**Issue by capotti** [eclipsesource/tabris-js#1353]
Is there a function to disallow webVIews overflow scrolling?
I just want to display a snippet of formatted html-code. But always user can overflow scroll on iOS.

**Comment by cookieguru** [comment]
This isn't specific to Tabris.js and there are [several possible solutions](https://www.google.com/search?q=ios+overscroll) out there.

**Comment by capotti** [comment]
I know - it results from wkWebView. But tabris.js is interessted in cross platform compatibility...
So expected behaviour is: same behaviour on all platforms. To target this, an option overflowScroll=true or false just would help programmers. This can't be solved within the html.
The advantage: use of a wevView with limited dimentions can be used to display structured content like a textView.
I just can tell you - other manufaturers provide this property also ;-)

**Comment by cookieguru** [comment]
> This can't be solved within the html.

Yes it can

**Comment by capotti** [comment]
Ok. Thanks for the hint. Than I will find a solution!


Am 23.05.17 um 20:38 schrieb Tim Bond:

**Comment by cookieguru** [comment]
See also #741
