### ISSUE TITLE
Allow text to be focused and selected in TextInput

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#136]
Currently there is no way to select all content in a Text widget and/or focus it, so that the user can either overwrite the content by starting to type, or continue to the next field without changing it.

**Comment by wilsonna** [comment]
:+1:

**Comment by mpost** [comment]
This feature is (still) implemented in Android. Checking on iOS.

**Comment by karolszafranski** [comment]
Property `selection` exists and is implemented in iOS framework. It should work when enabled in JS.

**Comment by mpost** [comment]
Android supports to get and set the selection as a two element array.
iOS currently supports to only set the selection via a two element array. Support to get the current selection is not implemented.

We could create a new property `selection` on the `TextInput` to reflect an array of start and end selection or we could introduce new methods like `setSelection(start, end)` and `getSelectionStart()`/`getSelectionEnd()`.

**Comment by mpost** [comment]
Added in 2.6.1.
