### ISSUE TITLE
"selection" property in TabFolder "select" event object is undefined

### ISSUE THREAD

**Issue by ifurnadjiev** [eclipsesource/tabris-js#1363]
According to the last documentation (https://tabrisjs.com/documentation/latest/api/TabFolder) the event object of the TabFolder "select" event should have a property "selection". It has "tab" property instead.

**Comment by ralfstx** [comment]
I think I tend to rename the event property to `selection` to match with the property that has changed.

**Comment by ifurnadjiev** [comment]
The "select" event of the other widgets (CollectionView, Picker...) has a property "index". Thus, to be consistent, the current state with widget specific "tab" property is a better choice. The other way round is to name this property "selection" in all the widgets!?
