### ISSUE TITLE
Build Service - ERROR: Failed to trigger build.

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#1365]
Tabris Build Service - ERROR: Failed to trigger build. 

iOS and Android, v1.10.0 and v1.10.0-nightly

**Comment by fwaibel** [comment]
I can reproduce this issue.

```
Connection timed out
```

We are experiencing problems connecting to GitHub.

<img width="642" alt="screen shot 2017-05-31 at 15 45 27" src="https://cloud.githubusercontent.com/assets/539039/26634894/4d7b75ac-4618-11e7-92be-6e09037db0b9.png">

App Servers seem to be down: https://status.github.com/

**Comment by bFlood** [comment]
looks like its back up now
