### ISSUE TITLE
Error: Failed to get absolute path to installed module

### ISSUE THREAD

**Issue by iteearmah** [eclipsesource/tabris-js#1366]
### Problem description
**Local build**
```
[build/cordova] cordova platform add /home/itee/tabris-android
Error: Failed to get absolute path to installed module
```
**Remote build log**

Running "shell:cordova_add_platform" (shell) task
Error: Platform android already added.
Warning: Command failed: cordova platform add ../tabris-android
Error: Platform android already added.
 Use --force to continue.
Aborted due to warnings.
/home/travis/.travis/job_stages: line 889:  3862 Terminated              travis_jigger $! $timeout $cmd
travis_time:end:24b3079c:start=1496147852916452755,finish=1496147873313767882,duration=20397315127

The command "travis_wait 40 grunt build deploy" exited with 6.
Done. Your build exited with 1.
[build/cordova] cordova platform add /home/itee/tabris-android
Error: Failed to get absolute path to installed module
### Environment
- Tabris.js version: tabris@2.0.0-rc2-dev.20170530

**Comment by cpetrov** [comment]
@iteearmah, can you post your `config.xml` with replaced/deleted sensitive data?

**Comment by mpost** [comment]
Closing as resolved. Please reopen if you experience any more issues.

**Comment by lavekush1** [comment]
What is the solution ?

> cordova plugin add C:\r\work\custom_plugins\cordova-plugin-webrtc-video-call -
-save
x Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova plugin add
        C:\r\work\custom_plugins\cordova-plugin-webrtc-video-call --s... (exit
        code 1):

        Error: Failed to get absolute path to installed module


C:\r\work>

**Comment by mpost** [comment]
You should list your plugin in the config.xml file. it will be added during the build.

But in that specific case the plugin might not work because it will likely rely on the browsers webrtc capabilities.

**Comment by lavekush1** [comment]
Thanks for your promt feedback

Its custom and local folder. So why should I mention in config.xml


--Lavekush Agrawal

**Comment by cookieguru** [comment]
According to [the Cordova Docs](https://cordova.apache.org/docs/en/latest/config_ref/#plugin) the `spec` attribute will accept a path to a plugin that is in a subdirectory of the current folder.

As @mpost suggested you should just add the plugin to your `config.xml` manually; the cordova cli tool seems to be very finicky when adding plugins.  Also as @mpost suggests it may be a futile effort as the plugin probably depends on browser capabilities and Tabris.js is not a browser enviornment (though [some](https://tabrisjs.com/documentation/latest/w3c-api.html) APIs are implemented).

**Comment by codinronan** [comment]
I am putting this on as many cordova-consuming repos as I can. To anyone else who runs into this, remove the plugin's files from your node_modules folder before re-installing. This fixes it for me every single time it happens - which is alot.

https://stackoverflow.com/questions/43856285/failed-to-get-absolute-path-to-installed-module#comment74749018_43856285

**Comment by zfalen** [comment]
@codinronan this worked for me due to some black magic wizardry.
