### ISSUE TITLE
Improve fs interoperability with cordove plug-ins

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#1371]
All APIs offered by tabris that deal with file paths should behave in the same way, on all platforms. This should improve cross-platform compatibility, avoid confusion, allow the app to use downloaded files as a resource and read bundled files via `fs`.

I suggest these basic rules that would should not cause any breaking changes:
 - All paths not starting with `/` are relative to the directory containing `package.json`. These files are "bundled" and read-only. Paths pointing outside this directory (e.g. `../foo.dat`) are invalid. (see #1210, #722)
 - All paths starting with `/` are "relative" to a os-specific root directory. Known directories can be retrieved from `fs` string properties (currently `filesDir` and `cacheDir`), which include the root slash. These directories have write-access unless noted otherwise.

The following of APIs should honor these rules:
 * `fs` - All methods that take a path. These are not URIs, the strings start directly with the path.
 * `fetch`and `XMLHttprequest`. These are URIs, so if the path is absolute it should start with a scheme, e.g. `file://`, -> `file://${fs.filesDir}/foo.dat`.
 * Widgets, i.e. `Video.url` (see #1312), `WebView.url`, all `image` properties. Since these also accept `http` URLs, absolute paths should probably include a scheme, just like `fetch`/`XMLHttpRequest`.
 * `app.getResourceLocation`: This should convert a relative paths to absolute URLs, so including `http://` or `file://`. Not sure what this would be needed for though. (see below)

We could also directly support the Cordova scheme `cdvfile`, (https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/index.html#cdvfile-protocol) for bundled resources only, which could easy the use of e.g. the media plugin.

Making our absolute paths (non-bundled files) Cordova compatible would probably be more difficult, at least on windows. The file system layouts they describe (https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/index.html#file-system-layouts) do not match our rules. May be `app.getResourceLocation` (or another method) could convert to their system.

**Comment by tbuschto** [comment]
This has been achieved to a degree that I would consider satisfactory for 2.0 - see https://github.com/eclipsesource/tabris-js/issues/1391

What's missing is fetch/XHR support for file URIs and possibly support for paths in Video and WebView, and likely Cordova integration via `app.getResourceLocation`

**Comment by ralfstx** [comment]
Also the native platforms currently don't support relative paths in `fs`.

**Comment by tbuschto** [comment]
@ralfstx 
So there is actually no way to read files bundled with the app via `fs`? (I think it works on windows.)

**Comment by tbuschto** [comment]
As Ivan pointed out, integrating our file system API with cordova plug-ins is currently not straight forward. In one case (camera plug-in) we get a `file://` (or in case of windows `ms-appdata://`) URI, and to get that file from `fs` you have to strip the scheme. Other plugins use `cvdfile://`, which are probably even more complicated. How about new `fs` methods: `pathFromNativeUri`/`pathToNativeUri`, and/or `pathToCdv`/`pathFromCdv`?

**Comment by mpost** [comment]
Needs more research and/or documentation.

**Comment by mpost** [comment]
Since the cordova file plugin is able to handle conversion from and to cdvfile schemes, we close this issue and provide a better tailored solution for image picking via https://github.com/eclipsesource/tabris-js/issues/1881.
