### ISSUE TITLE
How does the file system work?

### ISSUE THREAD

**Issue by Herobone** [eclipsesource/tabris-js#1372]
### Problem description

I want to use the FileSystem API, but I don't know how to use it. I googled it a few times but found nothing that could Help me! Additionally when I type tabris version it shows me 0.4.0, but everywhere is standing that V2 is out! Is this V2 or not? I installed it today and also startrd with it today. I know that reading and writing files is also possible in the way that cordova uses it, but this is so big and complicated! Please help me!  

### Environment

- Tabris.js version: downloaded today with npm it shows 0.4.0
- Device: every
- OS: every

**Comment by cookieguru** [comment]
Running `tabris version` will print the installed version of [`tabris-js-cli`](https://github.com/eclipsesource/tabris-js-cli/). If you want to see the version of Tabris.js that your project you'll need to run `npm ls tabris` from your project's folder.

The filesystem API will be introduced with 2.0.0-rc2, so for now you can [use a nightly build](https://tabrisjs.com/tabris-js-docs/latest/faq.html#development).  The documentation can be found [here](https://tabrisjs.com/tabris-js-docs/latest/api/fs.html).

**Comment by Herobone** [comment]
Ok, thanks. But now I have the porblem on my windows Tabris app it shows simply a Black Console when I log the "fs.filesDir"... 
On my iPhone it shows "undefined"
And BlueStacks dosn't want to start, so I can't test...

**Comment by cookieguru** [comment]
What version do you have installed for JS and what version did you build with?

**Comment by Herobone** [comment]
Node js V6.10.2

**Comment by cookieguru** [comment]
Tabris.js versions

**Comment by Herobone** [comment]
From Package.json:
""tabris": "^2.0.0-rc2-dev.20170611""

**Comment by cookieguru** [comment]
And what version did you build your app against?

**Comment by Herobone** [comment]
Version of what?

**Comment by cookieguru** [comment]
Did you build an app or are you just using the developer apps from the respective app stores?

As I mentioned previously, the `fs` API will be part of `2.0.0-rc2`.  The versions in the app stores is `2.0.0-rc1`, so you'll need to build your own development app in order to use these APIs.

**Comment by Herobone** [comment]
Build it for example with the online service, right? Can i see the console also from the build app?

**Comment by cookieguru** [comment]
Yes, and yes if you build a debug app.

**Comment by Herobone** [comment]
Warning: Could not create object "tabris.FileSystem"
Platform: Android

**Comment by Herobone** [comment]
Windows: Fordern Sie vom Entwickler ein neues App-Paket an. Dieses Paket kann Konflikte mit einem bereits installierten Paket verursachen, von nicht installierten Komponenten abhängen (Paketabhängigkeiten) oder für eine andere Architektur ausgelegt sein (0x80073CF3).
Sorry, I'm german and can't switch the language

**Comment by cookieguru** [comment]
Can you post your code?

You might also try [this snippet](https://github.com/eclipsesource/tabris-js/blob/master/snippets/fs.js)

**Comment by Herobone** [comment]
```javascript
function ab2str(buf) {
    return String.fromCharCode.apply(null, new Uint16Array(buf));
}

function str2ab(str) {
    var buf = new ArrayBuffer(str.length * 2); // 2 bytes for each char
    var bufView = new Uint16Array(buf);
    for (var i = 0, strLen = str.length; i < strLen; i++) {
        bufView[i] = str.charCodeAt(i);
    }
    return buf;
}

console.log(tabris.FileSystem);

FileSystem.writeFile(FileSystem.filesDir + "/hello.txt", str2ab("Hello"));
console.log(ab2str(FileSystem.readFile(FileSystem.filesDir + "/hello.txt")));```

**Comment by cristoferfb** [comment]
Hi ! I have the same problem: 

```
const {WebView, ui, fs} = require('tabris');

let file = fs.fileDir + '/src/newSession/newSession.html';
```

I have the next error message in IOS (Tabris.js 2 app):

> Could not load main module: TypeError: undefined is not an object (evaluating 'fs.fileDir)

**Comment by mpost** [comment]
Initial file system support will be available in the upcoming (next few days) Tabris.js 2.0 RC2. Until than you can experiment with it using the `nightly` version of Tabris.js

**Comment by Herobone** [comment]
Thanks! This helped me much! Now I build my App one time, installed it on Bluestacks and I am broadcasting the app now the common way ('$ tabris serve') an connect from the dev-app via IP

If you want to have a look at it you can find the source [here!](https://github.com/Herobone/food-app)

**Comment by cookieguru** [comment]
FYI there's also [`localStorage`](https://tabrisjs.com/tabris-js-docs/latest/w3c-api.html#persistent-storage)
