### ISSUE TITLE
Info need - on latest announcement

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1375]
### Problem description

I am seeing 'We switched to Tabris CLI for 2.x builds - please check the docs for details'. May you please where this docs are ?

Besides my debug app built over Cloud build is not having developer / debug enabled. Am i missing something ?

**Comment by ralfstx** [comment]
Yes, we should include a link, sorry. But you know our [docs](https://tabrisjs.com/documentation/latest), don't you? It's the first link on tabrisjs.com.

We don't wrap debug apps in the Tabris Developer App anymore, as the developer console now includes a URL field to load JS code served by the CLI. To enable the developer console, please include the preference:

```xml
<preference name="EnableDeveloperConsole" value="$IS_DEBUG" />
```

**Comment by natanraj** [comment]
@ralfstx Thanks. let me try this. Hope the cloud build will still work and Developer app support Scratchpad.

**Comment by cookieguru** [comment]
@natanraj Yes, cloud build still works.  The developer app in the app stores will still support the scratchpad

**Comment by natanraj** [comment]
@cookieguru thanks. I verified this after installing latest Dev Apps. Thanks

I am testing this app, in parallel through Tabris CLI. I get this error 

'Error: Cannot find module 'update-notifier'
    at Function.Module._resolveFilename (module.js:438:15)
'
But i could see this update-notifier is already installed. Any suggestions, please

**Comment by cookieguru** [comment]
@natanraj Are you using the same versions on the JS side and the app?

**Comment by natanraj** [comment]
I am still not into App. I am setting the server side so that i can see them on Dev App..

**Comment by natanraj** [comment]
correction : 

```
To initialize your project:
Type cd to an empty project directory.
Type tabris init.
```
I am attempting this

**Comment by cookieguru** [comment]
I don't understand, what code are you executing and how are you executing it?

**Comment by natanraj** [comment]
@cookieguru I am inside AWS and trying to setup a Developer App so that i can run using <aws_ip>:8080 port.

**Comment by natanraj** [comment]
@cookieguru  
I am following these inside the AWS: (I already installed tabris-cli)

```
Creating a new Tabris.js project
tabris init
... will guide you through creating a Tabris.js project structure in the current directory.

Serving a Tabris.js app
tabris serve
... will start a server you can point the **Tabris.js developer app to.**

Request logging can be enabled using the option --logging or -l.
```

**Comment by cpetrov** [comment]
> @cookieguru thanks. I verified this after installing latest Dev Apps. Thanks
> I am testing this app, in parallel through Tabris CLI. I get this error
> 'Error: Cannot find module 'update-notifier'
> at Function.Module._resolveFilename (module.js:438:15)
> '
> But i could see this update-notifier is already installed. Any suggestions, please

@natanraj The dependency `update-notifier` was declared in a wrong way in tabris-cli. Affected is the latest tabris-cli version 0.5.0. We will release a patch version containing a fix.

Please use 0.4.0 meanwhile:

```bash
npm install -g tabris-cli@0.4.0
```

**Comment by ralfstx** [comment]
A fix has been released for tabris-cli, please update to the latest version (0.5.1):
```
npm update -g tabris-cli
```
