### ISSUE TITLE
Support for events in JSX

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#1376]
```
    private render() {
        return (
            <textView on-tap={()=>doThis()}></textView>
        );
    }
```

It would be nice to have the JSX create element support this type of syntax, as I dont believe `new TextView({tap:()=>{}})` works.

If we can agree on the syntax for on, I will submit a pull request tonight.

**Comment by dalisoft** [comment]
This would be awesome like #1381

**Comment by tbuschto** [comment]
Supported as of 2.1
