### ISSUE TITLE
Cloud Build is failing

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1377]
Log shows some build errors for JavascriptMessageSender

**Comment by cookieguru** [comment]
You'll need to be more specific; a build log will help immensely

**Comment by natanraj** [comment]
There are 7 errors.
`error: JavaScriptMessageSender is not public in com.eclipsesource.tabris.android.internal.javascript; cannot be accessed from outside package
import com.eclipsesource.tabris.android.internal.javascript.JavaScriptMessageSender;
                                                           ^
/home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/android/CordovaLib/src/com/eclipsesource/tabris/android/cordova/CordovaInterfaceImpl.java:47: error: cannot find symbol
          widgetToolkit.showError( e );
                       ^
  symbol:   method showError(Exception)
  location: variable widgetToolkit of type IAndroidWidgetToolkit
/home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/android/CordovaLib/src/com/eclipsesource/tabris/android/cordova/CordovaInterfaceImpl.java:73: error: cannot find symbol
            widgetToolkit.showError( e );
                         ^
  symbol:   method showError(Exception)
  location: variable widgetToolkit of type IAndroidWidgetToolkit
/home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/android/CordovaLib/src/com/eclipsesource/tabris/android/cordova/TabrisWebView.java:106: error: cannot find symbol
    IMessageSender messageSender = activity.getWidgetToolkit().getMessageSender();
                                                              ^
  symbol:   method getMessageSender()
  location: interface IAndroidWidgetToolkit
/home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/android/CordovaLib/src/com/eclipsesource/tabris/android/cordova/TabrisWebView.java:107: error: cannot find symbol
    if( messageSender instanceof JavaScriptMessageSender ) {
                                 ^
  symbol:   class JavaScriptMessageSender
  location: class TabrisWebView
/home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/android/CordovaLib/src/com/eclipsesource/tabris/android/cordova/TabrisWebView.java:108: error: cannot find symbol
      JavaScriptMessageSender sender = ( JavaScriptMessageSender )messageSender;
      ^
  symbol:   class JavaScriptMessageSender
  location: class TabrisWebView
/home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/android/CordovaLib/src/com/eclipsesource/tabris/android/cordova/TabrisWebView.java:108: error: cannot find symbol
      JavaScriptMessageSender sender = ( JavaScriptMessageSender )messageSender;
                                         ^
  symbol:   class JavaScriptMessageSender
  location: class TabrisWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
7 errors`

**Comment by mpost** [comment]
The nightly was broken on tabris-android but should be fixed by now. Please retry.
