### ISSUE TITLE
"The executable contains an invalid signature" error with RC2 iOS Online Builds

### ISSUE THREAD

**Issue by shomeier** [eclipsesource/tabris-js#1378]
After switching to RC2 the online built *.ipa file is no more deployable to my iPhone:
When trying to deploy via XCode -> Devices the following error occurs:
**"App installation failed - The executable contains an invalid signature"**

I tried with a developer provisioning profile (which also worked with RC1 builds) and with an AdHoc provisioning profile.

Enabled Developer Console like described in doc for RC-2:
`<preference name="EnableDeveloperConsole" value="$IS_DEBUG"/>`

**Comment by cpetrov** [comment]
There is a problem with signing iOS apps on https://tabrisjs.com. We are currently working on a solution.

**Comment by cpetrov** [comment]
Issues with signing iOS apps on https://tabrisjs.com should be resolved now. Please reopen if you still have any problems.
