### ISSUE TITLE
FEATURE REQUEST: SVG, CSS-like syntax and etc...

### ISSUE THREAD

**Issue by dalisoft** [eclipsesource/tabris-js#1381]
### Features Request (Implemented myself i checked)
- [x] `requestAnimationFrame` - i can help with that, so how i should do it
- [ ] `Hot Reload and/or Live Reload` - have `rollup, brunch, webpack` implementation, but hasn't client (tabris dev app) implementation (HELP ME WITH IT)
- [x] `SVG`
- [x] `CSS-like polyfill` implementation
- [x] some of `React Native` components (partly)
- [x] extendable components (with it no need learn Objective-C side)
- [ ] Improving `Animation class`
### `requestAnimationFrame` polyfill for beginners
```javascript
window.requestAnimationFrame = ( fn ) => {
	return setTimeout( fn, 0 );
};
window.cancelAnimationFrame = ( timerId ) => {
	return clearTimeout( timerId );
};
```

### Hot/Live Reload
NOTE: This is code is just for providing example, maybe code looks like this
```javascript
// https://stackoverflow.com/a/12411705
let process = require( 'process' );
let cp = require( 'child_process' );
let fs = require( 'fs' );

let server = cp.fork( 'server.js' );
console.log( 'Server started' );

fs.watchFile( 'server.js', ( event, filename ) => {
	server.kill();
	console.log( 'Server stopped' );
	server = cp.fork( 'server.js' );
	console.log( 'Server started' );
} );

process.on( 'SIGINT', () => {
	server.kill();
	fs.unwatchFile( 'server.js' );
	process.exit();
} );
```

##### SVG
```javascript
// https://github.com/canvg/canvg
// SVG.js
// canvg( document.getElementById( 'drawingArea' ), '<svg>...</svg>' );

window.SVGPolyfill = () => {};
export class SVG extends window.SVGPolyfill {
	constructor( { tagName, ...attributibutes } ) {
		this.tagName = tagName;
		attributes = attributes || [];
		attributes.map( ( val, key ) => {
			this[ key ] = val;
		} );
		canvg( document.getElementById( 'drawingArea' ), '<svg><${tagName} ${...attributes.join(" ")}/></svg>' );
	}
}

export default function( svgTagName ) {
	return new SVG( svgTagName );
}
```

##### CSS-like polifill
```javascript
// https://www.npmjs.com/package/css-to-js-object
// CSS-like.js
import Converter from 'css-to-js-object';

// From CSS to Tabris.js Style-syntax
const ConvertizeMap = {
	color: 'textColor'
	, align: 'alignment'
	, ...etc
}

export default class CSSParser {
	constructor( { fileOrText } ) {
		if ( typeof fileOrText === "string" ) {
			if ( fileOrText.includes( "{" ) && fileOrText.includes( "}" ) ) {
				this.css = Converter( fileOrText );
			} else {
				this.css = Converter( require( fileOrText ) );
			}
		}
	}
	convertTo( oldObj ) {
		Object.keys( oldObj )
			.map( key => {
				if ( ConvertizeMap[ key ] ) {
					this.css[ ConvertizeMap[ key ] ] = this.css[ key ];
					delete this.css[ key ];
				}
			} );
			return this.css;
	}
}
```

### Some components
- [x] `View`
- [ ] `BlurView`
* much more

### Extendable
This for better purpose like supporting/adding 3D Peek and Pop Touch feature on iPhone, that implemeneted on React-Native

### JSX Events
- [x] Already implemented

### Welcome review for this request
Please let me know where i am missing and wrong typed.

**Comment by cookieguru** [comment]
Hot reload is already being tracked in [#1018](https://github.com/eclipsesource/tabris-js/issues/1018)

**Comment by dalisoft** [comment]
But not yet implemented

**Comment by cookieguru** [comment]
True, but one issue is enough; two just adds confusion.

As to your CSS request, would [this existing behavior](https://github.com/eclipsesource/tabris-js/blob/master/snippets/widget-styling.js) suffice?

**Comment by cookieguru** [comment]
Your suggestion for SVG would not work since there is no DOM, and thus no `document`.  SVG support is tracked in [https://github.com/eclipsesource/tabris-js/issues/794](#794).

**Comment by dalisoft** [comment]
I have question. If i am fork project and implement it then how i can test it work?

**Comment by cookieguru** [comment]
If you are modifying only the JS code, you would remove the `tabris` dependency from your `package.json` and then [add your fork like you would any other repository](https://www.google.com/search?num=100&q=install+an+npm+package+from+GitHub+directly).

If you are modifying native code, note that the sources are only available under an [https://tabrisjs.com/pricing](organization plan), but you could also get things to work with [custom widgets](https://tabrisjs.com/tabris-js-docs/latest/custom-widgets.html).

**Comment by dalisoft** [comment]
I cant modify native code not only because paid, i am not know the language of Objective C or Java. I am want edit JS site and test on Tabris Dev app, but both dev app and cloud build get tabrisjs from your files or npm maybe. Not from my file, thats why i am asking from you're to help how i can test

**Comment by dalisoft** [comment]
I looked for ReactNative just for a day and then return to this app. Because tabris is fast and ultra easy with Cordova support especially for low end pc without dependecy

**Comment by cookieguru** [comment]
> I am want edit JS side and test on Tabris Dev app, but both dev app and cloud build get tabrisjs from your files or npm maybe.

I'm not quite sure what you mean.  If you want to edit the Tabris.js JavaScript framework, then you would _remove_ the `tabris` dependency and install your own.  When the app gets built, an `npm install` will be executed against your `package.json` and only those dependencies will be installed.

**Comment by dalisoft** [comment]
Even i am use own fork tabrisjs devapp and libraru when build with online build loads tabrisjs from official file (tabris.js file)

**Comment by mpost** [comment]
@dalisoft As @cookieguru pointed out you can serve your own forked tabris.js by just replacing the tabris depdency in the package json and serving it locally with `tabris serve`. You can than use the dev app from the store to load your app with your custom tabris.

**Comment by dalisoft** [comment]
Ok so when building with cloud service i can point my library insteadof tabrisjs?

**Comment by mpost** [comment]
You can point it to all places where npm would be able to pick it up.

**Comment by dalisoft** [comment]
Ok, thanks. I am now implementing my own features to my renamed repo 'tez-native';

**Comment by dalisoft** [comment]
@mpost I did it and added some of my feature like `View` and JSX events (#1376) for beginning and when i am loading the my from dev-app it says `tabris` module not defined, but i have `tez-native` module even on `npm`

**Comment by mpost** [comment]
you need to build tabris to consume it.

could you post your package.json?

**Comment by dalisoft** [comment]
```json
{
  "name": "my-sample-app",
  "version": "0.1.0",
  "main": "dist/App.js",
  "private": false,
  "scripts": {
    "test": "eslint .",
    "start": "tabris serve",
    "build": "rollup -c --environment BUILD:prod",
    "source": "rollup -c --sourcemap",
    "prepublish": "npm run source && npm run build",
    "dev": "rollup -c -w --sourcemap"
  },
  "dependencies": {
    "es6-tween": "latest",
    "tez-native": "^2.0.0-rc2-dev.20170616"
  },
  "devDependencies": {
    "eslint": "^3.19.0",
    "rollup": "^0.41.6",
    "rollup-plugin-buble": "^0.15.0",
    "rollup-plugin-uglify": "^2.0.1",
    "rollup-watch": "^3.2.2",
    "uglify-es": "^3.0.11"
  }
}
```

**Comment by dalisoft** [comment]
I am run `grunt` for compile then publish to `npm`, look at [tez-native](https://www.npmjs.com/package/tez-native)

**Comment by mpost** [comment]
Is the build output properly published as tabris on npm?

**Comment by dalisoft** [comment]
I think yes, but you can check yourself, exactly like tabris.js i am exported (files are in same structure)

**Comment by mpost** [comment]
@ralfstx Do you have an idea why it wouldn't work?

**Comment by dalisoft** [comment]
Maybe i can export with `Rollup + Bubble`, i no need TS anyway and do not want use it. I want simple, lightweight way

**Comment by dalisoft** [comment]
@mpost You can see tabris file at [here](http://cdn.jsdelivr.net/npm/tez-native)

**Comment by dalisoft** [comment]
This is still Issue, because tabris dev app doesn't support the custom tabris module

**Comment by dalisoft** [comment]
I think there much of issue and developers do not time to see issue as working on implementation and other apps. As real, this issue was fixed, i should open another issue for fixing to errors while building my own tabris build
