### ISSUE TITLE
Tabris.js XMLHttpRequests not accepting responses: readystate 1

### ISSUE THREAD

**Issue by CooperITP** [eclipsesource/tabris-js#1382]
### Problem description

I have a tabris.js app that I needed to connect to a SQL database. In order to do so, I decided the best option would be to create an express REST API and then make XMLHttpRequests to it. When the app makes a request, the REST API shows that a GET request has been made and even responds with a result. I have tested it in a browser and found that the result is being returned flawlessly. The problem is that the readystate of the XHR never leaves 1 and therefore onload/onreadystatechange is never called. At one point I had this app working so I don't know what happened. I will include some mock REST API code and the Tabris.js code below. I should also note that the fetch API does the same thing: the REST API gets the request but the app never gets a timeout, error, or success.

### Expected behavior

Successful responses from the REST API and readyState changes from 1 to 4

### Environment

- Tabris.js version: 2.0.0-rc2-dev
- Device: iPhone 6S
- OS: iOS 10.3.3 Developer beta 3

### Code snippet

REST API:
```javascript
router.get('/', function(req, res) {
    res.json({Mock: 'Code'})
})
```

Tabris:
```javascript
const xhr = new XMLHttpRequest()

xhr.onload = function() { /* Not called */ }
xhr.onerror = function() { /* Not called */ }
xhr.onabort = function() { /* Not called */ }
xhr.ontimeout = function() { /* Not called */ }

xhr.onreadystatechange = function() {
    switch (xhr.readyState) {
        case 1: console.log('opened, not sent'); break // Called
        case 2: console.log('sent, awaiting response'); break // Not called, even though the API gets the request
        case 3: console.log('response received, downloading'); break // Not called
        case 4: console.log('finished'); break // Not called
    }
}

xhr.open('GET', 'http://ip.ad.dr.ess:port/', true)
xhr.send()
```

**Comment by cookieguru** [comment]
Can you post your fetch code?

**Comment by CooperITP** [comment]
```javascript
fetch('http://ip.ad.dr.ess:port/', {
    method: 'GET'
}).then(function(res) {
    // Not called
})
```

**Comment by cookieguru** [comment]
Does the [fetch example](https://github.com/eclipsesource/tabris-js/blob/master/examples/fetch/fetch.js) work on your device when using the Tabris.js Developer App from the App Store?
What happens when you put that same URL in to the browser on the device?

**Comment by cookieguru** [comment]
Also, you might try adding a `catch` to your `fetch` to see what the error is.

**Comment by mpost** [comment]
Adding the catch() to the fetch will help in identifying the problem. Could you provide the concrete end point so that we can try out the request ourselfs? Could you try it on Android?

**Comment by karolszafranski** [comment]
If it's iOS specific, and you don't use Tabris Developer app from the app store, reason might also be SSL.

https://github.com/eclipsesource/tabris-js/issues/1383

**Comment by CooperITP** [comment]
Well I am not sure at all what happened, but today I came in and started both up and it is working just fine. The only thing I did do was tried to update tabris, though no real update happened. I was on the current version as it was. Maybe I modified those files by accident in a really inconvenient way? Not sure.

**Comment by mpost** [comment]
Good to hear that it worked in the end.

Could you also comment on SO that you managed to solve the issue?

**Comment by CooperITP** [comment]
Sure. Someone did their research.
