### ISSUE TITLE
Fetch API not working on built apps

### ISSUE THREAD

**Issue by shomeier** [eclipsesource/tabris-js#1383]
When using the fetch API it works on scratchpad with official Tabris.js 2 Developer App but not on built apps (Cloud Build).
For example the following snippet works on scratchpad:
```
fetch("http://freegeoip.net/json/github.com").then(response => {
                return response.json();
            }).then(res => {
                console.info("RES: " + JSON.stringify(res));
                console.info("The IP address is: " + res.ip);
                console.info("Latitude: " + res.latitude);
                console.info("Longitude: " + res.longitude);
            }).catch((err) => {
                console.info("Error: ..." + err);
                console.info("Error: ..." + JSON.stringify(err));
            });
```

But on an app build with the cloud build service it throws the following error:
```
> Error: ...TypeError: Network request failed
> Error: ...{"line":32,"column":127591,"sourceURL":"http://192.168.1.102:8080/./node_modules/tabris/tabris.js"}
```

While IPs in the local network work hostnames do not.

**Notes:**
Using RC2.
Not doing any special imports in package.json (like whatwg-fetch or promise).

**Comment by mpost** [comment]
What platform are you seeing the problem on?

**Comment by shomeier** [comment]
Sry, I forgot. It is iOS

**Comment by mpost** [comment]
Does the fetch() example work for you on iOS? The example also uses fetch() in a bundled app.

**Comment by shomeier** [comment]
Yes, it does work.
Also my app and the example above works if I load them via local URL ("tabris serve") into the official Tabris Developer App (but not when built as an own single app).
Maybe I need to consider sth. in config.xml or package.json?

**Comment by karolszafranski** [comment]
Does it work with `https://`? If yes, than you have to disable App Transport Security in your build.

**Comment by tbuschto** [comment]
If it's the reverse it could also be `UseStrictSSL`? Or mayble `access`?

**Comment by shomeier** [comment]
Ahhh...damn, I totally forgot about that issue with plain http on iOS.
Yes, it works with https.  Sry for wasting your time here.
Is there an option to disable App Transport Security for cloud build?
If I remember right in local build I need to tweak a *.plist file

**Comment by karolszafranski** [comment]
To define any App Transport Security exceptions you have to use `<access>` and `<allow-navigation>` tags in cordova Config.xml file.

https://cordova.apache.org/docs/en/latest/config_ref/#access

**Comment by shomeier** [comment]
Thanks very much.
It worked with an <access> wildcard.
Closing this issue now.
