### ISSUE TITLE
Can't connect to URL, Tabris crashes

### ISSUE THREAD

**Issue by benoitkoen** [eclipsesource/tabris-js#1385]
### Problem description

I do not have the welcome page with Github sign in, etc...
When I go the developer console and try to connect to URL, the app crashes.

### Environment

- Tabris.js version: 2.0
- Device: Iphone 5
- OS: IOS 8.4.5

### Code snippet

```javascript
// A minimal, *self-contained* code snippet to reproduce the problem:
```

**Comment by cookieguru** [comment]
Is this an app you've built yourself or are you grabbing the developer app from the App Store?

**Comment by benoitkoen** [comment]
The one from the App store. I mean, I am just starting, so I did not modify anything. I do not have access to the welcome page...

**Comment by mpost** [comment]
The crash originates from the old iOS 8 version. We will drop support for iOS 8 for Tabris.js 2 so you will need to update your device.

**Comment by ralfstx** [comment]
See #1388

**Comment by mpost** [comment]
Closing as resolved since we dropped support for iOS8.
