### ISSUE TITLE
Recommended way to render "tables"

### ISSUE THREAD

**Issue by 3to1null** [eclipsesource/tabris-js#1386]
I'm going to rewrite my application completely this summer, since it's using Tabris 1, and I don't like the way certain functions are written.

In the old app, I'm using a collectionview to render a 5 by 9 grid, while it works alright on high-end devices, it generates quite a lot of dropped frames on low-end devices. I was wondering if there is a more efficient way to render tables. 

Since I control the backend I'm also able to generate a composite structure, and display that, but I don't know if that is possible in Tabris, and I'd prefer to stay with a normal JSON API that can be used by different apps & frameworks.

This is the code I use to render the collectionview.
```
		new tabris.CollectionView({
			layoutData: {
				left: 0,
				top: collectionTopMargin,
				right: 0,
				bottom: 0
			},
			class: 'roosterCollection',
			items: data,
			itemHeight: 20 * cellAmount,
			columnCount: 5,
			initializeCell: function(cell){
				var leraar = new tabris.TextView({
					layoutData: {
						top: topLeraar,
						height: 20,
						}})
				if(localStorage.getItem('-s-showLeraar') != 'false'){
					leraar.appendTo(cell)
				}
				var klas = new tabris.TextView({
					layoutData: {
						top: topKlas,
						height: 20,
					}})
				if(localStorage.getItem('-s-showKlas') == 'true'){
					klas.appendTo(cell)
				}
				var vak = new tabris.TextView({
					layoutData: {
						top: topVak,
						height: 20,
					}
				}).appendTo(cell)
				var lokaal = new tabris.TextView({
					layoutData: {
						top: topLokaal,
						height: 20,
					}
				}).appendTo(cell)
				var n = 1
				cell.on("change:item", function(widget, data){
					if(data['__render__'] != false && data['__render__'] != 'False'){
						leraar.set("text", data.teachers)
						if(data.groups.length < 3){
							klas.set('text', data.groups)
						}else{
							klas.set('text', data.groups[0] + " +" + String(data.groups.length - 1))
						}
						lokaal.set("text", data.locations);
						vak.set("text", data.subjects);
					} else {
						klas.set('text', '')
						leraar.set('text', '')
						lokaal.set('text', '');
						vak.set("text", '');
					}
					cell.set("background", get_background_color(data))
				})
			} 
		})
```

**Comment by cookieguru** [comment]
See #526 and #626.  Google's [Material Design Guidelines for tables](https://material.io/guidelines/components/data-tables.html) also has a wealth of information on the overall design of tables.

Due to the constrained horizontal space, tables are usually a less than ideal UI on a mobile device.  A way around this is to use a `CollectionView` displaying two or three key datapoints for each row item and then bringing up a new page for the user to see more details upon tapping the row.

**Comment by 3to1null** [comment]
I'm going to do some testing with a webview, and see if it is faster (this would be kinda weird, though).
#626 probably won't solve any performance issues.

To clarify, the content fits the screen, and it is readable. The problem is the performance on low-end phones.

**Comment by mpost** [comment]
We have made some improvements on the underlying communication with the CollectionView for Tabris.js 2.x, which should speed things up a bit. Depending on your workload (eg number of cells/rows) the layouting required could take some time.

**Comment by ralfstx** [comment]
Could you explain what you mean by a "composite structure" as opposed to a "normal JSON API"?

**Comment by 3to1null** [comment]
@ralfstx I meant creating the complete layout server-side and only displaying it client-side. So there would be no looping over items, no if statements etc. In a HTML/JS environment this is really easy to implement, but I don't think this will be possibly, or at least not easy, with Tabris. (Except maybe in a webview, but I'd rather not use those.)

@mpost I'll try and see if the improvements in the 2.x version are good enough.

Thanks for the help!

**Comment by ralfstx** [comment]
@3to1null 
> creating the complete layout server-side and only displaying it client-side. So there would be no looping over items, no if statements etc.

That doesn't sound like a viable option. Just make sure the code that updates the cells is fast (your code looks good in that regard) and if you still have performance issues with Tabris 2.0, please let us know.
