### ISSUE TITLE
Background sync/service (android)

### ISSUE THREAD

**Issue by 3to1null** [eclipsesource/tabris-js#1387]
Is there any way to sync app data with an API while the app is not running? The only plugin I found is https://www.npmjs.com/package/cordova-plugin-service-worker-background-sync, but it seems to work using service workers, which are not supported by Tabris.

**Comment by cookieguru** [comment]
I think https://github.com/eclipsesource/tabris-js/issues/1106#issuecomment-274434025 is still relavant

**Comment by mpost** [comment]
Supporting WebWorker would be an interesting option but as of know it is not supported.

**Comment by 3to1null** [comment]
I think Firebase's data messages are good enough for my needs, but WebWorker would be a nice addition to Tabris.

**Comment by ralfstx** [comment]
Thanks. For web workers, we have #358.
