### ISSUE TITLE
Drop support for iOS 8

### ISSUE THREAD

**Issue by karolszafranski** [eclipsesource/tabris-js#1388]
According to statistics provided by AppStore on 5th June, only 3% of devices are using iOS version earlier than 9, additionally all iOS 8 capable devices are eligible for iOS 9 update.

<img width="321" alt="screen shot 2017-06-19 at 11 12 37" src="https://user-images.githubusercontent.com/1746396/27278159-d41626da-54e0-11e7-9921-936d94b61c1d.png">

**Comment by ralfstx** [comment]
@karolszafranski Is there any change required on the native side? Do we actively exclude unsupported versions?

**Comment by karolszafranski** [comment]
I suppose need to update only https://github.com/eclipsesource/cordova-ios (build template).

**Comment by ralfstx** [comment]
iOS 8 is not officially supported in Tabris 2.0 anymore.
