### ISSUE TITLE
"cordova-plugin-geolocation" does not work under Android

### ISSUE THREAD

**Issue by ifurnadjiev** [eclipsesource/tabris-js#1390]
Plugin URL: https://github.com/apache/cordova-plugin-geolocation
Tested with tabris.js 2.0-rc2. 
JS error is thrown when using navigator.geolocation.getCurrentPosition function.
Internally it uses:
```
var geo = cordova.require('cordova/modulemapper').getOriginalSymbol(window, 'navigator.geolocation');
geo.getCurrentPosition(success, error, args);
```
As a result the `geo` variable is undefined.

**Comment by lakexyde** [comment]
Yeah it doesn't...  Ran into the same issue.  It appears to rely on the Webview so shouldn't work with tabrisjs. 

Use ```cordova-plugin-locationservices``` instead. It was develop to solve the issue with Android.

Hope it helps.

**Comment by mpost** [comment]
Closing as resolved.
