### ISSUE TITLE
Can't load image from absolute path

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#1391]
### Problem description

On Android, an ImageView does load an image from an absolute URL like `fs.filesDir` and `fs.cacheDir`.
The snippet below works on iOS:

### Code snippet

```javascript
const {ImageView, fs, ui} = require('tabris');

let file = fs.cacheDir + '/test.png';

let imageView = new ImageView({
  left: 10, top: 10, width: 100, height: 100,
  background: '#aaaaaa'
}).appendTo(ui.contentView);

fetch('http://httpbin.org/image/png')
  .then(res => res.arrayBuffer())
  .then(data => fs.writeFile(file, data))
  .then(() => imageView.image = file)
  .then(() => console.log('image:', file))
  .catch(err => console.error(err));
```

**Comment by mpost** [comment]
The issue has been fixed on Android. However on iOS the loaded image is scaled to be the size of the target `ImageView` instead of having its own native resolution. Opened an issue for that: https://github.com/eclipsesource/tabris-js/issues/1392

**Comment by tbuschto** [comment]
Also needs to be fixed on windows.

**Comment by tbuschto** [comment]
Fixed.
