### ISSUE TITLE
Loading image from disc into ImageView scales the image unexpectedly 

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1392]
### Problem description

Writting an image to disc via the `fs` api and than loaded into an ImageView by path leads to an image that is scaled to fit the entire `ImageView`, instead of having its default intrinsic size.

### Expected behavior

The image should not cover the entire `ImageView` and have its own intrinsic size.

### Environment

- Tabris.js version: 2.0
- Device: iPhone SE
- OS: 10

### Code snippet

Note that the `ImageView` has its default scaleMode set to `auto`.

```javascript
let file = tabris.fs.cacheDir + '/test.png';

let imageView = new tabris.ImageView({
  left: 10, top: 10, width: 100, height: 100,
  background: '#aaaaaa'
}).appendTo(tabris.ui.contentView);

fetch('http://httpbin.org/image/png')
  .then(res => res.arrayBuffer())
  .then(data => tabris.fs.writeFile(file, data))
  .then(() => imageView.image = file)
  .then(() => console.log('image:', file))
  .catch(err => console.error(err));
```

**Comment by karolszafranski** [comment]
I need more detailed explanation. Image size is 100x100px. Here is how it looks like in your snippet with different ImageView Sizes.


50x50 | 100x100 | 200x200
---|---|---|
![img_9461](https://user-images.githubusercontent.com/1746396/27475641-3fcf8cea-5806-11e7-990c-bc481c8f3803.PNG) | ![img_9459](https://user-images.githubusercontent.com/1746396/27475646-473d9b8e-5806-11e7-8d5c-94129ffba63b.PNG) | ![img_9460](https://user-images.githubusercontent.com/1746396/27475650-4e80f3aa-5806-11e7-888c-02af716065e8.PNG)

Which one of those three is unexpected, and why?

**Comment by mpost** [comment]
@karolszafranski Please run he snippet and compare the image with he Android client. You will see that the image is to large starting with the 100x100 example.

**Comment by mpost** [comment]
You will need to use devices with a scale factor higher than 1x to see the difference.

**Comment by tbuschto** [comment]
It works correctly on windows.

**Comment by karolszafranski** [comment]
As discussed in person with @mpost, the issue was fixed since I posted my last comment.
