### ISSUE TITLE
Create tutorial for creating non-native UI components

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#1393]
We should document:
 - How to extend existing widgets using ES6/TypeScript classes.
 - How to keep type safety while doing so in TypeScript.
 - How to best use this with JSX (TSX)
 - The "protected" APIs that can be used create native custom widgets.
 - How to provide the native part of a custom widget.

**Comment by mpost** [comment]
We already have docu for android and ios plugin creation.

**Comment by tbuschto** [comment]
Renamed it from "Document how to create js/native custom widgets" to "Create tutorial for creating non-native UI components". The native part should be only linked from there.

**Comment by tbuschto** [comment]
This is still an open Issue. We have some TypeScript best practices, but still no proper Tutorial, nor are protected APIs documented (or even available in TypeScript). There was also some disagreement where such a Tutorial should be placed, on the website, on the blog, or in the documentation itself...

**Comment by cookieguru** [comment]
My vote it's for the documentation. It's the first place I go to look for documentation, and it has search that works reasonably well, meaning I can discover it without knowing that I'm looking for it.

**Comment by mpost** [comment]
Close as related to https://github.com/eclipsesource/tabris-js/issues/1611
