### ISSUE TITLE
Document how to use a debugger on each platform

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#1398]
All 3 platforms allow debugging JS in some manner, but it's different for each and not documented anywhere as far as I can tell. Bonus points for debugging TypeScript.

**Comment by irbull** [comment]
I have an [article for Tabris-Android](http://eclipsesource.com/blogs/2016/06/06/debugging-javascript-with-tabris-js/). I will convert this to proper docs.

**Comment by tbuschto** [comment]
I added a revised article to the docs.
