### ISSUE TITLE
Complete widget property checks in JavaScript

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#140]
All supported properties should be checked in JS.

**Comment by tbuschto** [comment]
Opacity are transform are checked by now, as are Animation and Canvas parameters (#390).
Picker/Collectionview items should be checked to be arrays.
WebView checks url to be a string, video should do the same.

**Comment by tbuschto** [comment]
Categorized as bug as incorrect values can lead to crashes (not errors)
