### ISSUE TITLE
Plugin - Clipboard

### ISSUE THREAD

**Issue by arjunmenon** [eclipsesource/tabris-js#1402]
This plugin isn't working - https://github.com/VersoSolutions/CordovaClipboard

Its default example
```
var text = "Hello World!";
cordova.plugins.clipboard.copy(text);

```
returns _Cannot read property 'copy' of undefined._
In the config I got - `<plugin name="cordova-universal-clipboard" spec="0.1.0"  />`
Attempting to read native clipboard and display whatever it is in the textView.

### Environment

- Tabris.js version: 2.0
- Device: Redmi 4A
- OS: Android 6

**Comment by cookieguru** [comment]
It's possible that the plugin failed to install; can you post your full build log somewhere and link it here?

**Comment by arjunmenon** [comment]
I am making an attempt to get to know Tabris JS. In the process I am using the Hello World example, by simply adding the plugin to the config.xml and directly using it as mentioned in the plugin usage.

So far certain plugins like the clipboard, [upnp](https://github.com/scottdermott/cordova-plugin-discovery) have failed with the same error, `serviceDiscovery undefined`, in this case.

However, some work, like [network daignostic](https://www.npmjs.com/package/cordova.plugins.diagnostic#installation), [network information](https://www.npmjs.com/package/cordova-plugin-network-information), through the same method of configuring the cordova plugin I have been doing.

**Comment by cookieguru** [comment]
Is this representative of what you've been doing so far?

1. Downloaded the Tabris.js developer app from one of the app stores
2. Used the `tabris` command-line client to initialize a project
3. Added plugins to `config.xml`
4. Reload the aforementioned app

If so, it's missing a couple of steps.  Cordova plugins add additional native code (Java/Objective C/etc) code which has to be compiled to binary format and installed on the device.  When you use the reload function in the developer app, the only thing it does is fetch the JavaScript again.  The **only** way to get the new code is to build a new binary.

The developer app in the app stores comes pre-packaged with [a few plug-ins](https://tabrisjs.com/tabris-js-docs/latest/cordova.html#default-plug-ins) which explains why some of them work.

To build your app, you can use either the [Tabris.js online build service](https://tabrisjs.com/tabris-js-docs/latest/build.html#BuildService) or build the apps [locally on your machine](https://tabrisjs.com/tabris-js-docs/latest/build.html#LocalBuild).  You only need to build a new binary when you modify the native code--you can still [enable the developer console in your built apps](https://tabrisjs.com/tabris-js-docs/latest/build.html#preferences) and use the reload button to load your JavaScript code.

---
If I'm off base and you're already building apps, please post the full build log.

**Comment by arjunmenon** [comment]
https://tabrisjs.com/tabris-js-docs/latest/build.html#integrating-cordova-plugins
This says all cordova plugins can be installed to work by merely adding a reference to it in the config.xml file.
Since the plugins I have mentioned dont modify the DOM, should it not match with the note, 

> Most of the Plugins will work out of the box

And by build log, what specific notes do you wish to see? I can't understand accurately what it refers to.

If it means the code, then sure I would post a link to it.

**Comment by cookieguru** [comment]
The docs should be revised--I see how you can make the inference that merely adding the line to `config.xml` would be enough to make it work.  However, for the reasons I stated above, that is not technically possible.

Most plugins work "out of the box" *once they are installed*.  A notable exception is [cordova-plugin-googlemaps](https://github.com/mapsplugin/cordova-plugin-googlemaps) since it depends on the DOM, however you can use [tabris-plugin-maps](https://github.com/eclipsesource/tabris-plugin-maps) instead.

Both the clipboard and upnp plugins ship with Java and Objective C code.  Neither one of these languages is interpreted at runtime.  The source code must be compiled in to the app by compiling it.  Without the compilation, you will not have access to the source code.  Building your app is the only way to add this source code to your Tabris.js project.  However, your JavaScript code **is** interpreted at runtime, so you do not need to build (compile) the app when making changes to your JS code; you only need to reload the source using the refresh button in the app.  When you are ready to release your app to production, you will turn off the developer console and the app will ship with the JS code that exists when you build the app.

---

Follow the instructions to use either the [Tabris.js online build service](https://tabrisjs.com/tabris-js-docs/latest/build.html#BuildService) or build the apps [locally on your machine](https://tabrisjs.com/tabris-js-docs/latest/build.html#LocalBuild).  For the cloud build, you can access the build log once the build is complete:

![screenshot](https://user-images.githubusercontent.com/1888809/27466991-77fb1648-5793-11e7-9574-8fd6e45768d4.png)

**Comment by arjunmenon** [comment]
This is the repo - https://github.com/arjunmenon/tabrisjs-test

I am waiting for a build to complete. But reading the docs it suggests it would output an `apk` file?
Little lost here, since this step was not so upfront to gather.
After this, what is the step to proceed testing and working. I have enabled the `debug` flag on.

**Comment by cookieguru** [comment]
Once the build completes, all you need to do is install the apk file on your device.

**Comment by arjunmenon** [comment]
Hey builds are failing
Please have a look - http://paste.ubuntu.com/24965462/

**Comment by arjunmenon** [comment]
I have tried it numerous times, but builds just fails.

**Comment by cpetrov** [comment]
It seems the build fails with:

```
npm ERR! Invalid version: "0.1"
```

May it be that you have a dependency with a version "0.1" in your package.json, which doesn't have a matching release on npmjs.com?

**Comment by cookieguru** [comment]
@cpetrov Actually that's not a dependency but the package's version itself.  According to [npm's docs](https://docs.npmjs.com/files/package.json#version), the "version must be parseable by [node-semver](https://github.com/npm/node-semver)".

**Comment by arjunmenon** [comment]
What is the corrective measure? To change version to `0.0.1` in `package.json`?
Can you have a look at the hello world repo I am building?

https://github.com/arjunmenon/tabrisjs-test
https://www.npmjs.com/package/cordova-universal-clipboard
https://www.npmjs.com/package/Service-Discovery-DLNA-SSDP

Few more words on cordova in the docs would add a lot as a guide.

**Comment by cookieguru** [comment]
@arjunmenon The version number can be any number of your choosing, but as per the docs I linked it must contain a major, minor, and patch numbers.

**Comment by arjunmenon** [comment]
Since the `package.json` was generated by `tabris' and is untouched, I am a five year old trying to learn the rules from you. :-||

Maybe you can link a repo which actually builds, which has a debug flag and ticks all requirements what the cloud build expects.

I can take it from there, perhaps.

**Comment by ralfstx** [comment]
@arjunmenon The version number in your `package.json` is indeed invalid. The CLI sets this version to `0.1.0` for new projects. Could you update your tabris CLI and create a new example project?

    npm update -g tabris-cli

    mkdir example
    cd example
    tabris init

I'm sure this project will build on tabrisjs.com.

**Comment by arjunmenon** [comment]
Good news! 
It works!
That was the definitive "Aha" moment there. :sweat_smile: 

Now back to the plugins.
https://github.com/arjunmenon/second_tabris/blob/master/cordova/config.xml

I have enabled the developer console `true` and the debug flag. However post installing, I can't make changes to the app. Reloading does nothing.

Making an attempt to change the `app.js` file would not reflect in the installed app and it won't work in the tabris app either.

How can I start adding and modifying scripts in the installed app itself?

Also, upnp still doesn't work. `serviceDiscovery is undefined` is the tune it still caries.

**Comment by ralfstx** [comment]
Glad to hear the build succeeded!

When you're reloading a packaged app, it will simply reload the code bundled with the app. But you can use the developer console to load from a server. to do so, serve the app from your project directory:

    tabris serve

and then enter the URL logged by the CLI into the developer console.

**Comment by ralfstx** [comment]
As for your cordova plugin, the build logs a warning indicating that it failed to include `cordova-plugin-discovery`:

> Failed to restore plugin "cordova-plugin-discovery" from config.xml. You might need to try adding it again. Error: Error: Unpublished by skyup-str on 2015-12-28T12:21:38.174Z

Due to a bug in cordova, the build succeeds despite this failure (#1148).

**Comment by cookieguru** [comment]
FYI @arjunmenon I opened https://github.com/generator-tabris-js/pull/34 to validate the version number when running `tabris init`.

**Comment by ralfstx** [comment]
It looks like this issue can be considered resolved. As mentioned before, the cordova plugin does not work, you may look for an alternative. Please re-open if you need further assistance on that.

**Comment by arjunmenon** [comment]
Hey
Sorry, couldn't catch up.
Since clipboard works just fine, I think I may have not configured the upnp plugin properly. Or it just wont work. Maybe add a node-dependency, I have seen many packages in npm.

I would put up an update on upnp by end of day, hopefully.
Really appreciate you helping figure things out. :)

@cookieguru That would certainly help. Thanks.

**Comment by arjunmenon** [comment]
Hey 
If I can pick your brain here.
In package.json I got `node-upnp-client`
```

"dependencies": {
    "tabris": "^2.0.0-rc2",
	"moment": "~2.8.4",
	"moment-timezone": "~0.2.5",
	"android-versions": "1.1.0", 
	"node-mind": "1.0.1",
	"node-ssdp": "3.2.1",
	"node-upnp-client" : "0.0.2",
	"node-ssdp-lite": "0.2.0"
  },
```
In app js I have initialized it as
```
const upnpClient = require('node-upnp-client');
const cli = new upnpClient();
console.log(cli.searchDevices());
```

I am getting
```
Could not load main module: 
Reference error: process is not defined
```
Now its pointing to this line first `var path = process.env.SSDP_COV ? './lib-cov/' : './lib/'`, in 
`node-ssdp/index.js`

I dont know why but it works perfectly in the CLI but not in the app.

Second, 
other ssdp clients routinely require `dgram`. But that throws an error saying it can't be found. Even though it is [part of Node](https://nodejs.org/api/dgram.html) 

---
Side note-
One of your [blog posts](https://eclipsesource.com/blogs/2015/01/23/working-with-modules-and-libraries-in-tabris-js/) mentions

> The npm database hosts JavaScript modules for various JavaScript runtime environments, so not everything there is compatible with Tabris.js. But anything that depends solely on EcmaScript API will definitely work, and modules for web applications may also work if they do not use HTML.

I am not sure if Upnp is a lost cause with Tabrisjs, but if you could clear up what I need to look to be sure what can work, apart from things related to DOM, I can diagnose better.

Need your help!

**Comment by cookieguru** [comment]
Like you mentioned, `process` is part of Node.  And as you quoted, Tabris.js is built of EcmaScript APIs.  Specifically, JavaScriptCore for iOS, [J2V8](https://github.com/eclipsesource/J2V8) on Android, and Chakra on Windows.

There is a shim for some Node functionality: [tabris-js-node](https://github.com/eclipsesource/tabris-js-node/), however only `process.nextTick` is implemented for `process` and nothing at all for `dgram`.

**Comment by arjunmenon** [comment]
I guess I would have to work with a cordova plugin on SSDP and then, call upon its APIs.
