### ISSUE TITLE
How to Reload files from server with JavaScript

### ISSUE THREAD

**Issue by dalisoft** [eclipsesource/tabris-js#1403]
Hi. I am developing the own build, i am almost done my work here.
I can reload manually by button, but for Hot-Reload (aka Live Preview/Reload) need reload automatic when code changes.
I am have all the script except the reload server files from mobile app.

Example,
* Have files with ip adress in 192.168.10x.yz.
* Reload server 192.168.10x.yz with js from mobile

**Comment by ralfstx** [comment]
Are you looking for hot code replacement? This is already covered by #1018.

**Comment by dalisoft** [comment]
No, no. I am want trigger reload button, change detection, server connection i done. How i can trigger dev-app "reload" button?

**Comment by ralfstx** [comment]
Then maybe you're looking for [`app.reload()`](https://tabrisjs.com/tabris-js-docs/latest/api/app.html#reload())?

**Comment by dalisoft** [comment]
It loads files from server? Then yes

**Comment by dalisoft** [comment]
What action is used in devapp console reload button? It is app.reload?

**Comment by ralfstx** [comment]
The developer console is a native implementation, but its reload action is equivalent to `app.reload()`. When you've loaded your app from a server, then it will reload it from this server. In a bundled app, it will reload the code that is packaged with the app.

**Comment by dalisoft** [comment]
Thanks. I almost ready to build amazing fork of tabrisjs.
