### ISSUE TITLE
Android build fails when keystore password contains special characters

### ISSUE THREAD

**Issue by cookieguru** [eclipsesource/tabris-js#1405]
### Problem description

When a keystore contains special characters, the online build fails with the following:
```plain
Built the following apk(s): 
	/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build/outputs/apk/android-release-unsigned.apk
Running "create-artifacts" task
Running "shell:sign_apk" (shell) task
jarsigner error: java.lang.RuntimeException: keystore load: Keystore was tampered with, or password was incorrect
Warning: Command failed: jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -J-Dhttps.protocols=TLSv1.2,TLSv1.1 -tsa http://sha256timestamp.ws.symantec.com/sha256/timestamp -keystore signing/android.keystore -storepass $TABRIS_ANDROID_STORE_PASSWORD -keypass $TABRIS_ANDROID_KEY_PASSWORD -signedjar build/platforms/android/build/outputs/apk/com.[secure].app-unaligned.apk build/platforms/android/build/outputs/apk/android-release-unsigned.apk $TABRIS_ANDROID_ALIAS
```

### Environment

- Tabris.js version: 1.x-nightly
- Java version: 1.8.0_131

### Repro steps
1. Follow [this guide](http://docs.phonegap.com/phonegap-build/signing/android/) to create a new keystore using the password ``!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~``
2. Upload the keystore with that file
3. Build fails

It is unlikely that *all* those characters cause the build to fail.  I have not tested every permutation to see exactly which character is causing issues but can confirm that using a keystore password with none of them results in a sucessful build.

**Comment by jonek** [comment]
Probably this is caused by how the password is propagated to the `jarsigner` command and how we escape certain characters. @fwaibel could you look into this?

**Comment by cookieguru** [comment]
Cloud build has been retired.  Closing
