### ISSUE TITLE
Negative offsets are ignored in layoutData on Android

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#1406]
Negative offsets in layout data are ignored, i.e. treated as zero.

Nexus 5x, Android 7.1.2

```javascript
new tabris.Composite({
  id: 'first',
  left: 20, top: 20, width: 100, height: 100,
  background: 'red'
}).appendTo(tabris.ui.contentView);

new tabris.Composite({
  left: ['#first', -50], top: ['#first', -50], width: 100, height: 100,
  background: 'green'
}).appendTo(tabris.ui.contentView);
```

**Comment by mpost** [comment]
The missing supported for negative margins in the android layout library is tracked at https://issuetracker.google.com/issues/37136609

**Comment by tbuschto** [comment]
If we can not fix this we should at least align the behavior of iOS and Android.

**Comment by mpost** [comment]
There is no foreseeable support for the negative margins on Android. To align the behavior we should prohibit the negativ margin on all platforms.

**Comment by mpost** [comment]
Didn't mean to close the issue.

**Comment by cpetrov** [comment]
Follow-up issue: #1727
