### ISSUE TITLE
Developer app: do not open auto-suggest when scanning QR code

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#1414]
In the developer app's URL tab, when scanning a URL from a bar code, the auto-suggest pops up and covers the *Connect* button. That makes it a bit complicated to continue from this point.

As the playground URLs are long and cryptic, there's no real use for the auto-suggest in this case. I'd even suggest to connect to the URL immediately after a successful scan.

**Comment by ifurnadjiev** [comment]
Fixed!
