### ISSUE TITLE
Public playground ignores changes

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#1415]
- Navigate to https://tabrisjs.com/playground
- Make some changes to the code
- Load in the developer app using QR code scan

The developer app loads the default script, not the current version from the playground.

**Comment by dalisoft** [comment]
@ralfstx There bug should be in QR code, not Tabris-js related

**Comment by jonek** [comment]
This is what the JS console in Chrome tells me if I change the content of the editor on the playground page: 

```
Request URL:https://tabrisjs.com/api/v1/playground/5954c96fb375b0e4355d60a9/app.js
Request Method:POST
Status Code:404 Not Found
```

**Comment by jonek** [comment]
I am looking into it.

**Comment by ralfstx** [comment]
Works again with today's version.
