### ISSUE TITLE
Selection on TabFolder is wrong when setting programmatically

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1422]
### Problem description

Creating a `TabFolder` with `paging` enabled and setting the `selection` to another tab programmatically shows the new tab as expected. In the fired `selectionChanged` event the new tab is given as the event value. However when getting the current `selection` from the `TabFolder` in the `selectionChanged` event it still returns the previous tab.

### Expected behavior

Inside the `selectionChanged` event the `TabFolder.selection` should be up to date to reflect the new selected tab.

When disabling `paging` the `selection` is updated as expected.

### Environment

- Tabris.js version: `nightly`
- Device: iPhone SE
- OS: iOS 10.3.2

### Code snippet

```javascript
const {Tab, TabFolder, TextView, ui} = require('tabris');

let tabFolder = new TabFolder({
  left: 0, top: 0, right: 0, bottom: 0,
  paging: true
}).on('selectionChanged', ({value: tab}) => {
  console.log(`selectionChanged tab: ${tab.title}`);
  console.log(`tabFolder tab: ${tabFolder.selection.title}`);
}).appendTo(ui.contentView);

createTab('One');
let tab2 = createTab('Two');

function createTab(title) {
  let tab = new Tab({
    title: title,
  }).appendTo(tabFolder);
  new TextView({
    centerX: 0, centerY: 0,
    text: 'Content of Tab ' + title
  }).appendTo(tab);
  return tab;
}

setTimeout(() => tabFolder.selection = tab2, 1000);
```

**Comment by patrykmol** [comment]
Fixed in https://github.com/eclipsesource/tabris-ios/commit/c66e2d0d8425df76ed0ffde5c4d9d4ff4179c5b5
