### ISSUE TITLE
collectionView wrong behavior

### ISSUE THREAD

**Issue by jonaspm** [eclipsesource/tabris-js#1423]
### Problem description

When removing then adding items with the swipe-to-dismiss example, collectionView gets crazy.
![example](https://user-images.githubusercontent.com/7599554/28060628-f160eb52-65e4-11e7-955a-a870fbab0297.gif)

### Expected behavior

Remove item by swiping -> Item removed from the list.
Add new item by tapping any visible item -> New item created & loaded into the list.

### Environment

- Tabris.js version: 2.0.0-rc2
- Device: Lenovo k33b36
- OS: Android 6.0.1

### Code snippet

```javascript
let container = new Composite({
  id: 'container',
  left: 0, top: 0, bottom: 0, right: 0,
  background: 'white',
  highlightOnTouch: true
}).on('panHorizontal', event => handlePan(event))
.on('tap', () => {
  ITEMS.push({title: 'Fraud mail', sender: 'Unsuspicious Jack', time: 'yesterday'});
  collectionView.load(ITEMS.length);
  //collectionView.insert(ITEMS.length); // SAME BEHAVIOR
})
  .appendTo(cell);
```
Full project here: 
[tabrisjs-enhanced-swipe-to-dismiss.zip](https://github.com/eclipsesource/tabris-js/files/1138294/tabrisjs-enhanced-swipe-to-dismiss.zip)

**Comment by ralfstx** [comment]
That's because the CollectionView recycles cells. When you re-load the model, it re-uses cells that have been dismissed before, these cells still show the gray background. You should reset the container's translation in the `updateCell` function:

```js
view.find('#container').set('transform', {translationX: 0});
```

We should add this line to the swipe-to-dismiss example.

**Comment by jonaspm** [comment]
Thank you, it works now! Btw, Why is the 'select' event not working on appended widgets?

**Comment by ralfstx** [comment]
> Btw, Why is the 'select' event not working on appended widgets?
Which appended widgets do you refer to?

**Comment by jonaspm** [comment]
as you can see in the code snippet, #container (Composite) is appended to #cell (Composite).

cell is the main list item, but select event is not fired when #container is selected / tapped.

**Comment by cpetrov** [comment]
The interaction with the cell is consumed by the `"tap"` listener of the container composite, thus no `"select"` event will be fired by the collection view widget. If you don't register the `"tap"` listener on the container composite, `"select"` should fire on the collection view when tapping on the container.
