### ISSUE TITLE
Is possible to create Android/iOS native widget?

### ISSUE THREAD

**Issue by dalisoft** [eclipsesource/tabris-js#1428]
Is possible build iOS and Android widgets with Tabris.js like acejs?

**Comment by mpost** [comment]
You can create native widgets with tabris.js as well. Foe example. https://github.com/eclipsesource/tabris-plugin-maps

Please have a look at https://tabrisjs.com/tabris-js-docs/latest/widget-basics.html for the JS part or https://tabrisjs.com/tabris-js-docs/latest/custom-widgets.html (and left hand bar for native part)

**Comment by dalisoft** [comment]
Thanks

**Comment by dalisoft** [comment]
@mpost I no see the real widgets there. Widgets is in application shown in example

**Comment by dalisoft** [comment]
Real widget - native OS widgets such Weather or other like this

**Comment by mpost** [comment]
You mean like home screen widget? That could also be done as a plugin but needs some more integration of course.

**Comment by dalisoft** [comment]
Yep. Thats  what i need. Some guides will be nice

**Comment by dalisoft** [comment]
iOS and Android integration is need for me. I cant move to other project due of i made own structucal framework tez native with one of fastest and better

**Comment by mpost** [comment]
We haven't experimented with home screen widgets and Tabris.js yet so we can't really comment. Insights are appreciated.

**Comment by dalisoft** [comment]
Ace.js (where i find the Tabris.js) with cordova plugin can be ported to tabris.js

**Comment by cookieguru** [comment]
Normally this is a case where the Cordova ecosystem would prove useful.  However, Cordova is built around WebViews, and the native platforms don't support placing a WebView in a homescreen widget, so there is no plugin.

In this case, I belive @mpost's comment still stands: You'll have to write native code and can then expose that as a JS object.

**Comment by dalisoft** [comment]
Thanks. I will looking at acejs for widget now

**Comment by truthSeekr** [comment]
@dalisoft Did u manage to make work acejs with tabris ?

**Comment by dalisoft** [comment]
No, i now build cordova webview apps, still looking the way to build widget

**Comment by truthSeekr** [comment]
so with webview you could use ace to communicate between java and javascript. I imagine you want to have full javascript widget embeded as java widget. What was the problem ?

**Comment by dalisoft** [comment]
No, i not used acejs as widget app as docs not complete and easy tabrisjs. I just not build apps with widget as i dont know java. I know only JS.
