### ISSUE TITLE
Make theming files

### ISSUE THREAD

**Issue by dalisoft** [eclipsesource/tabris-js#1429]
Like the NativeScript or ReactNative has theme file or UI library.
Is there has any reference to full styling list like CSS. I want much of things with list. Making theming file allow users choose Tabris.js over Hybrid HTML5 apps

**Comment by dalisoft** [comment]
Like styles={
Color: color
textAlignment: textAlign
}
or styles=[ color, width, textAlignment, ...]

**Comment by cookieguru** [comment]
Check out this document on [the Apply method](https://tabrisjs.com/tabris-js-docs/latest/selector.html#the-apply-method).  You can then create a [stylesheet-like object](https://github.com/eclipsesource/tabris-con/blob/master/src/resources/platformStyles.js) and apply properties to widget children.

**Comment by dalisoft** [comment]
Thanks
