### ISSUE TITLE
ScrollView does not return to top scroll position

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1430]
### Problem description

When overscrolling a `ScrollView` once and letting it settle back into its initial position, the content is not in the same place as it was before. Instead the content is positioned a few pixel to far down.

Can be observed in the parallax example by starting the example and just overscrolling to the top once. As can be seen, there is a small gap between the image an the status bar.

![image uploaded from ios 7](https://user-images.githubusercontent.com/73655/28206350-d05440fa-6885-11e7-9998-96fb1d7d6393.jpg)

### Expected behavior

The `ScrollView` should settle in the same position as before the overscroll.

### Environment

- Tabris.js version: 2.0.0
- Device: iPhone SE
- OS: 10.3.2

### Code snippet

https://github.com/eclipsesource/tabris-js/tree/master/examples/parallax

**Comment by patrykmol** [comment]
ScrollView ends animating at (0,-0.5) offset but produces last callback with (0,0) offset. Incorrect offset becomes apparent when using Interface Inspector (when setting breakpoints offset value is correct (0,0)). This requires further investigation.

**Comment by karolszafranski** [comment]
https://developer.apple.com/documentation/uikit/uiscrollviewdelegate/1619385-scrollviewwillenddragging
