### ISSUE TITLE
Autocompleting jsx widget in WebStorm inserts element with all attributes spelled out

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1431]
### Problem description

Starting to type `comp...` and  autocompleting the widget in a jsx file in WebStorm inserts the composite element but with all attributes spelled out:

```js
ui.contentView.append(
  <composite background="" backgroundImage="" baseline="" bottom="" centerX="" centerY="" class="" classList="" cornerRadius="" elevation="" enabled="" font="" height="" highlightOnTouch="" id="" layoutData="" left="" opacity="" right="" top="" transform="" visible="" width="" win_theme=""></composite>
);
```
All the attributes seam to be "required" as even when not added WebStorm shows a warning that the attributes are missing.

### Expected behavior

Only insert the `<composite>` tag.

### Environment

- Tabris.js version: 2.0.0

**Comment by mpost** [comment]
The reason why WebStorm requires those properties is because they are not marked ass being optional as stated here: https://www.typescriptlang.org/docs/handbook/interfaces.html (Optional Properties).

Adding the optional (`?`) marker on the properties satisfies the WebStorm checker to require the argument in jsx.

**Comment by tbuschto** [comment]
They are optional: 
![grafik](https://user-images.githubusercontent.com/527303/28215007-c7d0a2da-68ac-11e7-9c08-db49dfd3f3a3.png)

**Comment by mpost** [comment]
Maybe those get lost in somewhere along the way? Looking at the tabris.d.ts file after installing tabris does not contain the question marks anymore.

```ts
interface _ActionProperties extends _WidgetProperties {

  /**
   * Icon image for the action.
   */
  image: Image;

  /**
   * Actions with higher placement priority will be placed at a more significant position in the UI, e.g.
   * low priority actions could go into a menu instead of being included in a toolbar.
   */
  placementPriority: "high" | "low" | "normal";

...
```

**Comment by mpost** [comment]
Yeah that could be. I'll open a bug on WebStorm.
