### ISSUE TITLE
Graphics are not drawn in Canvas

### ISSUE THREAD

**Issue by elshadsm** [eclipsesource/tabris-js#1433]
### Problem description

Basic draw operations do not work in Canvas. Even the example that is taken from Canvas documentation does not work.

### Expected behavior

Graphics must be drawn as expected.

### Environment

- Tabris.js version: 2.0.0-dev.20170718
- Device: iPhone 6
- OS: iOS 10.3.2

### Code snippet

```javascript
import {Canvas, ui} from 'tabris';

new Canvas({
  left: 10, top: 10, right: 10, bottom: 10
}).on('resize', ({target: canvas, width, height}) => {
  let ctx = canvas.getContext('2d', width , height);
  ctx.strokeStyle = 'rgb(78, 154, 217)';
  ctx.lineWidth = 10;
  ctx.moveTo(20, 20);
  ctx.lineTo(width - 40, height - 40);
  ctx.stroke();
}).appendTo(ui.contentView);
```

**Comment by mpost** [comment]
Does the canvas example show you any drawings?

**Comment by elshadsm** [comment]
When I run the snippet, the line is drawn in Android but not in iOS.

**Comment by cpetrov** [comment]
@elshadsm For me a line is drawn with Tabris.js `2.0.0`. Do you see any errors in the console?

However, API usage seems to currently diverge between Android and iOS. To produce same results as on Android, on iOS the canvas context should be scaled using the `device.scaleFactor` like in the updated [`canvas.js`](https://github.com/eclipsesource/tabris-js/blob/ffe4a24/snippets/canvas.js#L10) snippet.

**Comment by cpetrov** [comment]
I've tested using an outdated Android client. The context should be scaled properly on all platforms. Please reopen if you still have issues.
