### ISSUE TITLE
Allow excluding "internal" widgets from selector API 

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#1437]
When creating your own widget component, be it via inheritance or factory, you may want to avoid having the children of that component being picked up by the `appy` or `find` methods called on one of it's parents. To illustrate:

```js
MyCustomWidget extends Composite {

  constructor(props) {
    super(props);
    this.append(new Button({id: 'foo'});
    this.append(new TextInput({class: 'bar'});
  }

}
```

```js
ui.contentView.append(new MyCustomWidget({id: 'foo', class: 'bar'}));
ui.find('#foo').set({background: 'blue'}); // I actually only want MyCustomWidget to be blue
ui.apply({'.bar': {width: 100}}); // And I really only wanted to set the width of MyCustomWidget
```

**Comment by tbuschto** [comment]
My suggestion would be to simply offer a widget that is identical to `Composite` except for this feature. It could be called `UserSomthing` or `CustomSomething`, with "Something" possible being "Control", "Widget", "View", etc...

**Comment by cpetrov** [comment]
`children()` should be overwritten in custom widgets to prevent that. The [`_children()`](https://tabrisjs.com/documentation/latest/api/Widget.html#_childrenselector) method was introduced to provide the original `children()` behavior. It can be used in subclasses when needed.
