### ISSUE TITLE
Allow launching apps by URL

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#1438]
Mobile platforms allow opening other apps by specific URLs, e.g. `http://` URLs would open the browser, `mailto:` URLs an email app, `tel:` the dialer, etc. Apps can also register for custom URL schemes.

For example, the corresponding iOS would be [UIApplication](https://developer.apple.com/documentation/uikit/uiapplication/1648685-open).

This could be made available by a method on the `app` object, e.g. `app.open(url)` or `app.lauch(url)`.

**Comment by patrykmol** [comment]
This is an easy to implement feature. Do we have a proposed API for this feature?

**Comment by ralfstx** [comment]
`app.launch(url)` this is now available on all platforms.
