### ISSUE TITLE
Documentation about using platforms in local builds outdated

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js#1442]
The documentation of local builds states that the platform needs to be downloaded from the download page at https://tabrisjs.com in section "Downloading Tabris.js platforms" of this document: https://tabrisjs.com/documentation/latest/build.html#downloading-tabrisjs-platforms

This task is now handled by the tabis-cli. The section should be replaced by a section explaining how to use the tabris build key. (including a screenshot where to find the build key)

**Comment by jonek** [comment]
The new section about the tabris build key should give a hint that old platforms (for 1.x builds) can still be downloaded from the archive here: https://tabrisjs.com/download/archive

**Comment by patrykmol** [comment]
Reopening due to me typing wrong issue number in commit message.
