### ISSUE TITLE
Setting pageAnimation property of NavigationView causes unexpected results

### ISSUE THREAD

**Issue by elshadsm** [eclipsesource/tabris-js#1443]
### Problem description

Imagine that we have multiple pages that were appended to a NavigationView. Then, the pages need to be disposed except one. Before the start of disposing pages, we want to disable page animation. When we disable page animation, the result is empty content that is not expected.

![screenshot_20170721-163037](https://user-images.githubusercontent.com/13982125/28464365-dcb9387c-6e35-11e7-9f97-60ab4e60f750.png)

### Expected behavior

Enabling and disabling of page animation must not affect to the result of page dispose operation. 

### Environment

- Tabris.js version: 2.0.0-dev.20170718
- Device: Nexus 6P
- OS: Android 7.1.2

### Code snippet

```javascript
const {Button, NavigationView, Page, ui} = require('tabris');
let navigationView = new NavigationView({
  left: 0, top: 0, right: 0, bottom: 0
}).appendTo(ui.contentView);
new Page({
  id: 'initial',
  title: 'Initial Page',
  background: 'red'
}).appendTo(navigationView);
let page = new Page({
  title: 'Second Page'
}).appendTo(navigationView);
new Button({
  left: 16, top: 'prev() 16', right: 16,
  text: 'Go to initial page'
}).on('select', () => {
  navigationView.pageAnimation = 'none';
  navigationView.pages().filter(page => page.id !== 'initial').dispose();
  navigationView.pageAnimation = 'default';
}).appendTo(page);
```

**Comment by ralfstx** [comment]
A better way of removing all but the initial page, you should do this in two steps:

- first dispose all pages uinderneath, i.e. those that are not the *initial* page and not the current page - this won't result in an animation since the current page remains on top.
- then dispose the current page - this will show a single animation as expected.

```js
  navigationView.pages().filter(page => page.id !== 'initial' && page !== currentPage).dispose();
  currentPage.dispose();
```
