### ISSUE TITLE
local build failure

### ISSUE THREAD

**Issue by tstr007** [eclipsesource/tabris-js#1447]
Hi! 
I'm struggling with local build .
Followed instructions as in here:
https://tabrisjs.com/documentation/1.10/local-build.html

got the error in this screenshot:
![screenshot](https://user-images.githubusercontent.com/28858096/28757394-71bbc6f8-7582-11e7-93fb-e0e139cf1e5d.PNG)
any suggestions or clear tutorial on how to use local build?

**Comment by mpost** [comment]
This might be due to the fact that you are looking at the 1.10 docu but have downloaded a 2.0 platform. You should make sure to build with the tabris-cli and 2.x (https://tabrisjs.com/documentation/latest/build.html#local-build).

**Comment by tstr007** [comment]
Thanks for quick response . 
I've already tried the instructions in the link you provided and it gave me an error , so I searched the web and found instructions for v1.
Here is the error message I got when I followed instructions for tabris-cli and 2.x
![screenshot](https://user-images.githubusercontent.com/28858096/28769911-9b6e02d0-75dd-11e7-819d-8774aca5440a.PNG)
btw , I tried remote build and it did work fine for some apps . but I think that the size of apk file (14+ MB) is very large for an app even before adding plugins ,etc. Any suggestions to reduce it?

**Comment by mpost** [comment]
The tabris-cli is also able to download the correct platform for you. If you do not have an env var pointing to `TABRIS_ANDROID_PLATFORM` it will download a platform for you.

**Comment by cookieguru** [comment]
> I think that the size of apk file (14+ MB) is very large for an app even before adding plugins ,etc. Any suggestions to reduce it?
The apk ships with both arm and x86 binaries (see #888).  With a local build, you can specify platform options to build a separate apk for each architecture.

**Comment by tstr007** [comment]
@mpost I have manually downloaded tabris-android-2.0.0 and extracted it, then assigned it's path to TABRIS_ANDROID_PLATFORM variable environment that resulted in the error shown above.
After your post I removed environment variable and tabris-android-2.0.0 and hit tabris build android.
If searched for it in the same directory (see here) 
![screenshot](https://user-images.githubusercontent.com/28858096/28811493-cb75a2a0-768f-11e7-8d93-149295712a4b.PNG)
Is there a special command for tabris-cli to download the correct platform as you said?

@cookieguru Thank you . This is what I'm looking for. I'll try it when I'm finished with this local build issue.

**Comment by cpetrov** [comment]
@tstr007 in order for Tabris CLI to download the Android platform, the `TABRIS_ANDROID_PLATFORM` environment variable has to be unset.

**Comment by tstr007** [comment]
@cpetrov  Thanks! I checked it and ran tabris build android which downloaded android platform ,unzipped it  and started to build the app however it failed with this error 
![screenshot](https://user-images.githubusercontent.com/28858096/28814002-00b76d3e-769c-11e7-9efd-bf7df8fd3e0d.PNG)
btw I used to build apks with cordova and it worked fine.

**Comment by mpost** [comment]
At the bottom of your screenshot shows that an env var `_JAVA_OPTIONS` that sets the max memory to 512M. You should change that to 2048M.

**Comment by tstr007** [comment]
@mpost @cookieguru @cpetrov Thank you! Issue resolved!
