### ISSUE TITLE
CollectionView.load() does not reload content when itemCount not set

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1451]
### Problem description

Creating a `CollectionView` without setting the `itemCount` is a common scenario. Later on you would call `.load(itemCount)` but on iOS the list is not refreshed. Only when setting the `itemCount` manually without calling load() is the content shown.

### Expected behavior

`.load()` should be enough to replace the coll view content with the number of items.

### Environment

- Tabris.js version: 2.0.0
- Device: iPad Pro 9.5" 
- OS: 10.3.2

**Comment by karolszafranski** [comment]
It's not possible to reproduce the issue with the following snippet: https://gist.github.com/karolszafranski/3b859038f8d3f9d92824dc0b1aabe417 however after discussing in person we were able to see the issue in the app where it was discovered.
