### ISSUE TITLE
Improve console implementation

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#1459]
The `console` methods `debug()`, `log()`, `info()`, `warn()`, and `error()` do not format values consistently across platforms, as every platform implements their own formatting logic. The methods also don't support printf-like format strings, as they do [in browsers](https://developer.mozilla.org/en-US/docs/Web/API/Console/log) and [in Node.js](https://nodejs.org/dist/latest/docs/api/console.html#console_console_log_data_args).

We should implement the console in JavaScript so that all platforms share the same code.

**Comment by cookieguru** [comment]
Related: #971

**Comment by ralfstx** [comment]
The console implementation in JS (ff84154) guarantees consistent formatting across platforms.
