### ISSUE TITLE
UI Toolset for tabris

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#1460]
This is a pretty broad request, but tabris would greatly benefit from a sophisticated UI library like https://docs.nativebase.io/Components.html. Having a toolset that eases general development is obviously valuable.

**Comment by mpost** [comment]
Thanks for the feedback. Tabris offers a similar list of `Widgets`. Please check the left sidebar here: https://tabrisjs.com/documentation/latest/

There are some ui components that are not yet available in Tabris.js but the library keeps on growing steadily.

**Comment by mpost** [comment]
Are there any particular features you would like to see in Tabris.js?

**Comment by mpost** [comment]
Closing as "stale".
