### ISSUE TITLE
Cordova plug-ins not initialized, deviceready not fired

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#1461]
With the `boot.js` created as of 8d0d1341088088158e32455da7859abf4469aabb, a larger app with many cordova plugins runs into errors like this one:

```
Could not load main module: TypeError: Cannot read property 'isAvailable' of undefined
TypeError: Cannot read property 'isAvailable' of undefined
    at ./dist/main.js:2:455082
    at Module.get (<anonymous>:32:902)
    at Module.require (<anonymous>:32:1202)
    at d (<anonymous>:32:3570)
    at Object.tabris._start (<anonymous>:32:3764)
deviceready has not fired after 5 seconds.
Channel not fired: onNativeReady
Channel not fired: onCordovaReady
```

`isAvailable` is obviously part of an API normally provided by a Cordova plugin.

### Environment

This has been reported for Android, but it does not happen on 2.0.0, since the Android platform accidentally did not pick up the 2.0.0 `boot.js`.

Not sure about iOS.

**Comment by mpost** [comment]
Closing as resolved. Please reopen if still an issue.
