### ISSUE TITLE
Error when trying to access pages from drawer

### ISSUE THREAD

**Issue by tstr007** [eclipsesource/tabris-js#1463]
I have this code to access pages from drawer:
```js
const page1 = require('./page1');
const page2 = require('./page2');
const page3= require('./page3');

[page1, page2, page3].forEach((page) => {
  new Button({
    left: 10, top: 'prev() 10', right: 10,
    text: page.title
  }).on('select', () => page.appendTo(NavigationView))
    .appendTo(tabris.ui.drawer);
});
```

when running it gives this error . 
Error: Cannot append to non-widget.

What do i miss here?

Thanks in advance!

**Comment by cookieguru** [comment]
A [`NavigationView`](https://tabrisjs.com/documentation/latest/api/NavigationView.html) is a stack of pages.  Pages cannot be displayed inside a drawer.  You instead want to append your NavigationView to [tabris.ui.contentView](https://tabrisjs.com/documentation/latest/api/ui.html#contentview).

The [bookstore example](https://github.com/eclipsesource/tabris-js/tree/master/examples/bookstore) shows the `Drawer` and `NavigationView` in use, and there are several related [snippets](https://github.com/eclipsesource/tabris-js/tree/master/snippets) as well.

**Comment by ralfstx** [comment]
@tstr007 You have to add the pages to an *instance* of `NavigationView`, not to the constructor.
Please consider StackOverflow for this kind of questions.
