### ISSUE TITLE
npm mondules names containing a dot cannot be parsed

### ISSUE THREAD

**Issue by maoamid** [eclipsesource/tabris-js#1472]
### Problem description

npm install --save opentype.js
`require ('opentype.js')` generate a parse error

alternative solution: rename npm module folder inside node_modules or fork it with other name
If an npm module name should not contain a dot in his name, a specification must appear somewhere in docs

### Environment

- Tabris.js version: 2.1.0-dev.20170818

### Code snippet

```javascript
let opentype = require ('opentype.js')
```

**Comment by cpetrov** [comment]
This is actually related to the Tabris.js CLI. The client tries to parse `.../node_modules/opentype.js`, (which is served as a HTML directory listing by the CLI) as JavaScript and fails. This issue does not happen in built clients.

As a temporary workaround you could `require('opentype.js/')` (i.e. with a trailing slash) to enforce resolving the module as a directory.

**Comment by cpetrov** [comment]
The issue has been fixed in the Tabris.js CLI and will be available in the next Tabris.js CLI release.

**Comment by maoamid** [comment]
great work. Thank you @cpetrov
