### ISSUE TITLE
Support developer console URL suggestions from history

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1475]
### Problem description
On iOS and Windows URLs don't get auto-suggested. It is useful to connect to an URL one has connected previously to without having to input it once again.

### Expected behavior
URL input should show suggestions from input history.

On Windows, they could be shown in a dropdown below the URL input field.
On iOS, an arrow icon pointing down can be added right to the blue URL. Upon click, a modal UI similar to the search action UI could open (instead of the input dialog which opens currently), containing an input field and suggestions below it.

**Comment by mpost** [comment]
implemented on ios in 3.4
