### ISSUE TITLE
Improve command prompt in developer console

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1477]
### Problem description
On Android, the label of the code execution field is _Evaluate script..._, on iOS it is _Code_. This can be confusing for the user.
### Expected behaviour
Both labels should be aligned.

**Comment by mpost** [comment]
Do you have any suggestions to phrase the label?

**Comment by cpetrov** [comment]
* As discussed, it would be advantageous to move the code execution field to the bottom on iOS, use field style (full width, no rounded corners, with padding, e.g. https://developer.apple.com/ios/human-interface-guidelines/images/text_field_2x.png) and separate it from the console output with a thin grey separator (similar to Android). Together with #1476, this would free up the busy area with many touchable widgets on the top (often reason for false touches).

* One possibility would be to remove the label altogether and show a blue arrow like most browsers do (e.g. Firefox):
    <img width="222" alt="screen shot 2017-08-22 at 12 32 41" src="https://user-images.githubusercontent.com/2341769/29561597-54ff0924-8736-11e7-9830-4e44bffc66e1.png">
    However, in a platform like Tabris.js, the affordance of such a layout may not be good enough.

* Label suggestions: *Command...*/*Script...*/*Code...*

**Comment by mpost** [comment]
After some discussion we agreed on using the term "_Command..._".

**Comment by cpetrov** [comment]
Implemented on Android as follows:

![screenshot_1503474500](https://user-images.githubusercontent.com/2341769/29604567-38690f6e-87e8-11e7-80d6-e47185f564d7.png)

**Comment by ralfstx** [comment]
On Windows, it's just an empty input field without a message or an icon. I'd suggest to show at least the command prompt icon (`>`) on all platforms.

As for the message, the term "Command" can be misleading, as you would enter JavaScript expressions, not commands. I wonder if the message is needed at all. Granted, it may not be obvious that you can enter something there, but if you *look for* the command prompt, the `>` icon should be sufficient.

**Comment by patrykmol** [comment]
iOS is now aligned with Android.

**Comment by mpost** [comment]
Closing as resolved.
