### ISSUE TITLE
Support code execution in the developer console

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1478]
### Problem description
Sometimes it is useful to execute short code in the developer console directly on the mobile device. This feature is already supported on Android and iOS.

### Expected behavior
Code execution in the developer console should be also supported on Windows as well (in case it is possible at all).

**Comment by mpost** [comment]
Code execution is already supported on Windows as well.

![image](https://user-images.githubusercontent.com/73655/29560271-c7aa94a2-8731-11e7-9732-30c44fb10a07.png)

**Comment by cpetrov** [comment]
It seems the field is not visible on mobile. Since the most common use case is inputting code on desktop, we decided to close this issue.
