### ISSUE TITLE
Use canvas as image data src

### ISSUE THREAD

**Issue by maoamid** [eclipsesource/tabris-js#1484]
Canvas widget can support `.toDataURL()`?
Is there a solution to use a canvas draw like an .png image for example?

**Comment by ralfstx** [comment]
You should be able to get the raw pixel data using `getImageData()` and save that data to a binary file using the `fs` API. However, that's uncompressed data, you'd have to use a third-party library to transform it to PNG.

I'm not sure if Tabris should provide basic support for graphic file formats. It would certainly be good to have that, but given the many parameters and versions of those formats, it seems out of scope.

**Comment by maoamid** [comment]
@ralfstx thank you for the idea. I also think that supporting multiple graphic formats is a bit to  much, there are a lot of libraries who can do that. What I trying to achieve is to transform a canvas to a base64 image, now that imageView suport it on source.

**Comment by mpost** [comment]
You should not use base64 encoded images. Rather use ArrayBuffers.
