### ISSUE TITLE
CollectionView with auto cellHeight creates too many cells

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#1486]
### Problem description

When a CollectionView is created with the `cellHeight` property set to `'auto'` (the default), a huge number of cells is being created. Apparently, the number of cells vaguely matches the view height, so I assume that a height of 1 dip is assumed before actually layouting cell content.

### Expected behavior

The CollectionView should only create as many cells as fit on the screen (plus a small buffer).

### Environment

- Tabris.js version: 2.1.0
- Device: XCode Simulator
- OS: iOS 10.3

### Code snippet

```javascript
const {CollectionView, TextView, ui} = require('tabris');

let items = [];
for (let i = 0; i < 1000; i++) {
  items.push('bla '.repeat(i + 1));
}

new CollectionView({
  left: 0, top: 0, right: 0, bottom: 0,
  itemCount: items.length,
  createCell,
  updateCell
}).appendTo(ui.contentView);

function createCell() {
  console.log('create cell');
  return new TextView({
    left: 16, top: 16, right: 16
  });
}

function updateCell(cell, index) {
  console.log('update cell', index);
  cell.set('text', items[index]);
}
```

**Comment by karolszafranski** [comment]
Default estimated cell height was changed to 44.0pt in https://github.com/eclipsesource/tabris-ios/commit/47114564a9047ba6e8fdf8d8e244745616e02648

We might observe changes in collection view cell animations (insert/delete).
