### ISSUE TITLE
In some cases, images are unexpectedly laid out in physical pixels

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1488]
### Problem description

Since 2.1, images are laid out in physical pixels instead of device independent pixels when:

  * the `scaleMode` of the ImageView is set to _auto_ and:
    * the size of the ImageView is bigger than the size of the picture in DIPs
    ... or ...
    * the ImageView does not have explicit size

    ... or ... 
  * the `scaleMode` of the ImageView is set to _none_

### Expected behavior

With the current behavior on Tabris.js, pictures should always be laid out in device independent pixels for those cases. This ensures consistent layout among devices with the same size but with different pixel densities. In case downscaling is needed to prevent pixelized images, the `scale` property of the [`Image`](https://tabrisjs.com/documentation/latest/types.html#image) should be explicitly set.

### Environment

- Tabris.js version: 2.1
- Device: iPhone 5s (scale factor 2), Samsung J3 (scale factor 2)
- OS: iOS 10, Android 5.1.1

### Code snippet

See the [imageview-as-a-button.js](https://github.com/eclipsesource/tabris-js/blob/master/snippets/imageview-as-a-button.js) snippet.

| iPhone 5s (scale factor 2) | Samsung J3 (scale factor 2) |
| --- | --- |
|![img_0056](https://user-images.githubusercontent.com/2341769/30370390-ba5ebb28-9877-11e7-80a0-28035339a273.PNG)|![screenshot_2017-09-13-11-04-07](https://user-images.githubusercontent.com/2341769/30370399-bebbfdf2-9877-11e7-86fe-da9d323e3904.png)|

**Comment by karolszafranski** [comment]
The iOS client currently is using physical pixels for displaying images, that was introduced lately and requested in this issue: https://github.com/eclipsesource/tabris-js/issues/1392 where as an example file system snippet was used. However, the change affects all `ImageView`s - not only images loaded from `fs`, but literally every `ImageView`.

I created a snippet with two `ImageView`s displaying images from different sources.

When we run this snippet on two platforms, we see consistent behaviour for images loaded with `fs`. That is: size of the image view is equal to image size divided by pixel to point ratio. 

While for assets iOS keeps that rule, Android is using 1:1 ratio.

| iPhone 7+ (scale factor 3) | Nexus 5X (scale factor 2,625) |
| --- | --- |
| <img width="498" alt="screen shot 2017-09-13 at 13 32 19" src="https://user-images.githubusercontent.com/1746396/30375241-225d2916-9888-11e7-9578-b0f901fbea5d.png"> | <img width="523" alt="screen shot 2017-09-13 at 13 32 21" src="https://user-images.githubusercontent.com/1746396/30375251-2c242508-9888-11e7-801a-8c1009e9ad99.png"> |

**Comment by karolszafranski** [comment]
fixed https://github.com/eclipsesource/tabris-ios/commit/1a7086c5f4df0792475f0d3825fa6a7d31a2497a
