### ISSUE TITLE
Images loaded from absolute paths are sometimes laid out in physical pixels

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1489]
### Problem description

ImageViews receiving image paths pointing to a file given with an absolute path, render their images in physical instead of device independent pixels when:

  * the `scaleMode` of the ImageView is set to _auto_ and:
    * the size of the ImageView is bigger than the size of the picture in DIPs
    ... or ...
    * the ImageView does not have explicit size

    ... or ... 
  * the `scaleMode` of the ImageView is set to _none_

### Expected behavior

ImageViews should always render their images in device independent pixels for those cases.

### Related issues

* Contradicts with: #1392 
* Related: #1488

### Environment

- Tabris.js version: 2.2.0-20170911
- Device: Samsung J3
- OS: Android 5.1.1

### Code snippet

```javascript
let imageView1 = new tabris.ImageView({ // rendered in physical pixels although DIPs are expected
  left: 10, top: 10, width: 200, height: 200,
  background: '#aaaaaa',
  image: tabris.app.getResourceLocation('images/pig.png')
}).appendTo(tabris.ui.contentView);

new tabris.ImageView({ // rendered in DIPs as expected
  left: 10, top: [imageView1, 50], width: 200, height: 200,
  background: '#aaaaaa',
  image: 'images/pig.png'
}).appendTo(tabris.ui.contentView);
```

![screenshot_2017-09-13-14-13-21](https://user-images.githubusercontent.com/2341769/30377789-5a93d2d6-9891-11e7-87e7-ce54b585aad5.png)

**Comment by mpost** [comment]
Fixed for the upcoming 2.1.1 release.
