### ISSUE TITLE
How can i get a widget's offsetX and offsetY ?

### ISSUE THREAD

**Issue by xiaojue** [eclipsesource/tabris-js#1492]
### Problem description

How can i get a widget's offsetX and offsetY ? I want scroll to a widget location in scrollView. LayoutData is no offsetXY information.

### Expected behavior

Maybe add offsetXY  information with every widget layoutdata ?

### Environment

- Tabris.js version:2.1.0 
- Device:iphone6s 
- OS:ios 10.3.1 

### Code snippet

```javascript
var firstWidget = new TextView({top:0,height:50}).appendTo(ui.contentView);
var mywidget = new TextView({top:"prev() 10"}).appendTo(ui.contentView);
//mywidget.get("offsetY") //60?
```

**Comment by cookieguru** [comment]
#850

**Comment by cpetrov** [comment]
@xiaojue You can get the position of the widget relative to its parent by accessing its `bounds` property. However, it will be available only after the widget has been laid out. A widget has been laid out after its [`"resize"` event](https://tabrisjs.com/documentation/latest/api/Widget#resize) has been fired.

**Comment by xiaojue** [comment]
@cpetrov `bounds` property is my want ! thank you !
