### ISSUE TITLE
Picker fires "selectionIndexChanged" on creation

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1495]
### Problem description
Upon initialization of a TabFolder with Tabs and a Picker with items:

||`"select"`|`"selectionChanged"/"selectionIndexChanged"`|
|---|---|---|
|TabFolder|n|n|
|Picker|n|y|

When creating a TabFolder with Tabs, neither its `"select"` nor `"selectionChanged"` events are fired.

When creating a Picker with items, its `"selectionIndexChanged"` event is fired.

### Expected behavior

Since the Picker was initialized with its selection, its `selectionIndex` didn't change. I propose to suppress the initial `"selectionIndexChanged"` event.

||`"select"`|`"selectionChanged"/"selectionIndexChanged"`|
|---|---|---|
|TabFolder|n|n|
|Picker|n|n|

### Environment

- Tabris.js version: 2.1
- OS: iOS 11 and Android 5.1

### Code snippet

```javascript
const {Picker, Tab, TabFolder, ui} = require('tabris');

const AIRPORTS = [
  {id: 'SFO', name: 'San Francisco'},
  {id: 'TXL', name: 'Berlin Tegel'},
  {id: 'FRA', name: 'Frankfurt'}
];

new Picker({
  left: 20, top: 20, right: 20,
  itemCount: AIRPORTS.length,
  itemText: (index) => AIRPORTS[index].name
}).on('select', () => console.log('Picker: select fired'))
  .on('selectionIndexChanged', () => console.log('Picker: selectionIndexChanged fired'))
  .appendTo(ui.contentView);

let tabFolder = new TabFolder({
  left: 20, top: 'prev() 8', right: 20
}).on('select', () => console.log('TabFolder: select fired'))
  .on('selectionChanged', () => console.log('TabFolder: selectionChanged fired'))
  .appendTo(ui.contentView);

new Tab({title: 'Tab1'}).appendTo(tabFolder);
new Tab({title: 'Tab2'}).appendTo(tabFolder);
```

### Related
Related Windows issue: #1494

**Comment by patrykmol** [comment]
I have checked the iOS side and there is nothing fired on widget creation. It seems like JS problem (which makes even more sense because multiple platforms exhibit this problem).

**Comment by cpetrov** [comment]
The issue is that for the Picker, the properties are only set when `tabris "flush"` is fired. This happens too late, i.e. after the change event handlers are registered.

**Comment by cpetrov** [comment]
This issue is still valid.

**Comment by cookieguru** [comment]
Still valid in 3.0.0-beta2

**Comment by mpost** [comment]
I can also confirm this issue to still exist with the current 3.x `nightly`. Changing the labels to _js_.

**Comment by cpetrov** [comment]
On latest 3.x, no Picker items are initially preselected and no `selectionIndex` is initially fired.
