### ISSUE TITLE
cordova-plugin-x-toast hide() is not work in 2.1.0 developer app

### ISSUE THREAD

**Issue by xiaojue** [eclipsesource/tabris-js#1497]
### Problem description
cordova-plugin-x-toast hide() is not work in 2.1.0 developer app on iphone6s.

### Expected behavior
should be hide when toast success. i tried setTimeout 1000 but it's not hide too.

### Environment

- Tabris.js version:2.1.0 
- Device:iphone6s 
- OS:IOS 10.3.3 

### Code snippet

```javascript
// A minimal, *self-contained* code snippet to reproduce the problem:
window.plugins.toast.showShortTop("test",()=>{
  window.plugins.toast.hide();
})
//is not hide...
```

**Comment by cpetrov** [comment]
I can confirm the problem on iOS. It is also reproducible in the Cordova Example of the developer app - toasts show, but never hide. Works as expected on Android.

**Comment by ralfstx** [comment]
As toast popups are simple and universal UI elements, we consider supporting them in tabris directly (#1104).

**Comment by mpost** [comment]
The ios issue has been resolved in the mean time. Closing as "fixed".
