### ISSUE TITLE
"scale" method of CanvasContext does not work as expected

### ISSUE THREAD

**Issue by elshadsm** [eclipsesource/tabris-js#1499]
### Problem description

We scale the canvas context and draw graphics on it. Everything works fine for the first operation. However, when we try to redraw the graphics by using the same draw operations, the graphics are drawn bigger than previous. How much we continue to redraw the graphics, so much their size increases. The issue happens only in Android.

### Expected behavior

The same graphics must be shown with the same appearance when we redraw them.
### Environment

- Tabris.js version: 2.1.
- Device: Nexus 6P
- OS: 8.0

### Code snippet

```javascript
const {Canvas, Button, ui, device} = require('tabris');

let canvas = new Canvas({
  left: 10, top: 10, right: 10, bottom: 100
}).appendTo(ui.contentView);

new Button({left: 10, bottom: 10, right: 10, text: 'Draw'})
  .on('select', () => draw())
  .appendTo(ui.contentView);

function draw() {
  let scaleFactor = device.scaleFactor;
  let ctx = canvas.getContext('2d', canvas.bounds.width * scaleFactor, canvas.bounds.height * scaleFactor);
  ctx.scale(scaleFactor, scaleFactor);
  ctx.strokeStyle = 'rgb(78, 154, 217)';
  ctx.lineWidth = 10;
  ctx.moveTo(20, 20);
  ctx.lineTo(canvas.bounds.width - 40, canvas.bounds.height - 40);
  ctx.stroke();
}
```

**Comment by mpost** [comment]
Fixed in the android client.
