### ISSUE TITLE
Console.dir support

### ISSUE THREAD

**Issue by bryantee** [eclipsesource/tabris-js#1501]
As a user, I would love for there to be support for `console.dir` so that I can log some objects to the console just as I might expect in Chrome.

![image](https://user-images.githubusercontent.com/10674447/30888558-002311fa-a2d6-11e7-9f19-82648d8b4366.png)

**Comment by mpost** [comment]
We should improve the integration with the chrome/safari debugging to support this feature.

**Comment by mpost** [comment]
Closing this for now as the console now supports https://docs.tabris.com/latest/api/Console.html#dirxmlobject
