### ISSUE TITLE
tabrisJS 2 ios app error

### ISSUE THREAD

**Issue by gacal** [eclipsesource/tabris-js#1503]
!!!
![img_4626](https://user-images.githubusercontent.com/3254134/31097705-e8f4127a-a7c8-11e7-8e51-1c50e6dcffee.png)
![img_4627](https://user-images.githubusercontent.com/3254134/31097707-ea406cf0-a7c8-11e7-9e95-24e14bcac401.png)

**Comment by cookieguru** [comment]
The first error likely refers to an error installing the plugin during build time.  Please upload your full build log somewhere and link it here.

The second one is likely a syntax error in your code.

**Comment by cpetrov** [comment]
Compatibility with iOS 9 was broken in the latest developer app (2.1). We will release a patch soon addressing the issue. If possible, please update to iOS 10.

**Comment by gacal** [comment]
ios10 simulator...

<img width="322" alt="ekran resmi 2017-10-03 01 30 26" src="https://user-images.githubusercontent.com/3254134/31102381-80038040-a7da-11e7-9130-6c7d115093da.png">

and my device xiaomi mi5 android 7.0. build is successful but not working (null white screen)

**Comment by cookieguru** [comment]
@gacal You have a version mismatch.  See https://stackoverflow.com/questions/46351859/tabris-js-developer-app-not-loading-my-app

**Comment by gacal** [comment]
yes. i'm using tabris init, not working. same screen
my package.json

<img width="544" alt="ekran resmi 2017-10-03 01 40 51" src="https://user-images.githubusercontent.com/3254134/31102776-45680a12-a7dc-11e7-9f5c-238943f9b92e.png">

**Comment by cookieguru** [comment]
@gacal What version are you building your app against?

**Comment by gacal** [comment]
simulator : ios 10.2
reel device : android 7.0

**Comment by cookieguru** [comment]
@gacal What version of **Tabris.js** are you building your app against?

**Comment by gacal** [comment]
tabris 2.1.0 @cookieguru

**Comment by gacal** [comment]
move to folder **node_modules**, **package.json** and all **.js files** **www** directory 
...finally working

please check

**Comment by cpetrov** [comment]
@gacal Were you using the [Tabris CLI](https://www.npmjs.com/package/tabris-cli) for your builds when this issue occurred, i.e. `tabris build <platform>`? If yes, try to execute `tabris clean` and then `tabris build <platform>` again. Make sure that the environment variables `TABRIS_IOS_PLATFORM`, `TABRIS_ANDROID_PLATFORM` and `TABRIS_WINDOWS_PLATFORM` are unset. Tabris CLI will download the matching platform automatically. Also please ensure that you are using the latest version of the CLI.

Building using the Cordova CLI is not supported as of Tabris.js 2.

**Comment by gacal** [comment]
null project : 
tabris build ios = config.xml does not exist at cordova/config.xml

but there is xml file

<img width="706" alt="ekran resmi 2017-10-03 18 07 44" src="https://user-images.githubusercontent.com/3254134/31132584-cebda0a4-a865-11e7-83b9-be99aab415b1.png">

**Comment by cpetrov** [comment]
@gacal Tabris.js CLI requires a [project layout](https://tabrisjs.com/documentation/latest/build.html#project-layout) in which config.xml is located in a subdirectory called `/cordova`. Tabris CLI (when using `tabris init`) generates a project with such a layout.
