### ISSUE TITLE
tabris run ios syntax error

### ISSUE THREAD

**Issue by gacal** [eclipsesource/tabris-js#1504]
tabris run syntax error

<img width="648" alt="ekran resmi 2017-10-03 20 02 54" src="https://user-images.githubusercontent.com/3254134/31138092-f136dda2-a875-11e7-81ba-d65bc8bd4d44.png">

**Comment by cpetrov** [comment]
Your Node.js version does not support certain ES6 features utilized in Tabris.js CLI. Please update to the latest [LTS](https://nodejs.org/en/download/) or [current](https://nodejs.org/en/download/current/) version.

**Comment by gacal** [comment]
<img width="861" alt="ekran resmi 2017-10-03 21 34 58" src="https://user-images.githubusercontent.com/3254134/31142366-bccec4a0-a882-11e7-9ad9-ac4b2e3a2859.png">

**Comment by cookieguru** [comment]
@gacal Can you `pwd` on that last screenshot?  It's probably [this](https://github.com/eclipsesource/tabris-js/issues/1503#issuecomment-333923339)

**Comment by gacal** [comment]
<img width="772" alt="ekran resmi 2017-10-04 11 33 39" src="https://user-images.githubusercontent.com/3254134/31166579-eb030dac-a8f7-11e7-8e0c-0c5170ffce2e.png">

**Comment by gacal** [comment]
tabris init okay 
working
thanks

**Comment by gacal** [comment]
Do you want a fee?
