### ISSUE TITLE
transparent and float toolbar problem

### ISSUE THREAD

**Issue by gacal** [eclipsesource/tabris-js#1506]
### Problem description
i want to this profile page please help me.

<img width="320" alt="friends_profile" src="https://user-images.githubusercontent.com/3254134/31218636-a25482a8-a9c3-11e7-8953-c15133437cf9.png">

### Environment

- Tabris.js version: 2.1.0
- Device: xiaomi 5
- OS: Android 7

### Code snippet

```javascript
const {NavigationView, Page, ui, ImageView} = require('tabris');

// Create and open a page

let navigationView = new NavigationView({
    left: 0, top: 0, right: 0, bottom: 0,
    toolbarColor:'transparent'
}).appendTo(ui.contentView);

let page = new Page({}).appendTo(navigationView);

new ImageView({
    image: {src: 'source'},
    scaleMode: 'fill',
    layoutData: {left: 0, top: 0, right: 0, height: 200}
}).appendTo(page);

ui.statusBar.displayMode = 'float';
ui.statusBar.background = 'transparent';

```

**Comment by mpost** [comment]
Please be more specific about the challenges you are facing.

**Comment by gacal** [comment]
sorry,
i want to do noble transparent toolbar

**Comment by mpost** [comment]
The `displayMode` float is correct. you can set the color to a transparant color like eg: `#rrggbbaa`. For example `#00000000`.

**Comment by gacal** [comment]
ui.navigationBar.displayMode='float'; not working

<img width="843" alt="ekran resmi 2017-10-05 15 26 25" src="https://user-images.githubusercontent.com/3254134/31227421-75b8e620-a9e2-11e7-85ff-fd2e57d160ed.png">
<img width="843" alt="ekran resmi 2017-10-05 15 26 25" src="https://user-images.githubusercontent.com/3254134/31227521-cd5dca1c-a9e2-11e7-9cff-644edf2d46a3.jpg">

**Comment by mpost** [comment]
You likely want to set the statusbar 'theme' to _light_ as well:

```js
const {TextView, ui} = require('tabris');

ui.statusBar.displayMode = 'float';
ui.statusBar.background = '#00000000';
ui.statusBar.theme = 'light';

new TextView({text: 'Hello World!'}).appendTo(ui.contentView);
```

**Comment by gacal** [comment]
result same. toolbar not float
i want to this
![a](https://user-images.githubusercontent.com/3254134/31228941-d709b8c8-a9e7-11e7-9923-9a6298b712d5.jpg)

**Comment by mpost** [comment]
Try out the Snippet above. You will find that the `TextView` sits underneath the `StatusBar`.

**Comment by gacal** [comment]
the main problem is not the status bar; toolbar...

**Comment by mpost** [comment]
Looking at your screenshot, this is not a native iOS toolbar widget. You can therefore recreate it yourself with a regular composite.

**Comment by mpost** [comment]
Closing this as "resolved". Please reopen if you have any more issues.
