### ISSUE TITLE
Markdown lists are not correctly rendered in docs

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1508]
### Problem description

Looking at the lists in tables, you can see that the list is not rendered as expected. https://tabrisjs.com/documentation/2.1/build#android-specific-preferences

Also in the bullet list here there are some elements missing: http://docs.tabris.com/latest/layout.html#top-right-bottom-left

### Expected behavior

The html elements should be rendered as a proper list.

**Comment by tbuschto** [comment]
So in layout.md THIS:

```

**Comment by tbuschto** [comment]
The lists-in-tables problems seems to have been solved in the markdown files at some point. The issue in layout.md remains.

**Comment by tbuschto** [comment]
Fixed in eddf50fc6c69a5c21fa038c0b511e43efb1b6114
