### ISSUE TITLE
Developer console not accessible from App

### ISSUE THREAD

**Issue by arjunmenon** [eclipsesource/tabris-js#1509]
After building new apps, cannot access the developer console with the url.
Also, from the Tabris JS2 app, adding the url does not load the app.
In both cases, after adding the url it just relaunches itself.
Here is a video grab I just recorded

https://drive.google.com/file/d/0B3tW8HqE_ubMOXJMank0aUlhSU0/view?usp=sharing

The log file for the app built - http://paste.ubuntu.com/25691750/

Repo link to app - https://github.com/arjunmenon/csdk

### Environment

- Tabris.js version: 2.0.3
- Device: Redmi 4a
- OS: Andriod 6
- Node: 6.10.3

**Comment by cookieguru** [comment]
Can you post the logcat output?

**Comment by arjunmenon** [comment]
Hey
I am using the online build service to test out apps. I dont have a Android setup in my computer. As you can see, I am just using the starter app. I dont know why it is behaving this way. This had been a problem before but I ignored it by continuously building apps online and then testing it, I thought it may be a bug will be fixed eventually in updates.

**Comment by cookieguru** [comment]
To view logcat output, either [set up ADB on your development machine](https://www.google.com/search?q=minimal+adb) and run `adb logcat` or try one of the many [logcat apps](https://play.google.com/store/search?q=logcat&c=apps).

**Comment by mpost** [comment]
Is it possible that the url is not reachable from the device? You could try it on the deviecs browser.  access the `/package.json` file.

**Comment by arjunmenon** [comment]
@cookieguru 
http://paste.ubuntu.com/25712713/

In the start itself it says
```java
10-10 14:37:22.260 29051 29324 I TabrisJsLauncher: Connecting to app at http://192.168.1.3:8080
10-10 14:37:22.311 29051 29324 E TabrisJsLauncher: Could not load java script files
10-10 14:37:22.311 29051 29324 E TabrisJsLauncher: java.lang.RuntimeException: Could not load boot.min.js or boot.js file from tabris module 'node_modules/tabris/'
10-10 14:37:22.311 29051 29324 E TabrisJsLauncher: 	at com.eclipsesource.tabris.js.launcher.utils.loader.AbstractBootLoader.load(AbstractBootLoader.java:33)
10-10 14:37:22.311 29051 29324 E TabrisJsLauncher: 	at com.eclipsesource.tabris.js.launcher.utils.loader.DownloadService.downloadJavaScriptApp(DownloadService.java:45)
10-10 14:37:22.311 29051 29324 E TabrisJsLauncher: 	at com.eclipsesource.tabris.js.launcher.utils.loader.DownloadService.onHandleIntent(DownloadService.java:34)
10-10 14:37:22.311 29051 29324 E TabrisJsLauncher: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
10-10 14:37:22.311 29051 29324 E TabrisJsLauncher: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-10 14:37:22.311 29051 29324 E TabrisJsLauncher: 	at android.os.Looper.loop(Looper.java:154)
10-10 14:37:22.311 29051 29324 E TabrisJsLauncher: 	at android.os.HandlerThread.run(HandlerThread.java:61)
10-10 14:37:22.318 29051 29051 I Timeline: Timeline: Activity_launch_request time:106566179
10-10 14:37:22.353 29051 29051 D CordovaActivity: Paused the activity.
10-10 14:37:22.384 29051 29051 I CordovaLog: Changing log level to DEBUG(3)
```

**Comment by arjunmenon** [comment]
@mpost In the browser that package.json opens

**Comment by mpost** [comment]
Are the boot.js/boot.min.js available in the nodes_modules folder? Make sure you are on the latest tabris version.

**Comment by arjunmenon** [comment]
@mpost No. These are the files in both folders
```javascript
~/Desktop/node/tabris/csdk/node_modules/tabris$ ls
globals.d.ts  package.json  README.md  tabris.d.ts  tabris.js

~/Desktop/node/tabris/utest1/node_modules/tabris$ 
globals.d.ts  package.json  README.md  tabris.d.ts  tabris.js
```
Both have the same contents, but only `utest1` is working.

Will upgrading break the `utest1` app? That is the only one working as expected.

**Comment by mpost** [comment]
This means that your native client is based on a different tabris version than your Tabris.js version. You should make sure to build against Tabris.js 2.1.1 and also use Tabris.js 2.1.1 in your package.json.

**Comment by arjunmenon** [comment]
Hey @mpost 
That solves the problem. Updating the package makes it run in the Tabris JS developer app and the app console. Older versions dont run.

So any updates are not backward compatible. Noted.

Thanks for this.

**Comment by arjunmenon** [comment]
Hey @mpost 
Running the `examples` and `snippets` from the repo, have the same problem. It behaves the same way I had posted the video - https://drive.google.com/file/d/0B3tW8HqE_ubMOXJMank0aUlhSU0/view?usp=sharing

Updating the package.json does not help.

**Comment by mpost** [comment]
@arjunmenon Thanks for posting the video we will investigate the issue. At the moment you are ok with launching from the dev console i presume?

**Comment by arjunmenon** [comment]
Hey @mpost 
Yes from the online dev console I can access the snippets very good.
Wanted to simply inform you about that.
