### ISSUE TITLE
Tabris Chinese Documention

### ISSUE THREAD

**Issue by Youjingyu** [eclipsesource/tabris-js#1510]
I have translated the tabris.js document into Chinese, welcome to check it out :
[Tabris Chinese Documention](https://youjingyu.github.io/Tabris-Documention)

**Comment by mpost** [comment]
Thanks a lot for your efforts. At this point we are focusing on improving the English documentation. At some point we will provide translations to other languages and will be happy to integrate you translation.

**Comment by caiya** [comment]
Why 'API Reference' button of the documention page can not click, my browser is chrome, i tried sometimes, but still not.

**Comment by Youjingyu** [comment]
@caiya some JS files may not be loaded successfully. You can check them in the console.

**Comment by mpost** [comment]
Closing this for now.
