### ISSUE TITLE
Save image issue

### ISSUE THREAD

**Issue by KurozeroPB** [eclipsesource/tabris-js#1514]
When I try to run this code after I build the apk file it errors with "Error: No such file or directory: /sdcard/DCIM/Img/test.jpg". But when I run it with the Tabris.js 2 app it saves the image perfectly fine. Has anyone an idea why?
btw I know that /sdcard isn't the best way but I only need to use it and I know 100% that /sdcard/DCIM/Img exists.
```javascript
saveButton.on('select', () => {
  fetch(imgUrl)
    .then(res => res.arrayBuffer())
    .then(data => {
      // image is the the file name e.g. test.jpg
      tabris.fs.writeFile('/sdcard/DCIM/Img/' + image, data)
        .then(() => console.log('Saved image as: ' + image))
        .catch(err => console.error(err));
    })
    .catch(err => console.error(err));
});
```

**Comment by KurozeroPB** [comment]
Yes that was indeed it, thank you very much for these links. I could barely find anything on google about permissions or I was just looking over it. But it's working now, thank you.

**Comment by mpost** [comment]
Great to hear. :)
