### ISSUE TITLE
Gracefully handle version mismatches

### ISSUE THREAD

**Issue by cookieguru** [eclipsesource/tabris-js#1516]
### Problem description
There have been [several](https://stackoverflow.com/questions/46351859/tabris-js-developer-app-not-loading-my-app) [recent](https://github.com/eclipsesource/tabris-js/issues/1509) [issues](https://github.com/eclipsesource/tabris-js/issues/1503) regarding version mismatches with the Tabris.js native client and the JS code.  The error messages do not point to the fact that there is a version mismatch, and often point towards the Tabris.js internals.

### Expected behavior

Any of these, ranked in order of desirablility:
1. Prevent loading code through the developer console if the JS code doesn't match the native app's version
2. Prevent building an app if there is a version mismatch
3. Check for a version mismatch at runtime

**Comment by mpost** [comment]
With Tabris.js 2.1 we switched to load a file called `boot.js` as the first file. This file bootsraps how Tabris.js is is loaded. Before, we loaded the apps `package.json` as the first file. So in general we will get ride of the problem of having this initial mismatch as more and more people migrate to 2.1 with their Tabris.js clients and package.json version.

Once the loading has succeeded we do show an error when the client and js part do not match.

**Comment by mpost** [comment]
Since the missing boot.js file is a message people see quite often when they connect to a local app that is not available, we could make the error message more pleasing like: _Could not connect to http://123:8080 (no boot.js found)_.

**Comment by cookieguru** [comment]
@mpost I don't know if that last message is clear enough, as it doesn't provide the developer a way to recover from the error as boot.js is not a file that is expected to be provided by the developer.

**Comment by mpost** [comment]
@cookieguru You are probably right about that. We should not mention the boot.js at all.

**Comment by mpost** [comment]
We have improved the error messages in a previous release. It now states:

![image](https://user-images.githubusercontent.com/73655/41404726-351be91c-6fc8-11e8-8b8a-db611d13f9e8.png)
