### ISSUE TITLE
Including and Using Cordova Plugin

### ISSUE THREAD

**Issue by acefxlabs** [eclipsesource/tabris-js#1517]
Hello Guys

U am trying to use Cordova Device Plugin but the doc is not detailed enough

In the config.xml i added this line
`<plugin name="cordova-plugin-device"/>`

I then downloaded the plugin from [https://github.com/apache/cordova-plugin-device](url)
And extracted it to the cordova folder 

Then in my code i used `const c_device = require("cordova/cordova-plugin-device");` but i keep getting error with note `_notify@[native code]` and the application stops there

Please help is needed and will also appreciate an update on doc to guide new comers

**Comment by cookieguru** [comment]
You don't download the plugin.  You need to [build](https://tabrisjs.com/documentation/latest/build.html) an app to get access to the plugin's APIs.  When you build, the plugin will be integrated automatically.

Anything that touches a device's native API requires a new build.  If you are only modifying JavaScript, you do not need to build.  Adding a plugin means a new build, but updating your JS code does not.


Also FYI, most of the properties you get from `cordova-plugin-device` are available on [`tabris.device`](https://tabrisjs.com/documentation/latest/api/device.html).

**Comment by acefxlabs** [comment]
Thanks @cookieguru, will take that into practice, the reason i am using the device plugin is cause i want to get the UIID of the device but all my search about it has not yeilded anything

Please how can i get device UIID from `tabris.device`

**Comment by cookieguru** [comment]
See #609

**Comment by mpost** [comment]
As @cookieguru pointed out. The discussion in #609 describes why relying on the UUID is not best practice anymore.

**Comment by acefxlabs** [comment]
Hi thanks alot, i just realized its the IMEI of the device that i needed not the UIID, is there a way to that 

Thanks

**Comment by acefxlabs** [comment]
@mpost @cookieguru - apart from downloading the cordova plugin been wrong, 
- did i add the plugin the right way in the config.xml `<plugin name="cordova-plugin-device"/>` 
- Also did i call it rightly in the code `const c_device = require("cordova/cordova-plugin-device");`

Thanks in advance

**Comment by mpost** [comment]
@acefxlabs You should provide a version number when adding the plugin to your app.

May i ask what kind of information you want to retrieve via the plugin?

**Comment by acefxlabs** [comment]
@mpost - noted 
IMEI of the device

**Comment by mpost** [comment]
@acefxlabs you have to build your tabris app with the tabris cli or the tabrisjs.com build service in order to have an app which contains different plugins.

regarding the IMEI, this is also not a good way to identify a user. your device might not have a sim card or multiple sim cards in which case it can not be used reliably.

**Comment by acefxlabs** [comment]
Please, sorry my my questions if sounding stupid

> you have to build your tabris app with the tabris cli or the tabrisjs.com build service in order to have an app which contains different plugins.
**- Does that mean i cant test app directly in the tabris app to use other plugins**

> regarding the IMEI, this is also not a good way to identify a user. your device might not have a sim card or multiple sim cards in which case it can not be used reliably
**- I understand this but i still need to get the IMEI since the client spec require it and the API we are using need it to actually work** 

Thanks

**Comment by mpost** [comment]
You can not test plugins directly in the dev app. You have to rebuild the app since the plugins provide native code that needs to be compiled.

The IMEI could likely be obtained with the plugin you mentioned above.

**Comment by acefxlabs** [comment]
Thanks alot, clear with your answer now
