### ISSUE TITLE
Show widget image in all doc pages

### ISSUE THREAD

**Issue by caiya** [eclipsesource/tabris-js#1519]
Suggest added component pic in its introduce doc, easy to view component effects directly

**Comment by Youjingyu** [comment]
@caiya most widgets have a preview picture in widgets api. see [widgets](https://tabrisjs.com/documentation/latest/api/Action.html)

**Comment by mpost** [comment]
We should expand on the provided images.

**Comment by mpost** [comment]
See https://github.com/eclipsesource/tabris-js/issues/1617

**Comment by mpost** [comment]
The widget index page has been created.
