### ISSUE TITLE
how to read files and folders in hard disk (outside the application source) ?

### ISSUE THREAD

**Issue by Youjingyu** [eclipsesource/tabris-js#1520]
### Problem description

My app wants to browse files in user's hard disk, but with `fs` , i can only browse files in `fs.cacheDir`  and `fs.filesDir`, how to read files and folders outside them?  

 Do i need to use cordova plugin?  Can i use cordova-plugin-file to implement it?

**Comment by mpost** [comment]
Currently we only support reading files from the mentioned directories. We will expand on these capabilities in the future. For now you can use a cordova plugin like `cordova-plugin-file`.

**Comment by arjunmenon** [comment]
Are all features of `cordova-plugin-file` supported?
To get `metadata`, `toURL` these show that they are not defined.
Also, does the `cordova-plugin-media` not work outside the application source? I can't get it to read mp3s from the sdcard or the internal storage?

**Comment by mpost** [comment]
Closing as "resolved". Please reopen if you have any more issues.
