### ISSUE TITLE
Responsive UI in Tabris

### ISSUE THREAD

**Issue by acefxlabs** [eclipsesource/tabris-js#1521]
I had an issue recently getting Tabris to work for Tablets and Mobile insuch a way that i want so i ended up creating this function, I will keep posting an update on it but just wanna share it may be it can help

```
var box = {};
        if (this.ui.width > 600) {
            box = {
                centerX: 0,
                centerY: 0,
                width: (Number(this.ui.width) / 2) - 30
            };
        }
        //Phone
        else {
            box = {
                centerX: 0,
                centerY: 50,
                width: Number(this.ui.width) - 30
            };
        }

return box;
```

A more clean version will be posted on git page once we are done with the project, but needed to share this

**Comment by cookieguru** [comment]
Another option is to use a [`CollectionView`](https://tabrisjs.com/documentation/latest/api/CollectionView) with a [`columnCount`](https://tabrisjs.com/documentation/latest/api/CollectionView#columncount) of 1 or 2.  You can toggle between 1 and 2 depending on if the screen's height is greater than or less than its width.

**Comment by acefxlabs** [comment]
CollectionView worked well, thanks @cookieguru
