### ISSUE TITLE
Seeking guidance on Video fullscreen mode

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1523]
### Problem description

I am having a portrait orientation fixed app. I am displaying a Video (using Video widget) in one of the screen (like Youtube). I am looking for suggestions on how to get the behaviour like Full screen Play mode and return etc. (when the user touches / toggles the screen orientation). If toggle is not an option, may you suggest how can I play the same video on full screen mode (landscape like)

**Comment by mpost** [comment]
You should relayout your views so that the Video covers the entire screen when the screen size changes.

**Comment by mpost** [comment]
Closing as "resolved". Please reopen if that doesn't suite your needs.
