### ISSUE TITLE
ERROR: Failed to trigger build.

### ISSUE THREAD

**Issue by arjunmenon** [eclipsesource/tabris-js#1525]
Hey
I am facing issues building apps online.
Statuses looks fine - https://status.github.com/messages, https://www.traviscistatus.com/#

- Tabris.js version: 2.1.1

**Comment by mpost** [comment]
Could you provide more details? What issue are you facing?

**Comment by arjunmenon** [comment]
The app is not building online. It gives that error.

**Comment by arjunmenon** [comment]
I have tried multiple times between intervals.
![screenshot-2017-10-18 tabris js app test audioplayer](https://user-images.githubusercontent.com/953959/31718855-08b8dee8-b42f-11e7-983c-dfe2ab32b1cf.png)

**Comment by arjunmenon** [comment]
Hey
I noticed it was because of user permissions. If I remove these line, it was building.
```javascript
<platform name="android">

            <preference name="android-minSdkVersion" value="21" />
            <preference name="android-targetSdkVersion" value="23" />

            <uses-permission android:name="android.permission.BLUETOOTH" />
            <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />

            <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
            <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />

            <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
            <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

            <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
            <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
            <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
            <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />

  </platform>
```
But I require them to access a particular file directory.

**Comment by irbull** [comment]
If you click on a failed build, you should see a line in the summary such as:
`Build environment created <build_id>`. Can you past your build_id here?

**Comment by arjunmenon** [comment]
There is  no line like that. You can see in the screenshots, when I click on a failed build, that error is the only thing displayed.

**Comment by irbull** [comment]
What happens when you click on "#4 10 minutes ago"? (Likely something like 3 hours ago now).

**Comment by arjunmenon** [comment]
The second screenshot which I posted, it shows that with only this line - `ERROR: Failed to trigger build.`

**Comment by irbull** [comment]
Sorry, I didn't notice that at the bottom. It's not actually kicking off the build on travis. I know we support permissions, but maybe something is misconfigured here. Could it be the `android-minSdkVersion` lines?

@mpost is our android expert. Do you have any thoughts on these setting Moritz?

**Comment by mpost** [comment]
In general setting the permission is correct. Some more build output would be required to gain a better sense of the error.

**Comment by cookieguru** [comment]
@mpost I think @arjunmenon has posted all the output. It looks like it fails instantly.

**Comment by mpost** [comment]
@cookieguru I agree. We are investigating an infrastructure problem.

**Comment by arjunmenon** [comment]
@irbull I did a hit-n-trial with those configs. With the `<platform>`, with `<android-minsdkversion>`, with/out the `<Androidmanifest.xml>`, everything that `config.xml` file had.

The build only happened when I removed anything specific to a platform.

**Comment by mpost** [comment]
@arjunmenon Are you building against `nightly` or `2.1.1`?

**Comment by arjunmenon** [comment]
Building with 2.1.1

**Comment by arjunmenon** [comment]
Hey
Is there an example where `platform` specific configs are made? Looking for compatibility from Android 5.
Better if I follow your examples.

**Comment by cookieguru** [comment]
@arjunmenon [This] (https://github.com/eclipsesource/tabris-js/issues/1456#issuecomment-320196534) is the `config.xml` for the Tabris.js app in the app stores.

**Comment by mpost** [comment]
Closing this for now. Please reopen if you have any more problems.

**Comment by jumpjack** [comment]
Has this issue ever been solved?
I am not able to compile an apk for android, due to same error, and [tutorial ](https://docs.tabris.com/latest/build#build-service) is quite confusing, as it mixes online and offline development; I tried different folder structures, because other tutorials suggest different folder structures to compile cordova apps...

**Which is the correct folder structure?** 

Where should I exactly place config.xml, package.json and app.js? Do I need a /www folder or not?
I am very confused.
(Please post a screenshot of  correct folder structure, not an ASCII-structure of folders tree!)

**Comment by cookieguru** [comment]
`config.xml` should be placed in the `cordova` folder.
`package.json` should be at the root of the respository
`app.js` can be in any folder you'd like, but you'll need to point to it from the `main` field in your `package.json` file.

You can see a working app and its layout here:
https://github.com/eclipsesource/tabris-js-hello-world

**Comment by mpost** [comment]
Following the hello-world example folder structure is a good approach.

**Comment by cookieguru** [comment]
> There is no "dist" file or folder in that folder!

The example is built with Typescript, not Javascript.  The `dist` folder is generated by the `tsc` transpiler which will generate Javascript files and place them in the dist folder.  The dist folder is never committed because it is in [the repository's `.gitignore` file](https://github.com/eclipsesource/tabris-js-hello-world/blob/master/.gitignore#L1).  This is a standard practice with *all* Typescript projects--the built Javascript is never stored and only built as needed

You could clone the Hello World project, run `npm install` and get a feel for how it works

**Comment by jumpjack** [comment]
Thanks but I would prefer not to install anything, I'd like to get the online compiler working, because I don't use/know npm and node.js, I write in plain javascript, and I am trying to port my script to an Android app.

But I can't understand if this "Failed to trigger build" error is happening on my side or on server side: I see that previously it depended on server, but how can I figure it out? I see no errors in console.

**Comment by cookieguru** [comment]
@jumpjack It won't be possible to build an app with Tabris.js without npm.  Initially you'll need it to install the [`tabris` dependency](https://www.npmjs.com/package/tabris) by way of the `tabris-cli`.  That way you can test out your app with hot reloading without having to submit to the build service.

Regarding the "Failed to trigger build" error: I have seen this a couple of times recently as well.  Are you trying to build a repo which is private on GitHub?

**Comment by jumpjack** [comment]
I usually test my playground script directly on the phone using Tabrisjs developer app 3.x, and it works fine; now I'd like to turn the playground script into a standalone app.

The repo is public:
![image](https://user-images.githubusercontent.com/1620953/163178525-61cd0a37-7335-4455-b9a4-126333cdb0dc.png)
https://github.com/jumpjack/MyRenaultAndroid

**Comment by jumpjack** [comment]
The building page says "Contact us" at https://tabrisjs.slack.com/ , but I can't get it working, slack.com complains about me not having an account; do I need an account to ask for support? But if I access with google, site complains about me not having any account... but does not propose any method to register!

**Comment by jumpjack** [comment]
I eventually succeeded in compiling a demo app by  forking this repo:

https://github.com/gimco/tabris-helloworld

But it looks like tabris compiler looks for "master" branch, while default branch in github is now called "main", as I discovered after attempting some dozens of times to compile a branch while I was editing the other one....
