### ISSUE TITLE
Why connection failed on windows 10?

### ISSUE THREAD

**Issue by anUglyOldDog** [eclipsesource/tabris-js#1526]
## **Could not establish connection (status 0)**
Could not load file: http//127.0.0.1/package.json

![qq 20171019225454](https://user-images.githubusercontent.com/26728536/31777405-8e426d08-b520-11e7-99b7-d7f35d357a79.png)

![qq 20171019230144](https://user-images.githubusercontent.com/26728536/31777777-81014cc6-b521-11e7-8e21-1e3fe70a3c4b.png)

**Comment by cookieguru** [comment]
Number 3: https://tabrisjs.com/documentation/latest/windows-support.html#developer-app

**Comment by anUglyOldDog** [comment]
thank you.
