### ISSUE TITLE
cordova-plugin-media basic playback fails even for online files

### ISSUE THREAD

**Issue by arjunmenon** [eclipsesource/tabris-js#1528]
After a long [discussion on SO](https://stackoverflow.com/questions/46816599/cordova-plugin-media-not-playing-from-local-uri/46817230#46817230) about cordova-plugin-media, there is possiblity that this plugin does not work properly
I would like to find out if it is a tabrisjs issue or the plugins?
Here is the `adb` output - http://paste.ubuntu.com/25774543/ - for a simple app with nothing but the cordova-plugin-media with this simple code
```javascript
var media = new Media('http://www.vorbis.com/music/Epoq-Lepidoptera.ogg', onSuccess, onError);
media.play();

function onSuccess() {
            console.log("playAudio():Audio Success");
}
// error callback
function onError(err) {
            console.log("playAudio():Audio Error: " + JSON.stringify(err));
}
```

This [issue](https://github.com/eclipsesource/tabris-js/issues/484) had the same problem but it worked for playback from the internet. In my scenario, even that does not work.

Where could be the problem? Plugin?
In the[ `adb` output](http://paste.ubuntu.com/25774543/), you can see on `line 211` it starts but there is an  error immediately but on `line 237` there is buffering, but nothing happens on the phone. Not even a callback.

TabrisJS - 2.1.1
Android 6 on Redmi 4A
Git repo of basic code - https://github.com/arjunmenon/tabris-cordova-media

**Comment by cookieguru** [comment]
I can't say for sure, but this line looks fishey:
```
ExtMediaPlayer-JNI: env->IsInstanceOf fails
```
I would say that's a problem with the plugin.

**Comment by mpost** [comment]
In general media playback should work in Tabris.js as expected. Looking at the log, these lines do also look suspecious.

```
10-20 01:17:03.022  6762  6762 D outgoing-operation: 'Notify' o13 of 'finish' with arguments {message=S01 Media183579634 s, status=1, keepCallback=false, callbackId=Media183579634}
10-20 01:17:03.025  6762  6773 D MediaHTTPConnection: filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 6.0.1)
10-20 01:17:03.025  6762  6851 W PluginManager: THREAD WARNING: exec() call to Media.startPlayingAudio blocked the main thread for 36ms. Plugin should use CordovaInterface.getThreadPool().
10-20 01:17:03.026  6762  6774 D MediaHTTPConnection: proxy null port 0
10-20 01:17:03.027  6762  6774 I DpmTcmClient: RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor
10-20 01:17:03.038  6762  6762 D outgoing-operation: 'Notify' o13 of 'finish' with arguments {message=S11 Media183579633 {"action":"status","status":{"id":"123ab12c-b430-4762-e33b-16a242642de9","msgType":1,"value":1}}, status=1, keepCallback=true, callbackId=Media183579633}
10-20 01:17:03.040  6762  6762 D outgoing-operation: 'Notify' o13 of 'finish' with arguments {message=S01 INVALID s, status=1, keepCallback=false, callbackId=INVALID}
10-20 01:17:03.284  6762  6762 D CordovaActivity: Stopped the activity.
```

You mentioned that there are known problems with the plugin. Maybe this is similar?

**Comment by arjunmenon** [comment]
Maybe default to some other cordova plugin then.

**Comment by arjunmenon** [comment]
Hey @mpost @cookieguru 
Is there any good alternatives to this plugin sweetly compatible with Tabris?

**Comment by cookieguru** [comment]
@arjunmenon I have not tried either of them, but there here are two alternatives:
* [cordova-plugin-audioplayer](https://www.npmjs.com/package/cordova-plugin-audioplayer)
* [cordova-plugin-media-multi](https://www.npmjs.com/package/cordova-plugin-media-multi)

I was limiting my [search](https://cordova.apache.org/plugins/?platforms=cordova-android%2Ccordova-ios%2Ccordova-windows) to plugins that work on all three platforms that Tabris.js supports.  If you only need one or two there might be more options.
