### ISSUE TITLE
Main page dispose event is not fired

### ISSUE THREAD

**Issue by ifurnadjiev** [eclipsesource/tabris-js#153]
I want to keep the application state (some settings and field values) when leaving the application. I've tried to set some items in localStorage in main application page "dispose" event. Unfortunately, these items are not available on next application start. I don't know if "dispose" event is not fired or setting the item failed when destroying the application. This happens on Android. Can't try on iOS.
...
console.log(localStorage.getItem("foo"));
tabris.create( "Page", {
    title: "Tabris.js",
    topLevel: true
}).on( "dispose", function() {
  localStorage.setItem( "foo", "bar" );
}).open();
...
Is this supposed to work?

**Comment by ralfstx** [comment]
This issue is not related to installPatch. The dispose event is not fired on the root page when the application is left.

**Comment by ralfstx** [comment]
This use case should now be covered by the `terminate` event on `app`.
