### ISSUE TITLE
Unexpected color for the "initial" value

### ISSUE THREAD

**Issue by elshadsm** [eclipsesource/tabris-js#1530]
### Problem description

When we set "initial" value to the Button#textColor, `pink` colored text is displayed on the button. The unexpectable pink color causes some design-wise problems. 

### Expected behavior

The default colored text must be displayed when we set "initial" value to the Button#textColor. 

### Environment

- Tabris.js version: 2.1.1
- Device: Nexus 6p
- OS: Android 8.0.0

### Code snippet

```javascript
const {Button, ui} = require('tabris');

new Button({
  centerX: 0, centerY: 0,
  textColor: 'initial',
  text: 'Button Text'
}).appendTo(ui.contentView);
```
![screenshot_20171020-183046](https://user-images.githubusercontent.com/13982125/31826856-3f90c11c-b5c7-11e7-9fc4-4406704b1d65.png)

**Comment by cookieguru** [comment]
Reproduces on other widgets too.  Same color also on Android 8.0:
```js
const {TextView, ui} = require('tabris');
new TextView({
  text: 'Hello world',
  textColor: 'initial',
}).appendTo(ui.contentView);
```

**Comment by mpost** [comment]
Thanks for reporting we will fix this colorization.

**Comment by mpost** [comment]
The issue has been fixed in `nightly`. Please reopen if you have any more problems.
