### ISSUE TITLE
Unexpected text color for the disabled button

### ISSUE THREAD

**Issue by elshadsm** [eclipsesource/tabris-js#1531]
### Problem description

We set "initial" value to the Button#textColor then update it with a different color. When we disable the button, the text color becomes "pink" which is unexpectable. 

### Expected behavior

Proper disabled text color must be displayed when we disable the button. 

### Environment

- Tabris.js version: 2.1.1
- Device: Nexus 6p
- OS: Android 8.0.0

### Code snippet

```javascript
const {Button, ui} = require('tabris');

let button = new Button({
  centerX: 0, centerY: 0,
  textColor: 'initial',
  text: 'Button Text'
}).on('select', ({target}) => target.enabled = false)
  .appendTo(ui.contentView);

button.set({
  textColor: '#00386b',
  background: '#5fffc8',
});
```

![screenshot_20171020-185413](https://user-images.githubusercontent.com/13982125/31827275-54b7cb34-b5c8-11e7-8954-39ba2b26025a.png)

**Comment by mpost** [comment]
The issue has been fixed in `nightly`. Please reopen if you have any more problems.
