### ISSUE TITLE
Horizontal scroll view doesn't scroll in some cases

### ISSUE THREAD

**Issue by elshadsm** [eclipsesource/tabris-js#1533]
### Problem description

I tried to create exact widget structure that exists in the real project. We create vertical scroll view then append children that are created from Canvas. If we set `touchStart`, `touchEnd`, `touchCancel`, `tap` listeners to the every Canvas, the scroll view doesn't scroll.

### Expected behavior

The scroll view must scroll as expected. 

### Environment

- Tabris.js version: 2.1.1
- Device: iPhone 6
- OS: 11.0.3

### Code snippet

```javascript
const {ScrollView, Composite, Canvas, TextView, ui} = require('tabris');

let composite = new Composite({class: 'composite', left: 0, top: 100, right: 0, height: 50})
  .appendTo(ui.contentView);

let scrollView = new ScrollView({
  left: 2, top: 2, bottom: 2, right: 2,
  direction: 'horizontal',
  background: '#234'
}).appendTo(composite);

for (let i = 0; i <= 50; i++) {
  new Canvas({left: 'prev() 16', centerY: 0, width: 70}).append(
    new TextView({
      left: 4, top: 4, bottom: 4, right: 4,
      textColor: 'white',
      text: i + '°'
    })
  )
    .on('touchStart', () => { })
    .on('touchEnd', () => { })
    .on('touchCancel', () => { })
    .on('tap', () => { })
    .appendTo(scrollView);
}
```

**Comment by patrykmol** [comment]
ScrollView works as intended. Canvas consumes scroll events. Removing listeners solves the problem. Let me know how do you want to proceed with this.

**Comment by mpost** [comment]
When no `touchMove` event is registered, the `ScrollView` should be scrolling.
