### ISSUE TITLE
Custom Splash Screen size - without default margin

### ISSUE THREAD

**Issue by HudAgency** [eclipsesource/tabris-js#1534]
### Problem description

In addition to the default themes, the splash screen can not be customized in terms of 'size', it is not adaptive.

### Expected behavior

Is it possible to have the splash screen image that fits the size of the screen, ie without the default margins?

### Environment

- Tabris.js version: 2.1.3
- Device: Samsung Galaxy S7 Edge
- OS: Android 7.0

### Screenshot

![](https://i.stack.imgur.com/hVZSF.jpg)

**Comment by cookieguru** [comment]
Do you have a `xxxhdpi` splash screen specified in your `config.xml`?

**Comment by HudAgency** [comment]
Yes, my config.xml is this: 

    <?xml version='1.0' encoding='utf-8'?>
    <widget id="example.test.app" version="0.0.1">
	<name>{APP_NAME}</name>
	<description>Example Tabris.js App</description>
	<author email="{MY_EMAIL}">{MY_NAME}</author>
	<preference name="EnableDeveloperConsole" value="$IS_DEBUG" />
	<preference name="Fullscreen" value="true"/>
    <preference name="splashscreen" value="screen"/>
    <preference name="Orientation" value="portrait"/>
	<platform name="android">
        <splash density="ldpi" src="res/android/drawable-ldpi/screen.png" />
		<splash density="mdpi" src="res/android/drawable-mdpi/screen.png" />
		<splash density="hdpi" src="res/android/drawable-hdpi/screen.png" />
		<splash density="xhdpi" src="res/android/drawable-xhdpi/screen.png" />
		<splash density="xxhdpi" src="res/android/drawable-xxhdpi/screen.png" />
		<splash density="xxxhdpi" src="res/android/drawable-xxxhdpi/screen.png" />
		<preference name="ThemeSplash" value="@style/Theme.Tabris.SplashScreen" />
	</platform>
	<plugin name="tabris-plugin-maps" spec="3.0.0">
		<variable name="ANDROID_API_KEY" value="{MY_ANDROID_API_KEY}" />
	</plugin>
</widget>

PS: the stackoverflow question is obviously mine, but has no response.

Thanks in advance!

**Comment by mpost** [comment]
There are no default margins for the splash. you should not try to fill the entire screen with an image but only rely on a graphical element to be placed in the center.

**Comment by maoamid** [comment]
I had the same problem, and like @mpost said, the only working solution was to theme the android app with a colour background on splash, and put a logo on center from cordova config. How can I do the same on iOS? I cannot find theming info for iOS apps

**Comment by mpost** [comment]
@maoamid Great to hear that it worked for you. This is actually not "the only solution" but "the right solution". :) More details here: https://material.io/guidelines/patterns/launch-screens.html

For iOS the regular cordova splash screen configuration applies.

**Comment by HudAgency** [comment]
As last comment of @cookieguru on StackOverflow, I'll close it as resolved.
Thanks to all! :)

StackOverflow Comment: [link](https://stackoverflow.com/questions/46934117/custom-splash-screen-size-tabris-js/47291582#47291582)

**Comment by cookieguru** [comment]
😳 It was all @mpost
