### ISSUE TITLE
"resize" may fire prematurely in some cases

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1538]
### Problem description

In some cases, the `"resize"` event may fire prematurely, before the layout has been completed.

In the snippet below, `"resize"` of the `Composite` fires two times. Console output on the iPad Air:

```
768
{"left": 0, "top": 0, "width": 14, "height": 0}
{"left": 0, "top": 0, "width": 768, "height": 960}
```
Since the `Composite` is full-width, it should never be laid out with width 14, since the screen width is 768.

Expected behavior is observed when doing any of:

  * commenting out (1), i.e. letting `tabBarLocation` of the `TabFolder` be `"auto"`
  * commenting out (2), i.e. not calling the `device.screenWidth` getter immediately after creating the page widgets, i.e. requesting their layout
  * swapping (3a) and (3b), i.e. appending the page to the navigation view before it is appended to the content view

### Expected behavior

`"resize"` should always fire once and only after the layouting of the widget has been finished.

Expected console output:
```
768
{"left": 0, "top": 0, "width": 768, "height": 960}
```
### Environment

- Tabris.js version: 2.x-nightly
- Device: iPad Air
- OS: iOS 10

### Code snippet

```javascript
const {Composite, NavigationView, Page, TabFolder, Tab, device, ui} = require('tabris');

class TestPage extends Page {

  constructor() {
    super();
    this.append(
      new TabFolder({
        left: 0, top: 0, right: 0, bottom: 0,
        tabBarLocation: 'hidden' // (1)
      }).append(
        new Tab().append(
          new Composite({left: 0, top: 0, right: 0, bottom: 0})
            .on('resize', this._logBounds)
        )
      )
    );
    console.log(device.screenWidth); // (2)
  }

  _logBounds({target}) {
    console.log(JSON.stringify(target.bounds));
  }

}

let page = new TestPage();
let navigation = new NavigationView({left: 0, top: 0, right: 0, bottom: 0});
navigation.appendTo(ui.contentView); // (3a)
page.appendTo(navigation); // (3b)
```

**Comment by patrykmol** [comment]
The snippet produces the expected output now. Closing.
