### ISSUE TITLE
Unexpected layout

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1542]
### Problem description
In the layout scenario in the snippet, the red composite should fill its parent. However, after the image has been loaded, the red composite colapses. Its new height is dependent on the text length in the text view on the bottom - longer texts produce smaller heights of the red composite.

The problem is not apparent when:
1) The bottom bound of the green composite is changed from `'#customButton'` to `0`.
2) A composite instead of an image view is used or the `image` property is removed from the image view.

|Android|iOS(expected layout)|
|---|---|
|![screenshot_1509985174](https://user-images.githubusercontent.com/2341769/32451413-00d4b93a-c317-11e7-80e9-e0851ba1af13.png)|![img_98bb5b59e568-1](https://user-images.githubusercontent.com/2341769/32451340-df5a3b18-c316-11e7-9242-567b31840236.jpeg)|

### Expected behavior
The red composite should always fill its parent, regardless of image rendering, i.e. no green area should be shown. 

### Environment

- Tabris.js version: nightly
- Device: emulator 
- OS: Android 8.0.0

### Code snippet

```javascript
const {TextView, Composite, ImageView, ui} = require('tabris');

ui.contentView.append(
  new Composite({
    left: 0, top: 0, right: 0, bottom: '#customButton',
    background: 'green'
  }).append(
    new Composite({
      left: 0, top: 0, right: 0, bottom: 0,
      background: 'red'
    }).append(
      new ImageView({
        top: 0, left: 0,
        image: 'images/cart.png'
      })
    )
  ),
  new Composite({
    id: 'customButton',
    left: 10, bottom: 10, right: 10,
    background: 'blue'
  }).append(
    new TextView({
      left: 0, top: 0, right: 0, bottom: 0,
      text: 'Hello world! Just some text...'
    })
  )
);
```

**Comment by mpost** [comment]
This in fact caused by the same issue as described in https://github.com/eclipsesource/tabris-js/issues/1445.

**Comment by cpetrov** [comment]
#1445 closed.
