### ISSUE TITLE
Add fs API to create new directories 

### ISSUE THREAD

**Issue by sevenuz** [eclipsesource/tabris-js#1543]
Is there any way in tabris.js creating new directories without cordova?
Thanks :)

**Comment by mpost** [comment]
Creating directories is a very valid scenario. As of now Tabris.js does not support it out of the box but we will definitely add it in the near future. As of right now you can resort to a cordova plugin.

**Comment by mpost** [comment]
We will add support for 

```ts
fs.createDir(dir): Promise // nativeCall("createDir", {path, onSuccess, onError})
fs.removeDir(dir): Promise // nativeCall("removeDir", {path, onSuccess, onError})
ts.isFile(dir): <Promise or Boolean?>
ts.isDir(dir): <Promise or Boolean?>

```

**Comment by mpost** [comment]
In addition we will add

```ts
fs.removeDir(dir): Promise
fs.remove(file | dir): Promise
```

**Comment by mpost** [comment]
Extended file system support has been added for the Tabris.js 3.4 release. See the corresponding commit https://github.com/eclipsesource/tabris-js/commit/1b1b5e67e8f24a4dbb03842bdd0d8cc77b857ffc.
