### ISSUE TITLE
Get layout properties set dynamically

### ISSUE THREAD

**Issue by arjunmenon** [eclipsesource/tabris-js#1544]
Hey
How can I get properties of widgets when they are not specified but rather defined by different properties?

Like, `height` can be set by specifying `top` and `bottom`. But if I do `widget.get('height')` it would not return the computed height. I think `get` should return all widget properties.

I want to know because I want to set the [card height](https://github.com/jokorivai/cordova-plugin-tabrisjs-card) based on the composite it is in; 
And also it allows relative computation later with other widgets.

**Comment by cookieguru** [comment]
#446 might still appy.  Pretty sure this issue has come up before and there was a more relevant issue than #446 but I can't find it.

**Comment by arjunmenon** [comment]
Hey
I did search for this with various keywords. 
When I had tried that, simply doing `widget.bounds.height` returned `null`, same as with `get`.
In fact, doing `widget.bounds` just returned a hash of set values, all with zero, even when `left`, `right` were set, provided that was [the way to access them](https://tabrisjs.com/documentation/latest/types.html#bounds)

**Comment by arjunmenon** [comment]
Hey
Any update?
Can you give me an idea. I have an inner composite, the height of which needs to be half of the outer composite. The outer composite is set as `left: 0, top: 0, right: 0, bottom: '60%',`
Doing, `outer.get('height')` or `outer.bounds.height` returns `null`
Since, screen sizes could vary, not good to hard code.

**Comment by mpost** [comment]
You can only get the dimensions of your Views after they have been layed out. Use the `resize` listener to perform your calculations.

**Comment by arjunmenon** [comment]
Okay let me try this way. To be clear, I can fire that just after tab is appended to the `ui.contentView`, right?
Though, please consider this a feature request.
Thanks.

**Comment by mpost** [comment]
@arjunmenon When ever you change your layout by adding/removing widgets the ui will be relayouted. When widgets have a new size they will fire a `resize` event to which you can listen and adjust your ui accordingly.

**Comment by arjunmenon** [comment]
Hey @cookieguru 
I have a textview inside a composite, it is showing width greater than the composite. 
```JavaScript 
let musicInfo = new Composite({ // WRAPPER FOR SONG INFORMATION
    left:[albumArt,10],right: 10, top:20, bottom: 20
  }).appendTo(npHero)

  var songName = new TextView({ // # SONG NAME
    left: 10, top: 10,
    text: "A Sky Full of Stars A Sky Full of Stars",
    id: 'songName',
    font: 'bold 20px condensed',
  }).appendTo(musicInfo);

  musicInfo.on('resize', (element) => {
  console.log('musicInfo '+element.width); // musicInfo 168
});
  songName.on('resize', (element) => {
  console.log('songName'+element.width); // songName 299.5
});
```
Why is the TextView, `songName ` greater than Composite? Isn't that supposed to be 158?
You can try this in the playground as well.

**Comment by cookieguru** [comment]
@arjunmenon Which platform is this?

**Comment by arjunmenon** [comment]
Hey
On Android 6.
I also tried it on ipad v10.3.3. Set the size of the composite to minimum. The TextView still shows up bigger width.

**Comment by mpost** [comment]
If you want your `TextView` to have the same width as the parent `Composite` you should set the `right` property to 0 on the `TextView`.

**Comment by arjunmenon** [comment]
Hey @mpost 
That was it. Subtle. Will keep note.
While checking out [this issue](https://github.com/eclipsesource/tabris-js/issues/1347#issuecomment-302968698), per the solution for text break to work there should be a `right` property. Only if `top` is present it would simply clip without line-break. Can i assume this to be the norm across platform?

**Comment by mpost** [comment]
The outlined solution will work across platforms.
