### ISSUE TITLE
Text input cursor color is not changeable 

### ISSUE THREAD

**Issue by elshadsm** [eclipsesource/tabris-js#1547]
### Problem description

The text input cursor color is dark blue. According to the app design, we can use a color like a dark blue. In that case, it is hard to detect the cursor. If we want to change the cursor color, we can't do it. Change the text input cursor color is not possible.

### Expected behavior

The text input cursor color must be changeable.

### Environment

- Tabris.js version: 2.1.0
- Device: iPhone 6
- OS: iOS 11.1

![cursor](https://user-images.githubusercontent.com/13982125/32662441-000792a4-c644-11e7-97ca-4bf116a61941.jpg)

![cursor_problem](https://user-images.githubusercontent.com/13982125/32662752-0dacd49a-c645-11e7-9375-ace9daa81a85.jpg)

**Comment by karolszafranski** [comment]
https://github.com/eclipsesource/tabris-ios/commit/70f0cf71e4db1b01d4a8b0368ce9f5b4969ba8a2

**Comment by 3to1null** [comment]
I don't have experience with iOS, but on android the cursor is controlled by the theme. It might be the same on iOS.

**Comment by cookieguru** [comment]
@3to1null The theme is [specific to Android](https://tabrisjs.com/documentation/latest/build.html#android-specific-preferences)

**Comment by karolszafranski** [comment]
https://github.com/eclipsesource/tabris-js/commit/bd823345270281bc49cdc9b3fe3839813088e399
