### ISSUE TITLE
Change android SDK version used to compile

### ISSUE THREAD

**Issue by 3to1null** [eclipsesource/tabris-js#1548]
I was wondering if it is possible to change the android SDK version that Tabris uses to build the app. 

I need to use the [local notification plugin](https://github.com/katzer/cordova-plugin-local-notifications), but while building I get an error which [should be fixed](https://github.com/katzer/cordova-plugin-local-notifications/issues/1408) when using version 26 or higher of the android SDK. I tried to force tabris to use this version by adding  `<preference name="android-compileSdkVersion" value="26" />` to config.xml, but this doesn't appear to do anything.

**Comment by cookieguru** [comment]
I'm not an expert in this area, but there are a number of [Cordova preferences](https://cordova.apache.org/docs/en/latest/config_ref/#preference) that can control this as well as [Gradle properties](https://cordova.apache.org/docs/en/latest/guide/platforms/android/#configuring-gradle) (one of which is `cdvCompileSdkVersion`).

**Comment by 3to1null** [comment]
I tried both cordova (see my first comment) and Gradle (I tried adding `cdvCompileSdkVersion=26` as a Gradle argument) but neither of them seem to make any difference.

Can anyone else test if they are able to install the aforementioned local notification plugin?

**Comment by 3to1null** [comment]
So the android-compile-target appear to be set by Tabris. I tried editing the the target in the `tabris-android\framework\project.properties` but this results in lots of dependency issues which I am not able to solve.

I got the following error: `error: package android.support.v4.media.app.NotificationCompat does not exist`, which I fixed by adding `compile 'com.android.support:support-media-compat:26.+'` to the dependencies in `build.gradle`, but doing so resulted in another error (`error: cannot access ActivityCompatApi23
    final IAndroidWidgetToolkit widgetToolkit = activity.getWidgetToolkit();`) which I wasn't able to fix. I tried adding the [cordova-android-support-gradle](https://www.npmjs.com/package/cordova-android-support-gradle-release) plugin to my config.xml and I tried adding both `compile 'com.android.support:support-compat:26.+' and  `compile 'com.android.support:support-v4:+` to the dependencies in `build.gradle', but sadly, nothing seems to work.

**Comment by cookieguru** [comment]
Maybe a different approach can work: are you able to use an older version of `cordova-plugin-local-notifications`?

**Comment by 3to1null** [comment]
Just tried, I can install the 0.8.x branch, but it's not compatible with Tabris' firebase-plugin*. And I would like to use the 0.9.x branch, since it has lots of new features.

* following error occurs: `Tabris2-Ichthus-App\build\cordova\platforms\android\src\com\eclipsesource\firebase\messaging\TabrisFirebaseMessagingService.java:77: error: constructor Builder in class Builder cannot be applied to given types;
    return new NotificationCompat.Builder(this, NOTIFICATION_CHANNEL_DEFAULT)`

**Comment by mpost** [comment]
You could use the nightly platforms of tabris android as they are targeting the latest Android 8 (API 26).

**Comment by mpost** [comment]
Closing as resolved. Please reopen if you have any more issues.
