### ISSUE TITLE
Why Animations doesn't support layoutData so far?

### ISSUE THREAD

**Issue by sevenuz** [eclipsesource/tabris-js#1549]
The animate(...) funtion is great, but the posible values aren't enought.

I think the animations based on the platform animations and there are no possibilities animating the position or size?

Thanks so far, Tabris rocks

**Comment by cookieguru** [comment]
Yes, you can animate the position and the size.  Per [the docs](https://tabrisjs.com/documentation/latest/api/Widget#transform) you pass in a [`Transofrmation`](https://tabrisjs.com/documentation/latest/types.html#transformation) object, which can specify (among other things) `scaleX`, `scaleY`, `translationX` and `translationY` properties

**Comment by sevenuz** [comment]
Thank You, I know these values. But they don't change the layoutData. 
A Workaround is to reset the transformation data after animation and instead set the layoutData.

I found a solution to stay in line while scaling down the widget which would be centered.
You can checkout my [Gist](https://gist.github.com/sevenuz/0cb66804a1c3c8c17d0ef48fbf5a5671).
