### ISSUE TITLE
authentication in tabris-js

### ISSUE THREAD

**Issue by truthSeekr** [eclipsesource/tabris-js#1553]
Do you know some libaries that cover authentication in tabris-js. I dont want to use firebase.  When I was developing ionic I was using ng-auth-token + devise_auth_token, but I was using angular also.... What I found also is https://github.com/lynndylanhurley/j-toker that can be integrated with devise_auth_token easy and it uses jquery. Either angular or jquery I suppose its bad idea to use in tabris app. I found also library https://jwt.io/ but to use it I need to dig more in authentication process. 

Its not an issue its more open topic, are u watching stackoverflow for tabris js problems ?

**Comment by cookieguru** [comment]
See my comment to number 1 on https://github.com/eclipsesource/tabris-js/issues/1491

Yes, myself and the developers watch the StackOverflow tag--all the questions have answers. There's also a [Slack channel](https://tabrisjs.herokuapp.com/) where the community and maintainers gather.

**Comment by mpost** [comment]
Closing as resolved. Please reopen if you have any more input.
