### ISSUE TITLE
Setting TextInput 'focused' sometimes does not work

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1555]
### Problem description

A TextInput should get focused when the UI containing it has gets shown. This does not work in the case when the focused TextInput has been appended to a page, which is opened later.

### Expected behavior

In the snippet below, the TextInput should get focused when its page gets opened.

### Environment

- Tabris.js version: 2.x-nightly
- Device: iPad Air
- OS: iOS 10.3

### Code snippet

```javascript
const {Page, NavigationView, TextInput, ui} = require('tabris');

let navigation = new NavigationView({
  left: 0, top: 0, right: 0, bottom: 0
}).appendTo(ui.contentView);

let page = new Page();

new TextInput({
  top: 20, left: '20%', right: '20%',
  message: 'Type here, then confirm',
  focused: true
}).appendTo(page);

page.appendTo(navigation);
```

**Comment by patrykmol** [comment]
This snippet is working properly as of 2.5.1. Tested on iOS 11.4. Closing.
