### ISSUE TITLE
TextInput "focus" fired unexpectedly when tapping through a widget

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1556]
### Problem description

When a widget is overlaying a TextInput, tapping on the TextInput multiple times consecutively results into `"focus"` being fired fired multiple times (and the keyboard disappearing/reappearing), although the TextInput is already focused.

Overlaying a TextInput with e.g. a Canvas can be useful when drawing some custom TextInput borders.

### Expected behavior

Since the overlaying widget has no gesture event handler, it should not modify the touch interaction behavior of the widget underneath. i.e. `"focus"` should not be fired again when tapping on the TextInput widget multiple times.

### Environment

- Tabris.js version: 2.x-nightly
- Device: Simulator
- OS: Android 8 

### Code snippet

```javascript
const {Composite, TextInput, ui} = require('tabris');

ui.contentView.append(
  new TextInput({
    left: 0, top: 0, right: 0
  }).on({focus: () => console.log('focus')}),
  new Composite({left: 0, top: 0, right: 0, height: 100})
);
```

**Comment by mpost** [comment]
We can confirm the issue.

**Comment by mpost** [comment]
Testing the snippet in 3.5 yields no problems. Closing it for now.

```js
import { Composite, contentView, TextInput } from 'tabris';

contentView.append(
  new TextInput({
    left: 0, top: 0, right: 0
  }).on({focus: () => console.log('focus')}),
  new Composite({left: 0, top: 0, right: 0, height: 100})
);
```
