### ISSUE TITLE
Improve information in The Book about debugging

### ISSUE THREAD

**Issue by mkempka** [eclipsesource/tabris-js#1557]
The book about tabris.js 2.2 contains section 3.3 Develop-deploy-test cycle

* The information here says that debugging is possible only on Android. Jochen on the other hand said that with iOS and Safari debugging would also be possible.
* It says "A detailed description of debugging Tabris.js can be found online." The word "online" is blue, but doesn't link anywhere, and there is no further information for eventual printouts.

So, essentially, there is no helpful information about debugging, which many developers and the competing frameworks (react native) see as a most essential feature. 

https://tabrisjs.com/downloads/ebook/tabrisjs-2.2.0.pdf

**Comment by mpost** [comment]
Thanks for the input. We will update the section accordingly.

**Comment by acefxlabs** [comment]
Also, we will like to know if there are paid books out there that we can get on tabris and video training. 
Tabris seems very promising but some information are not detailed enough for newbies 

Thanks

**Comment by mpost** [comment]
Closing as resolved.
