### ISSUE TITLE
Improve feedback for the command line interface

### ISSUE THREAD

**Issue by mkempka** [eclipsesource/tabris-js#1558]
The following command does not output anything:

$ tabris awertargfafqaw4g

I would expect a standard error that this is not a supported command and a list of supported commands. This would be a similar behavior to other tools we work with on the same level of analysis, i.e. "cordova" and "git".

**Comment by mpost** [comment]
Thanks for your feedback. Please open the issue on https://github.com/eclipsesource/tabris-js-cli.

**Comment by mkempka** [comment]
https://github.com/eclipsesource/tabris-js-cli/issues/30
