### ISSUE TITLE
Include help in the command line interface

### ISSUE THREAD

**Issue by mkempka** [eclipsesource/tabris-js#1559]
The following command doesn't output anything:

$ tabris help run

I would expect help about the run command, for example how I can specify the emulator/device.

Obviously I'd expect similar commands to output useful information, too:

$ tabris help build
$ tabris help clean
$ tabris help help

etc.

**Comment by cpetrov** [comment]
Try `tabris build -h`

**Comment by mkempka** [comment]
So the information is already there. All the better. I still request the 'help' command. This seems to have become a de facto standard in the last years.

**Comment by mkempka** [comment]
https://github.com/eclipsesource/tabris-js-cli/issues/31
