### ISSUE TITLE
Closing the last page does not close the application

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#156]
That's probably not a use case at all, however, closing the last page should terminate the application.

**Comment by ralfstx** [comment]
@hstaudacher In Tabris.js, top-level pages can be opened and closed. Both client seem to support that. Only the last top-level page must not be closed. Does that make sense?

If it's forbidden to close the last page, this restriction should be documented and enforced.

**Comment by hstaudacher** [comment]
Yes, it's the same with Tabris remote. One more thing: It's not possible to close the top level page the user is currently on.

**Comment by ralfstx** [comment]
This currently works with Tabris.js, because we set the `activePage` to the most recent one *before* sending the destroy.
