### ISSUE TITLE
Video widget touch event call problem

### ISSUE THREAD

**Issue by maoamid** [eclipsesource/tabris-js#1561]
### Problem description

On video widget no touch event are detected (tried 'tap', 'touchStart', 'touchEnd' )
The controls disappear after a few seconds and video can not be controlled anymore.

### Expected behavior

calling the touch event

### Environment

- Tabris.js version: 2.1.1
- Device: iPhone 5S
- OS: iOS

### Code snippet

```javascript
const { Video, ui } = require('tabris');

  let video = new Video({
      left: 0, top: 0, right: 0, bottom: 0,
      url: 'http://184.72.239.149/vod/smil:BigBuckBunny.smil/playlist.m3u8',
      controlsVisible: true,
      //autoPlay: false,
      class: 'video'
  }).on('tap', (event) => console.log(event))
  .appendTo(ui.contentView);

```

**Comment by patrykmol** [comment]
This is no longer reproducible. Closing.
