### ISSUE TITLE
TextInput with Drop-Down List

### ISSUE THREAD

**Issue by sevenuz** [eclipsesource/tabris-js#1562]
In the Tabris Android App there is a Drop Down List showing the last IP's to connect the smartphone with the server running on the pc.
I couldn't find the source code.  How can I use this functionality in my App?
Thanks for helping me on this strange issue:))

**Comment by cookieguru** [comment]
Would a [SearchAction](https://tabrisjs.com/documentation/latest/api/SearchAction.html) work?

**Comment by sevenuz** [comment]
The search action is exactly what I want but I can not use it as an normal widget of a page. It is only usable in the head of a navigation view, isn't it?

**Comment by cookieguru** [comment]
That is correct.  You'll have to stay tuned for #1247 or implement your own functionality by listening to the `focus` and `blur` events of the `TextInput`.

**Comment by sevenuz** [comment]
OK thank you I close this issue because of #1247
