### ISSUE TITLE
Images not working on local dev. "Rename snippets directory "images" to "resources"

### ISSUE THREAD

**Issue by mrmccormack** [eclipsesource/tabris-js#1569]
### Problem description

Images are not appearing on local app development.

**Snippet:**
https://github.com/eclipsesource/tabris-js/blob/master/snippets/imageview-tintcolor.js

If I rename folder 
    resources
to
    images 

it works 

Is there something special about the name resources.

I copy the exact snippet, and it does not show images on iPHone/Android

### Expected behavior

Before the recent change, everything worked...
After the change

*"Rename snippets directory "images" to "resources"*
images don't show up.

I have the entire resources folder... yet this does not work

```js
  image: {src: 'resources/cloud-check.png', scale: 3}
```
but
if I have a images folder, this works
```js
  image: {src: 'images/cloud-check.png', scale: 3}
```

### Environment

- Tabris.js version:  2
- Device: iPhone, and Samsung Galaxy S8
- OS: 

### Code snippet

```javascript
  image: {src: 'resources/cloud-check.png', scale: 3}
```

**Comment by mpost** [comment]
Thanks for your report. as you saw in the commit making the change, the rename is fully present in the snippets folder: https://github.com/eclipsesource/tabris-js/tree/master/snippets

Running the `imageview-tintcolor.js` snippet above from `master` shows the expected result.

![image](https://user-images.githubusercontent.com/73655/33930126-2f53de98-dfec-11e7-8374-f897b4b4846c.png)

Please make sure that you do not have any open changes in your local git workspace.

**Comment by mrmccormack** [comment]
Thanks for fasts response.... I still can't get images to show up.

Here is my Github repository with app.js **not** serving images (app.js contains https://github.com/mrmccormack/tabris1---images-not-working )

Here is what I did.
1. Created a new folder on Desktop,  followed the very good instructions at: https://tabrisjs.com/documentation/2.0/getting-started.html
1. The demo app.js worked perfectly on my iPhone
1. I copied the /resource folder and placed it under /src folder (https://github.com/eclipsesource/tabris-js/tree/master/snippets/resources)
1. I copied the code from imageview-tintcolor.js to app.js and REFRESH iPhone
1. everything worked, except NO images are shown, no errors in console.

What am I doing wrong?

Reference on Mac Finder:
![screen shot 2017-12-13 at 8 26 41 am](https://user-images.githubusercontent.com/3249215/33941120-7090448a-dfdf-11e7-8300-89912870b2dc.png)

Code now in app.js

```js

const {ImageView, Picker, ui} = require('tabris');

const COLORS = ['initial', 'red', 'green', 'blue'];

let imageView = new ImageView({
  top: 64, centerX: 0,
  image: {src: 'resources/cloud-check.png', scale: 3}
}).appendTo(ui.contentView);

new Picker({
  top: [imageView, 16], centerX: 0,
  itemCount: COLORS.length,
  itemText: index => COLORS[index]
}).on({
  select: ({index}) => imageView.tintColor = COLORS[index]
}).appendTo(ui.contentView);

```
The file 
    resources/cloud-check.png
does exist.

Thanks for  help...

Screen shot
![tabris](https://user-images.githubusercontent.com/3249215/33941266-0ac6e3c4-dfe0-11e7-857b-2ee171e46a9f.png)

**Comment by cookieguru** [comment]
Per [the docs](https://tabrisjs.com/documentation/latest/types.html#image) relative paths are resolved relative to `package.json`.  So in your case, the correct image source would be `src/resources/cloud-check.png`.  The snippets are meant to be served from the snippets directory, i.e. `cd snippets` followed by `tabris serve`

**Comment by mrmccormack** [comment]
Thanks,
 **that works perfectly** .. running from snippets directory as shown here:

```
imedia: /Users/imedia/Desktop/tabris-js-master/snippets    
tabris serve imageview-tintcolor.js
Server started.
Point your Tabris.js client to:
   http://192.168.0.22:8080

```
I'm still confused about this:

```js

// WHY DOES this works without relative path from json
// this was the way it was before Tabris update a few days ago.
image: {src: 'images/cloud-check.png', scale: 3}

// and this works too
  image: {src: 'src/images/cloud-check.png', scale: 3}

// this works as per docs,
image: {src: 'src/resources/cloud-check.png', scale: 3}

// and I now know, why this doesn't work
image: {src: 'resources/cloud-check.png', scale: 3}

```

**Comment by mrmccormack** [comment]
** I'll do more testing... something just isn't right on my end **
The solution you gave works...

**Comment by mpost** [comment]
Closing this as resolved. Please reopen if you have any more problems.
