### ISSUE TITLE
tabrisjs example for geolcation usage missing

### ISSUE THREAD

**Issue by andreasmihm** [eclipsesource/tabris-js#1574]
### Problem description

I see, that the tabrisjs developer app 2 has the cordova-plugin-geolocation installed, but I'm not able to find any example tabrisjs project, which exp0lains, how to use geolocation

### Expected behavior

There should be an example on how to use geolocation in tabrisjs apps

### Environment

- Tabris.js version: 2.2
- Device: iPhone 62plus
- OS: iOS 11

**Comment by mpost** [comment]
Currently it is recommended to use the plugin https://github.com/eclipsesource/tabris-plugin-maps if feasible for you.

**Comment by andreasmihm** [comment]
Is cordova-plugin-geolocation not workign at all? I thouhgt, since it is integrated in the tabrisjs 2 developer app, this would make testing much easier, I want to use it in a task for my students

**Comment by mpost** [comment]
It is currently integrated but we will remove it because it doesn't work as expected on Android. It is not guaranteed that any of the plugin in the tabris-js-app will be a stable platform for app development.

**Comment by andreasmihm** [comment]
thx
