### ISSUE TITLE
iOS App Rejected by Apple

### ISSUE THREAD

**Issue by wilsonna** [eclipsesource/tabris-js#1576]
### Problem description

I created a bare app, containing only `config.xml` and `package.json` and an empty `app.js`. I built the app using the online build. The build completed successfully, and I submitted the .ipa file to iTunes Connect using Application Loader 3.0 (also tried 3.6). Upon submission, I got an email from Apple on the following issues. As seen from the `config.xml` below, there are no plugins, so I can't figure out what could have caused these issues to be flagged out by Apple. Anyone has any ideas how this can be resolved?

> We have discovered one or more issues with your recent delivery for "Bare Test". To process your delivery, the following issues must be corrected: 
>
> **Missing Info.plist key** - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data. 
> Though you are not required to fix the following issues, we wanted to make you aware of them:
>
> **Missing Push Notification Entitlement** - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. Xcode 8 does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1. 
> 

### Expected behavior

I should be able to submit to iTunes Connect without any issues

### Environment

- Tabris.js version: 1.10
- Device: NA
- OS: iOS

### Code Snippet

config.xml
```
<?xml version='1.0' encoding='utf-8'?>
version, you will need to increment CFBundleVersion -->
<widget id="com.ubiqworks.bare" version="0.0.1"
        ios-CFBundleVersion="2"
        xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    
    <name>Bare Test App</name>
    <description>
        Bare Test App
    </description>
    <author email="wilson_na@yahoo.com.sg" href="https://www.ubiqworks.com/">
        Bare Test App
    </author>

    <preference name="EnableDeveloperConsole" value="false" />
	<platform name="android">
		<icon src="www/res/android/icon/Icon-ldpi.png" density="ldpi" />
		<icon src="www/res/android/icon/Icon-mdpi.png" density="mdpi" />
		<icon src="www/res/android/icon/Icon-hdpi.png" density="hdpi" />
		<icon src="www/res/android/icon/Icon-xhdpi.png" density="xhdpi" />
		<icon src="www/res/android/icon/Icon-xxhdpi.png" density="xxhdpi" />
		<icon src="www/res/android/icon/Icon-xxxhdpi.png" density="xxxhdpi" />
    </platform>
    <platform name="ios">
		<!-- iOS 8.0+ -->
		<!-- iPhone 6 Plus  -->
		<icon src="www/res/ios/icon/Icon-60@3x.png" width="180" height="180" />
		<!-- iOS 7.0+ -->
		<!-- iPhone / iPod Touch  -->
		<icon src="www/res/ios/icon/Icon-60.png" width="60" height="60" />
		<icon src="www/res/ios/icon/Icon-60@2x.png" width="120" height="120" />
		<!-- iPad -->
		<icon src="www/res/ios/icon/Icon-76.png" width="76" height="76" />
		<icon src="www/res/ios/icon/Icon-76@2x.png" width="152" height="152" />
		<!-- iOS 6.1 -->
		<!-- Spotlight Icon -->
		<icon src="www/res/ios/icon/Icon-40.png" width="40" height="40" />
		<icon src="www/res/ios/icon/Icon-40@2x.png" width="80" height="80" />
		<!-- iPhone / iPod Touch -->
		<icon src="www/res/ios/icon/Icon.png" width="57" height="57" />
		<icon src="www/res/ios/icon/Icon@2x.png" width="114" height="114" />
		<!-- iPad -->
		<icon src="www/res/ios/icon/Icon-72.png" width="72" height="72" />
		<icon src="www/res/ios/icon/Icon-72@2x.png" width="144" height="144" />
		<!-- iPhone Spotlight and Settings Icon -->
		<icon src="www/res/ios/icon/Icon-small.png" width="29" height="29" />
		<icon src="www/res/ios/icon/Icon-small@2x.png" width="58" height="58" />
		<!-- iPad Spotlight and Settings Icon -->
		<icon src="www/res/ios/icon/Icon-Small-50.png" width="50" height="50" />
		<icon src="www/res/ios/icon/Icon-Small-50@2x.png" width="100" height="100" />
		
		<splash src="www/res/ios/splash/no-splash-320x480.png" width="320" height="480"/>
		<splash src="www/res/ios/splash/no-splash-640x960.png" width="640" height="960"/>
		<splash src="www/res/ios/splash/no-splash-768x1024.png" width="768" height="1024"/>
		<splash src="www/res/ios/splash/no-splash-1536x2048.png" width="1536" height="2048"/>
		<splash src="www/res/ios/splash/no-splash-1024x768.png" width="1024" height="768"/>
		<splash src="www/res/ios/splash/no-splash-2048x1536.png" width="2048" height="1536"/>
		<splash src="www/res/ios/splash/no-splash-640x1136.png" width="640" height="1136"/>
		<splash src="www/res/ios/splash/no-splash-750x1334.png" width="750" height="1334"/>
		<splash src="www/res/ios/splash/no-splash-1242x2208.png" width="1242" height="2208"/>
		<splash src="www/res/ios/splash/no-splash-2208x1242.png" width="2208" height="1242"/>
	</platform>
</widget>
```

package.json
```
{
    "name": "BareTestApp",
    "description": "Bare Test App",
    "main": "app.js",
    "dependencies": {
        "tabris": "^1.9.0"
    }
}
```

**Comment by patrykmol** [comment]
Hello. To fix the first issue you need to add the following to the `config.xml` inside `platform="ios"`:
```
<config-file parent="NSPhotoLibraryUsageDescription" target="*-Info.plist">
    <string>This app needs access to your Photo Library to include a screenshot with feedback foo</string>
</config-file>
```

The second error is only a warning. In general you should check provisioning profile and what is enabled for it. Tabris.js does not require any permissions for features that you are not using. You can also check app id entitlements in dev portal. Something might be there as well.

**Comment by wilsonna** [comment]
Thanks @patrykmol 

`config-file` didn't work for me, but `edit-config` did.
```
<widget ...>
	...
	<platform name="ios">
		<edit-config target="NSPhotoLibraryUsageDescription" file="*-Info.plist" mode="merge">
			<string>This app needs access to your Photo Library</string>
		</edit-config>
	</platform>
</widget>
```

That worked around the problem, but I'm curious why this was needed even when my app is completely bare.

As for the warning, I've checked the provisioning profile and app id. As shown below, the push notifications is disabled. It didn't happen before with the same settings, so I'm wondering if anything changed and whether anyone's encountered the same issues.

![image](https://user-images.githubusercontent.com/11240991/34506771-bf5f7a04-f06a-11e7-9d35-4ba82df8208e.png)

![image](https://user-images.githubusercontent.com/11240991/34506800-fc358428-f06a-11e7-8798-202a3faa7549.png)

**Comment by karolszafranski** [comment]
Even though you are not using those features, they have to be implemented in the binary tabris.js engine. Apple analyzes that binary and is able to see that for example push notification support is implemented.

For a native app developer, it would mean that someone wrote code for supporting push notifications (so the intention was to use it) but incorrectly signed the binary (while with provisioning profile like that push notifications are not supported).

**Comment by wilsonna** [comment]
Thanks @karolszafranski, I guess that explains. Funny it was still working fine a few months back. Something must have changed recently.
