### ISSUE TITLE
Improve CollectionView API

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1581]
### Problem description

The current CollectionView API takes care of some concerns, which could be better managed by its cells themselves. Some of the API semantics may be confusing. 

  * `collectionView.cellHeight` - `cellHeight` is a property naturally belonging to the cell and not to the CollectionView. The cell widget itself should be able to specify its own dimensions.
  * `collectionView "select"` - One does not select a collection view, but a cell, so the `"select"` event on the CollectionView is confusing and violates separation of concerns.

### Expected behavior

Proposal:

* The `width` and `height` properties of the cell (belonging to its `layoutData`) should be respected by the CollectionView when laying out the cells. The cell holder should have intrinsic height based on the cell height and be as wide as the collection view. Cells should be laid out relative to their cell holder. Remove support for `collectionView.cellHeight`.
* Remove support for `collectionView "select"`. `cell "tap"` should be used instead.

This would remove the need for 2 of the 4 typical explicit conditional structures required to use a collection view with multiple cell types, each with a different height and selection handler (see code snippet).

### Environment

- Tabris.js version: 2.x

### Code snippet

Example usage of the current CollectionView API:
```javascript
let list = new CollectionView({
  left: 0, top: 0, right: 0, bottom: 0,

  cellType: index => items[index].type,

  createCell: (type) => {
    if (type === 'type1') {
      return new CellType1();
    } else if (type === 'type2') {
      return new CellType2();
    } else if (type === 'type3') {
      return new CellType3();
    }
  },

  updateCell: (cell, index) => {
    let item = items[index];
    if (item.type === 'type1') {
      cell.image = item.image;
    } else if (item.type === 'type2') {
      cell.text = item.text;
    } else if (item.type === 'type3') {
      // ...
    }
  },

  cellHeight: (index, type) => {
    if (type === 'type1') {
      return 48;
    } else if (type === 'type2') {
      return 24;
    } else if (type === 'type3') {
      return 12;
    }
  }
}).on('select', ({index}) => {
  if (items[index].type === 'type1') {
    // do something
  } else if (items[index].type === 'type2') {
    // do something else
  } else if (items[index].type === 'type3') {
    // ...
  }
}).appendTo(ui.contentView);

list.load(items.length);
```

**Comment by cookieguru** [comment]
I can't find the comment, but someone benchmarked the change after the variable `cellHeight` was introduced.  The roundtripping to JS introduced significant lag.  For times when it is known in advance that the cell height will equal for all cells, would it be possible to specify this in advance, removing the need to roundtrip to calculate the height?  I foresee this as especially likely when `columnCount` > 1.

**Comment by tbuschto** [comment]
The select event is removed. The cellHeight thing is more a performance issue which should be tracked here #1767
