### ISSUE TITLE
Update documentation for keyboard types

### ISSUE THREAD

**Issue by mkempka** [eclipsesource/tabris-js#1587]
### Problem description

https://tabrisjs.com/documentation/latest/api/TextInput.html talks about keyboard types, and lists 'number' as one. But this is not actually a valid keyboard type.

### Expected behavior

It should list 'decimal' instead

**Comment by mpost** [comment]
It lists `decimal` as well. https://tabrisjs.com/documentation/latest/api/TextInput.html#keyboard

**Comment by jonek** [comment]
@mkempka Was the `decimal` "keyboard type" mentioned by @mpost what you were looking for?
Please close the issue if your problem is resolved.
