### ISSUE TITLE
geolocation cordova plugin doesn't work

### ISSUE THREAD

**Issue by Odle98** [eclipsesource/tabris-js#1588]
### Problem description

Like said in the title the [cordova-plugin-geolocation](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-geolocation/) doesn't work.

I tried to build a sample app with this plugin because I've to develop an app that sends location informations to a server.

I like this framework very much but I don't know how to solve this.

I obtain this error: "Could not load main module: TypeError: Cannot read property 'getCurrentPosition' of undefined...."

If I try to inspect navigator.geolocation via Tabris in-app terminal I obtain undefined

### Environment

I built the app for Android, creating an APK (not in release mode, so I've the in-app console).
Android Studio is installed and after I set ANDROID_HOME the build process is done without problems.

### Code snippet

config.xml

`<?xml version='1.0' encoding='utf-8'?>
<widget id="example.lez01" version="0.1.0">
  <name>Lez01</name>
  <description>
    Example Tabris.js App
  </description>
  <author email="john@example.org">
    John Smith
  </author>
  <preference name="EnableDeveloperConsole" value="$IS_DEBUG" />
  <plugin name="cordova-plugin-geolocation" spec="^1.0.0" />
</widget>`

app.js (location part)

`var onSuccess = function(position) {
        etichettaIniziale.text = 'Latitude: ' + position.coords.latitude;
};

navigator.geolocation.getCurrentPosition(onSuccess);`

I love this framework but I don't know what I'm missing.
I tried to read Cordova docs but still don't understand what's wrong with my configuration..

Thank you for support :)

**Comment by cookieguru** [comment]
Cordova runs in a browser, Tabris.js does not.  With Cordova, you can do anything a browser can do, but Tabris.js only [implements a subset of the APIs](https://tabrisjs.com/tabris-js-docs/latest/w3c-api.html) available in a browser.

See #1574, #1390, #960

**Comment by Odle98** [comment]
I tought that plugin doesn't rely on WebView, I should have documented better myself, excuse me..
Now it's all clear.

Thank you :D. 
I have appreciated your help very much!!
