### ISSUE TITLE
collectionView - select event issue

### ISSUE THREAD

**Issue by maoamid** [eclipsesource/tabris-js#1590]
### Problem description

Collection View
cells { imageView as icon + TextView as text label}
When Tapped over image(icon) zone in cell, there is no select event (neither tap event over image) only when highlightOnTouch is true on imageView (strange!)

### Expected behavior

select event should fire (doesn't matter what cell is composed from - my case one imageView + one textView)

### Environment

- Tabris.js version: nightly (2.4.0-dev20180216)
- Device: Lenovo Phone
- OS: Android 4.4.2

### Code snippet

```javascript
new CollectionView({
  left: 0, top: 0, right: 0, bottom: 0,
  padding: {
  	left: 3 * Style.MARGIN,
  	right: 3 * Style.MARGIN
  },
  background: black,
  itemCount: menuItems.length,
  cellHeight: maxItemHeight,
  columnCount: menuColumns, // two columns menu
  createCell: () => {
  	let cell = new Composite({
  		//highlightOnTouch: true
	}).on('tap', () => console.log('tapped'));
    new ImageView({
        centerX: 0, centerY: -15,
        id: 'icon',
        //highlightOnTouch: true
    }).appendTo(cell);
    new TextView({
        top: '#icon ' + Style.MARGIN,
        centerX: 0,
        textColor: Style.Colors.GREY,
        id: 'label'
    }).appendTo(cell);
	return cell;
  },
  updateCell: (cell, index) => {
    cell.apply({
      '#icon': {image: {src: './src/images/icon.png', width: 30, height: 30} },
      '#label': {text: 'label'}
    });
	}
}).on('select', ({index}) => {
  console.log('selected item: ' + index);
	let page = new Page({title: menuItems[index].title}).appendTo(navigationView);
})
```

**Comment by mpost** [comment]
This is a know issue on Android smaller than 6.0. The `highlightOnTouch` consumes the touch feedback. Please put the `highlightOnTouch` on the a sibling of the cell and not directly on the cell.

**Comment by maoamid** [comment]
@mpost I suspected also that is related to the known problem you said, but I report this issue because it's strange to use 'highlightOnTouch' to catch 'select' event. In my app because of the known problem I disabled highlightOnTouch globally on Android smaller than 5.0 (you confirm that I should use <6.0). but now I have to use those little hacks.
There is also a second issue: if you double tap on imageView, the image is zoomed. Can you confirm? I should open another issue?

**Comment by mpost** [comment]
The `select` event on the `CollectionView` was historically not a good idea which causes several problems. We are considering deprecting it in a future Tabris major release.

Regarding the zoom feature on the `ImageView`: This is a feature still under development in the nightlies and will be off by default. The full API will be part of the next release.

**Comment by cpetrov** [comment]
@maoamid The nightly you use (20180216) has an issue which causes all ImageViews to be zoomable and to steal tap events. Try using the latest tabris-js nightly, there the issue has been solved. Please reopen if you still have problems.
