### ISSUE TITLE
tabris-cli re-build error

### ISSUE THREAD

**Issue by gacal** [eclipsesource/tabris-js#1592]
### Problem description

1. tabris build android
first build no problem but re-build problem

### Environment

- Tabris.js version: 2.3.0
- Cordova Version : 8.0
- Device: Huawei Mate 10 Lite
- OS: android

<img width="1169" alt="ekran resmi 2018-02-27 22 54 29" src="https://user-images.githubusercontent.com/3254134/36754294-a588079c-1c19-11e8-8bf5-9410a4fa628e.png">

**Comment by mpost** [comment]
What commands did you run on the tabris cli?

**Comment by gacal** [comment]
tabris run android and tabris build android...

same result

**Comment by cpetrov** [comment]
@gacal Which Tabris CLI version do you use? `tabris -V`

**Comment by gacal** [comment]
versiyon 2.1.1

**Comment by cookieguru** [comment]
@gacal Update to 2.3.0: `npm update -g tabris-cli`

**Comment by jonek** [comment]
Could you resolve the problem in the meantime?
If not, maybe you can give version 2.4.0 of the CLI a try: https://www.npmjs.com/package/tabris-cli

**Comment by mpost** [comment]
Closing as resolved.
