### ISSUE TITLE
Online build error - After a long time i built

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1593]
### Problem description

Unable to build a source repository (though no code changes, no plugins added etc), but it fails to build. Last time the same repository was build in Dec without any error

### Expected behavior

Expected the build to pass
### Environment

- Tabris.js version: 2.0.x
- Device: NA
- OS: Android OS

### Code snippet from package.json

```javascript
{
  "main": "src/index.js",
  "dependencies": {
    "tabris": "2.0.x",
    "underscore": "^1.8.3"
  }
}
```

**Comment by natanraj** [comment]
Additonal Inputs: Build environment created 5a992be1ee64b0e4fb46c190

Build log is not showing any traceable error (to my knowledge), except the below

$ travis_wait 40 grunt build deploy
Still running (1 of 40): grunt build deploy
Still running (2 of 40): grunt build deploy
The command grunt build deploy exited with 6.

**Comment by jonek** [comment]
@natanraj did you trigger that failing build again to see if the problem is reproducible?

**Comment by natanraj** [comment]
Yes, three times so far

**Comment by natanraj** [comment]
@jonek Any help here is appreciated. Were there new build guidelines released which i could have missed. Please highlight them if any. I am eager to see my app surviving

**Comment by natanraj** [comment]
@mpost @ralfstx - hi.. I am extremely sorry guys if I am spamming you all. I am having this issue for last 3 weeks and delaying my development & app push. Any help on what mistake i am doing and how to rectify it, is highly appreciated. I am having difficulties in understanding the issue from the detailed build log. I have tried various permutations of changing the package.json, tabris.js client version etc. Not so successful.

Build environment created 5aa6691eee64b0e4aa64c190

**Comment by fwaibel** [comment]
@natanraj We removed the `travis_wait 40`. This seems to truncate the build logs in some cases.

**Comment by natanraj** [comment]
@fwaibel thanks. not it gives some hint why the online build failed as below

`> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 10.2.1.
* Tr`

I checked my google-services.json, couldn't find anything there about the version. I am using firebase plugin as below. Should i have to upgrade this to next version?
`<plugin name="tabris-plugin-firebase" spec="^1.0.0" />`

**Comment by mpost** [comment]
@natanraj the version on npm is a little older. i'd recommend to consume the firebase plugin from the github master branch atm.

**Comment by natanraj** [comment]
@mpost & @fwaibel : i got misled by google-services. it is infact failing from tabris-maps plugin. It was taking very latest and my plugin was failing due to this. I reverted to tag v3.0.x and it is working now. Thanks a lot for all your support.
