### ISSUE TITLE
Run in background

### ISSUE THREAD

**Issue by arjunmenon** [eclipsesource/tabris-js#1594]
Hey
Does tabrisjs apps have the ability to run in background?
For example, I have seen in my phone the native Music player never stops the whole night, even when back is pressed or screen is locked. It keeps playing music. So is it possible to achieve this with tabris apps, where the app only stops if we press an exit button or swipe it from the multitasker? Else, how can we do that?

**Comment by cookieguru** [comment]
Is your goal to play music or something else?

**Comment by arjunmenon** [comment]
I have a web server which I want to run. It would listen to incoming requests and serve files from phone over network. I have integrated that in a cordova plugin.
At present it works fine if the app is active. But when it is locked or phone sleeps, it stops listening to requests.

**Comment by cookieguru** [comment]
This is not something you should count on; Android has made [significant changes to background processes in newer versions](https://developer.android.com/about/versions/oreo/background.html) so any solution wouldn't work once you start targeting newer OSes.
A more effective solution would be to have your workers notify a central service and have that central service push notification out to your clients.  With [tabris-plugin-firebase](https://github.com/eclipsesource/tabris-plugin-firebase) you can do just that.

BTW general purpose questions are better suited for the [slack channel](https://tabrisjs.herokuapp.com/)

**Comment by mpost** [comment]
We are planning to support a WebWorker style background execution in Tabris.js 3.0. Please follow https://github.com/eclipsesource/tabris-js/issues/358. Closing this for now.
