### ISSUE TITLE
Linear Gradient Composite

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#1596]
### Problem description

It would be nice to be able to render a linear gradient composite. 

### Prior Art

https://github.com/react-native-community/react-native-linear-gradient

You can see here, react native has a plugin for simply displaying a linear gradient where you would normally display a view. It may even be possible to use the guts of this plugin as the implementation.

**Comment by mpost** [comment]
Adding support for linear gradients is very high on our list. Please stay tuned.

**Comment by mpost** [comment]
We have added support for linear-gradients on the `Widget` `background` property for the upcoming 2.5 release.
