### ISSUE TITLE
Documentation on website: several broken links

### ISSUE THREAD

**Issue by mrmccormack** [eclipsesource/tabris-js#1601]
I'm sure enjoying learning Tabris.js  -  **it's amazing.**

---
### Problem description

- looks like docs were recently moved to another folder...

- There are several broken links  and images at:
- https://tabrisjs.com/documentation/latest/

> Example
- bottom of page https://tabrisjs.com/documentation/latest/ the link to  follow the Quick Start Guide. It links to 404 error at: https://tabrisjs.com/latest/getting-started.html and should be https://tabrisjs.com/documentation/latest/getting-started.html

- many images are broken with the same trouble with path... i.e.https://tabrisjs.com/documentation/latest/api/Button.html  images are broken

> This might be  helpful:
- https://www.drlinkcheck.com/results/5feb67/1/broken

Thanks. R.

**Comment by mpost** [comment]
Thanks for the heads up. We will investigate the issue.

**Comment by mpost** [comment]
Links should work as expected now.
