### ISSUE TITLE
appendTo() does not bring pages to the top of the NavigationView stack

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1602]
### Problem description
Calling `appendTo()` on a page in the navigation view stack does not bring it to the top of the stack.

### Expected behavior

When called on a page already in the navigation view, `appendTo()` should remove it from the navigation view and append it to the top of its stack.

### Environment

- Tabris.js version: 2.4
- Device: iPhone 6
- OS: 11.2.6

### Code snippet

In the following code snippet, tapping on _Open page 1_ does not result in Page 1 being shown on iOS. 

```javascript
const {Button, NavigationView, Page, ui} = require('tabris');

let navigationView = new NavigationView({
  left: 0, top: 0, right: 0, bottom: 0
}).appendTo(ui.contentView);

let page1 = new Page({
  title: 'Page 1'
}).appendTo(navigationView);

new Page({
  title: 'Page 2'
}).appendTo(navigationView);

new Page({
  title: 'Page 3'
}).append(
  new Button({centerX: 0, centerY: 0, text: 'Open page 1'}).on({tap: () => {
    page1.appendTo(navigationView);
  }})
).appendTo(navigationView);
```

**Comment by karolszafranski** [comment]
fixed in: https://github.com/eclipsesource/tabris-ios/commit/2c2a44b224ff33cfcc6e03f52c5f8d51e182fa2a
