### ISSUE TITLE
Actions reusing images are not shown

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1603]
### Problem description

When creating several actions using the same image, actions appended to the NavigationView after the first one are not being shown.

### Expected behavior

It should be possible to create actions with the same image. This is particularly useful when using a  e.g. tab folder containing tabs with navigation views showing the same actions.

### Environment

- Tabris.js version: 2.4.0
- Device: iPhone SE
- OS: 11.2.6

### Code snippet

Replace the `navigationview-action` snippet:

```javascript
const {Action, NavigationView, ui} = require('tabris');

let navigationView = new NavigationView({
  left: 0, top: 0, right: 0, bottom: 0,
  background: '#e7e7e7'
}).appendTo(ui.contentView);
new Action({image: {src: 'resources/share-black-24dp@3x.png', scale: 3}}).appendTo(navigationView);
new Action({image: {src: 'resources/share-black-24dp@3x.png', scale: 3}}).appendTo(navigationView);

```

**Comment by patrykmol** [comment]
Fixed in https://github.com/eclipsesource/tabris-ios/commit/773e275e44ca31c844dc76388576d190dd4a3e52.
