### ISSUE TITLE
Problem with Ios Build(Rsync failed)

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1605]
Impossible to build a ios app 
TabrisJS 2.4.1
the log file say : step failed: : Error Domain=IDEFoundationErrorDomain Code=1 "Rsync failed" UserInfo={NSLocalizedDescription=Rsync failed}
error: exportArchive: Rsync failed

**Comment by cookieguru** [comment]
https://tabrisjs.slack.com/archives/C0AQ5BK36/p1521920161000146

**Comment by ishigo1987** [comment]
thank you for the link

**Comment by ishigo1987** [comment]
any answer?the problem is still on the table

**Comment by jonek** [comment]
@ishigo1987 are you able to create a local build of this app for iOS?

**Comment by jonek** [comment]
@ishigo1987 to confirm that your iOS build is working fine, please close this issue.
Thanks!
