### ISSUE TITLE
Online Build error

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1607]
Seeing Cloud build throwing error. it was working until yesterday. Below is the error in the logs

> * What went wrong:
> A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:2.3.1.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:2.3.1.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.1/gradle-2.3.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.1/gradle-2.3.1.pom'. Received status code 500 from server: Internal Server Error

**Comment by mpost** [comment]
When did you trigger the build? Could you please retrigger it?

**Comment by natanraj** [comment]
@mpost even now it fails

**Comment by mpost** [comment]
What tabris version are you targeting?

**Comment by mpost** [comment]
Atm there is also a download error at jcenter so that dependencies can not be downloaded: http://status.bintray.com/

**Comment by natanraj** [comment]
@mpost I am doing the Online build with 'latest' chosen in the settings drop down. For package.json i have 2.0.x.

This build was working previous day and I haven't changed anything on the settings/packages/plugin. So i will keep fillowing up on the status.bintray.com too.  thanks.

**Comment by natanraj** [comment]
@mpost I guess it is resolved and I am able to build now. Thanks for all the support
