### ISSUE TITLE
Question: what is available from which version

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1609]
Hi.. I am working with Tabris.js for last 16 months and it has come of ages. Is there a single place where we can see which is introduced in which major version onward ? For ex. I feel tabris2.0.x doesn't have ActionSheet.  Just like that new capabilities are available in various multiple upgrades. Wanted to see this in a single source of truth. Just a suggestion

**Comment by cookieguru** [comment]
Try the [https://github.com/eclipsesource/tabris-js/releases](releases) page

**Comment by natanraj** [comment]
Yeah, thanks. But it shows 404 page error.

**Comment by mpost** [comment]
Works fine for me as well: https://github.com/eclipsesource/tabris-js/releases

**Comment by natanraj** [comment]
Thanks. It worked
