### ISSUE TITLE
Put snippets on top of the documentation articles

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1615]
### Problem description

Currently, snippets appear on the bottom of the documentation articles. This makes them hard to notice, although they often provide a simple entry point into the API: a reusable code snippet, which can be copied, pasted and customised in the user code.

### Expected behavior

Put the snippet on the top of the article in a collapsed widget expanding on click, which initially only reveals 3-4 lines of the code (e.g. fading to the page background color) to reduce the taken vertical space.

**Comment by mpost** [comment]
We are able to provide "copy and pastable" snippets in a extra doc file which is inserted right at the top. Eg.  https://github.com/eclipsesource/tabris-js/blob/master/doc/api/device.md is used here http://docs.tabris.com/latest/api/device.html#device

**Comment by tbuschto** [comment]
Done
