### ISSUE TITLE
Provide a visual index of UI widgets

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1617]
### Problem description

Some widgets may be known under several names. E.g. a _picker_ may be known as a _dropdown_ or a _spinner_. 

### Expected behavior

Provide a visual gallery index listing all supported UI widgets to help the user identify his desired widget easily.

**Comment by mpost** [comment]
List of widget would be great. It should be generated from existing screenshots (animated would be great) and contain the "copy/paste" snippet and link to docs.

**Comment by mpost** [comment]
The widget indes page has been created.
