### ISSUE TITLE
Rework Action placementPriority on iOS

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1618]
### Problem description

Currently, the Action's `placementPriority` presents different UI on Android, Windows and iOS. On Android and Windows, actions with low placement priority appear in an overflow menu, which is only shown when tapping on the `...` icon, while actions on iOS appear in a bar on the bottom of the navigation view, which is always shown.

The iOS solution has several problems:

* Placing the actions in a bar, which is always visible on the bottom of the page is conceptually different than hiding the actions in an overflow menu.
* Left-alignment of toolbar icons makes the UI look asymmetrical, the buttons are hard to reach with the thumb and this alignment is untypical for iOS toolbars. [Toolbar](https://developer.apple.com/ios/human-interface-guidelines/bars/toolbars/) icons are usually evenly distributed.
* It causes visual clutter when using a TabFolder based navigation (i.e. TabFolder with a `tabBarLocation` set to `"bottom"`), although this would work fine on Android when using an overflow menu. This is discouraged by Apple's UX guidelines: [_Toolbars and tab bars never appear together in the same view._](https://developer.apple.com/ios/human-interface-guidelines/bars/toolbars/)

#### Proposal 1:

Align behavior with Android. Show a `...` button on iOS as well and use it to open an action sheet containing the low priority actions. 

This pattern is used in some native iOS apps like Pages and the App Store:

|Pages|App Store|
|---|---|
|![img_3e31eb45aff9-1](https://user-images.githubusercontent.com/2341769/38253749-c2e6a36c-3757-11e8-981f-d72efc7ada03.jpeg)|![img_5bd1df7138b7-1](https://user-images.githubusercontent.com/2341769/38253863-0a3eff98-3758-11e8-8954-9f99dbc8f556.jpeg)|

#### Proposal 2: 

Keep the bottom bar on iOS, but evenly distribute its icons.

**Comment by mpost** [comment]
While not necessarily a breaking change, if we implement this behavior we should do it for 3.0 so that we can remove the then outdated property [bottomtoolbarheight](http://docs.tabris.com/latest/api/NavigationView.html#bottomtoolbarheight).
