### ISSUE TITLE
Customize ActionSheet presentation on the iPad

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1621]
### Problem description

On iPads, the ActionSheet appears as a centered [popover](https://developer.apple.com/ios/human-interface-guidelines/views/popovers/) without an arrow. 

### Expected behavior

There should be an API which enables customising its position on the screen and showing/hiding the popover arrow. Maybe provide API to give a widget reference or an absolute screen position the ActionSheet should be pointing to.

**Comment by mpost** [comment]
With the introduction of the `Popover` in Tabris.js 2.5 the position of a "dialog" is now possible on the iPad. Closing as "resolved".
