### ISSUE TITLE
Customize the navigation action of the NavigationView

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1622]
### Problem description

Currently, the left part of the toolbar of the NavigationView shows either a back button, a drawer button or empty space. 

Modal views on iOS and Android typically display an action of the left side of their title bar, which is used for dismissal.

|iOS|Android|
|---|---|
|![](https://cloud.githubusercontent.com/assets/2341769/12609589/f8ae7eaa-c4e2-11e5-9ba9-6694a5fd4e45.png)|![](https://cloud.githubusercontent.com/assets/2341769/12609594/050542b0-c4e3-11e5-938e-ddca02a2e4ec.png)|

Currently, it is not possible to show such a button in the title bar of the NavigationView.

### Expected behavior

Introduce an API to replace the default behavior (showing a drawer or a back button) by showing a custom action in the left part of the NavigationView titlebar.

This could be a property called `navigationAction` of type `Action` on the `NavigationView`.

**Comment by tbuschto** [comment]
Supported in 2.5
