### ISSUE TITLE
broken link to ebook - website issue

### ISSUE THREAD

**Issue by mrmccormack** [eclipsesource/tabris-js#1625]
Website issue:

https://tabrisjs.com/documentation/latest/
at bottom of page - link to ebook
*We also have an excellent ebook that explains...*

ebook link:
https://tabrisjs.com/downloads/
broken....

It used to work, and I liked the ebook very much

R

**Comment by cookieguru** [comment]
Looks like it's off by a letter

https://tabrisjs.com/download/

**Comment by cpetrov** [comment]
@mrmccormack Good catch!

@cookieguru Thank you for the PR! We will publish the updated documentation as part of the next Tabris.js release.
