### ISSUE TITLE
Is it possible to save camera photo to device Photos -( for Playground tutorial)

### ISSUE THREAD

**Issue by mrmccormack** [eclipsesource/tabris-js#1630]
### Problem description

- For a tutorial, for my students, I have simplified the Cordova camera example and it that works on **Playground**
- Code is below (still testing on Android, works on iPhone from Playground)
- Code is a simplified example of the https://github.com/eclipsesource/tabris-js/blob/master/examples/cordova/CameraPage.js which took me a while to understand as it shows many cordova examples all at once. (requires 3 pages)

> Question:
- **Is it possible to save the photo to the device Photos ?** If so.. is there a simple working example I can study?
- I know I can save to the storage area on the device 
- My research turned up stuff 3 years old, like: https://github.com/eclipsesource/tabris-js/issues/556 etc. 
- I do see a `saveToPhotoAlbum` on https://www.npmjs.com/package/tabris-plugin-camera
- if I get this work work, I'll make another tutorial on it... Many thanks for a great dev tool!

---

### Environment
- Tabris.js version: 2.4 
- OS:  iOS 10.3.1 or Android 7.1

---

### Tutorial Code snippet
- this will take photo, but not save it anywhere.
- pretty amazing how short it is.

```javascript
const { Button, ImageView, ui } = require('tabris')

const widthPhoto = 300
const heightPhoto = 400

function takePhoto () {
  let onSuccess = image => imgPhoto.image = image
  let onFail = message => console.log('Camera failed because: ' + message)
  navigator.camera.getPicture(onSuccess, onFail, {
    quality: 50,
    targetWidth: widthPhoto,
    targetHeight: heightPhoto,
    destinationType: window.Camera.DestinationType.FILE_URI
  })
}

let btnShutter = new Button({ centerX: 0, top: 40, text: 'Take Picture' })
  .on('select', () => {
    takePhoto()
  }).appendTo(ui.contentView)

let imgPhoto = new ImageView({
  top: 'prev() 10',
  class: 'image',
  width: widthPhoto,
  height: heightPhoto,
  centerX: 0,
  image: 'https://raw.githubusercontent.com/mrmccormack/imd-learning-tabris/master/images/photo.png',
  scaleMode: 'fit',
  zoomEnabled: true
}).appendTo(ui.contentView)
```

**Comment by patrykmol** [comment]
It should be possible. You need to set `CameraOptions.saveToPhotoAlbum` to `true` and pass the options when invoking `getPicture()`.
https://www.npmjs.com/package/tabris-plugin-camera#module_camera.CameraOptions
You also need to set `NSPhotoLibraryUsageDescription` with a description in your app's `.plist` file.

**Comment by mrmccormack** [comment]
Hey thanks... exactly what I needed.  And this code works on Playground.

```js
const { AlertDialog, Button, ImageView, ui } = require('tabris')

const widthPhoto = 300
const heightPhoto = 400
const IMGURL = 'https://raw.githubusercontent.com/mrmccormack/imd-learning-tabris/master/images/'

function takePhoto () {
  let onSuccess = image => {
    imgPhoto.image = image;
    new AlertDialog({
    message: 'Your photo is saved to Photos',
    buttons: {ok: 'Ok'}
  }).open();}
  
  let onFail = message => console.log('Camera failed because: ' + message)
  navigator.camera.getPicture(onSuccess, onFail, {
    saveToPhotoAlbum: true,
    quality: 50,
    targetWidth: widthPhoto,
    targetHeight: heightPhoto,
    destinationType: window.Camera.DestinationType.FILE_URI
  })
}

let btnShutter = new Button({ centerX: 0, top: 40, text: 'Take Picture' })
  .on('select', () => {
    takePhoto()
  }).appendTo(ui.contentView)

let imgPhoto = new ImageView({
  top: 'prev() 10',
  class: 'image',
  width: widthPhoto,
  height: heightPhoto,
  centerX: 0,
  image: IMGURL + 'photo.png',
  scaleMode: 'fit',
  zoomEnabled: true
}).appendTo(ui.contentView)

```

**Comment by mrmccormack** [comment]
I just added the ability to perform simple edit once photo is taken with one line:

```js
let onFail = message => console.log('Camera failed because: ' + message)
  navigator.camera.getPicture(onSuccess, onFail, {
    saveToPhotoAlbum: true,
    allowEdit: true,
    quality: 50,
    targetWidth: widthPhoto,
    targetHeight: heightPhoto,
    destinationType: window.Camera.DestinationType.FILE_URI
  })
}
```

I think I will do a more advanced version with many features as a tutorial.

**Comment by mpost** [comment]
Nice addition. Will close this issue for now.
