### ISSUE TITLE
Append JSX from array

### ISSUE THREAD

**Issue by bryantee** [eclipsesource/tabris-js#1634]
In React you can render an array of JSX items like so:

```javascript
function renderImages(props) {
  const items = props.images.map(image => <Image source={{uri: image.url}} />);

  return (
    <View>
      items
    </View>
  )
}
```
It would truly make the code much more composeable if we could do something similar in Tabris.

**Comment by tbuschto** [comment]
I'm trying to understand what it is that you want specifically that doesn't work in in Tabris.js.

I'm using TypeScript here, JS would work as well.

Assuming a setup like this:
```ts
const images = [
  {url: 'http://lorempixel.com/400/200/sports/1/'},
  {url: 'http://lorempixel.com/400/200/sports/2/'},
  {url: 'http://lorempixel.com/400/200/sports/3/'}
];
```
(lorem pixel is currently painfully slow for me, maybe use another source.)

You could do write function that can be called directly generate image views:
```
function renderImages(props: {images: Array<{url: string}>}) {
  return props.images.map(image => <imageView image={image.url} top='prev() 0'/>);
}

const view: Composite = <composite left={0} top={0} right={0} bottom={0}/>;
ui.contentView.append(view);
view.append(renderImages({images}));
```

Or you could write a stateless functional component that does the same:

```ts

function RenderImages(props: {images: Array<{url: string}>}) {
  const items = props.images.map(image => <imageView image={image.url} top='prev()'/>);
  return new WidgetCollection(items);
}

ui.contentView.append(
  <composite left={0} top={0} right={0} bottom={0}>
    <RenderImages images={images}/>
  </composite>
);
```

What doesn't work right now is this syntax:
```ts
  return (
    <widgetCollection>
      items
    </widgetCollection>
  );
```
Though that could be fixed i think.

Of course this is a one-time rendering, if automatic incremental updates is what you want, (like ` ReactDOM.render`), this is currently not possible. It's something we are considering for 3.0, but we may also be going a different way entirely.

**Comment by tbuschto** [comment]
Ah, should have looked at the title again. You want to have that 
`<view>array</view>`
syntax. That I can probably do.

**Comment by tbuschto** [comment]
@bryantee I'm more experienced with XAML, so a virtual dom is rather alien to me. I'm not sure why it's so popular, maybe you can enlighten me? I see it's use for rendering something like lists, but that's a special case in Tabris.js considering that CollectionView works very differently. But since there is already some groundwork by dested I would consider adopting that project.

Anyway, here's what I have been working on for : https://github.com/eclipsesource/tabris-decorators/blob/master/doc/data-binding.md That would be the "different way". It's basically ready for a 1.0, still working on the tutorials.

**Comment by bryantee** [comment]
Thanks for the details, I'll take a closer look when back at my computer. Two-way binding is certainly a big improvement over what's current. 

As for the advantages to a virtual-dom, I'd say essentially it lets your re-render a page whenever there's a change to state, but then the vDom diff checks and only updates what is actually necessary in the view.

**Comment by cookieguru** [comment]
@bryantee That is essentially what the `CollectionView` does.  If the viewport is able to show 10 cells, and there are 100 items in the list, when you call [refresh](http://docs.tabris.com/latest/api/CollectionView#refreshindex) (with or without the optional index parameter) only the 10 visible cells are updated.  The others would update (or more accurately: render) once they become visible.  The cells themselves are actually re-used as you scroll up and down the list.

**Comment by bryantee** [comment]
@cookieguru I totally see that, and we make use of CollectionView when we have a long list of things. It'd be fantastic if this existed across the framework. It's power because it's declarative. I want to update the state, I don't have to worry about what happens after that.

**Comment by tbuschto** [comment]
@bryantee  I'd like to see an example where vDom accomplishes something that you couldn't do with traditional one- or two-way bindings (once we support converters, binding to models/other widgets, etc...). I'd be willing to go with a vDom-like approach instead or in addition, I'm just not sure it's worth the effort. Calling refresh explicitly seems like a hassle to me.

@cookieguru With 3.0 (after 2.5 or 2.6) I would like to provide some kind of (non-breaking) update or external extension for `CollectionView` with some kind of automatic change detection. No calling to `refresh`/`insert`/`remove`.

**Comment by tbuschto** [comment]
Okay, I see now that adding/removing widgets in some non-`CollectionView` page/form is difficult without vDom. I'll think about that.

**Comment by cookieguru** [comment]
@tbuschto I'm looking forward to that!

**Comment by bryantee** [comment]
@tbuschto

Question. We're often using a pattern where we create custom class components that extends composite and we'll store properties on the class. Currently when some part of state updates, we either rely on imperative code to dive down and update various components or rely on callbacks to do that for us. How could we do a 2-way bind to some model to react to a change in state somewhere higher up the tree?

**Comment by tbuschto** [comment]
@bryantee With the extension I linked (`tabris-decorators`) you can currently create bindings (via JSX) to a plain property (e.g. `name`), what you would need (and what's planned as one of the next features) is to also allow to bind to a property path, (e.g. `person.name`). In the project that this feature originated with we used a model-view-presenter pattern, so the model never touched the view and the problem didn't exist. What you can currently do as a workaround is to have one model property e.g. 'person' with a imperative setter that splits the model in to several protected (or private) properties that you can bind to. 

Here's how that could look like: (I'm just writing this on the fly, so maybe there are minor mistakes, but the concept has been test IRL):

```ts
@composite
class SomeView extends Composite {

  public set person(value: Person) {
    this._person = value;
    this.set(value); // assuming value only has properties supported by the view
  }

  public get person() { return this._person; }

  @property protected age: Number;
  @property protected name: string;
  private _person: Person;

  constructor() {} // the JSX part with the bindings according to the documentation

```

I'm off for a few days. If you want to test `tabris-decorators`, there's a setup guide: 
https://github.com/eclipsesource/tabris-decorators/blob/master/doc/setup.md

**Comment by bryantee** [comment]
Thanks @tbuschto. This is super interesting. Enjoy the days off.
