### ISSUE TITLE
Feature Request: Using Tabris.js developer app (TDA) for corporate custom apps

### ISSUE THREAD

**Issue by mrmccormack** [eclipsesource/tabris-js#1635]
**TDA** = Tabris Develop App
- *not to be confused with apps build, compiled and distributed apps on stores or other means*

### General Inquiry about TDA's for small corporate apps

- I wasn't sure if I should post to https://tabrisjs.slack.com, or here.
- Perhaps I don't fully understand the plans for the future of Tabrisjs, or if this feature already exists.

-  I know I can run a TDA from a bar code on the net,  or from a URL or I place into the TDA,  which is great and I'm sure enjoying the https://tabrisjs.com/playground - I can even run my apps from a local server link and share over private network.

- Say, I have written an app and want to give users a convenient way to launch it on their mobile device. Yes, I know it's pretty easy to launch a custom URL inside of TDA, but it doesn't take much to mix users up and teaching them to navigate through menus which have nothing to do with the specific app may be tricky for some monkeys :) Say, this app is not overly concerned with security.

### Q:
- Is it possible to simply put a URL link (on a company intranet), and users can simple click on it to launch the TDA on their mobile device? Without them first launching the TDA on their device.

- This is exact same functionally that when I click on a YouTube link, it launches my YouTube app.
- The way I think it works now, I think, is that URLs / Barcodes must be launched while inside TDA

- Also, if a user launches a custom app by this method, and the link that the app came from matches an embedded URL in the app - **then** this app will be come the default app for TBA, and anytime the user again launches the TDA, this app will load automatically (like index.*  does on any websites) - If the user must use other TDA apps, they can swipe to bring up all the features and console of TDA.

If this isn't clear... here is...
### Example in the wild:

- Say a small company, with very little resources for writing custom apps and no intention of publishing apps, wants to create a **minimal app** that simple does the following

**COMPANY XYZ - Incident Report App**

- they want their few employees, to be able to file an **incident report** with their mobile device by simply installing the TBA, and launching it via an email, or intranet link.

- the report must contain 4 Photos taken in  a certain way **and** only 50% quality, no need for the highest default quality on their phones.

- under each photo, a 100 word max. description

- a few check boxes to categorize the nature and priority of the incident

- a place for their "digital" and legally binding signature.

- everything time stamped.

-  using webview, in a TabFolder containing a private Google Doc for procedures to follow.

- When they fill it all in, they press a button and it's wrapped up in an email and send, or posted somewhere, or a PDF is generated emailed.  A text message could be generated and send a summary notice alert to their boss.

----

I think I could write this app in less than a week with Tabrisjs, and fully test in in another week. I've only being learning Tabris for a few months in my spare time.

I know of no other way (for me at least) to achieve a useful corporate private app in 2 weeks.  Before I stumbled upon Tabris, I was quite sure it would take me a year+ for learning, testing, and distribution.

Also, I haven't tried the update feature of Tabris, but that really appeals to me. Once the user has the custom app on their phone, it is SO EASY to update. Or the URL link could simply be updated to contain the latest version. I was surprised that Apple's lawyers and Store policies permitted this, but they do, and they put it in writing.

---

Just wondering if this functionality is something that will be promoted for the TBA in the future. The functionality of the TBA should be easy I think. It must be done inside of the TBA, as I have no way to control this simple functionality outside of the TBA in apps I write.

I think I'll write a tutorial
**Incident Reporting App with Tabrisjs**

I'll write a simple version that runs on Playground, and another with several NPM packages to do the heavy lifting.

 It would be great fun to try to make an app that others could freely use or learn from. (even if TDA never gets the functionality I have discussed)

- thanks!  Rob

**Comment by cookieguru** [comment]
I'm a member of the community and not part of the development team, so I can't comment on the roadmap, but hopefully can provide some useful information nonetheless.

Apologies if you already know the distinction, but there's a difference between _the_ Tabris.js Developer App (the one that can be downloaded in the three app stores) and an app built with the developer console.  They work the same, but have two differences:
* The one you refer to as the TDA ships with example code and a few plugins
* An app built with the developer console ships with your code and the plugins you choose

The scratchpad was built with the intent of allowing you to quickly test out snippets of code.  It lacks several features for full fledged development, namely the ability to load custom modules (npm) and any plugins not bundled with the developer app.  So if you want to embed a map, you'll have to roll your own build.  It's quite easy with the cloud build; you need only a few lines of code in a couple of files to kick one off.  If you build your app with the developer app enabled you still have the ability to reload code off your local development server.  Once you feel like you're in a good enough state for a beta, you can run a build off that and ship that binary to a client.  This is pretty easy if the client has an Android or a Windows device, but alas Apple throws a few hurdles in your way (chiefly a subscription requirement).

When building your own app, you can use the [cordova-universal-links-plugin](https://github.com/nordnet/cordova-universal-links-plugin) to deep link to any spot in your app--or even just make a specific URL open the app.  This is exactly what the YouTube app does.  (aside: on Android you can actually pull up the app details and disable this functionality if you want to keep using the HTML player).  Setting your own app up for deep links could theoretically use the [patch](http://docs.tabris.com/latest/patch.html) functionality to dynamically run multiple release candidates (though I would tread lightly in regards to Apple's license agreement).

I agree that it would be handy if the Developer App could be coded to open the [public scripts](https://tabrisjs.com/public/scripts), it'd be quite handy to send someone a link to download the Developer app in one of the app stores and a second link to bring up the exact functionality I'm trying to demonstrate, of course being subject to the aforementioned limitations that the scratch pad has.

With your example though, it sounds more a webpage could handle that task without any overhead of installing a separate app.

**Comment by mpost** [comment]
I can fully confirm the explanation given by @cookieguru. The distinction between the Tabris.js app in the store and your own app is an important one to make in terms of custom plugins and npm modules. 

For your use-case you will want to use a combination of plugins and node modules so a custom app that can be downloaded is the best approach for you. The cordova-universal-links-plugin is also a valid method of achieving the link interception that you described.

**Comment by mrmccormack** [comment]
Thanks all for taking the time to offer help.  I'll continue to learn TabrisJS. You can close this ticket if you think it doesn't belong in OPEN TICKETS. 

Maybe others can easily get things on the Apple App store- I'm not one of those, I was a Apple Developer $100 US, for a few years with nothing on the App store (Desktop apps in Objective C). 

I am aware of Google's  *Progressive Web App* - which have the advantage of "NO STORE INVOLVED" - and that started me thinking about Tabrisjs TDA. PWA's may change the way we think about the importance of App stores. I don't pretend to know the future.

Maybe slack.com is a better place for me too post to if things  don't involve bugs etc . Thanks again, Rob

**Comment by mpost** [comment]
The idea to not rely on a store is interesting in the PWA approach but it is also a rather new concept for many people. The trust in a store installation is usually pretty high. Also not every use case needs an app. Sometimes a mobile webpage is good enough. Especially when the interaction is not frequent.

i'll close the issue for now but please feel free to bring up new ideas in a new issue or the slack channel. 👍
