### ISSUE TITLE
Docs: Suggestion to Device example code

### ISSUE THREAD

**Issue by mrmccormack** [eclipsesource/tabris-js#1636]
**Suggestion:** 
- Modifications to the example: http://docs.tabris.com/latest/api/device.html to include more properties.
- works on playground

---

`device.js` 

```js
const {TextView, device, ui} = require('tabris');

// Display available device information
let propertyList = ['platform', 'version', 'model', 'vendor', 'language','orientation', 'screenWidth', 'screenHeight', 'scaleFactor']

propertyList.forEach(property => {
  new TextView({
    id: property,
    left: 10,
    right: 10,
    top: 'prev() 10',
    markupEnabled: true,
    text: property + ': <strong>' + device[property] + '</strong>'
  }).appendTo(ui.contentView)
})

device.on('orientationChanged', () => {
  propertyList.forEach(property => {
    ui.contentView
      .find('#' + property)
      .set('text', property + ': <strong>' + device[property] + '</strong>')
  })
})

```
---

 I test my apps on 2 iPhones, Android phone and tablet, and this provides useful information at a glance, as I am beginning to understand Device Independent Pixels and other things.

Thanks, Rob

---

`iPhone Screenshot`

![img_5668](https://user-images.githubusercontent.com/3249215/39191130-30676c76-47a4-11e8-9312-bbea767b908e.PNG)

---

**Comment by mpost** [comment]
Sounds reasonable. Could you open a pull request for it?

**Comment by mrmccormack** [comment]
I sure can submit a pull request...  I'll test on a couple iPhones, Androids and my Windows 10 machine first.

> NOTE:
- I made a few improvements/simplifications, and  I will add the ; to be consistent with your docs.
- I wrote this with submitting GitHub issues in mind (TextInput.text may be selected and copied and pasted into GitHub Issues, in suggested Issue format)
- Works on Playground, or QR, or link 
- I'm sure enjoying learning about Tabris and all its potential.

### LINKS:
- https://tabrisjs.com/api/v1/pins/5ae5025bee64b0e4dfbcc190
- https://tinyurl.com/tabris-device

**via QR CODE**:
![qrcode](https://user-images.githubusercontent.com/3249215/39406656-0a099666-4b88-11e8-98b3-fa06e70120d4.png)


### CODE

```js
const { app, device, TextInput, ui } = require('tabris')

// Display available device information for submtting issues
let propertyList = ['platform', 'version', 'model', 'vendor', 'language', 'orientation', 'screenWidth', 'screenHeight', 'scaleFactor']

const version = 'Tabris.js version: ' + app.version + '\n'

let txiList = new TextInput({
  left: 10, right: 10, top: 'prev() 10',
  type: 'multiline'
}).appendTo(ui.contentView)

function getProperties () {
  txiList.text = '### Environment \n' + version
  propertyList.forEach(property => {
    txiList.text = txiList.text + property + ': ' + device[property] + '\n'
  })
}

getProperties()

device.on('orientationChanged', () => {
  getProperties()
})


```


![device-properties](https://user-images.githubusercontent.com/3249215/39406638-b5b370a0-4b87-11e8-8379-bbe3af9d0a9d.png)

**Comment by mpost** [comment]
We have added more properties in the device snippet.
