### ISSUE TITLE
Basic question... runnning Tabrisjs from URL on my own domain

### ISSUE THREAD

**Issue by mrmccormack** [eclipsesource/tabris-js#1637]
I see I can run the default Playground app, from a Public URL (pinned).
- https://tabrisjs.com/api/v1/pins/5ae0cff3ee64b0e448b9c190

- I want to host a simple Tapris app on http://myowndomain.com/tabrisjs/demo  

**Question**
- Is it possible, what files / directory structure  are required?

- Ideally, I would like this to run from a Github public repository if possible

- I know about http://docs.tabris.com/latest/build.html 

- I assume the Examples are running from a public URL in the Tabris Dev. App.

- Any help with such a basic question is appreciated, thanks - Rob

**Comment by cookieguru** [comment]
> Is it possible, what files / directory structure are required?

Yes.  It requires the same directory structure as what you have when you run it on your LAN

> Ideally, I would like this to run from a Github public repository if possible

This would only be possible if you check in all dependencies in to the repo, which I would advise against

> I assume the Examples are running from a public URL in the Tabris Dev. App.

They are actually bundled with the app


An alternative is to use a tool like [ngrok](http://ngrok.io/) to serve content on your local machine to a world-accessible URL.  Keep in mind that if you use this or your own publicly-accessible HTTP server it is very slow, as every file is downloaded every time without caching.

**Comment by mrmccormack** [comment]
**Hey Thanks... it was easy** (like almost everything I've done so far with Tabrisjs)

>STEPS
1. http://docs.tabris.com/latest/getting-started.html#set-up-your-development-machine 
2. Just set up app: http://docs.tabris.com/latest/getting-started.html#create-your-first-app
3. **No need to run** In the project directory, `tabris serve` (*I didn't even test it locally*)
4. FTP to my domain http://im215.com/tabrishosted/
5. Pasted that URL into Tabris app - and **presto** it worked.

- Now I can try some more stuff with this. A great way to showcase and test your apps with Developer App

- For some reason... I thought it would be much harder.  I do run a Nodejs / Expressjs / MongoDB / Ngnix app on https://www.digitalocean.com/ 

- I'm slowing understanding more and more about Tabris, and thinks it is great.

Rob

  (I'm going to give http://ngrok.io/ a try too.)

**Comment by mpost** [comment]
Great that you could bring it to work. Closing this for now.
