### ISSUE TITLE
Text wrapping not consistent across platforms

### ISSUE THREAD

**Issue by cookieguru** [eclipsesource/tabris-js#1645]
### Problem description
A `TextView` without layout data wraps differently depending on the platform.  If the text is too long to fit the available width of the container, it will wrap on Windows but will clip on Android and iOS.

![Android](https://user-images.githubusercontent.com/1888809/39895076-cd7584b0-545d-11e8-8aa7-99e110867459.png) ![Windows](https://user-images.githubusercontent.com/1888809/39895045-b785efbe-545d-11e8-8769-e02b503aa178.png) 
![iOS](https://user-images.githubusercontent.com/1888809/40041270-3c250bac-57d2-11e8-9168-e8d97d257e62.jpg)

### Expected behavior

`TextView` is laid out consistently across platforms

### Workaround
Set width or left/right properties to force the widget to have horizontal bounding

### Environment

- Tabris.js version: 2.4.2
- OS: Android 8.0.0
- OS: iOS 11.3
- OS: Windows 10 Pro

### Code snippet

```javascript
const {TextView, ui} = require('tabris');

return new TextView({
  text: generateText(),
}).appendTo(ui.contentView);

function generateText() {
  let text = '';
  for(let i = 0; i < 100; i++) {
    text += 'Test ';
  }
  return text;
}
```

**Comment by mpost** [comment]
Thanks for opening the issue. This is indeed a know issue on the windows client. We actually forced the Android client not to wrap as well which is its default behavior. As you pointed out you can work around the issue by setting the left and right layout data properties.

**Comment by cookieguru** [comment]
Closing the issue as the Windows client is not being updated for 3.0
