### ISSUE TITLE
children() of CollectionView

### ISSUE THREAD

**Issue by kc853** [eclipsesource/tabris-js#1646]
### Problem description

I was trying to access the children() collection of a CollectionView using the `index` in the `select` event. I got strange results. I then did a test (see code snippet) and recognized that the children() collection is not as long as expected. It grows on scrolling but stops at max. 23 on my phone.  What could be the problem?
### Expected behavior

The children() collection should contain one object for each cell of the CollectionView.

### Environment

- Tabris.js version: 2.4.2 from playground
- Device: Unihertz Jelly pro (small screen device)
- OS: Android 7.0

### Code snippet

```javascript
const {CollectionView, TextView, ui} = require('tabris');

let elements=[];
for (i = 0; i < 500; i++) elements[i]=i;

let tv = new TextView({
    left:10,right:10,top:0,background:'red',
    textColor:'white',font:'bold 34px',alignment:'center'
    }).appendTo(ui.contentView);

let cv= new CollectionView({
    left:10,right:10, top:'prev() 10',bottom:0,
  
    createCell: ()=>new TextView({left:10,right:10,top:0,alignment:'center'}),
    updateCell: (cell,index)=>cell.set('text',elements[index])

	}).on('scroll', ({target}) =>{
        tv.text=target.children().length;
    }).appendTo(ui.contentView);

cv.load(elements.length);
```

**Comment by mpost** [comment]
The children of a `CollectionView` are not a valid return value and should not be used. Since you are reusing the cells in the CV you can not access the widgets outside of the updateCells method.

**Comment by kc853** [comment]
OK, may be it's worth to mention in the docs. Thank you.

**Comment by mpost** [comment]
Closing the issue as resolved.
