### ISSUE TITLE
HTTPS in webview production

### ISSUE THREAD

**Issue by acefxlabs** [eclipsesource/tabris-js#1649]
Hello

I am having issue loading https based pages in Webview in production app.
Is there a way around that. I have enabled cordova whitelist 

`<plugin name="cordova-plugin-whitelist"/>

    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />

    <allow-navigation href="http://*/*" />
    <allow-navigation href="https://*/*" />
    <allow-navigation href="data:*" />`

Yet no luck
Please i need your urgent help

Thanks

**Comment by cookieguru** [comment]
What exactly is the issue loading pages?

**Comment by acefxlabs** [comment]
When loaded on browser page loads and when in debug or test mode, page loads.
But once built into release for production it does show blank

Thanks

**Comment by acefxlabs** [comment]
I found the solution
Turns out not all browser was recognizing the certificate on mobile.
So its cause of it.

** FOR ANYONE WHO MAY READ THIS
Browse the website you are trying to access on WebView on multiple browsers
Chrome seem perfect but firefox and default browser showed the cert error
**
