### ISSUE TITLE
Native Window from plugin overlay

### ISSUE THREAD

**Issue by acefxlabs** [eclipsesource/tabris-js#1650]
Hello 
I am using a native player plugin [https://github.com/acefxlabs/cordova-plugin-streaming-media](url) and i was able to make it play the stream i was trying to play.
The only issue is it creates a Window overlay on the app and if i tap the back button, the player stop and  the overlay gets out.
** All tabris feature is not available (debug side or view) until the overlay closes.
Is there a way i can hide the overlay

Thanks

**Comment by mpost** [comment]
While i can't fully make any comments on the plugin, if it creates a new "dialog"/android window, the underlying tabris should work as expected. When it creates a new Activity, the tabris activity is not active anymore. You should check with the plugin itself.

**Comment by acefxlabs** [comment]
Thanks for the response.
Yes you are right, the issue here is i am not a java developer and i have tried to find a way to make that activity hidden but its not forth coming even after trying alot of things.
So my need is if there is a way to fix it or another plugin that can work

Thanks

**Comment by mpost** [comment]
Closing this for now. Please reopen if required.
