### ISSUE TITLE
On tabris2 app- we see background is not a property

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#1651]
### Problem description

Usig tabris.js app for playground. Used compositeWidget.background. No changes to code ... But in the console we are seeing 'Could not set properties on taris.Composite (Reason: Property background...'.

### Expected behavior

Background should be set without error

### Environment

Tabris Playground app

**Comment by cookieguru** [comment]
What's the rest of the error?

**Comment by mpost** [comment]
@natanraj You will most likely have to update your Tabris.js 2 app from the app store the latest version as the 2.5 brought some internal changed to the `background` property format to support the linear-gradient.

**Comment by mpost** [comment]
Unfortunately the tabris-android 2.5 release has not been published to the google play store as expected. Therefore you were not getting the latest update. This has been remedied now and you should see the 2.5 version in the play store, which also resolves the error mentioned above for you.
