### ISSUE TITLE
Button images don't work anymore

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1654]
### Problem description

Button images are not shown on Android as of Tabris.js 2.5.0.

### Environment

- Tabris.js version: 2.5.0
- Device: Android Emulator
- OS: 8.0.0

### Code snippet

```javascript
const {Button, ui} = require('tabris');

new Button({
  left: 10, top: 10,
  text: 'Button',
  image: 'resources/card-filled.png' // not shown.
}).appendTo(ui.contentView);
```

**Comment by mpost** [comment]
Fixed for the 2.5.1 release.
