### ISSUE TITLE
Layout with percentage ignored egative offset 

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#1655]
So far this I tested this only on android, but there the following:
```js
widget.left = ['33%', -10];
```` 
does the same as
```js
widget.left = ['33%', 0];
```` 

Our documentation does not explicitly state that negative numbers don't work in this combination, so I would expect them to.

**Comment by mpost** [comment]
This is a known issue of the used layout system on Android. Closing as duplicate of https://github.com/eclipsesource/tabris-js/issues/1406.
