### ISSUE TITLE
Incorrect layout

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1656]
### Problem description

In the example below, `#body` is not being rendered correctly on Android.

|Android|iOS (expected layout)|
|---|---|
|![screenshot_1527857470](https://user-images.githubusercontent.com/2341769/40841616-6283db98-65ab-11e8-841c-b3444a565089.png)|![simulator screen shot - iphone 6s - 2018-06-01 at 14 51 12](https://user-images.githubusercontent.com/2341769/40841576-3f7a4164-65ab-11e8-8ac0-437326013957.png)|

### Environment

- Tabris.js version: 2.5.1
- Device: Simulator
- OS: Android 8.0.0

### Code snippet

```javascript
const {Composite, ui} = require('tabris');

ui.contentView.append(
  new Composite({id: 'arrow', left: 0, top: 0, bottom: 0}).append(
    new Composite({id: 'body', left: 0, top: 0, bottom: 0, right: 'next()', background: 'red'}),
    new Composite({id: 'tip', right: 0, top: 0, bottom: 0, width: 20, background: 'blue'})
  )
).on({resize: bounds => ui.contentView.find('#arrow').first(Composite).width = bounds.width});

```

**Comment by mpost** [comment]
We can confirm the issue and are looking into fixing it.
