### ISSUE TITLE
Map not displayed using tabris-plugin-maps

### ISSUE THREAD

**Issue by maxapps** [eclipsesource/tabris-js#1658]
### Problem description

I created a simple test based on the example found on the **Tabris.js Maps Plugin** page. The build works and I think the plugin is working because the Google logo is displayed at the bottom right corner of the map container as can be seen in the screenshot:

![image](https://user-images.githubusercontent.com/292808/41121578-15a1290a-6a99-11e8-9215-1cd052010b1e.png)

The problem is that no map data is ever loaded. I suspect this is an issue with the **Google Maps API Key** but I have tried everything I can think of and it still doesn't work:

1. The same key works in a plain HTML/JS application.
2. The API Key is unrestricted (with a warning icon next to it in the Google API Console).
3. The **config.xml** includes the line `<variable name="ANDROID_API_KEY" value="$ANDROID_API_KEY" />`.
4. The actual API Key was correctly pasted into the Tabris project settings as **ANDROID_API_KEY**.
5. I even tried changing the the name of the name of the API Key in the Google Console from **API key** to **ANDROID_API_KEY**.

### Expected behavior

I don't think is is actually a Tabris problem but I've been hammering at this problem on and off for a couple months and have gotten to the point where I have to get it working or switch to another platform. Hopefully, someone has some ideas about what is wrong.

An old, closed issue [#840](https://github.com/eclipsesource/tabris-js/issues/840) mentions the same problem and the post by **jonek** on on Jun 26, 2016 states:

> You have to associate the API key with either a production or debug key you use when building your app. When you use a debug key, it has to be a key created by your own and registered with https://tabrisjs.com so the build services does not create a new debug key for each build under the hood (default behavior if you do not specify a key explicitly).

This is what led to me changing the name of the variable in the Google console from **API key** to **ANDROID_API_KEY** but it seems possible @jonek meant something entirely different.

### Environment

- Tabris.js version: 2.5.1
- Device: Samsung Note 8
- OS: Android 8.0.0

**Comment by cookieguru** [comment]
The gray screen usually indicates an invalid key.  [tabris-plugin-maps#12](https://github.com/eclipsesource/tabris-plugin-maps/issues/12) has some good troubleshooting tips; the logcat output will most likely point to the issue.

> The same key works in a plain HTML/JS application.

That's not necessarily and indicator that the key is "good"; the Google API console allows you to lock down the key in various ways.  If you have it set, for example, to HTTP referrers, it won't work in an Android app.

> The actual API Key was correctly pasted into the Tabris project settings as ANDROID_API_KEY.

Just to confirm, you're using the cloud build service and are referring to the _Environment Variables_ section?

> I even tried changing the the name of the name of the API Key in the Google Console from API key to ANDROID_API_KEY.

The name in the Google API console has no effect.

**Comment by maxapps** [comment]
@cookieguru Thanks for the help -- the issue at [ tabris-plugin-maps#12](https://github.com/eclipsesource/tabris-plugin-maps/issues/12) is identical to mine.

From that post:

> To see if your key ended up in the app correctly you can open the created apk in AndroidStudio (drag and drop onto it in latest beta version) and see if the AndroidManifest.xml has an entry

I just checked and the entry does exist in the generated APK file.

>... the Google API console allows you to lock down the key in various ways. If you have it set, for example, to HTTP referrers, it won't work in an Android app.

None of the Google API keys I've tried are locked down in any way. All have the warning icon next to them which states "_This API key is unrestricted. To prevent unauthorized use and quota theft, restrict your key to limit how it can be used._"

This is clearly an issue with API key so I really appreciate your help in getting it to work. A couple of the messages seem to indicate a specific SHA1 key is needed and that it needs to be "tied" to the Google API Key. Since the Google key is unrestricted this should not be needed. Am I missing something here?

These posts from Issue 12 make me question if that is true:
> I have a keystore file using which i got the SHA1 keys.
Then in console.google.com, i got a android API key and attached the package of my app and the SHA1. 

> That is promissing... The cloud build currently uses an internal debug keystore when building in debug mode. Please make sure to build a release version (or add the sha1 from the build apk in the google dev console).

These posts date from 2016 so maybe that was before you could specify a **Development Signing Key**? Please verify this should be able to work with a DEBUG apk and the default signing key.

**Comment by maxapps** [comment]
> Which type of Google Maps key did you generate? You need a Maps SDK for Android key.

I created a google maps API key with no restrictions at all. Are you saying I have to create an API key specifically for Android?

> I can confirm that I have generated a debug build of a Tabris.js app working with a Google Maps key. I'm using an autogenerated development signing key.

Did you somehow tie the **development signing key** to the **google API key** on the google console page? I know it would be a lot of work but a step by step guide showing what to do on both sides (Google console and Tabris console) would be really helpful. If I ever get this working, I'll take a shot at it.

> Logcat output should provide a better description of the problem.

Sorry, my background is not Android development so I'm not really certain how Logcat works. I installed [Logcat Reader](https://play.google.com/store/apps/details?id=com.dp.logcatapp) but don't really know how to view logs from my Tabris test app. Will investigate that and the possibility of generating an Android-specific API key in a few minutes.

Thanks again for your time.

**Comment by maxapps** [comment]
@cookieguru 

OK, figured logcat out and found that it is definitely a Google Maps Android API Authorization failure.

Next step -- figure out how to fix it...

**Comment by maxapps** [comment]
## SUCCESS

I'm not 100 percent certain **exactly** how I got it working but it had to do with enabling Android for the specific Google API Key I was using. This was accomplished from a different page of the console which was reached by following links specified in the logcat entry. Note that it had **nothing** to do with restrictions on the API key.

Now that a basic example is working, I will work on providing some kind of documentation to help anyone else who might not be familiar with the process.

Thanks again for the help.

**Comment by maxapps** [comment]
I added a post to the end of [issue 12 of the tabris-plugin-maps](https://github.com/eclipsesource/tabris-plugin-maps/issues/12) describing what steps were needed to make this work.

**Comment by cookieguru** [comment]
This would make a great PR to the [tabris-plugin-maps](https://github.com/eclipsesource/tabris-plugin-maps/) docs.

**Comment by maxapps** [comment]
## New (somewhat) related issue

The **tabris-plugin-maps** plugin does not provide GPS based geolocation services. It looks like you can enable the Google Geolocation API in a manner similar to enabling Android Maps but this doesn't include GPS. From the google docs:

> Find a location and accuracy radius based on information from things like cell towers and WiFi access points that a mobile client can detect with the Geolocation API. This is primarily used where GPS is not possible or appropriate.

From what I can tell, you have to use another plugin to actually get GPS geolocation data such as the device's current location. [Issue #960](https://github.com/eclipsesource/tabris-js/issues/960) from 2016 mentions [this plugin](https://github.com/louisbl/cordova-plugin-locationservices) which was last updated two years ago.

If I do nothing more than add a reference to that plugin, the app will no longer build using the online service. The line I added to the **config.xml** file was
`<plugin name="cordova-plugin-locationservices" spec="^2.1.0" />`

In the detailed log, the first line after the warning about the build failing was a note that some input files were using a depreciated API. I thought this might be caused by the out-of-date plugin so I also tried [android-location-provider](https://www.npmjs.com/package/android-location-provider) which was last modified 13 days ago.
`<plugin name="android-location-provider" spec="^1.0.1" />`
Unfortunately, this led to the exact same error message after it failed to build.

Again, the app builds just fine if neither of these plugins are included. Does anyone know of a cordova plugin which includes geolocation services that actually works with Tabris?

**Comment by cookieguru** [comment]
Can you clarify what you mean by geolocation services?  Are you just trying to [get the current location of the user](https://github.com/eclipsesource/tabris-plugin-maps#mylocation--number)?

**Comment by maxapps** [comment]
> Can you clarify what you mean by geolocation services? Are you just trying to get the current location of the user?

Yes, I just want to get the location of the device using GPS -- not based on WiFi or cell towers.

**Comment by cookieguru** [comment]
Does the method I linked to work for you?

**Comment by maxapps** [comment]
So far, enabling the Geolocation API has done nothing but the docs say it could take a while. In the meantime I also tried setting the map plugin's **showMyLocation** property to true BEFORE attempting to access **myLocation**. This resulted in a warning message in the Tabris app's console 

> Could not set properties on com.eclipsesource.maps.Map (Reason: android.permission.ACCESS_FINE_LOCATION not available)

According to the docs and several other Cordova related posts, the plugin is supposed to handle the permission settings so I don't really understand what is going on.

Incidentally, having a functional, robust mapping example in Tabris would be a huge reason for people to use the platform. I think if you could post a link to an actual working example on the Flutter support pages, numerous developers would be interested enough to check it out. It is one of the most requested features which is not adequately handled by the Flutter platform.

**Comment by maxapps** [comment]
Doing a search on "_MyLocation layer not enabled_" led to a [StackOverlow post](https://stackoverflow.com/questions/13739990/map-view-following-user-mylocationoverlay-type-functionality-for-android-maps/13753518#13753518) which sheds some light on the subject.

Based on this, does the plugin just need to be modified so it asks for the appropriate permissions? If so, you could then use the **showMyLocation** and **myLocation** properties as indicated.

**Comment by cookieguru** [comment]
`tabris-plugin-maps` does not ask for permission: [tabris-plugin-maps#18](https://github.com/eclipsesource/tabris-plugin-maps/issues/18).  You need [cordova-plugin-android-permissions](https://github.com/NeoLSN/cordova-plugin-android-permissions) for that, or you can enable it though system settings.  Or the plugin mentioned on the aformentioned issue.  I haven't used either.

**Comment by maxapps** [comment]
Adding [cordova-plugin-android-permissions](https://github.com/NeoLSN/cordova-plugin-android-permissions) took care of the issue.

For anyone else struggling with this here are the steps needed to get it working.

#### Add a reference to a plugin for managing android permissions to the **cordova/config.xml** file:
`<plugin name="cordova-plugin-android-permissions" spec="^1.0.0" />`

#### Add code which checks if the app already has permission to access fine location:
```javascript
let permissions = cordova.plugins.permissions;

permissions.checkPermission(permissions.ACCESS_FINE_LOCATION, result => {
  if (!result.hasPermission) {
    permissions.requestPermission(permissions.ACCESS_FINE_LOCATION, result => {
      if (result.hasPermission) {
        // The myMap var is a reference to a Map created with new esmaps.Map()
        // Setting showMyLocation must wait until access to FINE_LOCATION is granted
        myMap.showMyLocation = true;
      }
    }, error => console.log(error));
  }
}, error => console.log(error));
```

Note that permission granting via this scheme is only valid for Android 6.0+. I have no idea what would happen if you target earlier versions.

@cookieguru  Thanks again for steering me in the right direction.

**Comment by cookieguru** [comment]
@maxapps In Android <6.0 users were not able to control which services apps had access to.  They were defined in `AndroidManifest.xml` and apps had full control over each service they defined (location, camera, etc) and the user was not able to revoke the permissions.

**Comment by mpost** [comment]
Great to see that you could figure it out. Closing this issue for now.
