### ISSUE TITLE
Focusing a TextInput triggers "select" on its cell

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1659]
### Problem description

When focusing a TextInput, the `"select"` event of its cell gets triggered.

### Expected behavior

Since the intent of the user is not to select the cell, but to focus the TextInput inside it, the CollectionView should not fire a `"select"` event in this case.

### Environment

- Tabris.js version: 2.5
- OS: iOS 10.3

### Code snippet

```javascript
const {CollectionView, Composite, TextInput, ui} = require('tabris');

new CollectionView({
  left: 0, top: 0, right: 0, bottom: 0,
  itemCount: 20,
  cellHeight: 128,
  createCell: () => {
    let cell = new Composite();
    new TextInput({left: 0, top: 0, right: 0}).appendTo(cell);
    return cell;
  },
}).on('select', ({index}) => console.log('selected: ' + index))
  .appendTo(ui.contentView);

```

**Comment by cpetrov** [comment]
Possible workaround: use a `"tap"` listener on the cell `Composite` instead of the `CollectionView`'s `"select"` event. `"tap"` does not get fired on the `Composite` when focusing the `TextInput`.

**Comment by mpost** [comment]
The `select` event on the `CollectionView` causes various problems with scrolling and highlight on touch. We are considering to remove it in a 3.0 release since it can be easily replaced with a `tap` gesture on a widget.
