### ISSUE TITLE
Debugging with sourcemaps is not working

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1662]
### Problem description

When attaching the Chrome inspector:
* inline sourcemaps: no sourcemaps shown.
* external sourcemaps: no sourcemaps shown.

When attaching the Safari inspector:
* inline sourcemaps: sourcemaps shown, but when selecting them, an error message is shown stating: `An error occurred trying to load the resource`.
* external sourcemaps: no sourcemaps shown.

### Expected behavior

There should be a way to debug a Tabris.js app on both Android and iOS using sourcemaps. Compiling ES6 and TS code is very common.

### Environment

- Tabris.js version: 2.5.1

**Comment by mpost** [comment]
With the new debugging support introduced in tabris 3.4 this issue is resolved.
