### ISSUE TITLE
Improve warning logging

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1663]
### Problem description

Currently, warnings like `"Inconsistent layoutData: centerX overrides left and right"` and `"Unknown property ..."` don't include any line numbers or stack traces, so they are very hard to debug. 

### Expected behavior

Those warnings should present line numbers or a stack trace to make backtracking easier.

### Environment

- Tabris.js version: 2.5.1

_* As reported by @cookieguru_

**Comment by tbuschto** [comment]
We should also print warnings (including stack trace) when attempting trigger events on disposed objects. Setting built-in properties after dispose already prints warnings, but without stack trace.

**Comment by tbuschto** [comment]
It was suggested to me that access to unimplemented W3C features API should also provide warnings where they don't produce errors automatically.

**Comment by tbuschto** [comment]
Related: https://github.com/eclipsesource/tabris-js/issues/1766

**Comment by tbuschto** [comment]
I did not find any W3C features that could be sensibly print warnings since it's not possible to differentiate between legitimate uses (our mock is sufficient) and non-functioning ones. Therefore that part will not be implemented for now.
