### ISSUE TITLE
Integrate new events API from tabris-decorators project

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1669]
### Problem description

The current events API is not very TypeScript friendly.

### Expected behavior

Integrate Listeners class from here: 
https://github.com/eclipsesource/tabris-decorators/blob/master/src/api/Listeners.ts

Provide listeners objects for all built-in events.

The typescript declarations for "on" may be simplified to not be type-safe.

**Comment by tbuschto** [comment]
Done
