### ISSUE TITLE
Replace TabFolder textColor with more fine grained color properties

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1676]
### Problem description

The [`textColor`](http://docs.tabris.com/latest/api/TabFolder.html#textcolor) property on TabFolder is very broad since it colorizes the text, image, possibly tap bar background etc. 

### Expected behavior

Provide more fine grained control in the form of the following properties

* textColor
* imageColor
* selectedTextColor
* selectedImageColor

If required a more general `tabTintColor` could be used when the tab bar doesn't support fine grained styling.

### Environment

- Tabris.js version: 2.5

**Comment by mpost** [comment]
Related issue: https://github.com/eclipsesource/tabris-js/issues/882

**Comment by patrykmol** [comment]
In case of `TabFolder` we use 2 widgets depending on style. For `top` style we `UISegmentedControl` which only has one property `tintColor`. This affects all non-white elements visible in this widget. In case of `bottom` `UITabBar` is used. This has 3 properties that we can use.
```
barTintColor
The tint color to apply to the tab bar background.

tintColor
The tint color to apply to the tab bar items.

unselectedItemTintColor
The tint color to apply to unselected tabs.
```

**Comment by mpost** [comment]
On Android you would be able to have

- tabBarElevation
- tabBarBackground
- itemTextColor
- itemTextColorSelected
- itemIconColor
- itemIconColorSelected
- tabIndicatorColor (only top tabBar)

**Comment by mpost** [comment]
For the final API we agreed on removing `textColor` and to introduce the following new properties:

- `tabTintColor`
- `selectedTabTintColor`
- `tabBarBackground`
- `tabBarElevation` (Android only)
- `tabIndicatorColor` (Android only)
- `badgeColor` (If changeable on iOS)

**Comment by patrykmol** [comment]
iOS part is implemented.

**Comment by mpost** [comment]
Implemented via https://github.com/eclipsesource/tabris-js/commit/c23df4e98c5ceb9501d85156e11da78b42f2cf89
