### ISSUE TITLE
Extend Selector API

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#1678]
### Problem description

From experience using the selector API can be more verbose than it could be, both the selector strings and composite methods.

### Expected behavior

To start with there are some features that may be convenient and relatively easy to implement:
  * new selectors:  `:nth-child(x)`, `:nth-last-child(x)`, `:first-child`, `:last-child`
  * Allow using JSX stateless function components (SFC) as selectors and/or selector strings, just like constructors.
 * allow the combination of selectors i.e. `Composite, #foo`
 * Add `parents()` method, see https://github.com/eclipsesource/tabris-js/issues/563
 * Add `getWidgetById(id)` to composite

**Comment by mpost** [comment]
Related to https://github.com/eclipsesource/tabris-js/issues/504

**Comment by tbuschto** [comment]
See also https://github.com/eclipsesource/tabris-js/issues/326

**Comment by tbuschto** [comment]
See also https://github.com/eclipsesource/tabris-js/issues/563

**Comment by mpost** [comment]
All relevant improvements have been implemented but

"allow the combination of selectors i.e. Composite, #foo"
