### ISSUE TITLE
Support $ as an alias for WidgetCollection

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#1679]
### Problem description

We often need to write JSX like this...
```jsx
this.append(
  <widgetCollection>
    <textView/>
    <textView/>
    <textView/>
  </widgetCollection>
);
```
### Expected behavior

A shorter alias such as `$` would save a lot of characters in the long run.

Bonus: Since WidgetCollection API is already somewhat reminiscent of jQuery, we could put `$` in to global scope and provide some more jQuery-like API on it. I'm thinking specifically on something like `$(selector)`, where the selector searches globally through any currently existing widgets. 

### Environment

any

### Code snippet

The result would be:

```jsx
this.append(
  <$>
    <textView/>
    <textView/>
    <textView/>
  </$>
);
```

Note: 
JSX supports empty element names like this...

```jsx
this.append(
  <>
    <textView/>
    <textView/>
    <textView/>
  </>
);
```
 ... but unfortunately not with custom renderer like we use.

**Comment by tbuschto** [comment]
Caveat: This ONLY works if we put $ in global scope, since the character can not be used for intrinsic JSX elements. While I'm for that (as outlined above), we should probably discuss the PROs and CONs of that beforehand. The only library that I found using this is jQuery. While that is fairly popular, it is not very useful in tabris, and it has a no-conflict mode.

**Comment by mpost** [comment]
I agree that the current `widgetCollection` is rather lengthy. Would it be an option to leave out the top level element all together? It would be rather convenient.
