### ISSUE TITLE
Merge backgroundImage on Widget into background property

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1684]
### Problem description

It is not necessary to have the `backgroundImage` in parallel to the `background` property.

### Expected behavior

The image should be set via the `background` property.
Remove `backgroundImage` property.

### Environment

- Tabris.js version: 2.5

**Comment by tbuschto** [comment]
@mpost I'm not 100% convinced of the term "Shader". According to wikipedia "In computer graphics, a shader is a type of computer program...". Wouldn't "Brush" be better?

**Comment by mpost** [comment]
I like the term Shader since we provide a configuration for a program to draw some arbitrary background. It is also rather short. Brush would not be my obvious choice since the mental connection to the background is not immediate in my mind. On Android it is called "Drawable" which is rather lengthy but descriptive.
