### ISSUE TITLE
Allow to set different TextInput styles

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1686]
### Problem description

Currently the TextInput is tied to the default platform specific look. 

### Expected behavior

We should allow to create variations without any background, with box or rounded box background. Additionally the "flying hint message" could be supported.

https://material.io/design/components/text-fields.html

![image](https://user-images.githubusercontent.com/73655/41544834-01a0c756-731a-11e8-9d85-78569812ef43.png)

![image](https://user-images.githubusercontent.com/73655/41544899-2f8782b8-731a-11e8-8631-e12f031ffe37.png)

**Comment by patrykmol** [comment]
There are not that many things we can do to stylise `TextInput` on iOS. Single line text input has property called `borderStyle` with following values: `none`, `line`, `bezel` and `roundedRect`. However multi line text input has no such property but allows to set border width using float value. Single line text input also has this property. Both single and multi line also allow to set corner radius of borders. However this property is already supported on every widget.

**Comment by mpost** [comment]
The way how these types of styles are implemented on Android is via a `TextInputLayout` which would need to be a container of the tabris `TextInput`. This is technically difficult to do since all the properties would need to be applid on the TextInput and not the parent `TextInputLayout`. In addition not every `TextInput` would need these kind of features. We could therefore expose the layout as an extra widget or go through the length to reengineer the `TextInput` to work with with and without the `TextInputLayout`.

**Comment by mpost** [comment]
With these technical constraints this story will not make the cut for a 3.0 release but is scheduled for a later date.

**Comment by mpost** [comment]
The feature has been implement in Tabris 3.0 on Android.
