### ISSUE TITLE
Improve app startup time when sideloading code

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#1695]
### Problem description

Testing code changes in Tabris.js by restarting the app can be painfully slow, especially with many npm modules installed. This is mainly because every single JS file, even unchanged ones are transferred again, each requiring multiple https requests to find them.

### Expected behavior

 * Request only changed files
 * Request only files that exist.

This will likely require changes to the module code as well as the CLI and/or native clients.

**Comment by tbuschto** [comment]
Ages ago I already attempted to fix the multiple-requests-per-module issue: 
https://gerrit.eclipsesource.com/#/c/5090/

**Comment by tbuschto** [comment]
We may be able to do something with the debug websocket currently in development:
https://github.com/eclipsesource/tabris-js-cli/issues/8

Maybe even some kind of hot-module-replacement?

**Comment by tbuschto** [comment]
CLI counterpart: https://github.com/eclipsesource/tabris-js-cli/issues/36

**Comment by mpost** [comment]
Interesting insights. Is caching something we could introduce in the tabris module system?

**Comment by jonek** [comment]
@tbuschto
- How would a request for multiple files look like?
- What do you mean by `Caching module source code via file-system API.`? Storing them in the file system of the mobile device and retrieving them from that location when available before making a network request?

**Comment by cookieguru** [comment]
I noticed that `ecstatic` is already serving files with an `etag` header.

Is multiplexing à la HTTP/2 a possibility?

**Comment by tbuschto** [comment]
I'd like to be able to do all of this without changes to native code and no changes to the module system aside from providing some hooks for the debug client introduced recently to the CLI.

Right now, regarding both transferring multiple files in one request and caching, my idea is to introduce something like a tabris "chunk" file format that allows the CLI to deliver the content of multiple source files including meta information in one response, or just the meta information (i.e. hashes). The debug client can then organize the file transfer in such a way that only changed sources are downloaded in as few requests as possible. I thought about the details a bit, but it will be more productive to just experiment with these ideas instead of planning too much ahead.

**Comment by tbuschto** [comment]
As of commit 92c1c485deca03b1620b99ca85b68f4d9e408250 sideloading happens on a per-directory basis, in my tests that improved speed up to ten times. There is still room for improvement, for now I will consider this specific issue closed for Tabris 3.0.
