### ISSUE TITLE
StatusBar height unexpected with iPhone X

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1699]
### Problem description

StatusBar `height` is [commonly used in conjunction with `displayMode: "float"` in order to offset the app content](http://docs.tabris.com/latest/api/StatusBar.html#height). However, on iPhone X, `height` reports `44`, i.e. the height of the StatusBar including the area around the notch outside of the usable app view area. 

### Expected behavior

`height` should report the height of the StatusBar inside the app view area.

### Environment

- Tabris.js version: 2.5.1
- Device: iPhone X
- OS: iOS 11

**Comment by patrykmol** [comment]
This issue is invalid. You can set background colour of `statusBar` to transparent and content will rendered under the status bar. Status bar is still visible hence the non-zero value of it's height. This is correct behaviour. You can see it in effect in Google Maps or Weather app for example.
