### ISSUE TITLE
asynchronous function works on Iphone not Android

### ISSUE THREAD

**Issue by mrmccormack** [eclipsesource/tabris-js#1703]
### Problem description

- asynchronous function works on Iphone **not** on Android (just a simple example)

### Expected behavior
- code should work the same on both

###  Works on iPhone Environment

Tabris.js version: 2.5.1
platform: iOS
version: 11.4
model: iPhone10,4
vendor: Apple
language: en-CA
orientation: portrait-primary
screenWidth: 375
screenHeight: 667
scaleFactor: 2
*/

### NO work on Android  Environment
Tabris.js version: 2.5.1-20180529-0914
platform: Android
version: 23
model: 4060S
vendor: TCL
language: en-CA
orientation: portrait-primary
screenWidth: 320
screenHeight: 569
scaleFactor: 1.5

--- ERROR reported
Could not load main module: Error: Could not parse ./app.js:./app.js:32: SyntaxError: Unexpected token function
async function asyncCall () {
      ^^^^^^^^
com.eclipsesource.v8
*/

### Code snippet

```javascript
const {ui} = require('tabris')

// works on Playground...

// code from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

function resolveAfter2Seconds () {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve('resolved')
    }, 2000)
  })
}

async function asyncCall () {
  console.log('calling')
  var result = await resolveAfter2Seconds()
  console.log(result)
  // expected output: "resolved"
}

asyncCall()

```

**Comment by cookieguru** [comment]
CC @irbull https://github.com/eclipsesource/J2V8/issues/381
https://github.com/eclipsesource/J2V8/issues/402

**Comment by mrmccormack** [comment]
Thanks... does that mean async is not supported on Android yet?  I'm using them to test if a file exists - https://stackoverflow.com/questions/51384239/how-to-test-if-a-file-exists-in-tabris  (I have it working on iPhone only) - If no async... how do I test if a file exists?

**Comment by tbuschto** [comment]
This is documented, but now also explicitly statet in the yoeman generator.
