### ISSUE TITLE
iPhone8 device reports iPhone10,4 (device. model)

### ISSUE THREAD

**Issue by mrmccormack** [eclipsesource/tabris-js#1704]
### Problem description

I definely have an iPhone 8, but device. model says:  
`iPhone10,4`

### Environment
Tabris.js version: 2.5.1
platform: iOS
version: 11.4
model: iPhone10,4  (maybe this is wrong)

### Code snippet - from Tabrisjs docs

```javascript
const {TextView, device, ui} = require('tabris');

// Display available device information

['platform', 'version', 'model', 'vendor', 'name', 'language', 'orientation'].forEach((property) => {
  new TextView({
    id: property,
    left: 10, right: 10, top: 'prev() 10',
    text: property + ': ' + device[property]
  }).appendTo(ui.contentView);
});

device.on('orientationChanged', ({value: orientation}) => {
  ui.contentView.find('#orientation').set('text', 'orientation: ' + orientation);
});
```

Thanks for looking into this !

**Comment by cookieguru** [comment]
That is the identifier that iOS exposes

https://www.theiphonewiki.com/wiki/Models#iPhone

**Comment by mrmccormack** [comment]
Thanks  this ticket may be closed
