### ISSUE TITLE
topToolbarHeight does not return zero when tollbarVisible is set false

### ISSUE THREAD

**Issue by ifurnadjiev** [eclipsesource/tabris-js#1706]
### Problem description

Setting NavigationView `toolbarVisible` to false does not update `topToolbarHeight` property. According to the documentation, `topToolbarHeight` should return zero in this case. Also `topToolbarHeightChanged` event is not fired.

### Expected behavior

When `toolbarVisible` is set to false, `topToolbarHeight` must return zero.

### Environment

- Tabris.js version: 2.5.1
- Device: Samsung Galaxy S9
- OS: Android 8.0.0

**Comment by mpost** [comment]
We should fix this issue for 3.0 so that we can remove the then outdated property `bottomToolbarHeight` and possibly rename the `topToolbarHeight` to `toolbarHeight` etc.

**Comment by mpost** [comment]
The issue should be fixed in JS by accounting for the visibility state when getting the height. See https://github.com/eclipsesource/tabris-js/blob/d35641c3a9890b9a79c4a9951cd18473132400f3/src/tabris/widgets/NavigationView.js#L100

**Comment by mpost** [comment]
Closing this issue via https://github.com/eclipsesource/tabris-js/commit/7f07dbfe0c715521c560ed668a84c017b8e476b2

> With recent changes in iOS, the bottom toolbar has been removed from the NavigationView. Therefore there is no need for the "bottomToolbarHeight" property anymore. This change removes the "bottomToolbarHeight" property and renames the "topToolbarHeight" to "toolbarHeight".

The navigationview-properties.js snippet also fires the change event as expected. Please reopen if you have any more issues.
