### ISSUE TITLE
Reading/writing json files snippet - not updating json object

### ISSUE THREAD

**Issue by mrmccormack** [eclipsesource/tabris-js#1708]
### Problem description
 I'm writing a snippet to demonstrate how to read and write json files in Tabirsjs - I would think this would be a common task for developers.

### Expected behavior
My snippet works as expected, until  pressing the btnReadFile button. Then I can no longer update the `names` object when changing the TextInput fields. The *bookstore* example shows  how to read json file with, but I need to read/write json files and not just *require* a json file.

Try this:
1. run snippet in playground
1. change firstName to something
1. press `Write File button`
1. press `Read File`

and this works...

But now, any further changes to firstName show up in TextInput field, but the `names` object never changes and no further changes are written to disk. (see the many console.log's)

It's like the `ReadFile` freezes the `names` object. Not sure why? 

### Environment

- Tabris.js version:  2.5
- Device: iPhone 7
- OS: iOS 10.3.3 

### Code snippet (works on Playground)

```javascript
const {Button, fs, TextInput, ui} = require('tabris')

const FILE = fs.filesDir + '/' + 'names.json'

const RIGHT_MARGIN = 10
const LEFT_MARGIN = 10

var names = [
  {
    'firstName': 'Bob',
    'lastName': 'Jones'
  },
  {
    'firstName': 'Jill',
    'lastName': 'Willard'
  }

]

console.log(JSON.stringify(names))

names.forEach((name, index) => {
  let txiFirstName = new TextInput({
    id: 'txiFirstName' + (index),
    top: 'prev() 10',
    text: name.firstName
  }).appendTo(ui.contentView)

  txiFirstName.on('textChanged', () => {
    txiFirstName.borderColor = '#0f0'
    name.firstName = txiFirstName.text
    console.log('textChanged: \nname.firstName = ' + name.firstName)
    console.log(JSON.stringify(names))
  })

  let txiLastName = new TextInput({
    id: 'txiLastName' + (index),
    top: 'prev() 10',
    text: name.lastName
  }).appendTo(ui.contentView)

  txiLastName.on('textChanged', () => {
    name.lastName = txiLastName.text
  })
}) // end forEach

let btnReadFile = new Button({
  centerX: 0, top: 'prev() 10', width: 200,
  text: 'Read File: ' + FILE
}).appendTo(ui.contentView)

btnReadFile.on('select', () => {
  readFile(FILE)
  console.log(JSON.stringify(names))
  readNames()
})

let btnWriteFile = new Button({
  centerX: 0, top: 'prev() 10', width: 200,
  text: 'Write File: ' + FILE
}).appendTo(ui.contentView)

let btnRemoveFile = new Button({
  centerX: 0, top: 'prev() 10', width: 200,
  text: 'Remove File: ' + FILE
}).appendTo(ui.contentView)

btnWriteFile.on('select', () => {
  let jnames = JSON.stringify(names)
  fs.writeFile(FILE, jnames, 'utf-8')
    .then(() => {
      console.log('file written:', FILE)
      txiFile.text = jnames
      console.log(JSON.stringify(names))
    }
    )
    .catch(err => console.error(err))
})

btnRemoveFile.on('select', () => {
  fs.removeFile(FILE)
    .then(() => console.log('file removed:', FILE))
    .catch(err => console.error(err))
})

let txiFile = new TextInput({
  top: 'prev() 20', left: 5, right: 5,
  type: 'multiline'
}).appendTo(ui.contentView)

function readFile (filename) {
  fs.readFile(FILE, 'utf-8')
    .then(text => txiFile.text = text)
    .then(text => {
      names = JSON.parse(text)
      console.log(JSON.stringify(names))
      readNames()
    })
    .catch(err => console.error(err))
}

function readNames () {
  names.forEach((name, index) => {
    let t = '#txiFirstName' + index
    ui.contentView.apply({[t]: {text: name.firstName}})
    console.log(JSON.stringify(names))
  })
}


```

**Comment by mrmccormack** [comment]
**Thanks**,
you are correct, there were no `errors` - but **after** pressing btnRead, the value `name.firstName` would never change when the TextInput was changed (revealed with console.log). I never needed the two readNames(), so I removed one. I also have it working now.  I replaced `var` with `let` - and passed the json objects to functions as a parameter.  I don't understant what was going wrong, but it is working now.

I will continue to work on this snippet. I want to add a condition when it first runs to write the file with default json object, and then, have it read the file from then on. This is what I want on the small app I'm developing.

>REVISED CODE
https://gist.github.com/mrmccormack/769eadb17687910c9257342c45e225ae

>Comparison of changes:
https://gist.github.com/mrmccormack/769eadb17687910c9257342c45e225ae/revisions

**Comment by mrmccormack** [comment]
**Q**
Is it a bad idea to write the file on **every** change. 
`  txiFirstName.on('textChanged', () => // write file code` 

I wonder if I should write the file only on focus change mabye?  (`blur ` event)

**Comment by cookieguru** [comment]
It all depends.  Going to disk is a (relatively) expensive operation.  But if the user is likely to get interrupted somehow and you want to make sure you persist the data, it's something you'll have to do.  Alternatively, if you're keeping a copy of the data elsewhere, you can persist after a timeout, e.g. with a [debounce or throttle](https://medium.com/walkme-engineering/debounce-and-throttle-in-real-life-scenarios-1cc7e2e38c68).

**Comment by mpost** [comment]
Writing to disc on every textChanged (aka key stroke) can be done as the file operation is asynchronous. In general though a later point in time sounds more reasonable. Eg when the user hits a button or leaves the form.

**Comment by mpost** [comment]
Closing this as resolved. Please reopen if you have any more problems.
