### ISSUE TITLE
localStorage: storage limits, string limits

### ISSUE THREAD

**Issue by mrmccormack** [eclipsesource/tabris-js#1709]
Do we know string lenght limit, or storage limit for localStorage ?

**Ref:**
- http://docs.tabris.com/latest/api/localStorage.html
*The `localStorage` is only meant to store relatively short strings. To store larger amounts of data it is recommended to use the FileSystem API.*

- I think browsers  allow 5 - 10MB, but there seem to be many issues with localStorage.

thanks.

**Comment by mpost** [comment]
On iOS the localStorage is backed by the NSUserDefaults and on Android by the SharedPreferences. None of these two have a hard limit on the storage but the entire storage is deserialized when read so storing large amounts of data will slow down access.

**Comment by karolszafranski** [comment]
It does not use `NSUSerDefaults` on iOS. It’s a dictionary serialized to a file. All values are stored in a single dictionary which is synchronously written to the file system on each `set` and `remove`operation.

**Comment by mrmccormack** [comment]
Thanks, you can close this ticket.
