### ISSUE TITLE
Allow to overlay page content with navigation bar

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#171]
That should be a mode similar to the current "FULLSCREEN" that you can enable right now.

**Comment by ralfstx** [comment]
Comment by @jordiboehmelopez on dup #290:
> The important part is, that the start coordinates 0,0 are not at top left of the screen, instead below the status bar. The content would only become visible under the status bar, when it is scrolled.

**Comment by ralfstx** [comment]
iOS Example:
![images](https://cloud.githubusercontent.com/assets/61378/6267661/36d181aa-b846-11e4-99ce-b06bf18df49a.jpeg)

**Comment by mpost** [comment]
Will be available in Tabris.js 2.0.

**Comment by ralfstx** [comment]
The property `tabris.statusBar.displayMode` can be set to `float` to allow for this appearance.
