### ISSUE TITLE
Documentation: EventObject - Do you need to import EventObject

### ISSUE THREAD

**Issue by mrmccormack** [eclipsesource/tabris-js#1714]
### Importing EventObject

- I'm using `event.target` and the very useful `event.timestamp`, **yet**, I am not importing the EventObject as apparently required from documentation.

Q:
- Should I be importing EventObject ?

#### From Docs.
Import this type with: 
```js
const {EventObject} = require('tabris');
```

**Ref:**
http://docs.tabris.com/latest/api/EventObject.html

#### A snippet,

```js
  txiFirstName.on('blur', event => {
    txiBlur(event.target)   // function
    console.log('timestamp: ' + event.timeStamp)
    name.firstName = txiFirstName.text  // populate JSON object
    writeJSON(names)
  })

```

**Comment by cookieguru** [comment]
No, it is not necessary.  [The code that instantiates them](https://github.com/eclipsesource/tabris-js/blob/master/src/tabris/NativeObject.js#L195) takes care of importing them.

**Comment by mrmccormack** [comment]
Thanks...  so Docs could be changed.. (http://docs.tabris.com/latest/api/EventObject.html)

From:

~~Import this type with “const {EventObject} = require('tabris');”~~
to:

This object is available in the global namespace. You do not need to import it explicitly.

**Comment by mrmccormack** [comment]
Hey thanks for complete explanation.
