### ISSUE TITLE
Make type declarations work with strictFunctionTypes compiler flag

### ISSUE THREAD

**Issue by dbuschtoens** [eclipsesource/tabris-js#1719]
As described [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html), `--strictFunctionTypes` enables correct function parameter and return type variance checking.

Currently failing are the `MessagePort` type in `globals.d.ts`, change events of properties that are unnecessarily redefined in subclasses and the `SettableProperties` type

**Comment by tbuschto** [comment]
This compiler option causes tons of issues beyond the described one and it's not worth the time to fix this.
