### ISSUE TITLE
The text of the CheckBox is cut off

### ISSUE THREAD

**Issue by elshadsm** [eclipsesource/tabris-js#1720]
### Problem description

When the text of the CheckBox consists of two or more lines, it is cut off from the top and bottom. 

### Expected behavior

The text should be displayed as expected, even if multiple lines are used.

### Environment

- Tabris.js version: 2.5.1
- Device: iPhone 6
- OS: 11.4.1

### Code snippet

```javascript
const {CheckBox, ui} = require('tabris');

new CheckBox({
  left: 16, centerY: 0, right: 16,
  text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
}).appendTo(ui.contentView);
```

![file](https://user-images.githubusercontent.com/13982125/43859860-ec6b9444-9b62-11e8-8e51-7d6891d1157a.jpg)

**Comment by karolszafranski** [comment]
Fixed on `master` and cherry-picked to `2.6.x` branch.
https://github.com/eclipsesource/tabris-ios/commit/922fdbf9e9872fbb3bc4f9bdf620ae68f25dbf59
