### ISSUE TITLE
webView.postMessage is not a function

### ISSUE THREAD

**Issue by appsdevpk** [eclipsesource/tabris-js#1724]
### Problem description

webView.postMessage is not a function

### Expected behavior

A message should be posted to webView control.

### Environment

- Tabris.js version: 2.6.0
- Device: Nox Emulator
- OS: Android 4.4.2

### Code snippet

```jsx
import { WebView, ui } from 'tabris';

ui.contentView.append(
    <navigationView left={0} top={0} right={0} bottom={0} background='#e7e7e7'>
		<action title='Post Message' onSelect={() => {postMsg('testMessage')}}/>
		<page id="page1" title="Home Page">
		<webView id="wv" left={0} top='prev() 10' right={0} bottom={0} url="./web/index.html" />
		</page>
	</navigationView>
);
function postMsg(msg){
	let webView = ui.contentView.find('#wv');
	webView.postMessage(msg,'*');
}
```

**Comment by mpost** [comment]
When you do `find()` you should call `first()` as as `find()` returns a widget collection which does not support widget specific methods.

**Comment by mpost** [comment]
Closing this as resolved. Please reopen when you have any more issues.
