### ISSUE TITLE
iOS: Focus to set cursor in Text field doesn't work

### ISSUE THREAD

**Issue by mkempka** [eclipsesource/tabris-js#1725]
### Problem description

* Long press into a text field, so that the magnifying glass comes up.
* Choose a position and let go
* Actual behavior: no cursor is in the text field
* Expected behavior: cursor is at the indicated position

### Environment

- Tabris.js version: This has been happening on all my applications for a few months now. Should be reproducible from Tabris.js 2.5 upwards or so.
- OS: iOS 11.4.1

**Comment by patrykmol** [comment]
This issue has already been fixed for 2.7 and 3.0.
