### ISSUE TITLE
Enable customization of TextView link color

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1728]
### Problem description

On Android, a theme color is applied to links, but on iOS, there seems to be no means to customize the TextView link color.

### Expected behavior

Provide an API to set the TextView link color programmatically.

### Environment

- Tabris.js version: 2.6.1, 3.0.0-dev

**Comment by fax1ty** [comment]
+1

**Comment by fax1ty** [comment]
Just a property in TextView object
Like a 'linkColor': 'red'

**Comment by fax1ty** [comment]
Any progress?

**Comment by mpost** [comment]
No immediate update but it is on our radar.

**Comment by mpost** [comment]
Will be covered by https://github.com/eclipsesource/tabris-js/issues/1761
