### ISSUE TITLE
CollectionView: allow for dynamic item size

### ISSUE THREAD

**Issue by jordiboehmelopez** [eclipsesource/tabris-js#173]

**Comment by cookieguru** [comment]
Currently setting the height causes the app to crash.  See the following snippet for a "filter as you type" collection view:

```js
var page = tabris.create('Page', {
  title: 'Filter as you type',
  topLevel: true
});

var collection = tabris.create('CollectionView', {
  left: 0,
  top: 0,
  right: 0,
  bottom: 0,
  items: [{label: 'Red'}, {label: 'Blue'}, {label: 'Yellow'}, {label: 'Green'}],
  itemHeight: 24,
  initializeCell: function(cell, type) {
    var textView = tabris.create('TextView', {
      top: 2
    }).appendTo(cell);
    cell.on('change:item', function(widget, item) {
      textView.set('text', item.label);
      item.cell = cell;
      //cell.get('height') //returns null
    });
  }
}).appendTo(page);

tabris.create('SearchAction', {
  title: 'Search'
}).on('input', function(widget, query) {
  var items = collection.get('items');
  for(var i in items) {
    items[i].cell.set('height', items[i].label.toLowerCase().indexOf(query.toLowerCase()) > -1); //crashes
  }
});

page.open();
```
Attempting to set the height to 0 or a positive number of a `Cell` causes the app to crash.  Calling `get('height')` always returns `null`.  Setting `visible` works, but the visible property works just like the way it does in CSS: the element still takes up space but is invisible.

If it is possible on the native side, perhaps a `hide()` method could actually remove the element from the collection, while keeping it in the items array of the `CollectionView` on the JS side.

**Comment by mpost** [comment]
Thanks for the feedback. While the crash is unfortunate and should be circumvented on the native side there is another problem with your approach: 

You are storing a cell on your item. That will lead to unpredictable behavior when the list scrolls and the cell gets recycled for other items. In your snippet you would actually collapse the wrong items as the cells they were bound to are now used for other items.

The correct approach would be to [remove the item](https://tabrisjs.com/documentation/latest/api/CollectionView#removeindex) from the items list and/or [set a new items list](https://tabrisjs.com/documentation/latest/api/CollectionView#items).

**Comment by mpost** [comment]
We have fixed the crash on Android. Since the cell is a special parent widget it should not be touched directly so we ignore any layoutData changes to it.

**Comment by cookieguru** [comment]
With 500a04c16fdd8808dc1c867f92a760c0f88280bd this is now possible:

```js
let items = [
  'Item 0',
  'Item 1',
];

let view = new tabris.CollectionView({
  left: 0, top: 0, right: 0, bottom: 50,
  cellHeight: 'auto',
  itemCount: items.length,
  createCell: () => new tabris.TextView(),
  updateCell: (cell, index) => cell.text = items[index],
}).appendTo(tabris.ui.contentView);

new tabris.Button({
  left: 10, right: 10, bottom: 0,
  text: 'Add text'
}).on('tap', () => {
  items = items.map(item => `${item} More text\nEven More\nStill more`);
  view.refresh();
}).appendTo(tabris.ui.contentView);
```

**Comment by ralfstx** [comment]
Right, thanks!
