### ISSUE TITLE
Facing issue in tabris serve

### ISSUE THREAD

**Issue by jd048** [eclipsesource/tabris-js#1730]
### Problem description
i am just going to start development in tabrisjs, i am using mac environment
when i am going to do **tabris serve**  it will run sucessfully but when i am going to see my app in browser it will give me error **You don't have authorisation to view this page**

### Environment

- Tabris.js version: 2.6.1
- Device: Chrome 
- OS: Mac OS 10.12.6

### Code snippet

```javascript
// A minimal, *self-contained* code snippet to reproduce the problem:
```

**Comment by jd048** [comment]
![screen shot 2018-08-27 at 8 41 53 pm](https://user-images.githubusercontent.com/4142840/44869158-74469280-acaa-11e8-9300-0f896484cc4c.png)

**Comment by cookieguru** [comment]
You need to put the app in the Tabris.js Developer app, not a browser.  You can download the app here:

[App Store](https://itunes.apple.com/us/app/tabris.js-2/id1166468326?mt=8)
[Play Store](https://play.google.com/store/apps/details?id=com.eclipsesource.tabrisjs2)
[Microsoft Store](https://www.microsoft.com/store/apps/9n8z4pp9chtx)

**Comment by jd048** [comment]
i am started app in local pc and as per documentation in website

**Comment by cookieguru** [comment]
> *In the Developer App*, go to the URL tab, enter the URL printed by the CLI 

Your browser is not the developer app.  Download one of the three aforementioned apps

**Comment by cpetrov** [comment]
Nowadays a QR code will be shown in the browser when navigating to a Tabris CLI server URL. Let us know if you still have this issue @jd048.
