### ISSUE TITLE
Generate APK for android 

### ISSUE THREAD

**Issue by benhartouz** [eclipsesource/tabris-js#1731]
I want to genrate apk of my tabris app and i got this Error : 

Error: /Applications/Android Studio.app/Contents/gradle/gradle-4.4/bin/gradle: Command failed with exit code EACCES
The command /usr/local/lib/node_modules/tabris-cli/node_modules/.bin/cordova exited with 1

**Comment by cookieguru** [comment]
Do you have more of the command output before those two lines?

**Comment by benhartouz** [comment]
This is all the output : 

-------------------------------------------------------

[./] npm run --if-present build:android
[./] npm run --if-present build
[./] Copying Cordova files to build/cordova ...
[./] Copying JavaScript files to build/cordova/www/app ...
[build/cordova/www/app] npm install --production
up to date in 11.242s
[./] Replacing variables in config.xml...
[/usr/local/lib/node_modules/tabris-cli/src/services] npm bin
[build/cordova] /usr/local/lib/node_modules/tabris-cli/node_modules/.bin/cordova build android --no-update-notifier
ANDROID_HOME=/Users/macbook-pro/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
Subproject Path: CordovaLib
Error: /Users/macbook-pro/Documents/Tabaris/build/cordova/platforms/android/gradlew: Command failed with exit code EACCES
The command /usr/local/lib/node_modules/tabris-cli/node_modules/.bin/cordova exited with 1

**Comment by mpost** [comment]
@benhartouz What version of the `tabris-cli` are you using? Does it match your package.json tabris version? What command are you running to build your app?

**Comment by jonek** [comment]
@benhartouz Did you solve your problem in the meantime? Can you use the build service at https://tabris.com?

**Comment by benhartouz** [comment]
closing issue. problem resolved
