### ISSUE TITLE
Firebase integration

### ISSUE THREAD

**Issue by jd048** [eclipsesource/tabris-js#1733]
### Problem description
Hello 
i am enjoying work with tabris framework but if i want to integrate firebase with tabrisjs any documentation or and demo please?

### Environment

- Tabris.js version: 
- Device: 
- OS: 

### Code snippet

```javascript
// A minimal, *self-contained* code snippet to reproduce the problem:
```

**Comment by cookieguru** [comment]
https://github.com/eclipsesource/tabris-plugin-firebase

**Comment by mpost** [comment]
Closing as informed.
