### ISSUE TITLE
Align the values returned with `bounds` property when `padding` is set

### ISSUE THREAD

**Issue by karolszafranski** [eclipsesource/tabris-js#1738]
### Problem description

Currently on iOS `padding` is a "spacing" applied between "outer bounds" and "inner bounds" of the composite. It means that it does not affect `bounds` of any composites. Where "any" means siblings of the `Composite` and its children.

If you have a layout like in the snippet below, `bounds` of any view are not affected by the value of `padding` property.

### Expected behavior

`run-all.js` test does expect that bounds of the `TextView` will be `{left: 8, top: 8}`. In my opinion, it's wrong.

How should it work? Should we update the test or the clients?

### Environment

- Tabris.js version: 3.0.0
- Device: iOS
- OS: any

### Code snippet

**widget-padding.js** snippet

```javascript
import {Composite, TextView, ui} from 'tabris';

let composite = new Composite({
  left: 16, right: 16, top: 16,
  background: 'gray',
  padding: 8
}).appendTo(ui.contentView);

new TextView({
  left: 0, top: 0,
  text: 'Tabris.js'
}).appendTo(composite);
```

**Comment by mpost** [comment]
The padding should not affect the bounds of the widget. The padding takes away from the inner space of the widget.

**Comment by karolszafranski** [comment]
Changes are required in the `run-all.js` test then.

@tbuschto

**Comment by mpost** [comment]
Why would changes be required?

**Comment by tbuschto** [comment]
To clarify. The point here is that "bounds" returns different values on iOS and Android. On iOS the paddings are not included, but they are on Android. Therefore computing the relative positions of two widgets to each other will always fail on one of the two platforms when paddings are involved, depending on how you include padding or not in your calculations.
