### ISSUE TITLE
Incorrect intrinsic size

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1739]
### Problem description

In the following snippet, the TextView container should be as big as the TextView. However, it hugs its sibling.

|Expected layout (Android)| Problematic layout (iOS) |
|---|---|
|![screenshot_20180918-161647_gev](https://user-images.githubusercontent.com/2341769/45693955-88b9d480-bb5e-11e8-9deb-65ec61278c7f.jpg)|![simulator screen shot - iphone 6 - 2018-09-18 at 16 13 52](https://user-images.githubusercontent.com/2341769/45693921-750e6e00-bb5e-11e8-82ab-e76cded5122e.png)|

### Environment

- Tabris.js version: 2.6.1
- OS: 11.4

### Code snippet

```javascript
var {ui, Composite, TextView} = require('tabris');

ui.contentView.append(
  new Composite({left: 0, top: 0, right: 0}).append(
    new TextView({left: 0, centerY: 0, text: 'Hello world'})
  ),
  new Composite({left: 0, top: 'prev()', right: 0, bottom: 0}).append(
    new Composite({left: 0, top: 0, right: 0, bottom: 0}) // replace bottom with a positive height to see random layout behavior
  )
);
```

**Comment by karolszafranski** [comment]
fixed in: https://github.com/eclipsesource/tabris-ios/commit/fbcaf6940c74f65bd151277919bac3584915e946
