### ISSUE TITLE
Scratchpad URL barcode scanner cannot be closed

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1751]
### Problem description

The barcode scanner view is currently full-screen and on iOS there is no way to cancel the scan without terminating the app (on Android, the back button can be used).

### Expected behavior

There should be a "Cancel" button shown over/below the scan view to cancel the barcode scan in case it got started unintentionally.

### Environment

- Tabris.js version: 2.6.1, 3.0.0-dev

**Comment by karolszafranski** [comment]
Is this indeed an iOS bug?

`ESScannerView` from the plugin is a plain view with only camera preview. This allows users to use it in various ways. In the developer app, it's being shown in a `Popover` which also does not provide any UI for the same reason as `ESScannerView` doesn't. 

The only difference between Android and iOS is that devices with the first one have a back button which can be used to close the popover.

Shouldn't we have iOS specific (or maybe even available on both platforms) way of closing this specific popover in this specific app? Shouldn't this be improved in JS? I don't see any good way of fixing this on iOS side.

**Comment by mpost** [comment]
I agree with @karolszafranski. We should be able to close the camera view with a JS provided "close" button. Maybe as a overlay with alpha at the bottom.

**Comment by mpost** [comment]
Implemented.
