### ISSUE TITLE
Tabris.js Developer App No longer Works with Tabris.js 1.x

### ISSUE THREAD

**Issue by wilsonna** [eclipsesource/tabris-js#1753]
I hope I'm wrong about this, but my app no longer loads in the latest Tabris.js developer app dated 30 Sep 2018. When I tapped on my app, I saw a quick flash saying `Could not connect to server. No boot.js found in node_modules/tabris/.`, then it goes back to the app's landing page.

**Comment by wilsonna** [comment]
I managed to reinstall the older version from here, for those in the same predicament as me.
https://apkpure.com/tabris-js/com.eclipsesource.tabris.js

Just wished there was some warning before abandoning 1.x users. Our clients won't pay us to redevelop their app in a newer version of Tabris.js.

**Comment by jonek** [comment]
Thanks for your feedback. Please see my answer here #1747. I keep this issue open until we finally decide how to proceed with the Tabris 1.x developer app.

**Comment by jonek** [comment]
@wilsonna we just released Tabris.js 1.11.0. Please take a look at our release blog post: https://tabris.com/tabris-js-1-11-update/
As the post explains, you can use a debug build of a Tabris.js 1.11.0 app as a replacement for the Developer App.
I will close this issue. Feel free to reopen it if you run into problems.
