### ISSUE TITLE
Tabris CLI Directives

### ISSUE THREAD

**Issue by jokorivai** [eclipsesource/tabris-js#1754]
Is there any way I can use directives with CLI when serving/building?
So in my JS code, I can write code like
```js
{ifdef ENDUSERMODE}
goToDashboard();
{else}
// admin mode
goToUserManager();
{endif}
```
The idea is to minimalize code rewriting, when we are creating multiple app based on single code base.

**Comment by mpost** [comment]
Currently you would have to change a local file to contain a flag (maybe json document) that you would read in your app.
