### ISSUE TITLE
Cannot build application in Tabris 3

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-js#1760]
Log from console:
```
[./] Copying Cordova files to build/cordova ...
[./] Copying JavaScript files to build\cordova\www\app ...
[build\cordova\www\app] npm install --production
added 1 package and audited 52 packages in 1.694s
found 0 vulnerabilities

[./] Replacing variables in config.xml...
[./] Downloading android platform version 3.0.0-dev.20180915...
Unable to download platform: Unexpected status code 404
```
Online build doesn't work either.
```
App uses incompatible tabris version: 3.0.0-dev.20180915, 2.x.x required.
```
But 
![default](https://user-images.githubusercontent.com/26363214/48264748-02c25780-e444-11e8-9af2-0916071d0c31.png)

**Comment by cookieguru** [comment]
I don't know if the Cordova platforms are available for the 3.0.0 nightlies.  Local build should work fine for 3.0.0-beta1 as the platforms are available for [download](https://tabrisjs.com/download/).

The error for the online build is misworded (3.0.x is supported), but will fail for the same reason.  If you select `latest` then it will use the version you specified in your `package.json`.

In either case, try `3.0.0-beta1` in `package.json`

**Comment by fax1ty** [comment]
![screenshot_2](https://user-images.githubusercontent.com/26363214/48312685-0d0f5d80-e5cc-11e8-8e78-d252a80a22f3.png)

**Comment by jonek** [comment]
@fax1ty Please try to use `"tabris": "3.0.0-beta1"` in your `package.json`. That should work for a local build.
Don't use the versions string beginning with the `^`. Please make sure you downgrade your tabris dependency correctly from the nightly version to 3.0.0-beta1.

Currently our build service at https://tabris.com does NOT yet support 3.x builds. We are working on that.

**Comment by cremfert** [comment]
Had the same issue, modified `package.json`, removed ```node_modules``` and did ```npm i``` again. But why is the tabris-cli (installed version 3.0.0-beta1) referring to that old library versions? I just did `tabris init` without any further modifications and ran into the error.

**Comment by jonek** [comment]
@cremfert
1. Are you trying to do a local build or do you want to build on the build service?
2. What do you mean by "referring to that old library versions"?
3. "I just did `tabris init` without any further modifications and ran into the error." To which errors exactly are you referring here?

**Comment by cremfert** [comment]
I'm trying to do a local build. I installed Tabris 3 as mentioned on the webpage by running `npm install tabris-cli@3.0.0-beta1 -g`. Afterwards, I just called `tabris init` and then - without further modifications - `tabris build ios`. Now the CLI tries to download the IOS platform, but fails with a "404 not found" error unless I modify the `package.json`, delete `node_modules` and run `npm i` again. For a complete newbie in Tabris as I am, this feels a little bit unstable (although I know it's a beta).

**Comment by cookieguru** [comment]
What was the version of the `tabris` dependency that didn't work, and the one that did?

**Comment by jonek** [comment]
@cremfert We looked into this and can reproduce it. I opened a new bug in tabris-js-cli project. We already fixed it for the upcoming 3.0.0-beta2 release.

In the mean time please work around this issue by updating the `package.json` manually after `tabris init`.

**Comment by ishigo1987** [comment]
I have the same problem i can't build online

**Comment by fax1ty** [comment]
Any progress? 
![image](https://user-images.githubusercontent.com/26363214/54884485-2504c100-4e8b-11e9-9d4a-fe323abe2dcf.png)

**Comment by jonek** [comment]
Hi @ishigo1987 and @fax1ty.
Local build of Tabris apps agains `3.0.0-beta2` work as expected, BUT you have to take care about some aspects.
1. Your project's `package.json` has to pin the tabris version like this: `"tabris": "3.0.0-beta1"` Do **not** use the `^` in front of the tabris version in your `package.json` as long as you use a beta release.
2. You have to have a globally installed tabris-cli corresponding to the version of tabris that you specified in your `package.json`. `npm i -g tabris-cli@3.0.0-beta2`
3. You must **not** use `npm  audit fix` when you see
```
found 4 vulnerabilities (1 low, 1 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```
after you installed the tabris-cli globally!
4. Now a local Android build works as expected like this `tabris build android`

Please confirm that you can execute a local build like this. Thanks for your feedback!

**Comment by ishigo1987** [comment]
i'm not using local build
Online build work great?

**Comment by jonek** [comment]
We are currently fixing the build service to support `3.0.0-beta2` builds for Android properly.

**Comment by ishigo1987** [comment]
thank you

**Comment by jonek** [comment]
@ishigo1987 the build service does support Tabris `3.0.0-beta2` builds for Android and iOS now.
Please confirm that it works for you and feel free to close this issue if it does.

**Comment by ishigo1987** [comment]
@jonek i will try a build tomorrow and i will let you know

**Comment by maoamid** [comment]
@jonek:
- using "tabris": "^3.0.0-beta2" in my .json file (tabris init v3 beta 2 defaults ), the cloud build failed in the same, trying to push v2 dependencies 
- using "tabris": "3.0.0-beta1" The build failed like this in the end:
`Running "tabris_cli_build" task
Running "shell:tabris_cli_android_build" (shell) task
[./] npm run --if-present build:android
[./] npm run --if-present build
> @ build /home/travis/build/eclipsesource/tabris-js-build-template/build
> tsc -p .
src/app.tsx(1,46): error TS2305: Module '"../node_modules/tabris/tabris"' has no exported member 'contentView'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ build: `tsc -p .`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-03-27T05_59_26_250Z-debug.log
The command npm exited with 2
Warning: Command failed: tabris build android  --debug --device --verbose --cordova-build-config="../../../tabrisBuildConfig.json"
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ build: `tsc -p .`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-03-27T05_59_26_250Z-debug.log
The command npm exited with 2
 Use --force to continue.
Aborted due to warnings.
travis_time:end:0add405a:start=1553666360264247185,finish=1553666366287740448,duration=6023493263
The command "grunt build deploy" exited with 6.
Done. Your build exited with 1.`

**Comment by maoamid** [comment]
the error is fixable using ui.contentView instead, I think, but it's strange to generate a blank project with tabris-cli and not build on cloud for newcomers. If v3 beta2 will have a short life until the final release, is not big deal anyway.

**Comment by fax1ty** [comment]
![image](https://user-images.githubusercontent.com/26363214/55289070-756fa780-53d2-11e9-8421-b4dacaab2f1c.png)
tabris 3 rc-1
hooray!

**Comment by fax1ty** [comment]
![image](https://user-images.githubusercontent.com/26363214/58697052-ea973300-83a9-11e9-8b8e-18b2e87e90a3.png)
![image](https://user-images.githubusercontent.com/26363214/58697113-069ad480-83aa-11e9-99bc-848c10029027.png)

**Comment by fax1ty** [comment]
Also
![image](https://user-images.githubusercontent.com/26363214/58697415-8759d080-83aa-11e9-9ff4-a55eeed6eb9d.png)

**Comment by mpost** [comment]
@fax1ty Could you try to `tabris clean`?

**Comment by fax1ty** [comment]
> @fax1ty Could you try to `tabris clean`?

![image](https://user-images.githubusercontent.com/26363214/58725603-9bc0bc00-83f0-11e9-9038-7ef6718c934d.png)
The same

**Comment by mpost** [comment]
I presume it does work in the tabris.com build service?

**Comment by cookieguru** [comment]
> The only way to connect is doing it via external IP

This sounds more like a network issue.  Does `http://192.168.37.1:8080/package.json` work in a browser on the same device?

**Comment by fax1ty** [comment]
> The only way to connect is doing it via external IP

I fixed this issue, but how about building?

**Comment by cookieguru** [comment]
@fax1ty Does it work on the Tabris.js build service online?

**Comment by fax1ty** [comment]
> @fax1ty Does it work on the Tabris.js build service online?

nope

**Comment by fax1ty** [comment]
Well, I just initialized new app in 3.0.1. I tried to build it locally. Failure.
![image](https://user-images.githubusercontent.com/26363214/59103093-f00ef300-893e-11e9-874e-b2c49a8579b5.png)
Then I tried to build it with Cloud Build Service. Doesn't it support version 3.0 yet?
![image](https://user-images.githubusercontent.com/26363214/59104343-682ae800-8942-11e9-9d8e-cefec2dfa9d0.png)
```App uses incompatible tabris version: 3.0.0, 2.x.x required.```

**Comment by mpost** [comment]
3.0.1 is not out yet. A release is generally available as soon as we announce it on the tabris.com blog.

**Comment by fax1ty** [comment]
But I can't build locally in 3.0.0 too

**Comment by mpost** [comment]
in the online build?

**Comment by fax1ty** [comment]
> in the online build?

I just tried to build a test blank app and it was successfully built. 
Oh, how I can see, everything is fine with 3.0.0 in the Cloud. I will try to build the main app.

(P.S. But I still can't build locally)

**Comment by fax1ty** [comment]
Ohhh, yeah, I got a new error message.
![image](https://user-images.githubusercontent.com/26363214/62009178-54934500-b16d-11e9-8edb-1c8159ce3fef.png)

Also, I can't specify Android SDK version in Cloud Build. It is always 25 even if I use the `android-targetSdkVersion` flag
```xml
<preference name="android-targetSdkVersion" value="27" />
```
One of my plugins requires SDK 27. This causes the build to fail.
![image](https://user-images.githubusercontent.com/26363214/62009370-6aa20500-b16f-11e9-93ca-d80d7c0ddd97.png)
![image](https://user-images.githubusercontent.com/26363214/62009356-434b3800-b16f-11e9-8fdd-45835793f998.png)

**Comment by mpost** [comment]
The error message is correct in regards to the license agreement. You can either accept it in android studio or follow eg https://stackoverflow.com/questions/38096225/automatically-accept-all-sdk-licences

**Comment by fax1ty** [comment]
It's in your cloud build not on my own machine

**Comment by mpost** [comment]
Thanks for the info. Btw, the `Android SDK Tools Version` is not the same as the `android target SDK` verision. None the less the issue is valid of course.

**Comment by jonek** [comment]
@fax1ty Your build problems should be resolved in our online build service now.
Please trigger your build again.
Feel free to re-open this issue if you run into problems again.

**Comment by fax1ty** [comment]
The same with 3.1 (

![image](https://user-images.githubusercontent.com/26363214/62483915-ecc2a700-b7c9-11e9-8ef8-3f80e4f1db22.png)

(All specified files exist in the specified paths)

**Comment by jonek** [comment]
@fax1ty You screenshot seems to indicate that you got this error when doing a local build.
Did you have any problems build at our online build service?

**Comment by fax1ty** [comment]
Online build work as expected perfectly, but what with local builds? From time to time I need to build something locally. Any thoughts?

**Comment by tbuschto** [comment]
@fax1ty 
Can you post (and possibly update) your npm, node and tabris-cli versions?
```
npm --version
node --version
tabris --version
```

**Comment by fax1ty** [comment]
![image](https://user-images.githubusercontent.com/26363214/62550868-045a6800-b87c-11e9-80d9-b02e59b55640.png)
### Latest versions:
Node: 
![image](https://user-images.githubusercontent.com/26363214/62550913-1dfbaf80-b87c-11e9-821e-d91fb841a22f.png)
NPM: 
![image](https://user-images.githubusercontent.com/26363214/62551088-69ae5900-b87c-11e9-831e-2c53311eb695.png)
Tabris: 
![image](https://user-images.githubusercontent.com/26363214/62551127-7af76580-b87c-11e9-901c-efd7c74a9dc1.png)

I don't think that problem in minor NPM update but.... I can update it if you want

**Comment by cpetrov** [comment]
@fax1ty Your Tabris CLI cache might be broken, could you try deleting the `C:\Users\fax1ty\.tabris-cli` folder?

**Comment by fax1ty** [comment]
@cpetrov done, but nothing new except requesting building key
![image](https://user-images.githubusercontent.com/26363214/64065084-0b299000-cc1a-11e9-9d44-9a901df39c93.png)
