### ISSUE TITLE
Support fonts and colors within a TextView with markupEnabled

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#1761]
Something like this: 
```js
textView.set({
  markupEnabled: true, 
  text: 'Hello <span font='arial' textColor='blue'>World</span>'
});
```

Should also allow to style `<a/>` tags.

**Comment by tbuschto** [comment]
Not sure about the syntax, also to what degree is this possible on iOS?

**Comment by mpost** [comment]
We could build such a thing on top of the ability to load external fonts.

**Comment by patrykmol** [comment]
iOS part has been already implemented as far as I can tell.
