### ISSUE TITLE
Document which Tabris.js version is built on which Cordova version

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js#1763]
Currently it is not possible for a user to see which version of Tabris.js (a specific Tabris.js platform) is built on which version of the upstream Cordova platform.

This could be part of the documentation.

**Comment by cookieguru** [comment]
+1
Not just the Cordova version but also OS versions supported.

**Comment by mpost** [comment]
@cookieguru Yes agreed. We will update the documentation accordingly.

**Comment by tbuschto** [comment]
Platform versions are in the FAQ now (repo, not deployed yet).
