### ISSUE TITLE
Popover broken on Android <= 5

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js#1765]
Executing the popover snippet from the playground in the Tabris.js 2 developer app (2.6.3-20181122-0504) on a Android 5.1.1 looks like this:
![screenshot_2018-11-22-19-21-50](https://user-images.githubusercontent.com/185295/48919034-b5f16e80-ee90-11e8-83b7-4aebadc24f75.png)

**Comment by mpost** [comment]
Thanks for the info we will look into the issue.

**Comment by mpost** [comment]
Issue has been fixed and back-ported to 2.x
