### ISSUE TITLE
border and filter (more?) from CSS to native

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-js#1768]
I need to make a button with `background` and `border`. 

![default](https://user-images.githubusercontent.com/26363214/49148591-3399fc00-f321-11e8-8c10-7f201dd51cfd.png)

If the `background` property is already implemented in Tabris, the second one is mentioned only in `TextInput` and `Picker` ([borderColor](http://docs.tabris.com/latest/api/Picker.html#bordercolor)). It would be very cool if `Composite` widget had access to the css `border` property

Also I need to recreate this button:

![default](https://user-images.githubusercontent.com/26363214/49147470-3810e580-f31e-11e8-93d3-00ca2e8e5d58.png)

and I need drop-shadow [filter](https://developer.mozilla.org/en-US/docs/Web/CSS/filter) or at least [box-shadow](https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow)

Alas, from similar there is only uncontrollable [elevation](http://docs.tabris.com/latest/api/Widget.html#elevation) for now 😭 

I know that at this moment I can use `WebView` for this, but will more CSS features be implemented (and if so, when?) in Tabris as native?

**Comment by mpost** [comment]
We are planning to expand the `Button` styling capabilities as you can follow here: https://github.com/eclipsesource/tabris-js/issues/683.

At the moment you could use a `Canvas` to draw the button appearance that you want to achieve.

**Comment by josiahking** [comment]
Yea, it will be nice to see more styling options for native widget.

**Comment by mpost** [comment]
We have added support for multiple styling options in (the now closed) #683.
