### ISSUE TITLE
Android build fails with gradle

### ISSUE THREAD

**Issue by josiahking** [eclipsesource/tabris-js#1773]
### Problem description

Tabris build does not use the latest version of cordova.

### Expected behavior

I added a plugin called Layar, while building the android app, i encountered an error:
A problem occured evaluating root project 'android'.
Could not find method exclude() for arguments [{module=CordovaLib}] on project :com.layar.cordova.LayarPlugin:layar_sdk of type org.gradle.api.Project.

### Environment

- Tabris.js version: 2.0
- Device: PC
- OS: Windows

### Code snippet

```javascript
// Issue is with this code generated by gradle named build.gradle
implementation project(":com.layar.cordova.LayarPlugin:layar_sdk"){
        exclude module:("CordovaLib")
    }
```

**Comment by mpost** [comment]
@josiahking You should update your tabris version to the latest 2.6.x.

**Comment by josiahking** [comment]
I think the issue is caused by the plugin.
