### ISSUE TITLE
Question - How to use a different Cordova version to build

### ISSUE THREAD

**Issue by josiahking** [eclipsesource/tabris-js#1774]
### Problem description

I noticed that tabrisjs uses older version of cordova to build app

### Expected behavior

I expected it to use a more recent version.
How can i specify a different version of cordova for tabrisjs to use for building app?

**Comment by mpost** [comment]
The cordova version is always tied to a specific tabris release. eg tabris android 3.x will use cordova 7.x whereas tabris 2.6 uses cordova 6.4.x

**Comment by josiahking** [comment]
Is it possible to set the 2.6 to use a higher cordova version?

**Comment by cookieguru** [comment]
@josiahking No, but you can update your `tabris` dependency in `package.json` to use `3.0.0-beta1`.  There's a [Migration Guide for 2.x to 3.0-beta1](https://github.com/eclipsesource/tabris-js/blob/master/doc/migration-guide.md)

**Comment by josiahking** [comment]
Alright, thanks for the update.
