### ISSUE TITLE
Hot reloading App after save

### ISSUE THREAD

**Issue by josiahking** [eclipsesource/tabris-js#1777]
### Problem description

How can i make tabris reload development app(client) after saving a file, I can't find this feature anywhere on the doc.

### Expected behavior

After saving a file, instead of starting the app(2.0) afresh, i want to see the new changes or error message.

### Environment

- Tabris.js version: 2.6.3
- Device: Samsung Galaxy Grand
- OS: Android 6

**Comment by josiahking** [comment]
I saw an option to swipe from the right to get the developer app console.
But a need to auto load the app after save is still important.

**Comment by cookieguru** [comment]
Auto reloading isn't available in Tabris 2.x, but it is available in 3.0, which is currently in beta.  With `tabris-cli@3.0.0-beta1` installed you can run [`tabris serve -a`](https://github.com/eclipsesource/tabris-js-cli/#-a---auto-reload) for automatic reloading when a source file is modified.

**Comment by josiahking** [comment]
@cookieguru Thanks for the update.
It seems tabris-cli 3.0 is loading with features.
