### ISSUE TITLE
No progress indication when reloading app

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js#1778]
### Problem description

1. Open your a Tabris.js application (with activated developer console) on an iOS device
2. open the developer console
3. reload from development server
4. no progress indication is shown until app restarts

### Expected behavior

Developer console stays open showing some progress indicator until resources are loaded from server.
Then the developer console closes and the app restarts.

### Environment

- Tabris.js version: 2.x
- Device: iPad 9.7 6th gen
- OS: iOS 12.1.1

**Comment by mpost** [comment]
Closing this in favor of https://github.com/eclipsesource/tabris-js/issues/1778.

**Comment by cookieguru** [comment]
@mpost Same issue?

**Comment by mpost** [comment]
@cookieguru Corrected the link.
