### ISSUE TITLE
App does not scroll for overflow content

### ISSUE THREAD

**Issue by josiahking** [eclipsesource/tabris-js#1779]
### Problem description

I noticed that the content (TextView, TextInput, etc widgets) on my app doesn't scroll, even after i changed the orientation of the device.
Is there any settings or config to enable page or contentView scrolling 

### Expected behavior

Vertically overflow content of the screen should be scrollable.

### Environment

- Tabris.js version: 2.6.3
- Device: Samsung Galaxy Grand Prime Plus
- OS: Android 6

### Code snippet

```javascript
// A minimal, *self-contained* code snippet to reproduce the problem:
```

**Comment by mpost** [comment]
You should place your content inside a `ScrollView`.

**Comment by josiahking** [comment]
Thanks scrollView fixed this, didn't see it earlier.
