### ISSUE TITLE
Back navigationView event capture

### ISSUE THREAD

**Issue by josiahking** [eclipsesource/tabris-js#1780]
### Problem description

How can i capture event for the navigationView back icon action on click?

### Expected behavior

A method to capture the event.

### Environment

- Tabris.js version: 2.6.3
- Device: Samsung Galaxy Grand
- OS:  Android 6

### Code snippet

```javascript
app.on(
			'backNavigation',
			() => {
			console.log('nav')
			navigationView.toolbarVisible = false
			}
		); //works when device back button is pressed
		document.addEventListener("backbutton", () => console.log('back triggered'), false); doesn't work
		navigationView.on('navigationActionChanged', () => console.log('changed')) //doesn't work
```

**Comment by cookieguru** [comment]
Use the `dispose` event on the Page.

Note there's also a [Slack channel](https://tabrisjs.herokuapp.com/) for general questions (not issues) like this.

**Comment by josiahking** [comment]
Thanks the dispose event works.
