### ISSUE TITLE
Keyboard open; Unexpected layout when status bar is hide 

### ISSUE THREAD

**Issue by emitterpark** [eclipsesource/tabris-js#1781]
When StatusBar is hide, an unexpected layout behaviour. When keyboard is opened by TextInput focus, ContentView Resize is missing and ovelapping composite widget. Altough widget sizing is "bottom" relative. 
Expected is widget go up.
Platform Android. 

```js
const {TextInput, Composite, ui} = require('tabris');
  
//ui.statusBar.displayMode = 'hide';

let comp = new Composite({
  bottom: 100, centerX: 0, width: 300, height: 100,
  background: 'green'
}).appendTo(ui.contentView);


new TextInput({
  top: 30, centerX: 0, width: 200
}).appendTo(comp);`  
```

Platform: Android
Tabris.js 2.6

**Comment by elshadsm** [comment]
This is the known behavior and in case of setting `hide` and `float` value to the displayMode, the app switches to the full-screen mode. I don't know if it is a bug or policy, according to the [documentation](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#FLAG_FULLSCREEN), in that case, `...the window will stay fullscreen and will not resize`. Additionally, a couple of issues were reported to Google like [this](https://issuetracker.google.com/issues/36986276) and [this](https://issuetracker.google.com/issues/36911528). Also, you can find stackoverflow questions like [this](https://stackoverflow.com/questions/39115148/keyboard-overlaps-edittext-activity-fullscreen) and [this](https://stackoverflow.com/questions/7417123/android-how-to-adjust-layout-in-full-screen-mode-when-softkeyboard-is-visible).

**Comment by emitterpark** [comment]
as @elshadsm commented, and in the reports, a full screen meant a single static page. It seems native. And out of this framework scope.
