### ISSUE TITLE
Some intrinsically sized widgets overgrow their expected size

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1783]
### Problem description

In the particular constellation from the code snippet, the red composite will unexpectedly fill available vertical space in Tabris.js 2.6.3. Behaves as expected in Tabris.js 2.5.1.

|2.5.1 (expected)|2.6.3|
|---|---|
|![img_9a7dcfa46d62-1](https://user-images.githubusercontent.com/2341769/51829701-66934880-22ee-11e9-9fd2-3c43acf8c639.jpeg)|![img_a56640a02f7e-1](https://user-images.githubusercontent.com/2341769/51829712-6dba5680-22ee-11e9-90a6-5c49c7941cb7.jpeg)|

### Expected behavior

The red composite should should hug its blue child instead.

### Variations

Changing the `TabFolder` from the snippet to a `Composite` results into the problem occurring in Tabris.js 2.5.1 as well.

### Environment

- Tabris.js version: 2.6.2, nightly
- Device: iPhone SE
- OS: iOS 11.4.1

### Code snippet

```javascript
const {Composite, TabFolder, ui} = require('tabris');

ui.contentView.append(
  new Composite({left: 0, top: 0, right: 0, background: 'red'}).append(
    new Composite({left: 0, right: 0, centerY: 0, height: 100, background: 'blue'})
  ),
  new Composite({left: 0, top: 'prev()', right: 0, bottom: 0, background: 'gray'}).append(
    new TabFolder({left: 0, top: 'prev()', right: 0, bottom: 0})
  )
);
```

**Comment by cpetrov** [comment]
Making the TabFolder a sibling of the red composite works around the problem.

**Comment by mpost** [comment]
Can this issue also be observed in 3.x?

**Comment by cpetrov** [comment]
@mpost Cannot reproduce this in Tabris.js 3 beta 2

**Comment by mpost** [comment]
Ok. Closing as resolved.
