### ISSUE TITLE
ImageView: background & highlightOnTouch Conflict

### ISSUE THREAD

**Issue by raphaelpreston** [eclipsesource/tabris-js#1785]
The properties 'background' and 'highlightOnTouch' conflict with each other and the resulting object displays differently depending on the order in which the properties are defined.

```javascript
new tabris.ImageView({
    width: 128,
    height: 128,
    centerX: 0,
    centerY: 0,
    cornerRadius: 65,
    elevation: 8,
    image: "src/images/icon.png",
    // -- background first, then highlightOnTouch second
    background: 'red',
    highlightOnTouch: true
    // --
}).appendTo(ui.contentView);
```
yields the image as shown in the screenshot below.
![good](https://user-images.githubusercontent.com/46331908/52092659-7a041500-2575-11e9-9e1c-0bfc2ea803d9.png)

When the order is switched, as seen in the following code snippet...
```javascript
new tabris.ImageView({
    width: 128,
    height: 128,
    centerX: 0,
    centerY: 0,
    cornerRadius: 65,
    elevation: 8,
    image: "src/images/icon.png",
    // -- highlightOnTouch FIRST, then background SECOND
    highlightOnTouch: true,
    background: 'red'
    // --
}).appendTo(ui.contentView);
```
The result looks like this:
![bad](https://user-images.githubusercontent.com/46331908/52092661-7cff0580-2575-11e9-9b4a-4296016ef248.png)

I just migrated over to 3.0.0-beta1; this wasn't an issue in 2.x.x as far as I was aware.

**Comment by mpost** [comment]
Thanks for the info. This is of course not expected. What platform are you seeing this behavior on?

**Comment by raphaelpreston** [comment]
Platform is iOS 11.1.1

**Comment by karolszafranski** [comment]
Thanks, we will check it soon.
