### ISSUE TITLE
WebView Change Events Not Triggering

### ISSUE THREAD

**Issue by raphaelpreston** [eclipsesource/tabris-js#1786]
### Problem description
When navigating using a WebView, the ChangeEvents associated with certain properties are not firing, even when those properties are indeed changing. 

### Environment
- Tabris.js version: 3.0.0-beta1
- iOS 11.1.1

Here is some code I wrote to illustrate the problem
```javascript
/* webview */
let wv = new WebView({
	top: 0,
	bottom: '#toolbar',
	left: 0,
	right: 0,
	url: "https://www.duckduckgo.com"
})
.on('canGoBackChanged', () => console.log('canGoBackChanged triggered'))
.on('canGoForwardChanged', () => console.log('canGoForwardChanged triggered'))
.on('urlChanged', () => console.log('urlChanged triggered'))
.on('htmlChanged', () => console.log('htmlChanged triggered'))
.on('load', () => console.log('load triggered'))
.on('navigate', () => console.log('navigate triggered'))
.on('download', () => console.log('download triggered'))
.on('message', () => console.log('message triggered'))
.appendTo(ui.contentView);

/* log properties */
new Button({
	id: 'toolbar',
	left: 0,
	right: '#goback',
	bottom: 0,
	top: '90%',
	text: 'Log Properties'
}).on('select', () => {
	console.debug("canGoBack: " + wv.canGoBack);
	console.debug("canGoForward: " + wv.canGoForward);
	console.debug("url: " + wv.url);
	console.debug("html: " + wv.html);
})
.appendTo(ui.contentView);

/* go back */
new Button({
	id: 'goback',
	left: '#toolbar',
	right: 0,
	bottom: 0,
	top: '90%',
	text: 'Go Back'
}).on('select', () => {
	wv.goBack();
}).appendTo(ui.contentView);
```

After running the code above, here is the console output, with comments to explain when which actions were performed:

```html
<!-- initial appending to contentView -->
navigate triggered
navigate triggered
navigate triggered
load triggered

<!-- properties logged -->
canGoBack: false
canGoForward: false
url: https://duckduckgo.com/
html: undefined

<!-- searching for "test" -->
navigate triggered
navigate triggered
load triggered

<!-- properties logged -->
canGoBack: true
canGoForward: false
url: https://duckduckgo.com/?q=test&t=h_&ia=news
html: undefined

<!-- calling .goBack() -->
navigate triggered
load triggered

<!-- logging properties -->
canGoBack: false
canGoForward: true
url: https://duckduckgo.com/
html: undefined
```

As far as I can tell, `canGoBackChanged`, `canGoForwardChanged`, and `urlChanged` should be firing, as it is clear that their values are changing. I understand why `download`, `htmlChanged`, and `message` aren't being triggered, but I figured I'd include them for completeness. 

In the above example, `navigate` and `load` are triggered on every navigation, but I've also run into cases where they don't fire when they're supposed to as well. Here is another annotated console log, showing what happens when the URL is initially set as [this tweet](https://twitter.com/tabrisjs/status/1089827821487312897):

```html
<!-- initial appending -->
navigate triggered
navigate triggered
load triggered

<!-- log properties -->
canGoBack: false
canGoForward: false
url: https://mobile.twitter.com/tabrisjs/status/1089827821487312897
html: undefined

<!-- navigating to Tabris.js user page -->

<!-- log properties -->
canGoBack: true
canGoForward: false
url: https://mobile.twitter.com/tabrisjs
html: undefined

<!-- navigating to a different tweet -->

<!-- log properties -->
canGoBack: true
canGoForward: false
url: https://mobile.twitter.com/tabrisjs/status/1075320982909407232
html: undefined

<!-- calling .goBack() -->

```

In my particular use case, the goal is to darken a back button if the WebView cannot navigate back. As of now, I initialize the button as dark, but there is no way to tell when the WebView becomes able to navigate back without a reliable event to listen to.

Thanks in advance!

**Comment by mpost** [comment]
Thanks for the heads up. We will investigate the issue.

**Comment by patrykmol** [comment]
Hello. I can confirm issues with events you have listed except for `download` and `message`. `download` is Android-only event.

**Comment by patrykmol** [comment]
Fixes will be available in next nightly. Closing.

**Comment by raphaelpreston** [comment]
I just finished migrating to 3.0.0-beta2, and unfortunately I'm still facing these issues.

### Environment
- Tabris-js version: 3.0.0-beta2
- iPhone 7 iOS 11.1.1
- Serving from Windows 10 with CLI 3.0.0-beta2, using developer app version 3.0.1.

### Example
Using the same snippet as my original post (after removing `ui`), I re-ran the original tests.

The following is output when the first URL is `'www.duckduckgo.com'` .
```html
<!-- initial appending to contentView -->
navigate triggered
urlChanged triggered
navigate triggered
urlChanged triggered
navigate triggered
urlChanged triggered
load triggered

<!-- properties logged -->
canGoBack: false
canGoForward: false
url: https://duckduckgo.com/
html: undefined

<!-- searching for "test" -->
navigate triggered
urlChanged triggered
navigate triggered
canGoBackChanged triggered
urlChanged triggered
load triggered

<!-- properties logged -->
canGoBack: true
canGoForward: false
url: https://duckduckgo.com/?q=test&t=h_&ia=web
html: undefined

<!-- calling .goBack() -->
navigate triggered
canGoBackChanged triggered
canGoForwardChanged triggered
urlChanged triggered
load triggered

<!-- logging properties -->
canGoBack: false
canGoForward: true
url: https://duckduckgo.com/
html: undefined
```
Although it seems that the event `urlChanged` was indeed fixed, as far as I can tell, `canGoBackChanged` and `canGoForwardChanged` should be firing, as it is clear that their values are changing.

I'm also running into the same problems with some sites (like Twitter) as I was in my original post; however, in addition, now it seems that the `canGoBack` and `canGoForward` properties (that were correctly updating as of my original post) are no longer maintaining the correct values. The following is output when the first URL is [this tweet](https://twitter.com/tabrisjs/status/1089827821487312897).
```html
<!-- initial appending -->
navigate triggered
urlChanged triggered
navigate triggered
urlChanged triggered
load triggered

<!-- log properties -->
canGoBack: false
canGoForward: false
url: https://mobile.twitter.com/tabrisjs/status/1089827821487312897
html: undefined

<!-- nativating to Tabris.js user page -->

<!-- log properties -->
canGoBack: false <!-- this should be true, as it was in the original post -->
canGoForward: false
url: https://mobile.twitter.com/tabrisjs
html: undefined

<!-- calling .goBack() -->

<!-- log properties -->
canGoBack: false
canGoForward: false <!-- this should be true -->
url: https://mobile.twitter.com/tabrisjs/status/1089827821487312897
html: undefined
```

As a work-around to the original issues I was having, I used `setInterval()` to check `canGoBack` and `canGoForward` every 500ms to see if the user could go back/forward, but since those properties are no longer reliable, I'm not sure if there even is a work-around anymore.

Thanks again for the help!

**Comment by patrykmol** [comment]
Hello. I will investigate this again. Reopening.

(Feel free to reopen issues if you think they are still valid.)

**Comment by patrykmol** [comment]
I have checked your original snippet and I cannot confirm the behaviour you are talking about. Also in your recent log you can see lines `canGoBackChanged triggered` and `canGoForwardChanged triggered`. I have also modified your snippet to test it with the link you have provided and both events and properties are working correctly from what I can tell.

Here's my modified snippet
```
/* webview */
let wv = new WebView({
	top: 0,
	bottom: '#toolbar',
	left: 0,
	right: 0,
	url: "https://twitter.com/tabrisjs/status/1089827821487312897"
})
.on('canGoBackChanged', () => console.log('canGoBackChanged triggered'))
.on('canGoForwardChanged', () => console.log('canGoForwardChanged triggered'))
.on('urlChanged', () => console.log('urlChanged triggered'))
.on('htmlChanged', () => console.log('htmlChanged triggered'))
.on('load', () => console.log('load triggered'))
.on('navigate', () => console.log('navigate triggered'))
.on('download', () => console.log('download triggered'))
.on('message', () => console.log('message triggered'))
.appendTo(contentView);

/* log properties */
new Button({
	id: 'toolbar',
	left: 0,
	right: '#goback',
	bottom: 0,
	top: '90%',
	text: 'Log Properties'
}).on('select', () => {
	console.debug("canGoBack: " + wv.canGoBack);
	console.debug("canGoForward: " + wv.canGoForward);
	console.debug("url: " + wv.url);
	console.debug("html: " + wv.html);
})
.appendTo(contentView);

/* go back */
new Button({
	id: 'goback',
	left: '#toolbar',
	right: '#url',
	bottom: 0,
	top: '90%',
	text: 'Go Back'
}).on('select', () => {
	wv.goBack();
}).appendTo(contentView);

new Button({
	id: 'url',
	left: '#goback',
	right: 0,
	bottom: 0,
	top: '90%',
	text: 'url'
}).on('select', () => {
	wv.url = "https://tabrisjs.com/patrykmol/playground";
}).appendTo(contentView);
```

Such snippet produces following log:

```
<!-- initial load -->
navigate triggered
urlChanged triggered
navigate triggered
urlChanged triggered
load triggered

<!-- set url to tabris.js.com -->
urlChanged triggered
navigate triggered
urlChanged triggered
navigate triggered
urlChanged triggered
canGoBackChanged triggered
load triggered

<!-- go back -->
navigate triggered
canGoBackChanged triggered
canGoForwardChanged triggered
urlChanged triggered
load triggered
```

iOS 11 screenshot

![ios11](https://user-images.githubusercontent.com/12428999/53815482-0a14f000-3f62-11e9-951b-b76fea11996f.png)

iOS 12 screenshot

![ios12](https://user-images.githubusercontent.com/12428999/53815483-0a14f000-3f62-11e9-9417-adeade81b807.png)

Can you verify on your are seeing such behaviour as well? If you are still having problems with these events/properties can you provide an updated snippet where I can reproduce these issues?

Thanks!

**Comment by raphaelpreston** [comment]
You're totally right @patrykmol. I misspoke in part of my original post. The `canGoBackChanged` and `canGoForwardChanged` events are indeed firing for most URLs, including `tabris.js.com` and `duckduckgo.com`. The problem I'm running into is on Twitter.

After using your snippet (thanks for making that) to test further, I've discovered that if you set the `WebView.url` manually, then everything works fine, even if you're navigating within the Twitter domain.

```html
<!-- initial URL: https://twitter.com/tabrisjs/status/1089827821487312897 -->
<!-- button URL: secondary: https://twitter.com/tabrisjs-->

<!-- initial load -->
navigate triggered
urlChanged triggered
navigate triggered
urlChanged triggered
load triggered

<!-- url button tapped -->
urlChanged triggered
navigate triggered
urlChanged triggered
navigate triggered
urlChanged triggered
canGoBackChanged triggered <!-- expected behavior -->
load triggered

<!-- go back -->
navigate triggered
canGoBackChanged triggered
canGoForwardChanged triggered <!-- expected behavior -->
urlChanged triggered
load triggered
```

The problem occurs when you physically tap within the WebView to navigate (which is how I would assume the majority of WebView navigation would take place).
```html
<!-- initial URL: https://twitter.com/tabrisjs/status/1089827821487312897 -->
<!-- button URL: N/A -->

<!-- initial load -->
navigate triggered
urlChanged triggered
navigate triggered
urlChanged triggered
load triggered

<!-- tap on tabris.js user profile -->
...      <!-- webpage loads and functions as normal, nothing logged -->

<!-- go back -->
...      <!-- webpage loads and functions as normal, nothing logged -->
```

As you can see, nothing at all is triggered when physically tapping within the WebView on Twitter. I haven't tested for other sites, but I'm assuming that Twitter is not the only site that produces unexpected behavior.

Thanks @patrykmol for all the help.

**Comment by patrykmol** [comment]
Thanks you for the snippet. I will let you know when I know something.

**Comment by patrykmol** [comment]
It seems that native web view is not firing proper delegate methods when there is in-page JavaScript operation. This won't be a trivial issue to fix even if it is possible. I will keep you posted.

**Comment by patrykmol** [comment]
@raphaelpreston `WebView` has a `evaluate` method. Maybe you could inject some JS code that could help you. This is just a suggestion. I do not know if this will help you.

**Comment by raphaelpreston** [comment]
Thanks @patrykmol for all the help. I'll look into the `evaluate` method.

**Comment by cookieguru** [comment]
I believe this has to do with [`history.pushState()`](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState)

I used this slightly modified snippet:
```js
let wv = new WebView({
	top: 0,
	bottom: '#toolbar',
	left: 0,
	right: 0,
	url: 'http://html5doctor.com/demos/history/',
})
.on('canGoBackChanged', ({value}) => console.log(`canGoBack changed to ${value}`))
.on('canGoForwardChanged', ({value}) => console.log(`canGoForward changed to ${value}`))
.on('urlChanged', ({value}) => console.log(`url changed to ${value}`))
.on('htmlChanged', () => console.log('htmlChanged triggered'))
.on('load', () => console.log('load triggered'))
.on('navigate', ({url}) => console.log(`navigate triggered to ${url}`))
.on('download', () => console.log('download triggered'))
.on('message', () => console.log('message triggered'))
.appendTo(contentView);

/* log properties */
new Button({
	id: 'toolbar',
	left: 0,
	right: '#goback',
	bottom: 0,
	top: '90%',
	text: 'Log Properties',
}).on('select', () => {
	console.debug('canGoBack: ' + wv.canGoBack);
	console.debug('canGoForward: ' + wv.canGoForward);
	console.debug('url: ' + wv.url);
	console.debug('html: ' + wv.html);
})
.appendTo(contentView);

/* go back */
new Button({
	id: 'goback',
	left: '#toolbar',
	right: '#url',
	bottom: 0,
	top: '90%',
	text: 'Go Back',
}).on('select', () => {
	wv.goBack();
}).appendTo(contentView);

new Button({
	id: 'url',
	left: '#goback',
	right: 0,
	bottom: 0,
	top: '90%',
	text: 'url',
}).on('select', () => {
	wv.url = 'http://html5doctor.com/demos/history/';
}).appendTo(contentView);
```

I tapped on cat names several times, and the console only outputs the following:

```plain
navigate triggered to http://html5doctor.com/demos/history/
url changed to undefined
load triggered

 (tap Log properties)
canGoBack: false
canGoForward: false
url: http://html5doctor.com/demos/history/
html: undefined
```
The Go Back button _did_ work as expected.


Several unsubstantiated claims indicate that iOS has added its own security around the history API.  I'm willing to bet Twitter is leveraging the `pushState` method for their SPA.

I don't know if it would be possible to inject an [`onpopstate`](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onpopstate) handler using the aforementioned `evaluate` method.  [This answer](https://stackoverflow.com/a/6168151) has a possible workaround and [this answer](https://stackoverflow.com/a/42381895) also has some other suggestions.  Having it on a third party site significantly complicates the matter.

**Comment by patrykmol** [comment]
You are right @cookieguru. I have found similar reports regarding WKWebView and `history.pushState()` on the Internet. However I might have found a workaround for several events. That still needs some fine-tuning on native side.

`evaluate` has option to execute some JS code. However Tabris JS VM and WebView JS VM do not share resources in any way. Therefore callbacks are no go but you can get a return value from such evaluation. Maybe doing it on a timer would provide some help to this issue.

**Comment by patrykmol** [comment]
Hi @raphaelpreston. We have fixed `canGoBack` and `canGoForward` properties and theirs appropriate events. Those were the only events that we could reliably fix when a page is using `history.pushState()` for navigation. With current state of WebView we have decided to only fix these as other events were simply unreliable or duplicated. We hope this helps your issue.

**Comment by patrykmol** [comment]
`WebView` has an undocumented `initScript` API. This allows to execute a JavaScript code before page is loaded. Maybe you can find helpful. We are going to make this API public with next release.

**Comment by patrykmol** [comment]
`initScript` is now documented. Closing.
