### ISSUE TITLE
Reload in Androids Dev app not working for TypeScript project

### ISSUE THREAD

**Issue by kc853** [eclipsesource/tabris-js#1789]
### Problem description

I'm serving a TypeScript app created by tabris init. Changes in the app.ts code are not recognized on reloads in the Android dev app. Same procedure for a JavaScript app works fine.

### Expected behavior
Code changes take effect on reload in Android dev app for TypeScript projects

### Environment

- Tabris.js version: tabris-cli 2.7.0 in Termux
- Device: Gemini PDA
- OS: Android 7.1.1

**Comment by cookieguru** [comment]
Are you running `tabris serve `[`-w`](https://github.com/eclipsesource/tabris-js-cli/tree/2.x#-w---watch)?

PS, 3.0.0 (in beta) has [automatic reloading](https://github.com/eclipsesource/tabris-js-cli/#-a---auto-reload)

**Comment by kc853** [comment]
The -w switch does help indeed! Why is this just for TypeScript apps?

**Comment by cookieguru** [comment]
It would work equally well if you're using vanilla JS, e.g. Babel or some other transpiler.

**Comment by kc853** [comment]
OK, thank you.
