### ISSUE TITLE
Make preventDefault() work on Popovers too

### ISSUE THREAD

**Issue by kc853** [eclipsesource/tabris-js#1790]
### Problem description

When using preventDefault() on the apps backnavigation event the app wont close, but a `Popover` on it does.
The back key is intercepted in Activity.onKeyDown but since the `Popover` is a special window not tied to the activity it might require special care.

### Expected behavior

backnavigation.preventDefault() should work on non activity windows as well.

**Comment by mpost** [comment]
Thanks for the issue we will resolve it soon.

**Comment by mpost** [comment]
This has been fixed in the 3.0.0-beta2 release. 

We also adrressed the topic for the `AlertDialog`, `TimeDialog`, `DateDialog` and `ActionSheet`.
