### ISSUE TITLE
TestView Text Broken

### ISSUE THREAD

**Issue by raphaelpreston** [eclipsesource/tabris-js#1792]
### Problem description
TextViews don't grow appropriately with text, making it impossible to effectively align text to the top of the TextView.

### Expected behavior
The TextView should expand its sized based on how much text it needs to display.

### Environment
- 3.0.0-beta1, iPhone 7, iOS 11.1.1

### Examples
```javascript
new TextView({
	left: 16, top: 16, right: 16,
	background: '#D3D3D3',
	text: 'Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text '
}).appendTo(ui.contentView);
```
#### Output: 
![no height attribute](https://user-images.githubusercontent.com/46331908/53111500-6572c700-34fa-11e9-8e19-652f747b5578.JPG)
```javascript
new TextView({
	left: 16, top: 16, right: 16,
	// --
	height: 100,
	// --
	background: '#D3D3D3',
	text: 'Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text '
}).appendTo(ui.contentView);
```
#### Output: 
![with height attribute](https://user-images.githubusercontent.com/46331908/53111164-d4035500-34f9-11e9-92bc-e89b29dd0848.JPG)

-----

You can see that specifying a height attribute does indeed prevent the text from clipping, but then it stops you from being able to align the text to the top of the TextView. There is a possible workaround, but that would require coming up with a function that was able to calculate the height that is needed to perfectly accommodate the text in the TextView, which, as far as I can tell, isn't trivial.

**Comment by mpost** [comment]
Thanks for opening the issue we will fix it for the next release.

**Comment by patrykmol** [comment]
Hello. This issue has been fixed in today's nightly.
