### ISSUE TITLE
ImageView Alignment Not Scaling Properly

### ISSUE THREAD

**Issue by raphaelpreston** [eclipsesource/tabris-js#1793]
### Problem description
ImageView offset alignment is increasingly inaccurate as parent composite size decreases.

### Snippet
```javascript
let dot = (layout) => {
	let i = new ImageView(layout);
	i.top = '59%';
	i.bottom = '37%';
	i.background = 'red';
	i.tintColor = 'blue';
	i.image = 'src/images/loading_dot_min2.png';
	return i;
};

let c = new Composite({
	top: MARGIN,
	bottom: MARGIN,
	left: MARGIN,
	right: MARGIN,
	background: '#000000'
})
.append(
	dot({ id: 'dotMiddle', centerX: 0}),
	dot({ id: 'dotLeft', /* left: '35%' OR right: '#dotMiddle 15'*/ }),
	dot({ id: 'dotRight', /* right: '35%' OR left: '#dotMiddle 15' */ })
).appendTo(this);
```
### Expected behavior
My goal is to align three dots (images) onto the screen and have all the properties shrink and grow relative to the size of the parent composite. So if the parent is big, I want the dots to be big, and if the parent is small, I want the dots to be small. I accomplish this by setting the top of the dots as a % offset from top of the parent, and the bottom with a % offset from the bottom of the parent. This part works as expected.

I also want the distance between the dots to remain relative to the parent composite size as well. The way I do this is put a middle dot at `centerX: 0` and then align the left dot offset from the center dot's left edge, and align the the right dot offset from the center dot's right edge. As far as I'm aware, this should accomplish what I'm attempting to do, but it's producing unexpected results.

When I set `#dotLeft.right: '#dotMiddle 15'`, and `#dotRight.left: '#dotMiddle 15'`, effectively aligning the left and right dots to the middle dots with an offset of 15% (of the parent), I get these results:

When `const MARGIN = 0`: 
![margin_0_off_center_dot](https://user-images.githubusercontent.com/46331908/53206129-62a4ce80-35ed-11e9-9b48-75c5e486c054.png)
This is what I would expect. However, when `const MARGIN = 44%`, the following occurs:
![margin_44_off_center_dot](https://user-images.githubusercontent.com/46331908/53206689-df847800-35ee-11e9-8555-4964ce7c705d.JPG)
<sub>Note: I've zoomed in a lot for the second photo so we can see it more clearly.<sub>

I can't figure out why the dots are so far apart.

-----
### Workaround

I've found that I can accomplish the original goal by aligning the left and right dots to their respective walls instead of the center dot.

When `#dotLeftleft: '35%'`, and `#dotRight.right: '35%'`, we get the original expected behavior:

When `const MARGIN = 0`: 
![webp net-resizeimage 3](https://user-images.githubusercontent.com/46331908/53206558-7ef53b00-35ee-11e9-99cd-5ef30e5b8125.png)

When `const MARGIN = '44%':
![margin_44_off_walls](https://user-images.githubusercontent.com/46331908/53206681-d98e9700-35ee-11e9-9785-0faca59ebf63.JPG)

As you can see, the second photo looks the same as the first, except just smaller.

### Environment
- Tabris: 3.0.0-beta1, iPhone 7, iOS 11.1.1
- Serving from tabris-cli@3.0.0-beta1

**Comment by mpost** [comment]
> However, when `const MARGIN = 44%`, the following occurs:

I can't tell you why exactly that is happening but could it be that the three dots do not fit into the available space of 12% anymore? That might cause the items to go all over the place (not expected though).

**Comment by karolszafranski** [comment]
There is a misunderstanding in how the layout works. You say:
> When I set `#dotLeft.right: '#dotMiddle 15'`, and `#dotRight.left: '#dotMiddle 15'`, effectively aligning the left and right dots to the middle dots with an offset of 15% (of the parent)…

This is where I see the issue. We do not support the percentage offset from the other widget. Please look at https://docs.tabris.com/latest/layout.html#top-right-bottom-left. There is a list of relation types that can be used. In short: 
- offset (in points)
- widget id
- percentage (to the parents' edge)
- percentage and offset (to the parents' edge)
- widget offset (in points)

`#dotMiddle 15` means `15pt` from `#dotMiddle` and not `15%` from `#dotMiddle`.

If you make a screenshot of your layout with container margin set to 44% please try to measure the distance between the tiny dots. It is 15pt, so on your iPhone 7, it should be 30 pixels.

**Comment by raphaelpreston** [comment]
Oh, I see now. My bad! I misread the docs. I suppose this would be an interesting feature that I think would be useful, though. What I'm going to have to do for my use case is edit the actual images to add more white space around the dots and then attach the outside dots to the center dots with no offset.

**Comment by mpost** [comment]
Closing this issue as resolved. Feel free to reopen if you have any more problems.
