### ISSUE TITLE
TextInput "select"/"selectionChanged" events are broken

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1794]
### Problem description

No events are fired when the user modifies the selection of a TextInput interactively.

### Expected behavior

As [documented](https://docs.tabris.com/latest/api/TextInput.html#select), "select" / "selectionChanged" events should fire when the selection of a TextInput is altered in the UI.

### Environment

- Tabris.js version: 2.7.0
- OS: iOS, Android

### Code snippet

See `textinput-selection.js` snippet.

**Comment by cpetrov** [comment]
It seems my setup was inconsistent, since I cannot reproduce this issue anymore.

**Comment by mpost** [comment]
I can not confirm that behavior on Android nor iOS. Moving the cursor fires a `select` event on both platforms as demonstrated in the snippet.
