### ISSUE TITLE
Android Build & Serve Fails

### ISSUE THREAD

**Issue by raphaelpreston** [eclipsesource/tabris-js#1795]
### Problem description
Building (local and remote) and serving both fail. You can see the project I'm attempting to run [here](https://github.com/raphaelpreston/TabrisExample).

### Building
The same error occurs when building with the CLI at 3.0.0-beta1 or at nightly (3.0.0-beta1-dev.20190225)
<details>
<summary>Output</summary>
<pre>
</ PS C:\Users\USER\Documents\APP_App\theAPPapp> tabris run android
[./] npm run --if-present build:android
[./] npm run --if-present build
[./] Copying Cordova files to build/cordova ...
[./] Copying JavaScript files to build\cordova\www\app ...
[build\cordova\www\app] npm install --production
added 3 packages from 11 contributors and audited 205 packages in 2.171s
found 0 vulnerabilities
[./] Replacing variables in config.xml...
[C:\Users\USER\AppData\Roaming\npm\node_modules\tabris-cli\src\services] npm bin
[build/cordova] C:\Users\USER\AppData\Roaming\npm\node_modules\tabris-cli\node_modules\.bin\cordova platform add C:\Users\USER\.tabris-cli\platforms\android\3.0.0-beta2-dev.20190225 --no-update-notifier
Adding android project...
Running command: cmd "/s /c "C:\Users\USER\.tabris-cli\platforms\android\3.0.0-beta2-dev.20190225\bin\create.bat C:\Users\USER\Documents\APP_App\theAPPapp\build\cordova\platforms\android com.theAPPcompany.APP APP --cli""
internal/modules/cjs/loader.js:583
    throw err;
    ^
Error: Cannot find module 'cordova-common'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\USER\.tabris-cli\platforms\android\3.0.0-beta2-dev.20190225\bin\create:22:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
Error: cmd: Command failed with exit code 1
The command C:\Users\USER\AppData\Roaming\npm\node_modules\tabris-cli\node_modules\.bin\cordova exited with 1
</pre>
</details>

### Serving
With CLI at 3.0.0-beta1, there is no error and it prints `[iOS][iPhone9,1][1]: connected`, but the developer app screen is completely blank and nothing prints to the console.

With CLI at nightly (3.0.0-beta1-dev.20190225), the following occurs when the developer app connects to the serve:
<details>
<summary>Output</summary>
<pre>
[iOS][iPhone9,1][1]: connected
Could not load main module: Error: Could not parse ./src/hello.js:TypeError: tabris._client.execute is not a function. (In 'tabris._client.execute(e,t)', 'tabris._client.execute' is undefined)
  at createLoader (./node_modules/tabris/boot.min.js:271:24)
  at a (./node_modules/tabris/boot.min.js:1:2287)
  at i (./node_modules/tabris/boot.min.js:1:1967)
  at i (./node_modules/tabris/boot.min.js:1:2044)
  at ./node_modules/tabris/boot.min.js:1:1277
  at value (./node_modules/tabris/boot.min.js:1:1357)
  at o (./node_modules/tabris/boot.min.js:1:3349)
  at subscribe (file:///var/containers/Bundle/Application/CF38650F-3094-42DA-8351-EEA0C2E6E024/Tabris.js.app/www/cordova.js:713:16)
  at addEventListener (file:///var/containers/Bundle/Application/CF38650F-3094-42DA-8351-EEA0C2E6E024/Tabris.js.app/www/cordova.js:133:43)
  at file:///var/containers/Bundle/Application/CF38650F-3094-42DA-8351-EEA0C2E6E024/Tabris.js.app/www/cordova.js:1428:34
  at _start (./node_modules/tabris/boot.min.js:1:3505)
</pre>
</details>

### Local Environment
- Windows 10
- Tabris Version: nightly (3.0.0-beta2-dev.20190225)

**Comment by mpost** [comment]
The nightly cli should pull in beta2. are you sure that you are running the nightly cli and use `nightly` in your package.json?

**Comment by raphaelpreston** [comment]
Yes, I’m sure. You can see the exact project that I was attempting to build on my profile, or in the link in my original post.

**Comment by mpost** [comment]
ok thanks. we can reproduce the issue in the nightly and will fix it asap

**Comment by mpost** [comment]
The issue has been solved in the tabris-cli where the cordova version needed to be updated to the latest and greatest: https://github.com/eclipsesource/tabris-js-cli/commit/dd94421e9bfa2d378e0b7be81ea127f3b45f61f7. Please update your cli accordingly.

**Comment by raphaelpreston** [comment]
Still receiving the same errors. Am I doing something wrong by running `npm i -g tabris-cli@nightly`? It's still pulling in `'3.0.0-beta1-dev.20190225'`.

**Comment by cookieguru** [comment]
`3.0.0-beta1-dev.20190226` hasn't published yet; it will be in about 3 hours.  You can check the Versions tab [here](https://www.npmjs.com/package/tabris-cli) for the releases, or see the link to the diff above and manually patch it on your system.

**Comment by raphaelpreston** [comment]
The build works now, but I'm still receiving the same error upon serving from the original post:

```
Could not load main module: Error: Could not parse ./src/app.js:TypeError: tabris._client.execute is not a function
Error: Could not parse ./src/app.js:TypeError: tabris._client.execute is not a function
    at ModulePreLoader.createLoader (<anonymous>:271:15)
    at Function.target.(anonymous function) (<anonymous>:254:28)
    at t.a (<anonymous>:1:2275)
    at t.i (<anonymous>:1:1963)
    at t.i (<anonymous>:1:2040)
    at t.<anonymous> (<anonymous>:1:1273)
    at t.value (<anonymous>:1:1353)
    at Channel.o (<anonymous>:1:3342)
    at Channel.fire (./cordova.js:820:23)
    at Object.fireDocumentEvent (./cordova.js:230:45)
```

**Comment by mpost** [comment]
Hi i just checked out the *TabrisExample*  project ran `npm install` and `tabris serve` in it and found it to run fine. I am also on the nightly cli and am using the nightly tabris app.

**Comment by raphaelpreston** [comment]
Wow... the plot thickens! I just confirmed that when I follow the exact same steps, I still receive that error. What's left for me to do now? Also confirmed that package.json specifies `nightly` and `tabris --version` yields `3.0.0-beta2-dev.20190227`.

**Comment by cookieguru** [comment]
@raphaelpreston What version do you have in `package.lock`?

**Comment by raphaelpreston** [comment]
`"tabris": {
      "version": "3.0.0-beta2-dev.20190228",
      "resolved": "https://registry.npmjs.org/tabris/-/tabris-3.0.0-beta2-dev.20190228.tgz",
      "integrity": "sha512-..."`

**Comment by mpost** [comment]
You tried deleting your `node_modules` folder manually?

**Comment by tbuschto** [comment]
> ```
> Could not load main module: Error: Could not parse ./src/app.js:TypeError: tabris._client.execute is not a function
> ```

This seems to indicate that the native platform is older than the CLI needs. This would be expected if you combine the beta1 developer app with the nightly build CLI. If you build your nightly-based app with debug flag and use the developer side console to enter the IP the CLI prints it should work. 

If this turns out to be correct I could just add another check to ensure this kind of missmatach produces a better error.

**Comment by mpost** [comment]
Since we are gearing up for the 3.0-beta2 release we also have a public android beta version in the Google Play store. You could join the beta test and install that to test your served app again.

**Comment by raphaelpreston** [comment]
Tried deleting `node_modules` and then running `npm i` and `tabris serve`, still same error. Throughout this process I've been serving from my Windows 10, but I just confirmed that I also receive the same error when serving the same project from macOS Sierra 10.12.6. I've served from both computers to an iPhone 7 with iOS 11.1.1 and an HTC Desire 530 with Android 6.0.1.

**Comment by raphaelpreston** [comment]
@tbuschto you nailed it! I built my `nightly` app on macOS, deployed to my iPhone (11.1.1), served from Windows (#1803), and entered the URL into the newly built app in the drawer on the right. Everything worked perfectly.  Just to be sure, I navigated back to the developer app and tried connecting from there and it gave me the error, as expected.
