### ISSUE TITLE
Provide an event fired when scrolling ends

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1798]
### Problem description

Currently, `CollectionView` and `ScrollView` provide the `"scroll"` event, which is fired continuously during scrolling. 

A common UX pattern is fading/sliding-in an UI element during scroll and snapping it into place after the scroll has finished (e.g. hide or show dependent on whether more or less of 50% of it is visible - for example the search field in the Samsung Email app). It is currently not possible to implement the snapping part without e.g. using a timeout after a `"scroll"` event has been fired. Snapping right after scrolling has finished instead would result into improved perception of UI responsiveness.

### Expected behavior

Introduce an event, fired when the scroll has finished. 

Scrolling finishes when the list stops scrolling after the user lifts his finger. The event should not fire if the user is still touching the list, even if it may be stationary at this point, since this means that the user hasn't finished his interaction yet.

### Environment

- Tabris.js version: 3.x

**Comment by raphaelpreston** [comment]
This would be awesome! It would also fix the annoyance of how a user can the screen in an attempt to stop the scrolling, but their tap is still processed by the cell in the CollectionView.

**Comment by mpost** [comment]
Sounds like a viable addition. :+1:

**Comment by cookieguru** [comment]
As of 2724bf75fecac5cf512e4801ab319ee77607e406 this is possible now on a `ScrollView` with `scrollXState`/`scrollYState`

**Comment by mpost** [comment]
@cookieguru Well recalled. :) Closing this one as implemented for the `ScrollView`. A similar implementation could be added for the `CollectionView` in the future.
