### ISSUE TITLE
tern plugin for tabris.js to give tooling support in Eclipse and major editors

### ISSUE THREAD

**Issue by paulvi** [eclipsesource/tabris-js#180]
@angelozerr

The situation for tabris.js is different: it is in limited developer preview, so it is impossibly to say if it is popular with general users.

Having tabris.js support in Eclipse would help tabris.js adoption, so EclipseSource developers should take a look how to create new tern plugin for tabris.

What are current instructions?

(Also raised as GitHub issue https://github.com/eclipsesource/tabris-js/issues/180)

Date: Mon, 17 Nov 2014 09:26:18 +0100
Subject: Re: tabris.js invitation from Paul Verest

Hi Paul,
I think the best place to speak about tern plugin for tabris is to create an issue at https://github.com/eclipsesource/tabris-js/issues
We will able to see if it's really interesting, and if it's very interesting, tabris developer could telll us what they wish to have.
The very cool thing, is that they provide a JSON api https://github.com/eclipsesource/tabris-js/tree/master/doc/definitions that we will able to use to generate tern plugin.
Regard's Angelo
2014-11-17 8:03 GMT+01:00 

    Dear friend,
    Paul Verest has invited you to join the tabris.js developer preview. tabris.js is the Next-GEN cross-platform framework to build mobile apps using JavaScript. Jump in and give it a try!

    Paul Verest also left you a message:
    Please take a look at Tabris.js cross mobile development, what TernIDE could help https://github.com/eclipsesource/tabris-js

    The link below is valid until you have created an account with it. It's not limited to your person. So, feel free to delegate it.

    https://tabrisjs.com/signin?invite=54699dd47efdb0e4aedbb4d5

    Sincerly,

    your EclipseSource Team

**Comment by ralfstx** [comment]
@cpetrov worked with @angelozerr to update the configuration in [tern-tabris](/angelozerr/tern-tabris). Great work guys, thank you!

**Comment by angelozerr** [comment]
Many thantks to @cpetrov for her great improvment.

@ralfstx glad tern-tabris please you!

I would like to improve tern-tabris to support object literal cases  : 

```javascript
tabris.create( "Button", {
  // ctrll-space provides the default properties like layoutData, text, visibility, ...

tabris.create( "Button", {
  layoutData: { // ctrll-space provides the default properties like left, right, top, centerX ...
```

The magic feature of tern is that it works with any JS Editor like Browser, Eclipse, Vim, Emcas, Sublime. Hope one day Netbeans and WebStorm will integrate tern.java to support tern.

It should be very cool if you EclipseSource guys you tell to Orion guys that tern is very cool. If Orion integrates tern tern-tabris could work inside Orion.

AN Orion gut works on this topic. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=432940#c17 (please post your comment). We could after integrates ESLint inside Eclipse (it's my goal).
