### ISSUE TITLE
No Elevation on Android

### ISSUE THREAD

**Issue by raphaelpreston** [eclipsesource/tabris-js#1802]
### Problem description
The `elevation` property isn't casting a shadow. Here is a photo (sorry) of the result of the snippet below.
<img src="https://user-images.githubusercontent.com/46331908/53528460-e3a90d80-3aa6-11e9-8831-5b7937785f51.JPG" height="400">

### Expected behavior
Here is a screenshot of the same code, run on iOS 11.1.1.
<img src="https://user-images.githubusercontent.com/46331908/53528331-9462dd00-3aa6-11e9-9dc4-733b1f331dd5.JPG" height="400">

### Environment
- Tabris.js version: 3.0.0-beta1
- Device: HTC Desire 530
- OS: Android 6.0.1

### Code snippet
```javascript
let c1 = new Composite({
	id: 'c1',
	top: 0, right: 0, left: 0,
	height: 50,
	elevation: 50,
})
.append(new TextView({centerX: 0,centerY: 0,text: 'Hello World!'})).appendTo(ui.contentView);
```

**Comment by mpost** [comment]
To see the `elevation` you have to set a `background` on the Composite.

**Comment by raphaelpreston** [comment]
Fixed! Looks like that's only needed on Android.
