### ISSUE TITLE
Timer example has misaligned layout

### ISSUE THREAD

**Issue by cookieguru** [eclipsesource/tabris-js#1806]
### Problem description

When opening the [timer example](https://github.com/eclipsesource/tabris-js/tree/master/examples/timer) inside the Developer App, the layout is misaligned:

![Screenshot of timer example with misaligned layout](https://user-images.githubusercontent.com/1888809/53690682-23305d80-3d24-11e9-87f4-cb06a6f4773e.png)

When tapping inside the `TextInput`, the layout immediately fixes iteself:

![Screenshot of timer example with proper layout](https://user-images.githubusercontent.com/1888809/53690686-32afa680-3d24-11e9-9a55-c5f748861cda.png)

### Environment

- Tabris.js version: 3.0.0-beta2
- Device: Various
- OS: Android 8 and 9

**Comment by mpost** [comment]
Thanks for the heads up. We will correct the issue for the final release.

**Comment by elshadsm** [comment]
@cookieguru Cannot reproduce this in Tabris.js 3 beta 2.

**Comment by cookieguru** [comment]
@elshadsm Still reproducible for me, what device did you test with?

**Comment by elshadsm** [comment]
@cookieguru I have tested with Nexus 6P.

**Comment by cookieguru** [comment]
@elshadsm @mpost I can confirm the issue on a Galaxy S8 running Android 8.0.0 via the [Samsung Remote Test Lab](https://developer.samsung.com/remotetestlab/rtlDeviceList.action).

![Screenshot](https://user-images.githubusercontent.com/1888809/54776372-38830400-4bcd-11e9-87b9-3d19ce60870c.png)

**Comment by mpost** [comment]
Thanks for the info. We are still looking into the issue.

**Comment by mpost** [comment]
@cookieguru In the timer example the layout uses several percent values, can you also see the error, when you remove any usage of percent?

**Comment by cookieguru** [comment]
[timer.js@9ca63fe](https://github.com/eclipsesource/tabris-js/blob/9ca63fe49c672b05dc4283e9a444520e449c7084/examples/timer/timer.js) (using percent values) with 3.0.0-rc1-dev.20190429+0313 looks normal, closing.

![Screenshot](https://user-images.githubusercontent.com/1888809/57189769-8165f200-6ec7-11e9-8355-f42da0dbdc23.png)

**Comment by mpost** [comment]
Great to hear and thanks for testing.
