### ISSUE TITLE
Keyboard not shown when TextInput gains focus while changing parent background

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1807]
### Problem description

The keyboard is not shown when a `TextInput` gains focus while the parent `background` changes.

### Expected behavior

The keyboard should be visible and the parent `background` should change color.

### Environment

- Tabris.js version: 3.0.0-beta2
- Device: iPhone 6
- OS: iOS 12

### Code snippet

```js
import {contentView, TextInput} from 'tabris';

new TextInput({
  top: 20, left: '20%', right: '20%',
  message: 'Type here, then confirm'
}).onFocus(e => contentView.background = 'red')
  .appendTo(contentView);
```

**Comment by patrykmol** [comment]
Fixed.
