### ISSUE TITLE
File Read Failure on Android

### ISSUE THREAD

**Issue by raphaelpreston** [eclipsesource/tabris-js#1811]
### Problem description
Text file reading failure on Android.
### Snippet
```javascript
let {fs} = require('tabris');

let addr = fs.cacheDir + "/test";
let buffer = "hello123";
let encoding = 'utf-8';

fs.writeFile(addr, buffer, encoding)
	.then(() => {
		console.log("Saved file as " + addr);
		fs.readFile(addr, encoding).then(contents => {
			console.log("Contents: " + contents);
		});
	})
	.catch(err => {
		console.error(err);
	});
```
#### Output on iOS
```
Saved file as /var/mobile/Containers/Data/Application/<identifier>/Library/Caches/test
Contents: hello123
```
#### Output on Android
```
Saved file as /data/user/0/com.eclipsesource.tabris.js/cache/test
```
I discovered this problem when trying to address an issue in my custom-made file manager where the following error kept being thrown on Android (not on iOS):
```
Error: Invalid V8 thread access: current thread is Thread[pool-64-thread-1,5,main] while the locker has thread Thread[main,5,main]: /data/user/0/com.eclipsesource.tabris.js/cache/<filename>
```
I was unable to replicate that exact error message when testing the code, but I'm fairly certain the two are related, so I'm including that error message as it might help narrow down the issue.

### Environment
- Tabris.js version: 3.0.0-beta2
- Devices: 
  - iPhone 7 with iOS 11.1.1
  - HTC Desire 530 with Android 6.0.1

**Comment by mpost** [comment]
Thanks for reporting. We can confirm the issue and have fixed it in the latest 3.x nightly.

**Comment by raphaelpreston** [comment]
Can confirm that it works! Just not on the dev app. Thanks @mpost!
