### ISSUE TITLE
CollectionView does not show data but refreshes

### ISSUE THREAD

**Issue by josiahking** [eclipsesource/tabris-js#1813]
### Problem description

I tried to use collectionView widget to display some data. But I started off by using the example which didn't work as expected.
First of all i noticed that appending the CollectionView to the the Composite which i appeded to scrollview and then tab doesn't work.
So i appended it directly to the tab which works but the data is not displaying

### Expected behavior

I want to see a list of collections.

### Environment

- Tabris.js version: 2.7
- Device: Developer App 2.6.2
- OS: Android 6

### Code snippet

```javascript



const {Button, ui, ScrollView, CollectionView, RefreshComposite} = require('tabris');
let people = [
  ['Holger', 'Staudacher', 'holger.jpg'],
  ['Ian', 'Bull', 'ian.jpg'],
  ['Jochen', 'Krause', 'jochen.jpg'],
  ['Jordi', 'Böhme López', 'jordi.jpg'],
  ['Markus', 'Knauer', 'markus.jpg'],
  ['Moritz', 'Post', 'moritz.jpg'],
  ['Ralf', 'Sternberg', 'ralf.jpg'],
  ['Tim', 'Buschtöns', 'tim.jpg']
].map(([firstName, lastName, image]) => ({firstName, lastName, image: image}));
  let recordsView = new CollectionView({
    left: 0, top: 0, right: 0, bottom: 0,
    cellHeight: 'auto',
    refreshEnabled: true,
	refreshMessage: "Refreshing",
    createCell: () => {
		let cell = new Composite();
		new TextView({
		  left: 10, top: 'prev() 16', right: 10,
		  alignment: 'center'
		}).appendTo(cell);
		return cell;
	},
    updateCell: (cell, index) => {
		let person = people[index];
		console.log(index);
		cell.apply({
		  TextView: {text:person.firstName}
		});
	}
  }).appendTo(ui.contentView);
```

**Comment by cookieguru** [comment]
Your `CollectionView` has no `itemCount` property and thus has a length of 0, so no cells are rendered.

**Comment by josiahking** [comment]
Thank you. that solves it.

**Comment by josiahking** [comment]
Thank you. that solves it.
