### ISSUE TITLE
Allow to set the active Tab in JSX declaration

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1814]
### Problem description

When using JSX it is not possible to declare the active `Tab` in a `TabFolder`. Currently one has to select the active tab after the JSX declaration in regular js/ts code. This also has the unwanted side effect that the first tab always runs thru its `appear` callback although it will not be shown to the user.

### Expected behavior

Allow to declare the selected tab in the tab folder declaration. The snippet below sketches such a feature.

### Environment

- Tabris.js version: 3.x

### Code snippet

```xml
<TabFolder>
  <Tab />
  <Tab selected={true}/>
</TabFolder>
```

Variation:

```xml
<TabFolder selection='#two'>
  <Tab id='one'/>
  <Tab id='two'/>
</TabFolder>
```

**Comment by tbuschto** [comment]
I looked into it. There are issues with both variations, assuming we want to keep the JSX API identical to the Widget API (which i do).

Tab property `selected`:
 * Allows contradicting declarations
 * Redundant to TabFolder `selection` property
 * Unclear behavior when Tab is parentless. It would logically be forced to be false, in which case we still can't set the selection in JSX.
 
TabFolder property `selection` with selectors.
 * Asymmetrical API -> set selector, but get tab?
 * What if no Tab matches the selector?
 * What if a tab is added/removed and thereby the match changes?

Best i could come up with is a separate (additional) TabFolder property `selectionIndex`. It can still only be used to select already added tabs, but we can ensure that JSX adds the tabs before it sets the value.

**Comment by mpost** [comment]
The proposal for `selectionIndex` sounds good. It would also be a good addition in general where the index of the selected tab would be more important than the tab itself.

**Comment by mpost** [comment]
Implemented.
