### ISSUE TITLE
CollectionView: provide cell in selection event

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#182]
When manipulating the data item in a selection listener, it should be possible to update the cell. One simple option would be to provide a reference to the cell in the selection event so application code can trigger an itemchange event.

**Comment by jkrause** [comment]
https://github.com/eclipsesource/tabris-js/issues/271

**Comment by ralfstx** [comment]
As of commit 79b03ff9, CollectionView offers a `refresh` method that should be used to update the cell.
