### ISSUE TITLE
CollectionView fires "scroll" event on creation

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1821]
### Problem description

Creating and populating a `CollectionView` fires a `scroll` event although it should not fire when the `statusBar` is using the `displayMode` _float_.  The event is fired because the `CollectionView` scrolls its content out of the safe-area. Also see related https://github.com/eclipsesource/tabris-js/issues/1820.

### Expected behavior

The `scroll` event should only fire when the `CollectionView` actually scrolls. This is related to the general safe-area handling.

### Environment

- Tabris.js version: 3.0.0-beta2
- Device: iPhone 6
- OS: iOS 12

### Code snippet

```javascript
import {CollectionView, contentView, statusBar, TextView} from 'tabris';

statusBar.displayMode = 'float';

contentView.append(
  <CollectionView
    layoutData='fill'
    itemCount={300}
    createCell={() => <TextView text='Hallo World'/>}
    onScroll={(e) => console.log(e)}/>
);

```

**Comment by patrykmol** [comment]
Fixed in nightly.
