### ISSUE TITLE
updateCell is not declared

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-js#1825]
### Problem Description
At the moment, I get the error [TS2345](https://github.com/Microsoft/TypeScript/blob/b145eaf160e6b2729aaacb89856bc2346f85ac4c/src/compiler/diagnosticMessages.json#L1207), when create a CollectionView. I cannot use the `updateCell` property because it is not declared in types.
A copy of the types I got when I installed Tabris version 3.0 beta-2: [tabris.d.ts](https://hastebin.com/isupayetib.md)

![image](https://user-images.githubusercontent.com/26363214/54223961-0bba5700-4512-11e9-9ccb-15471d432792.png)

### How to Solve It

 ```js
public constructor(properties?: Properties<CollectionView> & Partial<Pick<CollectionView, 'cellHeight' | 'cellType' | 'createCell'>>);
```
just turn it in --->
 ```js
public constructor(properties?: Properties<CollectionView> & Partial<Pick<CollectionView, 'cellHeight' | 'cellType' | 'createCell' | 'updateCell'>>);
```

**Comment by cpetrov** [comment]
This has been fixed in the latest 3.x nightly.
