### ISSUE TITLE
Add property scrollbarVisible on CollectionView

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-js#1826]
[`CollectionView`](http://docs.tabris.com/latest/api/CollectionView.html) is `a scrollable list that displays data items in cells, one per row` (from the type declaration).
The problem is that not all cases require scrollbar visibility, but at the moment [`CollectionView`](http://docs.tabris.com/latest/api/CollectionView.html) does not have `scrollbarVisible` property, as in [`ScrollView`](http://docs.tabris.com/latest/api/ScrollView.html)

~~Sometimes, it is also necessary to scroll to the certain cell, but it is also impossible, as it is already implemented in [`ScrollView`](http://docs.tabris.com/latest/api/ScrollView.html) ([`scrollToY`](http://docs.tabris.com/latest/api/ScrollView.html#scrolltoyoffset-options))
Please make [`CollectionView`](http://docs.tabris.com/latest/api/CollectionView.html) more convenient to customize and work with cells.~~ (`reveal()`)

*P.S. Also you have not described the value of `scrollbarVisible` in the documentation for [`ScrollView`](http://docs.tabris.com/latest/api/ScrollView.html)*

**Comment by mpost** [comment]
The `scrollbarVisible` property is documented in the latest 3.0-beta2 release: https://docs.tabris.com/3.0-beta2/api/ScrollView.html#scrollbarvisible.

Having a similar property on `CollectionView` makes sense as well. 👍

**Comment by patrykmol** [comment]
iOS support is implemented.

**Comment by mpost** [comment]
`scrollbarVisible` has been added on the `CollectionView` as well.
