### ISSUE TITLE
Button with icon and stroke color has no padding

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#1828]
### Problem description

A button that has both an icon and a stroke color set looses all padding on Android.

### Expected behavior

Stroke color should not affect button layout.

### Environment

- Tabris.js version: 3.0 master
- Device: Samsung Galaxy S7
- OS: Android 8.0.0

### Code snippet

Can be reproduced with button-style.js snippet

**Comment by mpost** [comment]
Thanks for reporting. We will look into it.
