### ISSUE TITLE
Cannot change height of cell with "auto" height after initial layout pass

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1829]
### Problem description

Even though the intrinsic size of a cell with "auto" height should change after it has been initially laid out, it doesn't on iOS.

### Expected behavior

Cells with `"auto"` height should update their height dynamically according to the height of their contents.

### Environment

- Tabris.js version: 3.0.0-beta2
- OS: 12.1

### Code snippet

|Android (expected)|iOS|
|---|---|
|![Screenshot_20190313-162542_Tabrisjs](https://user-images.githubusercontent.com/2341769/54291920-98feb980-45ad-11e9-803a-7b1b197f1cab.jpg)|![Simulator Screen Shot - iPhone SE - 2019-03-13 at 16 26 12](https://user-images.githubusercontent.com/2341769/54291932-9e5c0400-45ad-11e9-8945-b0861805a3bd.png)|

```javascript
import {Composite, CollectionView, contentView} from 'tabris';

new CollectionView({
  left: 0, top: 0, right: 0, bottom: 0,
  itemCount: 1,
  createCell: () => {
    const composite = new Composite({background: 'black'});
    setTimeout(() => {
      composite.append(new Composite({width: 50, height: 50, background: 'red'}));
    }, 2000);
    return composite;
  }
}).appendTo(contentView);

```

**Comment by mpost** [comment]
I can confirm this issue. Also happens when eg, an image is loaded that would increase the height of a cell when it is loaded and placed into the layout.

**Comment by karolszafranski** [comment]
This is not going to be fixed. `UICollectionView` along with its layout does not support dynamic resizing at all. In general, it is not allowed to modify the contents of the cells outside of the `createCell` or `updateCell` event (including the timeouts).

If you need to resize the cell after it was initially loaded you probably should keep a model of each cell in your app, track the changes in objects which represent the cells and use [refresh](https://docs.tabris.com/latest/api/CollectionView.html#refreshindex) method on the `CollectionView`. when your model changes. This will trigger the `updateCell` event, where you will have the opportunity to make changes in the UI.
