### ISSUE TITLE
Tab: visibility property does not work

### ISSUE THREAD

**Issue by ifurnadjiev** [eclipsesource/tabris-js#183]
Visibility property should be supported for Tab. Currently, there is no warning that's not supported, but it's not working either. Have it working will allow us to show/hide tabs dynamically without disposing/creating them again.

**Comment by ralfstx** [comment]
Turns out that visibility is not yet properly supported by the clients.

When `visibility` is set to `false`, iOS hides the content but not the tab itself, Android doesn't respect this property at all.

**Comment by mpost** [comment]
There is no implementation for <code>visibility</code> on TabItem on the Tabris (remote) Android client yet. Requires some work since the TabFolder is composed of two separate Android Views.

**Comment by ralfstx** [comment]
According to @patrykmol it's doable but even more work on iOS.

**Comment by patrykmol** [comment]
iOS part is done.

**Comment by mpost** [comment]
Closing as implemented
