### ISSUE TITLE
Not possible to remove background of TextInput

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1831]
### Problem description

With tabris 3 it is not possible to remove the TextInput underline anymore by setting the `background` to _null_. It behaves the same as setting _initial_. This prohibits to create custom background containers to adjust an app to a custom design

### Expected behavior

It should be possible to remove a `TextInput` background to create a custom text input appearance.

### Environment

- Tabris.js version:  3.x

**Comment by ishigo1987** [comment]
yes it's true and it  happen only with the beta2 not the one

**Comment by mpost** [comment]
The current implementation is correct.

In order to hide the the underline the `background` color should be set to _transparent_.
