### ISSUE TITLE
Barcode Scanning Not Working v3 developer app

### ISSUE THREAD

**Issue by josiahking** [eclipsesource/tabris-js#1835]
### Problem description

Scanning barcode failed with error undefined.

### Expected behavior

Scan and download playground code.

### Environment

- Tabris.js version: 3.0
- Device: Samsung Galaxy Grand Prime Plus
- OS: Android 6

**Comment by cookieguru** [comment]
Duplicate of #1805

**Comment by mpost** [comment]
Yes that is very likely a duplicate. I am closing this issue for now. Please add a comment with your device name on the issue #1805.
