### ISSUE TITLE
Text widget caret position is always zero

### ISSUE THREAD

**Issue by AndrejLES** [eclipsesource/tabris-js#1840]
### Problem description

For the text widgets caret position a 0 is returned in any case on iOS.

### Expected behavior

The actual position of the caret is returned.

### Environment

- Tabris.js version: 2.7.0
- Device: iPadAir
- OS: iOS 11.2.2

**Comment by mpost** [comment]
According to this snippet it works as expected. https://github.com/eclipsesource/tabris-js/blob/master/snippets/textinput-selection.js Could you provide a snippet to demonstrate the behavior?

**Comment by ifurnadjiev** [comment]
Patryk fixed it today.

**Comment by mpost** [comment]
Closing as resolved. Thanks for reporting.
