### ISSUE TITLE
cornerRadius on TextInput clips the view instead of adjusting the corner radius

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1844]
### Problem description

Setting `cornerRadius` on a `TextInput` clips the view similar to a `Composites`. 

### Expected behavior

Since the default appearance suggest that the corners are rounded, i would expect the `cornerRadius` property to affect the corners

### Environment

- Tabris.js version: 3.x
- Device: iPad Pro 
- OS: iOS 12.2

### Code snippet

```jsx
import { contentView, TextInput } from 'tabris';

contentView.append(<TextInput stretchX text='Corner radius' cornerRadius={32}/>);
```

**Comment by patrykmol** [comment]
Fixed in https://github.com/eclipsesource/tabris-ios/commit/27135186c1388dfbea588061ca3a234f568b0e95.
