### ISSUE TITLE
Tabfolder weird behavior

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1845]
Tabris 3.0.0-beta2
Development with tabris Js app container
```
const tabfolder = new TabFolder({left:0,top:['prev()',0], right:0, bottom:0,elevation:1,tabBarLocation:'bottom',textColor:'#616161'}).appendTo(contentView);
new Tab({title:'Test',image:{src:'src/icons/home.png',scale:2}}).appendTo(tabfolder);
```

Expected result: bottom tab with gray image and gray text and when the tab is selected orange image and orange text
Result: bottom tab with blue image and blue text when tab is selected
and the TextColor Tabfolder return an error: there is no setter for property textcolor

**Comment by mpost** [comment]
What platform are you seeing the issues on?

It is good habit to use the provided issue template as it asks for input of this kind.

**Comment by mpost** [comment]
What you want to use is: https://docs.tabris.com/3.0-beta2/api/TabFolder.html#selectedtabtintcolor

**Comment by mpost** [comment]
Closing this as resolved. Please reopen if you have any more issues.
