### ISSUE TITLE
Tabris does not recognize other start script except app.js

### ISSUE THREAD

**Issue by josiahking** [eclipsesource/tabris-js#1847]
### Problem description

I noticed that the nightly build v3.rc cli does not change from the default src/app.js specified in the package.json

### Expected behavior

I tried to point the main entry script to another file but app still loads from src/app.js

### Environment

- Tabris.js version: @nightly
- Device: Samsung Galaxy
- OS: Android 6

### Code snippet

```javascript
// A minimal, *self-contained* code snippet to reproduce the problem:
```

**Comment by cookieguru** [comment]
What is listed for the `main` entry in your `package.json` file?

**Comment by josiahking** [comment]
````"main": "src/app.js",````
Tried changing it but it didnt work.

**Comment by cookieguru** [comment]
You may need to re-run `tabris serve` after changing it.  See also the [serve options](https://github.com/eclipsesource/tabris-js-cli/#tabris-serve-options) to enable logging or to override the `main` field.

**Comment by cpetrov** [comment]
@josiahking did @cookieguru's suggestion work for you?

**Comment by josiahking** [comment]
Thanks @cookieguru Your solution work just as expected.
