### ISSUE TITLE
TextView property: alignment: center not working

### ISSUE THREAD

**Issue by josiahking** [eclipsesource/tabris-js#1848]
### Problem description

TextView: Ignored unsupported value for peoperty "alignment": Accepting "left","right","centerX", given was: "center".

### Expected behavior

Center was working will before an update that i did.

### Environment

- Tabris.js version: @nightly
- Device: Samsung Galaxy
- OS: Android

### Code snippet

```javascript
// A minimal, *self-contained* code snippet to reproduce the problem:
```

**Comment by cookieguru** [comment]
https://github.com/eclipsesource/tabris-js/blob/master/doc/migration-guide.md#alignment-properties

**Comment by fax1ty** [comment]
![image](https://user-images.githubusercontent.com/26363214/55689104-d9294000-5991-11e9-8391-4c54160f0de5.png)
But what should I do with types?
![image](https://user-images.githubusercontent.com/26363214/55689110-e9411f80-5991-11e9-8a22-86169fc51826.png)
(3.0 rc1)

**Comment by mpost** [comment]
Quick turnover :) Closing as resolved.

**Comment by josiahking** [comment]
Should i update for the fix to work?

**Comment by cookieguru** [comment]
As you said, "center" worked before the update.  If you want to continue using "center", downgrade to the version you were previously using.  Othewise, please refer to the linked migration guide for the value that will be supported going forward.
