### ISSUE TITLE
TextView with markupEnabled and no left and right constraint layouts incorrectly

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1849]
### Problem description

A `TextView` with `markupEnabled` and no layout data given (or only the left side given) grows larger than the parent and does not show any text.

### Expected behavior

The `TextView` should constrain its size to the intrinsic size of the text.

### Environment

- Tabris.js version: 3.x
- Device: iPhone 6
- OS: iOS 12

### Code snippet

```javascript
import {contentView, TextView} from 'tabris';

new TextView({
  text: `Hello<br/> World`,
  markupEnabled: true,
  background: '#aaaaaa'
}).appendTo(contentView);
```

**Comment by karolszafranski** [comment]
Not the case anymore after https://github.com/eclipsesource/tabris-ios/commit/54e8429d05c9d9e34d857a2c5da503803b3478cf

![Screenshot 2019-05-15 at 12 07 44](https://user-images.githubusercontent.com/1746396/57767646-2e334100-770a-11e9-860d-af7acd8b37cb.png)
