### ISSUE TITLE
Browser widget does not work with self signed certificates

### ISSUE THREAD

**Issue by hstaudacher** [eclipsesource/tabris-js#185]
When using the browser widget with an HTTPS url that uses a self signed certificate just a blank screen is shown.

This happens on iOS and Android

**Comment by ralfstx** [comment]
@hstaudacher Is this fixed now with the [UseStrictSSL](https://github.com/eclipsesource/tabris-js/blob/master/doc/build.md#preferences) flag?

**Comment by jordiboehmelopez** [comment]
This is not "fixable" in iOS(!) as the Browser is a sandbox which cannot be influenced ...
Is a connection is not valid (e.g. self signed certificate) it will refuse to connect.
@patrykmol What do you think?

**Comment by jordiboehmelopez** [comment]
@ralfstx `UseStrictSSL` only affects connections we initiate...

**Comment by patrykmol** [comment]
This is unfixable on iOS.
