### ISSUE TITLE
Add animated GIF or APNG support + bug

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-js#1854]
At the moment, `ImageView` [does not support animation](https://github.com/eclipsesource/tabris-js/issues/482#issuecomment-111405503), and takes only the first frame when setting the image.
It would be great if Tabris has received the support of component such as [`AnimatedImageDrawable`](https://developer.android.com/reference/android/graphics/drawable/AnimatedImageDrawable)
### Also
At the moment, I convert GIF to MP4, create a new `Video` object and endlessly loop it.
```js
new Video({ height: 200, width: 200, centerX: 0, centerY: 0, url: 'endpoint/gif.mp4', controlsVisible: false })
    .appendTo(contentView)
    .onStateChanged(({ target, value }) => {
        if (value == 'finish') {
            target.play();
        }
    });
```
The problem is that when the application goes to the background and then returns to the foreground, the following error occurs

![1](https://user-images.githubusercontent.com/26363214/56041349-8f51a880-5d49-11e9-957e-e6fcd0b03d55.gif)
![2](https://user-images.githubusercontent.com/26363214/56041396-ad1f0d80-5d49-11e9-89aa-ba68f36d21a2.gif)

Test from Nox Emulator (Android 7.1.2) [first] and Xiaomi Redmi 5 Plus (Android 8.1.0) [second]
Error log available [here](https://pastebin.com/Y3hnHBG0)

**Comment by fax1ty** [comment]
If necessary, I can split it into two issues

**Comment by mpost** [comment]
Thanks for reporting the issue we will investigate the crash. animated gif supported has been requested before so it would be great to have this issue focusing on the crash.

**Comment by mpost** [comment]
We have fixed the crash in 3.x.
