### ISSUE TITLE
Button Widget Image property gives color to image

### ISSUE THREAD

**Issue by josiahking** [eclipsesource/tabris-js#1855]
### Problem description

I added an image to the button widget, but noticed it didn't come out with it default color, because the image is a png file from flaticon, which has its own color. E.g. red icon image.
The button image color is now like the default link color for android, that is goldish yellow.

### Expected behavior

Image should be default without any color added to it.

### Environment

- Tabris.js version: 3.0.rc
- Device: Samsung
- OS: Android 6

### Code snippet

```javascript
// A minimal, *self-contained* code snippet to reproduce the problem:
```

**Comment by cookieguru** [comment]
Can you fill out the issue template and provide a snippet and a sample image?  It's not very clear what the problem is.

**Comment by josiahking** [comment]
![001-mobile-phone](https://user-images.githubusercontent.com/16147779/56096806-b55f8000-5ee4-11e9-8b84-656987dcf61e.png)
![017-house-outline](https://user-images.githubusercontent.com/16147779/56096807-b7294380-5ee4-11e9-95ce-73fe99a279ff.png)
The above are the original files i added to the src of the image but here is the output
![Screenshot_20190414-183048](https://user-images.githubusercontent.com/16147779/56096835-e6d84b80-5ee4-11e9-9a69-16fca115f788.png)

Here is the code that performs these functions:
```
new Button({
                left: 0, right: 0, top: 'prev()',
                padding: {
                    top: 12,
                    right: 10,
                    left: 10,
                    bottom: 8
                },
                style: 'text',
                class: 'menu',
                //background: (menu.id == pageId ? AppConfig.color.colorPrimary : '#ffffff'),
                image: {
                    src: (menu.id == pageId ? menuItemsFocus[index].icon : menu.icon),
                    width: 20,
                    height: 20,
                },
                text: menu.text,
                font: '18px',
                //textColor: (menu.id == pageId ? '#ffffff' : AppConfig.color.colorPrimary)
            })
```

**Comment by josiahking** [comment]
I also noticed that adding background color doesn't work for button widget with property style as text

**Comment by cookieguru** [comment]
Are you using an [app theme](https://github.com/eclipsesource/tabris-js/blob/master/doc/theming-android.md)?

**Comment by josiahking** [comment]
No, am using default developer app as you can see in the screenshot

**Comment by cookieguru** [comment]
[Per](https://tabrisjs.slack.com/archives/C0AQ5BK36/p1555343539089700) @cpetrov:
> Just checked, those colors are defined in a custom theme of our developer app.

@josiahking Can you reproduce this in your own built app?

**Comment by josiahking** [comment]
@cookieguru The built app is the same with developer app. It comes with theme color.
This should be optional.

**Comment by cookieguru** [comment]
Unless overridden, all apps are build on the `Theme.Tabris.Light.DarkAppBar` theme, which is a thin extension of the default Android styles.

Let me ask again: Can you reproduce this same widget image color behavior in your own built apps?

**Comment by josiahking** [comment]
The image didnt come with its default color.
It came with the custom theme color. When i change the color of the button text the image color becomes white.

**Comment by cookieguru** [comment]
That's not what I asked

**Comment by josiahking** [comment]
What do you mean?

**Comment by mpost** [comment]
You are correct, that the Android button icon is currently changing its color to be in synch with the apps theme and button style. We could change it to always use its own color similar to ios.

**Comment by mpost** [comment]
The button behavior has been updated to not colorize the icon.

![image](https://user-images.githubusercontent.com/73655/56893753-18741980-6a84-11e9-8e8d-d0f5968027ff.png)

It will be set to a disabled color when the button itself has `enabled` set to _false_.

![image](https://user-images.githubusercontent.com/73655/56893762-2033be00-6a84-11e9-8a6a-05b4490f8c82.png)
