### ISSUE TITLE
Document Android theme location change in migration guide

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1856]
### Problem description
Expected location of themes has changed in Tabris.js 3. This change has not been documented yet.

### Expected behavior
To be documented in the migration guide:

Declared theme resources need to be changed to prefix the target with `app/src/main/`, e.g.:
```
<resource-file src="res/android/values/my_theme.xml" target="res/values/my_theme.xml" />
```

should be changed to:

```
<resource-file src="res/android/values/my_theme.xml" target="app/src/main/res/values/my_theme.xml" />
```

**Comment by mpost** [comment]
I would not call this a migration change since we have never documented the "old" path before. We had the only blog post which has been updated a few times but only on 3.x have created a proper documentation page. https://github.com/eclipsesource/tabris-js/blob/master/doc/theming-android.md

**Comment by cpetrov** [comment]
IMO this would still have value for users that used this feature.

**Comment by cpetrov** [comment]
I take this back since this change has been introduced by Cordova.
