### ISSUE TITLE
Button Widget needs more improvement and better customization options

### ISSUE THREAD

**Issue by josiahking** [eclipsesource/tabris-js#1858]
### Problem description

Lately, i was trying to work with the button widget due to its onselect event.
I noticed that the button comes with margin top and bottom that is impossible to remove.
I noticed that when image is added to a button the padding is disabled, image takes color of the theme of which changing the color is impossible even when the button text color is changed, and position image from text of button is impossible, positioning the button widget with image is impossible.
I also noticed that adding background to button with style 'text' is not working.

if you add image to a button and set the text color, the image color becomes white. That is if you set the text color other than the theme default color.

### Expected behavior

Like to see more improvement on the button widget.
### Environment

- Tabris.js version: 3.0
- Device: Samsung Galaxy & ZTE
- OS: Android 6 & 7

### Code snippet

```javascript
// A minimal, *self-contained* code snippet to reproduce the problem:
```

**Comment by cookieguru** [comment]
You could just use a `Composite` which will allow you to adjust the padding, images, and coloring to your heart's content.

**Comment by josiahking** [comment]
Composite does not have onselect event listener, thats why i am using button widget. I first tried composite.

**Comment by josiahking** [comment]
Nevertheless a button widget still need improvement.

**Comment by cookieguru** [comment]
`Composite` has a [`tap`](http://docs.tabris.com/3.0-beta2/api/Widget.html#tap) event

**Comment by josiahking** [comment]
I know it does, but not sufficient for my usage, thats why i switched to using button.

**Comment by cookieguru** [comment]
What does the `select` event provide you that the `tap` event doesn't?

**Comment by josiahking** [comment]
The tap event doesn't allow me to get the target and find its children.

**Comment by josiahking** [comment]
It will be much easier to implement using button.
If i use composit, i will need to add text and image widget, and they are all using tap.
The select event allow me to manipulate the target and its children more than tap.
I want to be able to get the children, change their color, get their values, change their image.

**Comment by cookieguru** [comment]
@josiahking Like this?

```js
new Composite().onTap(({target}) => {
    target.children(); // ...
}
```

**Comment by josiahking** [comment]
Yes thats what i mean, but i noticed that the children of the composite is what will be tapped and that makes this more complicated using the composite approach.
Lets say, a composite has a child textView which when you tap, the textview on tap event is fired rather than the composit, so if the composite has more than one child, each will have its own tap event fired rather than the parent tap event.
So the approach is a failing for what am trying to achieve, which is a menu.

By the way, i was wondering why with image added to a button, the padding stops working, but without image, padding works.

**Comment by cookieguru** [comment]
This Composite has everything you requested:
- Minimal padding
- An image
- Text
- A tap handler

```js
new Composite({
	background: 'blue',
	highlightOnTouch: true,
}).append(
	new ImageView({
		top: 3, left: 3, height: 48, width: 48,
		image: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Cot-icon-48x48.png',
	})
).append(
	new TextView({
		bottom: 3, left: ['prev()', 3],
		text: 'Ready',
	})
).onTap(({target}) => {
	target.background = 'red';
	target.children('ImageView').first().image = 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Allow.png/48px-Allow.png';
	target.children('TextView').first().text = 'Tapped';
}).appendTo(contentView);
```

You don't need separate tap handlers for each child widget.  In fact, that would work against you: If you listen for a tap on the `TextView` but the user taps on the `ImageView` or the blank space, the event wouldn't fire.

Renders like this:

![](https://user-images.githubusercontent.com/1888809/56435979-2f01c000-628f-11e9-897f-beadb02b7948.png)

Tapping _anywhere_ on it will change it to this:
![tapped](https://user-images.githubusercontent.com/1888809/56435991-35903780-628f-11e9-83b5-b5f777bc3869.png)

**Comment by mpost** [comment]
One of the main assumptions tabris makes, is that a Composite with children on it, eg a textview and an imageview that as a tap event attached will receive all the events so that creating "custom button" with that approach is expected. If the children have tap listeners themselves, they will intercept the tap event and not forward to the parent composite.

**Comment by mpost** [comment]
The native button has a certain behavior that is intrinsic to its implementation. Eg the default padding. We could provide api to change the padding between the image and the text. If you need fine grained control a Composite with ImageView and TextView (and tap event) is the best approach.

  >  I also noticed that adding background to button with style 'text' is not working.

The button of thy `text` or `outline` can bee seen has having a transparent background. You could use the `flat` style to colorize the background area.

See my comment here regarding the icon colorization https://github.com/eclipsesource/tabris-js/issues/1855#issuecomment-485732027
