### ISSUE TITLE
XMLHttpRequest doe snot support self signed certificates

### ISSUE THREAD

**Issue by hstaudacher** [eclipsesource/tabris-js#186]
Sending requests using the XMLHttpRequest with a HTTPS url and a self signed certificate results in an error.

This is true for Android. I believe that the same issue will exist for iOS but it's not verified.

**Comment by ralfstx** [comment]
@jordiboehmelopez Would the [UseStrictSSL](https://github.com/eclipsesource/tabris-js/blob/master/doc/build.md#preferences) flag help with this issue?

**Comment by hstaudacher** [comment]
No idea, you need to test it. Maybe we can use the old eclipsesource build server for this.

**Comment by ralfstx** [comment]
You have to add the following setting to your `config.xml` to work with self-signed certificates:

```xml
<preference name="UseStrictSSL" value="false"/>
```
