### ISSUE TITLE
Provide API to set default/minimum CollectionView cellHeight

### ISSUE THREAD

**Issue by cookieguru** [eclipsesource/tabris-js#1860]
### Problem description

Setting a `CollectionView`'s `cellHeight` property to `auto` allows for cell height to be computed on-the-fly, and to allow different cells to have different height.  Often times it is known in advance that all cells will be at least a certain height.  Currently the [default estimated cell height](https://github.com/eclipsesource/tabris-js/issues/1486#issuecomment-329748866) is unchangable, and the height is fixed at this height until all visible cells are laid out.  This means that for a short period the cell's contents will overflow before the height is calculated.

![video screenshot demonstration](https://user-images.githubusercontent.com/1888809/56448891-2679ab80-62c8-11e9-96e7-d857bc90c0dd.gif)

### Expected behavior

An API is provided that will set a minimum and/or default height for cells.

### Environment

- Tabris.js version: 2.7.0
- Device: iPhone 6
- OS: iOS 12.1.4

### Code snippet

```js
const {CollectionView, Composite, TextView, ui} = require('tabris');

const collectionView = new CollectionView({
  left: 0, top: 0, right: 0, bottom: 0,
  cellHeight: 'auto',
  refreshIndicator: true,
  refreshMessage: 'loading...',
  refreshEnabled: true,
  createCell: () => {
    let cell = new Composite({
      padding: {bottom: 12}
    });

    let a = new tabris.TextView({
      top: 8, left: 16, right: 16,
      id: 'a',
      font: 'bold 18px',
    }).appendTo(cell);
    let b = new tabris.TextView({
      top: [a, 8], left: 16, right: 16,
      id: 'b',
      font: '15px',
    }).appendTo(cell);
    new tabris.TextView({
      top: [b, 8], left: 16, right: 16,
      id: 'c',
      font: '14px',
    }).appendTo(cell);

    return cell;
  },
  updateCell: (cell, index) => {
    ['a', 'b', 'c'].forEach((i) => {
      cell.children('#' + i)[0].text = 'Foo bar';
    });
  },
}).appendTo(ui.contentView);

setTimeout(() => {
  const itemCount = 10;
  collectionView.insert(0, itemCount - collectionView.itemCount);
  collectionView.load(itemCount);
  collectionView.refreshIndicator = false;
  collectionView.reveal(0);
}, 500);
```

**Comment by karolszafranski** [comment]
ATM there is no way to alter the estimated height. It's probable that the Collection View widget will be reworked in the (not that distant) future. Depending on the decisions we make this API might become public.

**Comment by cookieguru** [comment]
@karolszafranski In the meantime is there a viable workaround?
