### ISSUE TITLE
snippets webview-webmessaging.js is not working

### ISSUE THREAD

**Issue by Nexter-day** [eclipsesource/tabris-js#1861]
snippets webview-webmessaging.js is not working！
I tried to test it with snippets, but I couldn't get it to work
I use the same code as the official，Hope to get help

**Comment by cookieguru** [comment]
Can you post the versions and device as requested from the issue template?

**Comment by Nexter-day** [comment]
### Problem description

snippets webview-webmessaging.js is not working！I don't know why
There were no errors in the console, and the button was clicked without any changes

### Expected behavior

Such as demo

### Environment

- Tabris.js version: 2.7.0
- Device: iphone 6s
- OS: ios 10.14

**Comment by cookieguru** [comment]
Works for me.

* Tabris.js version: 2.7.0
* Device: iPhone 6
* OS: iOS 12.1.4

```bash
npm install -g tabris-cli@2.7.0
git clone https://github.com/eclipsesource/tabris-js
cd tabris-js
git checkout 2.x
cd snippets
npm install
tabris serve webview-webmessaging.js
```

![67CF0E77-E9AB-4D78-A077-52AE2E9B9EA6](https://user-images.githubusercontent.com/1888809/56474921-b0935280-6435-11e9-86d0-4188ece9150c.png)

**Comment by Nexter-day** [comment]
It's works ！thanks! :)

**Comment by mpost** [comment]
Closing as resolved.
