### ISSUE TITLE
Tabris patch questions 

### ISSUE THREAD

**Issue by Nexter-day** [eclipsesource/tabris-js#1862]
### Problem description

Hello everyone
I have a very basic question about the APP patch .
After reading the documentation, I still can't finish it successfully. I hope can have a simple template  to learn.

### Expected behavior

Able to successfully patch

### Environment

- Tabris.js version: 2.7.0
- Device: Iphone6
- OS: IOS 12.1.4

**Comment by cookieguru** [comment]
The issue tracker is for bug reports whereas the [https://tabrisjs.herokuapp.com/](Tabris.js Slack channel) is a great place for questions like these.

You stated you have tried to patch already; what code do you have so far, and what is/isn't working?

**Comment by Nexter-day** [comment]
This is the code I am currently testing.

### OLD code
app.js

const {Page, Button, app, ui} = require('tabris');
new Button({text: 'Button'}).on('select', () => patch()).appendTo(ui.contentView);
function patch() {
    var patchUrl = 'patch.zip';
    app.installPatch(patchUrl, (error, patch) => {
        if (error) {
            // show error dialog
            console.log(error);
        } else {
            console.log('success');
            // confirm reload
            // app.reload();
        }
    });
}


### PATCH File:
src
└── app.js
patch.json    (This file is not sure how to write,Currently blank）


### PATCH src/app.js code:

const {Page, Button, app, ui} = require('tabris');
new Button({text: 'Button'}).on('select', () => patch()).appendTo(ui.contentView);

**new Button({ top: 'prev() 10 ',text: 'Button2'}).on('select', () => patch()).appendTo(ui.contentView);**

function patch() {
    var patchUrl = 'patch.zip';
    app.installPatch(patchUrl, (error, patch) => {
        if (error) {
            // show error dialog
            console.log(error);
        } else {
            console.log('success');
            // confirm reload
            // app.reload();
        }
    });
}

**Comment by cookieguru** [comment]
From [http://docs.tabris.com/2.7/patch.html](the docs):
> A patch is made available as a zip archive that contains the app files to be modified or added, and an ***optional*** descriptor file named patch.json

(emphasis added).  Also:

> The format and content of the patch.json descriptor file is not enforced by Tabris.js


From what you pasted (use ` ```js ` and ` ``` ` around the code to indicate code blocks) it looks like the `app.js` file for before and after is identical, so when the patch is successfully applied there'd be no way to discern any difference.

**Comment by Nexter-day** [comment]
patch app.js code

Different from the original file, PATCH has a button added
But after the trial, there was no success. I don’t know which side is doing something wrong.

**Comment by cookieguru** [comment]
What's the error?

**Comment by Nexter-day** [comment]
No error  display...but app.js still no working to change（Is the structure of zip cordova/www/src changed like this? Although I have tried it but it didn't work.）

**Comment by cookieguru** [comment]
I don't know if it's still the case but #553 mentions that patches are applied based on the URL (I'm not sure if that's still the case).  So if you're able to watch the request logs on wherever you're hosting the zip file, that should tell you if the zip is even being downloaded.


As to the directory structure, the zip file should match exactly.  So if it's project root 🡒 src 🡒 app.js then your zip file should contain a root folder src with a new app.js

**Comment by mpost** [comment]
The experimental app patch feature has been removed in Tabris 3 so it is not advised to build functionality on top of it.

**Comment by mpost** [comment]
@Nexter-day I will close this issue for now as there does not seem to be an underlying technical problem. It is removed in 3.x so you should not probably not rely on it. If you feel otherwise please reopen the issue.
