### ISSUE TITLE
CheckBox does not grow in height with its contained text

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1863]
### Problem description

A `CheckBox` with longer text does not grow in height to accommodate its text. This applied to certain character/word combinations. The snippet below uses _One two three four_ which shows the problem when the available space is to small. The text _One one one one_ does not show the problem. It seams like it is only a problem when using percentage values as in the snippet below.

### Expected behavior

Always grow the `CheckBox` bounds to fit its text.

### Environment

- Tabris.js version: 3.x
- Device: iPhone 6
- OS: iOS 21

### Code snippet

```jsx
import { CheckBox, contentView, Stack } from 'tabris';

contentView.append(
  <Stack left='60%' right={0} alignment='stretchX'>
    <CheckBox text='One two three four'/>
    <CheckBox text='Five'/>
  </Stack>
);

```

**Comment by patrykmol** [comment]
Fixed in nightly.
