### ISSUE TITLE
tabris 3 beta2 ios release build  failed 

### ISSUE THREAD

**Issue by Nexter-day** [eclipsesource/tabris-js#1864]
### Problem description

hello 

I got this error when I tried to build ios release

>warning: ignoring file /Users/david/apptest6/build/cordova/platforms/ios/Tabris/Tabris.framework/Tabris, missing required architecture i386 in file /Users/david/apptest6/build/cordova/platforms/ios/Tabris/Tabris.framework/Tabris (3 slices)
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_BasicObject", referenced from:
      _OBJC_CLASS_$_CordovaPluginBridge in CordovaPluginBridge.o
  "_OBJC_METACLASS_$_BasicObject", referenced from:
      _OBJC_METACLASS_$_CordovaPluginBridge in CordovaPluginBridge.o
  "_OBJC_METACLASS_$_TabrisClientAppDelegate", referenced from:
      _OBJC_METACLASS_$_AppDelegate in AppDelegate.o
  "_OBJC_CLASS_$_TabrisClientAppDelegate", referenced from:
      _OBJC_CLASS_$_AppDelegate in AppDelegate.o
ld: symbol(s) not found for architecture i386

### Expected behavior

The packaging is expected to complete

### Environment

- Tabris.js version: 3.0.0 bate2
- Device: iphone6
- OS: ios 12

**Comment by cookieguru** [comment]
Can you post the full build log and link it here?

**Comment by cookieguru** [comment]
At first glance it looks like the platform didn't download.  Did you [grab your API key](https://tabrisjs.com/settings/account) and enter it in to the CLI?

If so, can you post the full build log and link it here?

**Comment by Nexter-day** [comment]
I have the developer API key, and I used the tabris CLI method to build it, but failed..
That should be not binding API way , but i don't know how to do binding with cordova  

Now I create it by opening the file directly through xcode, and it has been successfully established so far..：(

**Comment by jonek** [comment]
@Nexter-day can you post the line from your `package.json` that contains the "tabris" dependency?

**Comment by Nexter-day** [comment]
tabris init 
tabris build ios --release
package.json 

> {
>   "main": "src/app.js",
>   "private": true,
>   "scripts": {
>     "test": "eslint .",
>     "start": "tabris serve -a"
>   },
>   "dependencies": {
>     "tabris": "^3.0.0-beta2"
>   },
>   "devDependencies": {
>     "eslint": "^5.16.0"
>   }

Does this information help?

**Comment by jonek** [comment]
@Nexter-day please remove the `^` at the start of your tabris version and try again.

**Comment by mpost** [comment]
Closing this for now. Please reopen if you see any more problems.
