### ISSUE TITLE
Background color of status bar changes when a popover opens 

### ISSUE THREAD

**Issue by Emehado** [eclipsesource/tabris-js#1870]
### Problem description
i have changed the color of my  statusBar and anytime i add a new page to my stack, my color remains, but after opening a popover, the background of the status bar changes to the default color of the toolbar. The background color goes back to my set color when Popover closes 

### Expected behavior
Color of StatusBar should not change upon appearance of a popover 

### Environment
- Tabris.js version: Tabris.js 2.7
- Device: Samsung galaxy s6
- OS: Android 6.0.1
### Code snippet

```javascript
// A minimal, *self-contained* code snippet to reproduce the problem:
```

**Comment by cookieguru** [comment]
Can you add a snippet that demonstrates the problem?

**Comment by Emehado** [comment]
`const {Popover,Button, ui} = require('tabris');

ui.statusBar.background="#e5519d"
new Button({
centerX:0, centerY:0,
text:"Open Popover"
}).on('select',()=>{
  new Popover({

  }).open()
}).appendTo(ui.contentView)`

**Comment by mpost** [comment]
I can confirm the issue. Here is your snippet migrated to tabris 3.x:

```js
import {Button, contentView, Popover, statusBar} from 'tabris';

statusBar.background = '#e5519d';

new Button({
  centerX: 0, centerY: 0,
  text: 'Open Popover'
}).on('select', () => {
  new Popover({}).open();
}).appendTo(contentView);
```

**Comment by Emehado** [comment]
OK

**Comment by mpost** [comment]
As of now, setting the values from the status or nav bar to a new value will not update the Popover appearance when the popover is already open.

As a workaround you could set the status or nav bar properties before opening the popover and reset them later.
