### ISSUE TITLE
Possible weird behaviour with layout

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1872]
Hello It could be a mistake from me but I think there's a problem with some layout of the 3.0.0RC1 of tabrisjs.
in the snippet below 
when I add a composite in the scrollview the first one fits well but the second one that should be after the first one rather overlaps it.
expected behaviour: the second composite should be placed after the first one during a dynamic insertion
```JAVASCRIPT
const {contentView,Composite,ScrollView,Button} = require('tabris');
const t = new ScrollView({top:0,left:0,right:0,height:100,direction:'horizontal'}).appendTo(contentView);
new Button({centerX:0,centerY:0,text:'add composite'})
.onSelect(()=>{
  new Composite({left:['prev()',15],top:15,width:65,height:65,cornerRadius:32.5,background:'#e0e0e0'}).appendTo(t);
}).appendTo(contentView);
```

**Comment by mpost** [comment]
@ishigo1987 It would be very helpful if you could use the provided issue templates when opening bugs. Therefore you would have filled in the platform on which this issues occurs which is an important detail.

**Comment by ishigo1987** [comment]
You're right i will not forget next time

Problem:
Hello It could be a mistake from me but I think there's a problem with some layout of the 3.0.0RC1 of tabrisjs.
in the snippet below
when I add a composite in the scrollview the first one fits well but the second one that should be after the first one rather overlaps it
Expected Behaviour:
the second composite should be placed after the first one during a dynamic insertion

Snippet 
``` JAVASCRIPT
const {contentView,Composite,ScrollView,Button} = require('tabris');
const t = new ScrollView({top:0,left:0,right:0,height:100,direction:'horizontal'}).appendTo(contentView);
new Button({centerX:0,centerY:0,text:'add composite'})
.onSelect(()=>{
  new Composite({left:['prev()',15],top:15,width:65,height:65,cornerRadius:32.5,background:'#e0e0e0'}).appendTo(t);
}).appendTo(contentView);
```
Environnement:
TabrisJs 3.0.0rc1
Huawei P10 Lite
Android 8.0

**Comment by mpost** [comment]
I can confirm the issue. We will look into.

**Comment by mpost** [comment]
Bug is resolved in upcoming nightly.

**Comment by ishigo1987** [comment]
Thank you
