### ISSUE TITLE
WebSocket Support

### ISSUE THREAD

**Issue by scho** [eclipsesource/tabris-js#188]
Hi tabris-team!

I've started to develop a small game with tabris.js. Pulling the game state every x seconds though could become an issue in the future. So I would like to use WebSockets instead.

Is there a plan to support WebSockets?

Cheers
Georg

**Comment by tbuschto** [comment]
'ws' depends on the 'http' module and a whole lot of other problematic ones (liky crypto). We need to support either WebSockets or nodes 'http' natively.

**Comment by chrwick** [comment]
Could this Cordova plugin be another option (at least for Android)?
Cordova 3: https://github.com/knowledgecode/WebSocket-for-Android
Cordova 2.3.0 - 2.9.x: https://github.com/knowledgecode/WebSocket-for-Android/tree/2.x
https://www.npmjs.com/package/cordova-plugin-websocket

**Comment by chrwick** [comment]
Just for the records:
These Cordova plugins cannot work out of the box at the moment without modification:
https://github.com/knowledgecode/WebSocket-for-Android
https://github.com/mkuklis/phonegap-websocket

Tabris.js lacks support of some important Web-APIs, see here #376.
They also do some version checks on navigator.userAgent to see if they should support Websockets from the plugin or use the implementation provided by the system.

**Comment by sand123** [comment]
I have successfully used engine.io-client with PhoneGap and engine.io as a server. May it be an option?

**Comment by mpost** [comment]
WebSocket support is something we are continuing to look into and have made some progress already. The following gif shows integration with Firebase via WebSockets. Expect it to land in in Tabris.js in the not to distant future.

![tabris js-firebase](https://cloud.githubusercontent.com/assets/73655/13772242/5e808d42-ea93-11e5-9cd8-e42e3f17b271.gif)

**Comment by bFlood** [comment]
is there a timeline for when this will be available? thanks!

**Comment by sergio-doman** [comment]
I'm waiting for this feature also. According to roadmap, this ticket was added to the "NEAR-TERM (~6 MONTH)" list.

**Comment by gosia-eclipsesource** [comment]
@bFlood @sergio-doman We should have an update about this in a week, please stay tuned.

**Comment by gosia-eclipsesource** [comment]
@bFlood @sergio-doman @sand123 @shanteadam
Thanks all for the wait. We're now pretty far along with WebSockets for both platforms, and it will be included in the release that comes after 1.9. (We haven't decided what that release will be called yet.)

**Comment by bFlood** [comment]
any word on this? thanks!

**Comment by mpost** [comment]
We are making good progress on the WebSocket integration.

We will support a brought range of features including sending text and binary data as typed arrays. The only omission (for now) will be support to receive data as blob.

Stay tuned for the next release. :)

**Comment by mpost** [comment]
WebSocket support has landed in the nightly build of the upcoming Tabris.js 1.10 release. It is currently also available in the Android client and will be in the iOS client as well for the 1.10 release.

Please give it a try and provide feedback. :)
