### ISSUE TITLE
Allow to share content to another app

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1891]
### Problem description

At the moment we have `tabris.app.launch()` which opens another app but does not allow to attach specific data and to pick the app to share to. We should allow to share image, text, audio and video.

Possibly mimicking the web share API: https://developers.google.com/web/updates/2019/05/web-share-files
 
Related https://github.com/eclipsesource/tabris-js/issues/1668

**Comment by fax1ty** [comment]
Possibly duplicate of https://github.com/eclipsesource/tabris-js/issues/1668

**Comment by mpost** [comment]
@fax1ty Thanks for linking the issues. It is not a duplicate but a subset. The share part is the easier scenario compared to receiving a result from another app. We will keep it in mind though.

**Comment by mpost** [comment]
Share support has been added via https://github.com/eclipsesource/tabris-js/commit/c2528ec5ce79293f25f9317330011fa2808998cb
