### ISSUE TITLE
Add ability to customize elevation color

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-js#1893]
Is it possible to change the color of the shadow that is created by specifying the `elevation` parameter?
Now, the shadow doesn't interact with the color of the object in any way.

![red](https://user-images.githubusercontent.com/26363214/59159807-2cc62000-8ae0-11e9-9374-666c94570b5c.png)
![green](https://user-images.githubusercontent.com/26363214/59159812-3c456900-8ae0-11e9-89e1-9a8862e8d167.png)
![blue](https://user-images.githubusercontent.com/26363214/59159803-220b8b00-8ae0-11e9-82cc-6842f6b8c643.png)

Is it possible to do something like `elevationColor`?

**Comment by mpost** [comment]
Android does not allow to change the elevation shadow color. It is possible on iOS thougth.

**Comment by fax1ty** [comment]
Is it possible to bypass this restriction to use SVG together with Tabris? I'm about [this lib](https://github.com/879479119/react-native-shadow). Or do I have to use `Canvas` for this?

**Comment by mpost** [comment]
Canvas would be best. Otherwise you could use a `WebView` with an svg file in it.
