### ISSUE TITLE
app.registerFont() failed on Android

### ISSUE THREAD

**Issue by jokorivai** [eclipsesource/tabris-js#1895]
I have an app with FontAwesome (TTF) registered as custom font using `app.registerFont()`. The app works as exected on iOS, showing FontAwesome glyph icon on both TextView and Button. On Android, `app.registerFont()` simply fails and ruins the app's UI.

On iOS:
<img width="322" alt="Screen Shot 2019-06-13 at 16 52 28" src="https://user-images.githubusercontent.com/11798147/59418473-aa996c80-8dfb-11e9-8749-2f4615ec6ceb.png">

On Android:
<img width="343" alt="Screen Shot 2019-06-13 at 16 51 28" src="https://user-images.githubusercontent.com/11798147/59418488-b127e400-8dfb-11e9-9799-79f9489dbf6e.png">

* You may notice the behavior of the ImageView also, as seen on sidebar's profile image.

### Problem description

`app.registerFont()` works on iOS, fails on Android (v6.0)

Log shows: `Could not call method "registerFont" on tabris.App (Reason: resourceLoader.load(file) must not be null)`

The app has been tested using `tabris build|run android` and `tabris serve -w`.

Please advice. 
Thank you.

<img width="340" alt="Screen Shot 2019-06-13 at 16 35 06" src="https://user-images.githubusercontent.com/11798147/59417138-483f6c80-8df9-11e9-8e39-c4ad1b76d383.png">

### Expected behavior

`app.registerFont()` should register custom font on Android to be used within app. This behavior happened as expected on iOS (device: iPhone 6s, simulator: iPhone X, ios 12.1)

### Environment

- Tabris.js version: 2.6.1
- Device: Android Emulator, Android 6.0, Intel Atom with HAXM enabled.
- OS: Android 6.0

### Code snippet

```javascript
app.registerFont('FontAwesome',  './res/font/fontawesome-webfont.ttf');
```

File `'./res/font/fontawesome-webfont.ttf'` existence was double-checked:

<img width="718" alt="Screen Shot 2019-06-13 at 16 44 50" src="https://user-images.githubusercontent.com/11798147/59418105-0283a380-8dfb-11e9-9084-3949129fddae.png">

**Comment by mpost** [comment]
Thanks for the detailed explanation. We will look into the issue.

**Comment by mpost** [comment]
In general it works as expected on Android. The following screenshot shows the 3.x tabris app with a custom bundled font in the header. This is a build app running on Android 6 emulator.

![InkedScreenshot_1560418213_LI](https://user-images.githubusercontent.com/73655/59421415-d6eac400-8dce-11e9-917b-6641958ce8db.jpg)

**Comment by mpost** [comment]
Are you able to provide the output from android adb logcat?

**Comment by jokorivai** [comment]
I am on travel currently. Will back soon once I have chance. Thank you.

**Comment by jokorivai** [comment]
Hi @mpost, I can confirm that the `app.registerFont()` failed on emulator, but worked as expected on real android device (Xiaomi Redmi 5 was the deviced tested on). 

![Photo on 18-06-19 at 20 21](https://user-images.githubusercontent.com/11798147/59681601-e458e180-9206-11e9-881f-a9d138bf41bb.jpg)
Sorry for bad photo quality.

**Comment by mpost** [comment]
That is good new in general. does it work with a app loaded via tabris serve and with a build app?

**Comment by jokorivai** [comment]
> That is good new in general. does it work with a app loaded via tabris serve and with a build app?

Yes it does. 
The problem seems to be some library lack on android emulator.

I am closing this issue for now.
Thank you @mpost
