### ISSUE TITLE
Allow to request app runtime permissions

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1896]
### Problem description

Several native features require to request runtime permissions from the user. At the moment it is possible to cover those cases with third part plugins like the [cordova-diagnostic-plugin](https://github.com/dpa99c/cordova-diagnostic-plugin) but this is often times uncomfortable and/or error prone. Tabris.js should provide the ability to request permissions directly.

Use case is visible in #1880.

### Proposed solution

To request a permission the developer has to request the permission in code but he also has to provide some compile time meta-data on both iOS (explanation string) and Android (permission key). To provide this entries the developer has to provide specific entries in the config.xml. For example a camera permission support would require the following config.xml entries:

```xml
<!-- iOS -->
<edit-config file="*-Info.plist" target="NSCameraUsageDescription" mode="overwrite">
  <string>Use the camera to take pictures.</string>
</edit-config>

<!-- Android -->
<config-file target="AndroidManifest.xml" parent="/manifest">
   <uses-permission android:name="android.permission.CAMERA" />
</config-file>
```

During runtime the following api scetches an approach on how to get authorization for a specific permission:

```js
let camera = new Camera();

// Supported permission parameter (string or string[]):
// either an android permissions by name eg "android.permission.READ_CALENDAR"
// or supported permission use-cases like "location" or "camera" (on android it maps to a set of concrete permissions)

// Return values from an authorization method
// "undefined" - Should ask user for permission
// "granted" - User granted access to this permission
// "denied" - User has declined for ever. ask to change permission in settings. (Never ask Again checkbox on Android)

// IOS
// "restricted" - Permission is unavailable and user cannot enable it. For example, when parental controls are in
// effect for the current user.

// Android
// "declined" -  User denied access to this permission (without checking "Never Ask Again" box). App can request
// permission again and user will be prompted again to allow/deny again.

if (tabris.permission.authorizationStatus('camera') === 'granted') {
  camera.start();
} else {
  let result = await tabris.permission.requestAuthorization('camera');
  if (result === 'granted') {
    camer.start();
  } else {
    // handle error cases (show dialog, prompt user etc.)
  }
}

if (tabris.permission.isAuthorized('camera')) { // shortcut for == 'granted'
  camera.stop();
}

class Camera {

  /**
   * Requires camera permission
   *
   * ios:
   *   <edit-config file="*-Info.plist" target="NSCameraUsageDescription" mode="overwrite">
   *      <string>Use the camera to take pictures.</string>
   *    </edit-config>
   *
   * android:
   *    <config-file target="AndroidManifest.xml" parent="/manifest">
   *       <uses-permission android:name="android.permission.CAMERA" />
   *    </config-file>
   */
  start() {
    if (!tabris.permission.authorizationStatus('camera') === 'granted') {
      throw new Error('no camera permission');
    }
    //...
  }
}

```

**Comment by cookieguru** [comment]
Just an idea:

Could the build scripts scan the app's generated codebase and run build hooks automatically to add the permission?

The correlation between calling a JS method and adding a line to an XML file is not obvious...

**Comment by mpost** [comment]
Yeah the hard requirement to augment the build environment is not very pleasant. Scanning the code base is pretty tricky and error prone but even if it would work, on iOS you need to provide a user facing message that is use case specific.

Our goal is to throw a meaningful error message when any API is called that does require the permission but it is not available or incorrectly configured.
