### ISSUE TITLE
Search action list button icons are semantically incorrect

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1898]
### Problem description

On iOS, an "i" icon is shown inside each search action proposal list item. When tapped, it replaces the text in the search field without accepting it. This is very unintuitive. One would expect the "i" icon to mean "information" and that additional information about the item would be shown when tapping on the icon. 

![IMG_7ED1E34B7CB6-1](https://user-images.githubusercontent.com/2341769/59605024-10446c00-910e-11e9-924b-4e8b2e03b9ec.jpeg)

### Expected behavior

Instead of the "i" icon, an icon of an arrow pointing from the bottom right corner to the upper left corner could be shown to provide the same functionality.

This is an established pattern used in browser search UIs on both iOS and Android:

|Safari on iOS|Chrome on Android|
|---|---|
|![IMG_0482](https://user-images.githubusercontent.com/2341769/59605453-1f77e980-910f-11e9-969b-efc665e49306.JPG)|![tempFileForShare_20190617-144438](https://user-images.githubusercontent.com/2341769/59605184-85b03c80-910e-11e9-9652-16880a9f68ab.jpg)|

This pattern is also already used for the Tabris.js search action on Android:
![tempFileForShare_20190617-144747](https://user-images.githubusercontent.com/2341769/59605405-053e0b80-910f-11e9-933b-085b3079ea4a.jpg)

### Environment

- Tabris.js version: 3.0.0

### Code snippet

See `snippets/navigationview-searchaction.jsx`.

**Comment by patrykmol** [comment]
Fixed in nightly.
