### ISSUE TITLE
TextInput property "revealPassword" not working as expected when set on creation

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1906]
### Problem description

`revealPassword` does not have an effect when set to `true` on widget creation.

### Environment

- Tabris.js version: 2.7.0, 3.0.1
- OS: Android; works as expected on iOS

### Code snippet

```javascript
const {TextInput, ui} = require('tabris');

new TextInput({
  left: 16, right: 16, top: 16,
  type: 'password',
  message: 'Test password',
  keepFocus: true,
  revealPassword: true
}).appendTo(ui.contentView);
```

**Comment by mpost** [comment]
Bug has been fixed for 3.x and 2.x.
