### ISSUE TITLE
NavigationView issue when trying to prevent interaction with toolbar

### ISSUE THREAD

**Issue by maoamid** [eclipsesource/tabris-js#1907]
### Problem description

Even if an Composite Widget is on top of the `NavigationView` `toolbar`, this not prevent existing `actions` acting on touch event. This issue can be reproduced on a stack with pages scenario where, if the `toolbar` is covered in `contentView` with any widget that haven't a touched event , the `back` action is always triggered, if tapped in the same screen region.
### Expected behavior

Widgets that cover the `NavigationView.toolbar` should prevent touch events on the toolbar.

### Environment

Android 7 / TabrisJS v3.0.1

### Code snippet

```javascript
import {Action, Composite, NavigationView, contentView, device, AlertDialog} from 'tabris';

const IMAGE = device.platform === 'iOS'
  ? 'resources/share-black-24dp@3x.png'
  : 'resources/share-white-24dp@3x.png';

contentView.append(
  <NavigationView stretch background='#e7e7e7'>
    <Action title='Action' image={IMAGE}
        onSelect={() => AlertDialog.open('Action selected.')}/>
  </NavigationView>
);

contentView.append(
  <Composite stretchX height={56} background='#f5b500'/>
);
```

**Comment by mpost** [comment]
This is the expected behavior. A `Widget` lets touches pass through unless it has an appropriate listener attached like `tap` or `touchEnd`.

Closing this issue as works as expected. Please reopen if you see other problems.

**Comment by maoamid** [comment]
@mpost Thank you for clarification, I didn't know that.
