### ISSUE TITLE
Online build issue

### ISSUE THREAD

**Issue by Christian-Kamdem** [eclipsesource/tabris-js#1909]
I got this message each time I try to build online : 
Warning: Command failed: tabris build android  --debug --device --verbose --cordova-build-config="../../../tabrisBuildConfig.json"
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ build: `tsc -p .`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-07-20T10_31_29_023Z-debug.log
The command npm exited with 2
 Use --force to continue.
Aborted due to warnings.
travis_time:end:102a036b:start=1563618679785634688,finish=1563618689057547010,duration=9271912322
The command "grunt build deploy" exited with 6.
Done. Your build exited with 1.

**Comment by maoamid** [comment]
@Christian-Kamdem I think you had various warnings from typescript constraints. Check the details log, it will help you.

**Comment by Christian-Kamdem** [comment]
Thanks,  problem solved! There were some warning in my code.
