### ISSUE TITLE
Attaching a touch event handler on ScrollView breaks the scrolling

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#191]
Attaching a touch event handler like `touchstart` or `touchend` to a ScrollView makes the scroll view not scrollable.

``` javascript
var page = tabris.create("Page", {
  title: "Scroll Composite - Horizontal",
  topLevel: true
});

var scrollView = tabris.create("ScrollView", {
  direction: "horizontal",
  layoutData: {left: 0, top: [40, 0], right: 0, bottom: [40, 0]},
  background: "#234"
}).on("touchstart", function(event) {
  console.log("touchstart triggered: " + JSON.stringify(event));
}).appendTo(page);

for (var i = 0; i < 50; i++) {
  tabris.create("TextView", {
    layoutData: {left: i * 30 + 20, centerY: 0, width: 30},
    text: i + "°",
    foreground: "white"
  }).appendTo(scrollView);
}

page.open();
```

**Comment by ralfstx** [comment]
Is this still valid? Could you try a "tap" gesture listener instead?

**Comment by cpetrov** [comment]
Listening for `tap` on a `ScrollView` generates the following error on the Android client:
```stacktrace
Could not create object "tabris.GestureRecognizer" (reason: 
Attempt to invoke interface method 'void com.eclipsesource.tabris.
client.core.IOperator.create(com.eclipsesource.tabris.client.core.
operation.CreateOperation)' on a null object reference)

Could not listen to event "gesture" (reason: The parameter 'type' 
in call ParamCheck.notNull() must not be null)
```
The iOS client doesn't generate an error, but `tap` never gets triggered.

**Comment by cpetrov** [comment]
`tap` gesture works fine.
Currently `touchstart` blocks scrolling on Android, but works on iOS.
Possible use case would be implementing `focus out` for custom widgets in a scroll view.

**Comment by cookieguru** [comment]
Similarly, listening for `touchend` on a `ScrollView` prevents scrolling on Android but works fine on iOS.  A `scrollend` event is what I was looking for.

```js
var page = new tabris.Page({
  title: '#191',
  topLevel: true
});

var scrollView = new tabris.ScrollView({
  layoutData: {left: 0, top: 0, right: 0, bottom: 0}
}).appendTo(page);

scrollView.on('touchend', function() {});

for(var i = 0; i < 20; i++) {
  new tabris.Composite({
    top: i * 100,
    left: 0, right: 0,
    height: 100,
    background: i % 2 ? 'black' : 'white'
  }).appendTo(scrollView);
}
page.open();
```
Neither platform fires the event.


The following is a valid workaround on Android, but does not work on iOS (no event is fired and no widgets are visible):
```js
var page = new tabris.Page({
  title: '#191 Workaround',
  topLevel: true
});

var scrollView = new tabris.ScrollView({
  layoutData: {left: 0, top: 0, right: 0, bottom: 0}
}).appendTo(page);

var composite = new tabris.Composite().appendTo(scrollView);

composite.on('touchend', console.log);

for(var i = 0; i < 20; i++) {
  new tabris.Composite({
    top: i * 100,
    left: 0, right: 0,
    height: 100,
    background: i % 2 ? 'black' : 'white'
  }).appendTo(composite);
}
page.open();
```


The use case for listening for `touchend` was getting the `ScrollView` to "snap" to certain positions when the user finished scrolling.  It's not a very high priority for me at this time.

**Comment by mpost** [comment]
Thanks for the heads up. I can confirm the issue and we will have a look at it.

**Comment by cookieguru** [comment]
Original snippet seems to have been written for 1.x; rewrote for 3.x and tested this on 3.0.0-beta2 and can confirm scrolling works well on both Android and iOS

```typescript
import {ScrollView, TextView, contentView, WidgetTouchEvent, Composite} from 'tabris';

const scrollView = new ScrollView({
	left: 0, top: '40%', right: 0, bottom: '40%',
	direction: 'horizontal',
	background: '#234',
}).onTouchStart(({type}: WidgetTouchEvent) => {
	console.log(`${type} triggered`);
}).appendTo(contentView);

for (let i = 0; i < 50; i++) {
	new TextView({
		left: i * 30 + 20, centerY: 0, width: 30,
		text: i + '°',
		textColor: '#FFF',
	}).appendTo(scrollView as Composite);
}
```

**Comment by mpost** [comment]
Thanks for the update on the original issue snippet. The attached snippet of code seams to be based on the previous _scrollview.js_ snippet which has just been replaced with a more streamlined [scrollview.jsx](https://github.com/eclipsesource/tabris-js/blob/master/snippets/scrollview.jsx) version.

**Comment by mpost** [comment]
@cookieguru @cpetrov I actully tested your snippet above and found that scrolling and the touch start event worked as expected on 3.x nightly. Can you still reproduce the issue?

**Comment by mpost** [comment]
I just retested the snippet above and found that the Android client does fire the touch start event, while ios does not.
