### ISSUE TITLE
Expose paths to external storage and cache directories on fs

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1910]
### Problem description

Currently, it is not possible to retrieve the location of the external storage and cache directories by using `fs` API alone and one needs to resort to using `cordova-plugin-file` (`cordova.file.externalCacheDirectory` / `cordova.file.externalDataDirectory`).

Those storages are particularly useful for storing files to be accessed by another apps, since `fs.cacheDir`/`fs.filesDir` are private to the app:

https://developer.android.com/guide/topics/data/data-storage.html#filesInternal

> By default, files saved to the internal storage are private to your app, and **other apps cannot access them**.

https://developer.android.com/guide/topics/data/data-storage.html#filesExternal

> Most often, you should use external storage for user data that should be **accessible to other apps** and saved even if the user uninstalls your app, such as captured photos or downloaded files.

### Expected Behavior

Expose API on `fs` providing the paths to external cache and data directories.

### Environment

Tabris.js version: 2.x/3.x

**Comment by mpost** [comment]
We have exposed the two Android specific storage locations in question with the commit https://github.com/eclipsesource/tabris-js/commit/a0ec14b4a8baee88c4c11f84e50abef59dcdcdeb.
