### ISSUE TITLE
Add support for bottom menu 

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-js#1914]
### Problem description
You already have something similar in `TabFolder`. Sometimes you want to use this menu with other widgets, but this is not possible. Alas, while [`Row`](https://github.com/eclipsesource/tabris-js/issues/1823) does not yet exist, there are problems with the automatic horizontal organization of content. It is not convenient to make an adaptive menu without using TabFolder. We have to calculate all the positions of the icons. Please give developers direct access to [`BottomNavigationView`](https://developer.android.com/reference/android/support/design/widget/BottomNavigationView) and [`UITabBar`](https://developer.apple.com/documentation/uikit/uitabbar)

![image](https://user-images.githubusercontent.com/26363214/62413943-818c9f80-b626-11e9-82bb-e59e113a3854.png)

**Comment by mpost** [comment]
Thanks for your feedback. While you are correct that we use the [BottomNavigationView](https://developer.android.com/reference/android/support/design/widget/BottomNavigationView) in the `TabFolder` you can in fact use it "standalone" with some manual work. If you don't specify a height of the tabfolder you it will be as high as the bar. you can than react on the select events to show arbitrary content above it.

Add the native view as a standalone widget is something that could be useful as well though.
