### ISSUE TITLE
Allow to use ImageBitmap, Blob/File and ArrayBuffer as Image.src

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1917]
### Problem description

Currently the `Image` object only accepts paths to an image. It should also accept local images in the form of `ImageBitmap`, `Blob`/`File` and `ArrayBuffer` as image on widgets that accept the `Image` object

### Environment

- Tabris.js version: 3.x

**Comment by tbuschto** [comment]
Done in 3.2.0
