### ISSUE TITLE
Make CollectionView reveal  animated

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-js#1918]
### Problem description
At this point, reveal instantly "teleports" to a given location. In some cases, it looks terrible, especially when the user is in the place where the CollectionView is displayed

### Expected behavior
Make a workflow similar to `ScrollView.scrollToY()`

### Environment
Any

**Comment by mpost** [comment]
This is a good addition which should be added in the future.

**Comment by patrykmol** [comment]
`reveal` is already animated on iOS.

**Comment by patrykmol** [comment]
iOS support for `animate` parameter is implemented.
