### ISSUE TITLE
macOS tabris build error

### ISSUE THREAD

**Issue by gacal** [eclipsesource/tabris-js#1919]
<img width="1211" alt="Ekran Resmi 2019-08-10 02 09 56" src="https://user-images.githubusercontent.com/3254134/62813544-0e969380-bb14-11e9-94f4-9cc4e0064259.png">

npm version : 6.10.3
node version: v12.8.0
cordova version: 9.0.0

can this cause error?

**Comment by jonek** [comment]
@gacal Could you provide more details? This is not a known issue.
What Tabris version do you specify in your `package.json`?
Which Android SDK do you have installed?
Are you using the `tabris-cli`?
Can you execute the build with our online build service?

**Comment by cpetrov** [comment]
Please reopen if you still have this issue.
