### ISSUE TITLE
Provide API allowing placeholders for images loaded remotely

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#192]
Currently when you perform two set operations only the later one wins. The developers should be able to execute a set operation on the same property multiple times. See https://github.com/eclipsesource/tabris-js/issues/176 for background discussion around setting an image on the ImageView.

**Comment by cpetrov** [comment]
+1

**Comment by mpost** [comment]
with the `load` event on an imageview you can now set the placeholder.
