### ISSUE TITLE
Chrome Debugger doesn't see device

### ISSUE THREAD

**Issue by mikeymop** [eclipsesource/tabris-js#1920]
### Problem description

I am following along with the [debugging](https://docs.tabris.com/latest/debug.html) guide.
When I open `chrome://inspect/#devices` I can see the chrome tabs open on my device but not the Tabris application.

Can Chrome debug the application when its run from the tabris application?

### Expected behavior

I'm not sure, bug I would expect the application to appear above the chrome tabs on the debugging device.

### Environment

- Tabris.js version: 3.1
- Device: Android Emulator (pixel2 api 28, Essential PH-1)
- OS: Android 9.0

**Comment by mpost** [comment]
The debug feature is only available when the app itself is build as a debug app. This is not the case for the tabris-js-app from the play store.
