### ISSUE TITLE
Build/run behind a proxy

### ISSUE THREAD

**Issue by edmlin** [eclipsesource/tabris-js#1924]
### Problem description
Cannot build/run behind a network proxy. 
Got an error message "Unable to download platform: getaddrinfo ENOTFOUND tabrisjs.com tabrisjs.com:443" when downloading android platform.
![image](https://user-images.githubusercontent.com/1139804/62959192-36148700-bdc6-11e9-89ff-a5e7554c7ca1.png)
Already added proxy settings in .npmrc and npm is able to download packages through the proxy.
Also tried adding http_proxy and https_proxy environment variables.

### Expected behavior

Build successfully behind a network proxy.

### Environment

- Tabris.js version: 3.1.0

**Comment by cookieguru** [comment]
The build is executed with the Cordova cli, so the node env vars won't have any effect there.  However this error comes before that even happens; it's necessary to download the Cordova platform, which happens with [node's `https`](https://github.com/eclipsesource/tabris-js-cli/blob/57cfff63d4f26dcc70f6ec38388ed47f4ba86d89/src/helpers/download.js#L9) which according to a quick web search does not appear to respect any global proxy settings.  If you're using a trusted cert on the proxy and you can MITM it, you could set the [`TABRIS_HOST`](https://github.com/eclipsesource/tabris-js-cli/blob/57cfff63d4f26dcc70f6ec38388ed47f4ba86d89/src/services/PlatformProvider.js#L11) env var to circumvent it.

Or better yet, log in to tabrisjs.com and [download the platform](https://tabrisjs.com/download/) and place it in (IIRC) `~/.tabris-cli/platforms/` (this needs to be documented)

The platform only needs to be downloaded once, so if you're able to connect the machine to the internet without using a proxy, you can have the CLI download it automatically and continue to build without running in to this error.

**Comment by edmlin** [comment]
Thank you for your reply. 
With your hint and checking the source code, I was able to get past this error.
For anyone else having the same issue here's what I did:
Make a folder "android" under %userprofile%\.tabris-cli\platforms. Make another folder 3.1.0 under the android folder. Download the platform zip file from the above link and unzip to content under the 3.1.0 folder.
