### ISSUE TITLE
Enable platform specific styling

### ISSUE THREAD

**Issue by jkrause** [eclipsesource/tabris-js#193]
If you need to style your app you quickly have to distinguish the platforms in your code. It should be possible to provide platform specific styling information in a better way.

**Comment by mpost** [comment]
With the introduction of custom themes on Android some work has been done in that regards: http://eclipsesource.com/blogs/2015/07/03/tabris-js-1-1-sneak-peak-custom-themes-on-android/

Closing for now.

**Comment by jkrause** [comment]
This can also be achieved now with the selector api: https://tabrisjs.com/documentation/1.4/selector
