### ISSUE TITLE
Problem with Tabris Playground and async function

### ISSUE THREAD

**Issue by DaveTW-Berlin** [eclipsesource/tabris-js#1934]
[I asked this question on Stackoverflow](https://stackoverflow.com/questions/57725467/tabris-js-playground-examples-do-not-work-due-to-async-function) already and I was recommended to open an issue here. The problem is as follows:

I want to start coding with Tabris.js, and try to get some experience with the playground. But every example which uses async function asyncFunctionName(...) doesn't start. The error message is:
`` Could not load main module: Error: Could not parse ./app.js:./app.js:7: ``
`` SyntaxError: Unexpected token function``
`` async function showActionSheet() {``
``.         ^^^^^^^^``
``com.eclipsesource.v8.V8ScriptCompilationException``
``at subscribe (./cordova.js:758:11)``
``at addEventListener (./cordova.js:133:34)``
``at _entryPoint (./cordova.js:1560:18)``

The simple examples like hello.js works well. The shipped examples in the tabris developer app work well. What am I doing wrong?

The answer of Cookie Guru is:
Comparing the output of what the Playground generates to what's inside the app they are definitely different. Tabris.js on Android does not yet support the async/await syntax natively (but iOS does).

This looks like a bug in implementation of the Playground, so it'd be worthwhile to open an issue for that.

**Comment by tbuschto** [comment]
Yeah somehow it doesn't transpile the "async" keyword anymore. I'll try to fix it asap.
