### ISSUE TITLE
Video Widget player state does not update accordingly

### ISSUE THREAD

**Issue by josiahking** [eclipsesource/tabris-js#1935]
### Problem description

When the video player starts playing video, everything works well until it finishes which set the state to finish.
When you try to play the video again using the play(), the state doesn't update correctly.
Most times it remains on finish.

### Expected behavior

By calling the play() video state should update correctly to play, then when you pause or  stop, it should do the same.
### Environment

- Tabris.js version: 2.7.1
- Device: Samsung Galaxy
- OS: Android 6

### Code snippet

```javascript
// A minimal, *self-contained* code snippet to reproduce the problem:
let videoPlayer = new Video({
				left: 0, top: 0, right: 0, height: 350,
				url: record.bgvideo,
				controlsVisible: true,
				//autoPlay: false,
				id: 'video'
			}).appendTo(sectionVideo);
new Button({
				top: '1', left: 12,
				text: 'Play',
				background: '#003504',
				textColor: '#fff',
			}).on('select',() =>{
			console.log(videoPlayer.state)
				if(videoPlayer.state !== 'play'){
					videoPlayer.play();
				}
			}).appendTo(sectionVideoBtn);
```

**Comment by mpost** [comment]
The issue is also resolved on 2.x. In addition we have clarified the docs in the 3.x stream to describe the various `states` better.

**Comment by josiahking** [comment]
@mpost What version of 2.x 
How can i upgrade to the latest 2.x version.

**Comment by cookieguru** [comment]
@josiahking `nightly-2.x`

**Comment by josiahking** [comment]
@cookieguru Thanks.
