### ISSUE TITLE
ConcurrentModificationException with 2 or more gestures detectors

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-js#1936]
### Problem description
If you attach 2 or more gestures listeners, you will get `ConcurrentModificationException`
Log here: https://pastebin.com/J3K9zMCt

### Expected behavior
Don't get exception :-)

### Environment

- Tabris.js version: `nightly (3.2.0-dev.20190907)` and `3.1`
- Device: Xiaomi Redmi 5 Plus
- OS:  Android 8.1.0 

### Code snippet

```js
import { Composite, contentView } from 'tabris';
let composite = new Composite({ width: 100, height: 100, background: '#000' })
    .appendTo(contentView);

composite.onSwipeLeft.once(() => { });
composite.onSwipeRight.once(() => { });
composite.onSwipeUp.once(() => { });
```

**Comment by mpost** [comment]
Thanks for the opened issue. We have resolved the issue. Should be available in the next `nightly`.
