### ISSUE TITLE
ActionSheet action image cannot be undefined/null

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1937]
### Problem description

When setting the image to `null` or `undefined`, the action sheed menu does not appear when calling `open()` on iOS. Works as expected when `"image"` is not a property of the action configuration object.

### Expected behavior

`image` should be configurable as `null` or `undefined` analogous to Tabris.js widget properties.

### Environment

- Tabris.js version: 2.8.1
- OS: iOS

### Code snippet

```javascript
const {ActionSheet} = require('tabris');

new ActionSheet({
  title: 'Actions',
  message: 'Select any of the actions below to proceed.',
  actions: [
    {
      title: 'Cancel',
      image: null, // works as expected without this line
      style: 'cancel'
    },
  ]
}).open();
```

**Comment by mpost** [comment]
Might be related to https://github.com/eclipsesource/tabris-js/issues/1866? This was only fixed on 3.x maybe.

**Comment by patrykmol** [comment]
Fixed.
