### ISSUE TITLE
How do I call other application activity from another application in android?

### ISSUE THREAD

**Issue by Nexter-day** [eclipsesource/tabris-js#1939]
### Problem description

I used cordova-plugin-startapp plugin to call another fb app. Unfortunately, there was an error message. I'm not sure how to fix it

### Expected behavior

Normal use, or does this tabris provide an API?

### Environment

Tabris.js version: 2.7
Device: sharp
OS: android 8.0

### Code snippet

const {} = require('tabris');
const startApp =require('com.lampa.startapp/www/startApp');
var sApp = startApp.set({"package": 'com.facebook.katana'});

**Comment by cookieguru** [comment]
Can you provide the error message?

**Comment by Nexter-day** [comment]
error message image is here [https://gph.is/g/amAmNRJ](url)

**Comment by cookieguru** [comment]
![Screenshot_2019-09-20 Private GIF](https://user-images.githubusercontent.com/1888809/65350498-b767f200-db9a-11e9-8d7e-3c489e11b823.png)

**Comment by Nexter-day** [comment]
sorry,already can open it

**Comment by cookieguru** [comment]
You can also just post the error as text:
`Could not load main module: Error: Cannot find module 'cordova/exec'`

Based on [the plugin's documentation](https://github.com/lampaa/com.lampa.startapp#android) you're not bringing it in to your project correctly.

Note you can also use [`tabris.app.launch`](http://docs.tabris.com/2.7/api/app.html#launchurl) with an [app scheme](https://stackoverflow.com/a/30231726)

**Comment by Nexter-day** [comment]
I have a reading document, but I can't find how to use it correctly.


I am not sure that such a reference is correct.
`const startApp =require('com.lampa.startapp/www/startApp');`

**Comment by cookieguru** [comment]
The plugin exposes a `startApp` global; you don't need to import it

**Comment by Nexter-day** [comment]
I don't understand
Why not import the plugin

Steps that typically use plugin

The first step 
 install the plug-in NPM install com.lampa. Startapp

The second step 
const `startApp` = the require (' com. Lampa.startApp/WWW/startApp ');
var sApp = `startApp`.set ({"package": 'com.facebook.katana'});

Does that mean I don't have to import it in?

**Comment by fax1ty** [comment]
You shouldn't do it. You have to rebuild your app with this plugin. If you use TypeScript (like me), you have to expend your Navigator object (or any object that plugin trigger) and you already can call it

**Comment by fax1ty** [comment]
Tabris doesn't provide instant rebuild. You can't just do `npm i -s somePlugin` and use it like eegular module

**Comment by fax1ty** [comment]
JS plugin code it's just a bridge between executable and Android or iOS natives that should be build with other peaces of native code

**Comment by fax1ty** [comment]
@cookieguru Perhaps, he tried to run exact intent what this plugin helped to achieve, otherwise, @Nexter-day use Tabris functionality. app.launch(url) will do own bests

**Comment by cookieguru** [comment]
@nexter-day
> Why not import the plugin
Unlike an npm package, a Cordova plugin adds functionality with native code.  The plugin does *not* add code to the node_modules folder and thus the import wouldn't work.

Additionally, the plugin's documentation does not indicate that the code should be imported that way.  If you're making up your own syntax you should not be surprised when it doesn't work 😋

> The first step install the plug-in NPM install com.lampa. Startapp
I think the confusion here is that the plugin is hosted on npm.  You do not use npm to install Cordova plugins.  You need to [add the plugin to your `config.xml`](https://docs.tabris.com/2.7/build.html#integrating-cordova-plugins) and then run a build.  Then the plugin's `startApp` will be available in every file, no need to import anything. 



@fax1ty
> If you use TypeScript (like me), you have to extend your Navigator object
Not necessary.  If the plugin is on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) you can include that as a dependency.  If it isn't, it's as simple as placing an interface in an unincluded file (convention is to use `global.d.ts`) and tsc will pick it up.
