### ISSUE TITLE
Developer App on iOS 13 crashes

### ISSUE THREAD

**Issue by tihmels** [eclipsesource/tabris-js#1940]
### Problem description

The Tabris.js App crashes instantly after opening. 

### Expected behavior 

The App starts 

### Environment

- Tabris.js version: 3.1.0.
- Device: iPhone 8
- OS: iOS 13.0

**Comment by cookieguru** [comment]
Probably related to #1926; not sure if that version has been deployed to the App Store

**Comment by mpost** [comment]
Very likely related tp #1926. Please test with the latest `nightly` build. I will close this issue for now.

**Comment by cookieguru** [comment]
@mpost I can confirm that 3.1.0 from the App Store crashes immediately upon launch on iOS 13.1.  Is there any chance of a 3.1.1 release?

**Comment by mpost** [comment]
@cookieguru We are just wrapping up the 3.2 build we are planning to release it this week.

**Comment by fax1ty** [comment]
@mpost 
Week in Phineas and Ferb
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/26363214/65831847-9c019300-e2ce-11e9-96ef-05d37a980f83.gif)
Week in real life
![image](https://user-images.githubusercontent.com/26363214/65832128-3662d600-e2d1-11e9-8d51-5b867283546f.png)

_(yeah, memes in GitHub 👍 )_
