### ISSUE TITLE
Fill layout not working with iPad popover

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1941]
### Problem description
When using a layout filling the available vertical or horizontal space, intrinsic layout is used instead. Works as expected on Android devices and on the iPhone.

|iPad|iPhone|
|---|---|
|![Simulator Screen Shot - iPad Air 2 - 2019-09-24 at 13 54 16](https://user-images.githubusercontent.com/2341769/65485030-4181c480-ded3-11e9-9c8f-afc7ae9e0ca4.png)|![Simulator Screen Shot - iPhone 6s - 2019-09-24 at 13 54 09](https://user-images.githubusercontent.com/2341769/65485046-49416900-ded3-11e9-844b-d247cfcfa9f7.png)|

### Expected behavior

Fill layout should be supported by the popover on the iPad as well.

### Environment

- Tabris.js version: 2.8.1
- Device: iPad Air 2
- OS: iOS 12.4

### Code snippet

```javascript
const {Composite, Popover} = require('tabris');

let popover = new Popover().open();
new Composite({left: 0, top: 0, right: 0, bottom: 0, background: 'red'})
  .appendTo(popover.contentView);
```

**Comment by patrykmol** [comment]
Fixed in `2.x` nightly.
