### ISSUE TITLE
Find better solution for opening developer console

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#1948]
The current methods for opening the developer console may not work anymore on future versions of Android/iOS. They are already hard to find intuitively and execute. So we need a better, more obvious cross-platform solution that works on all kind of devices and on emulators.

**Comment by tbuschto** [comment]
One relatively obvious way would be to have a browser-like toolbar above/below the app area, but then you can't see how the app layout would work in production. 

Second option would be to put something in the notification area of the device that can be tapped to open the console, but that would still be hard to find and annoying to execute.

Third option i can think of is to have a kind of tab/flag sticking in from the right (where the console opens from) overlaying the actual app. You can touch this and swipe left to open the console, basically like before but with more area to grab on to. Of course the would overlap the actual app and could get in the way. To eliviate that I would suggest to a) make it semi-transparent, and b) make it possible to slide it up/down to move it out of the way. Here's a rough draft of what this thing could look like:

![tabris_camera](https://user-images.githubusercontent.com/527303/66327042-68f07c80-e92a-11e9-9dea-3481739c7792.jpg)

**Comment by fax1ty** [comment]
Firstly, I would ask to let the developers decide for themselves how to open the console, as requested here: https://github.com/eclipsesource/tabris-js/issues/1696
Secondly, could I offer my way? As for me, nothing better than [FAB](https://developer.android.com/guide/topics/ui/floating-action-button) I have not seen yet. One button in the bottom right corner of the device

![image](https://user-images.githubusercontent.com/26363214/66329224-3735e080-e93f-11e9-96f3-d2835eae9ccc.png)

Something like
```js
new ImageView({ cornerRadius: 50 / 2, width: 50, height: 50, padding: 15, background: 'white', elevation: 3, highlightOnTouch: true, image: 'https://i.imgur.com/WnF4T4w.png', right: 25, bottom: 25 })
    .appendTo(contentView);
```

**Comment by patrykmol** [comment]
Not very iOS-like but decent idea nevertheless.

**Comment by cookieguru** [comment]
@fax1ty Wouldn't the FAB conflict with the user's app?

**Comment by fax1ty** [comment]
@cookieguru,
Any component that will be placed above the `contentView` will somehow be able to conflict with the design of the users. At least the FAB is designed to be located in the most convenient place to press. Very little useful content (with a tap listener) is located in the bottom right corner.
One more time... You can leave everything as it is, just give developers the opportunity to open the console through the code and they will decide how it will be more convenient for them

**Comment by cookieguru** [comment]
@fax1ty I don't understand.  The link you provided advocates that developers use a FAB for the primary interaction on a screen, and you're saying that it's an unused area.  The flagship Google apps certainly use this design pattern and it is definitely becoming more prevalent amongst other apps.  So if the developer's app has a FAB and this FAB is right on top of it there are surely going to be some problems.

Of course a middle right button can cause conflicts, but certainly less than a bottom right.

**Comment by fax1ty** [comment]
@cookieguru 
I agree, if someone makes his FAB, it will lead to conflict. Just like with any other UI component.
By the way, I still thought how it is possible to make not using UI. How about adding a listener to device shaking? I think it's pretty convenient. Shook the phone and opened the console.

**Comment by mpost** [comment]
Another viable approach would be a full bar which is always visible. similar to the top bar in the current navigation drawer. It will make it easy to discover and is always in reach. It will take away app screen space but that should not be a problem, since you should not rely on any particular dimension anyways.

**Comment by mpost** [comment]
We opted for an implementation with a persistent toolbar at the bottom.

![Screenshot_1582216193](https://user-images.githubusercontent.com/73655/75999345-5c387a80-5f02-11ea-865e-1fdfbff23e62.png)
![Screenshot_1582216202](https://user-images.githubusercontent.com/73655/75999343-5b9fe400-5f02-11ea-86e1-b5b994adef0f.png)
![Screenshot_1582216199](https://user-images.githubusercontent.com/73655/75999346-5c387a80-5f02-11ea-9b70-8b9f81e98ea5.png)

A similar implementation has been created for iOS.

**Comment by fax1ty** [comment]
@mpost 
I finally came face to face with the new Dev Tools. My little review:
1. There is a bug on Android (`keyboardAppearanceMode` is not set inside `TextInput` on top) that causes the keyboard to open endlessly.
2. When you restart (refresh the code) of the application, the top panel opens up again, even if it was closed
3. You cannot close the dev tools panel, but leave the console available. It is very inconvenient to have an unclosed (almost) panel on top that takes up 1/5 of your screen. Please make a way to use only the console

**Comment by mpost** [comment]
Thanks for your feedback. Could you describe how to reproduce the issue you mentioned step by step?

**Comment by fax1ty** [comment]
@mpost Just open any builded app
![ezgif com-resize](https://user-images.githubusercontent.com/26363214/80238666-dd450000-866f-11ea-8c20-dada0794df15.gif)
