### ISSUE TITLE
Crodova plug-in integration broken

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#1949]
It seems with 3.2 we broke non-tabris specific cordova plug-ins because of this line in the forked cordova exec.js: 

`tabris.NativeObject.defineProperties(Plugin.prototype, {service: 'any'});`

**Comment by dennisbappert** [comment]
Any news here? 3.2 is unusable and 3.1 doesn't support the latest iOS version.

**Comment by tbuschto** [comment]
Issue is fixed in latest nightly build
