### ISSUE TITLE
Strange behavior of updateCell for different CollectionView sizes

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-js#1954]
### Problem description
Below are screenshots of `CollectionView` with heights of 150 and 500. In the first option, `CollectionView` can be scrolled, in the second, no.
1) 
![image](https://user-images.githubusercontent.com/26363214/66507122-a9ddc200-eadf-11e9-9956-7d7b30c16f8d.png)
...
![image](https://user-images.githubusercontent.com/26363214/66507144-b4985700-eadf-11e9-9b37-f6f4ee8a3961.png)
2)
![image](https://user-images.githubusercontent.com/26363214/66507184-c24ddc80-eadf-11e9-9537-85e7f9cb1543.png)
Why does the eighth cell mistakenly have an index of 0?

### Expected behavior
I would like all cells to have a prescribed index

### Environment

- Tabris.js version: 3.2 
- Device: Xiaomi Redmi 5 Plus
- OS:  8.1.0

### Code snippet

```typescript
           new CollectionView({
// or height 500 to see difference 
                                top: 0, height: 150, left: 25, right: 25,
                                itemCount: 10,
                                createCell: () => {
                                    let cell = new Composite({ padding: { top: 25 } });
                                    cell.append(
                                        new ImageView({ width: 30, height: 30, cornerRadius: 30 / 2, background: 'gray' }),
                                        new TextView({ left: 'prev() 15', centerY: 0 })
                                    )
                                    return cell;
                                },
                                updateCell: (cell, i) => {
                                    cell.children(TextView).first().text = i.toString();
                                    if (i == 0) cell.children(TextView).first().textColor = 'blue';
                                }
                            })
```

**Comment by fax1ty** [comment]
>That's because the cell isn't reset automatically reset. So instead of  if (i == 0) widget.textColor = style.colors.blue; you need to do widget.textColor = i === 0 ? style.colors.blue : 'initial';. I'll clarify it in the documentation.

Sorry, didn't notice this in the comments

**Comment by fax1ty** [comment]
I finally understood what those words meant. We are required to specify `else` for content that is outside the scope of the condition. Can it be made easier? To be able to operate content simply by specifying the index

**Comment by cookieguru** [comment]
Change
```js
if (i == 0) cell.children(TextView).first().textColor = 'blue';
```
to
```js
cell.children(TextView).first().textColor = i == 0 ? 'blue' : 'black';
```

The cell is re-used, so it makes sense that it's going to keep its properties as it gets shuffled back in to the list.
