### ISSUE TITLE
Serif font used on iOS 13 when no font configured

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1957]
### Problem description

When the font configuration is omitted, a serif font is used with `TextView` on iOS 13. With iOS 12.x and lower, a sans-serif font got used instead.

### Expected behavior

Default to a sans-serif font when the font configuration is omitted. This was the default pre-iOS 13 behavior and is also the behavior when no family is specified in the font configuration (see snippet).

### Environment

- Tabris.js version: 2.8.1
- Device: Simulator
- OS: iOS 13.0

### Code snippet

<img width="98" alt="Screenshot 2019-10-14 at 15 14 33" src="https://user-images.githubusercontent.com/2341769/66734360-65627580-ee95-11e9-8048-9633499ab4f1.png">

```javascript
const {TextView, ui} = require('tabris');

// Create text views with different alignments

new TextView({
  centerX: 0, centerY: 0,
  text: 'Serif on iOS 13',
}).appendTo(ui.contentView);

new TextView({
  centerX: 0, top: 'prev() 10',
  text: 'Sans-Serif',
  font: 'bold 16px'
}).appendTo(ui.contentView);

```

**Comment by patrykmol** [comment]
@cpetrov I am not sure if this issue still exists. Please verify and see my screenshots below (done with newest Xcode 11.3.1).

## iOS 12.2 simulator
![iOS12](https://user-images.githubusercontent.com/12428999/73171082-37c9d100-4100-11ea-9d2f-d3f53b87b47f.png)

## iOS 13.3 simulator
![iOS13](https://user-images.githubusercontent.com/12428999/73171085-37c9d100-4100-11ea-8bdd-54ceeeff1cdc.png)

**Comment by cpetrov** [comment]
Cannot reproduce with Tabris.js 2.9 and 3.3.
