### ISSUE TITLE
Error on writing a programming tutorial application

### ISSUE THREAD

**Issue by jupiter-mic** [eclipsesource/tabris-js#1958]
I'm writing a tutorial app for a programming language in tabris...so I had to use 
```
def function (demo1, demo2){
body
}
```
and also some loops but I'm getting errors, when ever I removed the it works perfectly but when I added it back it throw errors
Please is there any solution to this?

**Comment by cookieguru** [comment]
This is a JavaScript framework; other languages won't work.  Can you explain more about what you're trying to accomplish?

**Comment by tbuschto** [comment]
closed due to inactivity
