### ISSUE TITLE
Webview : Cleartext HTTP traffic not permitted!!??

### ISSUE THREAD

**Issue by Nexter-day** [eclipsesource/tabris-js#1959]
### Problem description

Using webview, failed to connect in higher version of android
Cleartext HTTP traffic to XXX not permitted
Editing cordova/confige.xml is invalid

### Expected behavior

How does it work

### Environment

- Tabris.js version: 2.7
- Device: xperia
- OS: Android 9

### Code snippet

```javascript
<widget >
 <edit-config file="app/src/main/AndroidManifest.xml" target="/manifest/application" mode="merge">
        <application android:usesCleartextTraffic="$IS_DEBUG" />
    </edit-config>
</widget >
```

**Comment by cookieguru** [comment]
Did you build your app after adding the lines to `config.xml`?  Were there any build errors?

**Comment by Nexter-day** [comment]
Yes, I tried to build the app after adding it, and it build success（no erros）

**Comment by cookieguru** [comment]
Can you look at the generated `AndroidManifest.xml` and see if your config made it in?  Use Android Studio (Build > Analyze APK...), apktool, aapt, etc.

**Comment by Nexter-day** [comment]
ohhh，thank so much! Problem is solved!

original set
` <edit-config file="app/src/main/AndroidManifest.xml" target="/manifest/application" mode="merge">`

to 

` <edit-config file="AndroidManifest.xml" target="/manifest/application" mode="merge">`
