### ISSUE TITLE
My App size is too large after online build

### ISSUE THREAD

**Issue by Programmeryusuf** [eclipsesource/tabris-js#1961]
How can I get rid of large Android files made with tabris.js...i need 2MB file I'm seeing 34MB

**Comment by cookieguru** [comment]
Already answered [here](https://tabrisjs.slack.com/archives/C0AQ5BK36/p1571174727089400)

**Comment by mavyfaby** [comment]
Same problem how to fix this?

**Comment by mpost** [comment]
In 3.3 we added support for the android app bundle build switch. See the blog post: https://tabris.com/tabris-js-3-3-released/

```
tabris build android --release -- --packageType=bundle
```
