### ISSUE TITLE
TS: cannot configure readonly properties during instantiation

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1966]
### Problem description

When attempting to configure readonly properties during instantiation, the TypeScript compiler will throw an error.

### Expected behavior

One should be able to configure readonly properties when instantiating custom components.

### Environment

Tabris.js version: 3.2.1

### Code snippet

```ts
class CustomComponent extends Composite {
  // Works as expected after removing the `readonly` modifier.
  @property public readonly myProp: boolean; 
  constructor(properties: Properties<CustomComponent>) {
    super();
    this.set(properties);
  }
}

new CustomComponent({myProp: true});
<CustomComponent myProp />
```
**Compiler output:**
`new CustomComponent({myProp: true});`
-> 
`Argument of type '{ myProp: boolean; }' is not assignable to parameter of type 'Properties<CustomComponent, Pick<CustomComponent, unique symbol | "appendTo" | "insertAfter" | "insertBefore" | "parent" | "siblings" | "append" | "apply" | "children" | "find" | "jsxAttributes" | ... 81 more ... | "myProp">>'.
  Object literal may only specify known properties, and 'myProp' does not exist in type 'Properties<CustomComponent, Pick<CustomComponent, unique symbol | "appendTo" | "insertAfter" | "insertBefore" | "parent" | "siblings" | "append" | "apply" | "children" | "find" | "jsxAttributes" | ... 81 more ... | "myProp">>'. `

`<CustomComponent myProp />`
-> 
`Type '{ myProp: true; }' is not assignable to type 'Partial<Pick<Pick<Pick<CustomComponent, unique symbol | "appendTo" | "insertAfter" | "insertBefore" | "parent" | "siblings" | "append" | "apply" | "children" | "find" | "layout" | "onAddChild" | ... 79 more ... | "myProp">, unique symbol | ... 90 more ... | "myProp">, "layout" | ... 22 more ... | "width">> & { ...; ...'.
  Property 'myProp' does not exist on type 'Partial<Pick<Pick<Pick<CustomComponent, unique symbol | "appendTo" | "insertAfter" | "insertBefore" | "parent" | "siblings" | "append" | "apply" | "children" | "find" | "layout" | "onAddChild" | ... 79 more ... | "myProp">, unique symbol | ... 90 more ... | "myProp">, "layout" | ... 22 more ... | "width">> & { ...; ...'.`

**Comment by tbuschto** [comment]
This is sort-of by design. The type JSXAttributes/Properties types from tabris assume you use the same pattern as the built-in widgets where "readonly" really means "readonly". We calls these one-time-settable properties "const" internally, and they aren't declared as readonly, even though they are after they have been set. Maybe `@property` could be configured to behave like that.

**Comment by tbuschto** [comment]
The type declarations where relaxed a while ago and the above code now compiles
