### ISSUE TITLE
You cannot assign the same camera to two different CameraView

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-js#1967]
### Problem description
When the same camera is assigned to two different `CameraView`s, both `CameraView`s have no camera

![image](https://user-images.githubusercontent.com/26363214/67571260-96b82c80-f744-11e9-95cd-8c1b2ac80599.png)

### Expected behavior
Make it possible to use one camera on two `CameraView`s. If this is not possible, add a note in the documentation about it.

### Environment

- Tabris.js version: 3.2.1
- Device: Xiaomi Redmi 5 Plus
- OS: Android 10

### Code snippet
```typescript
import { contentView, CameraView, device } from 'tabris';

let backCamera = device.cameras.find(c => c.position == 'back');
backCamera.active = true;

new CameraView({ scaleMode: 'fill', background: '#000', width: 100, height: 100, camera: backCamera })
    .appendTo(contentView);
new CameraView({ scaleMode: 'fill', background: '#000', width: 100, height: 100, camera: backCamera, left: 'prev() 25' })
    .appendTo(contentView);
```

**Comment by tbuschto** [comment]
@fax1ty Is this a feature tha twould be useful to you somehow?

**Comment by fax1ty** [comment]
@tbuschto Nah, I don't need that. Just write somewhere that this is wrong and fix the crash.

**Comment by mpost** [comment]
I tested your snippet on the emulator and it works as expected. could you share an exception from the android log?

![Screenshot_1577973095](https://user-images.githubusercontent.com/73655/71670207-88ebdc80-2d6f-11ea-805c-a4646299de63.png)
