### ISSUE TITLE
Strange behavior of CameraView in CollectionView

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-js#1968]
### Problem description
I ran into a very strange problem. `CameraView` after it has been recreated in `CollectionView` loses the `camera`. However, the `camera.active` shows `true`

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/26363214/67569420-dd575800-f73f-11e9-9cf0-61ed65f6d15d.gif)

(`CameraView` also exist)

### Expected behavior
I want the `CameraView` to be active after being recreated in `CollectionView`

### Environment

- Tabris.js version: 3.2.1
- Device: Xiaomi Redmi 5 Plus
- OS: Android 10

**Comment by mpost** [comment]
That is an interesting use-case. We will investigate.

**Comment by mpost** [comment]
The problem is not native to the integration into the `CollectionView`. It can also be reproduced when reparenting the `CameraView`:

```tsx
import { app, CameraView, Composite, contentView, device, permission } from 'tabris';

app.idleTimeoutEnabled = false;
const camera = device.cameras[0];

permission.withAuthorization('camera',
  () => camera.active = true,
  () => console.log('"camera" permission is required.'),
  (e) => console.error(e));

contentView.append(
  <$>
    <Composite stretchX top={0} bottom={'50%'}>
      <CameraView camera={camera} onTap={switchParent}/>
    </Composite>
    <Composite stretchX top={'50%'} bottom={0}/>
  </$>
);

const topParent = $(Composite)[0];
const bottomParent = $(Composite)[1];
const cameraView = $(CameraView).only();

function switchParent() {
  if (cameraView.parent() === topParent) {
    cameraView.appendTo(bottomParent);
  } else {
    cameraView.appendTo(topParent);
  }
}
```

**Comment by elshadsm** [comment]
The issue has been resolved.
