### ISSUE TITLE
The value of device orientation property is constant

### ISSUE THREAD

**Issue by ahmadov** [eclipsesource/tabris-js#1970]
### Problem description
The value of `device.orientation` property does not change when the orientation changed.

### Expected behavior
The value of `device.orientation` property should change when the orientation changed.

### Environment

- Tabris.js version: 3.2.1
- Device: Any
- OS: Any

### Code snippet

```jsx
import {contentView, device, TextView} from 'tabris';

contentView.append(<TextView padding={16} markupEnabled font={'16px'} lineSpacing={1.4}/>);

device.onOrientationChanged(({value}) => renderDeviceProperties());
renderDeviceProperties();

function renderDeviceProperties() {
  $(TextView).only().text =
    <$>
      <b>Orientation:</b> {device.orientation}<br/>
    </$>
  ;
}
```

**Comment by tbuschto** [comment]
The orientation was cached in JS, the fix for that is currently in gerrit. However, in Android it still does not give the correct value. It seems to give the previous orientation. Thoughts @mpost ?

**Comment by mpost** [comment]
@tbuschto Running the device.jsx snippet and rotating the device works as expected. what aspect does not work for you?

**Comment by ahmadov** [comment]
@mpost I can still reproduce by running `device.jsx` on an Android device. This could happen at first try or after multiple tries. These are the screenshots from the latest Tabris.js app:

![Screenshot_20200505-115116](https://user-images.githubusercontent.com/7130712/81156399-31ac8180-8f86-11ea-99fd-cb973524453c.png)

![Screenshot_20200505-115123](https://user-images.githubusercontent.com/7130712/81156403-32ddae80-8f86-11ea-9683-2212a51cdfef.png)

**Comment by mpost** [comment]
I can confirm your observation. We will look into it.

**Comment by ahmadov** [comment]
I've built an app uses the Tabris.js nightly and the value of orientation property is always `unknown` now.

**Comment by mpost** [comment]
Agreed. It works as expected in the emulator but not on a real device. We will look into it.
