### ISSUE TITLE
Tabris app fails to establish websocket connection with server

### ISSUE THREAD

**Issue by NEMESYS43** [eclipsesource/tabris-js#1974]
### Problem description

My Tabris app will not connect to my WebSocket server or my socket.io server I have tried both and neither work but the same code works flawlessly in a static HTML file with the same script

### Expected behavior

I would expect for it to just connect right away with no errors but using this

```javascript
socket.addEventListener('error', function (event) {
  console.log('WebSocket error: ', event);
});
```

### Environment

- Tabris.js version: 3.2.1
- Device: Samsung Galaxy S8
- OS: Android 9.0

### Code snippet

```javascript
var socket = new WebSocket('ws://127.0.0.1:4343', []);
 
socket.addEventListener('error', function (event) {
  console.log('WebSocket error: ', event);
});
```

**Comment by fax1ty** [comment]
1) Socket.IO not suitable as a socket server for Tabris as far as I understand from experience
2) You MUST specify the protocol type as the second argument. I use `chat-protocol`

**Comment by NEMESYS43** [comment]
using the exact same websocket api in tabris i was able to connect to a socket.io server but still in tabris if i try to just connect with a barebones websocket server nothing happens

**Comment by NEMESYS43** [comment]
You were right my bad i just needed to add the 'chat-protocol' to my code i feel super stupid now lol is 'chat-protocol' actually a thing like what exactly does it specify i thought we were connecting over websockets is like a sub protocol
