### ISSUE TITLE
Worker Works well on Tabris developper App but not in compiled app

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1975]
I created a worker and it's works well on Tabris developper app but after the app compilation the worker return an error
 Expected behavior
Worker works on compiled app
 Environment
Tabris 3.2.1
Huawei P10 lite
Android 8.1
![Screenshot_20191023-113632](https://user-images.githubusercontent.com/12398336/68594633-4822c600-0498-11ea-9ad2-b17ea3b49383.jpg)

**Comment by cookieguru** [comment]
Please post your code snippet

**Comment by ishigo1987** [comment]
```
const workerContacts = new Worker("./src/helpers/extractContactsNumbers.js");
          workerContacts.onmessage = (event) => {
             workerContacts.terminate();
          };
          workerContacts.onerror = (error) => {
            console.error(`onerror: ${JSON.stringify(error)}`);
            workerContacts.terminate();
          };
           workerContacts.postMessage(['just a test']);
​
​
// this is the worker
​
global.onmessage = (data)=>{
  console.log(data);
};
```

**Comment by tbuschto** [comment]
I suspect the worker script is not included in the compiled app, or not at the same path. This can easily be the case when using Webpack or the TypeScript compiler. Please post your `package.json` and `.tabrisignore` files (if any).

**Comment by ishigo1987** [comment]
ok but i'm not using typescript or webcam i'm using the old plain javascript
```
{
  "main": "src/app.js",
  "private": true,
  "scripts": {
    "test": "eslint .",
    "start": "tabris serve -a -i"
  },
  "dependencies": {
    "awesome-phonenumber": "^2.21.0",
    "base-64": "^0.1.0",
    "tabris": "3.2.1"
  },
  "devDependencies": {
    "eslint": "^5.15.1"
  }
}

```

**Comment by ishigo1987** [comment]
tabrisignore
.eslintrc
.gitignore
.vscode/
node_modules/**/*.d.ts
node_modules/tabris/ClientMock.js
package-lock.json
README.md

**Comment by ishigo1987** [comment]
![IMG_20191112_145836](https://user-images.githubusercontent.com/12398336/68677877-24758380-055d-11ea-80dc-75c939ce4341.jpg)
The worker script is included in the compiled app, have you trying to reproduce the issue?

**Comment by tbuschto** [comment]
Yes, i copied your package.json and made a non-compiled app with the posted scripts:
https://github.com/tbuschto/tabris-worker-test
It works fine using the build service.

I'm still leaning towards script is not found since this is the only significant difference between sideloading and built app that i can see. Maybe I asked this before, but does it work ONLY in the developer app, or also in the built app when sideloading via the dev console?

**Comment by ishigo1987** [comment]
it's not working on the debugging compiled app, i never try to sideloading code via the dev console

**Comment by tbuschto** [comment]
Please try that it would help to narrow the issue down.

**Comment by ishigo1987** [comment]
Same problem after the code sideloading

**Comment by ishigo1987** [comment]
![IMG_20191112_171540](https://user-images.githubusercontent.com/12398336/68689083-21d05980-0570-11ea-9e7d-6b291c2a6a21.jpg)
Good when i execute code from tabris developper app

**Comment by ishigo1987** [comment]
Bad from sideloading code from
![IMG_20191112_171648](https://user-images.githubusercontent.com/12398336/68689236-55ab7f00-0570-11ea-9215-e1c8a625d671.jpg)
 my built app

**Comment by ishigo1987** [comment]
I've this error too
![IMG_20191112_172103](https://user-images.githubusercontent.com/12398336/68689609-e8e4b480-0570-11ea-96d6-f74dee5e6ce8.jpg)

**Comment by tbuschto** [comment]
Maybe it's a cordova plug-in, do you use any?
@mpost The error says filename "undefined" and "colno" -1. Is that an expected behavior in any scenario?

**Comment by ishigo1987** [comment]
@tbuschto exactly i suspect the same thing(cordova plugin) i using a lot of cordova plugin and i suspect that one of them have some worker mechanism and it interfer with regular tabris worker
i make another build with no plugin i will let you know

**Comment by ishigo1987** [comment]
Same problem

**Comment by cookieguru** [comment]
Works for me:

![Screenshot_20191113-003943](https://user-images.githubusercontent.com/1888809/68746952-75fa2e80-05ae-11ea-81fa-d69f22be41b1.png)


```plain
.
├── cordova
│   └── config.xml
├── node_modules
│   └── tabris
│       (snip)
├── package.json
├── package-lock.json
└── src
    ├── app.js
    └── worker.js
```

`package.json`:
```json
{
  "main": "src/app.js",
  "scripts": {
    "start": "tabris serve -a"
  },
  "dependencies": {
    "tabris": "~3.2.1"
  }
}
```
`app.js`:
```js
const worker = new Worker('./src/worker.js');

worker.onmessage = (event) => {
        worker.terminate();
};

worker.onerror = (error) => {
        console.error(`onerror: ${JSON.stringify(error)}`);
        worker.terminate();
};

worker.postMessage(['just a test']);
```
`worker.js`:
```js
global.onmessage = (data) => {
        console.log('Worker received:', data);
};
```

**Comment by elshadsm** [comment]
@ishigo1987, I took the [repository](https://github.com/tbuschto/tabris-worker-test) (which contains your snippet and configuration), built a client then ran it on Android 8.1 (Pixel 2) and Android 10 (Pixel 3). Everything works as expected.

Could you please share the detailed logs of your built client?

**Comment by ishigo1987** [comment]
For some reason that i can't explain
This plugin 
https://www.npmjs.com/package/cordova-plugin-network-information 
is why tabris worker doesn't work

**Comment by cookieguru** [comment]
@ishigo1987 As mentioned before, posting the full build log can help diagnose the issue

**Comment by ishigo1987** [comment]
The problem was not the build, i can build the app with no problem
The issue is resolved
Thank you everyone
