### ISSUE TITLE
Cannot build apps with plugins using CocoaPods

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1980]
### Problem description

Due to an incompatibility of the current iOS platforms (`3.2.1`, `2.9.0`) with a newly updated version of CocoaPods used by our build service provider, app builds will fail when an app uses a Cordova plugin that has a CocoaPods dependency (e.g. `tabris-plugin-firebase`). We are working on a fix for our next release.

### Workaround
As a workaround, a script can be setup to install the older CocoaPods version compatible with the currently available platforms. Please mind that the setup of the older CocoaPods version takes a long time, build time will be increased by ~10 minutes.

Create a file:

`cordova/scripts/setup_cocoapods_repository.sh`

... with contents:

```sh
#!/bin/sh
if [[ "$OSTYPE" == "darwin"* ]]; then
  echo "Setting up CocoaPods compatible with tabris <= 2.9.0/3.2.1 ..."
  sudo gem install cocoapods -v '1.5.3'
  pod setup
fi
```

And add:

```xml
  <hook type="before_platform_add" src="scripts/setup_cocoapods_repository.sh" />
```
inside the `<widget/>` element of your `cordova/config.xml`.

### Environment

- Tabris.js version: `3.2.1`, `2.9.0`
- OS: iOS

**Comment by mpost** [comment]
We have updated tabris 3.x nightly to use cordova 9.0 which should enable cocoapod support. please give it a try.

**Comment by patrykmol** [comment]
CocoaPods are now supported thanks to Cordova update.
