### ISSUE TITLE
Weird Behaviour on CollectionView For Android

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1981]
### Problem description

Duplicate action events on cell item  with different index

### Expected behavior

No duplicate event
![Screenshot_20191208-173454](https://user-images.githubusercontent.com/12398336/70392539-67ead280-19e1-11ea-9455-74c7aa1ef782.jpg)
![Screenshot_20191208-173501](https://user-images.githubusercontent.com/12398336/70392540-6e794a00-19e1-11ea-899a-07330ce771e2.jpg)

 action

### Environment

- Tabris.js version: 3.2.1
- Device: Huawei P10 lite
- OS: Android 8.1

### Code snippet

```javascript
const{app,Composite,CollectionView,TextView,contentView} = require("tabris")

const items = ['Apple', 'Banana', 'Cherry', 'Mangoes', 'WaterMelon', 'pineapple', 'Tomatoes', 'Plum', 'Quince', 'Pear', 'Lemon', 'Orange', 'Blackberry', 'Blueberry', 'Raspberry', 'Strawberry', 'Coconut', 'Passion fruit', 'Apricot'];

new CollectionView({
  left: 0, top: 0, right: 0, bottom: 0,
  itemCount: items.length,cellHeight:70,
  createCell: () =>{ 
  	const cell = new Composite({left: 0, top:["prev()",0], right: 0, height: 70, highlightOnTouch:true});
  	
  	new TextView({left:15,centerY:0}).appendTo(cell);

  	cell.onTap(({target})=>{
  		
  		target.background = "red";
  	});
  	return cell;
  },
  
  updateCell: (view, index) =>  {
    
    view.find(TextView).only().text = items[index];
  }
}).appendTo(contentView);
```

**Comment by ishigo1987** [comment]
The second image with the red band on blueberry is after the collectionView scroll the red band is duplicate

**Comment by fax1ty** [comment]
1) Please, don't use `.only()` this will throw error if widget has more than one child. Use `.first()` instead
2) use .onX in updateCell section

**Comment by ishigo1987** [comment]
@fax1ty  Done but same behaviour duplicate red band, check on your side please

**Comment by ishigo1987** [comment]
By onX you want to mean onTap right?

**Comment by fax1ty** [comment]
@ishigo1987 
I meant the indication of any event.

I'm not sure what you want to do. Now your code makes it so that any cell now when pressed becomes red

**Comment by fax1ty** [comment]
Maybe you need this?
```js
cell.onTap(({target})=>{
if (needToMakeRed) target.background = 'red';
else {}
});
```

**Comment by ishigo1987** [comment]
I need just the cell where I click to turn red, but strangely enough this behavior is repeated on a new cell when the next cells enter the screen and so on

**Comment by ishigo1987** [comment]
its weird because
```
cell.onTap(({target})=>{
console.log(target) // return the good cell
});
```
But why this duplicating happen?

**Comment by fax1ty** [comment]
I have already encountered this problem

https://github.com/eclipsesource/tabris-js/issues/1954

**Comment by fax1ty** [comment]
You must strictly specify which cell should be red and which is not. Use index matching

**Comment by ishigo1987** [comment]
I try something like that with no success same duplicate red band
```
view.onTap(({target})=>{
  		
  		if(target.parent(CollectionView).itemIndex(target) === index){
  			target.background = "red"
  		}else{
  			target.background = "white"
  		}
  	});
```

**Comment by fax1ty** [comment]
??????? It's always true
if(collection[index].isNeedToBeRed) target.red; else ....

**Comment by ishigo1987** [comment]
Damn you right i'm tired :v :v :v

**Comment by ishigo1987** [comment]
if i can add something else, if you want to listenning some events on your collectionView cells add them on cells in the createCell() method otherwise you will suffer from event callback duplication
