### ISSUE TITLE
Setting placement property of Action to "navigation" does not work as expected

### ISSUE THREAD

**Issue by ahmadov** [eclipsesource/tabris-js#1982]
### Problem description

Setting placement property to 'navigation' makes the Action unvisible on Android.
The behaviour is strange when setting placement property to 'navigation'. If the Action is text-only it's not visible but it's visible when the image property is set. Maybe that behaviour is expected but I could not find any information in the documentation.

### Expected behavior

The Action is visible even if image property is not set.

### Environment

- Tabris.js version: 3.2.1-dev.20191014
- Device: Pixel 3
- OS: Android 10

### Code snippet

```jsx
import {Action, NavigationView, contentView, device} from 'tabris';

contentView.append(
  <NavigationView stretch>
    <Action placement='navigation' title='Close'/>
    <Action placement='default' title='Settings'/>
    <Action placement='overflow' title='Share'/>
  </NavigationView>
);
```

**Comment by mpost** [comment]
The action is placed correctly in your snippet. The reason why you don't see it, is that the action does not support text as a navigation action. Please use an appropriate icon to visualize the action.
