### ISSUE TITLE
How To Set DateDialog language?

### ISSUE THREAD

**Issue by Nexter-day** [eclipsesource/tabris-js#1985]
### Problem description
How to set the language of “DateDialog”？

### Expected behavior
I hope you can set up different languages

### Environment

- Tabris.js version:  3.2
- Device:  iphone 6s
- OS:  IOS 12

### Code snippet
none

**Comment by cookieguru** [comment]
I believe https://github.com/eclipsesource/tabris-js/issues/1756#issuecomment-435836082 applies in the same way

**Comment by Nexter-day** [comment]
Thanks for the hint, I can set it directly through xcode, it's work! ：）
