### ISSUE TITLE
Provide connectionType property on Device

### ISSUE THREAD

**Issue by ifurnadjiev** [eclipsesource/tabris-js#199]
Both Android and iOS clients support connectionType property on Device. We should expose this property as API on tabris.js. Currently, I'm using the following code:

util.extend( tabris._Device._checkProperty, { connectionType: true } );
function isNetworkConnected() {
  return tabris( "_Device" ).get( "connectionType" ) !== "OFFLINE";
}

which works fine on both Android and iOS.

**Comment by ralfstx** [comment]
@hstaudacher Can you easily include this Cordova plugin in the developer app?

**Comment by ifurnadjiev** [comment]
The org.apache.cordova.network-information is already included in the developer app and it's used to obtain connection type.
