### ISSUE TITLE
CollectionView Bug

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#1992]
### Problem description

CollectionView make the app crash when i add too much images(like gallery app), more than 400 pictures

### Expected behavior

Not crashing

### Environment

- Tabris.js version: 3.3
- Device: Huawei p10 lite, Archos
- OS: Android 8.1

```

**Comment by fax1ty** [comment]
This is not exactly a bug. I understand that you do this directly, in the main UI thread? Each action takes some time. Because you do this in the UI thread, the system thinks the app is stuck and stops it. You need to do this through [Worker](https://docs.tabris.com/latest/w3c-api.html#worker).

**Comment by ishigo1987** [comment]
it's not possible to display a collectionView inside a worker
i retrieve the array of picture from my server and i display the pictures inside a collectionView of images

**Comment by cookieguru** [comment]
The retrieval should be done inside the worker

**Comment by fax1ty** [comment]
I assume you're setting the original images. Each image requires memory. 400 Full HD images-1Mb * 400 = 400 MB. It's too much at one time. Use thumbnails and don't load everything at once. Use the separated queries.

**Comment by ishigo1987** [comment]
the problem is not really the retrieval let me explain again where the bug is
retrieve the picture(from flickr api) is not a problem 
i add the pictures insides a collectionView with no problem
The bug appear when i try to scroll the collectionView fastly 
the app reload
@fax1ty  i'm not setting the original images

**Comment by ishigo1987** [comment]
```javascript
new CollectionView({
                        top: 0, left: 0, right: 0, bottom: 0, itemCount: responseWebService.Data.length, scrollbarVisible:false, columnCount: 3, cellHeight: cellHeight,
                        createCell: () => {
                            const cell = new Composite({ width: cellHeight, height: cellHeight, class: 'cell' });
                            new ImageView({ scaleMode: 'fill', highlightOnTouch: highlightOnTouchValue, width: cellHeight, height: cellHeight, id: 'userPicture' }).appendTo(cell);
                            new Composite({ bottom: 0, left: 0, right: 0, height: 1, background: theme.additionalColor.loaderBg }).appendTo(cell);
                            new Composite({ left: 0, top: 0, bottom: 0, width: 1, background: theme.additionalColor.loaderBg }).appendTo(cell);
                            new Composite({ bottom: 0, top: 0, right: 0, width: 1, background: theme.additionalColor.loaderBg }).appendTo(cell);
                            new Composite({ top: 0, left: 0, right: 0, height: 1, background: theme.additionalColor.loaderBg }).appendTo(cell);
                            cell.onTap(() => {
                                const index = cell.parent(CollectionView).itemIndex(cell);
                                // do something with the item...
                                
                            });
                            return cell;
                        }, updateCell: (cell, index) => {
                            const picture = cell.find('#userPicture').only();
                            picture.image = { src: responseWebService.Data[index].picture, width: cellHeight, height: cellHeight };
                        }  
                    }).appendTo(displayResultComposite);
```

**Comment by cookieguru** [comment]
What are the dimensions of the image and the dimensions of the cell?

**Comment by ishigo1987** [comment]
cellDImension = screenHeight / 3
dimension of image = screenHeight / 3

**Comment by fax1ty** [comment]
Better show the error log. What exactly is written in the crash log?

**Comment by ishigo1987** [comment]
Nothing special in the log, it looks like a memory saturation, when I go down to 100 pictures the problem disappears.
with TabrisJs 3.1 I could display a collectionView of 1000 pictures from my gallery without any problem.
I feel like there was a regression.

**Comment by cookieguru** [comment]
What are the dimensions of the _actual_ image?  Like @fax1ty said, if you're displaying it as 400x300 but the image is 800x600 you're wasting memory

**Comment by ishigo1987** [comment]
i don't know what is the actual dimensions flickr api does not give me thoses dimensions
But according to the tabris documentation the image are internal resizing when i provide with and height inside a image object

**Comment by fax1ty** [comment]
Check it out: https://github.com/mapbox/thumbnail-stream

**Comment by ishigo1987** [comment]
Thank you i thing that i will change my architecture
1) sending to my server the user screen width dimension
2) Get the images to the flickr api
3) resize the images to the exact user screen width dimension divide by 3 with https://github.com/lovell/sharp
4) send back the  resizing pictures to the user

**Comment by cookieguru** [comment]
The Flickr API can return several different sized thumbnails

https://www.flickr.com/services/api/flickr.photos.getSizes.html

**Comment by ishigo1987** [comment]
Yes i know that thank you
