### ISSUE TITLE
topGap CollectionView property

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-js#1994]
At this point, making the separation between two widgets in `CollectionView` is more difficult than it might be. 

Now there are two options: 

1. Calculate the cell size in `cellHeight`
2. Wrap the widget in `Composite` and set `padding`.

How about making a `topGap` property that will do automatically add value to `cellHeight`?

**Comment by mpost** [comment]
As you described there are numerous ways to achieve the desired effect and it is very use-case dependent. Therefore a method to create additional separation is currently not planned.
