### ISSUE TITLE
ImageView produces error message when zoomEnabled is set to false in the constructor

### ISSUE THREAD

**Issue by ifurnadjiev** [eclipsesource/tabris-js#1995]
This snippet produces 3 errors: 
ImageView[cid="$89"]: Ignored unsupported value for property "zoomLevel": zoomLevel can not be set when zoomEnabled is false
ImageView[cid="$89"]: Ignored unsupported value for property "minZoomLevel": minZoomLevel can not be set when zoomEnabled is false
ImageView[cid="$89"]: Ignored unsupported value for property "maxZoomLevel": maxZoomLevel can not be set when zoomEnabled is false

```
import {ImageView, contentView} from 'tabris';
new ImageView({zoomEnabled: false, left: 0, top: 0, right: 0, bottom: 0}).appendTo(contentView);
```

**Comment by tbuschto** [comment]
Yes, I see in the code how this could happen. Should be an easy fix. However, these are only warnings and can be safely ignored.
