### ISSUE TITLE
TextView with padding and highlightOnTouch are highlighted incorrectly

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-js#2000]
### Problem description
This bug is very old, I've always seen it, but I was always too lazy to open the issue, since I have a simple workaround. But I think using one widget instead of two is much more convenient, so it seems to me that this is a bug, not a feature.

![](https://i.imgur.com/1niChRd.gif)
I can only tap once, after which the highlighting fills the entire widget and doesn't work anymore
### Expected behavior
![](https://i.imgur.com/Qgo4YIq.gif)
If you wrap `TextView` in `Composite` everything will be executed properly

### Environment

- Tabris.js version: 3.x
- Device: Xiaomi Redmi 5 Plus
- OS: 8.1.0

### Code snippet
*bad* code
```typescript
import { contentView, TextView } from 'tabris';
new TextView({ top: 15, left: 0, right: 0, background: '#eee', padding: 15, text: `HTTP 200 OK\nAllow: GET, HEAD, OPTIONS\nContent-Type: application/json\nVary: Accept\n\n[\n{},\n{},\n{}\n]`, highlightOnTouch: true })
    .appendTo(contentView);
```

*good* code
```typescript
import { contentView, TextView, Composite } from 'tabris';
new Composite({ highlightOnTouch: true, top: 15, left: 0, right: 0, background: '#eee', padding: 15 })
    .append(
        new TextView({ text: `HTTP 200 OK\nAllow: GET, HEAD, OPTIONS\nContent-Type: application/json\nVary: Accept\n\n[\n{},\n{},\n{}\n]` })
    )
    .appendTo(contentView);
```

**Comment by mpost** [comment]
Issue 2000 :) We will verify the issue. :)

**Comment by fax1ty** [comment]
@mpost happy 2000s

**Comment by elshadsm** [comment]
Fixed in the upcoming 3.x release.
