### ISSUE TITLE
Cannot Run TabrisJs App On iOS Device

### ISSUE THREAD

**Issue by jokorivai** [eclipsesource/tabris-js#2004]
### Problem description

Yesterday I found a problem, Tabris CLI no longer able to run TabrisJs app directly on iOS device (iPhone 7). I Opened the project in Xcode, set up development team, set up requirements like trust certification, and ran the app, it did build and got installed on the iPhone, but couldn't run. 
The very same app ran smoothly on iOS simulator, but no on the iPhone.

An hour ago I realized that I was using `cordova-plugin-file` within the app, so I created a new TabrisJs app without any modification and run it into the iPhone, still no luck. Pure Cordova app, in the other hand, created with `cordova create app_name` did run with no problem at all. So this particular problem should be related to TabrisJs framework. 

<img width="1013" alt="Screen Shot 2020-02-24 at 22 59 31" src="https://user-images.githubusercontent.com/11798147/75164185-5c46b680-575b-11ea-809b-4b942bb97640.png">

<img width="858" alt="Screen Shot 2020-02-24 at 22 59 57" src="https://user-images.githubusercontent.com/11798147/75164252-7da7a280-575b-11ea-966f-4c46ee5962ed.png">

### Expected behavior

TabrisJs app should run normally on iOS devices as well as on simulator.

### Environment

- Tabris.js version: 3.3.0
- Device: iPhone 7
- OS: iOS 13.3.1

### Code snippet

```javascript
// No snippet, sorry. 
It just some code Tabris CLI generates to display "TabrisJs Rocks!"
```

**Comment by karolszafranski** [comment]
I've been able to compile and run the hello world app on my phone when using:
```
  "dependencies": {
    "tabris": "3.3.0"
  }
```

Which Xcode version do you use?

Can you please verify if `Tabris.framework` exists in the project (in Tabris folder) and if it is listed on the list of embedded content in the "General" tab of the app target settings? It also has to be embedded and signed. Like you see on the screenshot I attached below.

<img width="1392" alt="Screen Shot 2020-02-24 at 16 47 20" src="https://user-images.githubusercontent.com/1746396/75167643-f68c0780-5725-11ea-9b1f-e5023d8a5c65.png">

**Comment by jokorivai** [comment]
> Which Xcode version do you use?

I use Xcode 11 on OSX Catalina. 

> Can you please verify if `Tabris.framework` exists in the project (in Tabris folder) and if it is listed on the list of embedded content in the "General" tab of the app target settings?

Yes. It does exists there. 
In fact, I uses to be able to compile and run into my iPhone using the same OSX version, the same Xcode but with TabrisJs v3.2.1.
Things stopped working after updating TabrisJs to 3.0. I tried to revert back to 3.2.1 but the peroblem persisted.

**Comment by karolszafranski** [comment]
I suggest trying once again making a clean build. Please remove `build` directory and clear `tabris-js-cli` platforms cache:
```
$ rm -Rf ~/.tabris-cli/platforms/ios/
```

Other than that it looks very similar to this issue https://github.com/flutter/flutter/issues/49504 and on your screenshot, I see that you're using a personal provisioning profile. Do you have a possibility to try with a non-personal?

Is it possible that your device updated to iOS 13.3.1 in the meantime? Since you say that it stopped working for Tabris.js 3.2.1 as well I suspect that it might be a reason.

**Comment by jokorivai** [comment]
> ... I see that you're using a personal provisioning profile. Do you have a possibility to try with a non-personal?
Yes it is a personal profile. I have no paid profile yet. 
I also found this [https://github.com/Alamofire/Alamofire/issues/3051#issuecomment-580139830](https://github.com/Alamofire/Alamofire/issues/3051#issuecomment-580139830) which is toward your point.

> Is it possible that your device updated to iOS 13.3.1 in the meantime? Since you say that it stopped working for Tabris.js 3.2.1 as well I suspect that it might be a reason.
Yes. It is recently updated to 13.3.1

For now, a conclusion comes to my mind (as many other suggest): Apple doesn't allow any third party framework to be signed using a personal provisioning profile. While this may be wrong, I am closing this issue for now.
