### ISSUE TITLE
Some images Path does not work with TabrisJs 3.3.0

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#2005]
### Problem description

tabris 3.3.0 ImageView() can't load the picture with this path
content://media/external/images/media

### Expected behavior

ImageView() load images from content 

### Environment

Tabris 3.3.0

A workaround is to use the cordova-plugin-filepath to resolve the content path to  file path

**Comment by mpost** [comment]
Could you provide a snippet showing how to create and consume such a path in tabris.js?

**Comment by ishigo1987** [comment]
This kind of path? content://media/external/images/media
i get this kind of path from an intent to open a gallery
i use this plugin for the intent darryncampbell-cordova-plugin-intent

**Comment by jokorivai** [comment]
A snippet code would explain the problem better.

**Comment by mpost** [comment]
Do you see any security exceptions in the Android adb log?

**Comment by mpost** [comment]
In general it also works in the Tabris.js android client. i am for example able to display an image with a content uri such as `content://com.android.providers.media.documents/document/image%3A37`. (Note that the `:` colon char is html escaped). It is important to note that the file can only be read once after beieng picked from the intent ui.

**Comment by ishigo1987** [comment]
yes in some cases i was not able to display the image, in some others cases i was.
I didn't have to check the logs what I did when I got an error in the console about image not being able to load is to install the cordova plugin cordova-plugin-filepath.
you want which code snippet exactly? the one where I get the path to the image via the intent plugin

**Comment by mpost** [comment]
would be interesting to see.

**Comment by cookieguru** [comment]
That and logcat.  If there is an exception on the native side they won't log to the developer console

**Comment by ishigo1987** [comment]
When an image wasn't able to load into the console I had a message like the image... could not be loaded

**Comment by jokorivai** [comment]
@ishigo1987 would you like to share your snippet you use for loading the image?

**Comment by ishigo1987** [comment]
for loading the images a use another plugin, a plugin for intent
```javascript
module.exports = ()=>{
    return new Promise((resolve)=>{
        require("./plugins/intentStartActivityForResult.js")({ action: window.plugins.intentShim.ACTION_GET_CONTENT, type: "image/*"}).then((responseIntent)=>{
            if (responseIntent.Message === "Activity response"){
                resolve({ Message: "Picture available", Data:{imagePath:responseIntent.Data.data}})
            }
        });
    });
};
```

**Comment by mpost** [comment]
Maybe the image is loaded twice. Please do check the adb logs for any exception.

**Comment by ishigo1987** [comment]
ok

**Comment by mpost** [comment]
Closing this issue for now. Please reopen if you have any more related issues or create a new issue with a more specific topic.
