### ISSUE TITLE
cordova-plugin-purchase how to set manifest.json  google key

### ISSUE THREAD

**Issue by Nexter-day** [eclipsesource/tabris-js#2007]
### Problem description
Set up the cordova-plugin-purchase 

But I'm having trouble figuring out how to add manifest.json to a tabris js project

Cordova can be used with "play_store_key"

Is there any help and how to set it up properly

### Expected behavior
Manifest.json can be set correctly

### Environment

- Tabris.js version: 3.3
- Device: htc 
- OS: android 7.1

### Code snippet

```javascript
 <plugin name="cordova-plugin-purchase" spec="https://github.com/AlexDisler/cordova-plugin-inapppurchase.git"/>
    <platform name="android">
       <config-file mode="merge" parent="/manifest" platform="android">
            <preference name="play_store_key" value="KEY"/>
        </config-file>
    </platform>
```

**Comment by mpost** [comment]
The cordova subdir in your projects root acts as the cordova root dir. everything that should be in the cordova root should be in that subdir.

**Comment by fax1ty** [comment]
@Nexter-day While I was looking for information about your plugin, I found a couple of better options. Take a look

| Version | Guide | How to set the key | Updatability |
|:----------------------------------------------------------:|:----------------------------------------------------------------------------------:|------------------------|--------------|
| [cordova-plugin-purchase](https://github.com/j3k0/cordova-plugin-purchase/) | [click](https://github.com/j3k0/cordova-plugin-purchase/wiki/Setup-for-Android-Google-Play) | **config.xml**/widget: ```  <plugin name="cordova-plugin-purchase" spec="https://github.com/j3k0/cordova-plugin-purchase.git"><variable name="BILLING_KEY" value="$BILLING_KEY" /></plugin>``` | 👍 |
| [cordova-plugin-purchase](https://github.com/RevenueCat/cordova-plugin-purchases/) | [click](https://docs.revenuecat.com/docs/getting-started-1#section-configure-purchases) | use `Purchases.setup()` | 👍 |
| [cordova-plugin-inapppurchase](https://github.com/AlexDisler/cordova-plugin-inapppurchase) (your choice) | [click](https://github.com/AlexDisler/cordova-plugin-inapppurchase/blob/master/README.md#android)  | Somehow put `manifest.json` to the `www` folder[*](https://github.com/AlexDisler/cordova-plugin-inapppurchase/blob/d0765bbabfd9aa5f7dffe9f0abefd07eeaf195dc/src/android/InAppBillingV3.java#L69) | 😒 |

**Comment by mpost** [comment]
Closing this issue as resolved for now. Please reopen if you have any more issues.
