### ISSUE TITLE
Cannot build Android App Bundle in cloud service, only apk

### ISSUE THREAD

**Issue by violuke** [eclipsesource/tabris-js#2009]
### Problem description
I cannot build an Android App Bundle in the cloud build service which is a requirement for all new apps to be submitted to the Google Play Store (`.apk` is not acceptable for new apps). This is a big problem for us and renders the paid-for service considerably less useful than expected.

### Expected behavior
An option in the project settings. Or maybe an environment variable that can be used.

### Environment
Tabris Pro cloud build service.

**Comment by mpost** [comment]
We will add such an option in the near future. Please stay tuned.

Fyi, there is no hard requirement at the moment to upload an app bundle. You can still upload an apk as usual.

**Comment by violuke** [comment]
Thanks @mpost this would be really helpful.

I agree that it looks like there's no hard requirement for an app bundle, however I'm unable to release an apk. I believe that this is because it's a brand new app which has never been released before. I think an apk is ok for new updates to older apps. I'm not able to get you a screenshot at the moment, but I will when I get a chance. Thanks.

**Comment by violuke** [comment]
Any update on when this might be ready? I'm happy to be a beta tester if required. Thanks

**Comment by mpost** [comment]
@violuke It is still on our roadmap and will be added. You can expect it in Q2 2020. Sorry that i can't give you a more concrete date.

**Comment by violuke** [comment]
@mpost is there an update on when this feature will be ready yet? Thank you.

**Comment by mpost** [comment]
@violuke It is still on our roadmap. Please hang on.

**Comment by ifurnadjiev** [comment]
Support for Android bundle packaging is now available for builds based on tabris.js 3.3+.
