### ISSUE TITLE
Add the ability to control gravity of TextView

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-js#2013]
Currently, it is not possible to control the vertical position of the text inside `TextView`. As far as I know, Android has this property called `gravity`. It would be quite useful to have this property in Tabris

**Comment by cookieguru** [comment]
Duplicate of #1887

**Comment by mpost** [comment]
Rightfully pointed out to be a duplicated. iOS currently does not support it which stops us from implementing it cross platform. An Android only option would be possible.
