### ISSUE TITLE
When uploading windows build; invalid package family name and publisher name

### ISSUE THREAD

**Issue by rdewinter-colijnit** [eclipsesource/tabris-js#2014]
## Problem description 

When uploading the .appxupload file (built by tabrisjs online build service) to the windows app store, i get the following messages:
![image](https://user-images.githubusercontent.com/13573902/76852637-0d68da00-684c-11ea-9b9f-f177c1e6d269.png)

### Expected behavior

The build to be succesfully uploaded to the windows app store.

### Environment

- Tabris.js version: 2.9
- Device: windows

### Code snippet

Config.xml:
```
    <preference name="EnableDeveloperConsole" value="false"/>
    <preference name="WindowsStoreIdentityName" value="ColijnIT.iOnesignature"/>
    <preference name="WindowsStorePublisherName" value="Colijn-IT"/>
```

**Comment by tbuschto** [comment]
Unfortunatly the build service can not create packages for upload because of signing issues. You have to make a local build: https://docs.tabris.com/2.9/windows-support.html#building-an-app-for-the-windows-store

**Comment by rdewinter-colijnit** [comment]
Yes i know that local build is possibly the only viable next solution, but i already spent a couple hours on that and failed because a bunch of assemblies were missing. Looks like i need a very specific build environment in order for local building to work.

Do you know by any chance a place where i can find this required build environment for tabris projects?

**Comment by tbuschto** [comment]
All you should need is [Visual Studio 2017](https://visualstudio.microsoft.com/vs/older-downloads/) and the Windows SDK (10.0.14393.0). You can pick that in the VS Installer
![grafik](https://user-images.githubusercontent.com/527303/77430410-71a31500-6ddb-11ea-9479-384692271f38.png) or get it [here](https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/)

**Comment by rdewinter-colijnit** [comment]
Thank you, 
it is still not working because i have a custom tabris package but i am now getting support for that so i'm sure this issue can be closed.
