### ISSUE TITLE
Tabris 3 / Init command failed

### ISSUE THREAD

**Issue by faustfizz** [eclipsesource/tabris-js#2019]
I Have a problem, i want to create a new tabris 3 project based but it always fail.
First time i used Node v13 with not success and i thought that it's the version of node and i changed Node to Node v12 and i realised that the error can be from the tabris-cli itself because i use angular-cli with no problem, ionic 5 too with no problem.

I uninstalled tabris and reinstalled it but it not works.

I use a Ubuntu based system ( Zorin OS 15 )
Node: v12.16.1
npm: 6.13.4
tabris-cli: 3.3.0

here is the console output :

**faustfizz_yous@Hacker-HP-Laptop-15-bs0xx:~/mobile-dev/tabris$** tabris init
? Tabris.js Version 3.x
? App name as it appears on the device's home screen:
 Tabris
? App ID org.example.tabris
? Type of project? Compiled
? Additional IDE configuration? (e.g. launch options) Visual Studio Code
? Example Code Tiny/TSX
? Configure unit tests? None
events.js:288
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'split' of undefined
    at module.exports._removePatch (/usr/local/lib/node_modules/tabris-cli/node_modules/generator-tabris-js/app/generator.js:258:36)
    at /usr/local/lib/node_modules/tabris-cli/node_modules/generator-tabris-js/app/generator.js:117:75
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Emitted 'error' event on  instance at:
    at Immediate.<anonymous> (/usr/local/lib/node_modules/tabris-cli/node_modules/yeoman-generator/lib/index.js:433:22)
    at processImmediate (internal/timers.js:456:21)

I need Help !
Thanks in advance !

**Comment by cookieguru** [comment]
I'm not able to reproduce on Ubuntu 18.04.4.  However the error indicates that the `npm view` command failed during generation of the project.  Does the command `npm view tabris@latest version` output `3.3.0` for you?  There could be a connectivity issue between your machine and the npm servers.

As a workaround, you can edit `/usr/local/lib/node_modules/tabris-cli/node_modules/generator-tabris-js/app/generator.js` and change line 116 to
```js
const tabris_install_version = '3.3.0';
```

**Comment by faustfizz** [comment]
Hi,
I solved the problem 5 seconds ago. The problem was due to the fact that I installed node using the snap manager.
I solved the problem by installing nodejs from the command line.

thank you so much @cookieguru
