### ISSUE TITLE
Support displaying a map view

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#202]
Support displaying a map view utilizing the native client's map interfaces.

**Comment by jkrause** [comment]
Implement the map using the provisional api for creating custom widgets.

**Comment by cpetrov** [comment]
[Feature specification draft](https://docs.google.com/document/d/1Nv8Ce4017WNyguGI_GuUf2wbb3lJBe5JBv1aU1ezs3E)

**Comment by cpetrov** [comment]
Things to consider for JS API for custom widgets:
  * How to name the internal type of the widget? Discuss naming convention. Problem: How to avoid naming conflicts with existing widget types and other third party widget types?
  * How to declare initial properties that should not be regular properties (only used with "create", no setter and getter)

**Comment by bFlood** [comment]
this cordova plugin is great for Google Maps (on Android and iOS). There are portions that would need to be changed, specifically it's code to manage the placement of the native view within the webview, but I think the majority of the code (layers, markers, map events, view animation etc) are all applicable to tabris-js. the original author of the plugin @wf9a5m75 did an amazing job on it

https://github.com/wf9a5m75/phonegap-googlemaps-plugin

**Comment by cpetrov** [comment]
Opened eclipsesource/tabris-maps#1 for iOS support. We will now use repository issues to track the project's progress.
