### ISSUE TITLE
Allow to open/pick a file on device

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#2026]
### Problem description

At the moment it is not possible to open a file on the device without the usage of cordova plugins. We should allow to pick a single file and a set of files.

### Code snippet

Example api:
```javascript
const imageBlobs = await tabris.app.open('image/*', {quantity: 'multiple'});
```

**Comment by fax1ty** [comment]
It would also be great to get access to the [ContentResolver API](https://developer.android.com/reference/android/content/ContentResolver) to be able to get data about images in the gallery directly, so that you can create galleries in the app without using outdated plugins

**Comment by mpost** [comment]
@fax1ty While that is an interesting proposal, the api is pretty complex to expose as part of this issue. We will focus on picking a file from the system ui first. Please open a new issue for your suggestions.

**Comment by fax1ty** [comment]
Related with https://github.com/eclipsesource/tabris-js/issues/1881

**Comment by mpost** [comment]
@fax1ty These are indeed related. But pose some technical differences on iOS. We will consider it though.

**Comment by mpost** [comment]
@fax1ty Btw this plugin allows to query a content resolver: https://github.com/r-cohen/cordova-ContentProviderPlugin

**Comment by mpost** [comment]
the new `fs.openFile()` api provides support for this issue.
