### ISSUE TITLE
Unexpected results when launching an app with custom scheme through `app.launch()`

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#2027]
### Problem description

Currently, when launching an app through `app.launch()`, the target app activity will open in the task of the app calling `app.launch()` and any existing tasks of the target will not be brought to the foreground.  Explicitly setting [`android:allowTaskReparenting="true"`](https://developer.android.com/guide/topics/manifest/activity-element) of the target app does not have any effect, although this does not seem needed when the app is being launched through the browser (see https://github.com/eclipsesource/tabris-js/issues/1915). It seems that there is a disparity in the mechanism to launch a Tabris.js app from the browser and by using the `app.launch()` API.

When using the native `startActivity()` with `Intent.FLAG_ACTIVITY_NEW_TASK` instead of Tabris.js' `app.launch()` API, the activity will be launched in a new task/existing tasks will be brought to the foreground and their activities' `onNewIntent` will be called, similarly to the behavior of following a link in the browser:

[1]
```
    val intent = Intent(Intent.ACTION_VIEW)
    intent.data = Uri.parse(url)
    intent.flags = Intent.FLAG_ACTIVITY_NEW_TASK
    startActivity(scope.context, intent, null);
```

### Expected behavior

`app.launch()` should behave as closely as possible to the browser when handling custom schemes of Android apps:
* the activity is opened in a new task instead of the calling task.
* if a task exists with the target activity already, its activity is brought to the foreground and the `onNewIntent` method of the activity is called.
This is conceptually analogous to the behavior on iOS as well.

Does it make sense to generally use [1] for custom schemes? How does it differ from the current method implemented by `app.launch()`?

### Environment

- Tabris.js version: 3.4
- OS: Android

**Comment by mpost** [comment]
The behavior could indeed be improved. Using the the `FLAG_ACTIVITY_NEW_TASK` is more in line with the expected behavior of "going to a different app" to view the content. We will updated accordingly.

**Comment by cpetrov** [comment]
Configuring `launchMode` to `singleTask` may also be a viable alternative:

```xml
  <preference name="AndroidLaunchMode" value="singleTask"/>
```

**Comment by mpost** [comment]
We will close this issue for now and open a new one with a feature request to make the launch behavior configurable. Either launch in the same task stack or into a new one.
