### ISSUE TITLE
Android: Build fails if Projectname starting with a nunber

### ISSUE THREAD

**Issue by samynomad** [eclipsesource/tabris-js#2030]
### Problem description

The cordova-android checks Project names and throw a validation exception if the name of the project starts with a number. 
This causes the Tabris build to fail. 
However, Android and the Play Store do not have restrictions that prohibit such names. 

see https://github.com/apache/cordova-android/issues/701

### Expected behavior

The build should work, even if the projectname starts with a number.

### Environment

- Tabris.js version: 3.4
- OS: Android 7.1

**Comment by samynomad** [comment]
Problem is fixed in the cordova-android project, but not released yet: 

https://github.com/apache/cordova-android/pull/859

**Comment by mpost** [comment]
We could cherry pick this commit and release with with the next Tabris.js version if the cordova-android platform does not create a stable release until than.

**Comment by mpost** [comment]
The [relevant changes](https://github.com/apache/cordova-android/pull/859/commits/adcd59ea242bc9c9f1e42492f655e0d902e21381) have been merged into the android platform.
