### ISSUE TITLE
Child TextView disappears

### ISSUE THREAD

**Issue by elshadsm** [eclipsesource/tabris-js#2035]
### Problem description

When we create a TextView, attach it to composite, and set margins, the TextView is not rendered. The issue occurs starting from Tabris.js 3.x version.

![actual](https://user-images.githubusercontent.com/13982125/80124986-1a42c100-85a2-11ea-82b6-631798739b9f.jpg)

### Expected behavior

The TextView should be rendered as expected.

![expected](https://user-images.githubusercontent.com/13982125/80125025-2464bf80-85a2-11ea-8c13-bef40046b0a3.jpg)

### Environment

- Tabris.js version: 3.4.0-dev.20200423
- Device: Samsung  A70
- OS: Android 10

### Code snippet

```javascript
import { contentView, Composite, TextView } from 'tabris';

contentView.append(
    <Composite
        left={16} top={16} right={16}
        background='yellow'>
        <TextView
            left={16} top={16} right={16} bottom={16}
            text='Foo bar bloo'
            textColor='blue' />
    </Composite>
);
```

**Comment by mpost** [comment]
This is a long standing issue on Android. It is best to use `padding` in this case.
