### ISSUE TITLE
Modifying the widget tree in some ways leads to an unexpected layout

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#2036]
### Problem description

Modifying the widget tree in a certain way (snippet 1) to achieve the constellation from snippet 2 results into the red composite from the snippet disappearing. 

Creating the same constellation at once works as expected (snippet 2).

### Environment

- Tabris.js version: 3.4
- OS: Android 9

### Code snippet
Snippet 1:
```javascript
import {contentView, Composite} from 'tabris';

contentView.append(
  <Composite left={0} top={0} right='next()' bottom={0} background='red' />
)

setTimeout(() => {
  contentView.append(
    <Composite right={0} top={0} bottom={0} width={30} background='blue' />
  );
}, 2000)
```

Snippet 2:
```javascript
import {contentView, Composite} from 'tabris';

contentView.append(
  <$>
    <Composite left={0} top={0} right='next()' bottom={0} background='red' />
    <Composite right={0} top={0} bottom={0} width={30} background='blue' />
  </$>
)

```

**Comment by mpost** [comment]
Substituting the `right='next()'` with `right={0}`. Produces the expected result. We will look into it.

**Comment by cpetrov** [comment]
> Substituting the `right='next()'` with `right={0}`. Produces the expected result. We will look into it.

However, this substitution isn't a valid workaround, because the resulting layout would not be equivalent.
