### ISSUE TITLE
Add ability to run native code

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-js#2039]
(question/feature request)

Is it possible to run platform dependent code with JS? 
A lot of things haven't been implemented yet. Sometimes you need to access a specific method or XML (Android) property. It would be very convenient if each widget had access to the native one.

`Widget.view.anyValueOrMethod`
`app.runNative('Java / Objective-C code here')`

**Comment by cookieguru** [comment]
http://docs.tabris.com/latest/custom-widgets.html

**Comment by fax1ty** [comment]
@cookieguru This is not a question of writing your own plugin, but of getting native data directly into JS

**Comment by cookieguru** [comment]
That is the method for getting native data into JS.  You can't dynamically run native code at runtime as it needs to be compiled with the app; unlike JS it cannot be interpreted

**Comment by fax1ty** [comment]
At least we have reflections in both languages. We can get or set properties on the fly

**Comment by mpost** [comment]
@fax1ty The amount of values you would be able to set via reflections is surprisingly small. Eg when you want to set a color on Android you would want to set a native `ColorStateList` which would not be able to create from the js side. Therefore these kind of reflection approaches have limited use.

**Comment by fax1ty** [comment]
@mpost Ok. You can close it or leave it if it's even a little interesting

**Comment by mpost** [comment]
I will close this for now. Thanks for bringing it up though.
