### ISSUE TITLE
impossible to hide the status bar

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#2041]
### Problem description
Impossible to hide the statusBar

### Expected behavior
statusBar can be hidden

### Environment

- Tabris.js version: 3.4.0
- Device: Huawei P10 lite
- OS: Android 8

### Code snippet

```javascript
const{statusBar} = require("tabris");
statusBar.displayMode = "hide";
```

**Comment by fax1ty** [comment]
Can confirm on Android 8.1 - Xiaomi Redmi 5 Plus

![image](https://user-images.githubusercontent.com/26363214/80234796-cc918b80-8669-11ea-9cdb-64054c3057ec.png)

```ts
import { statusBar } from 'tabris';

statusBar.theme = 'light';
statusBar.displayMode = 'hide';
```

**Comment by mpost** [comment]
It works in the dev client but in a self build app the `'hide'` value has the effect of `'float'`.

**Comment by ishigo1987** [comment]
And what should we do? Because on version 3.3.0 for example it works perfectly.

**Comment by mpost** [comment]
That is true. We will the regression in the next release.

**Comment by mpost** [comment]
@ishigo1987 One insight... If you need to have it working right now, you can define your own theme. This will fix this issue atm.

**Comment by ishigo1987** [comment]
I already use a custom theme and it doesn't work, I came back to version 3.3.0 for this reason and also because the 3.4.0 debugger is quite annoying, visibly (UI) unstable with the url suggestion bar that pops up at every moment causing the keyboard to exit.

**Comment by mpost** [comment]
The issue has been fixed in the latest `nightly` build (available tomorrow).

With the changes in [Tabris.js 3.4](https://tabris.com/tabris-js-3-4-released/) the Android client now directly displays its ui inside the `CordovaActivity` whereas previously it included its own Activity. Thereby any unexpected behavior performed inside the `CordovaActivity` needs to be patched to fit out use-case.

**Comment by ishigo1987** [comment]
Ok I understand thank you, could I please know what motivated your choice to move from one activity to a fragment? Does this change lead to a performance boost?

**Comment by mpost** [comment]
It speeds up the launch time but more importantly it allows to embed tabris into existing apps. In addition it makes it easier to call other apps and to receive results from other apps.
