### ISSUE TITLE
Tabris Application is unable to upload to app store connect

### ISSUE THREAD

**Issue by Joshua-Beatty** [eclipsesource/tabris-js#2043]
### Problem description

A very simple app, requiring no plugins or permissions is denied by Apple to be uploaded by the following reasons
<pre><cocde>
<b> ITMS-90683: Missing Purpose String in Info.plist</b> - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a <b>NSCameraUsageDescription </b>key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

Though you are not required to fix the following issues, we wanted to make you aware of them:

<b>ITMS-90683: Missing Purpose String in Info.plist</b> - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a <b>NSLocationWhenInUseUsageDescription </b>key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

<b>ITMS-90809: Deprecated API Usage</b> - Apple will no longer accept submissions of new apps that use UIWebView as of April 30, 2020 and app updates that use UIWebView as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview). 
</code></pre>

### Expected behavior

I would expect an app using no plugins or permissions to not require an info string for Location services or for camera usage.

### Environment

- Tabris.js version: 3.4.1
- Device: N/A
- OS: Ios

### To reproduce
Fork the [Tabris.js Example App](https://github.com/eclipsesource/tabris-js-hello-world)
Modify the config.xml to [match the bundle id and version of an app you've registered on app store connnect](https://github.com/Joshua-Beatty/tabris-js-hello-world/commit/9121638fa4012d663fc38d9964e5c1f2b8300680)
Build the application using the online build service
Downloaded the .ipa and upload to transporter
Wait for the build to denied and to receive an email detailing the issues

**Comment by karolszafranski** [comment]
Hi @Joshua-Beatty, thanks for reporting. I confirm that the issue exists. I'm looking into it and let you know when it will be fixed.

**Comment by karolszafranski** [comment]
@Joshua-Beatty since today's nightly (`3.5.0-dev.20200429`) it will not be required to provide the usage description strings.

If you want to keep using 3.4.0 or older version of Tabris.js please add dummy descriptions to iOS platform section of your config.xml like this:
```
<?xml version='1.0' encoding='utf-8'?>
<widget
    id="com.eclipsesource.tabrisjs"
    version="$VERSION"
    xmlns="http://www.w3.org/ns/widgets"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android-packageName="com.eclipsesource.tabris.js"
    ios-CFBundleIdentifier="com.eclipsesource.tabrisjs">

  <name>Tabris.js</name>
  <description>The developer app for Tabris.js</description>

  <platform name="ios">

    <edit-config file="*-Info.plist" target="NSCameraUsageDescription" mode="overwrite">
      <string>Use the camera to scan qr-codes of Tabris.js applications.</string>
    </edit-config>

    <edit-config file="*-Info.plist" target="NSLocationWhenInUseUsageDescription" mode="overwrite">
      <string>Use the user location to visualise it on the map.</string>
    </edit-config>

    <edit-config file="*-Info.plist" target="NSPhotoLibraryAddUsageDescription" mode="overwrite">
      <string>This allows to demonstrate sharing to the photo gallery.</string>
    </edit-config>

  </platform>

</widget>
```
