### ISSUE TITLE
Text with markupEnabled not correctly spaced in JSX TextView

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#2044]
### Problem description

A `TextView` with `markupEnabled`  and a text inside the element does not add correct space when line break is just before a hyperlink `<a>`. Instead the link is directly attached to the leading word. When a regular word is before the link, it works as expected with a space added. See the snippet below for details.

### Expected behavior

Add a space when a line break occurred in a JSX text element.

### Environment

- Tabris.js version: 3.4
- Device: Android emulator, IPhone 6

### Code snippet

Not working:

```jsx
        <TextView left={0} right={0} markupEnabled>
            Text with link
                <a href='https://docs.tabris.com/latest/cordova.html'>www.tabris.com</a>.
        </TextView>
```

Working as expected:

```jsx
        <TextView left={0} right={0} markupEnabled>
          Text with
                link <a href='https://docs.tabris.com/latest/cordova.html'>www.tabris.com</a>.
        </TextView>
```

**Comment by tbuschto** [comment]
This is a known JSX quirk, nothing we can do about it.

https://stackoverflow.com/questions/32686728/how-to-avoid-jsx-component-from-condensing-when-react-js-rendering-it
