### ISSUE TITLE
Release App size too large after online build

### ISSUE THREAD

**Issue by mavyfaby** [eclipsesource/tabris-js#2050]
I want to test how much size it would take on online build, an empty app release alone is 31MB. How to reduce the app file size?

**Comment by fax1ty** [comment]
Only solution is not to use Tabris. I think you need true native code

**Comment by mavyfaby** [comment]
Okay

**Comment by cookieguru** [comment]
Using app bundles is the recommended way: https://developer.android.com/platform/technology/app-bundle

Note that adding your own JavaScript code is not likely to increase the build size much; as it is just plain text it will zip quite nicely.  The majority of the size comes from the JS interpreter--(J2V8)[https://github.com/eclipsesource/j2v8] is bundled as it is significantly faster than the built-in Android VM.

I agree with @fax1ty, achieving that level of compression is not likely with any cross-platform solution

**Comment by mpost** [comment]
App bundles are the right way to go. it will half your apk size.

```
tabris build android --release -- --packageType=bundle
```

**Comment by mavyfaby** [comment]
> App bundles are the right way to go. it will half your apk size.
> 
> ```
> tabris build android --release -- --packageType=bundle
> ```

This what I'm looking for. Thank you😊
