### ISSUE TITLE
More options for display an image

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#2056]
It would be a good idea i guess to allow a TextView widget to display a little image(like emoji) via a key, value or via a markupEnabled: true and <img /> html tags
It would allow for example to use emojis made of images and be able to display them in a textview.

**Comment by mpost** [comment]
For regular emojis you can use them directly by copying the corresponding glyph into your text. Eg from this table: https://apps.timwhitlock.info/emoji/tables/unicode.

At the moment it is not possible to inlude the unicode sequence itself in the `TextView`.

**Comment by ishigo1987** [comment]
Ok copy

**Comment by mpost** [comment]
You can actually use a string representation as well. eg `'\u{1F43B}'` will give you 🐻.
