### ISSUE TITLE
ImageView not loading relative path image

### ISSUE THREAD

**Issue by josiahking** [eclipsesource/tabris-js#2059]
### Problem description
ImageView not working as expected

### Expected behavior
Load image as described from relative path of package.json

### Environment

- Tabris.js version: 3.4
- Device: Samsung Galaxy / debug build
- OS: Android 6.0

### Code snippet

```javascript
new ImageView({
	image:{
		//src:'src/img/no-network-icon.png',
		src: "no-network-icon.png",
		width: 200,
		height: 200
	}, 
	scaleMode:'fit', 
	width:200, 
	height:200, 
	centerY:0
}))
```

Console log: Could not process 'create' with {image={type="uri",src="src/img/no-network-icon.png",width=null,height=null, scale=null},scaleMode="auto"} for type 'tabris.ImageView' ('$18')

**Comment by mpost** [comment]
When formatting the snippet correctly it works as expected: 

```js
import {ImageView} from 'tabris';

new ImageView({
  image: {
    src: 'no-network-icon.png',
    width: 200,
    height: 200
  },
  scaleMode: 'fit',
  width: 200,
  height: 200,
  centerY: 0
});
```

Make sure that your image path is relative to the `package.json`.

**Comment by josiahking** [comment]
My image is inside the src/img directory.
`src:'src/img/no-network-icon.png',`

Its working now, I wonder why it refused to show before.
Although, i later changed it to use base64, but after this test its showing.
