### ISSUE TITLE
Support resize options of createImageBitmap()

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#2063]
### Problem description

Services often need to impose restrictions on the size and dimensions of images. Cordova plugins like [`cordova-plugin-camera`](https://github.com/apache/cordova-plugin-camera#module_camera.CameraOptions) and [`cordova-image-picker`](https://github.com/wymsee/cordova-imagePicker#options) provide options to resize and compress images.

Provide a generic way to do this for various usage scenarios by supporting the `resizeWidth`, `resizeHeight` and `resizeQuality` options of the [`createImageBitmap()`  API](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/createImageBitmap).

### Environment

- Tabris.js version: 3.5.0

**Comment by mpost** [comment]
Implemented for 3.6
