### ISSUE TITLE
Problem with documentation

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#2065]
The app.share documentation is incomplete and not very understandable, without sample code on how to share a file.
https://docs.tabris.com/latest/api/app.html#object-app
TabrisJs 3.5

**Comment by cookieguru** [comment]
![image](https://user-images.githubusercontent.com/1888809/82476635-393e5100-9a83-11ea-8a5f-d3793985d5bc.png)

**Comment by ishigo1987** [comment]
Ok thank you for your help
