### ISSUE TITLE
Bug with Keyboard appearing when TextInput have no Focus

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#2066]
### Problem description

The problem is a bit special : reproducing it is not always easy, basically in some situations if a TextInput receives a focus, and then loses focus and is removed from the ui 
 a keyboard out of nowhere appears whenever the application switches from background to foreground while the TextInput has been laid out.
I show you on the image

### Expected behavior

A keyboard should not appear when the application comes back to the foreground when the TextInput does not exist anymore

### Environment

- Tabris.js version: 3.3.0, 3.4.0, 3.5.0
- Device: Huawei P10 lite, Archos 7s, Honor 7s Dual22
- OS: Android 7,8,8.1
![Hnet-image (2)](https://user-images.githubusercontent.com/12398336/82555578-ec7c7800-9b5f-11ea-9ed8-7aa6588c4e22.gif)

**Comment by mpost** [comment]
Could you provide a snippet to reproduce the behavior?

**Comment by ishigo1987** [comment]
```JAVASCRIPT
const{Composite, TextInput, TextView, contentView} = require("tabris")
    const headerComposite = new Composite({ top: 0, left: 0, right: 0, height: 57}).appendTo(contentView);
    const headerViewTitle = new TextView({ centerY: 0, left: ['prev()', 5], right: 30, textColor: "gray", text: "Test", font: 'bold 17px' }).appendTo(headerComposite);
    const searchCountry = new TextView({ centerY: 0, right: 15, textColor:"gray", text:"create input"})
    .onTap(({ target }) => {
        target.dispose()
        new TextInput({ width:200, centerY: 0, right: 5, message: "This is a test", style: 'none', floatMessage: false,  background: 'transparent', focused: true}).appendTo(headerComposite);
    }).appendTo(headerComposite);
```

First you'll notice that even though the textInput has the property focused: true, the keyboard doesn't come out, copy my snippet and do the following experiment,
click on create input then click on the input then click somewhere else so that the input loses focus, then put the application in the background and go back to it, you will see a keyboard appear each time

**Comment by ishigo1987** [comment]
Even if after you dispose all the widgets in and then redo Background -> Foreground you will see the keyboard come out
you can this at the end of my snippet for the test
```JAVASCRIPT
 setTimeout(()=>{
        headerComposite.dispose();
    },15000);
```

**Comment by mpost** [comment]
Please provide a self contained snippet that can be run directly without any required alterations.

**Comment by ishigo1987** [comment]
@mpost  my snippet is not enough?

**Comment by cookieguru** [comment]
@ishigo1987 As @mpost has mentioned several times the snippet needs to be *self contained*--it runs without dependencies or modifications, and ideally without unnecessary elements (e.g. don't add a button if the issue can be replicated without one).  If your snippet can't be pasted in [the scratchpad](http://scratchpad.tabrisjs.com/) and then run it isn't self-contained

**Comment by mpost** [comment]
While cookie is fully correct, in this case the snippet is running on its own. Although a modern code should use import rather than required.

**Comment by ishigo1987** [comment]
@cookieguru  For the bug to be replicable the textinput must be dynamically created, that's why I put a button.
@mpost  did you see what bug I'm talking about?
I still use the require because I'm old-fashioned.
and  I don't think that the current version of j2v8 already supports dynamic imports, since this is not the case, last time i check  I use require which supports dynamic imports

**Comment by cookieguru** [comment]
@ishigo1987 I understand, it was just an example.  This can also be a reference for anyone else; the point is not to paste your entire app :)

**Comment by ishigo1987** [comment]
yes you're right

**Comment by ishigo1987** [comment]
@mpost  any news?

**Comment by mpost** [comment]
@ishigo1987 We are still looking into it.

**Comment by ishigo1987** [comment]
Thank you @mpost

**Comment by elshadsm** [comment]
@ishigo1987 I have tested your [snippet](https://github.com/eclipsesource/tabris-js/issues/2066#issuecomment-632612973). 
First:

`First you'll notice that even though the textInput has the property focused: true, the keyboard doesn't come out, copy my snippet and do the following experiment,`

You can use the `setTimeout(() => input.focused = true);` after creation of `TextInput` in order to gain focus when the widget is created.

```TypeScript
const input = new TextInput({
        width: 200, centerY: 0, right: 5,
        message: "This is a test",
        style: 'none',
        floatMessage: false,
        background: 'transparent',
        focused: true
    }).appendTo(headerComposite);
    setTimeout(() => input.focused = true);
```

Second:

`click on create input then click on the input then click somewhere else so that the input loses focus, then put the application in the background and go back to it, you will see a keyboard appear each time`

I **couldn't reproduce** the issue with the relevant versions below:

```
Tabris.js: 3.5.0
Tabris Developer App: 3.5.0-20200527-0541
OS: Android 10
Device: Samsung A70, Android Emulator Pixel 3a XL
```
**Maybe you should try the latest Tabris Developer App?**

**Comment by ishigo1987** [comment]
@elshadsm elsha I didn't test it in the development application but directly in my test application (empty of any plugins) compiled in debug mode. If you have an already compiled application other than the development application I think you'll see the problem in question.
Tabris.js 3.3, 3.4, 3.5
Os: Android 7, 8
Device: Huawei P 10 lite, Honor 7s Dual Sim

Thank you for your snippert about the input focus

**Comment by elshadsm** [comment]
@ishigo1987  I have built an application based on your snippet (in local) and was unable to reproduce the problem. Maybe you can try rebuilding `your test application` and testing again?

P.S.

You should use the latest [platform ](https://tabrisjs.com/download/) versions...

**Comment by elshadsm** [comment]
I would suggest building the app in your local machine following these [instructions](https://docs.tabris.com/latest/build.html#local-build) and using these [tabris.js Android 3.5.0 / tabris.js iOS 3.5.0](https://tabrisjs.com/download/) platforms.

**Comment by ishigo1987** [comment]
yes i use the latest platform version and i try it on two devices with multiples rebuilds

@mpost were you able to reproduce the problem successfully?

**Comment by ishigo1987** [comment]
OK i will try your solution despite the fact that i never make a local build since i use tabris

**Comment by ishigo1987** [comment]
do you really think that the problem could be related to the way i build it? it would be amazing. A keyboard that comes out unexpectedly because of the way i compile the application.

Maybe @elshadsm  the problem is not related to the build but the android version lower than 10 or 9

**Comment by cookieguru** [comment]
It could also be the keyboard you're using

**Comment by cookieguru** [comment]
@ishigo1987 Was it the same keyboard on each device?  Can you reproduce your issue on the emulator?

**Comment by elshadsm** [comment]
> do you really think that the problem could be related to the way i build it? it would be amazing. A keyboard that comes out unexpectedly because of the way i compile the application.
> 
> Maybe @elshadsm the problem is not related to the build but the android version lower than 10 or 9

@ishigo1987 I just tested your snippet in the emulator in Android 8.1 and **was able to reproduce the problem**. It seems that the problem occurs in versions of Android that are lower than 10. We will figure out.

**Comment by ishigo1987** [comment]
Yes I was sure, fortunately some people like me still use old versions of android, to check the regressions.
Thank You @elshadsm

**Comment by elshadsm** [comment]
@ishigo1987 The issue has been solved.

**Comment by ishigo1987** [comment]
Thank you @elshadsm maybe this one 
https://github.com/eclipsesource/tabris-js/issues/2061 
is related to the same problem(only visible to lower version on Android)

**Comment by elshadsm** [comment]
You can build your app against the nightly Tabris Android platform in order to see the expected results.

**Comment by ishigo1987** [comment]
OK thank you, i will do that tomorrow, and i will let you know

**Comment by ishigo1987** [comment]
@elshadsm  the nightly Tabris is not available for the online build and i don't have the requirements for a local build inside my laptop, so I'll be waiting for the official 3.6 release

**Comment by cookieguru** [comment]
@ishigo1987 Nighly builds are indeed available in the online build service, you just need to update the dependency in your `package.json` to one of the [available versions](https://www.npmjs.com/package/tabris?activeTab=versions)

**Comment by ishigo1987** [comment]
Ok thank you @cookieguru

**Comment by ishigo1987** [comment]
@elshadsm  At the moment doing an online build with version 3.6.0-dev.20200607 doesn't work, the build fails,
I'll try again later.

```
>> 0 paths cleaned.
Running "copy:app" (copy) task
Created 18 directories, copied 303 files
Running "shell:fix_executable_bit" (shell) task
find: `cordova/scripts': No such file or directory
Running "writefile:tabrisBuildConfig" (writefile) task
1 file written.
Running "print_tabris_build_config_json" task
{
  "ios": {
    "debug": {
      "developmentTeam": "",
      "provisioningProfile": "",
      "codeSignIdentity": "",
      "packageType": "development"
    }
  },
  "android": {
    "debug": {
      "keystore": "signing/android.keystore",
      "storePassword": "[secure]",
      "alias": "[secure]",
      "password" : "[secure]"
    }
  }
}
Running "shell:npm_prepare" (shell) task
Running "shell:npm_install" (shell) task
added 224 packages from 131 contributors and audited 224 packages in 4.978s
12 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
Running "tabris_cli_build" task
Running "shell:tabris_cli_android_build" (shell) task
[./] npm run --if-present build:android
[./] npm run --if-present build
[./] Copying Cordova files to build/cordova ...
[./] Copying JavaScript files to build/cordova/www/app ...
[build/cordova/www/app] npm install --production
npm notice created a lockfile as package-lock.json. You should commit this file.
added 127 packages from 81 contributors and audited 221 packages in 4.199s
8 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
[./] Replacing variables in config.xml...
[./] Downloading android platform version 3.6.0-dev.20200608...
Unable to download platform: Unexpected status code 404
```

**Comment by mpost** [comment]
Please try again in 10 minutes

**Comment by ishigo1987** [comment]
@mpost It's still not working.

**Comment by mpost** [comment]
sorry please try again. the nightly is now correctly available.

**Comment by ishigo1987** [comment]
@mpost it works
@elshadsm the issue is indeed fixed 
Thank you both of you
