### ISSUE TITLE
TabFolder with stretch producing squished bottom tab bar

### ISSUE THREAD

**Issue by anselm0** [eclipsesource/tabris-js#2067]
### Problem description

Using the TabFolder widget with the layout "stretch" and tabBarLocation='bottom' produces unwanted squished effect for tab bar images and title elements.  Images used were same size, even used the same image across all the tabs to test.  Seems to be an issue with layout properties "top" and "bottom" when both set to 0.

```<TabFolder stretch tabBarLocation='bottom' >```

![Screen Shot 2020-05-20 at 6 27 21 PM](https://user-images.githubusercontent.com/25418234/82734278-a2ba9b80-9cdf-11ea-8c0a-2973f9605205.png)

Current work around is to define the top property and a height calculation which produces the tab bar correctly but positioning may vary with device.

```<TabFolder stretchX top={0} height={DEVICE_HEIGHT-(DEVICE_HEIGHT*.05)} tabBarLocation='bottom' selectedTabTintColor={[169, 52, 58]}>```

### Expected behavior

Bottom tab bar should render correctly without squishing the title and image elements when using layout of "stretch".

### Environment

- Tabris.js version: 3.5.0
- Device: iPhone Xs
- OS: iOS 13.4.1

### Code snippet
```contentView.append(
    <TabFolder stretch tabBarLocation='bottom' >
      <Tab title='Home' image='resources/home-page-tab-50.png' selectedImage='resources/home-page-tab-filled-50.png'>
      </Tab>
      <Tab title='News' image='resources/news-tab-50.png' selectedImage='resources/news-tab-filled-50.png'>
      </Tab>
      <Tab title='Calendar' image='resources/calendar-tab-50.png' selectedImage='resources/calendar-tab-filled-50.png'>
      </Tab>
      <Tab id='notificationsTab' title='Notifications' image='resources/push-notifications-tab-50.png' selectedImage='resources/push-notifications-tab-filled-50.png' badge={0}>
      </Tab>
    </TabFolder>
```

**Comment by patrykmol** [comment]
Hello @anselm0. I haven't been able to reproduce your issue. Could you provide a standalone snippet reproducing this issue? You can use images located in `snippets/resources` for this snippet. Thanks.

**Comment by cpetrov** [comment]
Might have to do with the layout used on devices without a home button, @patrykmol see related eclipsesource/tabris-js/issues/2081

**Comment by karolszafranski** [comment]
Issue was fixed today. Change will be visible in tomorrows nightly.
