### ISSUE TITLE
Add support to view PDFs

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#2070]
### Problem description

At the moment it is not possible to display a PDF in a tabris app.

### Expected behavior

Allow to view a PDF in a tabris app.

### Environment

- Tabris.js version: 3.6

### Code snippet

Suggested API

```javascript
contentView.append(
  <PdfView stretch
    background='#cccccc'
    padding={[24, 16]}
    spacing={16}
    zoomEnabled
    pageElevation={4}
    pageBackground={[255, 255, 255, 255]}/>);

(async () => {
  const response = await fetch('resources/example.pdf');
  $(PdfView).only().open(await response.arrayBuffer());
})().catch(e => console.error(e));
```

**Comment by ishigo1987** [comment]
It would be a good thing thanks a lot, but I think it will have the same problem I had with file sharing added on Tabrisjs 3.5.
Fetch is not able to retrieve data from the filesystem, for example I tried to retrieve a resource with this path file:///storage/emulated/0/
It didn't work at all.

**Comment by mpost** [comment]
@ishigo1987 This problem would be independet of the provided snippet. it takes an `ArrayBuffer` in this case. We also plan to allow to have an`open(uri)`. Which should be able to fetch local files.

**Comment by ishigo1987** [comment]
Thank you @mpost

**Comment by mpost** [comment]
Viewing PDFs is now possible with the new `PdfView`.
