### ISSUE TITLE
Action with low priority Placement

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#2072]
Hello , is it possible to add a way to have an action with low priority placement  on Composite widget, not only on NavigationView?
Thank you

**Comment by cookieguru** [comment]
It is specific to the NavigationView.  For Composite you should use an ImageView

The Slack channel is better suited for general questions rather than an issue tracker

**Comment by ishigo1987** [comment]
Maybe I misspoke.
Placing a low priority on a navigationView allows to have a kind of drop-down menu, but it only works on navigationView, my request is to allow this  same action that creates a drop-down menu on a composite.

**Comment by ishigo1987** [comment]
it's not a question but a request to add functionality, if possible.

**Comment by mpost** [comment]
What is requested is covered in https://github.com/eclipsesource/tabris-js/issues/1889

Closing this issue for now.
