### ISSUE TITLE
set navigationBar theme and statusBar theme not working anymore

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#2076]
Change the navigationBar or statusBar theme no longer works

```js
const{statusBar, navigationBar, Button, contentView} = require("tabris");
 statusBar.theme = 'light';
 navigationBar.theme = "light";

 new Button({centerY:0, centerX:0, text:"click me", background:"blue"})
 .onTap(()=>{
    statusBar.theme = "dark";
    navigationBar.theme = "dark";
 }).appendTo(contentView);
```

- Tabris.js version: 3.5
- Device: Huawei P10 lite
- OS: Android 8

**Comment by mpost** [comment]
There is indeed a problem in 3.5 when setting navbar and statusbar theme together. try setting only  one and the other one in a setTimeout with 0 ms.

**Comment by ishigo1987** [comment]
your trick doesn't work, but it's not a problem, when my app will be in production, the 3.6 will be already out

**Comment by elshadsm** [comment]
@ishigo1987 the issue has been solved.

**Comment by ishigo1987** [comment]
ok  thank you i test and i will let you know

**Comment by elshadsm** [comment]
You can build a new client now against the nightly Tabris.js version in order to test the issue.

**Comment by ishigo1987** [comment]
ok i will do that this night and i will let you know

**Comment by ishigo1987** [comment]
It works, thank you
