### ISSUE TITLE
fs.writeFile and fs.appendFile are working same way

### ISSUE THREAD

**Issue by acefxlabs** [eclipsesource/tabris-js#2077]
`fs.writeFile` and `fs.appendFile` are both appending files.
Let say I write a file using 
`fs.writeFile(fs.cacheDir+"/test/file.txt", '{key : "hello"}', 'utf-8')`
 and afterwards  i wrote to same file to 
`fs.writeFile(fs.cacheDir+"/test/file.txt", '{key : "goodbye"}', 'utf-8')`, 
i end up with a same file having 
**`{key : "hello"}{key : "goodbye"}`** 
as the new content

**Comment by cookieguru** [comment]
I can reproduce with the 3.5 developer app on Android 9 with the following snippet:
```js
import {fs} from 'tabris';

const FILE = fs.cacheDir + '/test.txt';

(async () => {
  await fs.writeFile(FILE, 'ab', 'utf-8');
  await fs.writeFile(FILE, 'cd', 'utf-8');
  await fs.readFile(FILE, 'utf-8').then((text) => console.log(text)); // expected: "cd"
})();
```

**Comment by mpost** [comment]
We can confirm the issue. Thanks for the self contained snippet @cookieguru. We will fix it immediately.

**Comment by mpost** [comment]
The issue has been fixed.
