### ISSUE TITLE
Camera captureImage() memory leak

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#2080]
### Problem description

When capturing images in a loop, memory consumption grows continuously in a linear fashion until the app is killed by the OS. It takes several minutes for the app to be killed.

![Screenshot 2020-06-17 at 18 14 19](https://user-images.githubusercontent.com/2341769/84923220-3ad15800-b0c7-11ea-9e24-22ae85474326.png)

### Expected behavior

Memory required for `captureImage()` should be released after the capture.

### Environment

- Tabris.js version: 3.6.0-dev.20200610
- Device: A1893
- OS: 12.4.1

### Code snippet

```js
import { device } from "tabris";

(async () => {
  device.cameras[0].active = true;
  while (true) {
    await device.cameras[0].captureImage();
  }
})();

```

**Comment by patrykmol** [comment]
This is no longer reproducible. Memory stays at 62-64MB used with occasional spikes to 120-140MB. Closing.

![Screenshot 2021-04-15 at 09 58 37](https://user-images.githubusercontent.com/12428999/114835147-8f219300-9dd1-11eb-8501-6df9f63ee1d6.png)
