### ISSUE TITLE
Tab Layoutproblem on iPhones (without home button)

### ISSUE THREAD

**Issue by samynomad** [eclipsesource/tabris-js#2081]
### Problem description

Setup: Main page has one widget: TabFolder with 'strech' layoutdata.
On iOS devices without a home button (i.E. iPhone 11), the layout of Tab eleemts is 'squashed':

![grafik](https://user-images.githubusercontent.com/1726398/85220262-5c259300-b3aa-11ea-9779-3067c8001b21.png)

### Expected behavior

On older iOS devices with Home Button, the example looks like that:

![grafik](https://user-images.githubusercontent.com/1726398/85220309-c3434780-b3aa-11ea-9824-2207f10b6fce.png)

### Environment

- Tabris.js version: 3.5
- Device: iPhone 11
- OS: iOS 13.51

### Code snippet

https://playground.tabris.com/?gitref=v3.5.0&snippet=tabfolder.jsx

**Comment by samynomad** [comment]
Same problem - screenshot from a customer project: 

![grafik](https://user-images.githubusercontent.com/1726398/85220468-f1755700-b3ab-11ea-9a5e-0ecfcb01297e.png)

Note: 
in this app, the initial layout is korrekt. If the user clicks on a textInput field, the layout is brocken after the focus of the TextInput is lost - the keyboard disappears and the layout is recalculated.

**Comment by cookieguru** [comment]
Looks like #2067

**Comment by samynomad** [comment]
@cookieguru  well spotted - thank you 
I will check with the Tabris team tomorrow if we should then close this as duplciate :)

**Comment by karolszafranski** [comment]
Issue was fixed today. Change will be visible in tomorrows nightly.
