### ISSUE TITLE
Q: Selector in onTab Event - WidgetCollection always empty - Not working?

### ISSUE THREAD

**Issue by nea** [eclipsesource/tabris-js#2082]
# Question

Hi there

I am currently experimenting with Tabris 3.5 in TypeScript and am currently trying the selector functionality, but it does not work as I would expect it and I do not find a lot of documentation which may point in the right direction. I hope you can help.

I have component class with a constructor such as
```
constructor(properties: Properties<XYZ>) {
    super();
    this.set(properties).append(
      <$>
        <ScrollView stretch layout={new StackLayout({ spacing: 16, alignment: 'stretchX' })} padding={16}>
          <TextInput id="email" message="E-Mail" keyboard="email" enterKeyType="next" />
          <TextInput id="password" class="password" message="Password" type="password" enterKeyType="next" />

          <Button text="Send" onTap={this.do} />
        </ScrollView>
      </$>
    );
  }
```

Now, I have a function `do`:
```
  public do(event: any) {
    ...
  }
```
Here, I would like to access the TextInput fields and get their text for validation purposes. But no matter what, no matter which selector, it is always empty.

I tried e.g. `contentView.find('#email')` but nothing. I tried `$(XYZ).find('#email')` but nothing and so on and so forth. The only way I was able to access any field was by grabbing the `target` from the event (the Button) and checking its siblings.

Is there no way to in general select or filter for a specific Id from here?

Thanks a lot in advance for any hint in the right direction ^^

**Comment by nea** [comment]
Maybe in addition: If I go for `._find(...)` it works.

Why does it work with the one but not the other for a normal Composite Component without any large hierarchy?

**Comment by cookieguru** [comment]
There's a detailed document on `find` and its related methods here:
http://docs.tabris.com/latest/selector.html

Generally you'd want to run find on the element closest (in the widget tree) to the element you're trying to find.  `contentView` is always going to be the furthest.  In your `do` method does it work if you execute `this.find(...)`?

**Comment by nea** [comment]
Hi @cookieguru 

I have of course read the documentation there. Otherwise, I would not have had any way what to try and used every example there. I also tried the hello world example. this returned the same nothing. 


Thanks

**Comment by cookieguru** [comment]
What object are you calling `find` on?

**Comment by nea** [comment]
Hi @cookieguru 

As mentioned above, I tried to find on the `contentView`, I tried on the component via `$(XYZ)`, this and many others I deleted meanwhile testing ^^


Best

**Comment by cookieguru** [comment]
`find` is able to traverse through multiple children including a `WidgetCollection` as demonstrated by this snippet which can be run on [the playground](https://playground.tabris.com/):
```js
import {contentView, Tab, TabFolder, TextView} from 'tabris';

contentView.append(
  <$>
    <TabFolder paging stretch>
      <Tab id='example' title='Example'>
        <TextView center>Content of Example Tab</TextView>
      </Tab>
    </TabFolder>
  </$>
);

console.log(contentView.find('#example'));
```

If your component was not added to the `contentView` by its initializer then that would explain why it is not findable my searching through the `contentView`.  As to why it doesn't work on `this` I don't have any ideas.  You may wish to run [`console.dirXml()`](http://docs.tabris.com/latest/api/Console.html#dirxmlobject) or [attach a debugger](http://docs.tabris.com/latest/debug.html) to see what the widget tree is on the element at the time of execution.

**Comment by nea** [comment]
Hi @cookieguru 

Yes, I know the examples and I know that it should work like that. That is why I am wondering why it is not working. I have my view `XYZ` visible on the Screen, in the emulator, added to the contentView. This view has that action as described above, I click the button and then in the callback it has an empty WidgetCollection, nothing can be found, not even a single child. But if accessing via `_find` it works.

There are no multiple components, no nothing. I deleted everything else, just `App` adding the component to the `contentView`. 

Ok, I will try to continue debugging. But the given example does not work for me in a TypeScript environment with two classes (not a plain top-down file) is what I found out so far.


Thanks

**Comment by ishigo1987** [comment]
@nea what I would suggest you do is create a new fresh empty project and try the cookieguru example, and send us what appears in the console.

**Comment by nea** [comment]
Hi @ishigo1987 

My test project is already pretty empty from the MVVM typescript template. Maybe, how would this example look as TypeScript class implementation of `App.tsx` and e.g. `ViewXYZ.tsx`?


Thanks

**Comment by tbuschto** [comment]
> Maybe in addition: If I go for `._find(...)` it works.

Maybe you are using @compoment?

https://docs.tabris.com/3.5/databinding/@component.html#encapsulation
https://docs.tabris.com/3.5/selector.html#encapsulation

If this helps, please let me know how you would think this should be documented. Maybe add comments to the template?

**Comment by nea** [comment]
Hey @tbuschto 

You are my hero! That was the link I was overlooking/reading over and missing!
https://docs.tabris.com/3.5/databinding/@component.html#encapsulation


Thanks big time ^^

**Comment by cookieguru** [comment]
@tbuschto Adding a link to that in the Selector doc would be spiffy 😀
