### ISSUE TITLE
Q: Data binding - nested object property binding possible?

### ISSUE THREAD

**Issue by nea** [eclipsesource/tabris-js#2083]
### Question

Hi there

Is it possible to `bind` into nested models? So, for example you have a model property `User` with an `email` field and would like to `bindAll` something like:
```
user.email: '#xyz.text'
```
to the models property path.

Is this possible in any way or am I thinking wrong here? ^^

Thanks a lot

**Comment by tbuschto** [comment]
You can bind to nested properties in one-way bindings[1], but not in two-way bindings[2]. The `bindAll` decorator creates two-way bindings. For an MVVM approach this should be sufficent as a ViewModel usually doesn't contain domain-specific models. You can also mix the two, though I'm not sure that is such a good idea.

[1] https://github.com/eclipsesource/tabris-decorators/blob/adddfc8a0a572e0a8dadc47a5937a771041d16bc/examples/bind-one-way/src/ExampleComponent.tsx#L35

[2] https://github.com/eclipsesource/tabris-decorators/blob/adddfc8a0a572e0a8dadc47a5937a771041d16bc/examples/bind-two-way-model/src/ExampleComponent.tsx#L12

**Comment by nea** [comment]
Ahoi @tbuschto 

Thanks for that and the enlightenment.

That is a good info, so I will adapt accordingly. I was just fooling around and testing whats possible and what not. But you make some good points.


Thanks a lot
