### ISSUE TITLE
Where is the code of com.eclipsesource.tabris.android.internal.nativeobject.view.ViewHandler

### ISSUE THREAD

**Issue by srghma** [eclipsesource/tabris-js#2085]
### Question

the `com.eclipsesource.tabris.android.internal.nativeobject.view.ViewHandler` is mentioned in documentation 

https://docs.tabris.com/latest/custom-widgets-android.html

but I cannot find where it's defined

I searched at

https://github.com/eclipsesource/tabris/tree/2.0.2/com.eclipsesource.tabris/src/com/eclipsesource/tabris/internal

but didnt find

tnx

**Comment by mpost** [comment]
The source code of the class in question is not publicly available. You can however compile against it. 

The repo you linked to (https://github.com/eclipsesource/tabris) is the home of "Tabris for Eclipse RAP". It is a different technology stack which is based on tabris-js.

**Comment by srghma** [comment]
Thanks for reply, yes, that in readme

Can I ask you why the source code of ` com.eclipsesource.tabris.android.internal.nativeobject.view.ViewHandler` is not available? Will it be available someday?

What about the source code for iOS? Is it too not available?

Thx

**Comment by cookieguru** [comment]
As mentioned in [pricing](https://tabris.com/pricing/) the native source code is available for license to Organization subscribers

**Comment by srghma** [comment]
@cookieguru did you ever consider to opensource the android and ios native code?

why it is not open-sourced?

______

I'm considering to make a purescript framework based on tabris (the codebase is prettier then of nativescript or react-native), but this is a problem for me

**Comment by cookieguru** [comment]
@srghma I'm not part of EclipseSource so I cannot answer that
