### ISSUE TITLE
Image load error when the src come from android-drawable

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#2086]
```Javascript
new tabris.ImageView({width:50, height:50, centerY:0, image:{src:"android-drawable://ic_sentiment_satisfied_black_24dp"}}).appendTo(tabris.contentView)
```
### Problem description

Display an image fail with error(Image '0' could not be loaded) if it comes from the drawable folder

### Environment

- Tabris.js version: 3.6.0-dev.20200626 
- Device: Huawei P10 Lite
- OS: Android 8

**Comment by cookieguru** [comment]
That one isn't bundled with the app.  This works:
```js
import {contentView, ImageView} from 'tabris';

new ImageView({
	background: 'black',
	width: 50,
	height: 50,
	centerY: 0,
	image: {src: 'android-drawable://abc_ic_menu_cut_mtrl_alpha'}
}).appendTo(contentView);
```

It'd probably just be easier to [import the PNGs](https://google.github.io/material-design-icons/#icon-font-for-the-web) and you'd get iOS compatibility too.

**Comment by ishigo1987** [comment]
Yes you're right, I often import the png but I was doing a test when I discovered that the icon didn't show up.
