### ISSUE TITLE
Installing an npm packet removes the tabris folder from the node_nodule folder

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#2087]
This is quite weird but if in your application in development you install an npm package via npm install package, the package installs fine, but removes the tabris package from the node_module folder implicitly.

As a workaround you have to copy again the tabris package manually into the node_module folder.
NodeJs 14.3.0
Npm 6.14.5
Tabris Cli 3.5
TabrisJs Nightly

**Comment by cookieguru** [comment]
Please post the contents of your `package.json` file

**Comment by ishigo1987** [comment]
```JSON
 {
  "main": "src/app.js",
  "private": true,
  "scripts": {
    "test": "eslint .",
    "start": "tabris serve -a"
  },
  "dependencies": {
    "base-64": "^0.1.0",
    "cordova-gallery-access": "^3.0.3",
    "fast.js": "^0.1.1",
    "google-libphonenumber": "^3.2.10",
    "infinite-list": "^1.1.0",
    "performance-now": "^2.1.0",
    "tabris": "nightly"
  },
  "devDependencies": {
    "eslint": "^6.8.0"
  }
}
```

**Comment by cookieguru** [comment]
Can you try a `npm install --verbose` to see why the package is removed?

**Comment by ishigo1987** [comment]
He doesn't show me anything special. The only interesting thing is that he uninstalls Tabris 3.5, I think.
npm info lifecycle tabris@3.5.0~preuninstall: tabris@3.5.0
npm info lifecycle tabris@3.5.0~uninstall: tabris@3.5.0

**Comment by cookieguru** [comment]
Looks like your lock file is out of date.  Compare the contents of `package-lock.json` to `package.json`.  If the version numbers are generally in sync and/or you do not mind upgrading dependencies to their latest version then you should delete `package-lock.json` and run `npm install` again.


BTW this is not a Tabris bug

**Comment by ishigo1987** [comment]
Ok, got it.

**Comment by mpost** [comment]
Closing this as resolved.
