### ISSUE TITLE
First Camera openning not works

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#2088]
### Problem description
the camera does not work the first time a user opens it and accepts the permission, in order for it to work the user must close the application and open it again

### Expected behavior
the camera must work as soon as the user has accepted the permission

### Environment

- Tabris.js version: Tabris 3.6 3.6.0-dev.20200629
- Device: Huawei P10 lite
- OS: Android 8

### Code snippet

```js
const{CameraView, contentView, device, permission} = require("tabris");

if (permission.isAuthorized('camera')) {
    displayCamera();   
} else {
    permission.requestAuthorization("camera").then((responseStatus) => {
        if (responseStatus !== "granted") {
            // Permission denied
        } else {
            displayCamera();
        }
    });
}

function displayCamera(){
  const camera = device.cameras[0];
  camera.active = true;
  new CameraView({layoutData: 'stretch', camera}).appendTo(contentView);
}
```

**Comment by elshadsm** [comment]
@ishigo1987 thanks for reporting the issue. But I couldn't reproduce the issue with Samsung A70 (Android 10), Emulator Pixel 3a XL (Android 10), and Emulator Pixel 2 XL (Android 8.1) devices.

We recently updated the CameraX library. Could you please try to build a new client against the latest Android Platform and retest?

**Comment by ishigo1987** [comment]
My last test was with the nightly from yesterday, do you want me to try again with the today nightly?

**Comment by elshadsm** [comment]
Do you mean that you created a new client yesterday and tested the code with this app?

**Comment by ishigo1987** [comment]
Yes

**Comment by elshadsm** [comment]
I will figure it out.

**Comment by ishigo1987** [comment]
Thank You @elshadsm

**Comment by cookieguru** [comment]
Logcat output would also be useful

**Comment by elshadsm** [comment]
@ishigo1987, the issue has been solved.

**Comment by ishigo1987** [comment]
Yes Thank you
