### ISSUE TITLE
opening the cameraView crashes the application

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#2093]
### Problem description
opening the camera crashes the application

### Expected behavior
the application does not crash

### Environment

- Tabris.js version:Nightly 3.6.0-dev.20200726
- Device: Huawei P10 Lite
- OS: 8

### Code snippet

```js

const{permission, CameraView, device, contentView} = require("tabris");

if (permission.isAuthorized('camera')) {
    camera()  
} else {
    permission.requestAuthorization("camera").then((responseStatus) => {
        console.log(responseStatus)
        if (responseStatus !== "granted") {
            // Permission denied
        } else {
            camera()
        }
    });
}

function camera(){
    const camera = device.cameras[0];
    camera.active = true;

    new CameraView({
      layoutData: 'stretch',
      camera
    }).appendTo(contentView);
}


```

**Comment by cookieguru** [comment]
Logcat output would be wonderful.

Does it make a difference if the permission is granted/denied/declined/undetermined?

**Comment by ishigo1987** [comment]
@cookieguru unfortunately at the moment with my phone every time I try to debug my machine doesn't recognize my phone.

@mpost  @elshadsm  are you there?

**Comment by elshadsm** [comment]
@ishigo1987, the issue has been solved.

**Comment by cookieguru** [comment]
@ishigo1987 There are apps where you can view logcat output on the device; no adb required

**Comment by ishigo1987** [comment]
@cookieguru  thank you very much
@elshadsm  Thank you too
