### ISSUE TITLE
fs.openFile() not working

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#2097]
### Problem description
Calling fs.openFile() function return an error like ```TypeError: fs.openFile is not a function```

### Expected behavior
Open the file picker Ui

### Environment

- Tabris.js version: 3.6.0
- Device: Huawei P10 lite
- OS: Android 8

### Code snippet

```js

const{permission, contentView, Button, fs} = require("tabris");
permission.requestAuthorization('storage')
    .then(status => {
        if (status != 'granted'){
            console.error('No permissions!')
        }
        else {
            new Button({centerX:0, centerY:0, text:"Take an image",background:"blue"})
            .onTap(()=>{
              fs.openFile({type:"image/*"}).then((response)=>{
                 console.log(response);
              });
            }).appendTo(contentView);
        }
    });
```

**Comment by ishigo1987** [comment]
@elshadsm , @mpost  have you seen this bug?

**Comment by mpost** [comment]
have you run `npm install` to fetch 3.6?

**Comment by ishigo1987** [comment]
No, I'll do it immediately.

**Comment by ishigo1987** [comment]
it's works thank you

**Comment by ishigo1987** [comment]
@mpost  according to the documentation 
```
Once the picker ui is closed the returned promise resolves with an array of File objects or an empty array if no file has been selected
```
but if i open the picker ui and i close it without taking any file i've this error
```
Uncaught promise rejection (id: 0) Error: uri
   Error: uri
       at onError (./node_modules/tabris/tabris.min.js:1:151592)

```

**Comment by mpost** [comment]
That is because you have to catch the rejected promise.

**Comment by ishigo1987** [comment]
You're absolutely right, thank you

**Comment by ishigo1987** [comment]
Hello @mpost  @elshadsm  right now ```fs.openFile``` return for example a file like that ```File { [Symbol(bytes)]: ArrayBuffer { byteLength: 60669 } }```
with name equal to the name of the file, how can i get the full path of the file(uri path)?

**Comment by mpost** [comment]
That is not possible since the file could be eg on a cloud drive.

**Comment by ishigo1987** [comment]
OK, you're right, but it brings up another problem, which I'm currently facing. I need to work with absolute paths, so every time I fetch a file with fs I have to copy the arraybuffer to a new file to get its absolute path, it quickly becomes problematic because if I have to copy multiple videos, or a large video it crashes the application and duplicates the files.

**Comment by ishigo1987** [comment]
i found a solution thank you again
