### ISSUE TITLE
Facilitate the layout of widgets in a grid

### ISSUE THREAD

**Issue by jkrause** [eclipsesource/tabris-js#21]
Grid layouts are a common way to layout user interfaces. Our relative layout is very powerful, but not very intuitive when creating grids.

One option to improve this is to create some kind of GridFactory that can be initialized with the number of columns (and their width). Calling the GridFactory in the order the widgets are created would then create the appropriate layoutData.
```
 var text = page.append( "Text", {
	text: "some text",
	layoutData: gridFactory.next()
  });
```

**Comment by gosia-eclipsesource** [comment]
Closing this as grid layout will be implemented for CollectionView (#172)
