### ISSUE TITLE
App freezes when we share a file

### ISSUE THREAD

**Issue by elshadsm** [eclipsesource/tabris-js#2106]
### Problem description
The app freezes when we download a pdf file then try to share it via the `app#share` feature.

### Expected behavior

The `app#share` feature should work as expected.

### Environment

- Tabris.js version: 3.6.0
- Device: iPhone 6
- OS: 12.4.8

### Code snippet

```TypeScript
import { app, Button, contentView, fetch } from 'tabris';

class SharePdf {

  public async share(url: string) {
    try {
      const pdf = await this.download(url);
      if (pdf) {
        const fileName = 'test.pdf';
        const file = new File([pdf], fileName, { type: pdf.type });
        await app.share({ files: [file] });
      }
    } catch (error) {
      console.error(error);
    }
  }

  public async download(url: string): Promise<Blob> {
    const result = await fetch(url);
    const blob = await result.blob();
    return blob;
  }

}

contentView.append(
  <Button
    stretchX centerY
    text='Download and Share'
    onSelect={() => {
      new SharePdf()
        .share('http://www.africau.edu/images/default/sample.pdf')
        .catch(console.error);
    }} />
);

```

**Comment by AndrejLES** [comment]
We experience a similar issue when trying to share zip files. In our case the app crashes.

**Environment**
- Tabris.js version: 3.6.1
- Device: iPad Air 3rd Gen
- OS: 13.6

**Code snippet**
`public async shareLogs() {
    await this.bundleLogFiles(async (archiver: ZipArchiver) => {
      const zipFilePath = await archiver.generateZipArchive();
      const blob = await (await fetch(zipFilePath)).blob();
      const file = new File([blob], 'logs.zip', { type: blob.type });
      await app.share({ files: [file] });
    });
  }

public async generateZipArchive(): Promise<string> {
    const zipFilePath = fs.cacheDir + `/${this._zipFileName}`;
    const content = await this.getZipArchiveContent();
    await fs.writeFile(zipFilePath, content);
    return zipFilePath;
  }`

**Comment by ahmadov** [comment]
This is even reproducible without sharing a file.

**Snippet to reproduce:**
```jsx
import {app, Button, contentView, Stack,TextInput} from 'tabris';

contentView.append(
  <Stack stretch padding={16} spacing={16} alignment='stretchX'>
    <TextInput stretchX right={8} message='enter text to share' />
    <Button onSelect={share} text='Share me'/>
  </Stack>
);

async function share() {
  try {
    const target = await app.share({
      title: 'Text share',
      text: $(TextInput).only().text,
    });
    console.log('Successfully shared to', target);
  } catch (e) {
    console.error(e);
  }
}

```

**Comment by ahmadov** [comment]
I can verify that it works as expected!
