### ISSUE TITLE
TextInput#onInput listener is not called

### ISSUE THREAD

**Issue by elshadsm** [eclipsesource/tabris-js#2109]
### Problem description

When we create a TextInput with an **XML-like declaration**, the `onInput` listener is not called when we input data. However, it works as expected when we create the same snippet with Imperative UI (Like `new TextInput({...})`). 

### Expected behavior

The `onInput` should be called as expected.

### Environment

- Tabris.js version: 3.7.0-dev.20201012
- Device: iPhone 6
- OS: 12.4.8

### Code snippet

```tsx
contentView.append(
      <TextInput
        left={16} right={16} centerY
        onInput={({ text }) => console.log(text)}
      />
    );
```

**Comment by patrykmol** [comment]
Works fine in nightly. Closing.
