### ISSUE TITLE
Support configuring the scroll behavior of CollectionView#reveal()

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#2112]
### Feature description

Currently, `CollectionView#reveal()` will scroll the minimal amount required to make an item visible on Android and the item will be put in the center of the view on iOS. For some UIs, like the fast scroll feature of Android's RecyclerView, one would prefer to put the revealed item on the top of the view:

![](https://i.stack.imgur.com/YyRtC.png)
Image source: https://stackoverflow.com/questions/31261437/how-to-create-material-design-like-custom-scrollbar-with-numbers-and-alphabets-b

### Proposed solution

`reveal()` should provide a parameter to configure whether the revealed item should be shown e.g. on the top, in the center of the view or if the view should scroll the minimal distance required to show the item.

**Comment by mpost** [comment]
On the Android side the method `androidx.recyclerview.widget.LinearLayoutManager#scrollToPositionWithOffset` could be used. It is not smooth scrolling but an instance jump. It allows to specify an offset in pixels to the original target position.

**Comment by karolszafranski** [comment]
Scroll position is configurable on iOS. Currently we use "centered".

Possible values: https://developer.apple.com/documentation/uikit/uicollectionviewscrollposition?language=objc#
