### ISSUE TITLE
CollectionView#reveal() behavior inconsistentent among platforms

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#2113]
### Problem description

On Android, `CollectionView#reveal()` scrolls the minimal amount of distance possible to show the item in the view. On iOS, the item to be shown will be shown in the center of the view instead.

### Expected behavior

Related to https://github.com/eclipsesource/tabris-js/issues/2112. In case #2112 cannot be implemented, the scroll behavior of `CollectionView#reveal()` on iOS and Android should be aligned.

### Environment

- Tabris.js version: nightly and 2.9.0
- OS: Android and iOS

### Code snippet
Run `tabris serve -im dist/collectionview-scroll.js` in `snippets/` and execute `tabris.contentView.find(tabris.CollectionView).first().reveal(40)` in the interactive console.

**Comment by mpost** [comment]
I would argue that it follows the native patterns established on each platform. When we implement https://github.com/eclipsesource/tabris-js/issues/2112 you should have more control of the exact behavior.

**Comment by tbuschto** [comment]
Can not be fixed.
