### ISSUE TITLE
textChanged event not fired when the text is auto-corrected

### ISSUE THREAD

**Issue by ahmadov** [eclipsesource/tabris-js#2119]
### Problem description

`textChanged` event is not triggered when the text is changed via the `auto-correction` feature. 

This is tricky to reproduce.
1. enter a text in the input
2. select text
3. replace the highlighted text with another one from the suggestion list for auto-correction.
4. `textChanged` event is not triggered.

### Expected behavior

`textChanged` event on TextInput is fired when the text is auto-corrected.

### Environment

- Tabris.js version: Tabris.js 2.10 (20201030)
- Device: iPadPro 3rd gen
- OS: iOS 14.0.1

### Code snippet

```js
const { ui, TextInput } = require('tabris');

ui.contentView.append(
  new TextInput({
    top: 50,
    left: '20%',
    right: '20%',
    type: 'multiline',
    autoCorrect: true,
    autoCapitalize: true,
    height: 120
  }).on('textChanged', ev => {
    console.log('text changed:', ev.target.text);
  })
);
```

**Comment by karolszafranski** [comment]
This is an iOS issue and unfortunately there is nothing we can do to fix it in Tabris.js.

To open more possibilities for workarounds, we introduced `beforeTextChange` event on `TextInput` https://github.com/eclipsesource/tabris-js/commit/0053a74af381675c74c7692816d8a47c4f901f11 It has been cherry-picked on 2.x and is already available on both platforms.

It is fired before text changes, but you can read the future `text` value from `newValue` parameter.
