### ISSUE TITLE
How to warp text on android?

### ISSUE THREAD

**Issue by Nabeel20** [eclipsesource/tabris-js#2120]
### Question

How to warp text on android

**Comment by cookieguru** [comment]
There's not much to go on here; a code snippet would help to know where you are starting from.  And I assume you mean _wrap_ not warp.

If you have something like this:
```javascript
import {TextView, contentView} from 'tabris';

new TextView({
  top: 0, left: 0,
  text: 'Hello World!'
}).appendTo(contentView);
```
You will notice that the text will start in the upper left corner and continue on to the right for all the text specified.

If you add `right` as specified like so:
```javascript
new TextView({
  top: 0, left: 0, right: 0,
  text: 'Hello World!'
}).appendTo(contentView);
```
It will force the TextView to end at the right edge of the screen, and text will flow to the next line as necessary.

There's also a [Tabris.js Slack Channel](https://tabrisjs.herokuapp.com/) full of experts that can answer questions any time

**Comment by Nabeel20** [comment]
Thank you!
