### ISSUE TITLE
how to change the icon of .apk file?

### ISSUE THREAD

**Issue by Nabeel20** [eclipsesource/tabris-js#2122]
`.apk` icon won't change or icon app in recent apps or in the device settings,  but **the icon of the app has already changed in online build page and in home screen after installing**. 

[link to image on Imgur](https://imgur.com/a/YxHPdMj)

**Comment by cookieguru** [comment]
Try uninstalling/reinstalling it

**Comment by Nabeel20** [comment]
@cookieguru  I have already done that and tried to rebuild the app, I just want to put the brand logo on ```.apk``` file icon instead of GitHub avatar.

**Comment by cookieguru** [comment]
Have you already set your app icons in your project's [`config.xml`](https://docs.tabris.com/latest/build.html#the-configxml-file)?

**Comment by Nabeel20** [comment]
@cookieguru  yes and I added a splash screen which works fine too, only the ```.apk``` icon still GitHub avatar icon.
```Javascript
<platform name="android">
<preference name="SplashMaintainAspectRatio" value="true"/>
 <icon density="ldpi" src="res/icon/ldpi.png"/>
 <icon density="mdpi" src="res/icon/mdpi.png"/>
 <icon density="hdpi" src="res/icon/hdpi.png"/>
 <icon density="xhdpi" src="res/icon/xhdpi.png"/>
 <icon density="xxhdpi" src="res/icon/xxhdpi.png"/>
 <icon density="xxxhdpi" src="res/icon/xxxhdpi.png"/>

 <splash density="port-ldpi" src="res/splash/splash-port-ldpi.png"/>
 <splash density="port-mdpi" src="res/splash/splash-port-mdpi.png"/>
 <splash density="port-hdpi" src="res/splash/splash-port-hdpi.png"/>
 <splash density="port-xhdpi" src="res/splash/splash-port-xhdpi.png"/>
 <splash density="port-xxhdpi" src="res/splash/splash-port-xxhdpi.png"/>
 <splash density="port-xxxhdpi" src="res/splash/splash-port-xxxhdpi.png"/>
 <resource-file src="res/theme.xml" target="app/src/main/res/values/theme.xml" />
 <preference name="Theme" value="@style/Theme.my_app_name" />
</platform>
```

**Comment by cookieguru** [comment]
Make sure you have the correct attributes and paths, see #905, #959

**Comment by Nabeel20** [comment]
@cookieguru  I have already checked #905 and #959 and If I have wrong paths the splash screen and the icon after insalling the app should not work, but both of them work fine so I am just saying that the apk file should have the same logo.
