### ISSUE TITLE
Can the direction of the Collection view be set to horizontal

### ISSUE THREAD

**Issue by DiamoandDog** [eclipsesource/tabris-js#2124]
I want a horizontally sliding collectionView,how should i configure it？

**Comment by cookieguru** [comment]
This is not currently possible; you'd need to use a `CollectionView` and set the [`direction`](https://docs.tabris.com/latest/api/ScrollView.html#direction) to `horizontal`.  I wouldn't recommend it if your list has several items as all children of the `CollectionView` are placed in memory when the widget is created.

If you have a small number of items and want the children to "snap" when scrolled left or right I'd look in to a [`TabFolder`](https://docs.tabris.com/latest/api/TabFolder.html) with the `tabBarLocation` set to `hidden`.

There's also a [Tabris.js Slack Channel](https://tabrisjs.herokuapp.com/) full of experts that can answer questions any time

**Comment by DiamoandDog** [comment]
> This is not currently possible; you'd need to use a `CollectionView` and set the [`direction`](https://docs.tabris.com/latest/api/ScrollView.html#direction) to `horizontal`. I wouldn't recommend it if your list has several items as all children of the `CollectionView` are placed in memory when the widget is created.
> 
> If you have a small number of items and want the children to "snap" when scrolled left or right I'd look in to a [`TabFolder`](https://docs.tabris.com/latest/api/TabFolder.html) with the `tabBarLocation` set to `hidden`.
> 
> There's also a [Tabris.js Slack Channel](https://tabrisjs.herokuapp.com/) full of experts that can answer questions any time

thank you so much！
