### ISSUE TITLE
How to obfuscate code in my app?

### ISSUE THREAD

**Issue by Nabeel20** [eclipsesource/tabris-js#2125]
I tried to use webpack so I could use plugin. I have already tried cordova plugin but because I am building online it does not work.
I am using: 
webpack: "^5.6.0",
webpack-cli: "^4.2.0",
webpack-obfuscator: "^3.1.0"
```javascript
ERROR in main
Module not found: Error: Can't resolve './src' in '/home/travis/build/eclipsesource/tabris-js-build-template/build'
webpack 5.6.0 compiled with 1 error in 131 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2020-11-23T07_12_54_192Z-debug.log
The command npm exited with 1
```

**Comment by cookieguru** [comment]
That looks like an error with your webpack configuration and is not Tabris-specific.

You might also check https://tabris.com/securing-your-mobile-application-in-javascript/

**Comment by ishigo1987** [comment]
@Nabeel20  maybe this link can help you
https://tabris.com/bundle-your-tabris-js-app-code-with-webpack/
