### ISSUE TITLE
Video player crash with 3.7

### ISSUE THREAD

**Issue by mfaessel** [eclipsesource/tabris-js#2128]
### Problem description

Video player crash with 3.7 (Tabris crash and close)
it works previously with 3.6

### Expected behavior

Video player to work (like with Tabris 3.6)

### Environment

- Tabris.js version: 3.7
- Device: MI9
- OS: Android 8 and Android 5 (Nox Player)

### Code snippet

https://playground.tabris.com/?gitref=v3.7.0&snippet=video.js

**Comment by cookieguru** [comment]
I can confirm the crash and have pasted logcat output [here](https://pastebin.com/raw/VsPF9bqV)

**Comment by mpost** [comment]
Thanks for the report we can confirm the issue and are working on a solution.

**Comment by elshadsm** [comment]
@mfaessel the issue has been solved.

**Comment by mfaessel** [comment]
You guys are awesome! 
Thank you for this awesome tool!
