### ISSUE TITLE
Canvas leaks memory

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#2130]
### Problem description

Calling `canvas.getContext()` creates an instance of `GC` and associates it with the `Canvas`:

https://github.com/eclipsesource/tabris-js/blob/3038b5827767ea5f343bb56788dff478eaf9598b/src/tabris/CanvasContext.js#L198-L205

The `GC` native object is however never disposed, resulting in a memory leak.

### Expected behavior

The `GC` object should be disposed along with its canvas.

Proposed fix (https://github.com/eclipsesource/tabris-js/blob/master/src/tabris/widgets/Canvas.js):

```ts
export default class Canvas extends Composite {
  // ...
  // overwrite _dispose() method:
  _dispose(skipNative) {
    if (this._gc) {
      this._gc._dispose();
    }
    super._dispose(skipNative);
  }
  // ...
```
Tested but not sure if I'm not missing anything, @mpost @patrykmol @karolszafranski do you think this would be viable?

### Environment

- Tabris.js version: 3.7

**Comment by Elyft** [comment]
@cpetrov  all thoses bugs(canvas and excludeFromLayout), are just for the 3.7 Tabris version?

**Comment by cpetrov** [comment]
@Elyft Likely they have been around for a longer time.

**Comment by Elyft** [comment]
yes you're right, it's a big problem
