### ISSUE TITLE
app pause event should be fired when app is reloaded

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#2135]
### Problem description

The app pause event is not fired when the app is reloaded during development via the reload
button in the developer ui bar or via CLI.

### Expected behavior

The event should fire since the "resume" event DOES fire after a reload. It's also useful if the pause event is used to persist data.

### Environment

- Tabris.js version: 3.8
- Device: iPad
- OS: iOS 13

**Comment by mpost** [comment]
I tried to replicate the issue on Android using the `app-events.jsx` snippet but to no success. The pause and stop events are fired when pressing the console or the reload button. I see the follow up protocol message in the LogCat log.

One thing that does not work is to print to the console. Possibly the tabris js client is already shutdown so printing to the console does not work?

**Comment by tbuschto** [comment]
Correction, it works on Android, but not iOS: Here is a snippet:
```
import {Button, TextView, TextInput, contentView, Stack, app} from 'tabris';

contentView.append(
  <Stack stretch alignment='stretchX' padding={16} spacing={8}>
    <TextInput id='value' message='Value' text='Value' onAccept={setValue}/>
    <Button text='Set' onSelect={setValue}/>
    <TextView id='output'/>
  </Stack>
);

const valueField = $('#value').only(TextInput);
const output = $('#output').only(TextView);

app.onPause(setValue);
getValue();

function setValue() {
  localStorage.setItem('Key', valueField.text);
  output.text = `"Key" set to "${valueField.text}"`;
}

function getValue() {
  output.text = `"Key" is "${localStorage.getItem('Key')}"`;
}
```
1. Load snippet. 
2. Enter a value and push "Set"
3. Reload -> Value was set
4. Enter another value, hit reload in the dev bar
5. Value will NOT have changed on iOS, but on Android it will have been set.
