### ISSUE TITLE
NavigationView toolbar disappears when showing large images

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#2138]
### Problem description

When an `ImageView` is appended to `Page` containing an image that has a larger size than the page bounds, the `NavigationView` toolbar disappears.

### Expected behavior

The NavigationView toolbar should be always visible, regardless of the `Page` contents.

### Environment

- Tabris.js version: 3.7.1
- Device: snippet tested with iPad 9,7''
- OS: iOS

### Code snippet

```ts
import {NavigationView, contentView, ImageView, Page} from 'tabris';

contentView.append(
  <NavigationView stretch>
    <CustomPage title='Initial Page'/>
  </NavigationView>
);

function CustomPage() {
  return (
    <Page padding={16}>
      {/* <ImageView stretch image='https://via.placeholder.com/1000x1000' /> toolbar doesn't disappear */}
      <ImageView stretch image='https://via.placeholder.com/2000x4000'/>
    </Page>
  );
}
```

**Comment by samynomad** [comment]
eclipsesource/diwoblood-linz#38 is a very similar problem - maybe (hopefully) related. 

Here, the toolbar shows in 99% of the cases - but sometimes not.
