### ISSUE TITLE
Bug with TextInput autoCapitalize

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#2139]
### Problem description

when you set a textinput (like on the snippet) and change its autoCapitalize property, the enterKeyType property sets itself to Done and the cursor on TextInput does not automatically go to the second character.

### Expected behavior

Just put the autoCapitalize to none after the change(like on the snippet)

### Environment

- Tabris.js version: 3.7.1
- Device: Huawei P10 Lite
- OS: Android 8

### Code snippet

```js
const{contentView, TextInput} = require("tabris");

new TextInput({left: 0, right: 0, centerY:0, height:50, autoCapitalize:"all",  message: "enter something", type:"multiline"})
.onInput(({target,text})=>{
    if(text === ""){
        target.autoCapitalize = "all";
      }else{
        target.autoCapitalize = false;
      }
}).appendTo(contentView);

```

**Comment by cookieguru** [comment]
Can confirm on Android 11.  It also looks like `autoCorrect` gets turned off

![screen-20210120-142251](https://user-images.githubusercontent.com/1888809/105248845-ffe74500-5b2b-11eb-947e-53cc5d47fe18.gif)

**Comment by ishigo1987** [comment]
@elshadsm  @mpost  , Hello

**Comment by elshadsm** [comment]
@ishigo1987, thank you for reporting the issue. We will figure it out.

**Comment by ishigo1987** [comment]
Thank you @elshadsm

**Comment by elshadsm** [comment]
@ishigo1987, the issue has been solved.
