### ISSUE TITLE
Sharing console contents crashes the app

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#2142]
### Problem description

When tapping "..." and "Share console", the app crashes. Can be reproduced in the latest Tabris.js app from the App Store.

### Environment

- Tabris.js version: 3.7.1
- Device: iPad Pro 9.7" FLMN2FD/A
- OS: 14.4

**Comment by patrykmol** [comment]
Fixed with https://github.com/eclipsesource/tabris-ios/commit/c2d1dde9c3269184a9099177674ac83d55ff128b
