### ISSUE TITLE
Implement proper "change" events for all properties

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#215]
Implementing this backbone inspired pattern only for a couple of properties (specifically selection and text) is rather confusing. Also, the existing change events should be fired ragerdless how the property is changed (by user input or by "set").

**Comment by tbuschto** [comment]
This will likely require #278 to be implemented first.

**Comment by ralfstx** [comment]
Fixed by commit e42272168a626b91089e2da1b3a46c3c2bea2634
