### ISSUE TITLE
Popover close event is not fired

### ISSUE THREAD

**Issue by elshadsm** [eclipsesource/tabris-js#2151]
### Problem description

When we close a Popover programmatically, the close event is not triggered. The event is fired as expected when I tap out of the Popover bounds.

### Expected behavior

The event should be fired as expected.

### Environment

- Tabris.js version: 3.8.0-dev.20210304
- Device: iPad 10.2, Samsung A70
- OS: iOS 14.4, Android 10

### Code snippet

```js
const { Popover, TextView, LayoutData, contentView } = require('tabris');

contentView.background = 'yellow';

const popover = new Popover({
  width: 200,
  height: 200
});

popover.onClose(() => console.log('*** closed ***'));

popover.contentView.append(
  new TextView({
    layoutData: LayoutData.stretch,
    text: 'Hello Popover',
    alignment: 'centerX',
    background: '#cecece'
  }).onTap(() => popover.close())
);

popover.open();
```

**Comment by mpost** [comment]
The JS side does not properly relay the native close event fired as a response to the close method to the js event listener
