### ISSUE TITLE
Popover not resized when keyboard is opened

### ISSUE THREAD

**Issue by kuashe** [eclipsesource/tabris-js#2153]
When focusing TextInput within a Popover , the layout is not resized.

- Tabris.js version: 3.7.1
- Device: iPhone 6S
- OS: iOS 13.3

![image](https://user-images.githubusercontent.com/6097946/110750864-70b10080-8243-11eb-8442-528db987e9a5.png)

```js
//  Bug  : on focus layout is not resized
Popover.open(
                  <Popover>
                          <TextInput bottom="10" text="Hello World" />
                  </Popover>
            )
```

```js
// Ok :  Layout is resized
contentView.append( <TextInput bottom="10" text="Hello World" /> )
```

**Comment by mpost** [comment]
Thanks or opening the issue. We will look into it.
