### ISSUE TITLE
Support Border property for Composite

### ISSUE THREAD

**Issue by kuashe** [eclipsesource/tabris-js#2154]
Would it be possible to add support for border for Composite Widget ?

The following would enable completely custom component from Javascript. 

```js
<Composite border={2} borderColor="blue" ></Composite>
```

It would be helpful for pure cross platform custom component.

**Comment by cookieguru** [comment]
See #1345, #1238, #1016, #886

**Comment by kuashe** [comment]
Thanks @cookieguru.

According to [#1016](https://github.com/eclipsesource/tabris-js/issues/1016#issuecomment-308432306) it was basically marked as 'Won't fix'.

I've looked into many apps , it's true they generally don't have border. 

But still , this is something supported on [iOS ](https://www.hackingwithswift.com/example-code/calayer/how-to-add-a-border-outline-color-to-a-uiview) and [Android](https://stackoverflow.com/questions/8203606/android-how-to-draw-a-border-to-a-linearlayout)

@mpost Are they particular reason why Tabris doesn't support border beyond the fact that's its not common ?

**Comment by cookieguru** [comment]
It *is* possible however, as mentioned in #1345 and #886
