### ISSUE TITLE
Add links to snippets on GitHub

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#2164]
All snippt links are currently leading the the playground. That is nice in theory since you can play with the code, but in reality the playground takes so long to completely load that I rather go to my IDE and open the snippet there directly. The links should point to GitHub by default and have a "run in playground" badge or similar attached instead.

**Comment by jumpjack** [comment]
I think this issue is closed now:

![image](https://user-images.githubusercontent.com/1620953/166641805-a7ac31cd-016d-4dc5-a41e-9815e42946d1.png)

**Comment by mpost** [comment]
As mentioned the issue has been resolved.
