### ISSUE TITLE
createImageBitmap crops after resize

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#2166]
### Problem description

createImageBitmap can both crop and resize an image when given all parameters. On iOS it first crops the image, and the result is scaled to the given size. On Android it first resizes the whole image, and then crops, resluting in a different portion of the image being visible since the coordinates were targeting the original size.

### Expected behavior

Apply cropping before the resize, like iOS and Chrome.
### Environment

- Tabris.js version: 3.8 nightly
- Device: Pixel 3 XL (Emulated)
- Android: API 29

### Code snippet

https://github.com/eclipsesource/tabris-js/blob/master/snippets/createimagebitmap-resize.jsx

The last for images differ between Android and iOS.

**Comment by mpost** [comment]
Issue has been resolved.
