### ISSUE TITLE
Fix Picker API

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#217]
The Combo API has several problems:
- The selection event does not contain any information, like selectionIndex or text
- No way to read the current text from the widget either (only by combining selectionIndex and items)
-"selectionIndex" should just be "selection"
-The name (see #115)

**Comment by ralfstx** [comment]
Closed by mistake. The issues haven't been addressed yet.

**Comment by tbuschto** [comment]
The text property exists, but how does it work? Is it ready only?

**Comment by cpetrov** [comment]
Related issues: #354, #355
