### ISSUE TITLE
Update J2V8 with the new upcoming 3.8 TabrisJs

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#2184]
Hello, don't you think it would be nice with this upcoming Tabris 3.8 version to update the J2V8 version because it is more than one year old, the last V8 version is 9.0

**Comment by mpost** [comment]
We are definitely interested in it. Stay tuned for updates on that.

**Comment by ishigo1987** [comment]
Nice, thank you

**Comment by ahmadov** [comment]
This issue can be closed with https://github.com/eclipsesource/J2V8/commit/00dddaa31a80782abbe93c4a01f325db3c4975d6
