### ISSUE TITLE
Unpredictable behavior of statusBar.displayMode when connecting to the server

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-js#2188]
### Problem description

There is a strange problem that sometimes appears in issues on Github (but no one has opened a separate issue about it). In the assembled application, you can specify `statusbar.displayMode = 'float'`, but if you connect to the console (with 'tabris serve') this setting will be ignored. The problem occurs on Android 10, 11 (maybe even older)

### Expected behavior

I want the behavior of `statusbar.displayMode` to be always predictable.

### Environment

- Tabris.js version: 3.7.2 
- Device: Samsung A51, Xiaomi Redmi 5 Plus 
- OS: Android 11, Android 10

### Code snippet

```js
import { statusBar } from 'tabris';

statusBar.background = 'transparent';
statusBar.theme = 'dark';
statusBar.displayMode = 'float';
```

**Comment by elshadsm** [comment]
The issue has been solved.
