### ISSUE TITLE
Drawer page title disappears

### ISSUE THREAD

**Issue by rherrmann** [eclipsesource/tabris-js#2194]
### Problem description

After selecting different drawer pages a few times, the page title disappears.

To reproduce, open the Drawer snippet 'Using a Drawer for app navigation' in the Tabris Developer App:
* Tap _Create page in drawer_
* Select the menu icon and switch forth and back between _Basket_ and _Checkout_

The page title that used to be shown next to the menu icon disappears

### Environment

- Tabris.js version: 3.7.2
- Device: iPhone
- OS: 14.7.1

### Screen Recording

https://user-images.githubusercontent.com/607182/129175332-7f4c21fa-6d3b-4aa7-b808-e62cc859772b.mov

**Comment by karolszafranski** [comment]
fixed https://github.com/eclipsesource/tabris-ios/commit/e6a6fd96229e5f4f8fdd8c2e6a70d3d1248b3a65
