### ISSUE TITLE
TextInput autoCapitalize doesn't work on iOS

### ISSUE THREAD

**Issue by violuke** [eclipsesource/tabris-js#2197]
### Problem description
I'm trying to use `autoCapitalize` attr on `TextInput` with a value of `"all"` (or `true`) but this isn't working on iOS. It's fine on Android. I'm using it in an `AlertDialog,` so it might be only a problem then, I'm not sure to be honest.

### Expected behavior

Each char should be capitalised immediately after input. In my video below, `f` should become `F` before the `a` is typed.

### Environment

- Tabris.js version: 3.7.2
- Device: 
- OS: 

### Code snippet

```js
const dialog = AlertDialog.open(
    <AlertDialog title='Manually enter code' buttons={{ok: 'Save'}}>
        If you can't scan a container's barcode, please enter the container's code here.
        <TextInput message='Container code' autoCapitalize="all" enterKeyType="go" keyboard="ascii" focused={true} keepFocus={true} />
    </AlertDialog>
);
```

https://user-images.githubusercontent.com/6420347/135079968-9a361bc8-281d-4508-8de2-876e0bc8cc8e.mov

Thank you :+1:

**Comment by karolszafranski** [comment]
Issue is fixed in nightly version of Tabris.js and will be available in upcoming 3.8.0 release. Thank you for reporting.
