### ISSUE TITLE
Tabris.js incompatible with npm@>=7

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#2199]
### Problem description

When attempting to build a Tabris.js app with `npm@7` or `npm@8` installed, the build fails with:

```
CordovaError: Could not determine package name from output:
added 1 package in 436ms
    at getTargetPackageSpecFromNpmInstallOutput (/Users/cpetrov/.tabris-cli/cordova/9.0.0/node_modules/cordova-fetch/index.js:104:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 0,
  context: undefined
}
```

### Expected behavior

Tabris.js app builds should be compatible with latest `npm`. 

### Environment

- Tabris.js version: 3.8.0

**Comment by cpetrov** [comment]
@tbuschto Yes, just tested with a freshly installed Node.js 16.13.1/npm 8.1.2 and Cordova freshly installed by the Tabris CLI.

**Comment by hariroshan** [comment]
Did you solve this? @cpetrov

**Comment by hariroshan** [comment]
Solved it by going into `~/.tabris-cli/cordova/9.0.0/node_modules/cordova-lib` and installed latest `cordova-fetch`

**Comment by cpetrov** [comment]
> Did you solve this? @cpetrov. Here is my output
> 
> ```shell
> [./] Replacing variables in config.xml...
> [build/cordova] /Users/hariroshan/.tabris-cli/cordova/9.0.0/node_modules/.bin/cordova platform add /Users/hariroshan/.tabris-cli/platforms/ios/3.8.0 --no-update-notifier
> (node:10639) Warning: Accessing non-existent property '/Users/hariroshan/.tabris-cli/platforms/ios/3.8.0' of module exports inside circular dependency
> (Use `node --trace-warnings ...` to show where the warning was created)
> CordovaError: Could not determine package name from output:
> up to date, audited 222 packages in 916ms
> 
> 12 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities
>     at getTargetPackageSpecFromNpmInstallOutput (/Users/hariroshan/.tabris-cli/cordova/9.0.0/node_modules/cordova-fetch/index.js:104:11)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
>   code: 0,
>   context: undefined
> }
> The command /Users/hariroshan/.tabris-cli/cordova/9.0.0/node_modules/.bin/cordova exited with 1
> ```

Unfortunately I don't have any workaround - other than using an older npm version.

**Comment by hariroshan** [comment]
It seems they fixed the issue in new version of `cordova-fetch`. So we just need to update `cordova-lib`. This is because `cordova@9.0.0` is using the older version of `cordova-fetch` which doesn't work with newer npm

**Comment by cpetrov** [comment]
Thank you for the info, @hariroshan. We should update Tabris CLI to use the new version of Cordova CLI.

**Comment by mpost** [comment]
the tabris-cli is now using cordova 11. Closing this as resolved. Please comment if you have any more issues.
