### ISSUE TITLE
Cannot build Android app with Tabris 3.8 on paid cloud build service

### ISSUE THREAD

**Issue by violuke** [eclipsesource/tabris-js#2201]
### Problem description
I cannot build a Tabris 3.8 app on the cloud build service for Android. iOS builds fine. Android can still build a 3.7.2 app without a problem.

### Expected behavior
App to build successfully.

### Error message
<img width="1053" alt="Screenshot 2021-11-26 at 12 15 49 pm" src="https://user-images.githubusercontent.com/6420347/143579693-e118d33d-a916-48b9-9520-ee8caac6e162.png">

**Comment by ifurnadjiev** [comment]
We are looking on it right now. With tabris.js 3.8 the Cordova platform and android tooling have been updated. As a result the produced bundle file name has changed from "app.aab" to "app-release.aab" or "app-debug.aab" .

**Comment by ifurnadjiev** [comment]
The issue has been resolved. Please trigger your builds again.

**Comment by violuke** [comment]
Thanks, I can confirm this is working for us now :+1:
