### ISSUE TITLE
How to Introspect on Widget property names?

### ISSUE THREAD

**Issue by seanstrom** [eclipsesource/tabris-js#2203]
### Question

Hello 👋,
Is there a way to retrieve a widgets property names? For example if I had the Button widget constructor, how could I retrieve a list of property names like “text” or “style”?

The context for this question is that I’m creating a web component wrapper around the Button widget and I’d like for a way to know the property names. I need the property names in this case because I’m attempting to create an `observedAttributes` list, which is required for a web component to receive attributes or props.

Any chance there’s a clever way to introspect on the widgets for my use-case?

**Comment by cookieguru** [comment]
Properties [aren't](https://github.com/eclipsesource/tabris-js/blob/master/src/tabris/widgets/Button.js) [really](https://github.com/eclipsesource/tabris-js/tree/master/src/tabris/NativeObject.ts) explicitly defined; in fact they are [defined at runtime](https://github.com/eclipsesource/tabris-js/blob/53cc13f9233c0a0e762bac5856b2d02d57f0e0f3/src/tabris/NativeObject.ts#L19).  Even if they were statically defined, getting the list wouldn't be so straightforward; [this SO answer](https://stackoverflow.com/a/40637896) goes in to more detail.  As the properties are defined, [a listener is added](https://github.com/eclipsesource/tabris-js/tree/master/src/tabris/NativeObject.ts#L19) to detect when a property is changed.

While you could access the `$props` variable directly such as with this code:
```typescript
import {Button, contentView} from 'tabris';

const button = new Button({
  left: 16,
  top: 16,
  text: 'Button',
});
button.appendTo(contentView);

console.info(button.$props);
console.info(button._layoutData);
```
which yields this output:
```plain
{ style: 'default', text: 'Button' }
{"left":"0% 16","right":"auto","top":"0% 16","bottom":"auto","width":"auto","height":"auto","centerX":"auto","centerY":"auto","baseline":"auto"}
```
...but I wouldn't rely on it.  Unlike the [public property names](https://docs.tabris.com/latest/api/Button.html#text) the private `$props` variable is subject to change between releases.

If you're dealing with a finite number of widgets, I'd make a correlation table for each object, basically copying the docs.  Those properties are [defined in JSON](https://github.com/eclipsesource/tabris-js/tree/master/doc/api) if you wanted to automate the process.

**Comment by seanstrom** [comment]
Thanks for detailed response, very appreciated! 😁
Based on what you've mentioned, I think my preferred choice is to use the JSON files to help me create my attribute names lists. Thankfully I can now avoid maintaining my own separate list of properties/attributes, since they would eventually diverge or something.

I'll try creating my `observerAttributes` list by referencing the `properties` field in the JSON documentation for each widget. And it appears I will be able to detect which JSON files are for widgets by looking at the `category` field in the JSON. Also maybe I'll be able to check for inherited attribute names by looking at the `extend` field, which seems tell me the name of the parent widget.

Let me know if you think there's something I'm missing or could improve, thank you for your help!
