### ISSUE TITLE
Cloud build service ignoring EnableDeveloperConsole and always builds a DEBUG app

### ISSUE THREAD

**Issue by violuke** [eclipsesource/tabris-js#2204]
### Problem description
The paid-for cloud build service for Android is always building with `EnableDeveloperConsole` as `true` regardless of what's actually being asked of it. I've not tried iOS, but have tried Tabris 3.72, 3.8 and 3.9 nightly using the cloud build service.

I'm unable to build without the developer console enabled. I've tried:
- `<preference name="EnableDeveloperConsole" value="$IS_DEBUG" />` and then toggling it off in the cloud build settings (this is what has been working until recently).
- Hard coding `<preference name="EnableDeveloperConsole" value="false" />` in `config.xml`.
- Removing any specification of `EnableDeveloperConsole` in `config.xml`.

But all options still result in the console being enabled.

The build console certainly thinks it is doing a release (non-debug) build, but that's not what's in the resulting app bundle.

```
Starting build
Cloning build template
Using build template revision 937bfa68b0b0c7f8c729d16c7af8a46cb85338de
Cloning app from https://github.com/REDACTED.git
Building from branch master
Using app revision 88c2ad963d3be2d6baf926ace5556710e76ac966
Processing App Directory
Tabris version from 'package.json': nightly
Determine build template for: 'nightly'
Using build template: default
Build environment created 61b2393f94e2b0e450b90362
Writing Android keystore 'Default Key (REDACTED)'
Encrypting Android Passwords
Encrypting Android Passwords
Choosing build language: android
Building with jdk: [oraclejdk8]
Building with Android components: [tools, platform-tools, build-tools-29.0.2, android-27, android-29]
These things will be built:
  App Id: REDACTED
  Tabris.js Version: 3.8.0
  Build type: Release
  Platform: ANDROID
Creating build job...
Scheduling job (61b2393f94e2b0e450b90362). This may take a few minutes...
Done. Build passed. You can download the apps now.
```

We urgently need to get a release made with the fix in 3.9 nightly, but we're unable to build without the developer console being displayed. Please can you help? Thank you.

**Comment by violuke** [comment]
An update would be greatly appreciated, we are in desperate need to release an update of our app and yet again the paid for build service is letting us down. I'm trying to fend off comments from others in the company suggesting Tabris was the wrong partner/platform (again). We really need this fixed urgently, please.

**Comment by cookieguru** [comment]
[Local build](https://docs.tabris.com/latest/build.html#local-build) is always an option

**Comment by violuke** [comment]
That's what we pay $50 per month to avoid, maybe we shouldn't bother, but we thought supporting the project financially was a good option.

Having never done a local build before, can this be done with the same signing key so as the Play Store trusts the update?

**Comment by cookieguru** [comment]
> Having never done a local build before, can this be done with the same signing key so as the Play Store trusts the update?

Assuming you generated the key yourself and uploaded that to the build service, yes.  If you used the autogenerated key, no (unless you can guess it)

**Comment by violuke** [comment]
We used the autogenerated key by Tabris :( In hindsight, this was the wrong choice.

Can the cloud build either be fixed, or given this is a Tabris problem can someone send me the key that Tabris generated, so I can do a local build in the meantime. I will be happy with either, but we just urgently need to get a build completed.

Thanks for your help.

**Comment by ifurnadjiev** [comment]
We are looking at the issue now. Will let you know with the results.

**Comment by violuke** [comment]
Thank you, very much appreciated :+1:

**Comment by ifurnadjiev** [comment]
We found and fixed the issue in the android platform. The fix will be available in the next nightly build. Please rebuild your app tomorrow (against tabris.js nightly) and let as know about the result.

**Comment by violuke** [comment]
Great, thanks @ifurnadjiev I will test tomorrow morning and confirm.

**Comment by violuke** [comment]
🎉  Yes, that's got it sorted. Thanks for all your help.
