### ISSUE TITLE
It is not possible to have an APK without the developer console on android.

### ISSUE THREAD

**Issue by micheg** [eclipsesource/tabris-js#2206]
### Problem description

It is not possible to have an APK without the developer console on Android.

### Expected behavior

by editing config.xml as follows:

`<preference name="EnableDeveloperConsole" value="false" />`

I would expect an app that doesn't show the "developer console".
(i am using local builds.)

### Environment

- Tabris.js version: 3.8
- Device: Samsung Phone
- OS: Android 11
- Build: Local, ubuntu server

**Comment by micheg** [comment]
Ah! Variable casting appears to be missing.
I see that in:
platforms / android / 3.8.0 / bin / templates / project / app / build.gradle
line 363 is missing a cast.

`    if (cdvHelpers.getConfigPreference('EnableDeveloperConsole', 'false')) {
        implementation("com.eclipsesource.tabris.android:devtools:$tabris_version")
    }`
 
instead of:

`    if (cdvHelpers.getConfigPreference('EnableDeveloperConsole', 'false').toBoolean()) {
        implementation("com.eclipsesource.tabris.android:devtools:$tabris_version")
    }`
    
At the moment I modify my local environment.
So let's say it's not a problem. :-)
(Great local builds)

**Comment by cookieguru** [comment]
You can also build with the nightly build, see https://github.com/eclipsesource/tabris-js/issues/2204#issuecomment-992398953

**Comment by mpost** [comment]
The issue has been resolved in the latest 3.9 nightly. It will properly resolve the `EnableDeveloperConsole` property.

**Comment by mpost** [comment]
We have also backported the fix to the current 3.8 release.
