### ISSUE TITLE
Facebook SDK/ Other library integration

### ISSUE THREAD

**Issue by jhay06** [eclipsesource/tabris-js#2213]
Hi ,
   would like to ask a tutorial on how to integrate facebook SDK and other native library to call from the tabris js part ? 

I want to integrate Facebook SDK event and other SDK such as Google SDK and Firebase SDK but there's no tutorial found on the internet.

also i want to know how to call java /objective c++ method from the JS code ..

thanks

Regards,

**Comment by cookieguru** [comment]
> also i want to know how to call java /objective c++ method from the JS code ..

You will need to create your own plugin; the docs can be found [here](https://docs.tabris.com/latest/custom-widgets.html)

**Comment by jhay06** [comment]
> > I want to integrate Facebook SDK event and other SDK such as Google SDK and Firebase SDK but there's no tutorial found on the internet.
> 

thanks for the response , is there any way that i can add a jar /aar references ? 


> There aren't plugins for this available yet. I suggest you use the [SDKs available on npm](https://www.npmjs.com/search?q=facebook) and use it like you would in any other non-browser environment.
> 
> > also i want to know how to call java /objective c++ method from the JS code ..
> 
> You will need to create your own plugin; the docs can be found [here](https://docs.tabris.com/latest/custom-widgets.html)

I tried the tabris-plugin-fab sample but i end up with an error below , 
4:05:20 PM - Starting compilation in watch mode...
src/App.tsx(9,21): error TS6138: Property 'main' is declared but its value is never read.
src/App.tsx(15,7): error TS2304: Cannot find name 'custom'.
src/App.tsx(26,42): error TS2339: Property 'show' does not exist on type 'Widget<any>'.
src/App.tsx(32,42): error TS2339: Property 'hide' does not exist on type 'Widget<any>'.
4:05:21 PM - Found 4 errors. Watching for file changes.



i followed all the instruction from the blog ,  i already add in the config.xml but i can't make it work

**Comment by jhay06** [comment]
Also i noticed that AndroidManifest , and other resources /res/values/strings.xml is not updating even if it was declared in plugin.xml , the only thing that works is <framework> element for build.gradle 

please see below 

<?xml version='1.0' encoding='utf-8'?>
<plugin id="tabris-plugin-fab" 
        version="1.0.0"
        xmlns="http://apache.org/cordova/ns/plugins/1.0"
        xmlns:android="http://schemas.android.com/apk/res/android">
 
    <name>Tabris Plugin Floating Action Button</name>
   <js-module name="FloatingActionButton" src="www/FloatingActionButton.js">
    <clobbers target="custom.FloatingActionButton" />
    <platform name="android">
     
      <config-file target="AndroidManifest.xml" parent="/manifest/application">
        <meta-data
            android:name="com.eclipsesource.tabris.android.HANDLER.com.tabris.js.android.fab"
            android:value="com.tabris.js.android.fab.FloatingActionButtonHandler" />
      
      </config-file>

      <config-file target="res/values/strings.xml" parent="/resources">
        <string name='test'>test </stirng>
      </config-file>

      <source-file src="src/android/com/tabris/js/android/fab/FloatingActionButtonHandler.kt"
                   target-dir="src/android/com/tabris/js/android/fab" />
      <source-file src="src/android/com/tabris/js/android/fab/ImageProperty.kt"
                   target-dir="src/android/com/tabris/js/android/fab" />
      <framework src="/Users/cebx/tabris/testapp/tabris-plugin-fab/src/android/build.gradle" custom="true" type="gradleReference"/>

    </platform>
</js-module>
</plugin>

whenever i run tabris build android . all resources are not updating other than build.gradle

Thanks

**Comment by jhay06** [comment]
> > > I want to integrate Facebook SDK event and other SDK such as Google SDK and Firebase SDK but there's no tutorial found on the internet.
> 
> thanks for the response , is there any way that i can add a jar /aar references ?
> 
> > There aren't plugins for this available yet. I suggest you use the [SDKs available on npm](https://www.npmjs.com/search?q=facebook) and use it like you would in any other non-browser environment.
> > > also i want to know how to call java /objective c++ method from the JS code ..
> > 
> > 
> > You will need to create your own plugin; the docs can be found [here](https://docs.tabris.com/latest/custom-widgets.html)
> 
> I tried the tabris-plugin-fab sample but i end up with an error below , 4:05:20 PM - Starting compilation in watch mode... src/App.tsx(9,21): error TS6138: Property 'main' is declared but its value is never read. src/App.tsx(15,7): error TS2304: Cannot find name 'custom'. src/App.tsx(26,42): error TS2339: Property 'show' does not exist on type 'Widget'. src/App.tsx(32,42): error TS2339: Property 'hide' does not exist on type 'Widget'. 4:05:21 PM - Found 4 errors. Watching for file changes.
> 
> i followed all the instruction from the blog , i already add in the config.xml but i can't make it work

Okay , i solved the problem above, but there's an annoying display when i run the app on the emulator / android 

![image](https://user-images.githubusercontent.com/5191437/165031083-e41208ad-022b-4c5e-9a8f-2d06c4dfe5a3.png)


how can i remove the URL input bar on the top.

**Comment by cookieguru** [comment]
That's the [developer tools UI](https://docs.tabris.com/latest/api/devTools.html) which can be hidden with a single property change.  Note this is always hidden in production builds.

**Comment by jhay06** [comment]
> That's the [developer tools UI](https://docs.tabris.com/latest/api/devTools.html) which can be hidden with a single property change. Note this is always hidden in production builds.

hi, thank s for the reply , what property should i neet to change ?

**Comment by cookieguru** [comment]
`showUi()`.  You can see it in action with the JSX snippet in the docs

**Comment by mpost** [comment]
Closing this as resolved. Please comment if you have any more issues.
