### ISSUE TITLE
Playground for 2.x is unable to compile some apps for 2.x due to "tabris-decorators" module missing

### ISSUE THREAD

**Issue by jumpjack** [eclipsesource/tabris-js#2220]
Documentation states that "tabris-decorators" module has been introduced in Tabris 2.x, but playground for 2.x fails in finding the module.

This line:

`const {ItemPicker, List} = require('tabris-decorators'); `

results in:

**Could not load main module: Error: Cannot find module 'tabris-decorators'**

in Android developer app for tabris 2.x

**Comment by cookieguru** [comment]
I'm not seeing that anywhere in [the docs](https://docs.tabris.com/2.9/).  Can you link to the line where that is indicated?

The `tabris` package does not export `tabris decorators`.  You'll need to add [the package](https://www.npmjs.com/package/tabris-decorators/v/2.8.0) to your package.json file yourself.  It is not possible to modify the package.json file of the playground; you will need to [set up a project with `tabris-cli`](https://docs.tabris.com/2.9/developer-app.html#run-your-app) in order to load custom packages.

**Comment by jumpjack** [comment]
![image](https://user-images.githubusercontent.com/1620953/166161647-9eac44fe-ac95-4109-a711-983d50f3cbbd.png)

https://tabris.com/tabris-decorators-part-2-introducing-tabris-components/

**Comment by cookieguru** [comment]
That is true, there is nothing in the article that _specifically_ indicates it is a new module that must be loaded.  @tbuschto do you think it would be worth adding that to the blog posts?

---

@jumpjack in the same article you linked there is this line:
> To write your first component, set up a Tabris 2.x project with tabris-decorators as described [here](https://github.com/eclipsesource/tabris-decorators/blob/2.x/doc/setup.md).

The [linked page](https://github.com/eclipsesource/tabris-decorators/blob/2.x/doc/setup.md) specifically indicates it must be installed by running `npm install tabris-decorators`

**Comment by jumpjack** [comment]
Actually it took a while to figure out that I have to add "tabris-decorators" in package.json, the information is well hidden somewhere (can't remember if on tabris site or on stackexchange). Eventually I had to connect developer app to my own repo on github, because I do not have node.js on my machine.

And I think I misunderstood playground capabilities: I read that it "supports tabris", so I supposed it supported it entirely, including decorators.

**Comment by tbuschto** [comment]
I tweaked the blog post series to mention that it's a separate install. The 3.x playground supports decorators, but not the 2.x one. This will not change.
