### ISSUE TITLE
Broken link to Cordova demo

### ISSUE THREAD

**Issue by jumpjack** [eclipsesource/tabris-js#2221]
Broken link to [Tabris.js Cordova demo](https://github.com/eclipsesource/tabris-js/tree/master/examples/cordova)
 in https://tabris.com/cordova-plugins-top-tabris-js-feature-4/ , probably it pointed to https://github.com/eclipsesource/tabris-js/tree/2.8/examples/cordova

Additionally:

there is no Cordova Demo in developer app for 3.x, although 3 plugins are included:

- cordova-plugin-ios-non-exempt-encryption
- tabris-plugin-barcode-scanner
- tabris-plugin-firebase

instead, a Cordova Demo is included in developer app for 2.x, but app does not list available plugins in About screen.
(sidenote: is it possible from inside a tabris app to list all available/installed plugins?)

**Comment by cookieguru** [comment]
The 2.x developer app doesn't list its bundled plugins.  It is recommended that you [build your own app](https://docs.tabris.com/2.9/build.html) in order to try out various plugins that you define in your project's [config.xml](https://docs.tabris.com/2.9/build.html#the-configxml-file) file.

**Comment by jumpjack** [comment]
I found that this line lists all dependecies/modules of the developer app:

console.log("Installed modules:" , Object.keys(require('./package.json').dependencies)); // List installed modules (just 'tabris' in developer app);

Does it exist anything similar which I can use with ./cordova/config.xml ? I tried with fs.fileRead() but it does not accept path "../cordova/config.xml"

**Comment by cookieguru** [comment]
The easiest way is to build an app from a config.xml that you authored yourself, that way you know what's in it.

**Comment by mpost** [comment]
@cookieguru Is correct about building your own app with the config.xml. Although nowadays the plugins should be listed int the `cordova/package.json` file. This is a convention introduced by cordova.

If you have any more problems please let us know.
