### ISSUE TITLE
Fail to build android with tabris-cli@3.8.1 on windows10

### ISSUE THREAD

**Issue by shengxr** [eclipsesource/tabris-js#2235]
### Problem description

I installed nodejs@v16.16.0 and npm@8.16.0 on newly installed windows10. And then run 'npm -g install tabris-cli' and 'tabris init' command to generate new project with default choice. But when I try to build for android, the follow errors occued.

[./] Downloading android platform version 3.8.0...
[./] Extracting platform...
[C:\Users\tabris\.tabris-cli\cordova\9.0.0] npm install cordova@9.0.0
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 455 packages, and audited 456 packages in 1m

16 packages are looking for funding
  run `npm fund` for details

9 vulnerabilities (4 moderate, 5 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
[build/cordova] C:\Users\tabris\.tabris-cli\cordova\9.0.0\node_modules\.bin\cordova platform add C:\Users\tabris\.tabris-cli\platforms\android\3.8.0 --no-update-notifier
(node:5276) Warning: Accessing non-existent property 'C:\Users\tabris\.tabris-cli\platforms\android\3.8.0' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
CordovaError: Could not determine package name from output:
added 1 package, and audited 3 packages in 1s

found 0 vulnerabilities
    at getTargetPackageSpecFromNpmInstallOutput (C:\Users\tabris\.tabris-cli\cordova\9.0.0\node_modules\cordova-fetch\index.js:104:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 0,
  context: undefined
}
The command C:\Users\tabris\.tabris-cli\cordova\9.0.0\node_modules\.bin\cordova exited with 1

### Environment

- Nodejs: 16.16.0
- npm: 8.16.0
- Tabris-cli: 3.8.1
- Tabris.js version: 3.8.0
- OS: Windows10

### Code snippet

```js
// A minimal, *self-contained* code snippet to reproduce the problem:
```

**Comment by tbuschto** [comment]
Duplicate of https://github.com/eclipsesource/tabris-js-cli/issues/83 and already fixed in https://github.com/eclipsesource/tabris-js-cli/commit/33c6e35ddf0b745108305a91c629421ced7a0f93. For now users can either downgrade to node 14 or install tabris cli directly from master where the fix is included.
