### ISSUE TITLE
Play Store complains about 'android:exported' property not set

### ISSUE THREAD

**Issue by cookieguru** [eclipsesource/tabris-js#2248]
### Problem description

When uploading a built APK to the Play Store I receive the following error message:

`You uploaded an APK or Android App Bundle which has an activity, activity alias, service or broadcast receiver with intent filter, but without 'android:exported' property set. This file can't be installed on Android 12 or higher. See: developer.android.com/about/versions/12/behavior-changes-12#exported`

Note I had to bump the target SDK version (from 28) with the following line in my `config.xml`:

```xml
<preference name="android-targetSdkVersion" value="31" />
```

### Environment

- Tabris.js version: 2.9.0

**Comment by mpost** [comment]
This is likely due to the usage of a plugin which does not set its "exported" property on a declared Activity. This would be merged into the AndroidManifest.xml. We set the exported flag on the main activity as you can see at `<platform>/templates/project/AndroidManifest.xml#L36`.

**Comment by cookieguru** [comment]
@mpost I'm only using [cordova-plugin-globalization](https://www.npmjs.com/package/cordova-plugin-globalization)@1.0.3 which [doesn't declare any activities](https://www.npmjs.com/package/cordova-plugin-globalization) and [tabris-plugin-maps](https://github.com/eclipsesource/tabris-plugin-maps)@5.0.0 (but with Google Play Services bumped to 16.1.0).  Would I need to modify something in [its manifest](https://github.com/eclipsesource/tabris-plugin-maps/blob/a6d4a8da7d4cc0cc2b71a2c4de2db8f69672e45d/project/android/maps/src/main/AndroidManifest.xml)?

**Comment by mpost** [comment]
Could you check your build ouput and see which Activity in your AndroidManifest.xml does not declare the export?

**Comment by cookieguru** [comment]
The `MainActivity` and the `TabrisActivity` don't have an exported attribute.  This is the only one with it:

```xml
        <activity
            android:theme="@ref/0x01030010"
            android:name="com.google.android.gms.common.api.GoogleApiActivity"
            android:exported="false" />
```

**Comment by mknauer** [comment]
In my case (a Tabris.js 3.8 based application) I was able to solve the issue by adding the following lines to the `config.xml`:

```xml
  <edit-config
    file="AndroidManifest.xml"
    target="/manifest/application/activity[@android:name='MainActivity']"
    mode="merge">
    <activity android:exported="false"/>
  </edit-config>
```

**Comment by cookieguru** [comment]
@mpost I think that target would work, but would apply the same value to both actives.  If I understand the docs correctly each activity separately should use a different true/false value; the [Android 12 changelog states](https://developer.android.com/about/versions/12/behavior-changes-12#exported) that:
> If the app component includes the `LAUNCHER` category, set `android:exported` to `true`. In most other cases, set `android:exported` to `false`.
and since the TabrisActivity doesn't use the Launcher intent it seems like that should be set to false.  I don't know if there is a downside to marking the TabrisActivity as exportable.

Also, using `file="app/src/main/AndroidManifest.xml"` has no effect; only `file="AndroidManifest.xml"` as @mknauer posted works.

I believe this will work:
```xml
<edit-config file="AndroidManifest.xml" target="/manifest/application/activity[@android:name='com.timbond.seattle.fire.dispatch.MainActivity']" mode="merge">
	<activity android:exported="true" />
</edit-config>

<edit-config file="AndroidManifest.xml" target="/manifest/application/activity[@android:name='com.eclipsesource.tabris.android.TabrisActivity']" mode="merge">
	<activity android:exported="false" />
</edit-config>
```
but cannot currently test because the build keeps failing with only `No Log Found` shown in the logs.  The `target` is xpath, so using simply `/manifest/application/activity` would result in only the first activity being updated.

**Comment by cookieguru** [comment]
I tried running a local build and have found that the cloud build is likely failing because of this error message:
```plain
[build/cordova] /usr/lib/node_modules/tabris-cli/node_modules/.bin/cordova build android --no-update-notifier
Conflict found, edit-config changes from config.xml will overwrite plugin.xml changes
Error: Unable to graft xml at selector "/manifest/application/activity[1]" from "/path/to/build/cordova/platforms/android/AndroidManifest.xml" during config install
The command /usr/lib/node_modules/tabris-cli/node_modules/.bin/cordova exited with 1
```

I've been unable to find a combination of `file` and `target` params which will reliably set the exported property on both activities so I'm going to do what I should have in the first place: migrate to 3.x

Closing as "resolved"
