### ISSUE TITLE
Provide information about native client

### ISSUE THREAD

**Issue by ifurnadjiev** [eclipsesource/tabris-js#225]
In some cases (tabris.js.app for example), it's useful to get some information about the native client like version, min supported platform version, supported cordova plugins...

**Comment by ralfstx** [comment]
I think those information should be included in our documentation (e.g. in the `cordova.md` section), but they should not be encoded in tabris.js. What would you need them for?

**Comment by ifurnadjiev** [comment]
Quoted from #229:
"Since new features almost always require changes in the native client, we can't be forward compatible. Such a check would require both the native client and tabris.js to expose their version numbers. Anyway, sounds like a good idea to me."
That's exactly what I meant - to have a way to check compatibility between tabris.js and bundled with tabris-js-app native client.

**Comment by ralfstx** [comment]
The native clients provide their own versions and tabris.js compatibility versions internally. All other information should go into the documentation.
