### ISSUE TITLE
Tabris Developers App

### ISSUE THREAD

**Issue by jhay06** [eclipsesource/tabris-js#2258]
hi , hope all is well ,
first of all i want to thank all ofthe developers of the tabris js for their effort in providing us alternative mobile development solution , thank you very much :) 

okay , i just want to ask if the tabris developers app source code is also available publicly? because im looking to all repos but didn't find it.

Why i'm asking :  I want to extend tabris js to other platform not only for android and ios , but also in other linux phones .such as plasma and ubuntu touch (ubports) also on desktop app if possible . 

but i think before i can extend this framework , i think i need to understand first the developers app . 

Thanks

Regards,

**Comment by cookieguru** [comment]
>  i just want to ask if the tabris developers app source code is also available publicly?

It is not

See #2203

**Comment by tbuschto** [comment]
Parts of the tabris framework that are currently open source: 
* [The JavaScript bootscript, native bridge and runtime APIs via the `tabris` npm module](https://github.com/eclipsesource/tabris-js).
* [The API extensions via `tabris-decorators` npm module.](https://github.com/eclipsesource/tabris-decorators/) 
* [The CLI via `tabris-js-cli` npm module](https://github.com/eclipsesource/tabris-js-cli)
* [The documentation](https://github.com/eclipsesource/tabris-js-docs)

Currently not open source (though free as binaries):
* The developer app (TypeScript)
* The native Android platform code (Java/Kotlin)
* The native iOS platform code (objective C/swift)
* Everything related to the build infrastructure.

For clarification: The developer app in the app stores is just a bit of UI that allows one to browse examples or launch another app with the [dev tools](https://docs.tabris.com/3.9/developer-app.html#the-developer-tools). The dev tools are not part of the app but baked in to the native platforms. We could probably open-source the app, but that would not help you much. 

What would be needed to bring tabris to other platforms such as linux is either an android emulation Layer (that actually already works pretty well with the Windows Subsystem for Android), or a complete re-write of the native platform code for that specific platform. The latter would be a massive undertaking. If it was easy we would already have done it. We actually did try do it for the windows universal platform, which was part of Tabris 2.x. However, we were never able to catch up with Android and iOS in terms of features, plus the windows universal platform itself never really got popular, so we discontintued windows support in 3.x.

So if you want to run a tabris app on other platforms, I recommend android emulation. If you are serious about writing a new platform we would of course supports such an effort as much as possible.

**Comment by cookieguru** [comment]
@tbuschto I would say the build infrastructure is very open with https://github.com/eclipsesource/tabris-connect-migration-guide

**Comment by tbuschto** [comment]
Well yeah, I mean the old infrastructure that our paid services are based on.

**Comment by jhay06** [comment]
> Parts of the tabris framework that are currently open source:
> 
> * [The JavaScript bootscript, native bridge and runtime APIs via the `tabris` npm module](https://github.com/eclipsesource/tabris-js).
> * [The API extensions via `tabris-decorators` npm module.](https://github.com/eclipsesource/tabris-decorators/)
> * [The CLI via `tabris-js-cli` npm module](https://github.com/eclipsesource/tabris-js-cli)
> * [The documentation](https://github.com/eclipsesource/tabris-js-docs)
> 
> Currently not open source (though free as binaries):
> 
> * The developer app (TypeScript)
> * The native Android platform code (Java/Kotlin)
> * The native iOS platform code (objective C/swift)
> * Everything related to the build infrastructure.
> 
> For clarification: The developer app in the app stores is just a bit of UI that allows one to browse examples or launch another app with the [dev tools](https://docs.tabris.com/3.9/developer-app.html#the-developer-tools). The dev tools are not part of the app but baked in to the native platforms. We could probably open-source the app, but that would not help you much.
> 
> What would be needed to bring tabris to other platforms such as linux is either an android emulation Layer (that actually already works pretty well with the Windows Subsystem for Android), or a complete re-write of the native platform code for that specific platform. The latter would be a massive undertaking. If it was easy we would already have done it. We actually did try do it for the windows universal platform, which was part of Tabris 2.x. However, we were never able to catch up with Android and iOS in terms of features, plus the windows universal platform itself never really got popular, so we discontintued windows support in 3.x.
> 
> So if you want to run a tabris app on other platforms, I recommend android emulation. If you are serious about writing a new platform we would of course supports such an effort as much as possible.

yes of course i'm very serious to write this to other platform :)

**Comment by jhay06** [comment]
btw what are the repos i need to review to port this to other platform ? thanks

**Comment by tbuschto** [comment]
@jhay06 This is the sourcecode for the `tabris` npm module that communicates with the native code layer: https://github.com/eclipsesource/tabris-js/tree/master/src

The entrypoint is https://github.com/eclipsesource/tabris-js/blob/master/src/boot/main.ts for the bootstrapping and  https://github.com/eclipsesource/tabris-js/blob/master/src/tabris/main.js for the public JavaScript API.
