### ISSUE TITLE
Support hidding elements while excluding them from the layout

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#226]
Setting `visibility` to `false` just hides the element, but does not exclude it from the layout. A feature similar to setting `display: none` in CSS or `GridData`'s `exclude` to `true` in SWT would be useful to hide the element altogether from the layout.

**Comment by cpetrov** [comment]
Alternatively a mechanism to remove the widget from the widget hierarchy could be provided.
@tbuschto

**Comment by tbuschto** [comment]
We should support this in combination with a "previous" keyword (see #545), but leave the existing behavior (for explicit references or ids) as is.

**Comment by tbuschto** [comment]
Windows also has no equal behavior to our "visible" true/false. It's either "visible" or "collapsed" - i.e. excluded from layout, size 0x0.

**Comment by mpost** [comment]
@patrykmol correct me if i am wrong but i think an property to exclude a child from the parent layout does not exist on iOS?

**Comment by tbuschto** [comment]
For now we agree on property name `excludeFromLayout`
