### ISSUE TITLE
Workers not working on Tabris 3.9 android after a local build

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#2267]
### Problem description

Workers don't work after compiling locally on Android
I created a new empty Tabris project (jsx/javascript) and compiled it with just one worker code.
Note also that after compiling in debug mode, the path to the worker is not correct because Tabris adds ./ in front of the src.
When I sideload the code, the onMessage events don't work but the worker path is ok.

### Expected behavior
Working

### Environment

- Tabris.js version: 3.9.0
- Device: Redmi 10 pro, Huawei P10 lite, Lenovo k6
- OS: Android 8, 9, 12

### Code snippet

```js
// Inside index.js

const worker = new Worker('src/worker.js');

worker.postMessage("test");

worker.addEventListener('message', (event) => {

    console.log(event)

});

worker.addEventListener('error', (event) => { 

    console.log(event)

});

// Inside worker.js

"use strict";
global.onmessage = (event)=>{
    
     console.log(event)

};

```

**Comment by ishigo1987** [comment]
Can you please @elshadsm  and @mpost  check this problem ?

**Comment by elshadsm** [comment]
@ishigo1987, thank you for reporting the issue. We will figure it out.

**Comment by elshadsm** [comment]
@ishigo1987, I recommend using the Worker structure from our [worker-script.js](https://github.com/eclipsesource/tabris-js/blob/v3.9.0/snippets/resources/worker-script.js) snippet.

So your **worker.js** should be:
```JavaScript
tabris.onMessage(event => {
    console.log(event)
});
```

Additionally, to take slower devices into account, I suggest adding a small delay before calling the `postMessage` function if you call it immediately after Worker initialization.
```JavaScript
setTimeout(() => worker.postMessage("foo"), 50);
```

**Comment by elshadsm** [comment]
@ishigo1987, additionally, I used your snippet above (applied my recommendations as well) then built a debug app in my local, and everything worked as expected.

If you encounter any path-related issues after compiling, you can check your compiler configuration.

**Comment by ishigo1987** [comment]
This is the contain of my tsconfig.json

```{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "outDir": "./dist/",
    "lib": [
      "es2017"
    ],
    "jsx": "react",
    "jsxFactory": "JSX.createElement",
    "noImplicitAny": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "alwaysStrict": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "allowJs": true,
    "typeRoots": ["node_modules/@types"],
    "skipLibCheck": true
  },
  "include": [
    "./src/**/*.ts",
    "./src/**/*.tsx",
    "./src/**/*.js",
    "./src/**/*.jsx"
, "src/lang/fr"  ]
}

Do i need to change something in order to fix my issue with paths ?

**Comment by cookieguru** [comment]
@ishigo1987 Could you share the solution?

**Comment by elshadsm** [comment]
@cookieguru, it seems that developers may encounter problems when accessing resources located in the `src` folder. Therefore, we recommend moving all resource files from the `src` folder to dedicated `resources/(images, fonts, workers)` directories.
