### ISSUE TITLE
[Question] : AbsoluteLayout

### ISSUE THREAD

**Issue by jhay06** [eclipsesource/tabris-js#2274]
Any one ? how to do it on tabris ? 
setting left to negative is not working it always fall to zero, 

my goal is to overlap a widget to screen , example a circle i want to move half of the circle on left area outside of the visible area of the screen. so only half circle will be shown , how to do it ?

**Comment by ishigo1987** [comment]
@mpost  @elshadsm

**Comment by elshadsm** [comment]
@ishigo1987,

The `ConstraintLayout` is the default layout used by `Composite` and most of its subclasses like `ContentView`. Notably, it offers better responsiveness, adaptability, and performance when compared to `AbsoluteLayout`.

The layout properties (`left`, `top`, `right`, and `bottom`)  must not have negative offset values.

There are multiple methods to achieve this. For example, if you want _"to move half of the circle on left area outside of the visible area of the screen"_, you can update the `transform` as follows:
```JavaScript
circleWidget.transform = {translationX: -100};
```
You can freely choose any `translationX` value.

If you provide a more detailed description of the UI you wish to create, we can recommend using the appropriate Tabris.js widgets.

**Comment by jhay06** [comment]
hi @ishigo1987  , 
will try that transform , 
what i want to achieve is like this 

![image](https://github.com/eclipsesource/tabris-js/assets/5191437/c16d159e-a6d2-44e0-90c4-84f507162497)


thanks

**Comment by jhay06** [comment]
transform is okay will close this now thanks
