### ISSUE TITLE
Use semantic versions

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#229]
Instead of milestones, use [semantic versions](http://semver.org) that are consistent between tabris.js, online documentation and developer app versions. This will make it easier to keep sub-projects in sync.

**Comment by ralfstx** [comment]
My proposal is to use `0.9.0` for the upcoming (M7) version.

**Comment by irbull** [comment]
Do all components use the same version, or do we envision a plan where different develop apps may work with different versions of Tabris.js?

**Comment by ralfstx** [comment]
At least after 1.0.0, I think, the developer app should also be usable with lower versions of tabris.js within the same major version range. Updating the developer app should not require users to update their Tabris.js version.

**Comment by irbull** [comment]
So let's call this 'backwards compatibility'. The Developer App is 'backwards compatible' with Tabris.js (within the same major version range). What about Forwards Compatibility? Does updating the Tabris.js version require an update of the Developer App? 

Should we devise a strategy that informs the user of version mismatch? For example, if you try to use Eclipse 4.3 to launch a 4.4 workspace you get warning dialog saying that Eclipse does not support forward compatibility. Should we print a warning (at least to the console) if the version of the developer app is not compatible with the version of Tabris.js?

**Comment by ralfstx** [comment]
Since new features almost always require changes in the native client, we can't be forward compatible. Such a check would require both the native client and tabris.js to expose their version numbers. Anyway, sounds like a good idea to me.

**Comment by ralfstx** [comment]
The `tabris.js` version is set to `0.9.0` and available in JS via `tabris.version`. The clients will provide the tabris.js version they are compatible with as a property (see #225).

For the version check we've discussed, I've opened #240.
