### ISSUE TITLE
Provide API to obtain display size

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#230]
Could this be another field on `tabris.Display`? One `displaySize` field or two separate fields `displayWidth` and `displayHeight`?

**Comment by ralfstx** [comment]
I'd suggest that the clients add the fields `screenHeight` and `screenWidth` to the `tabris.Device` object. This will allow us to make the size available as `device.screen.height` and `device.screen.width.

**Comment by ralfstx** [comment]
For compatibility, we may want to provide these values as [`window.screen.width`](https://developer.mozilla.org/en-US/docs/Web/API/Screen.width) and [`window.screen.height`](https://developer.mozilla.org/en-US/docs/Web/API/Screen.height) as well.

**Comment by jordiboehmelopez** [comment]
Should this values change on device rotation?

**Comment by ralfstx** [comment]
The question came up whether the properties `displayWidth` and `displayHeight` should take the actual device orientation into account, in other words, whether they are static or dynamic.

The description of [`screen.width`](https://developer.mozilla.org/en-US/docs/Web/API/Screen.width) and [`screen.height`](https://developer.mozilla.org/en-US/docs/Web/API/Screen.height) don't say anything about it, but at least Chrome on Android flips width and height on rotation. I think we should also implement them as dynamic properties - otherwise it's not clear which value should be the width and which one should be the height.

**Comment by ralfstx** [comment]
Implemented as suggested on iOS and Android.
