### ISSUE TITLE
jQuery ajax() post request problem with application/json content type

### ISSUE THREAD

**Issue by jkrause** [eclipsesource/tabris-js#231]
When using jQuery for post requests there seems to be a problem with honoring the contentType. It seems that the data always gets urlEncoded instead of using the encoding specified by the contentType property.

To reproduce:
$.ajax({
    type: "POST",
    contentType: "application/json",
    url: "http://locahost:8080/postToMe",
    data: {"item": "007", "quantity": 5},
}).done(function(response) {
   console.log(response);
)}.fail(function(jqXHR,error,msg) {
  console.log(error + " " + msg);
});

**Comment by cpetrov** [comment]
When passed as an object, data gets URL encoded. To prevent this from happening one should first serialize the object with JSON.stringify(...) or set the processData jQuery Ajax configuration parameter to `false`. From the jQuery documentation:

> **processData (default: true)**
> *Type: Boolean*
> By default, data passed in to the data option as an object (technically, anything other than a string) will be processed and transformed into a query string, fitting to the default content-type "application/x-www-form-urlencoded". If you want to send a DOMDocument, or other non-processed data, set this option to false.
