### ISSUE TITLE
Support different keyboard types for the Text widget

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#232]
Support keyboard types for numbers, emails, urls, etc.

**Comment by mpost** [comment]
We will support the following values for the <code>keyboard</code> property:


* <code>ascii</code>
* <code>decimal</code>
* <code>email</code>
* <code>number</code>
* <code>numbersAndPunctuation</code>
* <code>phone</code>
* <code>url</code>

**Comment by ralfstx** [comment]
@mpost which one is the default, i.e. how to reset the `keyboard` property to its default?

**Comment by mpost** [comment]
The ascii is regular text.
