### ISSUE TITLE
Allow hiding the action bar

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#234]
Allow hiding the action bar of a page.

**Comment by ralfstx** [comment]
dup of #171

**Comment by mpost** [comment]
This is not a dup of #171. Reopening.

**Comment by mpost** [comment]
The solution would allow to set a property that toggles the visibility of the tabris ui elements. We were not sure yet if we wanted to do 1 property or 2 since on iOS the main toolbar and the bottom toolbar can be controlled separately.  In any case the effort is not that much higher.

**Comment by mpost** [comment]
To simplify the story for now we have agreed to create a boolean property <code>toolbarVisible</code> that is <code>true</code> by default. Toggling this property hides the Toolbar on Android and both bars of the navigation controller on iOS.

**Comment by bFlood** [comment]
is this in the nightly build already? thanks

**Comment by mpost** [comment]
@bFlood Not yet.

**Comment by mpost** [comment]
We have added support for android and the tabris.js part. iOS is up next.
