### ISSUE TITLE
Allow creation of TextInput without a border

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#235]
This would allow creating Text widgets which don't inherit the platform-specific Text widget look. E.g. Android Text widgets have a subtle blue border below them and iOS widgets have have a border with rounded corners around them.

**Comment by bFlood** [comment]
+1

**Comment by mpost** [comment]
At least on Android you can set the `background` to null iirc.

**Comment by mpost** [comment]
Relates to https://github.com/eclipsesource/tabris-js/issues/683

**Comment by mpost** [comment]
Closing as covered by: https://github.com/eclipsesource/tabris-js/issues/1686
