### ISSUE TITLE
Allow to extends other types in registerType

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#236]
Support a field `_extends` in `registerType` that allows to base a type definition on another type. The resulting types would not "extend" the referred types, i.e. the super prototype would still be `Proxy`.

This would help us to reduce redundancy in type definitions, e.g. for SearchAction. It will also allow us to replace `registerWidget` with using `_extends: "Widget"` in `registerType`.

**Comment by mpost** [comment]
Does not apply anymore. Widget can now be extended.
