### ISSUE TITLE
API to set tintColor for Actions

### ISSUE THREAD

**Issue by jordiboehmelopez** [eclipsesource/tabris-js#237]
Currently images used in Actions are tinted blue by default.
Images (PNGs) with transparency are used as alpha masks.
It would make sense to provide API to disable or change the tintColor.
The current default behavior prevents us from using a gravatar image as Action.

**Comment by ralfstx** [comment]
Is there a need to have different tint colors within the same application?

**Comment by jordiboehmelopez** [comment]
Hmm... maybe we should close this issue and open a different one:
- Actions have the 'foreground' property which is already used for the text of an action.
- Images on actions are always colored by to operating system with a color, but there seems to be a way to instantiate an image and avoid any other post processing by the system. I must try this out to ensure it does not interfere with image scaling and other requirements.

So in the end maybe a property to disable the default Image tinting should be sufficient if we can control the behavior.

**Comment by ralfstx** [comment]
iOS "tints" images in certain locations such as tool bar items. This feature can be disabled by setting a rendering mode on a per-image basis. There is no such feature on Android.

If we need a way to disable image coloring on iOS, we could introduce a (hidden) image property such as `renderMode="perserve"` or `disableImageColoring=true`. However, that would imply a change on the image format that would also affect Android.

It sounds like a rather special requirement and I wonder if it's the right time to push it.

**Comment by mpost** [comment]
Has been added by now
