### ISSUE TITLE
Implement a version check

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#240]
Incompatible versions of `tabris.js` and the native client may lead to any kind of error or misbehavior that can be very hard to track down. We should detect those cases and print a warning to the console at least.

A mismatch would be defined according to the rules of [semantic versioning](http://semver.org) so that older tabris.js versions could still be used with newer versions of the native client / Developer App, but only within the same major version range.

We need to make sure that this version check will still work even in case of drastic changes in a new major release, such as replacing the native bridge with something different. Holger and me came up with the idea to provide a method `tabris._checkVersion(nativeVersion)` that would be called by the clients before `tabris._start()`.

**Comment by tbuschto** [comment]
tabris._start is called before the actual tabris.js is loaded. NativeVersion could just be a field on the client bridge.

**Comment by ralfstx** [comment]
Setting to high priority, version mismatches between tabris version and developer client are a common source of errors.

**Comment by ralfstx** [comment]
The version check should be as follows

if client major != tabris.js major -> throw error
if client minor.patch < tabris.js minor.patch -> print a warning that some features may not work
