### ISSUE TITLE
Disadvantageous dependence between LayoutData and Z-order

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#242]
Problem: create 2 composites, the second should be layouted under the first composite (it should have a reference to it in its layoutData), and should have a lower z-order than the first composite.

The only way to solve this, is to set the layoutData of composite2 subsequently:

``` javascript
var page = tabris.create("Page", {});

var offset = 20;

var composite2 = tabris.create("Composite", {
  background: "green"
}).appendTo(page);

var composite1 = tabris.create("Composite", {
  layoutData: {left: offset, top: offset, width: 100, height: 100},
  background: "red"
}).appendTo(page);

composite2.set("layoutData", {left: [composite1, -50], top: [composite1, -50], width: 100, height: 100});

page.open();
```

On Android, however, one could create the widgets, then append them in the right order and the references to other widgets would be kept in the layout (example below). On iOS the references are not respected in this case.

``` javascript
var page = tabris.create("Page", {});

var offset = 20;

var composite2 = tabris.create("Composite", {
  layoutData: {left: [composite1, -50], top: [composite1, -50], width: 100, height: 100},
  background: "green"
});

var composite1 = tabris.create("Composite", {
  layoutData: {left: offset, top: offset, width: 100, height: 100},
  background: "red"
});

page.append(composite2, composite1);

page.open();
```

Can an intuitive and cross-platform way be provided to solve this problem?

**Comment by ralfstx** [comment]
The layout code has been completely rewritten meanwhile. The z-index depends on append order, widgets appended later get a higher z-index (it once was the other way around).

Widgets can now be referenced using IDs, which allows referring to widgets before they're created (references to missing widgets are treated as `0`). Layout data are re-eval'ed everytime the list of siblings changes.

This should help to tackle the problems outlined in this issue.
