### ISSUE TITLE
Support npm module "util"

### ISSUE THREAD

**Issue by jkrause** [eclipsesource/tabris-js#244]
Node core modules don't need to be specified as module dependencies. This can lead to runtime errors if modules require core modules.

The node.js core module ```util``` is a pure JavaScript library which works fine with Tabris. We should provide a way to install it.

**Comment by jkrause** [comment]
https://github.com/eclipsesource/tabris-js/issues/267

**Comment by tbuschto** [comment]
## Compatibility
`util` is supported in Tabris.js 1.0 through the `tabris-js-node` compatibility module. Once installed (`npm install tabris-js-node`) and required, the module is available:

    require("tabris-js-node");
    console.log(require("util").format("%d %s", 4000, "seconds"));
