### ISSUE TITLE
Tabris.js util clashes with node.js util module

### ISSUE THREAD

**Issue by jkrause** [eclipsesource/tabris-js#245]
After loading the node.js util module the built in Tabris.js util methods are no longer available.

**Comment by tbuschto** [comment]
With commit 5f3cf7b220103080e3e4f43be20b186a857d1b1c util is no longer placed in the global namespace.

**Comment by jkrause** [comment]
https://github.com/eclipsesource/tabris-js/issues/267

**Comment by tbuschto** [comment]
Works as of commit de28de3201711a247af35b2c4c290552331b01f4, solution was later revised in commit 47bff8daa8d9c74324506b4d51c2efbf0364a92c.
