### ISSUE TITLE
Module loading does not recognize nested node_modules directories

### ISSUE THREAD

**Issue by jkrause** [eclipsesource/tabris-js#246]
When a node module bundles its dependencies in nested node_modules folders those are not read by Tabris.js

/my-project
/my-project/node_modules/
/my-project/node_modules/foo
/my-project/node_modules/foo/node_modules/bar

**Comment by tbuschto** [comment]
This was fixed with commit 0059327426aa2a717c5ae24f41898e6162dd824f.
