### ISSUE TITLE
Split TabFolder tabs and content area into two seperate widgets

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#247]
Currently the TabFolder and its content area is one widget. Having them separated would allow us to do things like animating the tabs independently from the content. Eg. scroll them away with the content or apply a drop shadow under the tabs that separates them from the content.

When separated, we could somehow provide infrastructure so that the Swipe widget can be used as the container for content and allow its position its position to be controlled by the TabFolder tabs widget.

**Comment by ralfstx** [comment]
We have the same pattern in `Page` - the composite is internally created by the framework, Page and composite appear to be a single widget. Do we have similar issues with `Page`?

We should have a consistent API pattern for sub-composites.

**Comment by mpost** [comment]
@ralfstx Yes you are right. The page "suffers" from the same problem. You could also not do things like scroll the nagivation bar away.

**Comment by ralfstx** [comment]
This feature can't be changed in a backward compatible way, and even changing it in a new major version would introduce conflicts that seem unacceptable. *Every* Tabris.js script would need to be rewritten and scripts would become considerably more complex: for every page, tab, scrollview, an additional composite would have to be created.

Therefore I'll close this issue for now, we can revisit this topic later.
