### ISSUE TITLE
Load tabris.js as a module

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#250]
Currently tabris.js is located by the "tabris" entry in a projects package.json, which is not part of any standard. We should load tabris.js as a node-module instead. To do so we need the following.

- tabris.js must be provided in a way that can be installed via npm. While the obvioius solution is to contribute it to npm itself, but it can also be an URL pointing to a git repo or tgz archive.
- The module script needs to be separated from tabris.js and built into the clients themselves.
- The native funtions require by the module system need to be made available before tabris.js is loaded. Either the nativeBridge is installed sooner, or these specific funtions are attached to the Module system itself.
- The startup must be changed to first load the Module script, then call require("tabris"). Everything else should be done by the module system.

**Comment by tbuschto** [comment]
A simple solution to the native bridge loading: Make tabris._start part of the Module script.

**Comment by jkrause** [comment]
https://github.com/eclipsesource/tabris-js/issues/267

**Comment by tbuschto** [comment]
Fixed with commit da05e9f0dd2e68a050b6e423a3084d1bf945ecde.
