### ISSUE TITLE
Order of page.destroy composite.destroy is wrong

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js#253]
Tabris.js differs from Tabris remote in the order the `page.destroy` and `composite.destroy` message are sent after a notify ShowPreviousPage.

Please change the order so that `page.destroy` is sent before `composite.destroy`.

**Comment by ralfstx** [comment]
@jordiboehmelopez agreed?

**Comment by jordiboehmelopez** [comment]
The order of "destruction" should not matter. So, OK for me.
