### ISSUE TITLE
how can i build my app ?

### ISSUE THREAD

**Issue by roysG** [eclipsesource/tabris-js#256]

**Comment by hstaudacher** [comment]
With 0.9 we made progress with our cordova integration (see #74). We put this even further and have support for the cordova CLI. This allows us to use the cordova build infrastructure e.g. `cordova build`. 

This is currently experimental but will be public soon.

**Comment by roysG** [comment]
so for now i just type corodva build, and take the apk ?
and second thing, if i want also install custom cordova plugin such as facebook and etc..
How can i do that ?

**Comment by hstaudacher** [comment]
Like with any other cordova app: `cordova plugin add URL/ID`

But it's not released yet. But this is the way we currently working with it right now.

**Comment by roysG** [comment]
when you say that this is not release you mean that i can׳t use it  ?

**Comment by hstaudacher** [comment]
Yes, not right now.

**Comment by jkrause** [comment]
You can now build an app using the Cordova CLI tools. A detailed instruction is here:

https://tabrisjs.com/documentation/cordova

You need a Cordova platform that contains the Tabris.js runtime.
