### ISSUE TITLE
how can i use in html files and how to load external js ?

### ISSUE THREAD

**Issue by roysG** [eclipsesource/tabris-js#257]

**Comment by ralfstx** [comment]
Tabris.js is a mobile framework that uses native widgets. To include HTML content, use the `WebView` widget. External js files can be included using the module system, e.g. `var external = require("external.js");`

BTW, questions that start with "How can I ..." are better suited for [stackoverflow.com](http://stackoverflow.com).

**Comment by roysG** [comment]
ok thanks.
