### ISSUE TITLE
Snippet/example missing to show different keyboard types for text input

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js#258]
We should have a snippet or example that shows how to use the different keyboard types that can be associated with a text widget.

Especially email and URL types are important on mobile.

The current documentation https://tabrisjs.com/documentation/widget-types#text does not mention this types on the text widget at all.

**Comment by mpost** [comment]
Duplicate of https://github.com/eclipsesource/tabris-js/issues/232

**Comment by ralfstx** [comment]
Right, documentation should be part of #232.
