### ISSUE TITLE
Allow to set focus on TextInput programmatically

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#259]
Setting focus should allow the user to type in a particular text field.

**Comment by ralfstx** [comment]
We didn't manage to address this in 0.9.2. I think that, even though an important feature, it is not release-critical because it's new API that can as well be added after 1.0.

**Comment by wilsonna** [comment]
+1 for this

**Comment by gosia-eclipsesource** [comment]
Closing this as I believe it's a duplicate of #136.
