### ISSUE TITLE
Remove support for modules violating established naming conventions

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#260]
Applications consisting of a lot of modules, especially npm modules, may take a while to load via http due to the high number of different file names a module may have. We already do not support the ".node" extensions, but there are a few more variants we could remove if we make the following assumptions:

- Modules are never files without extension ("./foo" may be "./foo.js", "./foo.json" or "./foo/", but never just "./foo")
- Node modules are always folders ("foo" must be "node_modules/foo/", never "node_modules/foo.js" or "node_modules/foo.json"

**Comment by ralfstx** [comment]
This would limit our compatibility with Node.js based on assumptions that are not made by Node.js itself. Chances are that this reduces the number of npm modules that can be used together with Tabris.js. I don't think that this is the right approach for the problem described.

**Comment by tbuschto** [comment]
Okay, I think there are  better ways to fix it.
