### ISSUE TITLE
Touch listeners should indicate if they consumed the event or not

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js#262]
The function of a touch listener https://tabrisjs.com/documentation/touch-events should have a boolean return value to indicate if the handler consumed an event (true) or not (false).

This is required for the native clients to decide if an event should bubble to any other native listeners or not.

E.g. on a list you want to decide in the touch listener of one element if it reacts on touch (e.g. for a swipe) or not. When the element reacts to the event, scrolling should never be triggered by the same event.

**Comment by ralfstx** [comment]
With our work on gesture support, we decided to try a different approach - the gesture types itself determine the interaction of different gestures, instead of negotiating the precedence programmatically (this is closer to the iOS way).
