### ISSUE TITLE
Docs for ScrollCoposite should explain behavior of empty child composite 

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js#266]
Adding an empty Composite to a ScrollComposite does not show anything. The documentation of ScrollComposite should therefor state explicitly that a defined height (when vertically scrolling) or width (when horizontally scrolling) of the child is required.

See this invalid bug eclipsesource/tabris-android#773 for an example.

**Comment by ralfstx** [comment]
For me the behavior seems obvious. Empty Composites are generally invisible, not only in a ScrollComposite.

We could consider implementing a minimal intrinsic size for empty Composites to provide at least a visual clue for the developer. I'm not fond of this idea as whatever minimal intrinsic we choose would be arbitrary and semantically wrong.
