### ISSUE TITLE
Optimize TextView implementation for iOS, Android

### ISSUE THREAD

**Issue by jkrause** [eclipsesource/tabris-js#270]
Label used to support displaying images as part of the label. With dedicated widgets for ImageView and TextView the implementation can be simplified and made more efficient.

https://github.com/eclipsesource/tabris-js/issues/269

**Comment by ralfstx** [comment]
We already have native TextView implementations on both platforms that support only the required features. Label is not used by Tabris.js anymore. See efc678489f0d4ac1399b0585b80e9a57c9ca229a.
