### ISSUE TITLE
Better support gestures

### ISSUE THREAD

**Issue by jkrause** [eclipsesource/tabris-js#274]
Implementing gestures on top of touch events has problems when the widgets are placed on scrolled areas.

**Comment by ralfstx** [comment]
See also #95

**Comment by tbuschto** [comment]
Proposed protocol API

    bridge.create("tabris.GestureRecognizer", {
      type: "tap" | "swipe" | "pan" | "logpress",
      target: "widget-id",
      duration: number, // delay of longpress
      direction: "top" | "left" | "right" | "bottom", // for swipe,
      fingers: number, // number of required simultaneous touches for this gesture
      touches: number // number of taps for the "tap" gesture to fire
    })

    bridge.listen("gesture", true)

    tabris._notify("widget-id", "gesture", {
      touches: [{x: number, y: number}*],
      ...
    });

**Comment by jordiboehmelopez** [comment]
Will the duration be in milliseconds or seconds?
On iOS the default is `0.5 seconds`.

**Comment by tbuschto** [comment]
milliseconds, updated spec. Defaults could depend on Os.

**Comment by ralfstx** [comment]
Gesture events are now implemented on iOS and Android. See https://github.com/eclipsesource/tabris-js/blob/master/doc/touch-events.md
