### ISSUE TITLE
Introduce orientation:change event

### ISSUE THREAD

**Issue by jkrause** [eclipsesource/tabris-js#276]

**Comment by ralfstx** [comment]
As event name we suggest `orientationchange`. The event parameter should be the new orientation in one of these forms:

- `landscape-primary`
- `landscape-secondary`
- `portrait-primary`
- `portrait-secondary`

where "secondary" stands for upside-down. The names follow an emerging [W3C standard](https://w3c.github.io/screen-orientation/) - credits go to them ;-). See also [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Screen.orientation).

Together with the event, we should also introduce a property `orientation`. Values should be the same. I'm afraid that this may be in conflict with the existing property.

**Comment by mpost** [comment]
@ralfstx Since the payload of a notify is a map you properly imply to use `orientation` as the key?

**Comment by ralfstx** [comment]
Yes, sounds right.

**Comment by jordiboehmelopez** [comment]
When should the event be fired?
a) When the UI is about to begin to rotate
b) When the UI finished rotation

**Comment by ralfstx** [comment]
Since the new orientation should correspond with the updated device.screenWidth/screenHeight properties, I'd say it should be fired when the rotation is finished.
