### ISSUE TITLE
Keep a copy of widget properties on JS side

### ISSUE THREAD

**Issue by jkrause** [eclipsesource/tabris-js#278]
Will reduce the number of context switches between JS and native.

https://github.com/eclipsesource/tabris-js/issues/269

**Comment by tbuschto** [comment]
Rough performance tests estimated about 0.3ms for a get operation right now, and less than 0.01 if we do cache.

**Comment by ralfstx** [comment]
Caching is implemented as of commit 14564ed2c2209943b985dbfaa31d79b3a1bc6ad9 for most properties.
