### ISSUE TITLE
Polish widget events API

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#283]
There are a number of API issue remaining around widget events:
- Missing change events: Why have some properties change events and some not? (#216)
- Missing event arguments: Some evens give arguments (touch, add/remove, ??), though not in a consistent API, some dont. (e.g. #217)
- Events to identify only user-triggered changes (#158)
- Optional: Missing Events: #158, #50

**Comment by ralfstx** [comment]
All referenced issues have been addressed.
