### ISSUE TITLE
Documention on debugging with V8

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#287]
It should be possible to debug Tabris.js application running on Android (V8). We should provide some documentation on how to setup a debugging session. @irbull you did that already - could you share some insights?

**Comment by gosia-eclipsesource** [comment]
Added Ian's blog post about [debugging Tabris.js](http://eclipsesource.com/blogs/2015/04/17/debugging-tabris-js/) on Android to the Articles section in the documentation.
