### ISSUE TITLE
DateTime widget needs to have several initial properties set

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#29]
The snippet below shows what is send when creating a <code>DateTime</code> widget. Especially important are the year, month, day and pattern properties as the widget is empty on android by default.

<pre lang="javascript">
["create", "w20", "rwt.widgets.DateTime", {
  "parent": "w6",
  "style": ["DATE", "MEDIUM", "BORDER"],
  "cellSize": [35, 20],
  "monthNames": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December", ""],
  "weekdayNames": ["", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
  "weekdayShortNames": ["", "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  "dateSeparator": "/",
  "datePattern": "MDY",
  "bounds": [111, 231, 234, 41],
  "children": [],
  "tabIndex": 9,
  "year": 2014,
  "month": 6,
  "day": 9,
  "subWidgetsBounds": [
    [0, 4, 10, 0, 19],
    [4, 4, 10, 0, 19],
    [2, 4, 10, 25, 19],
    [5, 29, 10, 7, 19],
    [1, 36, 10, 25, 19],
    [6, 61, 10, 7, 19],
    [3, 68, 10, 43, 19],
    [7, 202, 0, 30, 39],
    [13, 115, 0, 30, 39]
  ]
}]
<pre>

**Comment by mpost** [comment]
@gosia-eclipsesource You are still correct on the style warning. I have opened #282.

**Comment by jonek** [comment]
The date-time input field has been removed completely from the Tabris.js input example and from Tabris.js altogether.  We should raise the priority to re-introduce this widget(-s) again ASAP. User input of time and date values is quite common.

**Comment by wilsonna** [comment]
Hopefully this will be in the next version as I'm making do with the Picker widget currently :)

**Comment by ralfstx** [comment]
It's high on our list, but it won't yet be included in 1.1. If it helps, there's an experimental version in the [tabris-js-incubator](https://github.com/eclipsesource/tabris-js-incubator) repository that you may use in the meantime.

**Comment by wilsonna** [comment]
Thanks, I'll try it out

**Comment by ralfstx** [comment]
`DateTime` is not part of a Tabris.js release. There are good date/time picker dialogs [available as Cordova plug-ins](http://plugreg.com/search/?q=datepicker). Keeping the selected date/time in a TextView and open a date picker on tap is a common UX pattern and provides a viable alternative to an embedded date/time picker widget.

**Comment by cookieguru** [comment]
As of Tabris.js 2.2.0, the [DateDialog](https://tabrisjs.com/documentation/latest/api/DateDialog.html) and [TimeDialog](https://tabrisjs.com/documentation/latest/api/TimeDialog.html) widgets are available natively.
