### ISSUE TITLE
Make cordova JS API less alien/web-specific

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#291]
Currently most cordova plugins are mapped on either window, cordova (which is fine), or navigator. Navigator is an browser concept that looks alien in our enviroment, and it would be a trivial bit of additional code to copy the additions of cordova to the navigator object to the tabris object.

Compare the two:

        navigator.camera.getPicture(onSuccess);
        tabris.camera.getPicture(onSuccess);

Since tabris is shorter to type than navigator, it's likely that, if well documented, the API would actually be used, even if the navigator object is still present. I realize there is a tiny risk of collision (especially if we introduce more public API to the tabris object - non public API should be prefixed with _), but that can be detected and handled. The risk of specific cordova plugins not working due to missing browser API is actually much greater.

**Comment by hstaudacher** [comment]
Cordova plugins define their own API using clobbers. I think we should not add additional API (mapping) just for the sake of having it on the tabris object.

**Comment by ralfstx** [comment]
I agree that `navigator.` is a weird entrypoint for API to access native features. However, that's the design of a cordova plug-in, not our's.

By copying these fields to the `tabris` object, we'd create the impression that Tabris would take over responsibility for this API–which we do not intend.

**Comment by tbuschto** [comment]
We don't have to introduce new API. And we have no more or less responsibility for additional objects on the tabris object than browser have for the navigator object.

**Comment by ralfstx** [comment]
I think the prevalence of the Web API makes the difference. For issues with `navigator.camera.getPicture()`, chances are that you can find existing solutions on the Web. When there is a problem with `tabris.camera.getPicture()`, developers will turn to us.

**Comment by ralfstx** [comment]
We've discussed this proposal again and agreed that, although the `navigator` object doesn't make a lot of sense in a mobile app, and it's a weird parent for objects like `camera`, this is actually a problem of Cordova, or the respective Cordova plug-ins and not of Tabris.js. We should not try to fix it.
