### ISSUE TITLE
Change navigation menu background

### ISSUE THREAD

**Issue by calebeaires** [eclipsesource/tabris-js#292]
Is there any way to change navigation menu background color? Change style from pages slide menu and navigation will give us power on customization.

**Comment by ralfstx** [comment]
It's not yet documented, but you can use `tabris.ui.set("background", color)`.

**Comment by mpost** [comment]
The slide in navigation menu is no affected by the tabris ui background color. On android you can choose between a light and dark color scheme but you can not apply any styling programmatically. I'd rather think this is a duplicate of https://github.com/eclipsesource/tabris-js/issues/203

**Comment by ralfstx** [comment]
Sorry, I misunderstood the question.

Yes, the background will be customizable as part of #203.
