### ISSUE TITLE
Create a "controls demo" as one further example

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js#295]
We should have one example that acts as our "controls demo".
It should cover all widgets supported by Tabris.js.
It should show one widget per page.
Show multiple variations per page where it makes sense (different colors, layouts, ...).
Keep it simple! It should only act as a visual index to our widgets.

Maybe reuse the snippets here?

**Comment by hstaudacher** [comment]
Would be useful. I like this kind of demo: http://getbootstrap.com/components/

It has the documentation combined with the components

**Comment by jonek** [comment]
I do not think we should mix documentation and visual index in that example.

Had in mind something like this: https://www.polymer-project.org/components/paper-elements/demo.html

**Comment by mpost** [comment]
We have the snippets that are reasonably well maintained and serve a similar purpose. Closing this for now.
