### ISSUE TITLE
No events fired when property is changed programmatically

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js#297]
There are three cases in which a widget in Tabris.js could possibly fire an event:
1. creation of the widget while explicitly setting a property that has an associated change event
2. programmatically setting a property which has an associated change event
3. user interaction

Example for case 1:
```javascript
tabris.create("RadioButton", {
  text: "foo",
  selection: true
}.on("change:selection", function() { ... }).appendTo(page);
```
Here I would expect the event not to be fired, because the selection property is set before the listener is attached.

Example for case 2:
```javascript
var foo = tabris.create("RadioButton", {
  text: "foo"
}.on("change:selection", function() { ... }).appendTo(page);
foo.set("selection": true);
```
Here I would expect the event to be fired and thus the listener to be executed when the second line sets the selection property programmatically.
Currently this example **does not fire an event**. At least the listener is not executed. Although, the state of the button changes correctly.

What is to be expected in the following cases?
```javascript
tabris.create("RadioButton", {
  text: "foo"
}.on("change:selection", function() { ... }).set("selection", true).appendTo(page);

tabris.create("RadioButton", {
  text: "bar"
}.on("change:selection", function() { ... }).appendTo(page).set("selection", true);
```
I would suspect both of them to be equivalent to the second example.

I would also expect that all other widgets in Tabris.js that have properties with associated change events to behave consistently. Examples for such properties are: ```TextInput.text```, ```ToggleButton.selection```, ```CheckBox.selection```. Is this correct?

**Comment by tbuschto** [comment]
I agree with everything. Issues #215 and #216 also deal with this.

**Comment by tbuschto** [comment]
Fixed. See also #215.
