### ISSUE TITLE
Rename Composite widget to Container

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#298]
We should choose widget names that are close to the mobile concepts and APIs. The name `Composite` is used in SWT and GWT only. `Container` seems to be a more [common name](https://en.wikipedia.org/wiki/Graphical_control_element#List_of_common_generic_widgets) for widgets that contain other widgets.

In Android, [ViewGroup](https://developer.android.com/reference/android/view/ViewGroup.html) is the base class for container views. On iOS, there are [Container View Controllers](
https://developer.apple.com/library/ios/featuredarticles/ViewControllerPGforiPhoneOS/CreatingCustomContainerViewControllers/CreatingCustomContainerViewControllers.html).

If we change it, we should also rename `ScrollComposite` to `ScrollContainer`.

**Comment by jordiboehmelopez** [comment]
In iOS, everything (with a few exceptions) is a `UIView`. Each UIView can have subviews - so every widget/control is automatically also container! [UIView Documentation](https://developer.apple.com/library/ios/documentation/WindowsViews/Conceptual/ViewPG_iPhoneOS/CreatingViews/CreatingViews.html#//apple_ref/doc/uid/TP40009503-CH5-SW1)
"Container View Controllers" are more comparable to the Tabris UI Pages...

**Comment by tbuschto** [comment]
+1 for Container

**Comment by hstaudacher** [comment]
So it seems more that "View" is common in mobile frameworks and not "Container", right?

**Comment by ralfstx** [comment]
It seems that `View` is a common name for any kind of widget (TextView etc.). The Container is actually a layout container (which is a standard term). I thought that if we introduce alternative layout containers, `FlexContainer`, `GridContainer`, etc. would be good names.

We could also think about `ContainerView`, but then again - would `ScrollContainerView` sound right?

**Comment by hstaudacher** [comment]
To sum up a recent discussion one solution could be:

* Rename "Widget" to "View" (in docs)
* Rename Composite to "{LAYOUT}View" were {LAYOUT} should describe wha tour current layout does.
* Rename "ScrollComposite" to "ScrollView"
* Add views for other layouts e.g. "FlexView", "GridView"

**Comment by hstaudacher** [comment]
Maybe one way to find a name for the current layout is to think about the children. I'm not sure but in a Grid and Flex Layout the children will not define their "LayoutData" in the way our current layout works. Maybe they define an offset or similar things but not as detailed as it is in out current layout.

**Comment by ralfstx** [comment]
Since Composite has become API in 1.0, we should not rename it now.
