### ISSUE TITLE
Add property to change TextInput message text color

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js#301]
`TextInput` inherits the `foreground` and `background` properties from `Widget` but lacks a property to set the color of the `message` text which should differ from the `foreground` color.

**Comment by ralfstx** [comment]
How about supporting `messageTextColor` next to `textColor`?

**Comment by mpost** [comment]
Closing this in favor of https://github.com/eclipsesource/tabris-js/issues/875
