### ISSUE TITLE
Support Cordova plugins that respond via JavaScript

### ISSUE THREAD

**Issue by jordiboehmelopez** [eclipsesource/tabris-js#304]

**Comment by jordiboehmelopez** [comment]
Currently we assume that a cordova plugin communicates back to the application code using the native `CDVPluginResult`. Some plugins don't do that. They directly call the JavaScript counterpart: `cordova.callbackSuccess(...)`.

This leads to code being executed that might generate `set` operations which are not flushed. Flushing of operations only happens when the JavaScript VM is entry via the "_notify" function.

**Comment by tbuschto** [comment]
The solution would be to add a "tabris.trigger("flush");" to every code that cordova executes directly

**Comment by jordiboehmelopez** [comment]
In the native client (at least on iOS) there is only one way to re-enter the JavaScript VM for direct code execution. The client could then, after it executed the cordova plugin js code, execute this additional line.

**Comment by ralfstx** [comment]
So far we made the assumption that UI code can only be executed inside `_init` or `_notify`. Those assumptions make it easier to reason about the system.

How about providing a separate entrypoint for UI code for this kind of cordova plug-ins? Alternatively, would it also be possible for the client to trigger some kind of `_notify` after the JS code has executed?

**Comment by jordiboehmelopez** [comment]
We can trigger anything after the code has been executed.
This can be a `_nofity` or `flush`.

There seems to be only one way for Cordova plugins to execute JavaScript code in the VM by themselves:
By calling `- (NSString *)stringByEvaluatingJavaScriptFromString:(NSString *)script` on `UIWebView` - which we replace with our own implementation (a proxy) to be able to forward the call to our JavaScript VM.

**Comment by tbuschto** [comment]
Our preferred way would be to trigger an event (e.g. "refresh" on the tabris.ui instance) using nativeBridge.notify after the script execution.

**Comment by jordiboehmelopez** [comment]
OK. An event is now fired: tabris._notify("tabris.ui", "refresh", {} );
... and it works as expected!

**Comment by ralfstx** [comment]
Since the `flush` event is already triggered in `tabris._notify`, we don't need any special implementation on the JS side.
