### ISSUE TITLE
setTimeout fails when called without delay

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#305]
The reason for the error is, that the example uses jquery which calls: "setTimeout(jQuery.ready)" without a second parameter which is accepted by the browsers. On the client we just receive `undefined` and log an error.

![device-2015-02-27-110747](https://cloud.githubusercontent.com/assets/73655/6410597/f1a38750-be70-11e4-933e-5686260a6683.png)

**Comment by tbuschto** [comment]
We should support the HTML5 timer API, as described by the W3C:
http://www.w3.org/TR/2011/WD-html5-20110525/timers.html

This includes making the delay optional (defaults to 0), supporting additional argumetns to pass to the callback, and some details regarding the handling of invalid/unsupported parameters.
