### ISSUE TITLE
Cordova error Object.cordovaBridge.exec

### ISSUE THREAD

**Issue by calebeaires** [eclipsesource/tabris-js#312]
Tabris 0.9.2 and Cordova is not working together

![screenshot_2015-03-02-14-37-06](https://cloud.githubusercontent.com/assets/794195/6446447/05085174-c0ea-11e4-84d8-58beb8d4192f.png)

**Comment by hstaudacher** [comment]
Hey, I think this is because you are using a 0.9.1 client. Can you check it in the about of the developer app? 

The 0.9.2 apps are submitted to apple for review. Probably it's done by end of the week.

**Comment by jonek** [comment]
@calebeaires The apps are now in the store. Could you check them out?

**Comment by hstaudacher** [comment]
I think this can be closed now. Please reopen if the error still occurs.
