### ISSUE TITLE
Support "key" method and "length" property in localStorage

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#313]
To do so we would need to introduce new native API. I propose to introduce native calls of the same names ("key"), ("length").

It would also nice to support the storage events, but i think we can do so without native support.

**Comment by frh3ddy** [comment]
any idea when this methods will be supported?

**Comment by mpost** [comment]
@frh3ddy There is no ETA just yet but thanks for bringing it up again.

**Comment by tbuschto** [comment]
Fixed in 9efa673ea92dbb89888d92f07676e9e5017827ca
