### ISSUE TITLE
Remove support for animation progress event

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#319]
Basically, the progress event in iOS is useless, it neither gets you the current values of the animated properties (they are at their destination value), nor can we provide an progress value (0-1 after easing). We should re-write the tray demo and then remove support for the progress event.

**Comment by ralfstx** [comment]
+1 to remove the progress event. Progress information is not available on iOS, so any intermediate values we'd provide in the event would be just guessing.
