### ISSUE TITLE
Add widgets to navigation Drawer

### ISSUE THREAD

**Issue by paulocarvalhodesign** [eclipsesource/tabris-js#320]
First of all really nice piece of software.
Only started yesterday playing with it.
Would like to understand how to customize the navigation drawer items, add a icon next to it and add image widget to it, is this possible?

P.

**Comment by ralfstx** [comment]
Thanks, glad that you like it!

At the moment, the drawer is built-in and cannot be customized. However, we're reworking this component and plan to make it customizable soon (#203).

**Comment by kheff** [comment]
I am new to tabris-js but i really like it..I kindly request to know how i can customize the width and height of my drawer widget.Nice time

**Comment by cookieguru** [comment]
@kheff What do you mean by customize the height of the drawer?
