### ISSUE TITLE
BackgroundImage property not working on page widget on android

### ISSUE THREAD

**Issue by paulocarvalhodesign** [eclipsesource/tabris-js#321]
Hi, background image property works fine on ios but seems to fail on android.

function home(){
  		var page = tabris.create("Page", {
        title: "Home",
        topLevel: true,
        background:"#487898",
     // fails == backgroundImage: tool.imageTools(6),
        foreground: '#fff',
     //works ==   image: tool.imageTools(1),
        style: ["FULLSCREEN"]

    });

**Comment by mpost** [comment]
Thanks for reporting the issue. Setting the backgroundImage does indeed not work as expected and will be fixed in the next release.

**Comment by paulocarvalhodesign** [comment]
cool , looking forward for next release.

**Comment by mpost** [comment]
Fixed in 0.9.3.
