### ISSUE TITLE
How to define border

### ISSUE THREAD

**Issue by calebeaires** [eclipsesource/tabris-js#322]
I have tried to use border on CollectionView, but I have no success

**Comment by mpost** [comment]
Could you please elaborate what you mean by border? Are you referring to dividers between items? If so, they need to be part of the items themselves.

**Comment by calebeaires** [comment]
I mean: one line-border between itens. I have did it inside initializeCell


```
tabris.create("Composite", {
                layoutData: {
                    left: 0,
                    bottom: 0,
                    right: 0,
                    height: 1
                },
                background: "#e3e3e3"
            }).appendTo(cell);


```
