### ISSUE TITLE
No way to define activity background color on android.

### ISSUE THREAD

**Issue by paulocarvalhodesign** [eclipsesource/tabris-js#324]
Hi guys.
As far as I can see, there is no way to define background color/image on the main activity.
The side effect from this is that on page change on android you always the background of the activity when changing page for a few miliseconds.
Would be nice to be able to define this.
P

**Comment by mpost** [comment]
You can set the `background` of a page to a certain color. When you rotate the device you will not see the default background (white) of the underlying activity.

If you want to change the white default background of your app you would currently need to extend one of the tabris bundled android themes and set the `windowBackground` value.

For more details see https://tabrisjs.com/documentation/cordova#preferences

**Comment by paulocarvalhodesign** [comment]
yes did thought that would be the case, where are the theme files located, I cant find it, not much experience with android stuff, would be great if you could point me :)

**Comment by mpost** [comment]
if you see the activity background when your page has a background color of its own, that this would be a bug. From my test that does work though. Here is an example:

<pre lang="javascript">
var page = tabris.create("Page", {
  title: "Background color",
  topLevel: true,
  background: "red"
});

page.open();
</pre>

For a quick trial just through it in the scratchpad on tabrisjs.com and tell me if ti works or not. :)

**Comment by paulocarvalhodesign** [comment]
yes that works fine, the issue is :

var page = tabris.create("Page", {
  title: "Background color",
  topLevel: true,
  background: "red"
});

var page2 = tabris.create("Page", {
  title: "Background color 2",
  topLevel: true,
  background: "red"
});

page.open();
page2;

on android you will notice that on page switch you will see a white background behind the fading in new page.
That white is the activity background color.
Would be great to be to define that either with color or image

**Comment by paulocarvalhodesign** [comment]
I don't think its a bug , think is the theme bundled like you said before, would be awesome to be able to override that with config values added to config.xml .

**Comment by mpost** [comment]
yeah i see what you mean. during the animation where the page scales you see the background. That would be a case where you would want to colorize the activity background (and all pages with it).

In the cordova build you could use the build hooks to copy your custom android theme into the final build output. https://github.com/apache/cordova-lib/blob/master/cordova-lib/templates/hooks-README.md

Having a subset of theme properties directly in the config.xml is something we have considered as well. We haven't done any work in that direction yet though.

**Comment by paulocarvalhodesign** [comment]
yeah,  not a bug,  but an improvement in my opinion.
I will give the hooks a try and see if I can come up with a solution for this.

**Comment by paulocarvalhodesign** [comment]
is this worth labelling as new feature or something similar?

**Comment by mpost** [comment]
Feel free to open a feature request for it.

**Comment by mpost** [comment]
With the release of Tabris.js 1.1 we added advanced theming capabilities to the Android client: http://eclipsesource.com/blogs/2015/07/03/tabris-js-1-1-sneak-peak-custom-themes-on-android/

You can use it to style the windows background as well. I will close this issue for now. Please reopen if you feel it doesn't address your needs.
