### ISSUE TITLE
Is there some event fired on back button navigation?

### ISSUE THREAD

**Issue by calebeaires** [eclipsesource/tabris-js#325]
Need to clear thins on back button on SearchAction. Is there some event fired on back button navigation?

**Comment by mpost** [comment]
Currently we don't have api for it. It is on our list of todos though.

**Comment by paulocarvalhodesign** [comment]
I think you can handle back button via cordova .

**Comment by ralfstx** [comment]
`backbutton` is one of the [Cordova built-in events](https://cordova.apache.org/docs/en/4.0.0/cordova_events_events.md.html), that is, it is not available in a Cordova plug-in. We have to provide it.

**Comment by calebeaires** [comment]
Cool feature!

**Comment by calebeaires** [comment]
This feature will help us control many behavior on navigation!

**Comment by calebeaires** [comment]
I have found on solution:

```
// Create an Favor Action. It will show on all pages, except the Favor Page
tabris.create("Action", {
    title: "Favor",
    image: "images/star-25.png",
    id: "favorAction",
    visible: true
}).on("select", function() {
    app.favor(); // open the page favor
});

// On page change, check if it is on Favor Page, if yes, dont show Favor Action
tabris.ui.on('change:activePage', function(ui, page) {
    if (page.get('title') == "Favor" ) {
        tabris.ui.find('#favorAction').set('visible', false);
    }
});
```

**Comment by ralfstx** [comment]
Good. Alternatively, you could also listen on the `appear` event in your page.

**Comment by josiahking** [comment]
How can i capture event for the navigationView back icon action on click?

**Comment by mpost** [comment]
@josiahking You can not intercept that event on the navigationview. You can however listen to appear and disappera events on the pages you are showing.
