### ISSUE TITLE
Provide a convenience API to get the value of the selected radio button

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#326]
Using the jQuery selector API one would execute:

``` javascript
$('input[name=radioName]:checked', '#myForm').val()
```

Swing:

``` java
ButtonGroup buttonGroup = ...
ButtonModel buttonModel = buttonGroup.getSelection();
```

**Comment by paulocarvalhodesign** [comment]
Hi, I am wrong by pointing out that :
https://github.com/eclipsesource/tabris-js/blob/master/examples/input/input.js

demonstrates  how got get the value of the selected radio button?

**Comment by cpetrov** [comment]
Sorry, the title may have been misleading. I have updated it now.

**Comment by tbuschto** [comment]
How about that:

    page.children("RadioButton[selection=true]").first().get("text");

**Comment by ralfstx** [comment]
Looks like the obvious syntax. If we could make this available for all widget properties, this would be a powerful addition to the selector API.

**Comment by tbuschto** [comment]
Closed in favor https://github.com/eclipsesource/tabris-js/issues/1688
