### ISSUE TITLE
Differents Action by navigation/page

### ISSUE THREAD

**Issue by calebeaires** [eclipsesource/tabris-js#329]
Is there an way to create different Action for each navigation/page. When I created an action on subpage, then goes back to the early page, the action persist on navigation.

Found this solution https://github.com/eclipsesource/tabris-js/issues/8

**Comment by ralfstx** [comment]
Currently, all Actions are global. If you want to show them selectively, you need to toggle their visibility as shown in #8.

Anyway, I'm not sure I understand your requirements correctly. If this is a feature request that is not covered by support for page actions, could you please describe the requested feature in more detail?
