### ISSUE TITLE
Add support for ClientDevice service

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#33]
The <code>com.eclipsesource.tabris.device.ClientDevice</code> allows a user to get various details about the device running the app.

These details are exposed via a regular service but the mechanism to obtain these infos differs from other services. In Tabris remote we send all these infos on the first POST request. Example:

<pre lang="javascript">
["set", "tabris.Device", {
  "orientation": "PORTRAIT",
  "model": "Nexus 5",
  "osVersion": "4.4.4",
  "vendor": "LGE",
  "scaleFactor": 3.0,
  "connectionType": "WIFI",
  "timezoneOffset": -120,
  "capabilities": ["PHONE", "MESSAGE", "LOCATION", "CAMERA", "MAPS"]
}]
</pre>

The best way to deal with that is properly to query this data in the fly as with other services. Opinions?

**Comment by tbuschto** [comment]
We now have a device object supportting most of these, but not orientation (which would also require an event.)

**Comment by tbuschto** [comment]
See #276

**Comment by ralfstx** [comment]
We've introduced the `device` object with properties `model`, `platform`, `version`, `language`, `scaleFactor`, and `screen`. Additions should go into separate issues.
