### ISSUE TITLE
Make selection feedback configurable in CollectionView

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#330]
CollectionView items change the background color on selection. Not all mobile applications have this feature. I'm not even sure if it's a good default to have as not all CollectionView items have a selection behavior. At least on iOS, this highlight color can visually interfere with `highlighOnTouch` on child widgets as it has a slightly different timing.

Currently the highlighting can be suppressed by setting an explicit background color on the cell. I think we should rather have a property to enable this behavior explicitly, e.g. `showSelection: true|false`.

Should we also make the selection color configurable?

**Comment by mpost** [comment]
The highlight is now provided on the cell or its content.
