### ISSUE TITLE
Is it possible to lock orientation?

### ISSUE THREAD

**Issue by paulocarvalhodesign** [eclipsesource/tabris-js#332]
Hi guys, is it possible to lock orientation, the config.xml parameter seems to be ignored.
If this not this would be a good improvement.

**Comment by hstaudacher** [comment]
Not out of the box. But what about this? https://github.com/cogitor/PhoneGap-OrientationLock

**Comment by paulocarvalhodesign** [comment]
ha, that is a good find :)

**Comment by ralfstx** [comment]
@paulocarvalhodesign please re-open this issue if you notice problems with this approach.

**Comment by mpost** [comment]
@paulocarvalhodesign Did the plugin help you with the orientation lock?

**Comment by paulocarvalhodesign** [comment]
Will try to implement it tonight after work.
Ill report back to you guys .

**Comment by paulocarvalhodesign** [comment]
Works great.
Not tested in IOS

**Comment by mpost** [comment]
@paulocarvalhodesign Good to hear. :)
