### ISSUE TITLE
Support npm module "chart.js"

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#336]
Chart.js 1.0.2 calls following code to compute canvas size:
```javascript
document.defaultView.getComputedStyle(element).getPropertyValue(dimension);
```

`document.defaultView` and CSS-related `window` methods are not supported by Tabris.js.

**Comment by paulocarvalhodesign** [comment]
Ha yes I was trying this and found the same error.

**Comment by tbuschto** [comment]
Chart.js 1.0.1 is comptaible with Tabris.js 0.9.3

**Comment by paulocarvalhodesign** [comment]
This code does not render that chart.

var Chart = require("chartJs/chartjs.min.js"); // in node-modules folder version 1.0.1


var page = tabris.create("Page", {
    title: "Dashboard",
    topLevel: true,
    background:"#dedede"
});


var pieData = [
    {
        value: 300,
        color: "#F7464A",
        highlight: "#FF5A5E",
        label: "Red"
    },
    {
        value: 50,
        color: "#46BFBD",
        highlight: "#5AD3D1",
        label: "Green"
    },
    {
        value: 100,
        color: "#FDB45C",
        highlight: "#FFC870",
        label: "Yellow"
    },
    {
        value: 40,
        color: "#949FB1",
        highlight: "#A8B3C5",
        label: "Grey"
    },
    {
        value: 120,
        color: "#4D5360",
        highlight: "#616774",
        label: "Dark Grey"
    }
];
var canvas = tabris.create("Canvas", {
    layoutData: {left: 10, top: 160, right: 10, bottom: 10}
}).appendTo(page);

var createCanvasContext = function() {
    var bounds = canvas.get("bounds");
    var width = bounds.width;
    var height = Math.min(bounds.height, width);
    return tabris.getContext(canvas, width, height);
};

var ctx = createCanvasContext();
// workaround for scaling to native pixels by chart.js
ctx.scale(1 / window.devicePixelRatio, 1 / window.devicePixelRatio);
new Chart(ctx)[ 'Pie' ](pieData, {
    animation: false,
    showScale: true,
    showTooltips: false,
    scaleShowLabels: true
});

is anything wrong here, or does chart js not working atm.

**Comment by paulocarvalhodesign** [comment]
console.log(JSON.stringify(bounds));

returns  {"left":0, "right":0, "width":0, "height":0}

This is on android.

**Comment by mpost** [comment]
The bounds you "get" are 0,0 because the ui has not been layed out yet. Wrap the part in a "change:bounds" callback as can be seen here: https://github.com/eclipsesource/tabris-js/blob/master/examples/canvas/animation.js#L18

**Comment by mpost** [comment]
Ups. Didn't mean to close the issue. :)

**Comment by tbuschto** [comment]
I will close this, since 1.0.1 works. To support 1.0.2 we should create a separate issue.
