### ISSUE TITLE
Longer page titles may not fit in the PageSelector

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#338]
Reproducible in the page snippet.

The title text shown in the drawer could be truncated with ellipsis and/or a mean to set alternative page title to display in the drawer could be provided.

**Comment by ralfstx** [comment]
Exceeding page titles are meanwhile truncated with an ellipsis on iOS and Android. On Windows, they're cut off.

**Comment by mpost** [comment]
This issue should be closed since the `PageSelector` has been removed in Tabris.js 2.0

**Comment by ralfstx** [comment]
Right, I thought it was about page headers, but it's actually about PageSelector, so let's close it. The cut off page headers on Windows are really not a big deal.
