### ISSUE TITLE
Footer and sub-header widgets

### ISSUE THREAD

**Issue by calebeaires** [eclipsesource/tabris-js#343]
Is there already some footer and sub-header widget?

**Comment by paulocarvalhodesign** [comment]
Tabris will use on android the defined theme and on ios default behaviour.
I don't think that that concept, very common in hybrid apps frameworks like ionic comes into play with Tabris.
You can however have your pages fullscreen and add a composite at top and another at the bottom, and effectively create you header and footer.
Someone correct me if I am wrong here.

**Comment by calebeaires** [comment]
I have tried that, but had no success. Did you? If yes, which setup did you use?

**Comment by paulocarvalhodesign** [comment]
you can : 

var page = tabris.create("Page", {
             title: "Login",
             topLevel: true,
             background: 'rgba(1,1,1,0.6)',
             foreground: '#fff',
             style: ["FULLSCREEN"]

         });

 var headerComposite = tabris.create("Composite", {
             layoutData: {left: 0, top: 0, right: 0, height:50},
             background: 'green',
             opacity: 1
         }).appendTo(page);

var footerComposite = tabris.create("Composite", {
             layoutData: {left: 0,  right: 0, bottom: 0, height:50},
             background: 'red',
             opacity: 1
         }).appendTo(page);

give that a go

**Comment by calebeaires** [comment]
Did it. I get it done. Very thanks!

**Comment by paulocarvalhodesign** [comment]
cool, you may want to close this issue.
