### ISSUE TITLE
CollectionView: provide current item and index cell properties

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#344]
In order to delete an item on user interaction, the index of that item is required. Currently, the only way of getting this index is to store the item in the `itemchange` event and to call `indexOf()` on the CollectionView's `items` property. The index provided as second parameter to `itemchange` is not stable, in case of inserting or removing items, the index of a visible cell can change without the item changing.

We should provide both `item` and `index` as properties of a Cell, both with proper change events. The index would need to change when preceding items are deleted or inserted.

**Comment by tbuschto** [comment]
@ralfstx How should that be implemented? Adjusting all index properties of all cells by adding/subtracting the number of inserted/removed items? This seems an unjustifiable amount of delicate code when the application code could simply use indexOf when it actually needs the index.

**Comment by ralfstx** [comment]
An `itemIndex` property has been introduced in commit 9bf06d989979441341b78ae4d38f1d7170cf7ccc
