### ISSUE TITLE
CollectionView item selection feedback not always shown

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#345]
Item selection feedback is not shown when cells (or overlying composites) have set background.

**Comment by mpost** [comment]
On Android we actually place a "darkend screenshot" of the view on top of it. But when transforming the original view the "hightlight" view is not transformed. A better solution would be to use the standard android selectable background (with the ripple effect). An approach to integrate that onto a custom view can be found here: https://gist.github.com/chrisbanes/9091754. The drawback is that it has to be added on each widget individually. But i'd think if we would have it on Composite, ImageView and TextView we would be much better off than now.

**Comment by cookieguru** [comment]
Selection feedback is now shown based on whether the Cell's element(s) have enabled it, regardless of background.

**Comment by mpost** [comment]
Closing issue as resolved in 3.x. Please reopen if you have any more problems.
