### ISSUE TITLE
Provide a more flexible selection feedback mechanism

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#346]
Selection feedback/highlightOnTouch effect currently only appears and stays when touching and holding on the item to be selected. Moving the finger cancels the effect. This prevents continuously showing selection feedback while swiping items in a CollectionView using the `pan` listener in a swipe to dismiss scenario. Providing a way to change the color of the selection feedback can also make it possible to fit the app theming requirements.

**Comment by mpost** [comment]
On Android we actually place a "darkend screenshot" of the view on top of it. But when transforming the original view the "hightlight" view is not transformed. A better solution would be to use the standard android selectable background (with the ripple effect). An approach to integrate that onto a custom view can be found here: https://gist.github.com/chrisbanes/9091754. The drawback is that it has to be added on each widget individually. But i'd think if we would have it on Composite, ImageView and TextView we would be much better off than now.

**Comment by mpost** [comment]
Resolved via https://github.com/eclipsesource/tabris-js/issues/714 on Android 6.0 and up.
