### ISSUE TITLE
Cordova Admob Pro bug on tabris android platform

### ISSUE THREAD

**Issue by calebeaires** [eclipsesource/tabris-js#353]
When using cordova-admob-pro plugin with tabris.js and after some seconds the app loads, it breaks and show the message "... stoped".

How can I get more bugs logs details to give the plugin author some idea on whats is happing. I have posted this problem here: https://github.com/floatinghotpot/cordova-admob-pro/issues/104

**Comment by jonek** [comment]
Did you build your app with debugging support (the default)? Then you should be able to attach your Android device to Android Studio or you can use "adb logcat" on the command line. Both tools are able to show you the log-message of your device.

cordova-admob-pro seems to depend on a webview which is not available in Tabris.js.

**Comment by calebeaires** [comment]
I searched to an admob plugin that has no link with webview, but havent found!

**Comment by jonek** [comment]
To display banner adds with admob in Tabris.js a custom Cordova plugin would be required that interacts with the native UI created by Tabris.js. Currently we do not provide functionality to build such custom plugins.

**Comment by jonek** [comment]
We have plans to provide some extension mechanism to Tabris.js in the future. The mechanism should enable developers to use native libraries to add functionality that could also interact with Tabris.js' native UI.

**Comment by jonek** [comment]
@calebeaires Have you considered using [AdSense](https://www.google.com/adsense/start/) directly in a Tabris.js [WebView](https://tabrisjs.com/documentation/0.9/widget-types#webview) widget that you embed in your UI?

**Comment by calebeaires** [comment]
We cant. Admob/Adsense team told me using directly on a mobile-webview is a Google adsense policy violation.

**Comment by jonek** [comment]
@calebeaires Is it possible for you to switch to another ad service until we can provide support for Admob directly?

**Comment by calebeaires** [comment]
Maybe yes, but Admob is not a service from Adsense alone. It is a Mediation from others: Flurry, MobFox, AdSense, etc. My experience is that Adsense/AdMob is the best choice. Admob with Adsense give me a better revenue.

**Comment by jordiboehmelopez** [comment]
I fixed a few small issues in the **iOS** cordova-project-template and got the AdMob-pro plugin to work.
The changes will be available with Tabris.js version >= 0.9.5.

This is what you will have to do to use AdMob in the future:

* If use with Cordova CLI:
```bash
cordova plugin add com.google.cordova.admob
```

* If use with PhoneGap Buid, just configure in config.xml:
```javascript
<gap:plugin name="com.google.cordova.admob" source="plugins.cordova.io"/>
```

This is the JavaScript code used for the example:
```javascript
var page = tabris.create("Page", {
  title: "Cordova",
  topLevel: true
});

var button = tabris.create("Button", {
  text: "Show Ad",
  layoutData: {
    centerX: 0,
    top: 0
  }
}).appendTo(page);

var textView = tabris.create("TextView", {
  font: "16px",
  layoutData: {
    centerX: 0,
    top: [button, 24]
  }
}).appendTo(page);

button.on("select", function() {

  AdMob.createBanner({
    adId: "ca-app-pub-xxxx/xxxx",
    position: AdMob.AD_POSITION.TOP_CENTER,
    autoShow: true
  });
```


This is the result:
![bildschirmfoto 2015-04-08 um 13 49 13](https://cloud.githubusercontent.com/assets/61378/7044659/24768d04-ddf6-11e4-99fb-7e2488a6a829.png)

**Comment by calebeaires** [comment]
Cool. We are moving!

I will take a look more closely. Does it works on Android too?

**Comment by calebeaires** [comment]
Cordova platforms for iOS and Android is missing on the tabrisjs.com/download page. I prefer to use Cordova CLI instead Tabris.js Build. For some cases it is faster!

**Comment by calebeaires** [comment]
Some news about 0.9.5 Admob support?

**Comment by mpost** [comment]
We have enabled support for the plugin in the tabris.js 1.0.0 release.

**Comment by calebeaires** [comment]
Tested. It works very well!

**Comment by radiegtya** [comment]
Why my admob cannot shown on android device?

here my code at config.xml:
```
<plugin name="com.google.cordova.admob"/>
```

and this is my main code:
```
....................
var button = tabris.create("Button", {
  text: "Native Widgets",
  layoutData: {centerX: 0, top: 100}
}).appendTo(page);

var label = tabris.create("TextView", {
  font: "24px",
  layoutData: {centerX: 0, top: [button, 50]}
}).appendTo(page);

button.on("select", function() {
  label.set("text", "Totally Rockxx!");
  
  AdMob.createBanner({
    adId: "ca-app-pub-secret/xxx", 
    position: AdMob.AD_POSITION.TOP_CENTER,
    autoShow: true
  });

});

page.open();

```

Please help

**Comment by mpost** [comment]
I have tried your example above. It worked fine for me:

![admob-in-tabris](https://cloud.githubusercontent.com/assets/73655/9081171/69e893c0-3b5a-11e5-84a1-80e516ebbbc8.png)

Have you made sure that the adId is valid?

**Comment by radiegtya** [comment]
Here is my repo 
https://github.com/radiegtya/test-admob 

But the admob not shown on build .apk and there is no error when build with debug mode

**Comment by calebeaires** [comment]
Try to use this tag:

<gap:plugin name="com.google.cordova.admob" source="plugins.cordova.io" />

**Comment by radiegtya** [comment]
@calebeaires : is that code still work on latest tabris?

**Comment by calebeaires** [comment]
Yes. Here is my "work" project

https://github.com/calebeaires/Tabris-APK

**Comment by mpost** [comment]
@calebeaires @radiegtya Currently we suppor the <code>gap:plugin</code> and the <code>plugin</code> tag. The <code>gap:plugin</code> is still supported for backward compatibility but will be phased out eventually. <code>plugin</code> should be used from Tabris.js 1.1 onward

**Comment by mpost** [comment]
@radiegtya Have you tried setting your adview to show test ads? maybe there is a problem with fetching the ads.

**Comment by radiegtya** [comment]
@calebeaires : my build failed using gap :(

@mpost : This ads ID had no problem on my native android, my unity game, and my html 5 ionic too. Btw I had been build it without using test.

**Comment by calebeaires** [comment]
The plugin id in old cordova registry is com.google.cordova.admob, and now in npm is cordova-plugin-admobpro
