### ISSUE TITLE
Picker.get("items") returns inconsistent values among platforms

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#354]
iOS client returns "undefined" when no items set, Android returns an empty array. One would mostly expect "items" to be an empty array when no items are set.

**Comment by ralfstx** [comment]
Agree. items should be [] when no items are set. @cpetrov  Is this still valid with 0.9.4?

**Comment by cpetrov** [comment]
The problem is no longer reproducible on 0.9.4.
