### ISSUE TITLE
Picker: text property does not work on Android

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#357]
iOS implemented a getter for the `text` property, but Android did not. However, we should implement this getter in JavaScript based on the index. Since the text cannot change on the client, we don't need to obtain the value from the client.

**Comment by jordiboehmelopez** [comment]
On iOS, any property you can `set`you can also `get`. There is no "special" `getter` implemented.

**Comment by ralfstx** [comment]
`Picker` does not support a `text` property (anymore?).

**Comment by ralfstx** [comment]
`text` is now called `selection` and it's implemented as suggested.
