### ISSUE TITLE
Selector API: support widget classes

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#360]
Our selector API should also allow to select widget based on a custom "class". This would allow to apply property values to multiple widgets of the same class. The class would be a widget property, similar to `id`. Example:

```js
tabris.create("TextView", {class: "header", ... }).appendTo(page);
...
page.find(".header").set("font", "24px Helvetica");
```

**Comment by tbuschto** [comment]
Fixed in commit 7e0aac169a548a4e2ece2f8b551a939e00f6c20d
