### ISSUE TITLE
Support npm module "whatwg-fetch"

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#361]
This module provides the "fetch" function, a modern alternative to the XMLHttpRequest object.

See https://www.npmjs.com/package/whatwg-fetch

**Comment by mpost** [comment]
Me likes. +1

**Comment by tbuschto** [comment]
Requires #362 to be fixed.

**Comment by tbuschto** [comment]
Works since Requires #362 and #340 were fixed.

**Comment by tbuschto** [comment]
## Compatibility
Works with Tabris.js 1.0, but requires a Promise library, e.g. "promise".

    Promise = require("promise");
    require("whatwg-fetch");
