### ISSUE TITLE
Write widget and property documentation directly in markdown?

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#364]
Most of our documentation can be [browsed in github](https://github.com/eclipsesource/tabris-js/blob/master/doc/index.md). Only the reference documentation for widgets is not available, because it is generated from JSON files at build time. It would be nice to have the entire documentation available in github, without an additional build step.

Moreover, the formal JSON documentation didn't prove as useful as we assumed:
- JSON does not allow for longer paragraphs, we'd have to include an extra README file per widget.
- Editing description texts in JSON is tedious, it would be easier to edit markdown directly.
- The [generator](https://github.com/eclipsesource/tabris-js/blob/master/grunt/grunt-generate-doc.js) is a fairly complex piece of code we could get rid of.
- The formal spec describes the API, not the protocol interface–both are quite different. It can neither be used for client implementations nor for TCKs. This narrows the usefulness of the JSON.

On the downside, we could not include derived properties in a manually written documentation.

**Comment by tbuschto** [comment]
@ralfstx I would like to close this. A machine-readable description is essential for TypeScript support, and possibly declarative UI. It also allows us to make small changes to the generator with huge effects on the documentation. If anything we could try to create the documentation from JsDoc/TsDoc, like this: https://www.npmjs.com/package/tsdoc

**Comment by ralfstx** [comment]
I agree, things have changed and the formal API definition serves us well now.
Now that our code mostly has a class-based structure, JsDoc/TsDoc have become an option.
Another option could be converting the JSON files to YML. That would help to edit longer paragraphs and can probably be done very quickly...

**Comment by cookieguru** [comment]
+1 for TsDoc and the editor integration it would allow with DefinelyTyped
