### ISSUE TITLE
Fix various getter

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#365]
The following getter currently don't work correctly correctly (textInput was used to test the common properties like background). Those marked with "*" can be fixed by implementing a hardcoded default value in JS, or other JS-only fixes. The rest needs native changes.

- ~~textInput.background*~~
    - ~~Natives return "null" as initial value, which throws an error.~~
    - ~~Should be translated to transparent. In the protocol null" represents the "initial" or "unset" state for background, which is transparent in case of background. This is different from [0, 0, 0, 0], which is a color, not the absence of a background. Foreground should never return null.~~
- textInput.font:
    - iOS returns undefined as initial value, Android returns only the size ("18px")
    - see https://github.com/eclipsesource/tabris-ios/issues/692
    - see https://github.com/eclipsesource/tabris-android/milestones/0.9.4-tabris.js
- ~~textInput.transform*~~
    - ~~Android adds fields "rotationX" and "rotationY"~~
    - ~~iOS has rounding errors(e.g. scaleX:2 -> scaleX: 1.9999...)~~
- ~~textInput.highlightOnTouch*~~
    - ~~Android reports null instead of false~~
- ~~textInput.message*~~
    - ~~iOS returns undefined, Android null~~
- ~~textInput.alignment*~~
    - ~~iOS returns undefined~~
- ~~textInput.keyboard*~~
    - ~~iOS returns undefined, Android null~~
- action.foreground:
    - initial value is reported as transparent on both platforms
- action.placementPriority*
    - initial value is reported as undefined (iOS) or null (Android)
- ~~action.title*~~
    - ~~initial value is reported as null on Android~~
    - ~~changed values are incorrectly reported as UPPERCASE. Fixable in JS?~~
- ~~button.alignment, toggleButton.alignment~~
    - ~~initial value is reported as undefined on iOS~~
- ~~button.text, checkbox.text, radioButton.text*~~
    - ~~initial value is reported as undefined on iOS~~
- ~~collectionView.refreshMesage*~~
    - ~~initial value is reported as undefined (iOS) or null (Android)~~
- ~~collectionView.initializeCell*~~
    - ~~initial value is reported as undefined on iOS~~
- ~~imageView.scalemode (*)~~
    - ~~initial vaule is reported as "fit" (!!), not "auto" on Android~~
    - *harcoding would fix the reporting, but the initial native value has to be fixed anyway* See https://github.com/eclipsesource/tabris-android/issues/839
- ~~page.title*~~
    - ~~initial value is reported as null on Android~~
- picker.selectionIndex
    - has no range check on iOS
    - see #371
- ~~progressBar.state*~~
    - ~~initial value is reported as undefined (iOS) or null (Android)~~
- scrollView.direction*
    - default value is read as undefined on both platforms
    - value should be read-only, but isn't (JS issue)
- ~~SearchAction.proposals*~~
    - ~~initial value is reported as null on Android~~
- ~~tab.badge*~~
    - ~~Always returns undefined in iOS and null in Android~~
    - ~~Possibly related to internal JS issue~~
- ~~tab.title*~~
    - ~~Initial value is null in iOS~~
- ~~tab.image*~~
    - ~~value is not decoded (JS issue)~~
- tab.tabBarLocation*
    - default value is null/undefined
    - value should be read-only, but isn't
- textView.markupEnabled
    - Initial value is null on Android
    - Should be read-only (after) create, but is not
- ~~textView.text, textView.maxLines*~~
    - ~~Initial value is undefined in iOS~~
- ~~toggleButton.text*~~
   - ~~initial value is undefined on iOS, "OFF" in Android(??)~~
- video.url
   - initial value is undefined on iOS, null on Android
- webView.url, webView.html
    - initial values for iOS are undefined, for Android empty string and null
    - It's unclear which are the "right" ones.

Entries that are ~~strike-through~~ are fixed with https://gerrit.eclipsesource.com/#/c/4996/, https://gerrit.eclipsesource.com/#/c/5006/, https://gerrit.eclipsesource.com/#/c/5009/

**Comment by paulocarvalhodesign** [comment]
cant set badge value in tab.badge

**Comment by mpost** [comment]
@paulocarvalhodesign On ios oder android? The feature only exists on ios.

**Comment by paulocarvalhodesign** [comment]
android, not check ios.

**Comment by ralfstx** [comment]
There have been a lot of changes to the property system meanwhile, so things have probably changed. The referenced issues are all fixed. Let's open separate issues if we find any remaining inconsistencies.
