### ISSUE TITLE
Adding Tabris.js platforms

### ISSUE THREAD

**Issue by ruarch** [eclipsesource/tabris-js#366]
Tabris.js ships two custom Cordova platforms. This includes platforms for iOS and Android. Visit the Tabris.js download page and download the platform of your choice.

Extract the content of the downloaded archive and add the platform to your project using the cordova platform add command. You need to append the path to the download platform. E.g.:

But I don't see any archive to download

**Comment by gosia-eclipsesource** [comment]
They are on the <a href="https://tabrisjs.com/download">Tabris.js download page</a> in the section "Cordova Platforms".

**Comment by ralfstx** [comment]
Feel free to re-open if you need more information.
