### ISSUE TITLE
Ensure that picker selectionIndex and items can be set in same "set" call.

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#371]
This code:

    tabris.create("Picker", {
      selectionIndex: 3,
      items: ["0", "1", "2", "3"]
    });

How can we ensure that the selectionIndex is set after items?

**Comment by mpost** [comment]
Android applies items and than the index when send in one set operation

**Comment by paulocarvalhodesign** [comment]
cool need to catch up this week :)

**Comment by ralfstx** [comment]
So no problem on Android. @patrykmol Does iOS apply the properties in the same order?

**Comment by patrykmol** [comment]
@ralfstx It shouldn't be a problem on iOS either.

**Comment by ralfstx** [comment]
Ok, thanks.
