### ISSUE TITLE
backgroundImage and background should be the same property

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js#373]
Currently the clients both support only one kind of background, a color *or* an image.
It makes no sense to support two different properties for this on the JS side.

**Comment by tbuschto** [comment]
It should be noted that in RAP and HTML it's possibly to set both. The color is painted under the image, so if the image has transparency it is possible to see both.

**Comment by paulocarvalhodesign** [comment]
If i'm not mistaken in the page object background Image does not work on android platforms only ios, not sure if this was fixed in 0.9.3

**Comment by mpost** [comment]
@paulocarvalhodesign That has been fixed in 0.9.3 on android and should now work as advertised.

**Comment by paulocarvalhodesign** [comment]
great:)

**Comment by tbuschto** [comment]
Making it the same property would also be a bit problematic since images and colors can both be represented as strings. Therefore `"yellow"` could be a color as well as an image file without extension.

**Comment by mpost** [comment]
Closing this issue for now since unifying the properties does not have the highest priority. Please reopen if you feel otherwise.
