### ISSUE TITLE
Prevent drawer from stretching

### ISSUE THREAD

**Issue by paulocarvalhodesign** [eclipsesource/tabris-js#374]
Hy guys, the drawers on IOS seem to stretch the content on them if you continue to drag causing a not very nice effect.
I have only noticed this in IOS simulator.

**Comment by paulocarvalhodesign** [comment]
Just noticed on ipad as well.

**Comment by jordiboehmelopez** [comment]
This is now fixed and will be available with the next release. Version > 0.9.4
