### ISSUE TITLE
Improve DOM compatibility for Cordova plugins

### ISSUE THREAD

**Issue by jkrause** [eclipsesource/tabris-js#376]
We should support ```document.addEventListener``` for cordova plugins that use that mechanism to attach custom events. The ``èvent.target```should be available when the event is fired.

Plugin that needs the above mentioned API:
https://github.com/fastrde/phonegap-downloader/

**Comment by chrwick** [comment]
Maybe it would also be usefull to add the following as well:
```
window.postMessage()
document.createEvent()
```
A few Cordova plugins use these in the Javscript part.

**Comment by hstaudacher** [comment]
Good proposal. Thanks.

**Comment by chrwick** [comment]
Just an example plugin for ```document.createEvent()```:
https://github.com/blocshop/sockets-for-cordova/blob/master/socket.js

"This Cordova plugin provides JavaScript API, that allows you to communicate with server through TCP protocol. Currently we support these platforms: iOS, Android, WP8."

It also requires ```document.removeEventListener()```.

**Comment by chrwick** [comment]
In general it seems that Cordova plugins that try to implement a new feature (Web-API) which is not yet supported on all platforms, seem to do some checks to get the version information on the underlying platform:

Examples:
```
 ver = /Chrome\/(\d+)/.exec(navigator.userAgent);
```
or 
```
function hasWebSocket() {
  var m = /Android ([0-9]+)\.([0-9]+)/i.exec(navigator.userAgent);
  var hasConstructor = typeof WebSocket === "function";

  if (!m) { return hasConstructor; }

  var x = parseInt(m[1], 10);
  var y = parseInt(m[2], 10);

  return hasConstructor && (x > 4 || (x === 4 && y >= 4));
}
```
Maybe it would be a good idea to be able to specify what fake-responses should be sent to such plugins.

**Comment by tbuschto** [comment]
document.createEvent is already implemented. Is there any indication that it does not work already?

**Comment by chrwick** [comment]
Concerning ```window.postMessage```: 
https://github.com/knowledgecode/WebSocket-for-Android/blob/master/www/websocket.js#L37
I have tried this Cordova plugin to get websocket support on Android.
I do not know other plugins so far.

Concerning the userAgent string:
At least the above plugin seems to use this information to switch between built-in functionality of the webview or the external version provided by the Cordova plugin. This depends on the userAgent string for example for the javascript part of the plugin. 
Ok, maybe it is not the best way to derive details about the underlying platform.
Maybe this would be the better appoach: https://cordova.apache.org/docs/en/3.0.0/cordova_device_device.md.html
So it would be the plugin's authors responsibility to change that.

But let us keep in mind that Cordova plugins were developed for a webview based approach.
So it might be a natural assumption that at least the javascript part of a plugin might depend on a userAgent string to find out on what platform it is running to change behaviour accordingly.

**Comment by ifurnadjiev** [comment]
Today I tested the cordova-plugin-fastrde-downloader plugin. It uses document.addEventListener for different events. Didn't check all events, but those I tested are working without problem.
