### ISSUE TITLE
Allow writing files to the device

### ISSUE THREAD

**Issue by jkrause** [eclipsesource/tabris-js#377]
While the cordova.file plugin works fine for reading files, it requires the non-standard `Blob`object for writing files. Blob is neither supported by JavaScriptCore nor by V8. We should either provide a workaround for the Blob or another solution for storing data on the device that cannot be handled by LocalStore. 

We should at least support downloading files to the device, e.g. by enabling https://github.com/eclipsesource/tabris-js/issues/376

**Comment by bFlood** [comment]
+1

**Comment by ralfstx** [comment]
As of 2.0, the [fs](https://tabrisjs.com/tabris-js-docs/latest/api/fs.html) object allows writing binary to the device.
