### ISSUE TITLE
console.log from a simple object

### ISSUE THREAD

**Issue by calebeaires** [eclipsesource/tabris-js#379]
I have tried to print console.log on trabis from an simple object, but it print just an string. Take a look at the screenshot. Is trabis console.log rich as browser itself?

````
var test = [
  {"fruit": "apple"},
  {"fruit": "orange"},
]

console.log(test)
````

![screenshot_2015-04-04-11-13-09](https://cloud.githubusercontent.com/assets/794195/6992983/39bb1776-dabc-11e4-90b8-426b02d7fe6d.png)

**Comment by paulocarvalhodesign** [comment]
try console.log(JSON.stringify(test));

**Comment by irbull** [comment]
I addressed this last week, although I'm not sure if it's been released yet. 

Having said that, we don't pretty print objects recursively. So, in the case of an array, we just print:
[ [object Object], [object Object] ].

However, if you console.log(test[0]); you will get
{"fruit": "apple"}
