### ISSUE TITLE
Failing on debug turned off

### ISSUE THREAD

**Issue by ruarch** [eclipsesource/tabris-js#381]
when I build with debug off, it keeps failing. 
Here are the test app I wanted to build https://github.com/ruarch/redcityapp and https://github.com/ruarch/tabco

**Comment by hstaudacher** [comment]
Debug off means you are building a release build. You need to provide certificates for both platforms if you want them to be built. Have you added the signing keys for the platforms?

**Comment by ruarch** [comment]
I have again created a new key but still failed

**Comment by ruarch** [comment]
for android

**Comment by hstaudacher** [comment]
Can you send me the raw build log to hstaudacher@eclipsesource.com please?

**Comment by ruarch** [comment]
I'm using the on the online bulid...where do I get that log?

**Comment by hstaudacher** [comment]
click on the build number of the failing build. On the bottom right is a button called "Download technical log"

**Comment by ruarch** [comment]
Sent it

**Comment by hstaudacher** [comment]
Analyzed. There is something wrong with your android keystore. See line 1458:

```
jarsigner error: java.lang.RuntimeException: keystore load: Keystore was tampered with, or password was incorrect
```

I will try to reproduce it tomorrow. Can you provide me with the steps you have done to create the keystore?

**Comment by ruarch** [comment]
[4mRunning "shell:zipalign_apk" (shell) task [24m

/usr/local/bin/zipalign: line 3:
/usr/local/Cellar/android-sdk/23.0.2/build-tools/20.0.0/zipalign: No
such file or directory

/usr/local/bin/zipalign: line 3: exec:
/usr/local/Cellar/android-sdk/23.0.2/build-tools/20.0.0/zipalign:
cannot execute: No such file or directory

 [33mWarning: Command failed: /usr/local/bin/zipalign: line 3:
/usr/local/Cellar/android-sdk/23.0.2/build-tools/20.0.0/zipalign: No
such file or directory

/usr/local/bin/zipalign: line 3: exec:
/usr/local/Cellar/android-sdk/23.0.2/build-tools/20.0.0/zipalign:
cannot execute: No such file or directory

  Use --force to continue. [39m



 [31mAborted due to warnings. [39m

travis_time:end:10ce45ae:start=1428439659000000000,finish=1428439896000000000,duration=237000000000
 [0K

 [31;1mThe command "grunt build" exited with 6. [0m

travis_fold:start:after_script.1
 [0Ktravis_time:start:2673c8c4
 [0K$ security delete-keychain ios-build.keychain

travis_time:end:2673c8c4:start=1428439896000000000,finish=1428439896000000000,duration=0
 [0Ktravis_fold:end:after_script.1
 [0Ktravis_fold:start:after_script.2
 [0Ktravis_time:start:05e914f8
 [0K$ rm -f ~/Library/MobileDevice/Provisioning\ Profiles/*

travis_time:end:05e914f8:start=1428439896000000000,finish=1428439897000000000,duration=1000000000
 [0Ktravis_fold:end:after_script.2
 [0K

Done. Your build exited with 1.

**Comment by ruarch** [comment]
I maded a new key, the above is what I get last

**Comment by hstaudacher** [comment]
working on it right now

**Comment by hstaudacher** [comment]
Can reproduce the error. Working on a fix.

**Comment by hstaudacher** [comment]
Ok, there was a problem with the android build tools. An update is live. Can you try again and report if it has worked?

**Comment by ruarch** [comment]
I made a build a it worked fine. Thanks for the support Holger

**Comment by hstaudacher** [comment]
You are welcome. I will close this issue now. Btw I'm working on a speed up for the builds. By this evening every build should be faster by 3-5 min. Next week we will split iOS and Android builds to make it even faster.
