### ISSUE TITLE
Use reasonable defaults when encoding Canvas operations

### ISSUE THREAD

**Issue by irbull** [eclipsesource/tabris-js#390]
When encoding canvas operations, if parameters are missing the encoding breaks. For example
```
tabris.create("Canvas", {
  layoutData: {left: 10, top: 10, right: 10, bottom: 10}
}).on("change:bounds", function( canvas, bounds ) {
  var ctx = tabris.getContext(foo, bounds.width, bounds.height);
  ctx.beginPath();
  ctx.arc(bounds.width / 2, bounds.height / 2, 40, 2 * Math.PI);
  ctx.stroke();
}).appendTo(page);
```
the call to ctx.arc is missing a parameter:
```
ctx.arc(bounds.width / 2, bounds.height / 2, 40, 0, 2 * Math.PI);
```
This results in the packed operations to be missing a parameter, and the decoding fails (and crashes the app).

**Comment by mpost** [comment]
I close this issue for now since we deal with the problem on the tabris.js side.

**Comment by mpost** [comment]
Ups... that was the wrong issue. Reopening.

**Comment by mpost** [comment]
I close this issue for now since we deal with the problem on the tabris.js side.

**Comment by mpost** [comment]
And again... Sorry. Need to be more careful.
