### ISSUE TITLE
Drawer does not look native

### ISSUE THREAD

**Issue by hstaudacher** [eclipsesource/tabris-js#395]
At least on iOS. I think it should be styled in a platform specific way.

**Comment by jordiboehmelopez** [comment]
On iOS:

Cell height: 40px
font: ".HelveticaNeueInterface-Regular"
font-size: 17

This is what it looked like:
![bildschirmfoto 2015-04-17 um 13 12 05](https://cloud.githubusercontent.com/assets/61378/7201026/61767e44-e503-11e4-8591-6c9e433f6dd6.png)

**Comment by ralfstx** [comment]
For Android: http://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-specs
