### ISSUE TITLE
TabFolder should have more styling capabilities

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#396]
Currently we are only able to set `textColor` and `background` on a tabfolder. The `textColor` color does not provide enough information to provide the desired styling on ios and android.

We should be able to set individual colors for active tab, inactive tab, tabs background and an "accent color". Some more discussion is required for the exact properties.

For Android see http://www.google.com/design/spec/components/tabs.html. On ios the uisegmentedcontrol is used.

**Comment by calebeaires** [comment]
+1

**Comment by ruarch** [comment]
+1

**Comment by tbuschto** [comment]
Hiding the tab bar would also be very useful and could make this an alternative to the swipe widget.

**Comment by bFlood** [comment]
+1 for hiding tabs as an alternative for a swipe widget

**Comment by ralfstx** [comment]
In Tabris 1.5, it will be possible to hide the tab bar by setting `tabBarLocation: "hidden"` (commit b4ba9b3cfdf80b8f060c10ebb144ec7e8dbe0284).

**Comment by ralfstx** [comment]
On Android, we could support these additional properties:

- active and inactive text color, we could add `textInactiveColor` in addition to `textColor`
- active and inactive icon color, we could add `iconColor` and `iconInactiveColor`
- color of the indicator on selected tab, `indicatorColor`
- elevation of the tab bar, which is different from the elevation of the tab folder, `tabBarElevation`
- alignment of tabs, e.g. `alignment` or `tabBarAlignment`, values could be `"left", "fill", ...`

**Comment by ralfstx** [comment]
The additional properties are out of scope for 1.5, since the implementation would be based on a newer Android widget.

**Comment by mpost** [comment]
We could also add a `tabBarBackground` property which colorizes the background of the tab bar. Currently You have to set the regular `background` on the tabfolder and than set the background of each page back to eg "white".

**Comment by exocom** [comment]
+1
It would be great to be able to affect the tab alignment on the tab bar.

**Comment by mpost** [comment]
@exocom What styling properties would you like to see for the alignment?

**Comment by exocom** [comment]
@mpost Would like to see left/right aligned tabs.

Example on android when TabFolder only has 1 Tab it is in the center. It doesn't look right.

|____|TAB 1|____|  

Being able to left align would look much better

|TAB 1|_________|

**Comment by cookieguru** [comment]
@exocom Are you referring to the left keyline as demonstrated by the first image from Android's [Material design guidelines](https://material.google.com/components/tabs.html#tabs-specs)?

![Mobile landscape example of same tabs aligned with left keyline](https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B6Okdz75tqQsMFdsRFhCam4zaVk/components_tabs_usage_specs5.png)

versus

![Mobile landscape example of same tabs centered](https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B6Okdz75tqQsTWtHNEdHQjEyVzg/components_tabs_usage_specs4.png)

**Comment by mpost** [comment]
We are using the `TabLayout` from the material design library to render the tab strip. It has the two modes scrollable and fixed while we settled on fixed as the default since it is more in line of the typical dashboard/start page pattern we see in android apps.

https://developer.android.com/reference/android/support/design/widget/TabLayout.html#setTabMode(int)

**Comment by exocom** [comment]
@cookieguru Exactly!

**Comment by mpost** [comment]
Setting the indention of the Tab bar is currently not possible. We have discussed to separate the TabFolder into two seperate widgets but haven't gotten around to that yet.

**Comment by natanraj** [comment]
indicatorColor for tabFolder : is it possible ? - currently it is showing only default green tinge.

**Comment by mpost** [comment]
@natanraj Currently you can only set the `textColor` which affects the underline color as well.

If you want to customize it completely you can provide your own android theme which overrides the look of the default TabFolder.

**Comment by natanraj** [comment]
I think the textColor is  more than enough for time being.

**Comment by mpost** [comment]
Covered by https://github.com/eclipsesource/tabris-js/issues/1676
