### ISSUE TITLE
Allow to set line spacing on a TextView

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#397]
When a TextView wraps to display multiple lines of text we should allow to set the distance between each line to improve readability on longer text.

**Comment by cpetrov** [comment]
+1

**Comment by mpost** [comment]
On Android and iOS it is called "lines pacing" therefore it suggest to create a new property `lineSpacing` on `tabris.TextView`.

Android: http://developer.android.com/reference/android/widget/TextView.html#setLineSpacing(float, float)
iOS: http://stackoverflow.com/a/3908991/271877

**Comment by mpost** [comment]
After some discussion we agreed on a `TextView` property `lineHeight`. Its value is a factor modifying the space between lines (similar to the factor in the css property `line-height`).
