### ISSUE TITLE
Animation cannot be stopped

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#398]
Provide API to stop a running animation.

Example: https://api.jquery.com/stop/

**Comment by ralfstx** [comment]
This is a limitation of iOS, where animations are "fire and forget". If we want *native* animations, we have to live with this restriction. @jordiboehmelopez correct me if I'm wrong.

**Comment by jordiboehmelopez** [comment]
@ralfstx Thats right. The animations are "fire and forget".
