### ISSUE TITLE
Cannot start Project from Tabris.js App my Scripts

### ISSUE THREAD

**Issue by bakopf** [eclipsesource/tabris-js#400]
After updating my iOS and Android Tabris.js App its not possible to start any old Project.
Even a totaly new Project can't be started from the App.
I used the myapp.js and package.json from https://tabrisjs.com/documentation/0.9/quickstart for a new project and got the same Error. The Code of myapp.js is working in the Scratchpad.

Error: 
Could not load tabris module: Error : Cannot find module 'tabris'

Log: 
> b
require
_start

**Comment by ralfstx** [comment]
Did you run an `npm install` in the folder of your application? This should install the tabris module into `node_modules/tabris`.

**Comment by bakopf** [comment]
thank you for the tipp with npm install. i installed the tabris module with npm install now and it worked fine for me. I followed the steps from https://tabrisjs.com/documentation/0.9/getting-started and https://tabrisjs.com/documentation/0.9/quickstart, but i couldnt find any information about the requirement of the npm install in my project folder. If i just didnt see it myself im sorry for asking but if its not in there it would maybe be a good idea to add it.
Thank you for your help

**Comment by ralfstx** [comment]
Both articles contain the `npm install` step, you must have missed it. Anyway, good that it works now.

**Comment by jokorivai** [comment]
I had this error recently. Beside of `npm install` , other easy solution was to use Yeoman generator for tabris-js:
`yo tabris-js`

**Comment by capotti** [comment]
mkdir myproject
cd myproject
tabris init
npm install
tabris run android
-> ERROR: "module tabris could not be found"
-> I had to edit package.json manually and inserted:
"dependencies": {
    "tabris": "^2.0.0-beta2"
  }
-> Now it works

**Comment by ralfstx** [comment]
@capotti This works for me. You must have an outdated version of the tabris CLI or the yeoman generator. Please try
```
npm update -g tabris-cli generator-tabris-js
```

**Comment by capotti** [comment]
yes works.
