### ISSUE TITLE
Button Error: Object is disposed after goback from another page

### ISSUE THREAD

**Issue by bakopf** [eclipsesource/tabris-js#401]
A button with a link to another / second page disposes itself after go back from the page.

What the code is supposed is to link to a second page (page2). When using the goback in the navigationbar the button doesnt work anymore. I only get an Error "Object is disposed".

Scratchpad Code:

var page = tabris.create("Page", {
  topLevel: true,
  title: "TestAPP",
});

var image = tabris.create("ImageView", {
  layoutData: {left: 0, right: 0, top: ["#titleComposite", 0]},
  image: {src: "http://www.lcdmedia.de/UserFiles/Image/pages/reparatur/beamer_test.jpg"},
}).appendTo(page).on("touchstart", function() {
  page2.open();
});

var text = tabris.create("TextView", {
  layoutData: {left: 12, right: 12, top: [image,10]},
  text: "TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST" + 
  		"TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST" + 
  		"TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST" 
}).appendTo(page).on("touchstart", function() {
  page2.open();
});

var page2 = tabris.create("Page", {
  title: "Artikeldetail 2",
});

var button = tabris.create("Button", {
  text: "Seitenwechsel",
  layoutData: {top: [text, 10], centerX: 0}
}).appendTo(page).on("select", function() {
  page2.open();
});

page.open();
      
I also tried the example code from https://tabrisjs.com/documentation/0.9/widgets#codeontype-listener-contextcode instead of the page2.open() and i can use the button over and over again and the clicks are counted in the log. 

I think there could be something wrong with the cooperation between the button (select and touchstart) and the goback function.

Edit: 

To make sure that i didnt get anything wrong i also tried the code from snipped - Actions (https://tabrisjs.com/snippets/#actions) and i get the same dispoed error.

Code:

var page = tabris.create("Page", {
  title: "Actions",
  topLevel: true
});

tabris.create("Action", {
  title: "Action",
}).on("select", function() {
  page2.open();
});

var page2 = tabris.create("Page", {
  title: "page",
});

page.open();

**Comment by paulocarvalhodesign** [comment]
set page2 to be topLevel: true

**Comment by ralfstx** [comment]
The problem is that `page2` is disposed when navigating back to `page` (see https://tabrisjs.com/documentation/0.9/ui#the-page-stack). If page2 is supposed to be a stacked page, you have to create a new instance everytime it's opened.

**Comment by bakopf** [comment]
thanks for the suggestion with the toplevel: true and the link to the page stack. But isnt it a bit strange that i have to create the page over and over again? Isn't the button supposed to be a link with a regular goback? If you know how to use it its okay, but i dont think its a natural way of usage, isn't it?

**Comment by ralfstx** [comment]
That depends on your use case. When a new page is opened on the navigation stack, this page often displays a data item (a product, an email, etc.) That's why we assumed that you want to create a new page with new content.
