### ISSUE TITLE
showOnTouch does nothing

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js#402]
The following snippet does not work. When I touch the page, nothing happens. tested on iOS and Android.

```javascript
var page = tabris.create("Page", {
title: "Home",
topLevel: true
});

var composite = tabris.create("Composite", {
  layoutData: {top: 20, left: 20, bottom: 20, right: 20},
  highlightOnTouch: true
}).appendTo(page);

page.open();
```

**Comment by cpetrov** [comment]
Setting `highlightOnTouch` property to `true` on composites only has effect if the composite's `background` property is set to a [Color](https://tabrisjs.com/documentation/0.9/property-types#color) which is not `transparent`.

**Comment by jordiboehmelopez** [comment]
The `highlightOnTouch` property is implemented to only tint non transparent pixels with a color. Transparent pixels stay transparent.

**Comment by gosia-eclipsesource** [comment]
Closing because it works as expected. Reopen if you disagree.
