### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#403]
* https://tabrisjs.com/documentation/0.9/search?q=Widgets
* https://tabrisjs.com/documentation/0.9/search?q=Modules
* https://tabrisjs.com/documentation/0.9/search?q=Layouts
... all return "No Result".

**Comment by hstaudacher** [comment]
There was an error yesterday with github markdown parser. Restarted the system and the index was build successful.
