### ISSUE TITLE
Flaws in current page model

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#405]
The current page model seems to have some flaws that should be addressed in the next major version:
### open() and close() are not symmetric

While open() pushes a page onto the page stack, close() removes it from the stack AND disposes it.

```
CREATED --- open() ---> ON_STACK ---> close() ---> DISPOSED
```

It would be more intuitive if open() and close() would only relate to the visibility of a page and disposing of a page would be a separate operation:

```
CREATED --- open() ---> ON_STACK ---> close() ---> CREATED
CREATED --- dispose() ---> DISPOSED
ON_STACK --- dispose() ---> DISPOSED
```

However, this would open up for memory leaks because pages that are displaced by other pages would not be cleaned up.
### close() does not correspond to removing from stack

When a page is displaced by another page, it is closed. A top-level page, however, will only be removed from the stack, but it won't be closed. Hence, close does not correspond to "remove from stack". It's unclear what `close()` does. In fact, it is really just an alias for `dispose()`.

TBC

**Comment by tbuschto** [comment]
My understanding is that this relates only to the 1.x page model. Since we don't update 1.x anymore I will close this issue. Re-open if you disagree.
