### ISSUE TITLE
Navigation menu / drawer opens the wrong pages

### ISSUE THREAD

**Issue by bakopf** [eclipsesource/tabris-js#408]
Canvas example in the Tabris.js app for iOS (Downloaded from iTunes)
iPhone 5s 8.3

When you open the canvas example and switch through pages at one point it starts to open the wrong pages. You just need to open different pages a few time and suddenly every link opens the same or a other page than its supposed to.  Same error occurs in the Chart.js example. This possible could be an error in every Menu. 

1. Install Tabris.js app from iTunes
2. Open it -> Examples -> Canvas or Chart.js
3. Open Navigation / Drawer
4. Swtich through pages a few times
5. Now you should be able to see the error with the wrong pages

I also made a example myself which you can find in my GITHUB repositories. 
https://github.com/bakopf/myApp. The same error in the Menu occurs there.

**Comment by jonek** [comment]
Thanks for the report. We knew about this issue and have already fixed it. You will get it with the next release soon.
