### ISSUE TITLE
SearchAction does not fire textChanged while typing

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#409]
We introduced the text property, but still only fire the "input" event.

**Comment by mpost** [comment]
@tbuschto is this still valid?

**Comment by mpost** [comment]
The `input` event needs to be mapped to a `textChanged` event like in `TextInput`.

**Comment by cookieguru** [comment]
I believe this is working as expected; the `textChanged` event fires when the `text` property changes programmatically and the `input` event fires on user key press.

**Comment by mpost** [comment]
Agreed with @cookieguru. Closing as resolved. Please reopen if you have any more issues.
