### ISSUE TITLE
Clipping when displaying an image

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js#411]
Please support the following geometric shapes for clipping when displaying an image:
- `inset() = inset( <shape-arg>{1,4} [round <border-radius>]? )`
- `ellipse() = ellipse( [<shape-radius>{2}]? [at <position>]? )`

defined by: http://dev.w3.org/csswg/css-shapes-1/#typedef-basic-shape

In CSS these can be used with `clip-path`: http://dev.w3.org/fxtf/css-masking-1/#the-clip-path

See an HTML+CSS demo here:
http://bennettfeely.com/clippy/

**Comment by mpost** [comment]
the inset will work like a clipping padding correct?

**Comment by mpost** [comment]
With the introduction of the `cornerRadius` i would consider this feature covered. Closing for now. Please reopen if you have any remaining issues.
