### ISSUE TITLE
Support drawImage() on canvas

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js#413]
drawImage() as defined here https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage should be supported by canvas.

This issue should be part of #92.

**Comment by mpost** [comment]
+1

**Comment by ralfstx** [comment]
Images can be drawn using `putImageData()`.

The method `drawImage()` is used to draw DOM images, e.g. from `<image>` elements. Since we don't have a DOM, this method doesn't seem to make sense in Tabris.js.

Please reopen if you disagree.
