### ISSUE TITLE
Splash Screen Implementation

### ISSUE THREAD

**Issue by ruarch** [eclipsesource/tabris-js#414]
Do I need the cordova plugin for splash screen for my splash screen to show?
below is my code, the icon works fine but the splash screen does not show.
The images are outside the www

Below is what I have in my config.xml
The icon works but the splashscreen does not work.

  <preference name="SplashScreen" value="screen" />
	<preference name="SplashScreenDelay" value="10000" />
     <platform name="android">
        <icon src="ghanafeeds.png" />
	    <splash src="screen.png" density="land-hdpi" />
	    <splash src="screen.png" density="land-ldpi" />
	    <splash src="screen.png" density="land-mdpi" />
	    <splash src="screen.png" density="land-xhdpi" />
	    <splash src="screen.png" density="port-hdpi" />
	    <splash src="screen.png" density="port-ldpi" />
	    <splash src="screen.png" density="port-mdpi" />
	    <splash src="screen.png" density="port-xhdpi" />
    </platform>

**Comment by paulocarvalhodesign** [comment]
read here "Cant seem to get splash screen to work #328"

**Comment by mpost** [comment]
We should add a section about splash screens in the FAQ.

**Comment by gosia-eclipsesource** [comment]
Question added to FAQ.

**Comment by luciandinu** [comment]
It looks that Google change their mind about Splash Screen and now they call them Launch Screens - https://www.google.com/design/spec/patterns/launch-screens.html

"Because launching your app while displaying a blank canvas increases its perceived loading time, consider using a placeholder UI or a branded launch screen. "

**Comment by mpost** [comment]
Yeah that is an unfortunate turn of events. We might jump on that bandwagon as well.
