### ISSUE TITLE
Support `org.apache.cordova.file-transfer`

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#418]
Successfully tested r1.0.0

**Comment by capotti** [comment]
This is cordova-plugin-file-transfer? (please adopt title)

`var fileTransfer = new FileTransfer();`
runs in Developer App
But not on local build with config.xml settings
`<plugin name="cordova-plugin-file-transfer" spec="~1.6.3" />`
-> FileTransfer is unknown.
Do I have to register the plugin in additional way?

**Comment by capotti** [comment]
see https://github.com/eclipsesource/tabris-js-file-open-example/blob/master/www/app.js

**Comment by cookieguru** [comment]
>  Do I have to register the plugin in additional way?

You shouldn't have to; can you check your build log to see if there were any errors installing the plugin?

**Comment by capotti** [comment]
@cookieguru
Is there a special build log in the build folder?
Here comes the command line output.
There seems to be errors...

[ios_build.txt](https://github.com/eclipsesource/tabris-js/files/997935/ios_build.txt)

**Comment by cookieguru** [comment]
```plain
/Users/dirk/Documents/workspace/apps/maps/build/cordova/platforms/ios/Maps/Plugins/cordova-plugin-file-transfer/CDVFileTransfer.m:224:34: warning: 
      values of type 'NSUInteger' should not be used as format arguments; add an
      explicit cast to 'unsigned long' instead [-Wformat]
    DLog(@"fileData length: %d", [fileData length]);
                            ~~   ^~~~~~~~~~~~~~~~~
                            %lu  (unsigned long)
/Users/dirk/Documents/workspace/apps/maps/build/cordova/platforms/ios/Maps/Plugins/cordova-plugin-file-transfer/CDVFileTransfer.m:31:91: note: 
      expanded from macro 'DLog'
  ...[Line %d] " fmt), __PRETTY_FUNCTION__, __LINE__, ##__VA_ARGS__)
                                                        ^~~~~~~~~~~
1 warning generated.
```
Looks like the plugin is broken.

**Comment by ralfstx** [comment]
@capotti Just for completeness: Yes, the plugin has been renamed to `cordova-plugin-file-transfer` and no, there's no additional step to register the plugin, the line in `config.xml` is sufficient.

**Comment by capotti** [comment]
thanx for completeness - suppose, errors resulted from inconsistent local environment
see https://github.com/eclipsesource/tabris-js/issues/1308#issuecomment-301210408

**Comment by ralfstx** [comment]
Are you building locally with the CLI?

**Comment by cookieguru** [comment]
@ralfstx Yes, he is

**Comment by ralfstx** [comment]
Then what do you mean by
> inconsistent local environment

Did you `npm update` your `tabris` and `tabris-cli` and have the native client version that matches the tabris version?

**Comment by cookieguru** [comment]
That was the problem: inconsistent versions

**Comment by capotti** [comment]
>     uninstalled cordova via npm
>     downloaded both folder ios and android again (now 2.0.0rc1)
>     Now it works as expected!

that reduced a lot of local build errors in my case

**Comment by ralfstx** [comment]
Perfect! Thanks for the update.
