### ISSUE TITLE
Back arrow does not appear when I create a new Page

### ISSUE THREAD

**Issue by ruarch** [eclipsesource/tabris-js#419]
I can't get the back arrow to appear on create new page.
https://github.com/ruarch/ghanafeedsapp/blob/master/www/main.js

**Comment by paulocarvalhodesign** [comment]
You need to specify top level page to be false when you create the page otherwise will be true.
Check the examples of creating pages .
Anyone correct me if I'm wrong here please 😃

**Comment by ruarch** [comment]
Can anybody help with a snippet that creates pages with back arrow.

**Comment by paulocarvalhodesign** [comment]
var pageCount = 0;

createPage("Initial Page", true);

function createPage(title, topLevel) {
  var page = tabris.create("Page", {
    title: title,
    topLevel: topLevel
  }).open();

  tabris.create("Button", {
    layoutData: {left: 10, top: 10, right: 10},
    text: "Create another page"
  }).on("select", function() {
    createPage("Page " + (++pageCount), false);
  }).appendTo(page);

**Comment by ruarch** [comment]
I corrected it 

var pageCount = 0;

var page=createPage("Initial Page", true);

function createPage(title, topLevel) 
{
    var page = tabris.create("Page", {
    title: title,
    topLevel: topLevel
  }).open();
    return page;
}
tabris.create("Button", {
    layoutData: {left: 10, top: 10, right: 10},
    text: "Create another page"
}).on("select", function() {
      createPage("Page " + (++pageCount), false);
}).appendTo(page);


But still no arrow. Is it something with tabris 0.9.4?

**Comment by mpost** [comment]
@ruarch Indeed. There was a problem that has been fixed for the 0.9.5 release.

**Comment by mpost** [comment]
Closing as fixed.
