### ISSUE TITLE
Play Youtube videos

### ISSUE THREAD

**Issue by ruarch** [eclipsesource/tabris-js#420]
I can't get to make the tabris.create("Video" 
Play youtube videos e.g. https://www.youtube.com/watch?v=39_OmBO9jVg

**Comment by mpost** [comment]
The video widget only supports links to video files like .mp4. It does not support to embed youtube videos.

**Comment by jonek** [comment]
You can use the Tabris.js WebView to embedd a YouTube video in your UI.
