### ISSUE TITLE
Tab title with the same width

### ISSUE THREAD

**Issue by calebeaires** [eclipsesource/tabris-js#421]
how to adjust the tabs titles so that their size is also distributed on the screen

**Comment by ralfstx** [comment]
Could you provide a screenshot or a mock of the expected result?

**Comment by calebeaires** [comment]
![screenshot_2015-04-27-16-20-24](https://cloud.githubusercontent.com/assets/794195/7355764/62feec3e-ecfa-11e4-8140-acbfb781b03c.png)

The tittles is distributed on the tab folder equally. Doing this, the app get more pretty

**Comment by mpost** [comment]
Setting that property is currently not possible. We are planning to provide more styling capabilities for the Tabfolder in the future as suggested here: https://github.com/eclipsesource/tabris-js/issues/396
