### ISSUE TITLE
how to set the background color of action bar?

### ISSUE THREAD

**Issue by newhow** [eclipsesource/tabris-js#423]
Is there any way to set in the version 0.9.4? I want it the same color as the tabs, just like how Tabris.js dev app (android) appears.

**Comment by cpetrov** [comment]
Yes, set the *background* property of the `tabris.ui` object:

```javascript
tabris.ui.set("background", "#4e9ad9");
```

To change the background color of the tab buttons, set the *background* property of the `TabFolder`.

**Comment by newhow** [comment]
Works. Thanks a lot !
