### ISSUE TITLE
Cordova Plugins

### ISSUE THREAD

**Issue by ruarch** [eclipsesource/tabris-js#425]
How do I link to a plugin like the badge.

var PluginPage = require("./PluginPage");

from the example does not work.

Should I use ./plugins/de.appplant.cordova.plugin.badge? (that does not work either)

**Comment by tbuschto** [comment]
I'm not sure I understand the question. Perhaps this will clarify:

- "PluginPage" is a module that belongs to the cordova example app. It's not relevant to using cordova in tabris.js

- The "badge" plug-in can be used like this `cordova.plugins.notification.badge.set("42");`, as demonstrated [here](https://github.com/eclipsesource/tabris-js/blob/master/examples/cordova/modules/BadgePage.js) in the cordova example app, and documented [here](https://github.com/katzer/cordova-plugin-badge/tree/223ec28#set-the-badge-number) in the plug-ins documentation.

- The "link" feature in the cordova demo is implemented using a WebView, as shown [here](https://github.com/eclipsesource/tabris-js/blob/master/examples/cordova/modules/PluginPage.js). It's also got nothing directly to do with cordova.

**Comment by ruarch** [comment]
Thanks...I get it now

**Comment by ruarch** [comment]
how do I set a custom small icon for the badge

**Comment by ralfstx** [comment]
@ruarch I'm afraid that's not supported by the platforms, but that's really a question for [cordova-plugin-badge](https://github.com/katzer/cordova-plugin-badge).
