### ISSUE TITLE
I cannot get modules promise and whatwg-fetch work in tabris.js 1.0.0

### ISSUE THREAD

**Issue by newhow** [eclipsesource/tabris-js#426]
Could not load main module: Error: Cannot find module './lib/core.js'

**Comment by jonek** [comment]
Is the "fetch()" example working in your Tabris.js Developer app?

Have you added the dependencies to your project as described in this blog post?
http://eclipsesource.com/blogs/2015/04/24/tabris-js-examples-network-access/
(see paragraph "fetch()" in that post)

**Comment by newhow** [comment]
reddit pet example works on my Tabris.js Developer app

this is my project package.json:

{
  "name": "tabris-getting-started",
  "description": "Tabris.js - Hello, World!",
  "main": "hello.js",
  "dependencies": {
    "tabris": "1.0.0",
    "promise": "^6.1.0",
    "whatwg-fetch": "^0.7.0"
  }
}

**Comment by tbuschto** [comment]
- Please verify that `d:\xxx\node_modules\promise\lib\core.js` exists
- Verify that the file is reachable via http as `http://{project-root}/node_modules/promise/lib/core.js`
- Check the log of your http server. We recommend the node `http-server` which print it to the screen.
- If the log show that the client does request the file under the wrong URL, please post that URL. 
- If the log show that the client does request the file at all, what is the last request?

**Comment by newhow** [comment]
The error in my original post can still be reproduced by running a webstorm built-in server on 192.168.1.4:11111. I can reach http://192.168.1.4:11111/node_modules/promise/lib/core.js by a browser. But from tabris dev app, I have to connect to http://192.168.1.4:11111/xxx to get my project files like hello.js and package.json.  

If I start http-server under d:\xxx, I will get an error "cannot find module asap". (The log shows no problem on fetching promise/lib/core.js.) The following is the end of the log printed by http-server. 


[Thu, 30 Apr 2015 13:51:47 GMT] "GET /node_modules/asap" "com.eclipsesource.tabris.android/2.0.0 (com.eclipsesource.tabris.js/1.0.8-20150402-1522) (asus; Nexus 7; 4.4.2)"
[Thu, 30 Apr 2015 13:51:47 GMT] "GET /node_modules/asap" Error (404): "Not found"
[Thu, 30 Apr 2015 13:51:47 GMT] "GET /node_modules/asap.js" "com.eclipsesource.tabris.android/2.0.0 (com.eclipsesource.tabris.js/1.0.8-20150402-1522) (asus; Nexus 7; 4.4.2)"
[Thu, 30 Apr 2015 13:51:47 GMT] "GET /node_modules/asap.js" Error (404): "Not found"
[Thu, 30 Apr 2015 13:51:47 GMT] "GET /node_modules/asap.json" "com.eclipsesource.tabris.android/2.0.0 (com.eclipsesource.tabris.js/1.0.8-20150402-1522) (asus; Nexus 7; 4.4.2)"
[Thu, 30 Apr 2015 13:51:47 GMT] "GET /node_modules/asap.json" Error (404): "Not found"
[Thu, 30 Apr 2015 13:51:47 GMT] "GET /node_modules/asap/package.json" "com.eclipsesource.tabris.android/2.0.0 (com.eclipsesource.tabris.js/1.0.8-20150402-1522) (asus; Nexus 7; 4.4.2)"
[Thu, 30 Apr 2015 13:51:47 GMT] "GET /node_modules/asap/package.json" Error (404): "Not found"
[Thu, 30 Apr 2015 13:51:47 GMT] "GET /node_modules/asap/index.js" "com.eclipsesource.tabris.android/2.0.0 (com.eclipsesource.tabris.js/1.0.8-20150402-1522) (asus; Nexus 7; 4.4.2)"
[Thu, 30 Apr 2015 13:51:47 GMT] "GET /node_modules/asap/index.js" Error (404): "Not found"
[Thu, 30 Apr 2015 13:51:47 GMT] "GET /node_modules/asap/index.json" "com.eclipsesource.tabris.android/2.0.0 (com.eclipsesource.tabris.js/1.0.8-20150402-1522) (asus; Nexus 7; 4.4.2)"
[Thu, 30 Apr 2015 13:51:47 GMT] "GET /node_modules/asap/index.json" Error (404): "Not found"

**Comment by tbuschto** [comment]
The Android client seems to show some weird behavior when the trailing "/" is missing from the URL. E.g.  "http://192.168.1.4:11111/xxx/" vs "http://192.168.1.4:11111/xxx". Could you check if that fixes/improves the issue? 

Also the "asap" issue may be unrelated. Assuming you don't use the "asap" module yourself, it should be in "node_modules/promise/node_modules/asap/".

**Comment by jonek** [comment]
@newhow Could you please tell us the version of your Tabris.js Developer App? You can find it when you click on the person icon in the upper right corner of the launch screen and then click the 'About' button.

**Comment by newhow** [comment]
1.0.8-20150402-1522
Tabris.js: 0.9.4

**Comment by newhow** [comment]
Okay, no problem on promise or whatwg-fetch after upgrading dev app. But foreground of tabFolder does  not work. Thank you @tbuschto @jonek
