### ISSUE TITLE
Scratch pad and 1.0.0

### ISSUE THREAD

**Issue by rhg1968** [eclipsesource/tabris-js#427]
I just updated my tabrisjs app on my android device and the scratch pad displays some error message about not being able to load the tabris module and that it couldn't parse tabris.js because it has an invalid token. I reset the scratch pad back to the default and it has the same error.

**Comment by andreasmihm** [comment]
same error for me

**Comment by ralfstx** [comment]
There appears to be a problem with the tabrisjs.com server. We're working on it.

**Comment by ralfstx** [comment]
The problem has been fixed and the scratchpad should be working fine now with 1.0.0.

**Comment by rhg1968** [comment]
Looks good. Thank you 

Sent from Yahoo Mail on Android
