### ISSUE TITLE
Default Icon show up on Android 4.1

### ISSUE THREAD

**Issue by calebeaires** [eclipsesource/tabris-js#431]
Some icon from tabris/app is showing on Page Widget!
![captura de tela 2015-05-03 as 10 58 47](https://cloud.githubusercontent.com/assets/794195/7445322/0510ba7e-f184-11e4-9c80-84dc689ecede.png)

**Comment by mpost** [comment]
The icon you see by default is the launcher icon. That means, once you create your own build you will see your custom icon icon. Also of note... The icon is only used in Android prior 5.x as the material design guide discourages to use icons.

That being said we see the need for a way to set the icon manually and we will add a this feature in the next release.

**Comment by calebeaires** [comment]
Cool, ...hope get it on the next version!

**Comment by mpost** [comment]
With the Tabris.js 1.1 release we make use of the Material design on Android 4.x devices. Therefore you will not see an icon anymore even on Android 4.x.

For more info see: http://eclipsesource.com/blogs/2015/07/03/tabris-js-1-1-sneak-peak-custom-themes-on-android/

**Comment by calebeaires** [comment]
That`s fine. Happy with tabrisjs evolution. I am closily watching
