### ISSUE TITLE
Version Mismatch

### ISSUE THREAD

**Issue by ruarch** [eclipsesource/tabris-js#432]
After build, when I load the app the following message flashes;

Version Mismatch: JavaScript module "tabris" (version 0.9.4) is incompatible with this native tabris platform. Supported module versions: 1.0.0 to 1.0.0.

**Comment by mpost** [comment]
Have you adjusted the required tabris version in your package.json? Is the tabris version in synch with the designated version in the build?

**Comment by ruarch** [comment]
Yh found that out...I have corrected it. thanks anyway.
