### ISSUE TITLE
Creating Shortcuts

### ISSUE THREAD

**Issue by ruarch** [eclipsesource/tabris-js#433]
Do I need to use a plugin?

**Comment by jonek** [comment]
What do you mean by shortcuts?

**Comment by ruarch** [comment]
App shortcuts on the homescreen

**Comment by mpost** [comment]
Do you mean like multiple entry points into the same app via different launcher icons?

**Comment by ruarch** [comment]
Well, after installation of the app, I will like a shortcut to be created on the screen homepage, currently it's only created at the apps list area only.

**Comment by jonek** [comment]
Did you use the Tabris.js build service to build your own app?
If you build an app out of your Tabris.js JavaScript code, that app can have its own launcher icon. You can supply your own branding. See here: http://eclipsesource.com/blogs/2015/04/02/brand-your-tabris-js-app/

**Comment by ruarch** [comment]
Apps like whatsapp create a shortcut on the main homepage (screen) on
android. No homescreen shortcut after I install my build.

**Comment by jonek** [comment]
If there is no space on your homescreen the shortcut is created on another screen (if there is place left there). If all homescreens are full you can open your appdrawer and drag&drop your app to the homescreen. If there is no space left, you can group apps. Or you can remove another shortcut first and then drop you Tabris.js app there. At least that is how it works on my Android phone. Does this help?

**Comment by ruarch** [comment]
Yeah I do that....just wanted an automated way.

**Comment by jonek** [comment]
@ruarch IMHO the functionality is out-of-scope for Tabris.js. Creating shortcuts on the homescreen is functionality provided by you mobile operating system. When you install a Tabris.js app for the first time and there is space left on one of you screens, a shortcut with the app icon is created automatically.
