### ISSUE TITLE
All layout related dimension values should be set and get as decimal numbers

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#435]
Currently the clients return all dimensions as integer numbers, thereby losing precision when rounding, which leads to wrong dimensions. The clients should return and be able to process decimal numbers.

**Comment by mpost** [comment]
Affected properties are layoutData, bounds(?) and transformation

**Comment by tbuschto** [comment]
Anroid is done, iOS support still WIP.

**Comment by mpost** [comment]
Apparently no changes are required on the tabris.js side.

**Comment by patrykmol** [comment]
iOS already supports it. No changes are required.
