### ISSUE TITLE
Create a roadmap page

### ISSUE THREAD

**Issue by gosia-eclipsesource** [eclipsesource/tabris-js#436]
User request: Can we consider creating a roadmap page where users will be able to track upcoming features?

**Comment by jonek** [comment]
+1

**Comment by ralfstx** [comment]
Sure, we should publish a roadmap. I'd prefer a document on http://tabrisjs.com (somewhere next to the FAQ) rather than content tracked in the git repository.

**Comment by jonek** [comment]
We can use the existing infrastructure that support http://developer.eclipsesource.com/tabris/roadmap/

I would propose using that immediately and then review how it serves us after let's say two more sprints.

**Comment by ralfstx** [comment]
@gosia-eclipsesource What's the solution?

**Comment by gosia-eclipsesource** [comment]
@ralfstx We now publish the roadmap as a section on Grand Central:
https://tabrisjs.com/grand-central

**Comment by ralfstx** [comment]
Great, thanks!
