### ISSUE TITLE
npm module 'whatwg-fetch' causes "Invalid Signature" rejection

### ISSUE THREAD

**Issue by jordiboehmelopez** [eclipsesource/tabris-js#437]
The app is correctly built and signed, but then on upload to Apple rejected with the following error:

ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. The binary at path
[tabris.js.app/www/bundled_tabris_js_launcher/examples/fetch/node_modules/whatwg-fetch/test/run.sh]
[tabris.js.app/www/bundled_tabris_js_launcher/examples/fetch/node_modules/whatwg-fetch/test/server.js]
[tabris.js.app/www/bundled_tabris_js_launcher/examples/reddit/node_modules/whatwg-fetch/test/run.sh]
[tabris.js.app/www/bundled_tabris_js_launcher/examples/reddit/node_modules/whatwg-fetch/test/server.js]
 contains an invalid signature. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html"

**Comment by jkrause** [comment]
This cannot be fixed by tabris.js. As a workaround, delete the "test" folder from whatwg-fetch with a Cordova hook in your build.
