### ISSUE TITLE
Error: Unknown type Label

### ISSUE THREAD

**Issue by bev-on** [eclipsesource/tabris-js#440]
Was Label renamed in 1.0? I'm getting error "Unknown type Label" after update.

var label = tabris.create("Label", {
	layoutData: {left: 10, top:10},
	background: "red",
	text: "test" 
});

**Comment by cpetrov** [comment]
Yes, "Label" widget was renamed to "TextView" in [0.9.1](https://github.com/eclipsesource/tabris-js/releases/tag/v0.9.1).

**Comment by bev-on** [comment]
Thank you! :)
