### ISSUE TITLE
Getting Started guired does not get you started

### ISSUE THREAD

**Issue by rherrmann** [eclipsesource/tabris-js#442]
I followed the [getting started guide](https://tabrisjs.com/documentation/1.0/getting-started) from _Create Your First App_ on but wasn't able to get the Hello World app running.

After connecting the tabris.js app to `<my ip>:8080` the following error occured:
`Could not load tabris module: Error: cannot find module 'tabris'`

Only after cd-ing into the `tabris-js-getting-started` folder and running `npm install tabris`, the app worked. 

Not sure though what the intended behavior is. Should tabris be installed into each project? or should the getting started repository contain the tabris.js module already? or am I missing something?

**Comment by ralfstx** [comment]
Hmm, in the section "Test your app", it tells you to do an `npm install`. However, you're [not the first one](#400) who missed it. What can we do to make it more obvious?

**Comment by rherrmann** [comment]
Ups, there it is. I read `install http-server` and then skipped the entired text box because I already had the http server installed and running.

If you bevlieve that this wasn't just my skipping though too fast, you might consider to split the instructions into a _Install Http Server_ and _Install Tabris Module_ section.
Or a trooblshooting section at the end: if you see this error [...] then carefully re-read the above section ;)
