### ISSUE TITLE
How to add an Icon into the navigation bar 

### ISSUE THREAD

**Issue by bakopf** [eclipsesource/tabris-js#443]
I want to add an Icon into the navigation bar on the right side beside the page title.
Just like the reload icon which is given in the console, but i couldnt find anything about that
in the documentation / exmaples / snippets.

Is there a way to place an Icon with a link to a page in there?

![icon](https://cloud.githubusercontent.com/assets/9216973/7564575/678fd8d2-f7e8-11e4-956d-fb41131cbe57.jpg)

**Comment by jonek** [comment]
You should be able ti use an ```Action``` with an image for that purpose.
https://tabrisjs.com/documentation/1.0/api/Action

Here is a snippet that illustrates it: https://github.com/eclipsesource/tabris-js/blob/master/snippets/action/action.js

**Comment by bakopf** [comment]
Thank you for your fast help. 
I realy didnt see the conection between actions and the Navigationbar so far.
It finaly worked with the Action placement example.

**Comment by ralfstx** [comment]
Seems this issue can be closed. Please re-open if needed.
