### ISSUE TITLE
Decimal keyboard flickers before it disappears

### ISSUE THREAD

**Issue by rherrmann** [eclipsesource/tabris-js#444]
I have a UI that consists of a `TextInput` and a `Button`. The text field has `keyboard: "decimal"` set. When traversing from the text field to the button, the keyboard changes to the alphanumeric layout right before it disappears which causes unpleasant flicker.

Tested on Android  4.2.2.

**Comment by mpost** [comment]
Interesting. Are you using a custom keyboard? What device are you seeing that on?

**Comment by rherrmann** [comment]
The device is a [Fairphone](http://www.fairphone.com/) (1st generation) and no custom keyboard is installed.

**Comment by mpost** [comment]
I could imagine that this particular model comes with a none stock keyboard by default which has this behavior. Do you see that issue in other apps?

Do you have a snippet to reproduce the problem?

**Comment by mpost** [comment]
Closing this for now. Please reopen if you still see the problem.
