### ISSUE TITLE
Error in 'pause' listener

### ISSUE THREAD

**Issue by rherrmann** [eclipsesource/tabris-js#445]
My app has a _pause_ listener defined as follows:
```javascript
saveSettings = function() {
  localStorage.setItem( "foo", fooInput.get( "text" ) );
}
tabris.app.on( "pause", saveSettings );
```

`fooInput` is a TextInput that lives on the only top-level page. When the app is suspended and the text input wasn't touched before (i.e. nothing entered or otherwise interacted with) an error occurs. 
No message is shown, just an overlay with two curly braces that fades away after a while.
```
{   }
```

If the pause listener is removed, the error disappears also. If the `saveSettings` code is run outside the pause event, it executes just fine.

**Comment by tbuschto** [comment]
Android, iOs, or both? Is the value written to the localStorage anyway or not? If the text *was* changed, does it behave differently?

**Comment by rherrmann** [comment]
This can be observed on Android. For iOS, I don't know, Idon't have an iOs device.

The input field is empty initially. As said in the description, the error only occurs if the the input field was not _touched_. Hence it appears that the value isn't written. 
If a values was entered, everything works as expected.

**Comment by ifurnadjiev** [comment]
To my knowledge you can't store in local storage null/undefined values. Empty string is considered as such.

**Comment by tbuschto** [comment]
You can store anything in localStorage, it will just be converted to string. This seems like an Android issue. Moritz should have a look at it when he's back.

**Comment by irbull** [comment]
When is Moritz back? I'm off Monday but I can take a look on Tuesday.

**Comment by rherrmann** [comment]
@ifurnadjiev Thanks for this hint. Testing for an empty string lets the error disappear:
```javascript
if( fooInput.get( "text" ) ) {
  localStorage.setItem( "foo", fooInput.get( "text" ) );
}
```

However, I still think the is-empty-test shouldn't be neccessary. I haven't found any hints in the documentation that empty strings aren't allowed and such a behavior would be really counterintuitive.

**Comment by ifurnadjiev** [comment]
I think this is a JS issue, not Android. See https://github.com/eclipsesource/tabris-js/blob/master/src/js/WebStorage.js setItem implementation:
```
if (!value) {
   throw new TypeError("Value argument must be specified to execute 'setItem'");
}
```
