### ISSUE TITLE
How to get width/height of widget

### ISSUE THREAD

**Issue by bev-on** [eclipsesource/tabris-js#446]
For example I add new TextView to page and I set only width in layoutData. If I set multiline text, height will increase automatically to fit long text but problem is I can't find way to get height of this TextView after it's automatically resized.

var tw = tabris.create("TextView", {
	layoutData: {top:0, width:50},
	alignment: "center",
	textColor: "#ffffff",
	text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
	font: "11px"
});

tw.appendTo(mPage);

When I'm trying to get layoutData using tw.get("layoutData") it's only returns values of "top" and "width" properties because I already set them, but I can't get height because it's set automatically.

How can I get real height of widget either it's set automatically or manually?

**Comment by bev-on** [comment]
I try to use bounds as well but no success. tw.get("layoutData").height returns "Undefined" and tw.get("bounds").height returns "0".

**Comment by jonek** [comment]
You have to use a resize listener to wait for the layouting. Once layouted, your listener gets notified. You should be able to get meaningful layoutData in the listener.

Documentation for the resize event:
https://tabrisjs.com/documentation/1.0/api/Widget#resize-widget-bounds-options

Here is a snippet that uses a resize listener:
https://github.com/eclipsesource/tabris-js/blob/8318b229af6e619837d4c2472edde87e58181f47/snippets/layout-dynamic/layout-dynamic.js

**Comment by bev-on** [comment]
Thank you so much! It works :)
