### ISSUE TITLE
Load Cordova plugins

### ISSUE THREAD

**Issue by adenaman** [eclipsesource/tabris-js#448]
Hi
Im using the online build in your servers, so i need to configure the __config__ and the __package__ files.
I was able to use the calendar plugin using

```config.xml
<gap:plugin name="nl.x-services.plugins.calendar" />
```
This plugin is registered in http://registry.cordova.io/nl.x-services.plugins.calendar

But there are other plugins i would like to use : cordova-plugin-directions and cordova-plugin-file.
Those are not registered or at least i cant find them. So i must try to load them from a git url.
Using the PhoneGap structure of config file didn't help me either.

I also tried to use the __dependency__ feature from __package.json__
```package.json
    "cordova-plugin-directions": "git://github.com/leecrossley/cordova-plugin-directions.git",
    "cordova-plugin-file": "git://github.com/apache/cordova-plugin-file.git"
```
That build ok, but i can't use the modules in my code
```
require('cordova-plugin-directions');
directions.navigateTo("51.50722", "-0.12750"); // latitude, longitude
```
No problem with require, but there is no directions object

Also 
```config.xml
<gap:plugin name="SplashScreen" value="org.apache.cordova.core.SplashScreen" />
```
Should work, but it doesn't (this is not my main problem)

build.log:
```build.log
Fetching plugin "SplashScreen" via plugin registry
npm http GET http://registry.cordova.io/SplashScreen
npm http 404 http://registry.cordova.io/SplashScreen
```

**Comment by hstaudacher** [comment]
hmm, this seems related to #473 

The build service is not yet CLI 5.x ready. The plugins you want to use cordova-plugin-directions and cordova-plugin-file indicate that they are already npm modules. THey have changed the IDs from org.apache.* to cordova-* with 5.x

**Comment by gosia-eclipsesource** [comment]
Following the update to Cordova 5.1.1 in Tabris.js 1.1, I'm now able to build an app with the current versions of these plugins:
```xml
<plugin name="nl.x-services.plugins.calendar" version="4.3.4" />
<plugin name="cordova-plugin-directions" version="0.4.1" />
<plugin name="cordova-plugin-file" version="2.1.0" />
<plugin name="cordova-plugin-splashscreen" version="2.1.0" />
```
@adenaman Could you check if that solves the issues you encountered?

**Comment by bFlood** [comment]
is there a way to reference a github repo directly from the plugin tag?

**Comment by jonek** [comment]
@bFlood Yes. Just do something like in your Cordova project:
```bash
$ cordova plugin add https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin --save
```
When you take a look into your project's ```config.xml``` afterwards, you will find this line in there:
```xml
<plugin name="nl.x-services.plugins.toast" spec="https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin" />
```

**Comment by bFlood** [comment]
and this will work from your build service? 
thank you @jonek

**Comment by bFlood** [comment]
fwiw, this does work from the tabris build service

also, the sqllite plugin seems work as well. didn't do much testing but the database was created, added tables and rows and then able to query/populate CollectionView. Closing the app and restarting uses the previous database.

`<plugin name="io.litehelpers.cordova.sqlite" spec="https://github.com/litehelpers/Cordova-sqlite-storage" />`
