### ISSUE TITLE
Improve cordova/app documentation

### ISSUE THREAD

**Issue by hstaudacher** [eclipsesource/tabris-js#450]
A guy wrote an article about Tabris.js. He compared Tabris.js, Ionic and React Native. One thing in this article bothers me a lot: 

> Finally, the two have one thing in common: You can use Cordova plugins. But while Ionic is completely connected with Cordova, it feels a bit more natural to use it over there. As I added some Cordova plugins to Tabris.js I was not sure on how to connect the new added plugins with the Tabris app, so I ran into some problems.

I think we need to improve the documentation to make this clear. Will post the link to the article as soon as it is published.

**Comment by tbuschto** [comment]
I have one additional suggestion: Add a prominent tab, page or dialogue to the launcher that lists the installed cordova plug-ins, plus a link to the documentation how to add your own.

**Comment by hstaudacher** [comment]
Good idea. Maybe it can be a typical mobile list and every plugin item links to the specific plugin site. As long as you have the id of a plugin you can generate the link. At the end of the list a prominent button would be great with the text "Add your own".

**Comment by chrwick** [comment]
I would like to point out that the statement from above ("I was not sure on how to connect the new added plugins with the Tabris app") is really something that needs a better documentation, preferably with an example.

Please see #460 and #448.
These issues are related to the fact that the ```require``` does not work properly for the Cordova plugin.

Please see plugin.xml doc from here concerning the ```name``` in the ```<js-module>``` tag: https://cordova.apache.org/docs/en/4.0.0/plugin_ref_spec.md.html

What is the correct identifier to use for ```require```?
The above doc says it would be ```<module-id>.<name>```.
However, this does not seem to work.

Or do I have to use ```cordova.require```and not just ```require``` to find the js-module?
So how do I correctly include the javascript part of a Cordova plugin if I do not the path?

**Comment by hstaudacher** [comment]
`require` != `cordova.require`. Cordova has it's own module system. Good catch, we need to update the documentation and mention this prominently.

**Comment by chrwick** [comment]
Can you give a hint on how or where to find the javascript portion of a Cordova Plugin which is declared with the ```<js-module>``` tag inside plugin.xml?
Do I have to specify a path? Or do I have to specify it by the ID mentioned above?

Example: http://plugins.cordova.io/#/package/com.megster.cordova.ble
How do I import ```www/ble.js``` into my app.js? Or are all objects including the objects from the loaded plugins already available?

**Comment by ralfstx** [comment]
The [build article](https://tabrisjs.com/documentation/latest/build.html) now explains the links between Tabris.js and Cordova quite well and links to the relevant Cordova docs. For plugins there's a [separate article](https://tabrisjs.com/documentation/latest/cordova.html).

**Comment by neryortez** [comment]
> Can you give a hint on how or where to find the javascript portion of a Cordova Plugin which is declared with the <js-module> tag inside plugin.xml?

I also have this question.
Let's say I integrate a plugin adding it to the config.xml.
Now, Where do I go to access that pluging. Do I have to use a require('thePlugin") or something similar?

That's not explained on the documentation.

**Comment by cookieguru** [comment]
@neryortez It depends on the plugin.  You'll have to refer to the plugin's documentation on how to invoke its features.  Most of the time Cordova plugins inject globals so there's nothing you need to do except call the APIs as set forth in the documentation.

**Comment by ralfstx** [comment]
Yes, that seems obvious to us, but apparently, it's not. Let's add your answer to the documentation.

**Comment by mpost** [comment]
We should add the sentence _Most of the time Cordova plugins inject globals so there's nothing you need to do except call the APIs as set forth in the documentation._ from @cookieguru to the docs.

**Comment by cookieguru** [comment]
...as described in the plugin"s documentation
