### ISSUE TITLE
IOS Development Question

### ISSUE THREAD

**Issue by rhg1968** [eclipsesource/tabris-js#452]
I have seen some posts online about creating a p12 certificate using open ssl on a windows machine, but I was wondering can you complete the whole process of developing and pushing to the apple app store from a windows machine or do you absolutely need a mac for certain steps ?

**Comment by jordiboehmelopez** [comment]
Yes, you can complete the whole process of developing and pushing to the apple app store from a windows or linux machine. You don't need a Mac.

**Comment by jordiboehmelopez** [comment]
My comment above only applies to our (free) build service (on tabrisjs.com).
If you wan to build your app on your local machine, not in the cloud, you'll need a Mac with Xcode.
