### ISSUE TITLE
how to extend tabris android theme

### ISSUE THREAD

**Issue by paulocarvalhodesign** [eclipsesource/tabris-js#454]
How can I extend android tsbris theme.
I know we can set some hi bits but I need to know how to extend the default theme . 
The reason I need this is because may app has a bluish background Color and evertime I change page I get the white in the background while it fades in and out .
 I am aware that this is not a bug of any kind but I would like some guidance on this if possible as its a bit of a deal breaker :)

**Comment by jonek** [comment]
Moritz wrote a first [blog post](http://eclipsesource.com/blogs/2015/04/29/customizing-the-appearance-of-a-tabris-js-android-app/) about that topic. He will be able to answer you next week.

**Comment by paulocarvalhodesign** [comment]
I have done some progress and I can extend the activity theme but It shows the background color and straight after that gets overriden by the default tabris theme

**Comment by mpost** [comment]
As @jonek pointed out, a second blog post is on the way. Please stay tuned. :)

**Comment by paulocarvalhodesign** [comment]
Nice one I am well tuned :)

-- 
Paulo Carvalho
Sent with Airmail

On 26 May 2015 at 10:44:25, Moritz Post (notifications@github.com) wrote:

As @jonek pointed out, a second blog post is on the way. Please stay tuned. :)

**Comment by gosia-eclipsesource** [comment]
@paulocarvalhodesign Here is Moritz blog post [about customizing the Android theme](http://eclipsesource.com/blogs/2015/07/03/tabris-js-1-1-sneak-peak-custom-themes-on-android/), which you can already do with Tabris.js 1.1. :)
