### ISSUE TITLE
imageview on Android working in dev app, but not after build/release

### ISSUE THREAD

**Issue by andreasmihm** [eclipsesource/tabris-js#455]
I use a very simple Imageview in my project

imagebutton = tabris.create("ImageView", {
  layoutData: {left: buttonx, top: buttony},
  image: {src: "images/1.jpg"},
  highlightOnTouch: true
}).on("tap", function() {
   imagebutton.dispose();
   calculateTouchTime();
}).appendTo(page);

When I run it using the android tabrisjs dev app, it works correctly and displays the images, but when I build as release, install and run the app on android, it doenst show the image, but only a exclamation mark sign,
![img](https://cloud.githubusercontent.com/assets/1481850/7766016/18dd19fe-0065-11e5-9222-5ba28b7d4cfc.jpg)

The image files are correctly bundled into the apk,

Is that a known issue?

**Comment by andreasmihm** [comment]
btw. there is no debug log message raised

**Comment by jonek** [comment]
It should work. We use images in our examples bundled with the Tabris.js Developer App.
Could you please post the directory structure you are using with the build service?

**Comment by jonek** [comment]
I looked into your public Tabris.js repo "my-tabrisjs-app". You have image files there that end on ".JPG" but in your source code you are using ".jpg".
I would suspect that to be the problem. As URLs are case insensitive the are found on the web server but if you are only working with files inside your app case becomes relevant and the image files are not found anymore. Could you try to rename your image files?

**Comment by andreasmihm** [comment]
problem solved, thx
