### ISSUE TITLE
Provide API to set focus on widget

### ISSUE THREAD

**Issue by rherrmann** [eclipsesource/tabris-js#456]
tabris.js should provide API to set the input focus on a specific widget.
For example
```javascript
var input = tabris.create( "TextInput", { ... } );
input.focus();
// or
page.set( "focus", input );
```

**Comment by bFlood** [comment]
+1

**Comment by bFlood** [comment]
any word on this? we have a lot of users who want textviews to receive focus immediately (so the keyboard appears automatically ). Tapping them to receive focus is not a huge effort but for text entries that are used all the time, that one extra steps adds up quickly

thanks

**Comment by mpost** [comment]
This makes sense. Should be a feature to add.

**Comment by sand123** [comment]
Definitly should be implemented - to avoid annoying "Tap to input text" remark below input field

**Comment by mpost** [comment]
We are seeing the value of such a feature and plan to create an API like:

```js
inputText.focus(); // to request the focus
inputText.blur(); // to remove the focus
```

**Comment by ralfstx** [comment]
@tbuschto brought up the question why we don't implement it as a property, e.g. `widget.set('focused', true)`. A property would also allow to query the focused state of a widget. It would be an interactive property, i.e. it can change on the client. Also focusing one widget would reset another widget's `focused` state. However, thinking about tabs or radio buttons, this behavior doesn't seem uncommon.
