### ISSUE TITLE
Integrate Gitter

### ISSUE THREAD

**Issue by hstaudacher** [eclipsesource/tabris-js#461]
I think this would be the perfect additions to our issue based communication, see https://gitter.im/

**Comment by ralfstx** [comment]
It seems that noone from the team is around there yet. Unless we use it as a public developer chat ourselves, it's unlikely that anyone from the team will be around. This would be frustrating for users.

**Comment by ralfstx** [comment]
We agreed not to adopt Gitter at the moment because we probably won't be able to keep up with yet another communication channel. If there is real interest from the community, we'll look for alternatives.
