### ISSUE TITLE
Functional JSON api to native layer

### ISSUE THREAD

**Issue by FrigoEU** [eclipsesource/tabris-js#462]
Hey everybody. 

I just saw the Tabris demo after reading about it on InfoQ and I got intrigued. Especially the part about the architecture being just json sent back and forth between the js engine and the native layer. 

The current API is very much object-oriented, nothing wrong with that. However I do most of my work nowadays in PureScript. Do you think it's possible for a 3rd party developer (aka me) to fully skip the current OO api and directly talk json to the native layer by using the functional paradigm? 

Thanks for any info!

**Comment by jonek** [comment]
I would guess that it would be a very tedious undertaking and basically a non-object-oriented "re-implementation" of the Tabris.js JS part. The JS part of Tabris.js contains quite some functionality on-top of the mere JSON protocol. Just take a look at the code in this very repository. We also do not currently have any written specification of the JSON-protocol. I guess you would require such a thing. If you don't like the JS API of Tabris.js, I would propose to wrap it into something that serves you better.

**Comment by FrigoEU** [comment]
Thanks for the response! Indeed a specification of the JSON-protocol would be what I need. Wrapping the current JS API is indeed also a possibility, but I was thinking that talking the JSON-protocol directly would be much more efficient. Thanks!

**Comment by ralfstx** [comment]
Closing this old issue with a pointer to the [doc on custom widgets](https://tabrisjs.com/tabris-js-docs/latest/custom-widgets.html) - the way to go for Tabris.js 2.0.
