### ISSUE TITLE
Ignore case when searching for local resources (images)

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js#465]
See #455

**Comment by ralfstx** [comment]
Quoting from #455:

> As URLs are case insensitive the files are found on the web server but if you are only working with files inside your app case becomes relevant and the image files are not found anymore.

It's not true that URLs are generally case insensitive. The http server only delivers a resource with misspelled case when the underlying file system is case insensitive, as it is the case on Windows.

Case-insensitive names are a common cause of errors. Therefore I'm strongly opposed to introducing case insensitivity in Tabris.js. Please reopen if you disagree.
