### ISSUE TITLE
developing with cordova

### ISSUE THREAD

**Issue by andreasmihm** [eclipsesource/tabris-js#466]
https://tabrisjs.com/documentation/1.0/cordova

Do I read it correct, that when developing with cordova plugins other than the ones integrated in the tabrisjs dev app, I can only test with a build, but not during development?

**Comment by hstaudacher** [comment]
hmm, test with a build does not mean "not during development". If you want to integrate own plugins you need to build your own app. But with the build option "debug" = true it will build your custom tabrisjs dev app.

**Comment by andreasmihm** [comment]
ok
