### ISSUE TITLE
Add possibility to modify requests

### ISSUE THREAD

**Issue by hstaudacher** [eclipsesource/tabris-js#468]
For some services e.g. tabrisjs.com or github.com authorization is required. This means sending tokens as query or header parameter for every request to those domains. This includes:
- requests made from require statements
- resource loading e.g. images
- XMLHttpRequest requests

It would be nice to have the possibility to set persistent request attributes. E.g. `tabris.setRequestParameter( "https://tabrisjs.com/.*", "token", "value" );` or something like this. Of course parameters are not enough, it should also be possible to set headers and so on.

**Comment by tbuschto** [comment]
This has been implemented for a while for XHR/fetch. For require statements I don't think this is required. Loading images that require authentication can be done by downloading them via fetch, storing them on disc and loading them from there. Therefore I will close this issue.
