### ISSUE TITLE
Round corners and drop shadow on widgets

### ISSUE THREAD

**Issue by bev-on** [eclipsesource/tabris-js#469]
Is there any way to add shadow and round corners on widgets?

Example from Google Play Store
![Image](http://i.imgur.com/nGsQVGK.png?1)

**Comment by jonek** [comment]
Which widgets do you have in mind?

**Comment by bev-on** [comment]
Buttons and text inputs for example

**Comment by mpost** [comment]
Currently you would have to create separate images for the parts an assemble them manually.

**Comment by bev-on** [comment]
This is exactly  what I'm doing and not enjoying to do so :) Hope there will be some solution for this in next updates.

**Comment by jonek** [comment]
If we had the API to add custom widgets to Tabris.js already, the feature described in this issue could be implemented as a custom widget that wraps the Android Material Design [CardView](https://developer.android.com/training/material/lists-cards.html#CardView).

@mpost Maybe we can use this issue as an example for the upcoming custom widget API?

**Comment by bev-on** [comment]
Thanks @jonek. Great idea!

**Comment by gosia-eclipsesource** [comment]
We'll be working on the round corners part and track progress in #728.

**Comment by mpost** [comment]
With the properties `cornerRadius` and `elevation` this has been made possible.
