### ISSUE TITLE
Support animations

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#47]
We should provide a way to define animations in JavaScript.
Examples are:
- fade in / out
- move, resize
- page turning
- flip page

[1] http://www.polymer-project.org/platform/web-animations.html

**Comment by natanraj** [comment]
@mpost : Could we animate hide ? .animate({visible: true}, {duration: 1000}) something like this ? I am tryign this, but in vain. Reading your post now, I see only 8 attributes are supported

**Comment by ralfstx** [comment]
@natanraj You can animate `opacity`.
