### ISSUE TITLE
Provide tabris-js http-server

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#471]
A custom http-server would solve several problems:
1. Fix case-insensitivity (See #455)
2. Prevent unnecessary requests by sending file list.
3. Do not send generated index.html confusing the client.

The whole thing would not break support for other http-server.

I already have a draft for the server and the necessary module system enhancements, so it's mostly just committing to a name, internal API, etc.

**Comment by ralfstx** [comment]
The node http-server module sends a `Cache-Control` header with a value of `max-age=3600` by default. This default is unsuitable for the developer client, as it allows the client to cache files for one hour. At least for JSON files, the Android client indeed does not request files again once they're downloaded. Changes to those files during a debug session will not be discovered by the client.

A custom HTTP server should come with a reasonable default (e.g. use etags, but no max-age).

The caching can be turned off using the parameter `-c-1`.

**Comment by tbuschto** [comment]
will be dealt with as part of #760
