### ISSUE TITLE
Support Cordova 5

### ISSUE THREAD

**Issue by chrwick** [eclipsesource/tabris-js#473]
The Cordova docs say:
To include a plugin from npm specify npm in the source attribute.
```
<gap:plugin name="example-plugin" source="npm" />
```
I have tried this with
```
 <gap:plugin name="cordova-plugin-websocket" source="npm" />
```
The build service failes, because it does not respect the "source" parameter.

According to this announcement, the Cordova plugins are moving to npm:
https://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

**Comment by hstaudacher** [comment]
Tabris.js 1.0 was tested and is compatible with Cordova 4.x. The build service currently does not support 5.x

We will investigate and upgrade asap. Thanks for reporting

**Comment by hstaudacher** [comment]
We have updated to Cordova 5.1.1. You can already use the new version when setting the Tabris.js Version to `nightly` within the online build service. Please note that you don't need to use gap:plugin anymore. Cordova 5 support a simple plugin element in the config.xml now. A sample usage looks like this:

```xml
<?xml version='1.0' encoding='utf-8'?>
<widget
    id="my.first.app"
    version="1.0.0"
    xmlns="http://www.w3.org/ns/widgets"
    xmlns:cdv="http://cordova.apache.org/ns/1.0">
    ...
  <plugin name="cordova-plugin-camera" version="1.2.0" />
  <plugin name="cordova-plugin-dialogs" version="1.1.1" />
</widget>
```

**Comment by bFlood** [comment]
I'm seeing this error on the tabris build server now, this worked fine a month ago

```Failed to install 'cordova-plugin-camera':CordovaError: Plugin doesn't support this project's cordova-android version. cordova-android: 4.0.2, failed version requirement: >=5.0.0-dev```

**Comment by mpost** [comment]
The cordova version we support is 5, but each platform has its own version number. Therefore you should reference the older plugin name as stated here: https://github.com/apache/cordova-plugin-camera until we have added support for the cordova android 5.

**Comment by bFlood** [comment]
how would I do that from the tabris.js build service? what is the proper syntax for referencing older plugin version from config.xml?

**Comment by mpost** [comment]
Have you tried a concrete version number in you config.xml?
```xml
<plugin name="cordova-plugin-camera" version="1.2.0" />
```
See here for details https://tabrisjs.com/documentation/latest/build#adding-plugins

**Comment by bFlood** [comment]
this works, not sure why I had the older plugin tag code that used repo directly and not npm

thanks!

**Comment by mpost** [comment]
Great to hear that it worked. Thanks for the info.
