### ISSUE TITLE
Version mismatch: Javascript module and native tabris platform

### ISSUE THREAD

**Issue by chrwick** [eclipsesource/tabris-js#475]
I get a warning in the dev console:
```
Version mismatch: Javascript module "tabris" (version 1.0.1) is newer than the native tabris platform. Supported module versions: 1.0.0 to 1.0.0
```

The package.json file includes version 1.0.0 for tabris as dependency, while the build service setting contains the setting "latest".

I wonder how this could match the above warning. 
I would expect the opposite: a newer native platform and an older js module, because of my settings.

**Comment by hstaudacher** [comment]
Wow, this is strange. I have no idea how it gets the 1.0.1. We need to investigate. Thanks for reporting.

**Comment by ralfstx** [comment]
Moreover, I doubt if a newer patch version should really raise a warning (#477).

**Comment by chrwick** [comment]
This is the package.json file content:

https://github.com/chrwick/my-tabrisjs-app/blob/master/www/package.json

I have noticed that in your repository (->examples) their is a difference in the master branch:
```
"tabris": "^1.0.0"
```
while in older versions it is just:
```
"tabris": "1.0.0"
```

**Comment by hstaudacher** [comment]
I wonder how it gets the 1.0.1 because on npmjs.org only version 1.0.0 is published. @ralfstx any idea?

**Comment by hstaudacher** [comment]
Btw. we can exclude a bug in the build service for this. If the tabris.js version in the build service is set to latest and the service would use a "nightly" version the validation message on the client would say that the native parts are newer and not that the js parts are newer.

**Comment by chrwick** [comment]
I would like to add that it does not seem to happen if your start the bundled script the first time.
It also does not happen if you click on the "reload" circle in the dev console.
It only seems to happen if you have the app running and then click on the home ("house") icon in the dev console.

**Comment by chrwick** [comment]
And it happens on both - iOS and Android versions. 
Only if the home button is clicked while the app is running.

**Comment by hstaudacher** [comment]
Ok, found the reason for this bug. The released 1.0 dev app which is used contains a dependency to tabris.js nightly instead of 1.0.0. Will fix it now.

**Comment by hstaudacher** [comment]
Alright, it's fixed. Can you build you app again and report if it's gone?

**Comment by chrwick** [comment]
The message is gone now.

Thanks!

**Comment by hstaudacher** [comment]
perfect. Will close this issue now.
