### ISSUE TITLE
Support cordova plug-in "com.megster.cordova.ble "

### ISSUE THREAD

**Issue by chrwick** [eclipsesource/tabris-js#476]
I have tested the module on Android 4.4 and iOS 8.3.
Unfortunately, it does not seem to work.

This is the test code:
```
ble.startScan([], 
                  function(device) {
                    console.log(JSON.stringify(device));
                  }, 
                  function(reason) {
                    console.log("Error: " + reason);
                  }
              );

setTimeout(function() {
    ble.stopScan(
        function() { console.log("Scan complete"); },
        function() { console.log("stopScan failed"); }
    );
}, 5000);
```

You can easily test this by using another smartphone or tablet with a BLE app that can be used as BLE peripheral. 
So the above code should scan for BLE devices and show each discovered device on the console.
The ```setTimeout()``` function is working only if used in this way, because of #474.

**Comment by gosia-eclipsesource** [comment]
The referenced issue #474 has been fixed. @chrwick Could you please confirm if this one still persists?

**Comment by chrwick** [comment]
I am not evaluating Tarbis.js anymore, sorry.
