### ISSUE TITLE
My App in developer mode - accessing bundled scripts from scratchpad

### ISSUE THREAD

**Issue by chrwick** [eclipsesource/tabris-js#478]
While it seems to be possible to access custom bundled Cordova plugins from the scratchpad in my generated app in debug mode, it does not seem to be possible to access bundled scripts that are included in the custom app.

I would like to access the bundled jquery script in the app from the scratchpad:
`var $ = require("./lib/jquery.min.js");`

Would it be possible to add this feature?

**Comment by chrwick** [comment]
Can you confirm that my observation from above is correct?
It would be nice to know what directory structure the build service uses when the project is being built.

**Comment by hstaudacher** [comment]
hmm, when you are using the scratchpad basically a URL is used to load the app. The lookup to `./lib/jquery.min.js` should be done locally first. If it's not available the URL will be used joined with `./lib/jquery.min.js`. @ralfstx @mpost @jordiboehmelopez can you confirm or is the local lookup not made when the base URL is http?

**Comment by chrwick** [comment]
My scratchpad and the app.js file look like this:

```
// jQuery built with "grunt custom:-ajax/script,-ajax/jsonp,-css,-deprecated,-dimensions,-effects,-event,-event/alias,-offset,-wrap,-ready,-deferred,-exports/amd,-sizzle"
// https://github.com/jquery/jquery#how-to-build-your-own-jquery
var $ = require("./lib/jquery.min.js");

$.getJSON("http://www.telize.com/geoip", function(json) {
  console.log("The IP address is: " + json.ip);
  console.log("Latitude: " + json.latitude);
  console.log("Longitude: " + json.longitude);
});
```

It is the jquery.min.js from your repository here: 
https://github.com/eclipsesource/tabris-js/blob/903746012b3576d484a9f3736f9b8d96dbc2cb49/examples/jquery/lib/jquery.min.js
I have copied it to a subfolder "lib". 

This is how the dir structure looks like:
https://github.com/chrwick/my-tabrisjs-app

**Comment by jordiboehmelopez** [comment]
This is how it works on iOS:
Relative paths are by default relative to the URL you have loaded your App from: http(s): or file:

This default behavior can be "overwritten" by configuring `localResourceRoots` ... which is by default the `www` folder for the app in the Apple App Store . So the app searches first in the `www` for relative resources.

In your case it would try to load `file://<appbundlepath>/www/lib/jquery.min.js` before it loads `https://github.com/eclipsesource/tabris-js/blob/903746012b3576d484a9f3736f9b8d96dbc2cb49/examples/jquery/lib/jquery.min.js`.

So it comes down to check if:
1. is the `www` folder configured in `localResourceRoots`
2. does the `www` folder contain `lib/jquery.min.js`

**Comment by chrwick** [comment]
I think there is small misunderstanding. I am not trying to load anything remotely.
I have just **copied** the ```jquery.min.js``` from the remote URL to ```www/lib```.

1. Where can I specify ```localResourceRoots```? I do not have access to "local builds" as I am using the free plan. So I am just relying on my GitHub repo and the build service.
2. The ```www``` folder contains ```lib/jquery.min.js```

This is my test project:
https://github.com/chrwick/my-tabrisjs-app

**Comment by chrwick** [comment]
I cannot get it to work for now which really slows down testing with the scratchpad, because I have to do a new build every time with the build service.

I have also tried the way of having a local dependency in the ```package.json``` file of the ```app.js``` by creating a local package of the jQuery script with this ```package.json```:
```
{
  "name": "jQuery",
  "version": "1.0.0",
  "description": "",
  "main": "jquery.min.js",
  "author": "",
  "license": "GPL"
}
```

The ```app.js```file looks like this then:
```
{
  "name": "my-app",
  "description": "My first Tabris.js app",
  "main": "app.js",
  "dependencies": {
    "tabris": "1.0.0",
    "jQuery": "./lib/jQuery/"
  }
}
```

So I could just use something like ```var $ = require('jQuery');```
While this **works** in **bundled script mode** in my generated app, it does **not work** in **scratchpad mode** using the generazed app on iOS.

**Comment by ralfstx** [comment]
The scratchpad is targeted at beginners who want to try out some simple snippets. We don't intend to provide for accessing other npm modules or cordova plugins.

You can use the [Tabris CLI](https://www.npmjs.com/package/tabris-cli) to host your JS code locally and load it from you'r app's developer console.
