### ISSUE TITLE
Allow to install patches from a URL

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#479]
Deploying a new version of an app requires a full replacement of the ipa/apk. Being able to apply a patch to running applications would allow to provide fixes for critical issues much faster. This may even be used for Apple App Store apps when the patch does *not change the primary purpose of the app by providing features or functionality that are inconsistent with the intended and advertised purpose
(iOS Developer Program License Agreement section 3.3.2).*

The clients would have to download a patch zip and extract it to a location on the local filesystem. After reloading the app, resources available in this patch would effectively override local resources.

**Comment by chrwick** [comment]
Is this okay with Apple app store rules?

**Comment by chrwick** [comment]
From Apple Store approval guidelines: https://developer.apple.com/app-store/review/guidelines/

"Clause 2.7: Apps that download code in any way or form will be rejected"
"Clause 2.8 Apps that install or launch other executable code will be rejected"

The common sense about these guidelines seems to be that **after** the approval by Apple, the functionality is **no**t allowed to change afterwards by exchanging code.

I have found hints in the web that even screenshots in the Apple app store are subject to this. 
So no screenshots may be changed after the approval process.

**Comment by jkrause** [comment]
The answer has two parts:
A. The iOS Developer Program Agreement (Section 3.3.2) contains the following paragraph:

> An Application may not download or install executable code.  Interpreted code may only be used in an Application if all scripts, code and interpreters are packaged in the Application and not downloaded. The only exception to the foregoing is scripts and code downloaded and run by Apple's built-in WebKit framework or JavascriptCore, provided that such scripts and code do not change the primary purpose of the Application by providing features or functionality that are inconsistent with the intended and advertised purpose of the Application as submitted to the App Store.*

With Tabris.js the downloaded code is run by Apple's built-in Javascript Core, so if you adhere to the other rules that are put up you should be fine.

B. Tabris.js is not only intended for the App-Store apps, but also for Enterprise distribution, which benefits hugely from this feature.

**Comment by paulocarvalhodesign** [comment]
Would be good to try and replicate : 
http://docs.ionic.io/v1.0/docs/deploy-install

**Comment by ralfstx** [comment]
Request for comment:

#### API
Our current idea is to introduce a single method `installPatch` on the `tabris.app` object. This method accepts a URL and a callback (alternatively return a Promise). The process of checking for patches, keeping track of the current patch level if needed, determining the patch download URL etc. is up the application. This provides maximum flexibility for applications to adjust this process to their needs.

#### Native bridge protocol
* JS requests installation of a patch by a *call* operation `installPatch` on the `tabris.App` object. The method parameter `url` contains the URL as string.
* Clients download the patch and install it, but the patch must not be applied before the next reload of the App.
* After successful installation, clients must send the *event* `patchInstalled` to the `tabris.App` object. The app can then trigger a reload, resulting in a `reload` *call*.
* In case of a failure, clients must send the *event* `patchInstallFailed` instead. The parameter `error` should contain an error message (string).
* Clients *must* respond with exactly one event, either `patchInstalled` or `patchInstallFailed`.

#### Patch format
* The patch URL must point to a zip file. The zip must contain a subfolder `files` (?) that contains files to overlay the local application's resources. This allows us to support metadata, post-install scripts etc. later on.
* Patches are cumulative, that is, if multiple patches are installed, they add up. It's up to the application to either pre-merge patches on the server or to provide cumulative patches based on the client's patch level.

**Comment by sand123** [comment]
Great! Exactly what I want. Now I load patch code via AJAX, store in localStorage and eval on app start - but it's not acceptable for production

**Comment by jordiboehmelopez** [comment]
If patches should be cumulative, how can you get rid of them once an "official" App Store updated is released - and the patches should not be used any more?

**Comment by ralfstx** [comment]
Good point. We agreed that the clients are responsible for cleaning up patches. I've updated the RFC accordingly.

**Comment by ralfstx** [comment]
Another amendment: We agreed that patch zip files should contain a file `patch.json`. The contents of this file are provided in the `patchInstalled` event. I've added this to the RFC above.

**Comment by ralfstx** [comment]
We agreed to merge the two events `patchInstalled` and `patchInstallFailed` into a single event `patchInstall` with either an `error` or a `success` parameter.
