### ISSUE TITLE
blank login page on dev app when it is used in China

### ISSUE THREAD

**Issue by newhow** [eclipsesource/tabris-js#480]
Everything works fine when I was in the US a month ago. But I can't login any more after I moved to China mainland. When I tap the login button, a blank view appears instead of a Github login form. 

I am guessing this is due to the fact that China blocks all Google stuff, including any javascripts tabris may use in login process. I can login smoothly into Github from China. So I am thinking the login problem is caused by Google stuff.

I can't find any stable and free VPN service provider. So I am asking here for helps. Thank you.

**Comment by hstaudacher** [comment]
phew. A few month ago someone reported a similar problem. We removed all google.com stuff and do self host it now.

Anyway, maybe it has something to do with the google analytics tracking inside the app. We need to investigate. @ifurnadjiev do you takeover?

**Comment by ifurnadjiev** [comment]
Today I tried 3 different China proxies on my phone and the result is blocked tabrisjs.com web site. Both developer app and Android browser return "page not found" error.

**Comment by newhow** [comment]
The github login form on dev app does not show. I don't understand how this problem relates to tabrisjs.com?

Hao Liu

**Comment by jonek** [comment]
@newhow As @ifurnadjiev already said, http://tabrisjs.com seems not to be reachable from within China. The Tabris.js developer app make extensive use of web services provided by http://tabrisjs.com an OAuth login with GitHub, so everything that requires to be logged into (i.e. identified by) a GitHub account does not work if http://tabrisjs.com is not reachable for you.

What exactly do you want to achive? Can you access http://tabrisjs.com from within your browser? Can you log into http://tabrisjs.com from within your browser e.g. to use our build service?
