### ISSUE TITLE
Gif image not running 

### ISSUE THREAD

**Issue by radiegtya** [eclipsesource/tabris-js#482]
I am using ImageView and load gif image, but why the animation not running?

**Comment by mpost** [comment]
An ImageView does not support the animation of gif images.

**Comment by radiegtya** [comment]
@mpost : so what should I do to display gif image?

**Comment by mpost** [comment]
@radiegtya At the moment you could use a WebView widget to display the animated gif.

**Comment by radiegtya** [comment]
@mpost : thanks for the answer, but I can't using html properties on WebView, only url properties which is working. Any idea about this?

**Comment by jkrause** [comment]
This snippet works for me

```
var page = tabris.create("Page", {
  title: "Web View",
  topLevel: true
});

var webview = tabris.create("WebView", {
  layoutData: {left: 0, top: [urlInput, 8], right: 0, bottom: 0},
  html: "<html><body><img src='https://raw.githubusercontent.com/eclipsesource/tabris-js/master/examples/animation/images/animation-tray-android.gif'></body></html>"
}).appendTo(page);

page.open();
```

**Comment by radiegtya** [comment]
those snippet not working on my phone. it's only print a text on my webview.
LG L9 optimus.

**Comment by radiegtya** [comment]
Oh I see, it's because my android version 4.1.2 causing this problem. Will tabris support this android version? Because I think there are still many people using older version android

**Comment by mpost** [comment]
The above snippet references a none existing widget. I have updated it to be correct. Does that work for you?

**Comment by mpost** [comment]
Some more research showed that there is indeed a problem with the webview on older devices when rendering html directly. Below android 4.4 the webview was based on the native android web renderer and not on chrome. We will fix that asap.

**Comment by jonek** [comment]
@radiegtya: We fixed the underlying problem in that latest release of Tabris.js. Could you please try to execute the snippet that shows the animated gif in the WebView on your phone again using the latest Tabris.js Developer App? Please close this issue if thing are working for you now.

**Comment by mpost** [comment]
The question might be if we want to also support gif in ImageViews not only in the WebView (which is not the best place to show them).

**Comment by natanraj** [comment]
@mpost Any idea when can we expect the gif support on ImageView ?

**Comment by mpost** [comment]
@natanraj Currently there is no planned support for it. A custom widget could be created for it.

**Comment by mpost** [comment]
No immediate progress.

**Comment by cookieguru** [comment]
Support for animated gifs is being tracked in #1884
