### ISSUE TITLE
Back Button to Main Page

### ISSUE THREAD

**Issue by radiegtya** [eclipsesource/tabris-js#483]
How to make back button to main page?

**Comment by jkrause** [comment]
Did you have a look here? https://tabrisjs.com/documentation/1.0/ui

**Comment by radiegtya** [comment]
yes I did, but I need to link the back button not only redirect to previous opened page but able to back to main page, and I don't know how to do that

```
tabris.create("Page", {
  title: "My Second Page",
}).on('backButtonPressed', function(){
  anotherPage.open();
  console.log("is it possible with tabris?")
});
```

**Comment by mpost** [comment]
The described scenario is currently not possible. We are aware of possible use cases and are investigating how to enable this workflow. Stay tuned.

**Comment by mpost** [comment]
After some discussion we decided to go for a solution that would allow the user to attach a listener which is called and called upon back button invocation. In the listener he could perform some custom logic and decide whether he wants to continue with the normal back button behavior (eg closing a page) or break the chain to do something else.

How exactly the canceling of the normal back flow is performed is up to debate. Possibly by a property or function call on the event object.

**Comment by wilsonna** [comment]
looking forward to this :) @mpost could use a syntax similar to jquery i.e. event.stopPropagation()

**Comment by mpost** [comment]
@wilsonna A similar approach is high on our list of possible APIs.

**Comment by sand123** [comment]
I also asked about similar functionality in #548

**Comment by mpost** [comment]
@sand123 The answer provided in #548 is still correct. You should use topLevel pages and sub pages to drill down into content.

**Comment by tbuschto** [comment]
#548 is closed, so can we close this?

**Comment by mpost** [comment]
I would say yes.
