### ISSUE TITLE
Location path with Cordova Media /  File plugin

### ISSUE THREAD

**Issue by calebeaires** [eclipsesource/tabris-js#484]
org.apache.cordova.media cant find the correct path from the MP3 file, even if org.apache.cordova.file is used.

Code error: 1 (from here: https://github.com/apache/cordova-plugin-media)

**Comment by jkrause** [comment]
Could you please specify your mobile operating system (iOS / Android) and its version. It would also be good if you provided a minimal snippet.

**Comment by calebeaires** [comment]
Doesn't work:
```
var asset = cordova.file.applicationDirectory + '/www/ambient.mp3';
var media = new Media(asset, onSuccess, onError);
media.play();
```

Doesn't work:
```
var asset = cordova.file.applicationDirectory + '/Epoq-Lepidoptera.ogg';
var media = new Media(asset, onSuccess, onError);
media.play();
```

Doesn't work:
```
var asset = 'Epoq-Lepidoptera.ogg'; 
var media = new Media(asset, onSuccess, onError);
media.play();
```

but, it works:
```
var media = new Media('http://www.vorbis.com/music/Epoq-Lepidoptera.ogg', onSuccess, onError);
media.play();
```

**Comment by calebeaires** [comment]
After some try, I got this working on debug app. Does release app use this path too?
```
    asset = 'file:///android_asset/www/bundled_tabris_js_launcher/user_app/a.amr';
    media = new Media(asset, function() {
        console.log("ok")
    }, function(r) {
        console.log("0", r)
    });

    media.play();
```

**Comment by jonek** [comment]
@calebeaires How did you come up with the 'file:///android_asset/www/bundled_tabris_js_launcher/user_app/a.amr' URL to the asset. Where does the a.amr file come from? Do you bundle it together with your application at build time or are you recording it during runtime? Are you using the file plugin to make the asset available to the new Media()?

Pleas provide this info and then we can look into it.

Please also let us know what you want to achieve and where you think Tabris.js is lacking functionality.

**Comment by calebeaires** [comment]
1. The Media Cordova plugin couldn't play the Audio because it couldn't find the audio file path. I just unzip the APK to find out where does trabis put the "app" assets. After I have figure out it, I just configure the javascript to get the file on the right place. 

2. a.amr is a single audio file: http://developer.android.com/guide/appendix/media-formats.html

3. I have used http-server to play with this issue.

**Comment by jonek** [comment]
Ok, there are a couple of problems with your approach.

1. Your string holding the path to the bundled a.amr media file will only work on Android. (On iOS the path is a different one!)
2. You only know the absolute path after extracting you apk. (Everything else is only guessing.)
3. There is currently no reliable way to get the absolute path of a bundled resource (independently of the native platform!) in Tabris.js.

For the last point I opened the new issue: #592.

Please confirm that this would solve your problem.

**Comment by iteearmah** [comment]
How can I append these plugins to widgets like TabFolder and composite

**Comment by cookieguru** [comment]
> How can I append these plugins to widgets like TabFolder and composite

The Cordova Media plugin doesn't have any UI functionality.  Instead it is invoked via your code in a way you determine.  Looking at some sample code from the [Cordova Media readme](https://github.com/apache/cordova-plugin-media#readme):
```js
var my_media = new Media('http://example.com/file.mp3');
my_media.play();
```
If you wanted to play the file when a button is tapped:
```js
new tabris.Button({
  text: "Play media",
}).on("select", function() {
  my_media.play();
}).appendTo(page);
```

**Comment by iteearmah** [comment]
how about UI based pluigin like https://github.com/nchutchind/cordova-plugin-streaming-media.git

**Comment by oussaki** [comment]
How about ios did anyone knows the path of assets in IOS ?

**Comment by cookieguru** [comment]
@oussaki Take a look at eed37ea21642ddb3fc07b7a2812a9a82cbabf679 for a sample, but note that commit was later reverted due to path issues.

**Comment by oussaki** [comment]
so there is no way to use a path like android this way : 
myMedia = new Media("/android_asset/www/ar/assets/audio/csharp.mp3");
OR using CDVFILE
 myMedia = new Media("cdvfile://localhost/en/assets/audio/jazz.mp3");

this last one i dont know how to really use it with IOS i don;t know if the path is correct or not 
for android the first code woks fine for me .

**Comment by cookieguru** [comment]
@oussaki You can also try [`getResourceLocationPath()`](https://tabrisjs.com/documentation/latest/api/app#getresourcelocationpath)
