### ISSUE TITLE
Pushbots cordova plugin build failed

### ISSUE THREAD

**Issue by radiegtya** [eclipsesource/tabris-js#486]
Hello there, I tried to add https://pushbots.com cordova plugin to my build app but no luck (failing build).

here are the error logs: https://gist.github.com/radiegtya/532c9440ab905c2bae7a

here my cordova setting for my simple app (cordova/config.xml):

```
<?xml version='1.0' encoding='utf-8'?>
<widget 
    id="tabris.pushbot" 
    xmlns:gap="http://phonegap.com/ns/1.0"
    xmlns="http://www.w3.org/ns/widgets"
    xmlns:cdv="http://cordova.apache.org/ns/1.0"
    version="1.0.0">
    <name>Pushbot Test</name>
    <description>
        A sample Tabris.js application PUSHBOT.
    </description>
    <author email="radiegtya@gmail.com" href="https://tabrisjs.com">
        Radiegtya
    </author>
    <gap:plugin name="com.pushbots.push" version="1.2.3" source="plugins.cordova.io" />
    <access origin="*.pushbots.com" />
</widget>
```

and here my simple code to receive push notif

```
var page = tabris.create("Page", {
    title: "Test Pushbot",
    topLevel: true
});

//init pushbots
if (PushbotsPlugin.isAndroid()) {
    PushbotsPlugin.initializeAndroid("55802c4117795971628b4567", "421100931770");
}

var myTextView = tabris.create("TextView", {
    layoutData: {centerX: 0, centerY: 0},
    text: "Hello Pushbot"
}).appendTo(page);

page.open();

      
```

Please help, thanks

**Comment by hstaudacher** [comment]
Seems like a problem with the Cordova Android Integration. @mpost can you confirm?

**Comment by mpost** [comment]
The problem originates from the fact that the cordova plugin brings along dependencies to a third party library (android.support.v4) that is already included in the tabris-client itself. The pushbots plugin simply places a jar file onto the classpath instead of referencing it as a gradle dependency which would allow gradle to resolve the conflict (aka use the newer one).

**Comment by radiegtya** [comment]
So what should I do @mpost ? thanks

**Comment by mpost** [comment]
@radiegtya We are currently discussion solutions on how to improve the situation. Please stay tuned.

**Comment by gosia-eclipsesource** [comment]
@radiegtya Could you build the app again but select "nightly" in the build service?

**Comment by radiegtya** [comment]
@gosia-eclipsesource : I had set it to nightly build. but still failed

**Comment by gosia-eclipsesource** [comment]
@radiegtya Thanks for checking. Unfortunately we will have to wait till Cordova Android build provides better gradle support. We're keeping this issue open so we will update you when we are able to support this plugin.

**Comment by mpost** [comment]
The [pushbots-cordova-plugin](https://github.com/pushbots/phonegap) has been updated to play nice with the gradle based cordova build. Please retry with the latest version and let us know how it works for you. Closing this for now.
