### ISSUE TITLE
How to add android manifest permission such as geolocation

### ISSUE THREAD

**Issue by radiegtya** [eclipsesource/tabris-js#487]
```
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
```

where can I able to add those line?

**Comment by hstaudacher** [comment]
If you are using Cordova Plugins to determine e.g. geolocation the plugin is responsible for adding the permissions. 

Anyway, if you want to modify them by yourself during build time you can create a build hook. A good starting point for hooks is this article: http://devgirl.org/2013/11/12/three-hooks-your-cordovaphonegap-project-needs/

**Comment by hstaudacher** [comment]
This is also a good read http://forum.ionicframework.com/t/cordova-ionic-cli-hooks-for-modifying-androidmanifest-xml-or-ios-plist-file/12293

**Comment by radiegtya** [comment]
@hstaudacher : it seems that I should using tabris pro pricing to do that? Am I right? Because I had trying hook using tabris online builder and have no luck.

**Comment by hstaudacher** [comment]
The online build service simply does a cordova build and we also using some hooks. So, no you don't actually need a local build. of course it would be faster to develop because you don;t need to push any update. Have you added the hooks to your config.xml?

**Comment by radiegtya** [comment]
What should I add into config.xml? can You give example? because I can't find that config.xml should be modified in this tutorial. http://devgirl.org/2013/11/12/three-hooks-your-cordovaphonegap-project-needs/

**Comment by jonek** [comment]
Please take a look at the Tabris.js documentation about adding Cordova
Plugins to your project when using the build service:
https://tabrisjs.com/documentation/1.0/build#adding-plugins

**Comment by hstaudacher** [comment]
@radiegtya here is the official hook guide http://cordova.apache.org/docs/en/edge/guide_appdev_hooks_index.md.html#Hooks%20Guide

**Comment by jonek** [comment]
@radiegtya As Holger said before. to enable the required permissions on Android to enable geolocation support just add the geolocation Cordova Plugin to you project. You do not need to enable those Android permission yourself.

**Comment by jonek** [comment]
@radiegtya Can you please try to add this line to your ```config.xml```?

```
...
 <gap:plugin name="org.apache.cordova.core.geolocation" />
...
```

**Comment by radiegtya** [comment]
I did, but still it says geolocation not supported .

I tried in main.js

```
if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(showPosition);
} else {
   window.plugins.toast.showShortCenter("Geolocation is not supported by this browser.");
}
```

and ofc adding this line on config.xml (btw you provide wrong cordova plugin link org.apache.cordova.core.geolocation, which the right one was org.apache.cordova.geolocation)
```
<gap:plugin name="org.apache.cordova.geolocation" /> 
```

the app still said that geolocation not supported

Thanks

**Comment by mpost** [comment]
We have taken a look at this particular plugin. While the permissions are added correctly on Android the plugin does not add any other native code on Android.

As stated in the docs "This plugin defines a global navigator.geolocation object (for platforms where it is otherwise missing).". 

Unfortunately for us, Android is such a platform where `navigator.geloaction` is natively available in the WebView. Therefore the plugin does not add any native functionality on Android as we can see by the lack of Android specific code here: https://github.com/apache/cordova-plugin-geolocation/tree/master/src

To incorporate geolocation support you should use a different cordova plugin.

**Comment by wilsonna** [comment]
Please try this plugin https://github.com/Moussawi7/Cordova-GPSLocator . It's a little basic, but it works for me.
