### ISSUE TITLE
Support cordova plug-in "com.couchbase.lite.phonegap"

### ISSUE THREAD

**Issue by chgerkens** [eclipsesource/tabris-js#490]
Build fails when adding cordova plug-in "com.couchbase.lite.phonegap" due to "duplicate files during packaging of APK":

```
:dexDebug
:processDebugJavaRes UP-TO-DATE
:validateDebugSigning
:packageDebugError: duplicate files during packaging of APK /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build/outputs/apk/android-debug-unaligned.apk
	Path in archive: META-INF/ASL2.0
	Origin 1: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/libs/jackson-mapper-asl-1.9.2.jar
	Origin 2: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/libs/jackson-core-asl-1.9.2.jar
You can ignore those files in your build.gradle:
	android {
	  packagingOptions {
	    exclude 'META-INF/ASL2.0'
	  }
	}
 FAILED
```

It seems not possible to
 specify packagingOptions for android: adding a cordova/platforms/android/build-extras.gradle leeds also to a build failure:

```
Running "shell:platform_android" (shell) task
Platform android already added.
Warning: Command failed: Platform android already added.
```

**Comment by mpost** [comment]
Since the plugins are based on the deprecated ant based build and are not gradle aware they have no way to have any saying in the gradle build process. The plugin itself should be updated to include a customized build.gradle addition.

Since that is not the case you could add it in your own project as described here: https://cordova.apache.org/docs/en/5.1.1/guide_platforms_android_tools.md.html

Under "Extending build.gradle".

**Comment by chgerkens** [comment]
That is what I did (extending the build): I created cordova/platforms/android/build-extras.gradle:

```
android {
    packagingOptions {
        exclude 'META-INF/ASL2.0'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
    }
}
```

But then I get another build failure as describe in my post above: "Platform android already added."

**Comment by mpost** [comment]
We will investigate the issue and get back to you.

**Comment by hstaudacher** [comment]
@chgerkens can you build the app again using "nightly" within the build service?

**Comment by mpost** [comment]
Closing for now. Please reopen if the problem still exists.
