### ISSUE TITLE
Add support for switch on iOS

### ISSUE THREAD

**Issue by patrykmol** [eclipsesource/tabris-js#491]
As discussed here: https://github.com/eclipsesource/tabris-js/issues/200

**Comment by jordiboehmelopez** [comment]
Duplicate of https://github.com/eclipsesource/tabris-ios/issues/738

**Comment by ralfstx** [comment]
There are some changes to the native bridge protocol for the Switch widget. @patrykmol Could you please adjust your implementation? Thanks!

**Comment by patrykmol** [comment]
This is a duplicate topic. Reopened https://github.com/eclipsesource/tabris-ios/issues/738
