### ISSUE TITLE
TextView padding/line-height differs between iOS and Android

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#495]
Consider the following code where the font-size and the height available to TextView are both 140px.

```
var comp = tabris.create("Composite", {
  layoutData: {left: 10, top: 10, height: 140, right: 10},
  background: "green"
}).appendTo(page);

tabris.create("TextView", {
  layoutData: {top: 0, left: 0},
  font: "140px",
  text: "Alpen"
}).appendTo(comp);
```

The results are different:
![wp_20150624_18_09_31_pro](https://cloud.githubusercontent.com/assets/527303/8335303/293cb56e-1a9d-11e5-9821-b14b36621d36.jpg)

Android cuts off much more at the bottom than iOS.

The browser here shows the same scenario in HTML, and even there is a padding (it's part of the line-height), therefore it seems acceptable that the text is cut off in in this scenario. However, the height that allows the entire text to be shown _must_ be the same on both platforms for cases where the auto height can not be used, e.g. when determining the height of a CollectionView Cell.

**Comment by mpost** [comment]
This is actually dependent on the platform specific font and its native font padding. The developer should set a custom font if he wants pixel perfect alignment.
