### ISSUE TITLE
Tabris App embedded in Tabris.js App

### ISSUE THREAD

**Issue by mouaniss** [eclipsesource/tabris-js#496]
Hi support Team

Is it possible to include a Tabris app (online application connected to a RAP App Server) into a Tabris.js App as a Cordova Plugin ?
My attempts still buggy because I have some conflicts between Tabris lib and Tabris.js lib.

This feature is very useful in order to 
- Work offline
- Store critical data / process in server side
- Skip mobile new release juste because screens were updated. Tabris is a great framework for that. It's easier to update business process in server side comparing to update mobile app.

Used platform 
- Cordova : 4.X
- Tabris.js : 1.0.0
- Tabris : 1.4.4
- Native app : Android 4.4 and 5.0.1
- Gradle : 2.2.1

Thank you for your time.
Have a great day.

**Comment by mpost** [comment]
Embedding tabris into tabris.js (or vice versa) is currently not supported. If you need such a hybrid approach it might make sense for you to create a tabris.js app and use a WebView inside it for remote content.

We are aware that the integration tabris and tabris.js is a compelling approach and we are constantly looking into ways to bring the two close together.
