### ISSUE TITLE
Can't Login to tabrisjs account

### ISSUE THREAD

**Issue by ruarch** [eclipsesource/tabris-js#498]
Can't Login to tabrisjs account

**Comment by hstaudacher** [comment]
Can't reproduce the issue. Both app and website are working for me

**Comment by ruarch** [comment]
https://tabrisjs.com/api/v1/signin redirects me to homepage

**Comment by hstaudacher** [comment]
So strange. For us everything works fine. Can you delete all cookies for tabrisjs.com in your browser please and try again?

**Comment by ruarch** [comment]
Want to create a new github account to try, do I need to be invited like the first time?

**Comment by hstaudacher** [comment]
ahhhh. I understand. We set a cookie to identify who you are to calculate the OAuth scopes. I have used the system with several github accounts. No idea why it makes trouble on your side. Have you deleted the cookies before signing in with the new account?

**Comment by ruarch** [comment]
yh

**Comment by ruarch** [comment]
Cookie set after try to login; 
_gat
_ga

**Comment by hstaudacher** [comment]
Hmm, I would say there is a bug when registering as a new user but since yesterday evening we had several new registrations. I need to play this through. Will do it first tomorrow morning.

**Comment by ruarch** [comment]
Ok...thanks

**Comment by ruarch** [comment]
Hi...Any progress on the login issues

**Comment by hstaudacher** [comment]
Working on it right now. Can you give me some more information like the browser and OS you are using?

**Comment by hstaudacher** [comment]
Can reproduce it. Working on a fix now

**Comment by hstaudacher** [comment]
Having a fix ready. Will be deployed in about 7 minutes

**Comment by hstaudacher** [comment]
Done. Problem fixed. Can you verify?

**Comment by ruarch** [comment]
Thanks working now
