### ISSUE TITLE
Research: WebView - allow to load and navigate local content

### ISSUE THREAD

**Issue by jkrause** [eclipsesource/tabris-js#502]
Currently only single local pages can be loaded with the WebView. It should be possible to point the WebView to local resources on the device and navigate between them with relative links.

We may need to provide a local http-server, e.g. like https://github.com/XWebView/XWebView/blob/master/XWebView/XWVHttpServer.m

**Comment by irbull** [comment]
Use a time boxed slot (1 day) for research on how to solve this.

**Comment by mpost** [comment]
To support this feature on Android we would need to provide a "base url" inside the apps resources. So some tabris-js API is required there.

**Comment by patrykmol** [comment]
In iOS all resources that are bundled with the app are in the same location so to enable this we would have a way to navigate between them (toolbar?) or user would have to pass filename and extension to access one them.

**Comment by jkrause** [comment]
@patrykmol - user need a way to navigate content with hyperlinks, not with toolbars or by passing filenames. Did you look into running a local http-server as a possible solution?

**Comment by patrykmol** [comment]
HTTP server is a possible solution. I was also thinking about intercepting URL load requests. If there was a request with special URL prefix (eg. loc-res://somepage.html) we could intercept and redirect to specified resource without the need to setup HTTP server.

**Comment by patrykmol** [comment]
Closing as bundled resource are now loadable by using getResourceLocation()
