### ISSUE TITLE
Add support for cordova plugin cordova-plugin-whitelist

### ISSUE THREAD

**Issue by hstaudacher** [eclipsesource/tabris-js#507]
When creating a new cordova project with Cordova 5.1.1 the CLI add a plugin element to the config.xml. This instructs the CLI to install `cordova-plugin-whitelist` when building the app.

When starting the app with iOS/Android a JS error occurs. This is because the cordova-plugin-whitelist plugin does make use of web APIs we don't have. See https://github.com/apache/cordova-plugin-whitelist/blob/master/whitelist.js

``` js
if (!document.querySelector('meta[http-equiv=Content-Security-Policy]')) {
    var msg = 'No Content-Security-Policy meta tag found. Please add one when using the cordova-plugin-whitelist plugin.';
    console.error(msg);
    setInterval(function() {
        console.warn(msg);
    }, 10000);
}
```

It would be nice if project created with the Cordova CLI could work without the need to modify the config.xml like it was before.

**Comment by mpost** [comment]
This is not required anymore.
