### ISSUE TITLE
Different folder structure in cordova build on local machine and on build server makes writing custom build hooks hard

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#508]
Currently you can either create a regular cordova project via the cordova-cli which gives you the default folder structure or you can create a folder structure and have a separate cordova folder inside it (which could be build on the tabris.js build services).

Cordova allows to create build hooks that customize your build which works as advertised when having the default cordova project structure. When using "our" project structure with the cordova subfolder it is not clear how to deal with relative paths since the folder structure is changed back to the regular structure during build time.

Additionally with our the cordova subfolder structure you can not test your build hooks on your local machine since the folder structure is not in its final form.

**Comment by ralfstx** [comment]
We have agreed on a common project layout that is documented in [build.md](https://github.com/eclipsesource/tabris-js/blob/master/doc/build.md). This project layout can be created and built by the CLI. There should be no confusion anymore.
