### ISSUE TITLE
Document app patching

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#510]
Create a documentation article for the app patching process. Include a link to the `tabris.app.installPatch` API reference.

**Comment by tbuschto** [comment]
@ralfstx I'm not a fan of this feature and would not want to feature it more prominently. (I'm also not enthusiastic about the prospect to implement this on windows.) Can this issue be closed?

**Comment by ralfstx** [comment]
@tbuschto We already have an [article on app patching](https://tabrisjs.com/documentation/latest/patch) that states

> This feature is considered provisional and the API described here may be adjusted in a future release.

I think unless we decide to remove this feature, we should include this method in the documentation and mark it as *provisional*.

Having that said, I also consider the feature very dangerous and given the faster turnaround times in the app stores, it might not be as critical anymore. However, that would be the topic of another issue.

**Comment by mpost** [comment]
The app patch feature is scheduled to be removed in Tabris.js 3.0.

**Comment by cookieguru** [comment]
@mpost What is the rationale behind the change?

**Comment by mpost** [comment]
@cookieguru We found that the app patching feature is not used that often and with the shortened review times on the apple app store the need for it is not so urgent. Do you feel it is a required feature?
