### ISSUE TITLE
Evaluate / Improve CollectionView Performance

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#511]
With the support for different cell types (#131), we've introduced another native bridge turnaround (event/call) for every item. In case of the iOS client, it turned out that this turnaround is required for every data item upfront in order to calculate the aggregated height and then once again before creating / populating every single item. This increases the number of (native/JS) context switches also for CollectionViews that don't use multiple cell types. Chances are that this has a noticeable effect on the performance.

We should evaluate and, if necessary, optimize the native bridge protocol for iOS.

**Comment by ralfstx** [comment]
I'll see if can come up with some numbers tomorrow.

**Comment by tbuschto** [comment]
For 1000 items (41 on screen), time from before create -> after render
1.0: 210 - 240 ms
1.1: 400 - 420 ms

**Comment by tbuschto** [comment]
Optimizing the protocol seems like something we should do. Back to staging.

**Comment by karolszafranski** [comment]
I don't have any specific ideas but I agree that we could look closer and try to speed things up.

**Comment by cpetrov** [comment]
Collection view scrolling performance still does not seem satisfactory. The Reddit example is visibly stuttering during scroll with iPhone SE/11.4.1. The performance is comparable to iPhone 6/12.0. Scrolling is mostly fluid with iPhone X/12.0, but scrolling still stutters sometimes. Using `"auto"` cell height further worsens scrolling performance.

**Comment by mpost** [comment]
Closing as handled by https://github.com/eclipsesource/tabris-js/issues/1767
