### ISSUE TITLE
Research Windows 10 (WinRT/UWP) support

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#512]
Goals:
* Create a minimal Windows 10 Universal App in C# - DONE
* Execute JS within it - DONE
* Call C# from JS
* make bootstrap/tabris module run (against dummy bridge, w/o module system)
* Identify UWP widgets matching our core Tabris.js widgets
* Analyze prototype, find reusable parts
* Understand UWP unit testing
* Understand UWP navigation concepts and how we may map ours on it
* Understand UWP layouting and how we may map our layouting on it
* Understand UWP Touch/Gesture events and how we may map our events to them

**Comment by mpost** [comment]
With Microsoft cutting 7800 Jobs in its phone division and writing of 7.6$ billion dollar from the Nokia acquisition i think we should reevaluate how we approach the Windows Phone story.

**Comment by tbuschto** [comment]
This is just the hardware phone business. Windows 10 & Windows 10 mobile
are very likely here to stay. Also, they won't discontinue the Lumia line.
Their market share in europe and south america is pretty good. If you look
around the web, half the articles on the future of WP are optimistic, half
aren't.

On 9 July 2015 at 12:50, Moritz Post <notifications@github.com> wrote:

> With Microsoft cutting 7800 Jobs in its phone division and writing of 7.6$
> billion dollar from the Nokia acquisition i think we should reevaluate how
> we approach the Windows Phone story.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipsesource/tabris-js/issues/512#issuecomment-119907588>
> .
>



-- 
Innoopract Informationssysteme GmbH
tbuschto@eclipsesource.com
Tel: +49 721 - 66 47 33 - 0
Fax: +49 721 - 66 47 33 29

**Comment by hstaudacher** [comment]
34.9 million units of windows phones were sold in 2014. So, quite a market I would say.

See https://www.thurrott.com/mobile/windows-phone/1588/windows-phone-grew-unit-sales-in-2014-lost-market-share

**Comment by tbuschto** [comment]
Also, Nokia made a whole bunch of non-windows phones (Android and non-smartphones). Of course MS has no interest in those.

**Comment by tbuschto** [comment]
Between myself and @irbull we pretty much checked off all the points on the list. There seems to be nothing that should block us, though layout could be a bit problematic.

**Comment by calebeaires** [comment]
Windows Phone getting bigger and bigger! 
Smartphone OS Sales market share
http://www.kantarworldpanel.com/global/smartphone-os-market-share/
