### ISSUE TITLE
Upload image to remote server with org.apache.cordova.camera

### ISSUE THREAD

**Issue by ruarch** [eclipsesource/tabris-js#513]
Hi,
Any idea to upload  image to remote server with org.apache.cordova.camera

**Comment by mpost** [comment]
Have you tried to use the `destinationType: Camera.DestinationType.DATA_URL`?

**Comment by ruarch** [comment]
Yeah, Found a way out. Thanks any way.

**Comment by mpost** [comment]
@ruarch Good to hear you solved the issue. What approach did you take?

**Comment by ruarch** [comment]
I used the destinationType: window.Camera.DestinationType.DATA_URL
onSuccess, I post the data to a server side php script to write the data into an image file

**Comment by ruarch** [comment]
var button = tabris.create("Button", {
    layoutData: {left: 10, top: 10, right: 10},
    id:"picturebtn",
    text: "Take a picture"
  }).appendTo(page).on("select", function() {
    navigator.camera.getPicture(onSuccess, onFail, {
      quality: 50,
      targetWidth: 1024,
      targetHeight: 1024,
      destinationType: window.Camera.DestinationType.DATA_URL
    });
    function onSuccess(imageData) {
      $.post( "http://192.168.0.100/apiserver/upload.php", {data: imageData}, function(data) {
        imageView.set("image", {src: data});
  });

**Comment by mpost** [comment]
Cool. Thanks for adding the snippet.
