### ISSUE TITLE
Introduce alias property "checked"

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#515]
For two-state widgets like `CheckBox`, `RadioButton`, `ToggleButton`, and `Switch`, the property name `checked` seems more intuitive than `selection`. I'd suggest that we introduce it as an alias and deprecate the `selection` property.

Likewise, we may consider `toggle` as an alias for the event `select`.

**Comment by mpost** [comment]
select has been replaced with checked.
