### ISSUE TITLE
StatusBar text should turn white on iOS when using dark background colors.

### ISSUE THREAD

**Issue by liamchax** [eclipsesource/tabris-js#516]
When setting the below:

tabris.ui.set({
	background: 'rgba(21, 21, 21, 1)',
	textColor: 'rgba(255, 255, 255, 1)'
});

The iOS status bar text should also become white.

**Comment by ralfstx** [comment]
The property `textColor` is currently not supported on `tabris.ui`.

**Comment by ralfstx** [comment]
On Android, the background of the system bar can be controlled using the theme settings in the cordova build. This seems to be the preferred method. @patrykmol is this also the preferred way on iOS?

**Comment by liamchax** [comment]
It would be handy to dynamically set the system bar text colour. For example, you may have a dark colour background during the initial walkthrough/setup screens, and then a predominantly light coloured background from then on. Or you could have a dark coloured app that opens a white coloured Cordova plugin. Both scenarios would require setting the Tabris UI textColor.

**Comment by gosia-eclipsesource** [comment]
It would be best to make the color of the status bar text user-controllable. According to @patrykmol another option would be probing the color underneath the status bar, but that might not always be 100% effective.
