### ISSUE TITLE
How do i work with GPS and Google Map in tabris

### ISSUE THREAD

**Issue by smila** [eclipsesource/tabris-js#518]
Is there a way i can integrate GPS locator and Google Map using tabrisjs?

**Comment by wilsonna** [comment]
I've tried many cordova geolocation plugins and this seems to be the only one that works. https://github.com/Moussawi7/Cordova-GPSLocator

Hope it helps.

**Comment by smila** [comment]
Thank you for your response Wilsonna. I have been working with your tuts but i get [0,0] coordinates 

from the console.

Below is my source code. Please help me rectify the problem.
https://drive.google.com/file/d/0B_697EAy7ssENDhwQnAtS3BpVTQ/view?usp=sharing

**Comment by wilsonna** [comment]
@smila I think you're missing this in your config.xml. Just add it to the end.
    <gap:plugin name="https://github.com/Moussawi7/Cordova-GPSLocator" />

**Comment by gosia-eclipsesource** [comment]
Feel free to reopen if you need more help on this issue.

**Comment by camstuart** [comment]
@wilsonna Once the plugin is loaded, how do I access the `GPSLocator` object?

```
window.plugins.GPSLocator.getLocation(...)
```

Did not work for me, even though the tabris online build logs show the plugin is loaded from github
