### ISSUE TITLE
A listener to intercept App Exit event?

### ISSUE THREAD

**Issue by wilsonna** [eclipsesource/tabris-js#519]
I guess this is more applicable to Android due to the back button. Currently, the app may be accidentally exited when the back button is pressed too many times. It would be nice if we could intercept this event and cancel it to prevent accidental exit.

**Comment by jonek** [comment]
Tabris.js current provides the [tabris.app](https://tabrisjs.com/documentation/1.0/api/app) object where you can register a listener for "pause" and "resume" events. Is that sufficient for you needs?

**Comment by wilsonna** [comment]
Thanks for your reply. Unfortunately, I think those listeners are not able to satisfy my needs. The pause listener kicks in when I press the Home key, which has it's useful applications. But it is unable to intercept the event which exits the app. Do correct me if I'm understanding those events wrongly.

**Comment by mpost** [comment]
@wilsonna We are aware that more control over the back button is needed and we will integrate appropriate API in an upcoming release.

**Comment by wilsonna** [comment]
Hi Moritz, great to hear :) This is an amazing product and I've really enjoyed developing with it. Keep up the great work!

**Comment by mpost** [comment]
Closing this issue as it will be resolved when https://github.com/eclipsesource/tabris-js/issues/483 is implemented.
