### ISSUE TITLE
Support i18n

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#52]
We need a way to access the client's locale.

**Comment by ralfstx** [comment]
The client's language can be accessed by `device.language`. i18n can be easily implemented by loading localized contents from JSON modules that corresponds to the client locale.

**Comment by hstaudacher** [comment]
Can we add an example for this in 0.9.1?

**Comment by ralfstx** [comment]
Sure, good point.

**Comment by jkrause** [comment]
https://github.com/eclipsesource/tabris-js/tree/master/examples/i18n
