### ISSUE TITLE
Reuse existing widgets in different pages

### ISSUE THREAD

**Issue by sand123** [eclipsesource/tabris-js#521]
Can I create widgets on module level and then just add it to page when page opened?
Inside module I created CollectionView, and defined method to show this widget
```javascript
var cv = tabris.create("CollectionView", {...});

exports.showItem = function(dataItems){
    cv.insert(dataItems);
    tabris.create("Page", {
        title: "View Item"
    }).append(cv).open()
}
```
But when I close page - it disposes all children items and my `cv` too

I added `pubsub` module at application level to listen server events. So, when I open page and get new `dataItems` from server - I'd want to refresh list immediately, so I have to add one more listener every time `cv` instance created after page opening
```javascript
pubsub.on("NEW_DATA", function(dataItems){
    cv.insert(dataItems)
})
```
If `cv` woudln't be disposed after page closed - I would use only one listener

Right now I use this workaround
```javascript
page.on("dispose", function(widget){
    widget._removeChild(cv);
})
```

**Comment by sand123** [comment]
Right now I use this workaround
```javascript
page.on("dispose", function(widget){
    widget._removeChild(cv);
})
```

**Comment by ralfstx** [comment]
You can't reuse the same widget on different pages. Since your exported `showItems` method creates a new Page, it must also create a new CollectionView.

**Comment by wilsonna** [comment]
If I understood you correctly, I got around this by appending the "heavy" widget (in this case your collection view) to a hidden Composite that's defined in a global module which never gets displayed. I will then re-append the widget from this global module when the page is rendered again, and it will be generated much faster now. It sort of works like a widget cache.

**Comment by ralfstx** [comment]
Yes, that's possible.

To make my previous statement more precise: a widget cannot have multiple parents at the same time. You can however, move a widget from one parent to another. By appending it to a new parent, it's removed from the old one. This allows for re-using the same widget on different pages sequentially.

**Comment by sand123** [comment]
@wilsonna And how do you revert widget back to cache before page closed? I jsut remove widget from page and it stays in module global scope. I didn't find any better than use `dispose` event and `_removeChild` which is not in public Widget API. Bad practice, I think

**Comment by wilsonna** [comment]
@ralfstx I hope the below snippet helps:

    var Global = require("./global.js)
    
    var page = tabris.create("Page", {
        title: "My Page"
    }).on("dispose", function() {
        myHeavyComposite.appendTo(Global.hiddenComposite);
    });

    var myHeavyComposite = Global.hiddenComposite.find("#heavy-composite")[0];
    if (myHeavyComposite) {
        myHeavyComposite.appendTo(page);
    } else {
        myHeavyComposite = tabris.create("Composite", {
            id: "heavy-composite",
            ....
        });
        .....
    }

And in my global.js:

    exports.hiddenComposite = tabris.create("Composite");
