### ISSUE TITLE
Revise property system

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#522]
The code and internal API of our property system is very complex and increasingly difficult to understand. Since it's likely that it will only get more complicated as we add new features (#517, #515, eventually theming, declerative UI) and fix issues (#394, #392). We should investigate if the current system can get more streamlined.

**Comment by tbuschto** [comment]
We already did some improvements:

* commit 5e3928d27b17c7d1281e3abff93cbee3b6e20d7f - Store cached properties in same object as non-native properties
* commit 34cde2cde3b6afaa64212a14ac8ed2663f729624 - Call custom property setter/getter with property name
* commit d4928ccebdc74f7fa4042b70f295e7e5d7a6f9ad - Move custom setter/getter handling from Proxy.js to Properties.js
* commit 7f5fa477e91aa3c617b08341e0386e230537c412 - Introduce keyword "any" for type definitions
* commit f21900e59b24767f941176636c50f679684b397a - Merge source files for PropertyEncoding and Decoding
* commit ac250abfe3e9c21554498fa36fd66d60d774b415 - Convert property type strings/arrays to objects in registerType method

What's still missing is the revision of the type strings and adding access strings. I will describe these feature in #517.

**Comment by tbuschto** [comment]
Since #517 was closed, here is was is still to do:

 * Instead of prefixing special configurion parameters in registerType with "_", extract the non-configuration parameters (which will be put on the prototype) into a "members" object parameter.
 * Revise the property "type" syntax to replace the current array notation with strings.
 * Instead of giving an object with set/get functions, let "access" consume string similar to "type". Examples would be "cached", "uncached", "cached readonly", "cached static", etc.
 * Automatically give the wiget as the first parameter to event listener so that there is no need to implement custom trigger functions.
    Optional: Combine the property type configuration keys into a single string that can be given instead of the object, e.g. "cached int 5".

**Comment by ralfstx** [comment]
With `registerType()` replaced by `NativeObject.defineProperties()`, I think most of the remaining issues are resolved: the `_` prefix is gone, properties `nocache` and `readonly` exist etc. I think that's all we're going to do for 2.0. Future plans should be tracked by a new issue.
