### ISSUE TITLE
Concept: Common color property naming scheme

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#523]
We have a lot of color properties (mostly platform-specific) missing form our API, partially because we don't know yet how to name them. See #396, #301, #237, #472. Also related: #373.

We should first come up with lists that are as complete as possible for the missing native color properties of both platforms, then decide how we name them in our API.

**Comment by patrykmol** [comment]
Here is a list of preset colours in iOS SDK. https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIColor_Class/#//apple_ref/doc/uid/TP40006892-CH3-SW18

**Comment by ralfstx** [comment]
@patrykmol thanks. Some widgets also offer different color properties to set, such as a *tint color*, right? Do those properties follow some common pattern?

**Comment by patrykmol** [comment]
@ralfstx Whole iOS follows the same colour pattern.

**Comment by mpost** [comment]
On Android the colors are provided in a theme and applied throughout the app. There are e few base colors that are defined per theme: https://developer.android.com/training/material/theme.html. Setting these theme colors is possible as described in my blog post here: http://eclipsesource.com/blogs/2015/07/03/tabris-js-1-1-sneak-peak-custom-themes-on-android/

On top of that each widget has several specific properties that affect there appearance. There is also one property called "tint color", that can be applied on a View level. The view decides what it wants to do with it.

**Comment by ralfstx** [comment]
The global properties `textColor` and `background` are problematic. Some widgets don't have a text (e.g. Switch), others have multiple texts. Sometimes the textColor is currently used as an accent color. For some other widgets, the background color applies not to the entire background but to a specific region (e.g. Picker on Android), so `background` is also not specific enough.

We agreed to introduce more widget-specific color properties (for example `thumbColor`, `messageTextColor`, etc.) to replace the global properties. Those properties should be consistently suffixed with `...Color`.

I'm closing this issue and we continue the discussion on a per-widget basis.
