### ISSUE TITLE
WebView doesn't support localStorage

### ISSUE THREAD

**Issue by jeffmikels** [eclipsesource/tabris-js#525]
Though tabris might support localStorage, the WebView component doesn't seem to at least in the developer app. Will the WebView component support localStorage when the final app is built?

**Comment by mpost** [comment]
@jeffmikels This will be fixed in the next release.

**Comment by jeffmikels** [comment]
Good to know.. is there an ETA for when the next release is coming and/or a roadmap of what is planned for the next release?

**Comment by mpost** [comment]
You can already try the upcoming release when you choose the "nightly" build on tabrisjs.com. The local storage bug hasn't been merged yet but as soon as this issue is closed, the nightly should contain the change.

We plan to publish the next release within the next 2 weeks.

**Comment by cpetrov** [comment]
Tested on iOS (works out of the box) and Android. The issue has been resolved and the fix on Android will be released with Tabris.js 1.1.0.
