### ISSUE TITLE
Support more HTML tags in TextView

### ISSUE THREAD

**Issue by wilsonna** [eclipsesource/tabris-js#526]
Just a suggestion. Tags like ul, ol, li and those associated with tables would be very useful. In fact, I think that would cover over 90% of the use cases.

Supporting CSS would be a superb bonus, but the currently supported font tag would suffice for now.

**Comment by wilsonna** [comment]
I'd also like to add that HTML doesn't seem to be supported for iOS. At least for iOS 8 that I tested with my friend's phone. The HTML tags appeared as normal text.

**Comment by mpost** [comment]
There is no such support on the native platforms for such a feature. I would recommend to use a WebView to show the content of the file.

**Comment by wilsonna** [comment]
@mpost oh, that's unfortunate. A webview would not be very appropriate in cases where we need to manipulate the contents. But since there are definitely workarounds for this, it is not such a big deal. Thanks!

**Comment by mpost** [comment]
@wilsonna We are considering to add support to directly set data ontp a WebView. Would that help you?

**Comment by wilsonna** [comment]
@mpost Yes, that would be great!
