### ISSUE TITLE
Video Widget causes crashing

### ISSUE THREAD

**Issue by jeffmikels** [eclipsesource/tabris-js#527]
Trying to play this video (http://lafayettecc.net/media/2015_06_28__Spin__Part_04__The_Jesus_Perspective_in_Action/2015_06_28__Spin__Part_04__The_Jesus_Perspective_in_Action__video_512k.mp4) or any video using the Video Widget is crashing my app... even causing reboots in my 5.1 Android phone.

Video and audio don't play in the WebView controller either.

**Comment by jeffmikels** [comment]
Is there a way to open the default media player from tabrisjs code?

**Comment by mpost** [comment]
@jeffmikels Currently you can no inoke it directly from Tabris.js. However you could resort to a cordova plugin. There are several out there that deal with video playback.

**Comment by jonek** [comment]
@jeffmikels With the following snippet i am able to play your video using the Video widget.
Just paste the snippet in your scratchpad on http://tabrisjs.com/ -> "My Scratchpad" and launch it from the Tabris.js Developer App.

If that crashes, please report you exact phone, Tabris.js and Android version details.

```javascript
var page = tabris.create("Page", {
  title: "Video",
  topLevel: true
});

tabris.create("Video", {
  layoutData: {left: 0, right: 0, top: 0, bottom: 0},
  url: "http://lafayettecc.net/media/2015_06_28__Spin__Part_04__The_Jesus_Perspective_in_Action/2015_06_28__Spin__Part_04__The_Jesus_Perspective_in_Action__video_512k.mp4"
}).appendTo(page);

page.open();
```

**Comment by jonek** [comment]
I am closing the issue as I can not reproduce it.
Please re-open the issue if the provided snippet does not work for you.
