### ISSUE TITLE
App build by "Build Service" doesn't work (error: Cannot find module './')

### ISSUE THREAD

**Issue by alpaca0984** [eclipsesource/tabris-js#528]
I build my application for iOS and installed it to iPhone but does not work.
When I access through the internet (http://\<*my ip address*\>:8080), it works.

Here are error messeges.

<pre>
⊘ Could not load main module: Error: Cannot find module './'
> a
require
g
fire@file:///private/var/mobile/Containers/Bundle/Application/DB5ECCB2-27F9-4E40-A64E-320DF9948D28/HelloTabris.app/www/cordova.js:773:28
file:///private/var/mobile/Containers/Bundle/Application/DB5ECCB2-27F9-4E40-A64E-320DF9948D28/HelloTabris.app/www/cordova.js:226:53
file:///private/var/mobile/Containers/Bundle/Application/DB5ECCB2-27F9-4E40-A64E-320DF9948D28/HelloTabris.app/www/bundled_tabris_js_launcher/user_app/node_modules/tabris/tabris.min.js:33:3112
_callAll@file:///private/var/mobile/Containers/Bundle/Application/DB5ECCB2-27F9-4E40-A64E-320DF9948D28/HelloTabris.app/www/bundled_tabris_js_launcher/user_app/node_modules/tabris/tabris.min.js:32:8223
trigger@file:///private/var/mobile/Containers/Bundle/Application/DB5ECCB2-27F9-4E40-A64E-320DF9948D28/HelloTabris.app/www/bundled_tabris_js_launcher/user_app/node_modules/tabris/tabris.min.js:32:8048
_trigger@file:///private/var/mobile/Containers/Bundle/Application/DB5ECCB2-27F9-4E40-A64E-320DF9948D28/HelloTabris.app/www/bundled_tabris_js_launcher/user_app/node_modules/tabris/tabris.min.js:32:22750
_notify@file:///private/var/mobile/Containers/Bundle/Application/DB5ECCB2-27F9-4E40-A64E-320DF9948D28/HelloTabris.app/www/bundled_tabris_js_launcher/user_app/node_modules/tabris/tabris.min.js:32:8598
_notify
</pre>

And this is my repository
https://github.com/alpaca0984/com.alpaca0984.tabris

Any help would be appreciated .

**Comment by hstaudacher** [comment]
The build service eliminates the cordova folder because it makes a valid cordova project out of it. As a result please dont put an js sources in it or reference it the way `cordova/...` at any place.

**Comment by ralfstx** [comment]
The `main` field in your `package.json` should not point to a file in `cordova/`.

**Comment by ralfstx** [comment]
Please re-open if you need more assistance.

**Comment by alpaca0984** [comment]
> hstaudacher, ralfstx

Thanks for your advices I will try.
