### ISSUE TITLE
Support Simple Validations in TextInput

### ISSUE THREAD

**Issue by wilsonna** [eclipsesource/tabris-js#529]
For example, max/min length, regex pattern. Right now, it's not really feasible to control the user input by listening to the input event. Rewriting the user input would force the cursor to the first character, affecting user experience.

**Comment by ralfstx** [comment]
What would you expect to happen when a validation fails?

**Comment by wilsonna** [comment]
I was thinking, in the case of max length, perhaps it could prevent the user from further entering more characters. Or a regex acting as some sort of input filter which prevents certain character patterns from being entered. But those are rather specific cases. Perhaps for maximum flexibility, I'm not sure if it's possible to capture the event before the input is echoed on screen? i.e. on("before:input") That way, we could intercept the inputs and handle it before it is actually displayed.

**Comment by ralfstx** [comment]
Limiting the length of a text field seems to be impossible to implement properly on Android (https://github.com/eclipsesource/tabris-js/issues/534).

> Rewriting the user input would force the cursor to the first character, affecting user experience.

That's only the case on Android. I've opened #537 for this issue.

**Comment by wilsonna** [comment]
oh, that's a bummer :( Since you've opened a new issue to track that, I'll close this then.
