### ISSUE TITLE
XHR: Encode user data in Base64 when sending requests with credentials enabled

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#53]

**Comment by ralfstx** [comment]
@cpetrov Can you provide a pointer? Where would this have to be implemented?

**Comment by cpetrov** [comment]
See https://www.ietf.org/rfc/rfc2617.txt, line 273.

User credentials are stored in `scope.requestUrl.userdata` in clear text (XMLHttpRequest.js, line 301). It should suffice to encode them in base64.

**Comment by ralfstx** [comment]
Thanks. I see. We currently don't have a way to encode base64. Is this feature worth including a 3rd-party library?

**Comment by irbull** [comment]
How is encoding in base64 a secure way to send credentials?

**Comment by jonek** [comment]
@ralfstx: base64 encoding and decoding can be important in any Tabris.js app that uses some XHR. I think it would be definitely worth including that feature in Tabris.js.

**Comment by jonek** [comment]
@irbull: As far as I understand the RFC, base64 encoding of credentials in basic http authentication is not  a matter of security but just part of the standard that defines how that authentication method is supposed to work. If you want to use it between a Tabris.js app as a client and a given server (that you most probably do not control) the app has to be compliant with the RFC.

**Comment by ralfstx** [comment]
You'd set the HTTP header to a base64-encoded string, e.g.:

```js
xhr.setRequestHeader("Authorization", "Basic " + btoa("username:password"));
```

@cpetrov It's not the responsibility of XHR to encode certain parameters, is it?

**Comment by cpetrov** [comment]
According to [this TODO](https://github.com/eclipsesource/tabris-js/blob/1556be054f21ce5bfddea2eff52403a670370244/src/tabris/XMLHttpRequest.js#L219), this issue seems only relevant for the [`open()`](https://xhr.spec.whatwg.org/#the-open%28%29-method) method when using an URL with authentication part or the `username` and `password` parameters of `open()`: 

`open(method, url, async, username, password)`

... which are passed to the authentication part of the url. This type of authentication has been [deprecated](https://www.ietf.org/rfc/rfc3986.txt) and is [not supported by modern browsers](https://bugs.chromium.org/p/chromium/issues/detail?id=82250#c7). 

I suggest that we change the XHR implementation to ignore the authentication part of URLs.

Currently the authentication part is misused for basic authentication, which is implemented wrong anyway (`user:password` in plain text instead of Base64-encoded).
