### ISSUE TITLE
Provide TypeScript type definitions for Tabris.js

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#530]
TypeScript seems to [become popular](https://github.com/borisyankov/DefinitelyTyped/blob/master/CONTRIBUTORS.md). While type definitions probably wouldn't help with property types (would they?), they could at least assist developers with basic types like Widget and WidgetCollection.

We should consider to support users who want to go with TypeScript and provide type definitions for Tabris.js on [DefinitelyTyped](http://definitelytyped.org/).

**Comment by NekR** [comment]
> While type definitions probably wouldn't help with property types (would they?)

Method overloads should help, e.g.
```ts
get(prop: "left"):number;
```

**Comment by ralfstx** [comment]
@NekR Indeed, that works! Thanks for the hint!

**Comment by ralfstx** [comment]
TypeScript definitions pull request: https://github.com/borisyankov/DefinitelyTyped/pull/5868
