### ISSUE TITLE
People animation demo exception thrown on subsequent tap

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#531]
To reproduce: tap quickly more than one time on a face. An exception is thrown: "Error: Object is disposed".

The `animationend` callback cannot be removed on subsequent animation as the animation target was already disposed in the previous `animationend` callback.

**Comment by ralfstx** [comment]
The problem is that when an animation ends, the animated widget may already be disposed. We're missing a disposed check in the wrapped callback in `Events.js/once`.
