### ISSUE TITLE
Allow to disable the horizontal paging of TabFolder

### ISSUE THREAD

**Issue by wilsonna** [eclipsesource/tabris-js#533]
I was trying to implement a slide-to-delete within a Tab but the event only fired for a split second before it stopped. This is understandable since the TabFolder also relies on the horizontal panning to navigate from tab to tab. But I'm wondering if this is by-design, or it's actually a bug. Would it be possible for the widgets' listeners to take priority over the TabFolders, if they happen to be listening to the pan:horizontal event?

**Comment by mpost** [comment]
@wilsonna Swipe-to-dismiss inside a horizontal scrolling tab folder is very uncommon. For a user that could lead to confusion.

That being said implementing your suggestion is not that easily possible with the current gesture API. Maybe it would make more sense to for you if tabris.js added API which disables the horizontal paging of the tab folder? Thereby you could control your swipe-to-dismiss gesture as you planned to.

**Comment by wilsonna** [comment]
@mpost Yup, an API to disable the horizontal paging (or any specific native listeners) would be useful :)

**Comment by ralfstx** [comment]
This API exists already:
```js
tabris.create("TabFolder", {
  paging: false,
  ...
});
```
