### ISSUE TITLE
Support limiting TextInput text length

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#534]
Some form inputs have limited length. An additional attribute can be used to support this scenario.

**Comment by ralfstx** [comment]
The property `maxLength` has been removed in commit bef059050b351aca9b136ef84efe6f90618ea9b2:

> It turned out that this property cannot be properly implemented on
Android. It probably doesn't result in a modern UX anyway (rather
than to prevent typing, a validation should indicate that the limit
is exceeded).

**Comment by ralfstx** [comment]
@mpost do you remember the restrictions? If we can't support it properly, I think we should close this issue.

**Comment by mpost** [comment]
@ralfstx Not exactly sure... Wasn't it like you could put more text in programmatically than allowed?

**Comment by ralfstx** [comment]
@mpost https://github.com/eclipsesource/tabris-android/issues/785

**Comment by mpost** [comment]
Closing as "wontfix".

**Comment by cpetrov** [comment]
Reopening due to https://github.com/eclipsesource/tabris-android/issues/785#issuecomment-187121335
