### ISSUE TITLE
Consider removing disposed checks for common methods

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#535]
Tabris.js widgets are generic model objects that delegate certain properties to the native clients. When disposing of a widget, we don't need to suppress setting custom properties or triggering custom events.

Only native calls must be suppressed after dispose. However, a warning might be sufficient.

**Comment by tbuschto** [comment]
I like the idea of allowing as much as possible. The purpose of the dispose method only to clear the native resources associated with the proxy, the rest is up to the JS garbage collector.

**Comment by mpost** [comment]
We plan to always print warnings when accessing a disposed widgets and to improve the warn output via https://github.com/eclipsesource/tabris-js/issues/1663.
