### ISSUE TITLE
TextInput: inconsistent cursor position after changing text

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#537]
When the `text` property is changed programmatically, the text cursor jumps before the first character of the text on Android. On iOS, it moves after the last character, which seems more intuitive. Could this be aligned?

**Comment by mpost** [comment]
Since this came up again, we have agreed to make the clients consistent by setting the cursor to the end when the text changes.

**Comment by mpost** [comment]
We have adjusted the clients to set the cursor position to the end of the text when the text changes programmatically.
