### ISSUE TITLE
Patch of a Patch seems to fail (on Android)

### ISSUE THREAD

**Issue by irbull** [eclipsesource/tabris-js#541]
On Android:
 * Deploy an app with a button, selecting the button invokes an update
 * Have an updated version available at a URL
 * Press the button, and the update happens (good)
 * Restart and the new version is there
 * Press the button again:
  * No _getRequest_ is performed
  * However, the installPatch callback is invoked without an error, so I assumed it worked.

**Comment by mpost** [comment]
@irbull Could that be related to caching of the snippet on the client? Make sure your server does not apply caching via the cache-control headers (eg "http-server -c-1" when using the npm http-server).

Otherwise... Could you show the snippet you are using for testing?

**Comment by irbull** [comment]
YES! I bet cache control is the problem. I'll check and report back.

**Comment by irbull** [comment]
Yes, this is the cache control header. Since we only use time based cache invalidation, update of update don't work in short succession. I think we should add something to the docs. I'll put a change-set together.

**Comment by irbull** [comment]
I added a note to the docs.
