### ISSUE TITLE
Buttons sometimes don't have touch feedback

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#543]
Buttons sometimes don't have touch feedback when the background has been set to a color different than "initial".

**Android KitKat:**
☒ No touch feedback.

**Android Lollipop:**
☑ Touch feedback as expected.

**iOS:**
☒ Touch feedback only on the button text.

```
var page = tabris.create("Page", {
  title: "ProgressBar",
  topLevel: true
});

tabris.create("Button", {
  background: "red",
  text: "Just a button",
  layoutData: {centerX: 0, centerY: 0}
}).appendTo(page);

page.open();
```

**Comment by mpost** [comment]
This has been fixed.
