### ISSUE TITLE
Support data binding

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#544]
Currently, application code has to update all widgets programmatically. Being able to bind properties to a data model would eliminate update code and often the need for a widget id.

Idea: when every widget supports a `model` property, properties could be set to a function instead of a value. This function would extract the property value from the data model. Example:

``` js
tabris.create("TextView", {
  text: function(book) {return book.title}
});
```

When data models can be inherited from the parent, you'd only have to set the data model to a Page or Composite, and all contained widgets would update.

**Comment by tbuschto** [comment]
Databinding support was started as part of the tabris-decorators project: https://github.com/eclipsesource/tabris-decorators

We could move part of that code to the core framework so it can be used without TypeScript/JSX, but I'm sure it would be worth the effort. Are there cases were one needs databinding but does not want to use TypeScript?

**Comment by mpost** [comment]
Data-binding support could also be part of its own module independent of the core. thereby other implementations could also emerge.

**Comment by mpost** [comment]
We agreed on closing this issue in favor of implementations in external modules.
