### ISSUE TITLE
Allow referring to previous item or parent in layoutData

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#545]
Widgets are often arranged in a row, horizontally or vertically. This still requires a reference to the previous item. If a widget is removed, the reference is no longer valid and subsequent widgets will disappear.

Instead of referring to a particular widget, could we allow to align a widget to the previous widget in `layoutData`? If there is no previous widget, the parent should be used. If the previous item is removed, the references should be updated.

**Comment by irbull** [comment]
Are there Docs or an example for this? Doesn't appear to be any in b8eb6f8
