### ISSUE TITLE
Working with json after ajax call

### ISSUE THREAD

**Issue by smila** [eclipsesource/tabris-js#546]
How do i use json from ajax call as items in CollectionView

function carownerControlFunc(taxi_no){
var carownerControlPage = tabris.create("Page", {
										  title: "Taxi App - User Control",
										  topLevel: false
										});
										tabris.create("Button", {
										  id: "editCarownerProfile",
										  text: "Edit Profile",
										  background: "#FFCC00",
										  textColor: "#4A4A4A"
										}).on("select", function() {
											
										}).appendTo(carownerControlPage);
										tabris.create("TextView", {
											markupEnabled: true,
											text: "<b>Requested services made by customers.</b>",
											id: "reqSevLabel"
										  }).appendTo(carownerControlPage);
										  //get customers requested for services
										  var taxi_no = taxi_no;
										  $.ajax({ //Process the form using $.ajax()
											type      : 'POST', //Method type
											url       : 'http://192.168.137.1/taxiapiserver/customer-service-request.php', //Your form processing file URL
											data      : {taxi_no:taxi_no}, //Forms name
											dataType  : 'json',
											cache	 : false,
											success   : function(data) {
														var services = JSON.stringify(data);
														//console.log(services);
														tabris.create("CollectionView", {
														  layoutData: {left: 0, top: 0, right: 0, bottom: 0},
														  items: services,
														  itemHeight: 10,
														  initializeCell: function(cell) {
															var nameTextView = tabris.create("TextView", {
															  layoutData: {left: 3, top: ["#reqSevLabel", 20], right: 10},
															}).appendTo(cell);
															cell.on("change:item", function(widget, service) {
															  nameTextView.set("text", service.customer);
															});
														  }
														}).on("select", function(target, value) {
														  console.log("selected", value.customer);
														}).appendTo(carownerControlPage);
															},
											error	: function(data, errorThrown)
															{
																console.log('Update not fetched '+ errorThrown);	
															}
										});	
										  
										carownerControlPage.apply({
										   "#editCarownerProfile": {layoutData: {left: 10, top: 20}},
										   "#reqSevLabel": {layoutData: {left: 10,  top: ["#editCarownerProfile", 20]}},
										});
										
		return carownerControlPage;
}

/*==============================api======================================*/
<?Php
include_once('dbcon.php');
include_once('function.php');

$taxi_no = isset($_POST['taxi_no']) ? mysql_real_escape_string($_POST['taxi_no']) : '';

	
	$s=mysql_query("SELECT * FROM services_request WHERE taxi_no='{$taxi_no}'");
		$json = array();
		while($row=mysql_fetch_assoc($s)){
			$json[] = $row;
		}
		echo json_encode($json);
?>

**Comment by jonek** [comment]
As @tbuschto pointed out in issue #547 you could use JSON.parse(data) in your success callback.

I think it would also help to create the VollectionView before you do the AJAX request and just populate the items from within the success callback.
