### ISSUE TITLE
How do we create a picker from mysql and php 

### ISSUE THREAD

**Issue by smila** [eclipsesource/tabris-js#547]
I want to be able to create picker items from mysql db.

**Comment by sand123** [comment]
Hello, @smila 
In general, you can use [XMLHttpRequest](https://tabrisjs.com/documentation/latest/w3c-api) to fetch JSON data from server, then create [Page](https://tabrisjs.com/documentation/latest/api/Page) with [CollectionView](https://tabrisjs.com/documentation/latest/api/CollectionView) and listen to [SELECT](https://tabrisjs.com/documentation/latest/api/CollectionView#events) event

**Comment by smila** [comment]
I want to be able to create items for tabris picker. When i fetch data from the server and echo as json_encode, the json is read as string.

eg. I want to be able to create items like ["Ghana","USA","Canada"].

**Comment by tbuschto** [comment]
I'm not quite sure what the scenario is, but if you have the data as a JSON string, you can simply decode it with JSON.parse, e.g.

    picker.set("items", JSON.parse(json));
