### ISSUE TITLE
Back button with topLevel: true pages navigation

### ISSUE THREAD

**Issue by sand123** [eclipsesource/tabris-js#548]
When navigating between `topLevel: true` pages with native back button (Android) - it quits app instead of poping up previous top page as expected.

With Drawer and PageSelector
- select topPage **page1**
- select topPage **page2**
- press **back** button

Application is suspended, but I expected to see **page1** opened.
Is it by design?

**Comment by jonek** [comment]
You would have to make page2 a child page of page1. Then the back button navigation works as expected. Reopen if this does not help in you scenario.
