### ISSUE TITLE
Support Promise without explicitly importing thrid party library

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#549]
Right now Promise can't be used in tabris.js unless you get a third party library such as bluebird, which doesn't always work (#540). This keeps us from using them in our API, e.g. in the "animate" or "installPatch" methods.

**Comment by tbuschto** [comment]
In my opinion there are two libraries that we could include.

"es6-promise": https://github.com/jakearchibald/es6-promise
* actively maintained, 1,076,932 DL/M
* subset of rsvp
* 32/18 KB (one file/module, no dependencies)
* instance methods: then, catch
* constructor methods: all, race, resolve, reject

"promise": https://github.com/then/promise
* actively maintained, 1,714,376 DL/M
* npm version has one dependency, consists of multiple files itself
* browserified version at https://www.promisejs.org/polyfills/promise-6.1.0.js has 11KB (minified)
* instance methods: then, catch, done
* constructor: all, race, resolve, reject

"promise" is more actractive (and appears to be a "official" implementation), but may be more complicated to include. There are two approaches we could use: Either include the library in our build (and whatever code we need to map it to the global Promise object), or add it as a dependency of Tabris and require it lazily (like we do in the node compatibility module).

**Comment by tbuschto** [comment]
There is also the option to not include a Promise library at all, but still use Promisis in our API. The user would then be required to ensure a Promise library is present if he wants to use the API. Not sure what should happen if the API is used without a (working) Promise being present.

What I don't like about that is that not only has the promise library added to package.json and loaded at runtime (in case of "promise" split into several modules), but the user still has to do the mapping, i.e. "window.Promise = require("Promise");" somehwere.

The main reason I want Promise is that the animation API seems broken right now. There is no good way to give a method that is executed after a specific animation has finished. You usually will register the "animationend" listener function *before actually calling animate*, and you have have to give and check the name of the animation in case there are multiple ones. 

That said, there a somewhat ugly but easy workaround for that without relying (exclusively) on promises: Introduce an optional callback parameter to animate, i.e. "widget.animate(props, options, callback);"

**Comment by ralfstx** [comment]
Yes, it would be convenient for the user not having to care where the Promise implementation comes from, however, I don't like the idea that the tabris module "smuggles" Promise support into the platform.

On the other hand, for the native clients as the provider of the platform, it seems legitimate to amend the platform. What about providing promises not in the tabris module, but as part of the native clients, e.g. in boot.js?

**Comment by ralfstx** [comment]
I tried to use [es6-promise](https://github.com/jakearchibald/es6-promise), but this module depends on a global function `setImmediate`. This function is emulated by `setimmediate.js` (included but has to be loaded explicitly) based on `window.postMessage`, which is also not available in Tabris.js.

To use this module, we'd have to provide a `setImmediate` function, which is non-standard according to [MDN](https://developer.mozilla.org/en/docs/Web/API/Window/setImmediate).

**Comment by ralfstx** [comment]
Included the [promise](https://github.com/then/promise) module from npm in commit 0d9cdb9. In contrast to other shims this one is self-contained and has a clear structure.

In Tabris.js 1.7.0, Promise is available and operational on all platforms.
