### ISSUE TITLE
Support on-the-fly typescript translation

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#550]
It'd be really cool if one could use .ts files with tabris.js as if they were .js files. Integrating the translation in the build service shouldn't be too hard, but to support the launcher app the translation would have to be integrated in either the client or server.

See also:
Provide TypeScript type definitions for Tabris.js #530
Provide tabris-js http-server #471

**Comment by NekR** [comment]
How then one could decide which TS version to use?

**Comment by ralfstx** [comment]
We decided to leave the TypeScript configuration to the individual projects. We'll make a template available to show how to set up and build a Tabris.js project with TypeScript (#760).
