### ISSUE TITLE
After building my apk file, i had this error message "Cannot read property 'toast' of undefined". But it works fine from URL tab of the developer app.

### ISSUE THREAD

**Issue by smila** [eclipsesource/tabris-js#552]

**Comment by hstaudacher** [comment]
I guess you haven't included the cordova toast plugin? Just include:

```xml
<gap:plugin name="nl.x-services.plugins.toast" version="2.0" />
```

to your config.xml

**Comment by jonek** [comment]
@smila Please be aware that the Tabris.js Developer App contains a predefined set of Cordova plugins that your code can use if you start your application via the URL field. You can click on the "plug" icon in the toolbar of the Tabris.js Developer App to see the list of available plugins.

If you build your own app, you have to include all the plugins you need yourself like @hstaudacher explained.

You can find more information here: https://tabrisjs.com/documentation/latest/build#adding-plugins

Pleas reopen the issue if you still have problems.

**Comment by smila** [comment]
Thanks Holger, It is working perfect now.
