### ISSUE TITLE
Provide a selectionValue property for Picker

### ISSUE THREAD

**Issue by wilsonna** [eclipsesource/tabris-js#554]
Currently, we have the selection (i.e. text value) and selectionIndex properties. However, more often than not, we would identify a selection by an "id" or "value", since the text value and the index may be derived programmatically and is not the true value of the select item. This would be similar to how the select/option tags is implemented, where there is a text value and an underlying true value.

We could pass in an array of value/text pair to the items property when initialising the picker list. e.g.

    items: [[0,'First item'],[1,'Second item'],[2,'Third item']]

**Comment by mpost** [comment]
A possible solution could be to lean on a similar API as the collection view where you pass in a list of data objects and have a function to that converts the data items to strings .

**Comment by ralfstx** [comment]
Since this request would be covered by generic data binding system, I'd not like to implement a widget-specific function property to extract the display name from an item.

In the meantime, shouldn't it be simple to solve your issue using Array functions like:
```js
items: values.map(function(value) { return value[1]; })
```
With ES6, it will become even simpler:
```js
items: values.map(value => value[1])
```

**Comment by cookieguru** [comment]
@ralfstx Which version is Tabris.js on?  I can't find any info on that, or which version of J2V8 Tabris.js uses, or what version of ECMAScript that any J2V8 uses.

**Comment by wilsonna** [comment]
@ralfstx There may be a misinterpretation of my suggestion. Below is an example of my intention.

    var books = [{
        sno: 23765825,
        title: "Once Upon a Time"
    }, {
        sno: 29438583,
        title: "Happily Ever After"
    }, {
        ...
    };

    var myPicker = tabris.create("Picker", {
        items: books.map(function(book) { return book.title + "(" + book.sno + ")"; }), // picker shows book titles concatenated with serial number
        itemValues: books.map(function(book) { return book.sno; }) // but the true value is kept here
    });

or better still, simply

    var myPicker = tabris.create("Picker", {
        items: books.map(function(book) { return [book.sno, book.title + "(" + book.sno + ")"]; })
    });

as described in my first post, or

    var myPicker = tabris.create("Picker", {
        items: books.map(function(book) { return {value:book.sno, label:book.title + "(" + book.sno + ")"}; })
    });


so that I can do this

    var selectedSNo = myPicker.get("selectionValue");

because while the picker lists the book description (consisting of title and serial number), the real value I want returned is just the serial number. Currently we only have "selection" and "selectionIndex", both of which are not what I really need.

**Comment by ralfstx** [comment]
@tbuschto @irbull Not sure which ES version is supported in current J2V8, but since Node.js supports lambdas already, J2V8 will soon do as well. We'll have to wait for JavaScriptCore anyways. But you can use TypeScript, Babel, Traceur, etc. with Tabris.js.

**Comment by ralfstx** [comment]
@wilsonna I see. The thing you call "value" is actually an id to identify the item. I can understand the need for an id when the text is not unique, i.e. when you can have more than one book with the same title. However, since the only indication a user has to select an item is the text, there is no point in having multiple items with the same text.

Currently we have the index, which I think serves the same purpose. Instead of
```js
var selectedSNo = myPicker.get("selectionValue");
```
you can write
```js
var selectedSNo = books[myPicker.get("selectionIndex")][0];
```

I'm not against a new API, but since there is a way to achieve the same result with a slightly less convenient syntax, I'd like to wait until we have data binding implemented.

**Comment by wilsonna** [comment]
@ralfstx I agree that having multiple items with the same text in a Picker doesn't make sense. In the example above, I instead concatenated the title with the serial number (this happens often enough), implying that I'm now unable to directly infer the serial number from the text, even when the text is unique, since it is derived programmatically. I would need to store this new derived text in a separate map, which maps to the serial number.

The selectionIndex also does not exactly serve the same purpose as we often need to sort the array in alphabetical order of the title before displaying in the Picker, which messes up the original sequence.

While both cases could be resolved by receiving the original object array with the proper display text and sort order, that is often not the case, either because we have no control over the web service which we get this array from, or because it may not just be used for the Picker.

In any case, I'll be looking forward to the data binding feature to resolve such issues :) cheers!

**Comment by irbull** [comment]
TabrisJS uses J2V8 3.0.1 (or 3.0.0). Either way, that's V8 3.26. I have
prototyped moving J2V8 to V8 4.x, however, the limiting factor here is iOS
support. I'm not sure iOS supports ES 6 yet.

On Mon, Sep 28, 2015 at 8:32 AM, Ralf Sternberg <notifications@github.com>
wrote:

> @tbuschto <https://github.com/tbuschto> @irbull
> <https://github.com/irbull> Not sure which ES version is supported in
> current J2V8, but since Node.js supports lambdas already, J2V8 will soon do
> as well. We'll have to wait for JavaScriptCore anyways. But you can use
> TypeScript, Babel, Traceur, etc. with Tabris.js.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipsesource/tabris-js/issues/554#issuecomment-143779605>
> .
>



-- 
R. Ian Bull | EclipseSource Victoria | +1 250 477 7484
http://eclipsesource.com | http://twitter.com/eclipsesource

**Comment by ralfstx** [comment]
@wilsonna If I understand correctly, you suggest an `itemsValue` property next to `items`. Both properties would have to be in sync. If they run out of sync, the widget would be in an inconsistent state.

What if we'd allow setting arrays of arbitrary data items to the `items` property instead (same as in CollectionView)? You could provide a function to extract the display text from a given data item:

```js
myPicker.set({
  items: books,
  itemText: function(book) { return book.title + "(" + book.sno + ")"; }
});
```
When an item is selected, you could directly access the data item:

```js
myPicker.on("select", function(picker, book) {
  console.log(book.sno);
});
```

I've drafted a change here: https://gerrit.eclipsesource.com/#/c/5925/. Would that help in your case?

**Comment by wilsonna** [comment]
@ralfstx That would be excellent! :+1: In fact, that's even better since we wouldn't be just restricted to the "id".
