### ISSUE TITLE
Add onMenu button press to  show menu list

### ISSUE THREAD

**Issue by iteearmah** [eclipsesource/tabris-js#555]
Will like a feature where when the menu button is pressed a menus pops up.

**Comment by wilsonna** [comment]
@iteearmah I believe it already does. If you add your Action widgets with placementPriority "low", they will not only appear as "..." in the Actionbar, pressing the menu button will also reveal these actions in a popup.

**Comment by mpost** [comment]
@wilsonna is correct. On Android it is called the overflow menu. @iteearmah could you provide more details on what you are trying to achieve?

**Comment by gosia-eclipsesource** [comment]
Feel free to reopen this issue if needed.
