### ISSUE TITLE
highlightOnTouch interferes with set("transform", ...)

### ISSUE THREAD

**Issue by wilsonna** [eclipsesource/tabris-js#557]
Refer to the code below. The idea is to translate the Composite horizontally as the pan:horizontal event is fired. However, I noticed that if the Composite has the property highlightOnTouch, the Composite will not translate, even though the gesture object returns the correct "x" translation. 

    var composite = tabris.create("Composite", {
        layoutData: {top:0, bottom:0, left:0, right:0},
        highlightOnTouch: true
    }).on("pan:horizontal", function(widget, gesture) { // Remove item
        widget.set("transform", {translationX:gesture.translation.x});
    });

**Comment by mpost** [comment]
What platform are you seeing this on?

**Comment by wilsonna** [comment]
@mpost I'm testing it on Android 4.4.2

**Comment by mpost** [comment]
@wilsonna Thanks for the clarification.

**Comment by mpost** [comment]
With the resolution of https://github.com/eclipsesource/tabris-js/issues/714 this issue is fixed on Android 6.0 and above.
