### ISSUE TITLE
Show text when CollectionView is empty

### ISSUE THREAD

**Issue by wilsonna** [eclipsesource/tabris-js#558]
I would like to suggest having a property for CollectionView, say, "emptyText", which shows if the CollectionView is empty. Better still, allow this property to take in a TextView widget so that styling can also be applied to it.

**Comment by sand123** [comment]
+1
Right now I have to toggle CollectionView visibility manualy (if dataset is empty) and show text widget with `emptyText` instead and vice versa

**Comment by mpost** [comment]
I think @sand123 pointed out the "correct" implementation when dealing with empty collections. Furthermore i'd say _if_ there would be such a feature to show something when the collection view is empty it should just be a Composite so that you could place arbitrary Views in there. Eg an image as well. But since there is a reasonable good workaround this feature will not be a top priority.

**Comment by ralfstx** [comment]
I agree with @mpost that programmatically replacing the CollectionView with another widget as needed is not only a workaround but the *correct* approach.

The suggested property is plain convenience, and it falls short when anything else than a text is to be displayed, e.g. an image or a color gradient.

**Comment by wilsonna** [comment]
@mpost @ralfstx I agree about the possibility of showing other widgets instead of text. Perhaps instead of using "emptyText" as suggested, you could consider "emptyWidget" instead, which points to the widget that displays in place of the CollectionView if it is empty, or points to a function which is able to take in parameters and spit out a widget.

The rationale why I feel this is useful is because for UX reasons, in almost any circumstances, we would want to show something in place of an empty CollectionView. While using a conditional if-else statement is definitely do-able, it adds to code clutter and boiler plate.

But I agree that this is probably low in priority since it's not exactly a show stopper.

**Comment by ralfstx** [comment]
Still doesn't sound like a functionality to be offered by a widget. The responsibility of the widget is to display data, not to control other widget's visibility.

Once we have data binding (soon to come), there may be an easy way to show the other widget only in case of an empty data model.

**Comment by wilsonna** [comment]
@ralfstx yes that would work. looking forward to it :)
