### ISSUE TITLE
Support multiline text in Radiobutton

### ISSUE THREAD

**Issue by wilsonna** [eclipsesource/tabris-js#560]
As per title. If the text is longer than 1 line, it will get truncated instead of wrapping to the next line like how TextViews do.

Android 4.4.2

**Comment by mpost** [comment]
That is the default behavior of a button in Android. We will need to provide API to enable wrapping.

**Comment by mpost** [comment]
We are enforcing buttons to be [<code>singleLine</code>](http://developer.android.com/reference/android/widget/TextView.html#attr_android:singleLine) for historical reasons. We would need to add API to re enable line wrapping for it.

**Comment by wilsonna** [comment]
I see. I'm currently working around this by stretching an empty Radiobutton / Checkbox widget to the desired width, then overlay it with a TextView, so that I can still tap on the text to select the button.

**Comment by mpost** [comment]
@wilsonna Sounds risky since the dimensions of the radio button could change. But atm i would go a similar route.

**Comment by mpost** [comment]
Android, iOS and Windows now wrap the text as expected. Closing this issue.
