### ISSUE TITLE
Allow Radiobuttons to be grouped even when not under same parent

### ISSUE THREAD

**Issue by wilsonna** [eclipsesource/tabris-js#562]
Currently, Radiobuttons are grouped only if they are all under the same parent. It would be better if they could be grouped by some kind of group identifier, perhaps by introducing a property called "groupId" for Radiobuttons.

**Comment by mpost** [comment]
I would tentatively agree with the request to make radio button grouping more flexible.

A different approach than adding an explicitly group id, would be to allow to have a group that is further up the view hierarchy chain act as the "group parent". So you could have one main Composite that is the RadioGroup parent but inside it you could have multiple (possible nested) other Composites that hold the RadioButtons.

**Comment by ralfstx** [comment]
@mpost: There may also be another use case: different radio groups within the same composite. In case, choosing a higher-level parent would not help, but group ids would. Ids could also be simply added to a declarative UI.

**Comment by wilsonna** [comment]
I agree with ralfstx. I was also thinking, perhaps this may also be useful for Checkboxes so that we may have a means of:
1) identifying whether any checkbox in the group is selected
2) obtain the selected checkbox / radiobutton value(s) in the group
3) allow a checkAll or uncheckAll feature for checkboxes

That would then mean that the "group" would have to be more than an id, but a widget itself. e.g.

    var checkboxGroup = tabris.create("SelectGroup");
    
    for (var i=0; i<10; i++) {
        tabris.create("Checkbox", {
            group: checkboxGroup
        }).appendTo(...);
    }
    
    var selections = checkboxGroup.get("selections");
    checkboxGroup.selectAll();
    checkboxGroup.unselectAll();

Just throwing it out there. :smiley:

**Comment by mpost** [comment]
@ralfstx Yeah i was thinking that multiple groups could be desired... but in i was also thinking that on Android a parent is declared that acts as the radio group container and i haven't ever hear anybody complain that this wouldn't suffice.

**Comment by wilsonna** [comment]
@mpost below is a use case where I think this would be applicable

Captain | M.V.P. | Player
------------ | ------------- | -------------
(X) | (_) | Peter
(_) | (_) | John
(_) | (X) | Michael
(_) | (_) | William

**Comment by mpost** [comment]
@wilsonna Good example there. We still believe that it is a good idea but since there are workarounds for it is not on our immediate list of supported features.

**Comment by wilsonna** [comment]
@mpost Thanks and noted.

**Comment by mpost** [comment]
Closing this for now... Please reopen if you think it needs to be retargeted.
