### ISSUE TITLE
Allow find() to traverse ancestors

### ISSUE THREAD

**Issue by wilsonna** [eclipsesource/tabris-js#563]
Currently, this function traverses descendents. There are some use cases where I would like to look for a specific ancestor instead, e.g. to get the encasing CollectionView, or to get the ancestor Composite with a specific "id". Perhaps the find() method could take in another boolean parameter to indicate whether to traverse up or down (default if this param is not specified) the hierarchy.

**Comment by ralfstx** [comment]
That would be something similar to the [parents](https://api.jquery.com/parents/) method in jQuery. Wherever possible we're following popular naming schemes and semantics. Thus I'd prefer a separate method `parents` instead of extending the `find` method.

**Comment by tbuschto** [comment]
We have that now (`parent(selector)`)
