### ISSUE TITLE
New Patch feature and Developer App

### ISSUE THREAD

**Issue by wilsonna** [eclipsesource/tabris-js#568]
I haven't tested the Patch feature with a standalone app yet, only with Developer App. I noticed that once the patch is applied, it stays there permanently, even after I refresh my instance or restart the Developer App.

For example, my original app has tabris.ui background set as blue in my app.js. After I applied a patch to replace my app.js to set the background to black, there doesn't seem to be a way to revert my patch and reset my app.js. Whatever changes I make to my original app.js no longer seems to take effect as the patched app.js always seems to take precedence even when I subsequently turned off my patch feature. The only way I could make it right again is to rename my app.js to another name and update my package.json to point to it.

**Comment by ralfstx** [comment]
Patches are kept and applied based on the URL. If you open another snippet from the same URL, the patch will be applied. The only way of getting rid of it is to clear the Developer App's data or to re-install the Developer App.

Closing as a dup of #553. Let's continue there.
