### ISSUE TITLE
Link to Layout in doc of Widget is broken

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#571]
https://tabrisjs.com/documentation/1.1/api/layout link should be changed to https://tabrisjs.com/documentation/1.1/layout

**Comment by cookieguru** [comment]
Forgot to create a new branch so this is part of my pull request in #574 (see cookieguru/tabris-js@da14bbcb88004b0302a51a178e5d5d80b6edc680)

**Comment by cookieguru** [comment]
Note that this file also references `animations.md` which does not exist

**Comment by gosia-eclipsesource** [comment]
Changes submitted. Thanks @cookieguru
