### ISSUE TITLE
Layout Wrap and Layout Fill

### ISSUE THREAD

**Issue by calebeaires** [eclipsesource/tabris-js#573]
Mobiles app native structure uses logic like Layout Wrap and Layout Fill. TabrisJS make use of layout adjustments by absolute path or adjustments by its parents. Does you intend to implement some WRAP and FILL layouts?

**Comment by ralfstx** [comment]
We plan to support alternative layouts such as Row and Grid (#21). Row would support wrapping.

A Fill layout can be specified as `layoutData: {left: 0, right: 0, top: 0, bottom: 0}`. A shortcut syntax should be possible and probably useful.

**Comment by calebeaires** [comment]
Very Thanks!
Maybe a Roadmap page would be good!
