### ISSUE TITLE
Change event for WebView

### ISSUE THREAD

**Issue by cookieguru** [eclipsesource/tabris-js#575]
Given the following snippet:
```js
var webview = tabris.create('WebView', {
	layoutData: {left: 0, top: 0, right: 0, bottom: 0}
}).appendTo(page);

webview.on('change:url', function() {
	console.log(arguments);
});

webview.set('url', 'https://tabrisjs.com/');
```

When I run the above code, there is one entry in the log for when the webview's URL is initially set.  Navigating to other pages in the webview does not fire subsequent `change:url` events.

If I click say the Blog link, I would like a way to find a way to get notified that the webview's url changed; perhaps a `navigate` event?  In my particular use case I need to capture the URL a user is redirected to after a series of navigations and then take action in the app based on the URL.

**Comment by gosia-eclipsesource** [comment]
Should be easy to implement both on iOS and on Android. We'll work on this soon.

**Comment by cpetrov** [comment]
Relevant platform API:
**iOS**:
* https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIWebViewDelegate_Protocol/#//apple_ref/occ/intfm/UIWebViewDelegate/webView:shouldStartLoadWithRequest:navigationType:

**Android**:
* [http://developer.android.com/reference/android/webkit/WebViewClient.html#shouldOverrideUrlLoading(android.webkit.WebView, java.lang.String)](http://developer.android.com/reference/android/webkit/WebViewClient.html#shouldOverrideUrlLoading(android.webkit.WebView, java.lang.String))

**Comment by cookieguru** [comment]
This was marked ready before the 1.2 release but didn't make it in to either 1.2 or 1.3.0.  Any chance I can start using this soon?

**Comment by gosia-eclipsesource** [comment]
Sorry, the "ready" label means that it's ready to work on but haven't gone "in progress" yet. We are aiming to include it in 1.4.

**Comment by cookieguru** [comment]
I think this can be closed, since there's an undocumented event that is firing.  Here's sample code:
```js
var page = tabris.create('Page', {
	title: 'Web View',
	topLevel: true
});

var webview = tabris.create('WebView', {
	layoutData: {left: 0, top: 0, right: 0, bottom: 0}
}).appendTo(page);

webview.on('load', function() {
	console.warn(arguments);
});

webview.set('url', 'http://tabrisjs.com/');

page.open();
```

There are two arguments that are getting passed in.  The first is the widget, so I can look at `arguments[0].get('url')` (which is the same as `this.get('url')`) and get what I need.  I'm not sure what the second parameter is; I looked at it in the debugger and this is what I see:

![untitled-1](https://cloud.githubusercontent.com/assets/1888809/10892896/b5e22156-815a-11e5-8166-c348f3fc795c.png)

The event is [named "Progress"](https://github.com/eclipsesource/tabris-js/blob/master/src/tabris/Widgets.js#L623) which I think is a misnomer since the event doesn't fire until the page is loaded (so far as I can tell, and I can only speak to Android).  I'm also not exactly sure where this event name comes in to play.  Perhaps that's buried somewhere in the second argument?

**Comment by ralfstx** [comment]
The `load` event is documented now. A `change:url` event is still missing when navigating from one page to another.

**Comment by cookieguru** [comment]
@ralfstx I see only the first parameters was documented, any idea what the second one is?

**Comment by ralfstx** [comment]
@cookieguru That should be just an empty event object.

**Comment by ralfstx** [comment]
Closing as suggested by @cookieguru
