### ISSUE TITLE
Consider splitting layoutData into separate properties

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#576]
Currently all aspects of a widget's position are defined by a single property `layoutData`, which supports an object with a combination of the following attributes:

`left`, `right`, `top`, `bottom`, `centerX`, `centerY`, `baseline`, `width`, `height`

This results in a system of nested properties and leads to an additional level of nesting in JSON that is applied using the `apply` method.

```js
page.apply({
  "#submit", {
    text: "Submit",
    layoutData: {
      top: 10,
      centerX: 10
    }
  }
});
```

For declarative UI, we'd need a string representation.

```xml
<Button text="Submit" layoutData="top: 10; centerX: 10;" />
```

It could be possible to support all of the layoutData attributes as properties of their own. This would avoid the nesting and also make declarative UIs easier:

```js
page.apply({
  "#submit", {
    text: "Submit",
    top: 10,
    centerX: 10
  }
});
```
```xml
<Button text="Submit" top="10" centerX="10" />
```

The latter looks like a simpler system to me. What implications could this change have?

**Comment by ralfstx** [comment]
When changing the positioning of a widget using the `apply` method, other layout properties may need to be reset. For example, to change the horizontal alignment of a widget by means of a CSS class, the following could work:

```json
{
  ".left-aligned": {
    "left": 10,
    "right": null,
    "centerX": null
  },
  ".right-aligned": {
    "left": 10,
    "right": null,
    "centerX": null
  },
  ".center-aligned": {
    "left": null,
    "right": null,
    "centerX": 0
  }
}
```

Having to reset other properties explicitly can be seen as a drawback, however, with layoutData it is **not possible at all** to replace only the *horizontal* positioning of a widget.

Properties would have to have to be resettable by a value like `null` or `"auto"`.

**Comment by irbull** [comment]
The obvious implication of this is that we lose the layoutData namespace. Are there any widgets with properties such as 'left', 'right', 'top', etc...?

**Comment by ralfstx** [comment]
No, these properties are not used in any widgets. And what else could the mean? At least for `left`, `top`, `right`, `bottom`, `width` and `height` the meaning is pretty obvious, these properties also exist in CSS. For the remaining properties `centerX`, `centerY`, and `baseline`, I think it's acceptable to reserve them for positioning as well - each of them represents another "auxiliary" edge to align a widget on.

Another case to think about is support for alternative layouts. When a different layout is set on the parent, some of these properties (or all of them) will not be respected. For example, in grid layout, we'll have something like `row`, `column`, `rowSpan`, etc., for flex box, we'd have `flex-grow`, `fley-wrap` and so on.

Some properties like `margin` (we don't have that yet, but it would help) could be respected by different layout managers.
