### ISSUE TITLE
Allow to insert widgets before other widgets

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#577]
Currently, widgets can only be *appended* to a parent. It's not possible to insert a widget *before another widget*. I'd suggest to provide a method `insertBefore()` next to `appendTo()`, following the contract of [insertBefore in jQuery](https://api.jquery.com/insertBefore/).

This method could also be used to re-order widgets within their parent.

**Comment by bFlood** [comment]
+1
