### ISSUE TITLE
Android Text Select bar misplaced

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#578]
when you select text in Android inputs, the selected text bar pushes the main tabris navbar down. 

![image](https://cloud.githubusercontent.com/assets/404991/9240638/9bed9c62-4136-11e5-9707-33867fe6b213.png)

**Comment by mpost** [comment]
Thanks for catching this issue. Will be addressed in the next release.

**Comment by mpost** [comment]
The issue has been solved for the upcoming 1.2 release.
