### ISSUE TITLE
Android reinstall issue

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#579]
using the build service, when you build a new version of a dev app (to test custom plugins etc), it installs and works great. however, if you rebuild (even with the exact same settings/files), the new APK will not install over the old one. You have to fully uninstall the app and the install the new one for it to work (wiping out previously saved files etc)

the android install error is:
"An existing package by the same name with a conflicting signature is already installed"

which is strange since the signing cert did not change at all

**Comment by gosia-eclipsesource** [comment]
This only happens in debug mode. If you build in release mode with your own signing key then everything goes as expected. But we should make it more convenient to update the app in debug mode as well.

**Comment by bFlood** [comment]
good to know, I was more concerned with release mode anyway. I would say this is not high prioty
