### ISSUE TITLE
modal pages

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#580]
is there any way to display a page modally? if not, is there a way to disable the drawer?

**Comment by ralfstx** [comment]
What do you mean by "modally" - disallow to navigate to another page?

Regarding the drawer, there is no drawer by default, only if you add one to your application, see
https://tabrisjs.com/documentation/1.1/api/Drawer

**Comment by bFlood** [comment]
something like these guidelines from iOS but for tabris Pages
https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/Modal.html
for example, when you open the Settings window in GMail on iOS, the drawer is disabled.

on appgyver, they made it easy to display a page in this way:
http://docs.appgyver.com/en/edge/steroids_Steroids%20UI%20Components_Steroids.modal_index.md.html

I guess its not high priority, especially if there is a way to disable the drawer temporarily 

thanks!

**Comment by ralfstx** [comment]
You could try the `enabled` property, but I'm afra

**Comment by mpost** [comment]
For simple dialogs with text and buttons you could use the `cordova-plugin-dialogs`.

As @ralfstx pointed out you are currently not able to place arbitrary widgets in a dialog. It is a common use case so we should think about adding support for it.

**Comment by bFlood** [comment]
sounds good, already make heavy use of cordova-plugin-dialogs. glad you are considering it for the future. disabling the drawer would be enough for my use case

**Comment by mpost** [comment]
@bFlood When using the `cordova-plugin-dialogs`, are you able to open the drawer? On what platform do you see that behavior?

**Comment by bFlood** [comment]
the cordova-plugin-dialogs work perfectly and as expected. On top of the functionality in cordova-plugin-dialogs, I also need to display custom dialogs/modals.

for instance, how would you display a Settings page in tabris? You could obviously just use a Page but the user would be able to swipe the drawer out from the side, not horrible but not exactly the best UX either. an api to disable the drawer would be helpful or something like Page.open({modal:true})

**Comment by cookieguru** [comment]
>how would you display a Settings page in tabris? You could obviously just use a Page but the user would be able to swipe the drawer out from the side, not horrible but not exactly the best UX either

What makes this a bad UX?  Settings should save automatically, so if a user changes a setting and then wants to go to a different part of the app, they shouldn't have to tap something to dismiss the settings page.  This is especially useful if they arrive at the settings page by accident.

**Comment by mpost** [comment]
I agree with @cookieguru. A regular fullscreen page with auto saving options is a good approach for settings.

**Comment by mpost** [comment]
Closing this one as "solved" since you get destroy and recreate the drawer when required.
