### ISSUE TITLE
Build Service iOS - code signing issue

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#581]
I'm pretty sure this is my fault but just checking here to see if anyone else has had any problem signing their custom iOS builds. I've checked and rechecked the bundlename, the cert and the provision file and I'm pretty sure they all are correct (but this has tripped me up in the past)

error:
`Check dependencies
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.
CodeSign error: code signing is required for product type 'Application' in SDK 'iOS 8.1'
ERROR building one of the platforms: Error: /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project`

**Comment by patrykmol** [comment]
Did you check what team you have set in under General tab in Xcode project?

**Comment by bFlood** [comment]
ok, maybe I'm doing this wrong. In the past for other build services, I've essentially followed the appgyver code signing docs (http://docs.appgyver.com/tooling/build-service/build-settings/build-settings-for-ios/ ) so I didn't do anything from XCode

is that correct for tabris as well, when using your build service?

thanks!

**Comment by wilsonna** [comment]
I'm facing the exact same problem as @bFlood . I've created a development cert and the p12 file, specified the correct password, and created a development provisioning profile, also ensured that the App ID Suffix is the same as the tabris.js app id (not sure if that matters).

**Comment by bFlood** [comment]
can someone from tabris confirm the ability to build a custom iOS app using your build service?

**Comment by patrykmol** [comment]
Yes, this is possible. It seems that bundle ID in certificates and in project are not the same. Have you tried using a certificate with wildcard bundle ID (i.e. my.company.*)? Could also provide whole log?

**Comment by bFlood** [comment]
build log - https://gist.github.com/bFlood/ff6ced69112d7fbad3df

wildcard cert - I'll try this, thanks

**Comment by bFlood** [comment]
I've tried a couple different Cert/AppId/ProvisionFile combinations and it's still failing. here's a different log with a different error then before:
https://gist.github.com/bFlood/60de183238bd7327c939

**Comment by wilsonna** [comment]
@bFlood I managed to build for iOS by switching to Debug setting (although this doesn't work for Android). You may want to give that a shot.

**Comment by mpost** [comment]
@wilsonna @bFlood We can confirm that we are currently having problems executing production builds on iOS. Debug builds will work as expected though. Please stay tuned.

**Comment by irbull** [comment]
I've looked into this, and it appears that travis-ci (the infrastructure we use to build) has identified a problem with their iOS build infrastructure. While I don't know if it's related, all iOS builds are currently disabled while they fix it.

```
Identified - We are working on rectifying an OS X build infrastructure problem which has caused numerous requeues. During this time, we will be stopping build processing entirely, so as to expedite the cleanup process. 
Aug 18, 17:44 UTC
```
https://www.traviscistatus.com/#

**Comment by wilsonna** [comment]
FYI, it seems like travis-ci has resolved their OS X issue, but the Release build for iOS is still failing with the same error.

**Comment by patrykmol** [comment]
Yes, we are aware of it and working on solving this issue.

**Comment by gosia-eclipsesource** [comment]
@bFlood @wilsonna We have verified that everything is now working normally for us.

Could you please download your "Certificate" for "Production" use and the "Provisioning Profile" for "Distribution" again from developer.apple.com, and then upload it with the corresponding p12 to tabrisjs.com?

![ios-production-certificate_1024](https://cloud.githubusercontent.com/assets/6769496/9437697/6c9aed22-4a58-11e5-9699-a82016e4a934.png)

![ios-distribution-profile_720-2](https://cloud.githubusercontent.com/assets/6769496/9437668/39aa9fe8-4a58-11e5-905e-637603584225.png)

Also make sure that you select Distribution -> App Store when you create a new certificate.

Hope it helps and sorry for the trouble.

**Comment by wilsonna** [comment]
@gosia-eclipsesource Thanks for the instructions. The build is successful now.

**Comment by bFlood** [comment]
Thanks, I will try later this week

**Comment by wilsonna** [comment]
Although I could get it to build successfully, I can't get the app to be installed if I use Distribution Type to App Store. It just gets stuck at the Installing stage. It only works if I set my Distribution to Ad Hoc mode (i.e. I need to specify the devices I'm stalling to). Not a big issue for me at the moment. But I wonder if I'll face the same problem when I eventually move to production.

**Comment by patrykmol** [comment]
@wilsonna You have to use App Store provisioning profile if you want to submit app to iTunes Connect for verification. Otherwise use Ad Hoc profile to run app on your devices.

**Comment by wilsonna** [comment]
@patrykmol Got it, thanks! Sorry, haven't really worked with iOS till recently

**Comment by bFlood** [comment]
I'm still having problems. 

1. recreated the production certificate and exported the p12 file (selected both the cert and private key files in keychain during the export)
2. recreated the AppId (bundle id com.sdlportal.sdlmobile3) 
3. recreated the Provisioning Profile (AdHoc) that uses the new cert and new AppId
4. Uploaded p12/provisioning profile to tabrisjs.com as a new key for iOS builds

I did not recreate the tabris.js app, I used an existing one. Would this cause an issue, could the old cert/provisioning profile be cached?

I still get this error during the build:
`Check dependencies
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.
CodeSign error: code signing is required for product type 'Application' in SDK 'iOS 8.1'
ERROR building one of the platforms: Error: /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
** BUILD FAILED **
The following build commands failed:
	Check dependencies
(1 failure)`

**Comment by wilsonna** [comment]
Looks right to me. Have you tried removing all your iOS signing keys before creating a new one again?

**Comment by bFlood** [comment]
removing the tabris.js iOS signing key? yes, I did remove that first and then added a new one

thanks!

**Comment by patrykmol** [comment]
Judging from error you are getting you are using wrong .p12 certificate/key pair. For production builds you have to export iPhone Distribution certificate and key pair not iPhone Development. Please note that downloading certificate from Apple's Member Center does not contain private key. It is only generated once when you create certificate request. You will have to generate another request and certificate and export it if you have lost your private key. For detailed instructions follow this document: http://docs.build.phonegap.com/en_US/signing_signing-ios.md.html#iOS%20Signing. Feel free to ask any further questions.

**Comment by bFlood** [comment]
thanks Patryk, I know this is almost certainly an issue on my end with the cert but I've tried and re-tried and keep getting the same error about the null team id. is there anything else you can check on your end, maybe the build service is using one of the older ones I created by mistake?

here's the cert I just created today in keychain, the p12 includes the cert and private key:

<img width="811" alt="keychain_access_and_desktop" src="https://cloud.githubusercontent.com/assets/404991/9580936/5d0944d6-4fca-11e5-8990-51e51175f81c.png">

**Comment by patrykmol** [comment]
This highly unlikely. When you delete key from tabrisjs.com site it is also deleted from build service. If you have deleted previous keys there is no way old one was used. You probably have done that but have you checked bundle IDs? Maybe mistake is there.

**Comment by wilsonna** [comment]
@bFlood I would like to suggest that you try creating a band new app with nothing but a simple text message, then re-create all the cert / p12 / profile etc again. If it still doesn't work, I would be happy to help you test by forking your app and trying it on my side with your cert / p12 / profile to see if I can reproduce your problem. Maybe that way, we can isolate the problem together.

**Comment by wilsonna** [comment]
I've updated my git profile to show me email address. You send it there and I'll take a look when I can find some time :)

**Comment by bFlood** [comment]
thanks, I sent you an email
