### ISSUE TITLE
Page does not appear if Action widget is present in iOS

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#583]
As of commit b8eb6f852249f7a87de6a4f9331a74308d418432 Pages no longer appear if Actions are used in iOS. The only effective change of that commit is that layoutData is now rendered twice in some cases, for example for the Composite that represents the Page in the widget tree (not the actual "Page" type object).

Page composites fill the entire screen by default in iOS (as opposed to Android), but somehow setting layoutData twice (once before the internal Page object is created and opened and once after) makes it disappear (it may have an actual size of 0x0).

**Comment by ralfstx** [comment]
See https://github.com/eclipsesource/tabris-ios/issues/770

**Comment by tbuschto** [comment]
I implemented an explicit workaround in commit cda23b1cf8086906ec8016a8cbeda9d2f244317f, but that can't be a long term solution. While it would be preferred to fix https://github.com/eclipsesource/tabris-ios/issues/770, this seems to be a longer and complicated issue. I currently have a change in Gerrit (https://gerrit.eclipsesource.com/#/c/5587/) that would - as a side effect - revert the behavior in regards of layoutData and Page to what we had before (render it once before everything else). When that is merged I would close this issue, but not the iOS issue.

**Comment by tbuschto** [comment]
https://gerrit.eclipsesource.com/#/c/5587/ has been submitted (commit 712c65c51667198f0c4e766a9fd186eafdd8bfee) and removed the workaround. I'm closing this issue.
