### ISSUE TITLE
promise npm package

### ISSUE THREAD

**Issue by rhg1968** [eclipsesource/tabris-js#585]
I am struggling to figure out how to use the npm package promise. The fetch example doesn't show how to use independently. I am using version 6.1.0 of the promise library and trying to follow along with the directions on npm, but I haven't had much success. Does anyone have a simple example of how to use this library ?   Thanks

**Comment by tbuschto** [comment]
Assuming it's installed correctly, all you have to do is call `Promise = require("promise");` once. Does that work for you?

**Comment by rhg1968** [comment]
That works, but I'm not how to create a promise based function after it has been brought in through the require method. I am used to promises mainly from angular using the $q service. I just wanted to see if I could see an example using this library to create a deferred function that executes properly.

**Comment by rhg1968** [comment]
I was able to get it working.
