### ISSUE TITLE
Refactor "page-fullscreen" snippet to use the new "toolbarVisible" property

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#586]
With the introduction of the new `toolbarVisible` flag (https://github.com/eclipsesource/tabris-js/issues/234) we should rework the "page-fullscreen" snippet which still makes use of the internal API   `style: ["FULLSCREEN"]`.

**Comment by ralfstx** [comment]
This snippet has been replaced as of 7c7ac9773aafaaf42ed82d57540826f0eb307819. `FULLSCREEN` is not used anymore.
