### ISSUE TITLE
Question - using Bitbucket

### ISSUE THREAD

**Issue by rhg1968** [eclipsesource/tabris-js#587]
I just subscribed to the developer plan and I am trying to set up an app with my private repository. I know this maybe a little out of scope of Tabrisjs itself, but any help would be greatly appreciated.

I am struggling with how to set up the keys. I'm on windows 7 and I generated an ssh key pair with GIT Bash, not 100% sure if that is the right way to go with Bitbucket. When I sign into Bitbucket I can add keys at the top level, above all my repositories or a deployment key at the repository level. I tried both without much luck. I just opened the files generated by the ssh key gen, but bitbucket only seemed to like me entering the public key. If I then pasted either the public or private keys into the Tabris create app screens it failed to authenticate. 

Any guidance on how to set this up would be greatly appreciated. Thank you.

**Comment by rhg1968** [comment]
I got it to work. I wasn't pasting the entire private key into the tabris-js form field. I also ended up setting up the public key in Bitbucket on the repository itself as a deploy key and used the private key in Tabris. I built a small sample app and it worked.

**Comment by mpost** [comment]
Good to hear. Thanks for sharing how you were able to connect the two.
