### ISSUE TITLE
Provide a property to let users build absolute paths to a bundled resource

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js#592]
I propose the following property: `tabris.app.filesystemroot`

The property will contain the absolute path to the directory in a device's file system that contains our application resources. The properties type would be string.

This will enable users to create absolute paths to bundled resources. Such paths can be required by third party Cordova plugins. E.g. the media plugin could be used to play a bundled media file. The user could just concatenate both parts of the path:
```javascript
mediaFilePath = tabris.app.filesystemroot + 'media/my.mp3';
```

**Comment by calebeaires** [comment]
+1

**Comment by bFlood** [comment]
+1

**Comment by bFlood** [comment]
is there any way to get this value now?

**Comment by patrykmol** [comment]
@bFlood Unfortunately no.

**Comment by ralfstx** [comment]
How about a method like `tabris.app.getResourcePath()` or `getAbsolutePath()`. This method could also normalize the path (eliminate double slashes etc.) and perform some checks on the relative path...

**Comment by bFlood** [comment]
is this in nightly yet? thx

**Comment by mpost** [comment]
@bFlood Not yet. We are working on it.

**Comment by ralfstx** [comment]
You can now call `tabris.app.getResourceLocation(path)` with the app-relative path to a bundled resource. The result will be a file URL, except in the developer client, where an http URL is returned. This allows to run the same code in the dev app, where the resources aren't yet bundled.
