### ISSUE TITLE
Allow external contributions to add a property/function to all "Views"

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#600]
Currently it is not possible to a new property to all widgets hat have a visual representation ("Views"). It is only possible to add properties a know widget directly. Therefore when creating a third party contribution it is not possible to add property to all "Views" while also supporting upcoming new "Views".

**Comment by ralfstx** [comment]
@mpost Is this a dup of #673?

**Comment by mpost** [comment]
yes. closing as dup since #673 sounds more understandable.
