### ISSUE TITLE
Allow to get bounds value with eg. get("width") etc.

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#605]
With tabris 1.2 layout data can be set directly on a widget. That means i can do <code>.set("width", 213)</code> but getting the <code>width</code> does not reflect the dynamic value after the view has been layouted. That is a bit confusing since what you see on screen is not the value you receive from the <code>get("width")</code> call.

**Comment by tbuschto** [comment]
Can we close this? While I agree it may be confusing, it's even more confusing to set one width and get another in return. Bounds is what is used for that.
