### ISSUE TITLE
enable/disable drawer

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#607]
feature request - method to enable/disable the drawer

**Comment by mpost** [comment]
You request is to have a drawer with regular content but then to be able to disable/enable it programmatically i presume?

**Comment by bFlood** [comment]
yes, thanks

**Comment by alexiusp** [comment]
I can explain a use-case where it would be useful, if you don't mind.
I have some "start" page, where I don't want to have a drawer. When I select a button, it leads to the "main" section of application with multiple pages and a drawer. Currently I can not get back from "inner" page to the "start" page without a drawer. If I created a drawer once - it will be always accessible even on the "start" page. I tried to dispose the drawer and it leads to crash.
So, if you implement some function which will allow to disable or hide the drawer for such cases - it would be great.

**Comment by mpost** [comment]
@alexiusp Yeah you are right. The classic "welcome" page that introduces you to the app should have the ability to now show the drawer.

For now maybe it helps you to display the page as `fullscreen` so that the navigation bar is hidden (and the drawer icon with it). Given you could still swipe in i think.

**Comment by mpost** [comment]
You could also dispose the drawer and recreate it if necessary.

**Comment by mpost** [comment]
Since simply recreating the drawer on demand should work for now i'll close this issue. Please reopen if you think it is still valid.
