### ISSUE TITLE
Pushwoosh plugin

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#608]
the Pushwoosh plugin will not compile on the build service for Android apps. Works for iOS

https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin

**Comment by mpost** [comment]
Could you provide some more details on the problem? We tested the plugin and it works as expected.

**Comment by mpost** [comment]
Apparently the pushwoosh plugin needs the google play services cloud messaging dependencies which is not installed on the Travis instance. We will look into that.

```java
* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-gcm:+.
     Searched in the following locations:
         https://jcenter.bintray.com/com/google/android/gms/play-services-gcm/maven-metadata.xml
         https://jcenter.bintray.com/com/google/android/gms/play-services-gcm/
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/
         file:/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/m2repository/com/google/android/gms/play-services-gcm/maven-metadata.xml
         file:/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/m2repository/com/google/android/gms/play-services-gcm/
         file:/usr/local/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/maven-metadata.xml
         file:/usr/local/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/
         file:/usr/local/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-gcm/maven-metadata.xml
         file:/usr/local/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-gcm/
     Required by:
         :android:unspecified
```

**Comment by mpost** [comment]
We have made sure to include the google play services in the Travis build and could successfully build an app including pushwoosh. Please let us know if it works for you.

**Comment by bFlood** [comment]
excellent, the android build service is now working with this plugin. thanks!

**Comment by mpost** [comment]
@bFlood Good to hear. :)

**Comment by bFlood** [comment]
Android - Push event works fine when the app is active but clicking on the notification from the system tray causes the app to freeze (white screen) when Android tries to load/make active the app

10-05 09:00:21.729: E/Parcel(938): Class not found when unmarshalling: com.eclipsesource.tabris.android.internal.javascript.JavaScriptApp
10-05 09:00:21.729: E/Parcel(938): java.lang.ClassNotFoundException: com.eclipsesource.tabris.android.internal.javascript.JavaScriptApp
10-05 09:00:21.729: E/Parcel(938): 	at java.lang.Class.classForName(Native Method)
10-05 09:00:21.729: E/Parcel(938): 	at java.lang.Class.forName(Class.java:308)
10-05 09:00:21.729: E/Parcel(938): 	at java.lang.Class.forName(Class.java:272)
10-05 09:00:21.729: E/Parcel(938): 	at android.os.Parcel.readParcelableCreator(Parcel.java:2275)
10-05 09:00:21.729: E/Parcel(938): 	at android.os.Parcel.readParcelable(Parcel.java:2239)
10-05 09:00:21.729: E/Parcel(938): 	at android.os.Parcel.readValue(Parcel.java:2146)
10-05 09:00:21.729: E/Parcel(938): 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2479)
10-05 09:00:21.729: E/Parcel(938): 	at android.os.BaseBundle.unparcel(BaseBundle.java:221)
10-05 09:00:21.729: E/Parcel(938): 	at android.os.BaseBundle.getString(BaseBundle.java:918)
10-05 09:00:21.729: E/Parcel(938): 	at android.content.Intent.getStringExtra(Intent.java:5384)
10-05 09:00:21.729: E/Parcel(938): 	at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1852)
10-05 09:00:21.729: E/Parcel(938): 	at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1399)
10-05 09:00:21.729: E/Parcel(938): 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4799)
10-05 09:00:21.729: E/Parcel(938): 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4594)
10-05 09:00:21.729: E/Parcel(938): 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:141)
10-05 09:00:21.729: E/Parcel(938): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3129)
10-05 09:00:21.729: E/Parcel(938): 	at android.os.Binder.execTransact(Binder.java:446)
10-05 09:00:21.729: E/Parcel(938): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.eclipsesource.tabris.android.internal.javascript.JavaScriptApp" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
10-05 09:00:21.729: E/Parcel(938): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-05 09:00:21.729: E/Parcel(938): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
10-05 09:00:21.729: E/Parcel(938): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
10-05 09:00:21.729: E/Parcel(938): 	... 17 more
10-05 09:00:21.729: E/Parcel(938): 	Suppressed: java.lang.ClassNotFoundException: com.eclipsesource.tabris.android.internal.javascript.JavaScriptApp
10-05 09:00:21.729: E/Parcel(938): 		at java.lang.Class.classForName(Native Method)
10-05 09:00:21.729: E/Parcel(938): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
10-05 09:00:21.729: E/Parcel(938): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
10-05 09:00:21.729: E/Parcel(938): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
10-05 09:00:21.729: E/Parcel(938): 		... 18 more
10-05 09:00:21.729: E/Parcel(938): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by mpost** [comment]
@bFlood Thanks for the info. We will look into it.

Quick github tip: When pasting a stacktrace you can wrap it in java source tags as well:

    ```java
    <my-stacktrace>
    ```

**Comment by bFlood** [comment]
also, there is an error when compiling using the Tabris Build service for iOS:

what is the official Tabris recommendation for Push notifications?

```
#define ALog(fmt, ...) NSLog((@"%s [Line %d] " fmt), __PRETTY_FUNCTION__, __LINE__, ##__VA_ARGS__);
        ^
In file included from /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/SDL Mobile/Plugins/com.pushwoosh.plugins.pushwoosh/ios/PushNotification.m:13:
In file included from /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/SDL Mobile/Plugins/com.pushwoosh.plugins.pushwoosh/ios/PushNotification.h:13:
In file included from /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/device/include/Cordova/CDV.h:28:
/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/device/include/Cordova/CDVDebug.h:25:9: note: previous definition is here
#define ALog(fmt, ...) NSLog((@"%s [Line %d] " fmt), __PRETTY_FUNCTION__, __LINE__, ##__VA_ARGS__)
        ^
/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/SDL Mobile/Plugins/com.pushwoosh.plugins.pushwoosh/ios/PushNotification.m:80:15: warning: initializing 'AppDelegate *__strong' with an expression of incompatible type 'id'
        AppDelegate *delegate = [[UIApplication sharedApplication] delegate];
                     ^          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/SDL Mobile/Plugins/com.pushwoosh.plugins.pushwoosh/ios/PushNotification.m:81:44: error: property 'viewController' not found on object of type 'AppDelegate *'
        PushNotification *pushHandler = [delegate.viewController getCommandInstance:@"PushNotification"];
                                                  ^
/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/SDL Mobile/Plugins/com.pushwoosh.plugins.pushwoosh/ios/PushNotification.m:237:16: warning: initializing 'AppDelegate *__strong' with an expression of incompatible type 'id'
                AppDelegate *delegate = [[UIApplication sharedApplication] delegate];
                             ^          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/SDL Mobile/Plugins/com.pushwoosh.plugins.pushwoosh/ios/PushNotification.m:238:45: error: property 'viewController' not found on object of type 'AppDelegate *'
                PushNotification *pushHandler = [delegate.viewController getCommandInstance:@"PushNotification"];
                                                          ^
/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/SDL Mobile/Plugins/com.pushwoosh.plugins.pushwoosh/ios/PushNotification.m:360:15: warning: initializing 'AppDelegate *__strong' with an expression of incompatible type 'id'
        AppDelegate *delegate = [[UIApplication sharedApplication] delegate];
                     ^          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/SDL Mobile/Plugins/com.pushwoosh.plugins.pushwoosh/ios/PushNotification.m:361:44: error: property 'viewController' not found on object of type 'AppDelegate *'
        PushNotification *pushHandler = [delegate.viewController getCommandInstance:@"PushNotification"];
                                                  ^
4 warnings and 3 errors generated.```

**Comment by bFlood** [comment]
this plugin still won't compile on iOS, same error as above? Can anyone at tabris get this plugin to work ? (recently that is, I know you've said it worked in the past)

thanks!

**Comment by patrykmol** [comment]
We will see if we can fit it this release. :)

**Comment by gosia-eclipsesource** [comment]
For push notifications, we now recommend using our fork of phonegap-plugin-push:
https://github.com/eclipsesource/phonegap-plugin-push
This plugin uses Google Cloud Messaging on Android and Apple Push Notification Service on iOS.
