### ISSUE TITLE
Provide API to close an app

### ISSUE THREAD

**Issue by wilsonna** [eclipsesource/tabris-js#610]
Is there a method I can call below to close the app?

``` js
    tabris.app.on("backnavigation", function(app, options) {
        if (tabris.ui.get("activePage").get("topLevel")) {
            navigator.notification.confirm(
                'Do you wish to exit the app?',
                function(buttonIndex) {
                    if (buttonIndex == 1) {
                        // What should I do here?
                    }
                }, 'Exit', ['Yes','No']
            );
            options.preventDefault = true;
        }
    });
```

**Comment by mpost** [comment]
Small hint: It is considered back practice to blog the user from leaving the app. Such question dialog could make sense in the context of a question stating:

> "Your "input" will be lost. Do you want to leave 'this screen'?"

That being said... You could close the current page with <code>page.close()</code> which would also close the app if it is the last page on the stack.

**Comment by wilsonna** [comment]
I tried that too. Unfortunately, closing the last page on the stack doesn't work. It throws the error "Cannot close the last page".

All too often, the user will accidentally exit the app by pressing the Back button in quick succession. Hence many commercial apps actually introduce this mechanism on Android to prevent accidental exits, since re-opening the app may take awhile.

**Comment by mpost** [comment]
Ah okay. I wasn't aware that you couldn't close the app by closing the last page. We will discuss how to better handle that case. Thanks for opening the issue.

Btw... those other apps "are doing it wrong". ;)

**Comment by wilsonna** [comment]
I thought of a half-baked workaround that shows my own custom dialog (created with a Composite), instead of the native one, with a message saying "Press back again to exit the app", and a single Cancel button to close the "dialog". Although this still doesn't stop the user from accidentally exiting the app by spamming the back button in quick succession, it does help users who forgot that they are already at a top level page, and the next press would exit the app.

**Comment by mpost** [comment]
That sounds like sort of valid workaround. It will not be as pretty but could do the job.

**Comment by bFlood** [comment]
does "backnavigation" work on iOS?

**Comment by patrykmol** [comment]
@bFlood Natively there is no concept of "app-closing button" on iOS. So the answer is no. The only way is to go to task manager and close app from there.

**Comment by bFlood** [comment]
thanks, I realize that but I was wondering if the event is fired when you go back a page in the stack (either by tapping the navbar button or swiping)

it doesn't appear to but it would be nice to make this similar to android

**Comment by mpost** [comment]
I still think that closing the last page on the stack should also close the app. Therefore we keep this issue around.

**Comment by mpost** [comment]
With the migration to the `NavigationView` we should consider adding a concrete method like `tabris.app.close()` to close the app since the the page back metapher will not work with multiple `NavigationViews`.

**Comment by patrykmol** [comment]
This is impossible on iOS.

**Comment by mpost** [comment]
With the addition of the `App.close()` on Android this issue has been resolved since such a feature is not available on iOS.

http://docs.tabris.com/latest/api/app.html#close
