### ISSUE TITLE
Picker background inconsistent across platforms

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#612]
```javascript
var page = tabris.create("Page", {topLevel: true, background: "blue"}).open();

var picker = tabris.create("Picker", {
  items: ["some item", "another item"], 
  layoutData: {left: 0, top: 0}
}).appendTo(page);
```

On Android `Picker`s appear transparent with black text. On iOS the widget is white with black text. The appearance of `Picker` may need to be unified on both platforms.

**Comment by mpost** [comment]
Isn't that the particular native appearance on both platforms?

**Comment by mpost** [comment]
Closing as "works as intended". The platform specific themes are honored in that case.
