### ISSUE TITLE
Support XHR response and send data type "ArrayBuffer"

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#613]
For implementation details see: http://www.w3.org/TR/2012/WD-XMLHttpRequest-20120117/

**Comment by tbuschto** [comment]
I'll try to find time to figure out if there is a good way for both platforms to read/write arraybuffer/typedarray.

**Comment by ralfstx** [comment]
The `responseType` `arraybuffer` is supported as of 2.0.0 Beta 1.
