### ISSUE TITLE
TextInput type:search on Android

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#616]
TextInput with type:"search" does not show the Search keyboard on Android (should it?)

**Comment by mpost** [comment]
@bFlood You are correct. Currently the <code>search</code> type has no affect on Android. We could  apply the <code>[IME_ACTION_SEARCH](http://developer.android.com/reference/android/view/inputmethod/EditorInfo.html#IME_ACTION_SEARCH)</code> to it to change the keyboard behavior.

**Comment by bFlood** [comment]
that would be great. also, maybe some other methods to control display of the keyboard. For instance, be able to detect when the Search Key or Done Key were pressed and then be able to close the keyboard (can we do this now?)

thanks!

**Comment by bFlood** [comment]
the "accept" event works well and (I'm not sure why) but now the "Done" button  on the keyboard shows up now instead of the "Next" button. Not sure why, there was always only a single TextInput on the page. maybe hooking the "accept" event caused it to change

either way, this works for what I need now. closing the issue

**Comment by mpost** [comment]
I am happy to hear that you could solve the problem. I'll reopen the issue though to track the implementation of the <code>search</code> type on Android.

**Comment by mpost** [comment]
Closing as implemented for the 2.0 release.
