### ISSUE TITLE
Clarify/streamline JavaScript-only custom widget development process

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#617]
Creating JS-only custom widgets can be either done by using factory methods or by using the `tabris.registerType` infrastructure. What would be the recommended way of doing that? Using the latter can be advantageous for some reasons, e.g.: 
* custom widgets will have own type in the Tabris.js context
* overwriting default methods can be done in a convenient way
* properties may have own types
* setters/getters of properties can be overwritten

It has some implications though:

* Event, set/get and create operations are sent by default method implementations over the native bridge, so they must be overwritten by the user to prevent this behavior. This sounds like a hard to maintain boilerplate code. Is there a way to improve the process, like e.g. introduce a JavaScript-only custom widget type using the custom widget infrastructure for which communication doesn't involve the native bridge?

* What would be the recommended way to add own property types?

Custom widget documentation is lacking some important details which would be currently needed for the creation of JavaScript-only custom widgets using `tabris.registerType`:

* Internal widget types. Most JavaScript-only custom widgets would extend the `rwt.widgets.Composite` type.
* `_create` key. Overwriting the `create` method would be needed to append more widgets to the base widget and prevent a `create` operation from being sent over the native bridge.
* `listen` event map value. Overwriting `listen` will be needed to prevent handler registrations from being sent over the native bridge.
* The property `access` map. One would need to overwrite setters/getters to prevent operations from being sent over the native bridge.

**Comment by ralfstx** [comment]
Closing as dup of #601. @cpetrov If any of the above is still relevant, please add your points to this issue.
