### ISSUE TITLE
Improve action bar customizability

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#618]
One common use case for the action/navigation bar is a place for widgets used for filtering and sorting results. This pattern can solve visual clutter when requirements are not too complex.

On iOS this is usually done by including modal drop-down widgets and on Android - contextual action bar mode with "drill-down" style navigation.

On both platforms filter/sort widgets are usually combined with a text input widget for keyword search.

| iOS (App Store) | Android (Keep) |
| --- | --- |
| ![sort_ios](https://cloud.githubusercontent.com/assets/2341769/9680538/cadd2e98-52f7-11e5-9247-aab31251a730.PNG) | ![screenshot_2015-09-06-11-32-37](https://cloud.githubusercontent.com/assets/2341769/9680713/1f15201e-52f9-11e5-8379-70cc7f58a469.png) ![screenshot_2015-09-06-11-38-55](https://cloud.githubusercontent.com/assets/2341769/9680806/d3950108-52f9-11e5-92f6-bda9eb754757.png) |

**Comment by bFlood** [comment]
+1

**Comment by luciandinu** [comment]
+1

**Comment by mpost** [comment]
The desired effect can be achieved with a `Popover` and an overlayed Navview.
