### ISSUE TITLE
Provide a way to display modal containers

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#619]
Modal widgets are used to exclusively get user's attention for an interaction. They usually disappear when tapped outside their bounds.

Modal views are commonly used in native apps on both platforms. 

| Examples |
| --- |
| ![screenshot_2015-09-06-12-04-34](https://cloud.githubusercontent.com/assets/2341769/9681362/cd3f0098-52fd-11e5-9706-493598457262.png) |
| ![screenshot_2015-09-06-12-04-12](https://cloud.githubusercontent.com/assets/2341769/9681375/dd1635cc-52fd-11e5-9830-83fa520b7022.png) |
| ![sort_ios](https://cloud.githubusercontent.com/assets/2341769/9681429/399362ac-52fe-11e5-86cf-ca872ffef49c.PNG) |
| ![Modal intro (iOS)](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/Art/modal_intro_2x.png) For the first picture of this iOS example `cordova-plugin-dialogs` may be used, for the second picture see #580. |

**Comment by bFlood** [comment]
+1

**Comment by mpost** [comment]
+1 For the feature and for adding all the screenshots :)

**Comment by iteearmah** [comment]
+1

**Comment by cookieguru** [comment]
+1

**Comment by natanraj** [comment]
Any idea when will this come ? Eager to implement this.

**Comment by cookieguru** [comment]
@natanraj Have you tried [cordova-plugin-actionsheet](https://github.com/EddyVerbruggen/cordova-plugin-actionsheet)?

**Comment by natanraj** [comment]
@cookieguru I liked this action sheet. Apart fromproviding  action-hyperlinks, i don't have any other means of designing components inside, to my least knowledge goes

**Comment by mpost** [comment]
@natanraj we are aware that we are currently lagging in the modal department. We will start out with a simple dialog to show modal messages with a couple of buttons like OK/Cancel and expand it to more elaborate elements.

**Comment by maxapps** [comment]
Any progress on this? It's another major issue with using Tabris (along with supporting font icons).

**Comment by cookieguru** [comment]
@maxapps Currently there's [AlertDialog](https://tabrisjs.com/documentation/latest/api/AlertDialog.html) and [ActionSheet](https://tabrisjs.com/documentation/latest/api/ActionSheet.html) but nothing like the screenshots above

**Comment by mpost** [comment]
@maxapps Use AlertDialg and ActionSheet is currently the recommended way. Additionally you will be happy to hear that you can use custom fonts starting with the yet to be released tabris.js 2.3. You can try it out in the nightly builds if you are curious. https://github.com/eclipsesource/tabris-js/commit/e92cb9f1ae68c97972078e3e686d04c014d865cd

**Comment by maxapps** [comment]
@mpost Fantastic news about font icons in Tabris 2.3.
I'm familiar with AlertDialog and ActionSheet but they can't really be used for anything but the most basic dialogs. For now, I'm creating them manually using Composite and [Material Design guidelines](https://material.io/guidelines/components/dialogs.html).

**Comment by mpost** [comment]
@maxapps What is your targeted usecase for more flexible dialogs?

**Comment by mpost** [comment]
We have added the new `Popover` which in Tabris 2.5. This should cover some of the use cases.

**Comment by mpost** [comment]
With the introduction of the `Popover` we should close this issue and reopen a new one for the Android native Popupmenu we see in the first screenshot. Is that fine with @cpetrov?

**Comment by mpost** [comment]
Closing this in favor of the remaining android popup menu support as outlined in https://github.com/eclipsesource/tabris-js/issues/1889
