### ISSUE TITLE
Support customizing Switch button colors

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#621]
Most Tabris.js widget support setting the background color of the widget. This could be the color of the widget's track in checked state.

Optimally there could be properties for setting the colors of the thumb and the track in checked, unchecked (track) and pressed, unpressed (thumb) states.

**Comment by bFlood** [comment]
+1

**Comment by ralfstx** [comment]
I'd suggest to
- introduce a property `thumbColor` that applies to the movable thumb
- introduce properties `onXxxColor` and `offXxxColor` that colors the plate depending on the state. Replace Xxx with Plate, Frame, Background? This property would only be supported on iOS.
- ignore the properties `textColor` and `background` in the Switch widget.

**Comment by mpost** [comment]
The <code>thumbColor</code> property will also color the "inside" of he switch with a lighter version of the color. The "inside" color is derived from the "tintColor" property on Android, to which we would map the <code>thumbColor</code>.

![Material Design Switch](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7NDg4aGIzVXYxVEE/components_switches_switch1.png)

**Comment by ralfstx** [comment]
If there are no objections, I'd name the colors:

* `thumbColor`
* `onFrameColor` (iOS only)
* `offFrameColor` (iOS only)

**Comment by cpetrov** [comment]
Android uses the term `track` for the frame. This term might be more familiar to app developers.

**Comment by ralfstx** [comment]
@patrykmol Would you think "track" makes sense on iOS as well (`onTrackColor`, `offTrackColor`)?

**Comment by ralfstx** [comment]
@mpost Seems there is a new API to set the track colors on Android as well: https://developer.android.com/reference/android/widget/Switch.html#setTrackTintList%28android.content.res.ColorStateList%29

**Comment by patrykmol** [comment]
@ralfstx I would like `Background` or `Tint` but @mpost does not like that and I don't have better ideas.

**Comment by mpost** [comment]
@patrykmol I would not fancy background as that could also be the area of the bounds. As been said before.. on android there is a "track" (the part the knob slides in) and the "thumb" (the part that moves) they can be colored separately but only starting with Android 6. Before that we only have a "tint" property which effects the "track".

**Comment by patrykmol** [comment]
@mpost @ralfstx OK, let's stay with `track` keyword.

**Comment by mpost** [comment]
With all of the above said... That applies to the regular Switch button on Android. In practice we use [SwitchCompat](https://developer.android.com/reference/android/support/v7/widget/SwitchCompat.html), to have a material look on pre Android 5 which does not support the track property (yet) and only allows to tint (which applies to the track).

**Comment by ralfstx** [comment]
*on track* and *off track* sounds funny. How about `trackOnColor` and `trackOffColor`? Also better for editor support.

**Comment by ralfstx** [comment]
@tbuschto Why did you close this issue? The change is still pending in Gerrit, and it seems it's not yet implemented in the clients, is it?

**Comment by ralfstx** [comment]
Implemented on both platforms. These new properties are available on Switch:

- thumbOnColor
- thumbOffColor
- frameOnColor
- frameOffColor
