### ISSUE TITLE
Introduce a Slider selection event triggered after the finger has been lifted

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#623]
Triggering resource intensive operations in a "select" event handler for each thumb movement may not be favorable. Introducing an alternative to the "select" event triggered only when the finger has been lifted will help trigger those operations only once when the user has finished his selection.

**Comment by tbuschto** [comment]
Closed due to inactivity. If you have resource intense work to do due to a slider selection event you can use a throttle mechanism built on setTimout.
