### ISSUE TITLE
Modernize iOS navigation drawer icon, change button text

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#624]
iOS navbar questions

1. can we change the icon used for the hamburger menu? It doesn't look like the standard one used in other iOS apps

2. Can we change the Back button text? 

thanks!
![img_0918](https://cloud.githubusercontent.com/assets/404991/9788996/46088200-579b-11e5-96e7-54f99537e8dd.PNG)

**Comment by patrykmol** [comment]
@bFlood Unfortunately you can't change any of those at the moment.

**Comment by mpost** [comment]
@patrykmol Maybe we could modernize the navigation drawer icon for the next release.

**Comment by bFlood** [comment]
that would be great, thanks

**Comment by patrykmol** [comment]
Menu icon will be updated as of 1.5.
