### ISSUE TITLE
iOS button height changes after tap

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#625]
iOS button height changes after tap. is this a bug?

**Comment by cpetrov** [comment]
This is a known issue and we are working on a solution.

**Comment by bFlood** [comment]
any word on this, its not a major issue but kind of ugly

**Comment by mpost** [comment]
@bFlood We are aware of this visual glitch and put it high on our TODO list. Expect a fixed at the beginning of next year.
