### ISSUE TITLE
Table or Grid View

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#626]
Table or Grid View - any thoughts on the best way to do this? a CollectionView in a horizontal ScrollView works but seems a little slow to load for larger sets of data

thanks

**Comment by mpost** [comment]
@bFlood A similar effect can be achieved by evenly spacing the content of one item. Eg. showing two elements side by side in one item.

You mention horizontal scrolling. Could you be more specific on what you are trying to achieve?

**Comment by bFlood** [comment]
horizontal scrolling - I need to display rows of data where the columns (in some cases 20-30 columns) would extend off the width of the screen. So the view needs to scroll vertically and horizontally

I've got CollectionView hosted in a horizontal ScrollView working pretty well now. you just need to preprocess all the row data to find maximum widths and heights and then use those when drawing the cells. 

thanks

**Comment by mpost** [comment]
@bFlood Seems like a reasonable approach. Good that it works out for you.
