### ISSUE TITLE
Picker does not fire event when user selects the selected entry

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js#630]
I have a use case where I want to get a selection (or any of the other) event  when the user opens the picker and then selects the value that was selected before.

Is there a reason why we do not fire events in that case?

In the case of the ```select``` event at least there is no indication in the event's name that this event needs an actual "change" to get fired (in contrast to the other two events: ```change:selection``` and ```change:selectionIndex```).

**Comment by mpost** [comment]
I have checked the selection listener on Android. It does not fire when the selection does not change so this feature would take some effort on Android.

**Comment by mpost** [comment]
I also wouldn't call it a bug since when nothing changes, a change event is not fired (as one would expect). I'll therefore replace the "bug" tag with "enhancement".

**Comment by ralfstx** [comment]
Actually, iOS *does* send another select event when the user chooses the previously selected item and then presses "Done" in the popup. It does not send an event on "Cancel".

On Android, I would expect an event on actively selecting an item from the picker drop-down, regardless if it was selected before or not. If the drop-down is closed by tapping anywhere outside the drop-down, I would not expect an event.

**Comment by ralfstx** [comment]
Works on iOS, fixed on Android.
