### ISSUE TITLE
Tabris Calendar widget - iOS

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#631]
are there plans to include an iOS version of this widget? or is this just a demonstration of how to create custom widgets on Android?

https://github.com/eclipsesource/tabris-calendar

**Comment by mpost** [comment]
Currently it is just a demonstration how to create a custom widget but we will also introduce iOS support in the future. Alas... PRs are welcome. :)

**Comment by mpost** [comment]
Since there is no direct counterpart to the Android CalendarView on iOS, i will close this issue. Please continue the discussion on https://github.com/eclipsesource/tabris-calendar
