### ISSUE TITLE
EMap plugin on iOS - build error

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#632]
`s/ios/build/SDLMobile.build/Debug-iphoneos/SDLMobile.build/Objects-normal/arm64/Map.o
/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/SDLMobile/Plugins/com.eclipsesource.tabris.maps/Map.swift:11:18: error: use of undeclared type 'CDVPlugin'
@objc class Map: CDVPlugin {
                 ^~~~~~~~~
CompileSwift normal arm64 /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/SDLMobile/Plugins/com.eclipsesource.tabris.maps/MapView.swift
    cd /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios`

full log here: https://gist.github.com/bFlood/b9a5141779e782d1f630

**Comment by cpetrov** [comment]
The ESMap custom widget is currently only implemented on Android.

**Comment by patrykmol** [comment]
This is fixed with maps widget release.
