### ISSUE TITLE
possible Android CollectionView performance issue

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#634]
seeing this in the Android adb logs when a CollectionView is refreshed (either refresh method or setting the items). it appears several times in a row and slows down the refresh (not bad but noticeable, on older android devices it's pretty bad)

`09-22 16:56:32.583: W/View(6946): requestLayout() improperly called by android.support.v7.widget.AppCompatTextView{11716aa4 V.ED.... ......ID 128,32-1168,372 #7f090066 app:id/developer_console_log_entry_message} during second layout pass: posting in next frame`

many times you see this displayed as well:
`09-22 16:56:32.563: I/Choreographer(6946): Skipped 38 frames!  The application may be doing too much work on its main thread.`

this happens on all versions of android that I have tried. it's worse when a CollectionView cell has more tabris widgets on it

**Comment by mpost** [comment]
We have seen this before but we didn't see it have a performance impact. Interesting to hear that it might impact performance. Can you share your collection view javascript code? Or distill it to an example?

**Comment by mpost** [comment]
We are not seeing these log messages anymore in the latest version of the Tabris.js. Closing for now.
