### ISSUE TITLE
Android V5 - button background setting not working

### ISSUE THREAD

**Issue by davehibshman** [eclipsesource/tabris-js#635]
Trying to set background property to "#0000FF"  on my button is not working. This is easily observed running the Inputs example and noticing that on Android version 5.0 the Place Reservation button background is not red, though it is configured to be so.

**Comment by mpost** [comment]
Could you provide a snippet that showcases your issue?

**Comment by bFlood** [comment]
+1

**Comment by mpost** [comment]
I am seeing a red button on Android 5.1 (Nexus 5, 6, 7) any more infos on hardware, software?

**Comment by bFlood** [comment]
Samsung Android 5.0, latest tabris.js demo app from Play Store

![image](https://cloud.githubusercontent.com/assets/404991/10138466/9b052fc6-65cc-11e5-8647-731a092eeaaa.png)

![image](https://cloud.githubusercontent.com/assets/404991/10138475/a52a9c48-65cc-11e5-9821-e38099b942ae.png)

**Comment by mpost** [comment]
Okay thanks for the info. We are looking into it.

**Comment by davehibshman** [comment]
Samsung Galaxy 5, Android 5.0.

**Comment by mpost** [comment]
We can confirm the issue for Android 5.0 and are working on a fix. The bug is not present on Android 5.1+ or up until 5.0.

**Comment by mpost** [comment]
The issue is fixed for the upcoming Tabris.js 1.3 release.

For curios folks: The issue is related to a "bug" in Android 5.0 as outlined [here](http://stackoverflow.com/a/29756195/271877)

**Comment by davehibshman** [comment]
Thanks, great turnaround.
