### ISSUE TITLE
Improve/restore intended parallax example layout

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#639]
* Picture must appear behind the semi-transparent header. The header initially appears under the image on iOS until the device is rotated for the first time.
* Content overlaps the header when scrolling. It must stay behind the header.
* Hide the UI toolbar (optional)

**Comment by jkrause** [comment]
![screenshot_2015-12-19-09-54-06](https://cloud.githubusercontent.com/assets/624059/12227398/6435cdea-b82c-11e5-85e2-9860bc03bfd1.png)

**Comment by cpetrov** [comment]
Fixed in 4870e4d7760e4f32589d555a19607115a7e89550.
