### ISSUE TITLE
Cordova plugins resources from NPM

### ISSUE THREAD

**Issue by calebeaires** [eclipsesource/tabris-js#640]
Cordova 5.1.1 use gradle to build on Android and made changes on plugins resources. Plugins authors has updating his plugins to support NPM installs. I have tried to build with it, but had no success.    

 ```<gap:plugin name="cordova-plugin-device" source="npm" />```

**Comment by gosia-eclipsesource** [comment]
@calebeaires Please try like this:
```<plugin name="cordova-plugin-device" spec="^1.0.1" />```

No need to specify source. The plugin's ID tells the build service to look for it on NPM.
Also with 5.1.1 you don't need to use gap:plugin anymore.

**Comment by cookieguru** [comment]
Most of the properties that `cordova-device-plugin` will give you can also be accessed in [`tabris.device`](https://tabrisjs.com/documentation/latest/api/device).  The only exception is `uuid` which is discussed in #609.
