### ISSUE TITLE
Some Missing features.

### ISSUE THREAD

**Issue by yayolonginos** [eclipsesource/tabris-js#642]
Hi, I've started to create some POCs with this framework, and in few hours I was up and running, and I found it to be really exciting.

Nevertheless, I have found that some features widgets are not available like:

* Date / Time Pickers / Slide view . Available thru incubator, but have some quirks at least on KitKat 4.4
* Number Input (Not Text with number keyboard)
* Indeterminate progress indicator.
* Grid Layout.
* A way to return data from a Page in the case custom modals are not possible.
* Baked in SQLite, LocalNotifications support, it is not so great to look outside the Fx for basic functionality.

I also have some troubles with the documentation, there are certain details that might require further explanation like a fully pledged Add Cordova Plugins 

Also I need to note some good points as the Parse sdk works out of the box and it even keeps the session active. nice!

**Comment by mpost** [comment]
Thanks for your feedback. You raised some valid points, most of which we are ware of (and are working on :)).

Some remarks:
* What kind of number input would you like to see?
* You could also incorporate SQLite support via a cordova plugin.
* Great to see Parse working for you

**Comment by yayolonginos** [comment]
Sorry for the late response. Its good to know that some of them are in progress, I cannot wait to test them out.

For the numeric input I would like to have a numeric box that only accept digits and points and commas, currently Im able to enter ()*  etc while using number.

**Comment by mpost** [comment]
Fyi. we created a separate issue for the spinning progress indicator: https://github.com/eclipsesource/tabris-js/issues/647

**Comment by gosia-eclipsesource** [comment]
Number input is currently a "won't fix", for other points we opened more issues.

Date / time pickers: #652
Return Page data: #653

Progress on grid layout will continue to be tracked in #21.

**Comment by mpost** [comment]
@yayolonginos Regarding the number input, what characters are displayed on the keyboard depends on the keyboard you use. We already provide the correct hint but the keyboard has the final saying. I would recommend to recreate the number input in pure widgets similar to a dialer app.
