### ISSUE TITLE
Only one Tabris App per github repo

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#643]
It looks like the Tabris App UI will only allow a single app per github repo. I'm sure there's a good reason for this but I was wondering how to deal with the following situation

I would like to have two apps per repo, one for debug/development and one for release. I can use build hooks to alter the single config.xml between the two

the main reason this is necessary is to use two different Google Maps API keys (with two different fingerprints) for each app. I could just clone the existing repo everytime I want to create a new release build but it would be nice to have them both pull from the same location

any thoughts? thanks

**Comment by mpost** [comment]
We had a discussion in the past to provide subfoldes into the repo in the build config. We haven't gotten around to implement that yet though. 

So currently my best bet would also be a build hook. Any other thoughts?

**Comment by mpost** [comment]
Appereantly my pervious statment is no valid as we already support to specify the branch name and to state the subfolder path inside a selected branch to act as the apps base folder.

Could you describe your problem a bit more detailed? From my understanding you could specify to have two different builds, building the same app from the same repo but providing a different maps api key in each build configuration.

**Comment by bFlood** [comment]
ok, this worked for me

1. created a new tabris app using a random github repo
2. opened and edited the new app to point at the repo that is already in use. I had to save and then reopen the app but the change did take
3. use build hooks and environmental variables to change the Google Maps API key and EnableDeveloperConsole variables in config.xml

I'll take a look at using a different branch (not sure how you select this from your new App UI) but the above workflow works for me now, so I'm happy

thanks
