### ISSUE TITLE
Custom Widget - iOS example

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#644]
are there any custom widget examples for iOS yet? 

maybe you could just release some of the internal code used for a basic control (ex: checkbox or textview etc)

thanks

**Comment by patrykmol** [comment]
I'm writing custom maps widget for iOS. It should be available soon.

**Comment by bFlood** [comment]
thanks @patrykmol

**Comment by bFlood** [comment]
hi @patrykmol - any movement on this? thanks

**Comment by patrykmol** [comment]
@bFlood Not at the moment. Sorry. :(

**Comment by gosia-eclipsesource** [comment]
Custom maps widget is finished for iOS:
https://github.com/eclipsesource/tabris-maps
