### ISSUE TITLE
ReloadApp from Dev Console crashes android

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#645]
Open Developer Console drawer and click the refresh/reload button On Android, it will consistently crash the entire app

this just started happening on a recent build, it used to work perfectly. I can't tell if its something I added or something in the tabris runtime. 

``` java
10-06 16:27:56.460: E/AndroidRuntime(19746): FATAL EXCEPTION: main
10-06 16:27:56.460: E/AndroidRuntime(19746): Process: com.sdlportal.sdlmobile3, PID: 19746
10-06 16:27:56.460: E/AndroidRuntime(19746): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.eclipsesource.tabris.android.internal.javascript.JavaScriptApp.getBaseUri()' on a null object reference
10-06 16:27:56.460: E/AndroidRuntime(19746): 	at com.eclipsesource.tabris.android.internal.toolkit.nativeaccess.App.restartApp(App.java:323)
10-06 16:27:56.460: E/AndroidRuntime(19746): 	at com.eclipsesource.tabris.android.internal.toolkit.operator.AppOperator.call(AppOperator.java:107)
10-06 16:27:56.460: E/AndroidRuntime(19746): 	at com.eclipsesource.tabris.android.internal.toolkit.DeveloperConsoleView$5.onClick(DeveloperConsoleView.java:209)
```

**Comment by mpost** [comment]
Are you seeing the behavior inside the Tabris.js app or your own custom build app? Is the custom build in debug mode or production?

**Comment by bFlood** [comment]
1. custom build app (using tabris build service)
2. tabris version: latest (I might have been using v1.2.0 prior, can't remember) 
3. debug mode with DeveloperConsoleEnabled

**Comment by mpost** [comment]
@bFlood We tried to reproduce the problem but with no success yet. 

Do you restart a bundled app or a remotely loaded app? Did the app you tried to launch at first successfully load? Do you see this problem only on this one specific build or do you see it on other builds as well?

**Comment by bFlood** [comment]
1) it crashes on both the bundled and remotely loaded app
2) yes, it always loads and functions correctly. this only occurs when reloading from the dev console. for this build, it is 100% reproducible (even on different wifi networks)
3) I'll try another build and see if that works. do you think the 1.2.0 vs. latest would make a difference or are they just the same right now

**Comment by mpost** [comment]
@bFlood Please try another build or even better another app. "latest" is currently the same as "1.2.0".

**Comment by bFlood** [comment]
created a new build and it still crashes the same way

any thoughts on what could be causing it (based on the error above), maybe a plugin I'm using?

it's not critical, it doesn't affect the release build but it makes debugging a lot more tedious

**Comment by mpost** [comment]
@bFlood I am still not seeing the problem in your setup. What is happening on the client, is that it takes the JavaScriptApp object that has been passed to the activity and reuses its url to restart the activity. If that app object is null it must mean that either it has never been set (which means you couldn't have started the app in the first place) or the intent has been reset. Did you maybe launch the app via some other mechanism again?

**Comment by bFlood** [comment]
no, I launch the app and then connect via url  (it happens with the embedded app as well)

here's a quick video:
https://www.dropbox.com/s/j8n8juaf2ldq9zc/example%5B1%5D.mp4

**Comment by mpost** [comment]
Hi brian... Thanks for the video. We might have an idea of what if going on. In you video we can see that you are using several cordova plugins... We think that one of the cordova plugins overrides the intent with which the app is first started. So our solution would be to copy the launch intent of the Tabris.js app and make a copy of it instead of fetching the launch url directly from the intent.

Are you able to verify whether one particular cordova plugin is causing the app to crash? Or to provide us with a list of plugins so that we can check if they modify the intent?

**Comment by bFlood** [comment]
maybe the Pushwoosh plugin : https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/blob/master/plugin.xml#L78

  Plugins:
    https://github.com/apache/cordova-plugin-battery-status
    https://github.com/apache/cordova-plugin-dialogs
    https://github.com/apache/cordova-plugin-camera
    https://github.com/katzer/cordova-plugin-badge
    https://github.com/apache/cordova-plugin-device-motion
    https://github.com/apache/cordova-plugin-device-orientation
    https://github.com/apache/cordova-plugin-contacts
    https://github.com/apache/cordova-plugin-file
    https://github.com/apache/cordova-plugin-file-transfer
    https://github.com/apache/cordova-plugin-geolocation
    https://github.com/apache/cordova-plugin-globalization
    https://github.com/apache/cordova-plugin-inappbrowser
    https://github.com/apache/cordova-plugin-media
    https://github.com/roberthovhannisyan/PhoneGap-Plugin-ListPicker
    https://github.com/EddyVerbruggen/Insomnia-PhoneGap-Plugin
    https://github.com/apache/cordova-plugin-network-information
    https://github.com/apache/cordova-plugin-vibration
    https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin
    https://github.com/litehelpers/Cordova-sqlite-storage
    https://github.com/pwlin/cordova-plugin-file-opener2
    https://github.com/Sharinglabs/cordova-plugin-datepicker
    https://github.com/Paldom/SpinnerDialog
    https://github.com/EddyVerbruggen/cordova-plugin-actionsheet
    https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin
    https://github.com/Moussawi7/Cordova-GPSLocator
    https://github.com/VVelda/device-feedback
    https://github.com/spatialdatalogic/tabris-maps
    https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin

**Comment by mpost** [comment]
Thanks for this (exhaustive) list. 

You mentioned the pushwoosh plugin... judging from the a [quick search](https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/search?utf8=%E2%9C%93&q=intent) it does not seam as if the plugin is altering the intent.

**Comment by mpost** [comment]
Does the app allow to reload when you remove the pushwoosh plugin dependency?

**Comment by bFlood** [comment]
I'll try it with Pushwoosh removed (but I would still need a Push plugin, any Tabris recommendations?)

**Comment by mpost** [comment]
@bFlood Yeah you should be able to use the PushWoosh plugin. We are just trying to narrow down the cause of the problem for now.

I went through all the plugins you listed and didn't find any plugin that seriously altered the launch intent. The PushWoosh plugin does make use of the `onNewIntent`callback which could be the source of the problem.

**Comment by mpost** [comment]
@bFlood We were able to reproduce the problem by building an app that makes use of the PushWoosh plugin. We will fix the issue with the next release.

**Comment by bFlood** [comment]
great, thanks for looking into it. if you are testing the Pushwoosh plugin, there's also these issues:
https://github.com/eclipsesource/tabris-js/issues/608

the issue of not launching on a cold start from a push message sounds like it could be related to the intent and how Tabris implements its loading

**Comment by mpost** [comment]
Yeah #608 could be related. I am not 100% sure. I had success with the PushWoosh plugin before.

**Comment by mpost** [comment]
@bFlood We have fixed the issue. You can switch to "nightly" on the build service to try it out yourself.

**Comment by bFlood** [comment]
working, thanks!

issue https://github.com/eclipsesource/tabris-js/issues/608 is still there but at least the reloading is easier now

are you seeing the same thing when receiving a push notification while in the app is in the background? (or a cold start)

**Comment by bFlood** [comment]
so much easier to debug now, thanks!

**Comment by mpost** [comment]
We will look at #608 independently. Great to hear that this issue has been resolved for you.

**Comment by bFlood** [comment]
thanks for the fast turnaround and more importantly, a fantastic product. I find Tabris so much easier to use then the other NativeUI+JS alterntives, really great job!

**Comment by mpost** [comment]
@bFlood Thanks for your kind words. :)
