### ISSUE TITLE
Incorrect quickstart

### ISSUE THREAD

**Issue by alexiusp** [eclipsesource/tabris-js#646]
I've tried to follow the quickstart in the documentation section. And the myapp.js do not work. It shows just a white screen without any text on it. In the log of the http-server I see following lines:

[*Date and time*] "GET /node_modules/tabris.js" Error (404): "Not found"
[*Date and time*] "GET /node_modules/tabris.json" Error (404): "Not found"

tabris.js is installed with "npm install" command. And the file is in the folder. I don't know why the server doesn't see it.

Why it asks for tabris.json? There is no such file in node_modules/tabris folder!

The application example from the "My scratchpad" section works correct if I replace the content of myapp.js with the content of the scratchpad. But still the errors mentioned above are present in http-server log.

Here is a full log of one application start:
[Wed, 07 Oct 2015 22:53:48 GMT] "GET /package.json" "com.eclipsesource.tabris.android/2.0.0 (com.eclipsesource.tabris.js/1.2.0-20150827-1521) (Sony; C6603; 5.1.1)"
[Wed, 07 Oct 2015 22:53:49 GMT] "GET /node_modules/tabris" "com.eclipsesource.tabris.android/2.0.0 (com.eclipsesource.tabris.js/1.2.0-20150827-1521) (Sony; C6603; 5.1.1)"
[Wed, 07 Oct 2015 22:53:49 GMT] "GET /node_modules/tabris/" "com.eclipsesource.tabris.android/2.0.0 (com.eclipsesource.tabris.js/1.2.0-20150827-1521) (Sony; C6603; 5.1.1)"
[Wed, 07 Oct 2015 22:53:49 GMT] "GET /node_modules/tabris.js" "com.eclipsesource.tabris.android/2.0.0 (com.eclipsesource.tabris.js/1.2.0-20150827-1521) (Sony; C6603; 5.1.1)"
[Wed, 07 Oct 2015 22:53:49 GMT] "GET /node_modules/tabris.js" Error (404): "Not found"
[Wed, 07 Oct 2015 22:53:49 GMT] "GET /node_modules/tabris.json" "com.eclipsesource.tabris.android/2.0.0 (com.eclipsesource.tabris.js/1.2.0-20150827-1521) (Sony; C6603; 5.1.1)"
[Wed, 07 Oct 2015 22:53:49 GMT] "GET /node_modules/tabris.json" Error (404): "Not found"
[Wed, 07 Oct 2015 22:53:49 GMT] "GET /node_modules/tabris/package.json" "com.eclipsesource.tabris.android/2.0.0 (com.eclipsesource.tabris.js/1.2.0-20150827-1521
) (Sony; C6603; 5.1.1)"
[Wed, 07 Oct 2015 22:53:49 GMT] "GET /node_modules/tabris/tabris.min.js" "com.eclipsesource.tabris.android/2.0.0 (com.eclipsesource.tabris.js/1.2.0-20150827-1521) (Sony; C6603; 5.1.1)"
[Wed, 07 Oct 2015 22:53:49 GMT] "GET /package.json" "com.eclipsesource.tabris.android/2.0.0 (com.eclipsesource.tabris.js/1.2.0-20150827-1521) (Sony; C6603; 5.1.1)"
[Wed, 07 Oct 2015 22:53:49 GMT] "GET /myapp.js" "com.eclipsesource.tabris.android/2.0.0 (com.eclipsesource.tabris.js/1.2.0-20150827-1521) (Sony; C6603; 5.1.1)"

**Comment by gosia-eclipsesource** [comment]
Hi @alexiusp,
 
The reason why myapp.js does not work is because the file is missing the last line:
`page.open();`
Add it after `.appendTo(page);` Sorry and thanks for reporting!

Regarding the errors, looking for the tabris.js module in different places before it is found is normal. That's just part of the commonJS module standard which we use to load it. Eventually it finds the module in node_modules/tabris/tabris.min.js. So everything is ok :)

**Comment by alexiusp** [comment]
Hi @gosia-eclipsesource,
Thanks for the answer. I knew that the library itself works and the problem must be in myapp.js.
Hope you will fix the Quickstart guide, so that other curious developers who tries tabris.js will avoid this trouble.

**Comment by gosia-eclipsesource** [comment]
You're absolutely right - it's now fixed in master and will be redeployed soon. Thanks @alexiusp & @cookieguru!
