### ISSUE TITLE
Add support for ActivityIndicator widget that shows ongoing activity

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#647]
Currently we only have the ProgressBar.

**Comment by bFlood** [comment]
+1

**Comment by wilsonna** [comment]
:+1:

**Comment by cpetrov** [comment]
+1

**Comment by mpost** [comment]
The Android and iOS client already support such a feature from tabris-remote but we are missing tabris.js API for it.

Here is the code in tabris-remote: https://github.com/eclipsesource/tabris/blob/master/com.eclipsesource.tabris/src/com/eclipsesource/tabris/widgets/enhancement/ProgressBarDecorator.java#L38
