### ISSUE TITLE
Support Blob/ArrayBuffer in XHR

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#650]

**Comment by bFlood** [comment]
+1

**Comment by bFlood** [comment]
any movement on this? ability to write files would be nice

**Comment by jonek** [comment]
@bFlood writing data you are receiving over XHR should be already possible right now if you receive e.g. JSON and later just write that JSON object to a file by using the Cordova file plugin.

**Comment by gosia-eclipsesource** [comment]
And regarding Blob/ArrayBuffer support, we haven't started working on it yet. It will first take some research on the native parts.

**Comment by bFlood** [comment]
@jonek I need to write a file that was created on the device, not downloaded via FileTransfer plugin. Is there a way to do this now? for this particular scenario, the device is offline as well

**Comment by ralfstx** [comment]
The responseType `arraybuffer` is supported as of 2.0.0 Beta 1. Blob is covered by #687.
