### ISSUE TITLE
Add date / time pickers as concrete widgets

### ISSUE THREAD

**Issue by gosia-eclipsesource** [eclipsesource/tabris-js#652]
Add date / time pickers as concrete widgets that can be put in the widget hirarchy.

**Comment by ralfstx** [comment]
We've found that there are good [date/time picker dialogs available as Cordova plug-ins](http://plugreg.com/search/?q=datepicker) that work with Tabris.js and provide a viable alternative to an embedded date/time picker widget. Displaying the selected date/time in a basic widget such as `TextView` and open a date picker on tap seems to be a common UX pattern.

I think that with this alternative, a DatePicker is not a high priority anymore and, unless users ask for it explicitly, I'd suggest to close this issue. Please re-open if you disagree.

**Comment by cookieguru** [comment]
As of Tabris.js 2.2.0, the [DateDialog](https://tabrisjs.com/documentation/latest/api/DateDialog.html) and [TimeDialog](https://tabrisjs.com/documentation/latest/api/TimeDialog.html) widgets are available natively.
