### ISSUE TITLE
canvas - transparent background

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#661]
canvas widget - is a transparent background possible?

**Comment by mpost** [comment]
Yeah possible. We inherited the white background.

**Comment by bFlood** [comment]
is it possible now or is this a feature that needs to be added?

**Comment by mpost** [comment]
it is a feature that needs to be added.

**Comment by bFlood** [comment]
ok, thanks. I would think it should be transparent by default

**Comment by bFlood** [comment]
is this an easy fix? it really hinders placing a canvas over any other UI elements

**Comment by gosia-eclipsesource** [comment]
Should be. @mpost is away so we will revisit it when he is back next week.

**Comment by mpost** [comment]
@bFlood We have changed the behavior previously. Could you please try the following snippet:

```java
var page = tabris.create("Page", {
  title: "Canvas",
  topLevel: true
});

tabris.create("TextView", {
  text: "hello world",
  layoutData: {left: 40, top: 50}
}).appendTo(page);

tabris.create("Canvas", {
  layoutData: {left: 10, top: 10, right: 10, bottom: 10}
}).on("resize", function(canvas, bounds) {
  var ctx = canvas.getContext("2d", bounds.width, bounds.height);
  ctx.strokeStyle = "rgba(78, 154, 217, 0.9)";
  ctx.lineWidth = 10;
  ctx.moveTo(20, 20);
  ctx.lineTo(bounds.width - 40, bounds.height - 40);
  ctx.stroke();
}).appendTo(page);

page.open();

```

![canvas](https://cloud.githubusercontent.com/assets/73655/11625263/e506e9c2-9cd9-11e5-9f18-0948c0863ff5.png)

**Comment by bFlood** [comment]
@mpost it still appears all black on iOS and Android, I'm using tabris 1.4

**Comment by mpost** [comment]
@bFlood Interesting to hear. Did you verify with the snippet above?

When you say things appear black... What exactly is black? Could you provide a snippet that shows the behavior you are describing?

**Comment by bFlood** [comment]
hmm, I tried your sample above and it worked perfectly. let me check my code and see what I'm doing wrong. thanks!
