### ISSUE TITLE
ScrollView set position

### ISSUE THREAD

**Issue by sergio-doman** [eclipsesource/tabris-js#662]
As I see, there is no way to set scrolling position for ScrollView to the top or any other place, it would be really nice to have it

**Comment by mpost** [comment]
Setting the scrolling position is a useful addition and we will be adding it in a future release.

**Comment by wilsonna** [comment]
Would just like to add that CollectionView has something similar https://tabrisjs.com/documentation/latest/api/CollectionView#revealindex

**Comment by gosia-eclipsesource** [comment]
@sergio-doman We added ability to set scrolling position with properties <code>scrollX</code> and <code>scrollY</code>. If you'd like to check it out, you can use those properties already in nightly.
