### ISSUE TITLE
Toolbar height

### ISSUE THREAD

**Issue by sergio-doman** [eclipsesource/tabris-js#664]
I can't find any way how to find available screen height. Yes, there are screen.width and screen.height but it includes toolbar which square is not available to use.

**Comment by mpost** [comment]
You could get the bounds of your current page. That gives you the height that you are able to work with.

Keep in mind that you would need to retrieve them in a bounds listener as it requires a layouting phase on startup.

**Comment by sergio-doman** [comment]
I'll try it, thank you!

**Comment by gosia-eclipsesource** [comment]
Closing this. Feel free to reopen if you have more questions.
