### ISSUE TITLE
Provide simple non-native custom widget API

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#672]
Non-native custom widgets can be easily implemented using change events. However, to put them in separate modules is not super-convenient and leads to completely different code for creating custom widgets vs. non custom-widgets. Assuming the module exports a single factory function, your code will look like this:

```
var createCustomPage = require("../pages/CustomPage.js"); // do this in every module using it
var page = createCustomPage(args);
```

If we allow to extend the tabris.create method with factories (as opposed to using the semi-internal native custom widget API), it could look like this:

```
tabris.registerType("CustomPage", require("pages/CustomPage.js")); // do this only once
var page = tabris.create("CustomPage", args);
```

The whole thing could be easily implemented in less than a day. 
Registering the same type twice should throw an exception (unless the factory is the same).
The return value must be of type Proxy, thereby not breaking the pattern that tabris.create always creates an object with native resources.

**Comment by ralfstx** [comment]
@tbuschto Is this still relevant in the light of ES6?

**Comment by tbuschto** [comment]
No. It's just documentation.
