### ISSUE TITLE
Support adding new properties on existing widget types

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#673]
Currently we have preliminary API to create new widgets but we do not allow to add new properties on existing widgets. These new properties should be send to the native side.

**Comment by ralfstx** [comment]
You can add properties to the prototypes of existing widgets:
```js
Object.defineProperty(tabris.Widget.prototype, 'foo', {
  get() {
    return this._foo;
  },
  set(value) {
    this._foo = value;
  }
});
```
In the getter and setter methods, you can use [NativeObject](https://github.com/eclipsesource/tabris-js/blob/master/src/tabris/NativeObject.js) methods like `_nativeSet` and `_nativeCall` to communicate with the client.

**Comment by dalisoft** [comment]
@ralfstx You can do like this too
```javascript
class foo extends Widget {
constructor () {
super();
}
}
```

**Comment by ralfstx** [comment]
@dalisoft That's right and it's the recommended way. Moritz' use case was a bit different, he needed to add a custom property to *all* existing widgets.

Anyhow, both is now possible with Tabris.js 2.0.
