### ISSUE TITLE
SearchAction "input" callback is fired inconsistent across Android and iOS

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#675]
On iOS entering one letter already triggers the `input` event callback, while on Android it takes two characters to trigger the callback. The boundary should probably be removed on Android.

**Comment by cookieguru** [comment]
Additionally, the Cancel button on iOS triggers the `input` event callback whereas the X (clear input) and back button (toolbar) on Android does not.

**Comment by mpost** [comment]
Issue has been fixed on Android by removing the 2 character limit.

This also fixes the issue mentioned by @cookieguru that the "input" event was not triggered when the clear button ("X") is invoked.
