### ISSUE TITLE
Local development server timeout on Android developer app

### ISSUE THREAD

**Issue by gverschuur** [eclipsesource/tabris-js#679]
When using the developer app on a Samsung S4 (Android 5.0.1), the app gives a timeout when trying to connect to the development server URL with the message: `could not establish connection, failed to connect to ... after 5000ms`. 

The http server is running on node v0.12.7. When opening the URL in the browser on the device, I get the directory content as expected, so the device can find the server on my machine.

I've tried reinstalling the app, restarting the server etc but nothing works. The iOS device connects without any problems whatsoever.

This is the first day I'm working with Tabris and I have zero experience with Android devices, so I don't know exactly what more information to give.

**Comment by mpost** [comment]
My first shoot would be "Is the ip, port, path etc entered correctly"?

**Comment by gverschuur** [comment]
As I said, opening the same URL in the browser works, and opening the same URL on the iOS developer successfully starts my app. So yes, ip, port etc are all correct.

**Comment by mpost** [comment]
There is inherintly nothing wrong with the way the Android client performs connection requests as far as we know. Are you able to connect to eg the scratchpad from within the "Tabris.js" app in the play store?

**Comment by gverschuur** [comment]
Yes, the scratchpad works without any difficulty. After restarting the device, the error seemed to persist but I managed to launch the app 1 or 2 times. However, after going back to dev app home screen and trying to connect again, the timeout occurred again, and sometimes the developer app hangs in it's entirety and just show a white screen.

**Comment by gverschuur** [comment]
I just tried the app on a Samsung Galaxy S5 running Android 5.0.2 and that one works without any problems, so I'm going to be using that one.

**Comment by mpost** [comment]
Glad you could figure it out.
