### ISSUE TITLE
Builds are failing for Android and iOS

### ISSUE THREAD

**Issue by wilsonna** [eclipsesource/tabris-js#680]
Anyone encountered this problem as well? It was working this morning for me. But I'm getting this now. Note the "(empty)". https://www.traviscistatus.com/# didn't show anything abnormal.

    /home/travis/.nvm/v0.10.36/lib
    └─┬ grunt-cli@0.1.13 
      ├─┬ findup-sync@0.1.3
      │ ├─┬ glob@3.2.11
      │ │ └─┬ minimatch@0.3.0
      │ │   ├── lru-cache@2.7.0 
      │ │   └── sigmund@1.0.1 
      │ └── lodash@2.4.2 
      └─┬ nopt@1.0.10
        └── abbrev@1.0.7 
    travis_time:end:0c352407:start=1446810508527154392,finish=1446810511153944292,duration=2626789900
    travis_fold:end:before_install.2
    travis_fold:start:before_install.3
    travis_time:start:01181523
    $ npm install -g cordova@5.1.1
    npm WARN engine npm@1.3.4: wanted: {"node":">=0.6","npm":"1"} (current: {"node":"0.10.36","npm":"3.3.12"})
    npm WARN install:rimraf@2.2.0 ENOENT, chmod '/home/travis/.nvm/v0.10.36/lib/node_modules/cordova/node_modules/npm/node_modules/rimraf/bin.js'
    /home/travis/.nvm/v0.10.36/lib
    └── (empty)
    npm WARN EBUNDLEOVERRIDE Replacing bundled cordova > npm > cmd-shim with new installed version
    npm WARN EBUNDLEOVERRIDE Replacing bundled cordova > npm > read-installed with new installed version
    npm WARN EBUNDLEOVERRIDE Replacing bundled cordova > npm > read-package-json with new installed version
    npm WARN EBUNDLEOVERRIDE Replacing bundled cordova > npm > rimraf with new installed version
    npm WARN EBUNDLEOVERRIDE Replacing bundled cordova > npm > sha with new installed version
    travis_time:end:01181523:start=1446810511157650436,finish=1446810548856025841,duration=37698375405

    The command "npm install -g cordova@5.1.1" failed and exited with 1 during .
    Your build has been stopped.

This is what I got this morning, which was successful

    /home/travis/.nvm/v0.10.36/lib
    └─┬ grunt-cli@0.1.13 
      ├─┬ findup-sync@0.1.3
      │ ├─┬ glob@3.2.11
      │ │ └─┬ minimatch@0.3.0
      │ │   ├── lru-cache@2.7.0 
      │ │   └── sigmund@1.0.1 
      │ └── lodash@2.4.2 
      └─┬ nopt@1.0.10
        └── abbrev@1.0.7 
    travis_time:end:222e4ef4:start=1446774575408200822,finish=1446774576866116856,duration=1457916034
    travis_fold:end:before_install.2
    travis_fold:start:before_install.3
    travis_time:start:104a7264
    $ npm install -g cordova@5.1.1
    npm WARN engine npm@1.3.4: wanted: {"node":">=0.6","npm":"1"} (current: {"node":"0.10.36","npm":"3.3.10"})
    /home/travis/.nvm/v0.10.36/bin/cordova -> /home/travis/.nvm/v0.10.36/lib/node_modules/cordova/bin/cordova
    /home/travis/.nvm/v0.10.36/lib
    └─┬ cordova@5.1.1 
      ├─┬ cordova-lib@5.1.1 
      │ ├── bplist-parser@0.0.6 
      │ ├── cordova-app-hello-world@3.9.0 
      │ ├─┬ cordova-js@4.0.0 
      │ │ ├─┬ browserify@10.1.3 
      │ │ │ ├── assert@1.3.0 
      │ │ │ ├─┬ browser-pack@4.0.4 
      │ │ │ │ ├─┬ combine-source-map@0.3.0 
      │ │ │ │ │ ├── convert-source-map@0.3.5 
      │ │ │ │ │ ├─┬ inline-source-map@0.3.1 
      │ │ │ │ │ │ └── source-map@0.3.0 
      │ │ │ │ │ └─┬ source-map@0.1.43 
      │ │ │ │ │   └── amdefine@1.0.0

**Comment by mpost** [comment]
We can't really pinpoint any problem with the build. Might be a problem on the travis side. We will investigate.

**Comment by aMarCruz** [comment]
My build fails too (a very simple "hello world" style App)
The detailed log of travis stop on:
`The command "npm install -g cordova@5.1.1" failed and exited with 1 during . `

**Comment by gosia-eclipsesource** [comment]
We've fixed it by limiting npm to 2.x versions. The builds are working again.

**Comment by wilsonna** [comment]
Yup, it's working, thanks!
