### ISSUE TITLE
Revise documentation type definitions

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#682]
TypeScript type definition syntax is currently being used as a general guideline for defining types.

There are still challenges to consider:
- What to do with variable types? e.g. _itemHeight_ type declaration is `number|function`. Should we introduce own types (e.g. here `ItemHeight`) in these cases?
- TypeScript has the `Function` interface. Should we rename `function` to `Function` to comply to TS's syntax?
- `margin`, `dimension`, `offset` and `timeoutID` use lower case similar to literals. Is there a TS convention for fixed values?

**Comment by tbuschto** [comment]
@cpetrov @dbuschtoens Is this a current issue?

**Comment by ralfstx** [comment]
The issues mentioned here are already resolved. Actually, the type definitions for TypeScript are now generated from the types declared in the JSON files, so they have to be TS compatible.
