### ISSUE TITLE
Add support for "flat" and "border" button style

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#683]
Mobile platforms have the notion of "flat" buttons, that are not raised by default and "border" buttons that draw an outline around the button. We should support such an appearances as well.

**Comment by 3to1null** [comment]
Will this be implemented anytime soon? Or is it already implemented (I couldn't find it)? If so this issue should be closed.

**Comment by cookieguru** [comment]
@3to1null You can replicate similar behavior with `highlightOnTouch` and a `Composite`.

**Comment by mpost** [comment]
As @cookieguru stated you can mimic the flat button behavior in full with a `TextView`.

I have updated the issue title to include the "border" syle button as well which is also very prominent on mobile platforms. It can be replicated with a Canvas atm.

**Comment by 3to1null** [comment]
@cookieguru Problem with this is that `highlightOnTouch` only generates the ripple effect on android 6.0 or higher. 

Creating a one cell `CollectionView ` will work, I think.

**Comment by cookieguru** [comment]
See also #1339

**Comment by patrykmol** [comment]
For `border` there is a property we can use to apply it. It accepts `float` as a value. As for `flat` style I don't really get it in iOS world. From what you have described, default iOS buttons are already flat as far as I understand.

**Comment by patrykmol** [comment]
As for additional styling, default buttons on iOS can have a few different styles. Here are examples.
![screenshot 2018-11-13 at 16 09 18](https://user-images.githubusercontent.com/12428999/48423816-a328bc80-e761-11e8-8383-993a354f5ca9.png)
Although the differences between last 3 types (`detailDisclosure`, `infoDark`, `infoLight`) escape me. This leaves 2 new potential styles that we could add to iOS at least.

**Comment by mpost** [comment]
Implemented as part of Tabris.js 3.

![screenshot_1544450573](https://user-images.githubusercontent.com/73655/51592347-ab367280-1eef-11e9-9f45-446656fa0a36.png)

**Comment by josiahking** [comment]
Thanks
