### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#684]
Is there a document showing future plans and general dates of when it will be available?

from my perspective, development appears to have slowed down since the 1.2 update. Is there a reason for this? I really like this platform but there are still some issues that aren't even on the milestone docs yet (Push notifications, Custom Widgets on iOS, File Writing...)

thanks!

**Comment by mpost** [comment]
Thanks for your feedback. You are right that the feature set of the latest releases has been a little smaller than usual. We are actually working on some big new addition to Tabris.js in the realm of tooling and debugging. Please stay tuned for that. :)

Also we are actively developing the iOS maps support as a third party plugin similar to Android. That will be done very soon and should act as a guide on how to add custom widgets on iOS. That will go along with more documentation for iOS plugin development.

In regards to your Push notifications question... You are referring to PushWoosh not functioning properly? https://github.com/eclipsesource/tabris-js/issues/608 We will refocus on tackling that issue.

The file writing, and canvas scenario is something we are looking into but needs to be fleshed out a little more before it can be added to tabris.js.

Hope that helps you. There are some big things coming that we are very excited about. So please stay tuned.

**Comment by bFlood** [comment]
thank you @mpost , very happy there's a lot going on in the background

Push - I'll use anything, we just started with PushWoosh. what have you tested successfully on both Android and iOS? I understand canvas/file writing maybe not being top priority but I think fully supported Push notifications are pretty important

**Comment by mpost** [comment]
@bFlood Yes. push notifications are very imporatant. We have successfully worked with PushWoosh on Android and iOS via the cordova plugin. If there are problems currently we have to look into that.

**Comment by bFlood** [comment]
PushWoosh - https://github.com/eclipsesource/tabris-js/issues/608, specifically the crash on cold starts from a push notification

can you think of any workarounds for saving a file right now? 

thanks!

**Comment by mpost** [comment]
@bFlood With the current tabris.js version the cordova file plugin provides the most flexible way.

**Comment by bFlood** [comment]
tabris.js supports writing files with the current cordova file plugin? (see https://github.com/eclipsesource/tabris-js/issues/377 )

**Comment by mpost** [comment]
yes it does. You can in fact use the cordova file plugin to write arbitrary data (eg. a string) to disc.

**Comment by jonek** [comment]
@bFlood using the cordova-plugin-file you can currently only write text files, not binary files from a Tabris.js app.
I am currently looking into writing binary files, too.
#377 is a bit misleading. Yes, Tabris.js currently does not contain ```Blob```. But the ```FileWriter.write(data)``` lets you perfectly write strings into a file.

I just verified that ```fileWriter.write('foo');``` successfully created a file on my device containing 'foo'.

**Comment by jonek** [comment]
Some good examples on how to use the cordova-plugin-file can be found in this blog post: https://www.neontribe.co.uk/cordova-file-plugin-examples/

**Comment by bFlood** [comment]
yes, I can confirm text data works as well. Blob is not defined and passing an ArrayBuffer just creates and empty file. ArrayBuffer works in standard cordova

so, I until tabris.js supports native file writing, we'll need a custom plugin to save decoded base64 data to file

**Comment by bev-on** [comment]
@mpost @jonek Any idea when WebSockets will be supported? Sockets are really important in modern apps (e.g. online gaming and messaging apps).

**Comment by irbull** [comment]
Thanks for opening this issue @bFlood. @gosia-eclipsesource and I spent some time updating our 'road map' document and made it available on *Grand Central* at [https://tabrisjs.com/grand-central](https://tabrisjs.com/grand-central). This shows our roadmap, as well as concrete tasks that the team is working on. Unfortunately this only pulls information from our public repositories, and much of the recent work is happening on the clients -- which is not reflected here. I'll find a way to to more transparent about that work too.

I'm going to close this issue because we now have a place to show and track progress with Tabris.js.

**Comment by cookieguru** [comment]
@irbull So glad to see this!
One comment though--only collaborators can tag issues, so the instruction "Please feel free to open issues labeled with `feature request`" doesn't help much

**Comment by irbull** [comment]
@cookieguru Thanks! I've updated the wording and even put a link to the *open new issue* dialog.

**Comment by gosia-eclipsesource** [comment]
@bev-on We agree about WebSocket support. it's on our extended roadmap. Hopefully in not too long a time we'll move it to near term.
