### ISSUE TITLE
iOS Build Error for Non-DEBUG Mode

### ISSUE THREAD

**Issue by wilsonna** [eclipsesource/tabris-js#685]
I'm having problems building in non-DEBUG mode for iOS again (DEBUG mode still works). I'm quite certain that my p12 and provisioning provfile is correct. Not sure when this last happened, but it's at least 2 weeks back. It was working 2 months ago. Back then, I see this in the log

	CodeSign build/device/My\ App.app
		cd /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios
		export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
		export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/travis/.rvm/gems/ruby-2.0.0-p481/bin:/Users/travis/.rvm/gems/ruby-2.0.0-p481@global/bin:/Users/travis/.rvm/rubies/ruby-2.0.0-p481/bin:/Users/travis/.rvm/bin:/Users/travis/bin:/Users/travis/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"
		
	Signing Identity:     "iPhone Distribution: Wilson Na (MBZKA7362S)"
	Provisioning Profile: "MyApp Distribution Provisioning Profile"
						  (23e80896-305c-46ac-8cec-c46b175b601d)
		/usr/bin/codesign --force --sign 87DF38D9168E8ADE65F1A712E8ABBB94661713AE --entitlements /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/My\ App.build/Release-iphoneos/SAF\ eMart.build/SAF\ eMart.app.xcent /Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/build/device/My\ App.app
	** BUILD SUCCEEDED **

But now, I see this in the log

	=== BUILD TARGET My App OF PROJECT My App WITH CONFIGURATION Release ===
	Check dependencies
	Code Sign error: No matching provisioning profile found: Your build settings specify a provisioning profile with the UUID “af3b00c2-45c0-4a7c-b60b-0785383041a3”, however, no such provisioning profile was found.
	CodeSign error: code signing is required for product type 'Application' in SDK 'iOS 8.1'
	** BUILD FAILED **

A search of the UUID “af3b00c2-45c0-4a7c-b60b-0785383041a3” shows this in the log

	Build settings from configuration file '/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/cordova/build-release.xcconfig':
		CODE_SIGN_IDENTITY = iPhone Distribution
		PROVISIONING_PROFILE = af3b00c2-45c0-4a7c-b60b-0785383041a3
	=== BUILD TARGET CordovaLib OF PROJECT CordovaLib WITH CONFIGURATION Release ===

The above is not seen in the old log, so apparently, something about travis has changed that resulted in its Provisioning Profile overriding mine. Is that deduction correct?

**Comment by patrykmol** [comment]
Has any of your certificates expired recently?

**Comment by wilsonna** [comment]
Nope. The certs expire next year. In any case, I created a new cert again and recreated everything just to be sure, but still the problem still persists.

**Comment by patrykmol** [comment]
Keys you are using are somehow wrong. Log says you are using profile with id 23e80896-305c-46ac-8cec-c46b175b601d and build chain expects af3b00c2-45c0-4a7c-b60b-0785383041a3. Mu guess is that you have changed something.

**Comment by wilsonna** [comment]
The first code block above is the log output from what was previously working, where 23e80896-305c-46ac-8cec-c46b175b601d was the previous ID of my app. But It's currently 8fe80782-cedf-4d94-84d1-657b030b6a88 since I've recreated it.

The next 2 code blocks are from the log where the build no longer works, and af3b00c2-45c0-4a7c-b60b-0785383041a3 is not my app's ID. It's the ID of specified in "/Users/travis/build/eclipsesource/tabris-js-build-template/build/platforms/ios/cordova/build-release.xcconfig". Basically, regardless of which app I'm trying to build (hence different IDs), I will get the error with this exact same ID.

**Comment by patrykmol** [comment]
Is the bundle id the same as id in provisioning profile? You said you have changed ID and if you don't have wildcard provisioning profile builds will fail.

**Comment by wilsonna** [comment]
Sorry, I meant the provisioning profile UID which was changed. The App ID is still the same. It's not a wildcard app id. The app Id matches exactly for my app and the provisioning profile.

**Comment by patrykmol** [comment]
I have tracked the issue. I will let you know when it's fixed.

**Comment by patrykmol** [comment]
Fix for this issue is available on nightly builds. If you are using stable you will have to switch to nightly.

**Comment by wilsonna** [comment]
Thanks, I've confirmed that the nightly build fixes the problem.

**Comment by patrykmol** [comment]
Good to hear. :+1:
