### ISSUE TITLE
Debug Build works but Release Build Fails (Android)

### ISSUE THREAD

**Issue by maxapps** [eclipsesource/tabris-js#689]
Finished first demo app and was thrilled with the result and speed of development. Problems came when attempting to create a release build. The debug build worked perfectly but, after turning debug off and adding an Android key, the release build fails completely with no explanation of what is wrong. I tried a second time with the same results.

Please advise about how to determine what caused the build to fail and possible solutions to the issue.

Thanks for the help.

**Comment by cookieguru** [comment]
Probably related to #685

**Comment by gosia-eclipsesource** [comment]
Please post the exit error message from the detailed log and we will have a look.

**Comment by maxapps** [comment]
I didn't know how to access the logs but have since figured it out.

The log has the following line:

The Tabris.js version used for the build (1.4.0) does not match the
version configured in the package.json of your app (1.1.0). This may
cause runtime errors!



Let me correct the json file and see if that fixes the issue before
bothering you again.


Thanks

**Comment by maxapps** [comment]
Changing the json file did not help. Here are the last several lines from
the detailed log which seem to indicate multiple aliases. I have very
little experience but did not intentionally create multiple aliases. I'm
not even certain how that would be possible. I did use the same string for
the Key Name and Key Alias fields when creating the Android Key using your
online system. Could the problem be related to that?

BUILD SUCCESSFUL
Total time: 1 mins 36.009 secs
Built the following apk(s):
    /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build/outputs/apk/android-release-unsigned.apkRunning
"create-artifacts" taskRunning "shell:sign_apk" (shell) task
Only one alias can be specified
Please type jarsigner -help for usageWarning: Command failed: Only one
alias can be specified
 Use --force to continue.Aborted due to warnings.
travis_time:end:0defbd45:start=1449010603744662723,finish=1449010706151536617,duration=102406873894The
command "grunt build deploy" exited with 6.
Done. Your build exited with 1.



Thanks again for the help.

**Comment by irbull** [comment]
Did you use spaces in your Alias name? I saw this on StackOverflow, may be
related?

http://stackoverflow.com/questions/8748089/jarsigner-only-one-alias-can-be-specified

On Tue, Dec 1, 2015 at 3:59 PM, Jeff Carver <notifications@github.com>
wrote:

> Changing the json file did not help. Here are the last several lines from
> the detailed log which seem to indicate multiple aliases. I have very
> little experience but did not intentionally create multiple aliases. I'm
> not even certain how that would be possible. I did use the same string for
> the Key Name and Key Alias fields when creating the Android Key using your
> online system. Could the problem be related to that?
>
> BUILD SUCCESSFUL
> Total time: 1 mins 36.009 secs
> Built the following apk(s):
>
> /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build/outputs/apk/android-release-unsigned.apkRunning
> "create-artifacts" taskRunning "shell:sign_apk" (shell) task
> Only one alias can be specified
> Please type jarsigner -help for usageWarning: Command failed: Only one
> alias can be specified
> Use --force to continue.Aborted due to warnings.
>
> travis_time:end:0defbd45:start=1449010603744662723,finish=1449010706151536617,duration=102406873894The
> command "grunt build deploy" exited with 6.
> Done. Your build exited with 1.
>
>
>
> Thanks again for the help.
>
> On Tue, Dec 1, 2015 at 5:35 PM, Jeff Carver <maxapps@gmail.com> wrote:
>
> > I didn't know how to access the logs but have since figured it out.
> >
> > The log has the following line:
> >
> > The Tabris.js version used for the build (1.4.0) does not match the
> version configured in the package.json of your app (1.1.0). This may cause
> runtime errors!
> >
> >
> >
> > Let me correct the json file and see if that fixes the issue before
> > bothering you again.
> >
> >
> > Thanks
> >
> > On Tue, Dec 1, 2015 at 3:51 AM, Malgorzata Mitros <
> > notifications@github.com> wrote:
> >
> >> Please post the exit error message from the detailed log and we will
> have
> >> a look.
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/eclipsesource/tabris-js/issues/689#issuecomment-160897186
> >
>
> >> .
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipsesource/tabris-js/issues/689#issuecomment-161136351>
> .
>



-- 
R. Ian Bull | EclipseSource Victoria | +1 250 477 7484
http://eclipsesource.com | http://twitter.com/eclipsesource

**Comment by maxapps** [comment]
No spaces were used in the Key Name/Alias. Upper and lower case ASCII
letters only.

**Comment by gosia-eclipsesource** [comment]
Haven't been able to reproduce the issue so far. Could you please let us know your operating system and what Java version you have installed?

**Comment by maxapps** [comment]
OS is Windows 10. JDK is 1.8.0_65, JRE is 1.8.0_66 but it looks like the
error being reported is coming from your sever???

If you were able create a working apk from my source, it would seem that
the problem almost certainly has something to do with my Android key. If
all this is correct, I will try generating a new one and see what happens.
Probably can't get to it until tomorrow, though.

**Comment by cookieguru** [comment]
Are you using the Tabris.js hosted build or the local build on your box?

**Comment by maxapps** [comment]
Hosted build. I have a Developer account, not a Pro account.

**Comment by gosia-eclipsesource** [comment]
@maxapps Thanks, I asked for the Java version in case it's something that happens during the generation of the keystore file. We may have to wait till next week when @mpost is back to investigate further. (Unless @jonek could help before then?)

**Comment by maxapps** [comment]
Understood, and thanks for the assistance.

**Comment by irbull** [comment]
@maxapps Not sure if this is the [app](https://github.com/maxapps/PtgDemo01) you are talking about, but we forked it and built it using a release key on tabrisjs.com. Can you try to remove your keys and try again? Everything appears ok with the setup.

**Comment by maxapps** [comment]
Thanks. Should be able to try tomorrow evening.

**Comment by maxapps** [comment]
It's now working. The problem seems to have been something I did wrong when creating the android keystore. The only thing I **intentionally** did different when creating the new one was to not use the same string for the Key Name and the Key Alias.

Again, thanks for all the assistance.

**Comment by cookieguru** [comment]
I just had the same issue with the build failing.  Not sure what the cause was, but when I uploaded my keystore I actually used the same name for the Key Name and Key Alias (both in the web and when generating it with Java).  I wonder if perhaps the Key Alias you type in has to match exactly what you used for the `-alias` command for keytool?
