### ISSUE TITLE
Build Download Cuts off at 80KB

### ISSUE THREAD

**Issue by wilsonna** [eclipsesource/tabris-js#690]
The build is successful, but when I tried to download the apk or ipa files, they both got cut off at 79.81KB. I tried downloading from both my laptop and mobile phone to eliminate the likelihood that it is client related.

**Comment by bFlood** [comment]
I was able to download ipa files but not apks, it starts and finished really quickly but then the downloaded file is corrupt

**Comment by bFlood** [comment]
anything on this yet? all android downloads (debug/release) get cut off and are invalid

**Comment by gosia-eclipsesource** [comment]
@wilsonna @bFlood We can confirm the issue and are working to fix it. Please stay tuned.

**Comment by irbull** [comment]
Please try again. I've changed the way we stream the files from the build output to the user. I've tested a few IPAs / APKs and they are now working for me.

**Comment by bFlood** [comment]
working again, thanks! seems to be a lot faster on the download too

**Comment by irbull** [comment]
Thanks @bFlood. Marking as closed. Please re-open if the problem persists.

**Comment by wilsonna** [comment]
Thanks!
