### ISSUE TITLE
Default cordova plugins not included in Release builds

### ISSUE THREAD

**Issue by maxapps** [eclipsesource/tabris-js#693]
It may be obvious to others but I was surprised to find that the "Default Cordova Plug-Ins" are only defaults in the **debug** version of an app. When you build a release version, they are not automatically included and must be added via &lt;plugin&gt; tags in the cordova/config.xml file.

The documentation states:
> While using the Tabris.js Developer App, your application can directly access the following pre-packaged plug-ins:

In retrospect, this does infer that they are only included in a debug build but might not be obvious to someone just starting out. Hopefully this comment will save them some time.

**Comment by mpost** [comment]
That is a valid point. We should be more clear in that regard.

**Comment by gosia-eclipsesource** [comment]
Added a note in the docs. Will be online in the next deployment.
