### ISSUE TITLE
getResourceLocation not defined in developer app

### ISSUE THREAD

**Issue by maxapps** [eclipsesource/tabris-js#694]
The developer app does not seem to include the **getResourceLocation()** which was added in version 1.3. I can see it in the source code but attempts to use the method return error messages saying it is not defined.

Try the following to see what I mean:
> console.log(tabris.app.getResourceLocation);
> // returns "undefined".

Other functions such as:
> console.log(tabris.app.dispose);
> console.log(tabris.app.installPatch);

return the expected results (i.e. the function definition).

Is there some reason this is not working?

**Comment by mpost** [comment]
Running against the dev app that is running an app hosted on a local ip works on iOS and Android.:

```js
console.log(tabris.app.getResourceLocation());
// returns "http://<ip>:<port>"
```

Make sure to include the brackets on `getResourceLocation`.

**Comment by maxapps** [comment]
This does not work for me. I just entered the exact line from your response:

console.log(tabris.app.getResourceLocation());
>
> This generates an error:

Could not load main module:

 TypeError: undefined is not a function



> at ./main.js:81:24
> at Object.define-
> Property.get (boot.js:
> 1:1401)


Line 81 is the console.log(tabris.app.getResourceLocation()); statement and
column 24 is the beginning of getResourceLocation.

I probably made things more confusing in the original post by adding the
information about calling console.log() on getResourceLocation without
invoking the function but this is a valid statement. I was attempting to
show that getResourceLocation is not defined on the app.tabris object and
it definitely is not, at least not in the version I am using
(1.4.0-20151029-1453).

I am testing on a Nexus 6 running Android 6.0, is there any chance it's a
version 6 issue? It seems doubtful since the function doesn't even exist on
the app.tabris object.

**Comment by mpost** [comment]
The script i posted above runs fine on a nexus 6. Is the app you use the one directly from the play store? Could you verify on ios?

**Comment by maxapps** [comment]
Yes, and I just uninstalled it and reinstalled from the app store. Still
doesn't work and generates the same error. I cannot verify on ios but we
must be missing something simple here.

I am about to create a single line app which has nothing but the
*console.log(tabris.app.**getResourceLocation());* line.

**Comment by maxapps** [comment]
BTW - The ScratchPad is also broken (in computer browser, not phone).
Making changes to it has no effect on what is displayed on the phone. I
tried logging out and back in but this didn't work either.

Bringing up the chrome developer console shows two errors:

Uncaught SyntaxError: missing ) after argument list     in
> tern-tabris-connect.min.js:8
>
Uncaught ReferenceError: CodeMirror is not defined   in  (index):333


The second is probably caused by the first.

**Comment by maxapps** [comment]
I may have found the problem.

While creating the single-line app, I was poking around in the various
folders. Inside the node_modules/tabris/package.json file, the version says
"1.1.0".

The project structure was based on the Getting Started Project which was
downloaded from https://tabrisjs.com/documentation/latest/getting-started

**Comment by maxapps** [comment]
OK, you can close this one. It was definitely caused by the incorrect
version of tabris. I updated the project's package.json file to require
tabris 1.4.0 or greater then did an npm update and it is now working as you
stated.

I also noticed that the Getting Started Project still indicates version
"1.1.0".

{
>   "name": "tabris-getting-started",
>   "description": "Tabris.js - Hello, World!",
>   "main": "hello.js",
>   "dependencies": {
>     "tabris": "^1.1.0"
>   }
> }


Thanks for all the help.

**Comment by mpost** [comment]
Ok great you could figure it out. :) Is the scratchpad still misbehaving for you?

**Comment by maxapps** [comment]
Not at computer at moment. Will recheck in next hour or so.

**Comment by maxapps** [comment]
It is working now (after clearing browser cache). Thanks
