### ISSUE TITLE
Cordova Text-to-Speech Plugin Works with Tabris

### ISSUE THREAD

**Issue by maxapps** [eclipsesource/tabris-js#699]
Just a quick not for the compatibility section.

The Cordova Text-to-Speech Plugin (https://github.com/vilic/cordova-plugin-tts) works perfectly with Tabris by adding this line to the cordova/config.xml:
```xml
<plugin name="cordova-plugin-tts" />
```

and using **window.TTS,speak()** instead of **window.plugins.TTS.speak()**.

Please note that this was only tested on Android 6.0 but the plugin is supposed to work on iOS.

**Comment by gosia-eclipsesource** [comment]
Thanks!
