### ISSUE TITLE
Provide a reliable way to open the developer console on iOS

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#700]
On iOS, it's sometimes very hard to open the developer console by swiping in from the right. On iOS 9, if I'm not mistaken, the gesture competes with some OS function. For some applications, it is even impossible to use this gesture, e.g. a full-size tab folder with paging enabled would always consume the swipe gesture.

We should provide some alternative method of opening the developer tray on iOS.

**Comment by mpost** [comment]
The four finger tab can be used reliably.
