### ISSUE TITLE
tabris 1.5 ETA?

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#702]
tabris 1.5 ETA? thanks!

**Comment by mpost** [comment]
Within the next week. :)

**Comment by irbull** [comment]
@bFlood Just a bit more context. Our *internal* release date was yesterday, with App store submission marked for today (we submit the developer app to the stores). That means that all development is done on a release. We then release when apple approves the app which is typically within a week.

**Comment by bFlood** [comment]
understood, thanks for the info

does Nightly on the Build service have 1.5? I think users who are building their own debug versions would appreciate not having to wait for Apple :)

**Comment by patrykmol** [comment]
@bFlood Yes. Nightly is 1.5.
