### ISSUE TITLE
tabris-maps error

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#707]
this was working in tabris1.4. 

on Android, during tabris.create("ESMap")... I'm seeing a new warning in the debug log:

``` Could not create object "tabris.Map" (reason: Could not find IOperationDelegate for null) ```

the map is just white. also, there are no Google Maps warning in the adb log about the wrong map key (which usually happens with a new debug build) so I don't think its even getting to point of creating the Google Map at all

I'm using the same config.xml for tabris-map as tabris-maps-example

haven't tried on iOS, see https://github.com/eclipsesource/tabris-js/issues/703

**Comment by mpost** [comment]
We have solved the issue on the Android side and will push an update the maps repo today.

**Comment by bFlood** [comment]
thank you!

**Comment by bFlood** [comment]
its working now on android, thanks!

just waiting on the IOS build service issue now
