### ISSUE TITLE
Cannot dynamically hide Action icons

### ISSUE THREAD

**Issue by cookieguru** [eclipsesource/tabris-js#711]
Take the following code, which is mostly based on the Bookstore example:
```js
tabris.create('Action', {
	title: 'Settings',
	image: {
		src: 'https://raw.githubusercontent.com/eclipsesource/tabris-js/master/examples/bookstore/images/action_settings.png',
		scale: 3
	}
}).on('select', function() {
	this.visible = false;
	this.opacity = 0;
	this.enabled = false;
	tabris.create('Page', {
		title: 'Settings'
	}).open();
});
```
This places a settings icon in the top right corner of the application.  When clicked, it will open an empty page with a title Settings and a back button next to the page title.  The Settings icon is still visible, and clickable.  If the user taps the settings icon from within the settings page, another Settings page will be created on the stack forcing the user to hit a back button twice (and they'll see the first settings page, which will have all the widets in the state they were in when the page was created, which may differ from how they were left on the second settings page).  Of course this can be fixed by creating the Settings page outside the `select` handler function, but the icon will still remain visible.

Given that a Settings page usually acts as a modal page, the settings (and other) Action icons should not be visible from the settings page.  Setting `visible` nor `opacity` nor `enabled` has any effect on the Action button.  However this should not _always_ be the case as actions are not used exclusively to open modal pages.

**Comment by cookieguru** [comment]
D'oh, I forgot the properties aren't "watched" and need to notify the appropriate handlers by using the `set` function.

This snippet works:
```js
tabris.create('Action', {
	title: 'Settings',
	image: {
		src: 'https://raw.githubusercontent.com/eclipsesource/tabris-js/master/examples/bookstore/images/action_settings.png',
		scale: 3
	}
}).on('select', function(action) {
	action.set('visible', false);
	tabris.create('Page', {
		title: 'Settings'
	}).open().append(
		tabris.create('TextView', {
			text: 'This is the settings page!'
		})
	).on('dispose', function() {
		action.set('visible', true);
	});
});
```
I'm on the fence about having to manage this inside the action's select function; I'd rather see a new property as part of the creation process that will take care of it for me.  Mostly I don't like it because the only good place to re-enable the icon is in the `Action`'s `Page`'s `dispose` handler (`disappear` could also work).

Will leave open to get some feedback on this idea.

**Comment by bFlood** [comment]
I think Actions should have a Page property as well and then let the tabris framework handle everything. that said, I use tabris.ui.on("change:activePage") to manage this all manually and decide which Actions should be visible, it works pretty well and allows you to build your Page structure normally

**Comment by cookieguru** [comment]
An `Action` could kick off a Cordova plugin, so I don't think they should necessarily have a `Page` associated with them.  But you also bring up a valid point in that different pages might have different `Action`s, so having an `Action` manage its own visibility would be just as complicated as having the `Page` (or some other manager) watch them.
