### ISSUE TITLE
Open URL in default browser

### ISSUE THREAD

**Issue by cookieguru** [eclipsesource/tabris-js#712]
There are times when I'd rather have a URL open in the device's native browser rather than a WebView.  How do I go about doing that?

**Comment by mpost** [comment]
You could use the [`InAppBrowser`](https://github.com/apache/cordova-plugin-inappbrowser) cordova plugin.

**Comment by cookieguru** [comment]
Thanks Moritz, this couldn't have been much easier.

For anyone keeping score at home, in `cordova/config.xml` add:
```xml
<plugin name="cordova-plugin-inappbrowser" version="1.1.1" />
```
In the app, add:
```js
cordova.InAppBrowser.open('http://tabrisjs.com/', '_system');
```

Build the app and it just works!

**Comment by mpost** [comment]
Happy to hear that it worked out. :)

**Comment by cookieguru** [comment]
@mpost Is there any reason against using this, so that loading the plugin is not necessary?

```js
tabris.registerWidget("MyWidget", {
  _type: "tabris.MyWidget",
    openUrl: function(url) {
    this._nativeCall("openUrl", {url: url});
  }
});

var myWidget = tabris.create('MyWidget');
myWidget.openUrl('http://www.tabrisjs.com/');
```

**Comment by mpost** [comment]
The above script is correct though you shouldn use `tabris` as the `_type` prefix as it should only be used by internal widgets. Instead you should use your own vendor name.

That said the above `tabris.MyWidget` will only be known to the system if you provide a corresponding native implementation for it.

**Comment by cookieguru** [comment]
I was more curious about the `openUrl` native call.  Is it off limits for any reason?

**Comment by mpost** [comment]
Using `_nativeCall` is currently the way to go if you want to send a call operation to the native side.
