### ISSUE TITLE
minor issue - highlightOnTouch should use material design ripple effect on android

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#714]
widget.highlightOnTouch should use material design highlighting (touch ripple) on Android

right now the only way to get this effect is to use a button or the cell of a CollectionView. If you place a new composite over the cell, the effect is not available

**Comment by mpost** [comment]
Agreed.

**Comment by mpost** [comment]
Implemented for the upcoming 1.6 release.

The ripple effect will work only work on devices running Android 6.0 and up since we use the new Android property [`foreground`](http://developer.android.com/reference/android/view/View.html#attr_android:foreground) to show the ripple effect.
