### ISSUE TITLE
running J2V8 on linux.

### ISSUE THREAD

**Issue by webclimber** [eclipsesource/tabris-js#719]
Hi there, has anyone been able to run on linux ? 
I tried version 3.1.1 and got: 

Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library. Reasons: 
  no j2v8_linux_x86_64 in java.library.path
  /home/geobuildci/libj2v8_linux_x86_64.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/geobuildci/libj2v8_linux_x86_64.so)

with 3.1.6 I get

inconsistent module metadata found. Descriptor: com.eclipsesource.j2v8:j2v8_linux_arm64:3.1.6 Errors: bad module name: expected='j2v8_linux_x86_64' found='j2v8_linux_arm64'

My build.gradle contains: 

    // V8 Integration
    compile "com.eclipsesource.j2v8:j2v8:${J2V8Version}"
    compile "com.eclipsesource.j2v8:j2v8_macosx_x86_64:${J2V8Version}"
    compile "com.eclipsesource.j2v8:j2v8_linux_x86_64:${J2V8Version}"

any suggestions on this will be welcomed

I am testing on

Linux ubuntu-vm 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu 14.04.3 LTS \n \l

**Comment by cookieguru** [comment]
Might look at eclipsesource/J2V8/#34 or something else in that repo

**Comment by webclimber** [comment]
apologies I just realized I added this one on the wrong place .... 
Thanks !
