### ISSUE TITLE
The animate() method does not return widget

### ISSUE THREAD

**Issue by maxapps** [eclipsesource/tabris-js#720]
In the [Tabris blog about creating animations](http://eclipsesource.com/blogs/2015/04/14/tabris-js-examples-animations/), it clearly states that the animate() method returns the widget.
> It is interesting to note that the call to animate(..) returns the widget itself, so you can easily chain a call to register a listener to animation events. Building upon the simple example above, the following snippet shows how to listen to an animation end event:
```javascript
widget.animate(
  {opacity: 0.5}, {duration: 1000}
).on("animationend", function() {
    console.log("animated ended");
});
```
This is not supported by the documentation and doesn't appear to be true in version 1.5. I get an error when attempting to use the code shown in the example and capturing the result of the animate() method returns "undefined":
```javascript
var tmp = widget.animate({opacity: 0.5}, {duration: 1000});
console.log(tmp);    // returns 'undefined'
```

**Comment by cookieguru** [comment]
Adding `return this;` to the end of the `animate` function in [Animation.js](https://github.com/eclipsesource/tabris-js/blob/master/src/tabris/Animation.js#L72-L73) fixes this.
