### ISSUE TITLE
Action title not showing up

### ISSUE THREAD

**Issue by cookieguru** [eclipsesource/tabris-js#721]
I'm using an image for an Action and the image is bundled with the app.  When the app first launches, there is a brief period while the image is being fetched/rendered where the action displays `<NO-TITLE>`:

![screenshot_2016-01-09-22-53-04](https://cloud.githubusercontent.com/assets/1888809/12220666/15346718-b72f-11e5-94bc-6ffc3476168f.png)

The action was declared with a title:
```js
tabris.create('Action', {
	title: 'Settings',
	image: {
		src: 'images/settings.png',
		scale: 3
	}
});
```

This is even more pronounced when loading an image on a remote server or when trying to load a resource that doesn't exist.

**Comment by mpost** [comment]
You are right. While loading the image the title is not applied beforehand.

**Comment by mpost** [comment]
The issue has been fixed. And will be part of the next release.
