### ISSUE TITLE
Image source containing ".." path segments not resolved in Cordova builds

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#722]
Example:

**Not working:**

``` javascript
tabris.create("ImageView", {
  image: {src: "../images/logo.png"}
}
```

**Working:**

``` javascript
tabris.create("ImageView", {
  image: {src: "images/logo.png"}
}
```

Resolving image resources with the ".." syntax works in the developer app. This issue affects both iOS and Android clients.

**Comment by tbuschto** [comment]
I don't quite get the description, but I think it is completely valid to now allow resource paths to point to file outside the `www` directory. Maybe we should simple prohibit these paths.

**Comment by ralfstx** [comment]
@cpetrov I agree with @tbuschto that `../` segments should not be allowed in resource paths. We should enforce that in JS. Please reopen if we're missing something.

See also #1210.
