### ISSUE TITLE
Allow to set round clipping to corners on a widget

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#728]
It can be desirable to set round corners on a view to mimic a "card" appearance or to create a circle outline.

* On iOS the property `cornerRadius` could be used
* On Android the property `setOutlineProvider` (Android 5+) could be used

**Comment by bFlood** [comment]
+1

**Comment by jkrause** [comment]
Also see https://github.com/eclipsesource/tabris-js/issues/411

**Comment by mpost** [comment]
The inset mentioned in #411 is not so easily doable so we will focus on the rounded corners for now.

**Comment by bFlood** [comment]
this issue is closed, is this feature available yet?

**Comment by gosia-eclipsesource** [comment]
Yes, it's ready for 1.7 and available in nightly.

**Comment by bFlood** [comment]
just tried this with 1.7 and I'm not getting anything on iOS. what is the property syntax and allowed values?

**Comment by ralfstx** [comment]
@bFlood See [this snippet](https://github.com/eclipsesource/tabris-js/blob/v1.7.0/snippets/cornerradius/cornerradius.js). It works for me, even on iOS 8. Did you update the tabris module?

**Comment by bFlood** [comment]
doh, forgot to update tabris module. works perfectly now, thanks!

**Comment by narayansikarwar** [comment]
why cornerRadius property is only working android 5.0+ and not working on less than 5.0.

**Comment by cookieguru** [comment]
@narayansikarwar See Moritz's comment [here](http://eclipsesource.com/blogs/2016/04/07/creating-the-floating-action-button-in-tabris-js/#comment-151246).

**Comment by mpost** [comment]
@narayansikarwar the ability to created rounded corners (or outlines for that matter) have only been introduced in Android 5 and can not easily be backported. Especially in conjunction with the `elevation` feature.
