### ISSUE TITLE
Provide a way to repeat animations indefinitely

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#729]
Currently animations can be repeated a fixed number of times. To repeat animation indefinitely, one would have to start the animation again on animation end. Animations API should provide a convenient way to run animations for infinite number of times.

**Comment by mpost** [comment]
On Android the repeat count can be set to [INFINITE](http://developer.android.com/reference/android/view/animation/Animation.html#INFINITE) (-1) to repeat indefinitely.

**Comment by mpost** [comment]
Also see https://github.com/eclipsesource/tabris-js/issues/973

**Comment by tbuschto** [comment]
Closed in favor of https://github.com/eclipsesource/tabris-js/issues/973
