### ISSUE TITLE
Introduce indeterminate circular loading indicator

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#730]
Circular loading indicators are commonly displayed while long lasting operations are being processed to inform the user that the current process is progressing.

An example for a common use case for showing spinning wheels is during fetching list items data from a remote resource.

Currently spinning wheels using advanced animations can only be designed using a canvas (Android version) and more simpler variants using alternating images (iOS version), which may be complex and time consuming. Introducing a ready to use indicator utilizing native widgets can minimize the effort of displaying an indicator with native look and feel.

**Android:**
![spinningwheel](https://cloud.githubusercontent.com/assets/2341769/12444852/27790d2c-bf61-11e5-89fc-e14c3ed59b51.gif)
(source: https://thomas.vanhoutte.be/miniblog/android-lollipop-animated-loading-gif/)

**iOS:**
![uiactivityindicator_intro](https://cloud.githubusercontent.com/assets/2341769/12444891/647cbaa2-bf61-11e5-8fc8-b49a0fc3a1e0.png)
(source: https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/UIKitUICatalog/UIActivityIndicatorView.html)

Images may not be accurate and are only included for demonstration purposes.

Also see eclipsesource/tabris-js#458.

**Comment by mpost** [comment]
Great feature description. Sadly it is a duplicate of https://github.com/eclipsesource/tabris-js/issues/647 ;)

None the less... the Android and iOS client already support such a feature from tabris-remote but we are missing tabris.js API for it.

**Comment by cpetrov** [comment]
I must have missed it. :(

**Comment by mpost** [comment]
Here is the code in tabris-remote: https://github.com/eclipsesource/tabris/blob/master/com.eclipsesource.tabris/src/com/eclipsesource/tabris/widgets/enhancement/ProgressBarDecorator.java#L38
