### ISSUE TITLE
CollectionView - update item? 

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#732]
CollectionView has Insert, Remove but needs an Update method for individual items (or am I missing it?)

altering the item in the list and then setting the items property again seems like overkill

**Comment by cookieguru** [comment]
Right now that's the only way to do it.

**Comment by mpost** [comment]
Agreed with this assumption there should be an `update` method as well.

**Comment by mpost** [comment]
The collection view has [`refresh(index)`](https://tabrisjs.com/documentation/latest/api/CollectionView#refreshindex). Doesn't that suffice?

**Comment by bFlood** [comment]
that will update the UI and is very helpful during a ColectionView "select" event where the item is passed and is editable. however, what if I had a large list of items and I needed to update 5-10 of them, the only way to do this is reset the entire list (AFAIK)

**Comment by mpost** [comment]
@bFlood so you would like to have something like refresh(index, itemCount) ?

**Comment by bFlood** [comment]
refresh(index) doesn't change the values of the item right, it just forces an update of the UI for that cell?

I need to change the value of individual items, then I would call refresh(index) for each one. right now the only way to change the values is to completely reset the items property (myCollectionView.set("items", my_large_list) which on larger screens (iPad etc) sometimes causes a noticeable blink/flash of all the items (I'm assuming because all of the cells/controls are destroyed and recreated)

on another note, it would also be nice to have an option to turn on/off item animations for updates. for instance you can remove and item and then reinsert it with changes values to accomplish what I'm looking for but you get a very noticeable animation on iOS as the item is removed

**Comment by mpost** [comment]
@bFlood You are right about your statement: _I need to change the value of individual items, then I would call refresh(index) for each one_. Doesn't that work for you? At least for one item?

**Comment by bFlood** [comment]
ahhh, my bad. I was referencing a copy of the array used in the CollectionView so any changes I made there were not reflected in CV when refresh(index) was called. soooo, you are correct and it already does what I need. thanks!

**Comment by mpost** [comment]
Good to hear :)
