### ISSUE TITLE
Option to edit / smart default for highlightOnTouch / collectionview

### ISSUE THREAD

**Issue by shaialontabris** [eclipsesource/tabris-js#734]
![752e4183-cc2c-4643-b87f-1ac3dda6cda0](https://cloud.githubusercontent.com/assets/16774265/12479277/6f3f4a84-c03a-11e5-8abf-9bd6b469b955.png)

**Comment by shaialontabris** [comment]
Discussed to @patrykmol - It's 3 days of work to implement on iOS

**Comment by shaialontabris** [comment]
Summary:
An iOS only implementation that would change the default from blue to grey is 2 days.

An iOS - Android - Js implementation that makes the color configurable is about 3 days (3 iOS, 3 Android, 2 js)

**Comment by mpost** [comment]
The `CollectionView` is a special case in that sense, that each item has touch feedback enabled by default. It is not the `highlightOnTouch` property but a "native" feedback.

We would need to find a custom property to colorize this feedback on a `CollectionView`. An alternative could be to remove the default touch feedback from an item and only allow to set and configure it via the `highlightOnTouch` property.

I would prefer the later as there are also some cases where you don't want touch feedback (eg. section headers) where you have to create an item spanning the entire view just to shield the touch feedback.

**Comment by patrykmol** [comment]
Maybe we should implement it as a property on cell, especially with regard to issue https://github.com/eclipsesource/tabris-js/issues/796

**Comment by mpost** [comment]
Closing this as the proposed solution to remove select event is covered in https://github.com/eclipsesource/tabris-js/issues/1581.
