### ISSUE TITLE
installPatch issues

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#739]
I'm having an issue installing patches. Everything seems to work just fine, the zip is downloaded the callback is executed with no error and the patch.json file and the have been unzipped on the device (for iOS - appname\Application Support\patches\version_number\some_uuid\patch_id )

when the app restarts (either manually or via tabris.app.reload) it uses the older files, not the newer ones from the patch. my app looks like a local cordova build, so the zip file has a patch.json file in the root and then a "www" folder with a single test file to overwrite. could this be the problem? I did notice the note about local cordova folder structure in the docs but I thought this would be correct

on another note, I can't help but notice the patch files are unzipped and stored in plain text on the device. is this by design? in fact, how are an app's files stored on the device during a release deployment? (in  my quick look around, I could not find them, making me feel it was relatively safe from casual tampering)

**Comment by mpost** [comment]
Does this problem apply to iOS only or also on Android?

**Comment by bFlood** [comment]
yes, it was happening on both. although I did not check if the files were added to the android file system like on iOS

**Comment by cookieguru** [comment]
>In fact, how are an app's files stored on the device during a release deployment?

The user will have the APK on their system which contains all your code as-is.  I can't speak to iOS, but on Android they can open the APK and edit a file, but when they try to re-install the APK the signature won't match so they'd need to re-sign it.  There's a [tool](https://code.google.com/p/apk-resigner/) for that, but as you mentioned it's not easy for the casual tamperer.

**Comment by bFlood** [comment]
wow, assumed it was a little more locked down. you're right, the files are right there in the apk.  I guess in hindsight, it would be difficult for tabris to encrypt/obfuscate them but it sure would be a nice option

anyone tried building a single obfuscated/minified and deploying that?

**Comment by cookieguru** [comment]
A packed version should work just as well, but all the code is still there.  For example if you're working with an external API where you have to store your credentials in the app (and those credentials are the same you use to log in--I'm looking at you, UPS API) anyone will still be able to see them.  Of course this is poor API design, but not something the developer controls most of the time.  Which means in order to protect these credentials you'll probably have to resort to proxying.

Sorry to derail this... back to patching.

**Comment by bFlood** [comment]
Can anyone get patching to work? Or is it somehow related to my Cordova folder setup
Thanks

**Comment by mpost** [comment]
We are looking into it for the upcoming 1.6 release.

**Comment by mpost** [comment]
One general question... Over the weekend the nighlies contained a bug that stopped local resource loading from working on Android. That has been fixed on Monday. Does patching still not work on Android with the latest nightly?

**Comment by bFlood** [comment]
I will check but my issue affected both iOS and android

**Comment by mpost** [comment]
I have created a little example that makes use of the patch logic on Android. It works as expected. I would guess that it has something to do with your paths.

I have created a local build with a file `www/app.js` and i have loaded a patch.zip file which just contains one file `app.js` at the root level. It has overwritten the `app.js` that was previously in `www`.

**Comment by bFlood** [comment]
thanks @mpost I was able to get this mostly working for iOS and Android. my patch zip had a www folder containing the files, instead they needed to go in the root folder

one minor item, image files were updated in iOS but I got an error on Android that the file could not be found. its seems like the other patch files were applied though

**Comment by mpost** [comment]
Just tested image replacement as well. It works as expected for me. The patch overwrote the image with the same name:

![patch](https://cloud.githubusercontent.com/assets/73655/12641330/4f584052-c5af-11e5-9594-74c01d4d4b23.png)

**Comment by bFlood** [comment]
Was the image in the root or in a child directory?

**Comment by mpost** [comment]
in the root directory

**Comment by bFlood** [comment]
can you try from a child directory, that is where most apps will store the image asset correct? it works from iOS but I get the error on Android. I'll try from the root as well and confirm that is working

thanks

**Comment by mpost** [comment]
Yes works as advertised:

App:

![image](https://cloud.githubusercontent.com/assets/73655/12645548/1569c1d8-c5cb-11e5-90e1-0f4238a74cb7.png)

**Comment by mpost** [comment]
I am closing this issue for now. Feel free to reopen if you think it is malfunctioning.
