### ISSUE TITLE
Webview up/down dragging (ios)

### ISSUE THREAD

**Issue by sergio-doman** [eclipsesource/tabris-js#741]
Is there any way how to disable vertical webview dragging? Any opened page may be dragged up/down even if it fits perfect and there are no scrollbars visible. Also, it shows annoying grey background, got it on iOS devices. I need to show internal html page with static element for offline app.

**Comment by cookieguru** [comment]
I have not tried it, but there is the `DisallowOverscroll` [preference](https://cordova.apache.org/docs/en/4.0.0/config_ref/#link-multi-platform-preferences) you could add to your `cordova/config.xml`.  It would apply globally to the app and not just to WebViews.

This would probably need to be implemented on the native side using `webView.scrollView.bounces = NO;` (iOS) and `webView.setOverScrollMode(View.OVER_SCROLL_NEVER);` (Android).  I'm not seeing a similar property on Windows Phone, but [vendor CSS](http://stackoverflow.com/a/28975594/1810770) can fill in the gap.

**Comment by mpost** [comment]
As @cookieguru pointed the property can be set but it is not directly applied on each `WebView` instance. We would probably have to make that configurable.

@patrykmol any thoughts on that issue?

**Comment by michaeleparkour** [comment]
@sergio-doman have you tried to set body css in webView to {position:fixed, top: 0; left:0; width: 100%; height: 100%;} this is known hack to prevent safari overscrolling. May be helpful.

**Comment by sergio-doman** [comment]
@michaeleparkour I've tried your suggestion and this trick works great for desktop safari, but not for mobile webview. Here is screenshot from iPad - http://oi68.tinypic.com/2hcole0.jpg

**Comment by sergio-doman** [comment]
Also, there is one more problem - I can't block manual zooming in/out of webview

**Comment by cookieguru** [comment]
```html
<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
```

**Comment by mpost** [comment]
On iOS it is a flag that can be toggled. We should be able to provide Tabris.js API for that.

**Comment by sergio-doman** [comment]
@cookieguru Thank you, this solved all my problems!

**Comment by cookieguru** [comment]
> On iOS it is a flag that can be toggled. We should be able to provide Tabris.js API for that.

See #255
