### ISSUE TITLE
Support customizing the activity indicator color on Android

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#746]
Note: The iOS progress bar widget does not support color customization.

**Comment by mpost** [comment]
We could set the "tint" color on Android.

**Comment by mpost** [comment]
The tint color is currently derived from the accent color of the android theme used in the app. to customize this you can provide your own theme: http://eclipsesource.com/blogs/2015/07/03/tabris-js-1-1-sneak-peak-custom-themes-on-android/

**Comment by mpost** [comment]
The colors can now be customized with http://docs.tabris.com/latest/api/ActivityIndicator.html#tintcolor.
