### ISSUE TITLE
Support pop-up menus

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#747]
Pop-up menus may be modal or modeless. 

See images below for examples.

![Google Drive Modal Menu](https://cloud.githubusercontent.com/assets/2341769/9681375/dd1635cc-52fd-11e5-9830-83fa520b7022.png)

![Google Play Store Modeless Menu](https://cloud.githubusercontent.com/assets/2341769/9681362/cd3f0098-52fd-11e5-9706-493598457262.png)

![App Store Modal Menu](https://cloud.githubusercontent.com/assets/2341769/9681429/399362ac-52fe-11e5-86cf-ca872ffef49c.PNG)

See also: #619

**Comment by cookieguru** [comment]
Similar functionality is possible with the [Cordova Actionsheet plugin](https://github.com/EddyVerbruggen/cordova-plugin-actionsheet) which is compatible with Tabris.js (and had demos added to the developer app in fe8d9253efa970d8bcb9a63213ab066fac372731).

**Comment by mpost** [comment]
We have added support for `Popover` in Tabris.js 2.5 which supports this usecase.
