### ISSUE TITLE
Support fullscreen modal views

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#749]
Fullscreen modal views can help present complex tasks which don't belong to the main app UI and require exclusive user interaction.

See:
- modal view on iOS: https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/Alerts.html#//apple_ref/doc/uid/TP40006556-CH14-SW3
  ![modal_view_mail_compose_2x](https://cloud.githubusercontent.com/assets/2341769/12609589/f8ae7eaa-c4e2-11e5-9ba9-6694a5fd4e45.png)
- full-screen dialog on Android:
  https://www.google.com/design/spec/components/dialogs.html#dialogs-behavior

![modal-view-android](https://cloud.githubusercontent.com/assets/2341769/12609594/050542b0-c4e3-11e5-938e-ddca02a2e4ec.png)

See also: #619

**Comment by bFlood** [comment]
+1

**Comment by sergioradovcic** [comment]
+1

**Comment by bFlood** [comment]
this would be a great addition for tabris 2.0

**Comment by cpetrov** [comment]
A full screen modal view could be a view presented as a container:

* on phones: covering the screen, which slides in from the bottom
* on tablets:
  * iOS: [popover](https://developer.apple.com/ios/human-interface-guidelines/views/popovers/)
  * Android: an empty [dialog](https://material.io/guidelines/components/dialogs.html)

The use cases from the screenshots could be implemented by appending a NavigationView to this container. Related: #1622

**Comment by mpost** [comment]
Implemented via the new `Popover` in tabris 2.5.
