### ISSUE TITLE
Support intrinsic CollectionView item height

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#753]
Sometimes it is useful to let CollectionView item height grow at least as high as the item's content.

![http://i.stack.imgur.com/0MDSX.png](http://i.stack.imgur.com/0MDSX.png)
_Picture source:_ http://stackoverflow.com/questions/34326698/create-a-list-containing-a-dynamic-number-of-views-with-recyclerview

**Comment by mpost** [comment]
+1

**Comment by calebeaires** [comment]
+1

**Comment by bFlood** [comment]
+1

**Comment by cookieguru** [comment]
This would be even better than #173 since there's no precalculation necessary

**Comment by mpost** [comment]
Will that would be really great... There are some technical difficulties on iOS where it is not cheap to relayout each cell based on its content. We will be looking into a solution.
