### ISSUE TITLE
Provide Templates with ES6/TypeScript support for different IDEs

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#760]
A CLI could provide:
- templates / project initialization
- server start script / custom http-server

A custom http-server could also provide ES6/TypeScript transpiler and/or faster commonjs module loading. There is a draft for the latter in gerrit.

**Comment by cookieguru** [comment]
Related: #471

**Comment by tbuschto** [comment]
Instead of a CLI that is globally installed we will offer templates that include npm scripts. They can fulfill the same function, but require no additional setup and can be project specific. However, the topic of a globally installed CLI may return in the future.

**Comment by tbuschto** [comment]
@ralfstx Should we close this issue?

**Comment by ralfstx** [comment]
Yes!
