### ISSUE TITLE
Cant find https module.

### ISSUE THREAD

**Issue by frh3ddy** [eclipsesource/tabris-js#763]
Hi. Im trying to use Syncano library and it uses the https module but the tabris app can't find the https module.

**Comment by cookieguru** [comment]
`https` is a code node module but is not implemented in [tabris-js-node](https://github.com/eclipsesource/tabris-js-node).  It would need to be implemented there.
Alternatively, you could package [the module](https://github.com/nodejs/node/blob/master/lib/https.js) separately and load it, for example, [using a tarball](https://docs.npmjs.com/cli/install).

**Comment by ralfstx** [comment]
> you could package the module separately and load it

That would not work, as this module depends on other node modules such as `http` that aren't yet available in Tabris.js.

For HTTP, your options in Tabris.js are currently either using `XmlHttpRequest` or the npm module `whatwg-fetch`.

Alternatively, you could try to find a Cordova module for Syncano and use this.

**Comment by ralfstx** [comment]
The builtin node modules `http` and `https` are not supported by Tabris.js. Even a partial implementation would be a considerable amont of work.
