### ISSUE TITLE
TabFolder selection property does not change the active tab

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#764]
Programmatically setting the selected tab changes only the content, not the selected tab in iOS.

As an example, given a tab folder with two tabs, the first tab is currently active. After calling `tabFolder.set("selection", tab2)`, the tab folder displays the content of tab2, however, the tab bar still highlights tab1.

**Comment by jkrause** [comment]
@patrykmol Patch has been submitted, please review

**Comment by Homoola** [comment]
not fixed in 1.8,
 disappointed how can i contact the technical support ?

**Comment by mpost** [comment]
The issue has been fixed as advertised. Could you provide a snippet to reproduce the problem?

**Comment by Homoola** [comment]
yah it has been fixed  :( sorry
