### ISSUE TITLE
Disable predictions in developer console

### ISSUE THREAD

**Issue by cookieguru** [eclipsesource/tabris-js#767]
My keyboard thinks it's being really helpful when it adds a space after every `.` but when typing JavaScript this is less than ideal.  It'd be great if predictions could be turned off.

![screenshot_2016-02-04-22-52-19](https://cloud.githubusercontent.com/assets/1888809/12839920/b3a61fd2-cb92-11e5-8d7b-c4c3fcd54e97.png)

**Comment by mpost** [comment]
Makes sense. We will look into that.

**Comment by mpost** [comment]
Improved in the upcoming 1.6 release
