### ISSUE TITLE
App loading icon is sometimes Tabris.js logo on iOS

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#768]
Icon shown while installing the app (grayed out icon on launcher with circular loading indicator on top of it) is Tabris.js logo when installing the app for the first time (i.e. not updating it), although no Tabris.js logo is bundled in the root directory of the .ipa payload package. Is it known where this asset comes from?

Tested with debug apps.

**Comment by bFlood** [comment]
is there an update on this? this is very obvious during app installation, I don't think it will block us from the app store but it doesn't look great as a first experience with an app

**Comment by patrykmol** [comment]
Can you check if you have overwritten all of the following files?

```
icon-40.png
icon-40@2x.png
icon-50.png
icon-50@2x.png
icon-60.png
icon-60@2x.png
icon-60@3x.png
icon-72.png
icon-72@2x.png
icon-76.png
icon-76@2x.png
icon-small.png
icon-small@2x.png
icon-small@3x.png
icon.png
icon@2x.png
```

These are all of the Tabris icons in the template. I'm pretty sure that you are missing one of those.

**Comment by cpetrov** [comment]
They were overwritten for our tests.

**Comment by cpetrov** [comment]
The icon may have been cached for an old state of the app when the icon wasn't overwritten yet, see:
https://www.google.de/search?q=/var/mobile/Library/Caches/com.apple.IconsCache&ie=UTF-8&oe=UTF-8&hl=de-de&client=safari

@bFlood can you try installing the app (please verify that all icons @patrykmol listed are overwritten) on an iOS device you have never installed the app on?

**Comment by bFlood** [comment]
icon-small@3x.png was not be overwritten, if that helps. I'm running a build now to test. also, are the file names case sensitive?

I don't have another fresh iOS device to test the possible caching issue on, all of ours have had the app installed at least once (doesn't uninstalling take care of that anyway?)

thanks!

**Comment by bFlood** [comment]
fyi -I added icon-small@3x.png but the loading icon is still the tabris one on intiall install. all other image files are overwritten

**Comment by cookieguru** [comment]
Does your `config.xml` use the same case as the name of the file?  And if you unzip the built `.ipa` do you see your own 87px icon named `icon-small@3x.png`?

Try removing the app and reinstalling it.  Might require a version bump and a new TestFlight deployment.

**Comment by cpetrov** [comment]
We have identified the issue. The Tabris.js logo shown when downloading the app is referenced in the .ipa download metadata provided by http://tabrisjs.com. The logo is only shown for .ipa-s installed using the .ipa download link on the website. Therefore this problem won't affect apps released in the App Store.

We are working on a solution to show the app icon instead of the Tabris.js logo when installing the app from https://tabrisjs.com.

**Comment by patrykmol** [comment]
This has been fixed already.
