### ISSUE TITLE
Input example output text is cut off on some devices

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#769]
Restructure the example or wrap the items in a scroll view to prevent text from being cut off.

![f2b9054e-f413-4430-8f24-d0793015f826](https://cloud.githubusercontent.com/assets/2341769/12886616/21323520-ce6f-11e5-9b03-8d0f13518281.png)

**Comment by mpost** [comment]
The content is now wrapped in a `ScrollView` which makes the content readable.
