### ISSUE TITLE
Tabris.js developer app closes in offline (IOS)

### ISSUE THREAD

**Issue by sergio-doman** [eclipsesource/tabris-js#772]
When I tried several times to launch Tabris developer app w/o internet connection, it closes automatically in 2 seconds, even when I had stable wifi connection to local server. Thus, it's not possible to develop & debug my app in offline mode.

**Comment by mpost** [comment]
@sergio-doman We have also seen this problem and it is already fixed in the upcoming 1.6 release. For now you could also run a custom build against nightly to get a fully functional version.
