### ISSUE TITLE
Support key event cancelation

### ISSUE THREAD

**Issue by cookieguru** [eclipsesource/tabris-js#776]
Take this snippet to filter a `TextInput`'s text to numbers only:

``` js
tabris.create("TextInput", {
  keyboard: "number"
}).on("input", function(widget, text) {
  widget.set("text", text.replace(/[^\d]/g, ""));
});
```

After the `input` callback fires, the cursor is placed at the end of the `TextInput` (iOS) or at the beginning (Android)--see #537.  Assuming this behavior is aligned so that all platforms move the cusor to the end, it still provides an undesirable UX.

For example, if a user were to enter 1256, place the cusror between 2 and 5, and type 34, the input should show 123456 but instead would show 123564.  In a browser, the behavior is identical but this can be overcome by recording the `<input>`'s `selectionStart` on keydown and providing that value to [`HTMLInputElement.setSelectionRange()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange) after the setting the `<input>`'s value on keyup.

I think this would be easiest to simply have a `before:input` event (as suggested in #529) which could cancel the event if the input doesn't match the validation criteria.

**Comment by ralfstx** [comment]
Even if the cursor position would be restored after changing the text, that would not result in the expected behavior. In your example, if you place the cursor at `12|34` and then enter `a`, you'd first get `12a|34`, and after replacing the text and preserving the cursor position it would be `123|4`.

Only a cancelable event that is fired before the character is entered would allow for this approach. I seem to remember that this was not supported by the native platforms (@mpost: is that right?).

**Comment by ralfstx** [comment]
It seems that we can use `InputFilter` on Android. @patrykmol @tbuschto Would iOS and Windows support cancellable key events?

**Comment by patrykmol** [comment]
@ralfstx It's doable on iOS.

**Comment by cookieguru** [comment]
@ralfstx It's still possible without a cancellable event--you just have to read the position before transforming the value.  See [this example](http://codepen.io/anon/pen/JGQqZx) (which uses [jQuery Carat](https://bitbucket.org/accursoft/caret/wiki/Home)).  If I enter `12|34` and type "a" the carat stays between 2 and 3.  Of course whether or not this approach is possible natively on the three platforms is a different story.

**Comment by tbuschto** [comment]
Should be no problem.

On 22 February 2016 at 22:40, Tim Bond <notifications@github.com> wrote:

> @ralfstx <https://github.com/ralfstx> It's still possible without a
> cancellable event--you just have to read the position before transforming
> the value. See this example <http://codepen.io/anon/pen/JGQqZx> (which
> uses jQuery Carat <https://bitbucket.org/accursoft/caret/wiki/Home>). If
> I enter 12|34 and type "a" the carat stays between 2 and 3. Of course
> whether or not this approach is possible natively on the three platforms is
> a different story.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipsesource/tabris-js/issues/776#issuecomment-187398507>
> .
>



-- 
Innoopract Informationssysteme GmbH
tbuschto@eclipsesource.com
Tel: +49 721 - 66 47 33 - 0
Fax: +49 721 - 66 47 33 29

**Comment by cookieguru** [comment]
This is now possible with 4a2e12018e9c261127ee8579e2406a3dff58079c
