### ISSUE TITLE
CanvasContext does not support createLinearGradient method

### ISSUE THREAD

**Issue by shaialontabris** [eclipsesource/tabris-js#779]
**See example:**
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createLinearGradient

**This code will throw an error:**
var page = tabris.create("Page", {
  title: "Canvas",
  topLevel: true
});

tabris.create("Canvas", {
  layoutData: {left: 10, top: 10, right: 10, bottom: 10}
}).on("resize", function(canvas, bounds) {
  var ctx = canvas.getContext("2d", bounds.width, bounds.height);

  var grd=ctx.createLinearGradient(0,0,170,0);
  grd.addColorStop(0,"black");
  grd.addColorStop(1,"white");

  ctx.fillStyle=grd;
  ctx.fillRect(20,20,150,100);

}).appendTo(page);

page.open();

*_According to @mpost , the native clients support the functionality and it just needs to be added to the js client.
*_

**Comment by ralfstx** [comment]
We'll have to implement [CanvasGradient](https://developer.mozilla.org/en-US/docs/Web/API/CanvasGradient) and extend the optimized data structure in `CanvasContext` to support arrays. Who said the JS side was simple :innocent:? Will have a look...

**Comment by ralfstx** [comment]
Closing as a dup of #133.
