### ISSUE TITLE
Android target SDK

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#780]
I built an android version 2 weeks ago using the "nightly" and then published in the Google Play store as a beta version. I built another one today and when I go to public in the Play Store beta again, I get this error:

"It is forbidden to downgrade devices which previously used M permissions (target SDK 23 and above) to APKs which use old style permissions (target SDK 22 and below). This occurs in the change from version 31117 (target SDK 23) to version 30206 (target SDK 22)."

It also supports fewer android device types

so, my question is:
1) what SDK does the build service target now? and what will it be in the near future (presumably when tabris 1.6 comes out)?
2) is there a way to control this in the config.xml file or via a build script?

thanks

**Comment by mpost** [comment]
With the [update to Cordova 6](https://cordova.apache.org/news/2016/01/28/tools-release.html) we have also adopted Cordova Android 5.1 which is now compatible with Android 6 Marshmallow. As a result apps build with the Tabris.js build service now apply the latest targetSdkLevel of 23 (Android 6).

When doing a local cordova build it should also be possible to control the target level but i don't fully recall how to configure it.

**Comment by mpost** [comment]
Closing this for now. Please reopen if you feel that we need to take action.
