### ISSUE TITLE
fix apps with Apache Cordova vulnerabilities

### ISSUE THREAD

**Issue by molasaheb** [eclipsesource/tabris-js#783]
Hi,
I've recently published my app to google play store and I used the online built function to build my app.
but I've got a warning in google play store that says: "you are using Apache Cordova that has some security vulnerabilities"
more info : https://support.google.com/faqs/answer/6325474
 
It is mentioned that after may 2016 google will block any app using Apache Cordova version less than 4.1.1

Please upgrade the apache cordova on online build as soon as possible.

Thank you

**Comment by mpost** [comment]
Please build your app with the just released Tabris.js 1.6. It is based on the latest Cordova 6 version.
