### ISSUE TITLE
Examples show a blank screen

### ISSUE THREAD

**Issue by rherrmann** [eclipsesource/tabris-js#784]
I downloaded the Tabris.js developer app from the Play Store on a FairPhone 2 running a stock Android 5.1.

Trying to run the Hello World or any other example shows a blank screen only. Same for the Scratchpad app. I can't see any console output or error indicator either.

 Any hints how to solve this?

**Comment by mpost** [comment]
Do you see any output in the console or even better in the android adb logcat?

**Comment by rherrmann** [comment]
As I said, _ I can't see any console output_. I've installed _aLogcat_ on the device, force-stopped Tabris, and repeated the steps but apparently nothing is logged.

**Comment by mpost** [comment]
That is very curious. Would you able to come into the office so that we can have a closer look?

**Comment by cookieguru** [comment]
I was noticing this too yesterday, both Android and iOS with the 1.6 app.  Wiping out the scratch pad and adding new text fixed the issue.

**Comment by rherrmann** [comment]
Thanks for this hint. However the trick doesn't work for me.

> I was noticing this too yesterday, both Android and iOS with the 1.6 app. Wiping out the scratch pad and adding new text fixed the issue.

**Comment by mpost** [comment]
@rherrmann Are you still seeing the issue with the latest 1.10 client?

**Comment by rherrmann** [comment]
@mpost With the latest version from the Play Store the examples work. The device is running plain Android 5.1.

**Comment by mpost** [comment]
@rherrmann That is good to hear. Closing this for now. Feel free to create a new issue if device specific problems arise.
