### ISSUE TITLE
Support Widget.siblings()

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#786]
Sometimes it is useful to select the siblings of a given widget, e.g. when implementing custom radio button behavior.

**Comment by ralfstx** [comment]
That should be a just shortcut for `parent().children()`, right?

**Comment by cookieguru** [comment]
Except that the current element would be filtered out, [like jQuery](https://github.com/jquery/jquery/blob/master/src/traversing/var/siblings.js).
