### ISSUE TITLE
Tab + italic problem (android)

### ISSUE THREAD

**Issue by sergio-doman** [eclipsesource/tabris-js#787]
Sometimes, I need to add italic tags for several words inside TextView. But tab symbol ignored each time   I tried to add tags into text with enabled markup on android platform.

Code:

```
  var page = tabris.create("Page", {
    title: "Tab problem with italic",
    topLevel: true
  });

  var text1 = tabris.create("TextView", {
    layoutData: {left: 10, top: 10, right: 10},
    markupEnabled: true,
    text: "\tThe quick brown fox jumps over the lazy dog"
  }).appendTo(page);

  var text2 = tabris.create("TextView", {
    layoutData: {left: 10, top: 50, right: 10},
    markupEnabled: true,
    text: "\t<i>The quick brown fox jumps over the lazy dog</i>"
  }).appendTo(page);

  page.open();
```

Screenshot:
![12746500_990438001004109_1888932112_n](https://cloud.githubusercontent.com/assets/14274214/13204011/7a8c2b4a-d8cd-11e5-8236-8ed7c5345929.jpg)

**Comment by mpost** [comment]
When Android interprets tags as html instructions it does not interpret the `\t` character as it has no meaning in html. So this html code:

```html
<p>\t <i>hello</i></p>
```

will print \t _hello_

So i would argue that the behavior is correct. Unfortunately the ios client still interpret the `\t` as a tab character and indents the text which brings the clients out of sync.

**Comment by ralfstx** [comment]
How about translating `\t` to `&emsp;` (=`"\u2003"`)?

**Comment by sergio-doman** [comment]
@ralfstx Unfortunately, does not helped
@mpost In fact, your example works great - 
 ` text: "<p>\t<i>The <b>quick brown fox</b> jumps over the lazy dog</i></p>"`

![_img_1894](https://cloud.githubusercontent.com/assets/14274214/13230671/f4e03f80-d9ae-11e5-9174-403a38720074.jpg)

**Comment by sergio-doman** [comment]
Final solution I used:
`text = text.replace("\t", "&#160;&#160;&#160;&#160;");`
This works fine both for iOS and Android

**Comment by mpost** [comment]
Wrapping the text in `<p>` shouldn't work on Android. But than again there is no concrete definition of what i means to enable html tags.

**Comment by mpost** [comment]
We could wrap every text that contains these control characters into a `<p>` on Android so that it is in line with the iOS client.

**Comment by mpost** [comment]
Closing this as resolves. the markup string `<i>hello</i>\t world` prints as `hello\t world` on both platforms.
