### ISSUE TITLE
Cloud builds in debug mode or production not functioning

### ISSUE THREAD

**Issue by shaialon** [eclipsesource/tabris-js#788]
An app that works perfectly locally, is successfully built in the tabris.js service, but then fails to function properly (like in the dev env). My assumption is that something is wrong with fetching the dependencies.
Attached are the errors (not very understandable).
Built from:
https://github.com/shaialon/tabrisjs-rss-reader-example
App **56c483b2a2d3b0e46aca2efe** on user: **shaialontabris**

![screenshot_2016-02-22-19-38-14](https://cloud.githubusercontent.com/assets/3126207/13227276/8cc9b2e2-d99e-11e5-9321-c71b4023e8a2.png)
![img_0579](https://cloud.githubusercontent.com/assets/3126207/13227277/8ccc7018-d99e-11e5-82d4-80f7ac436922.jpg)

**Comment by irbull** [comment]
How do you build it locally?

**Comment by shaialon** [comment]
did not build locally just worked with an http-server and the developer app.

Just to keep the info - I moved the repo to:
https://github.com/eclipsesource/tabris-js-rss-example
and the issue was still going on.
The issue went away after I:
1. Added a .gitignore
2. Changed the <widget  id=" ... " > ib cordova config.xml

But obviously this should not have happened.

**Comment by mpost** [comment]
Closing as "resolved".
