### ISSUE TITLE
iOS collection view sometimes does not fire the .on('select') event

### ISSUE THREAD

**Issue by shaialon** [eclipsesource/tabris-js#798]
Load the app from here:
[rss repo in the **ios-selection-bug** branch](https://github.com/eclipsesource/tabris-js-rss-example/tree/ios-selection-bug)

Scroll up and down rapidly. Go into the products (watches) and back.
At some point you can't open the products any more. This only happens on iOS.
If you cannot reproduce, try reloading the app and scrolling again...

**Comment by patrykmol** [comment]
I was unable to pinpoint the exact problem causing this but I think it might be related to issue https://github.com/eclipsesource/tabris-js/issues/796 and fixing it might also help with this issue.

**Comment by patrykmol** [comment]
Non reproducible as of latest nightly/2.0.
