### ISSUE TITLE
device.platform inconsistent with cordova for Windows

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#801]
For Android and iOS, the platform names returned by `device.platform` are consistent with those returned by the [Cordova Device Plugin](https://github.com/apache/cordova-plugin-device).

We currently use "UWP" for windows client, but in Cordova it's "Windows".

**Comment by tbuschto** [comment]
I have to admit that if we imitate cordova API we should return the same values. However, that is not "Windows" (with upper case). Here's the relevant code of the device plugin for windows:

```
        var userAgent = window.clientInformation.userAgent;
        // this will report "windows" in windows8.1 and windows phone 8.1 apps
        // and "windows8" in windows 8.0 apps similar to cordova.js
        // See https://github.com/apache/cordova-js/blob/master/src/windows/platform.js#L25
        var devicePlatform = userAgent.indexOf("MSAppHost/1.0") == -1 ? "windows" : "windows8";
```

So we would have to return "windows" (lower case).

However, with the platform property prefixes I feel that we could be shorter and more precise. If we use "windows" as a prefix we may get to  cases like `widget.set({windows_toolbarTheme: "dark"});` which is pretty long. "win" would be shorter, but "uwp" is nicely precise: It describes the enviroment of windows store apps in the version we are using that runs across different windows 10 variants (desktop, mobile, xbox, holo lense.)

**Comment by tbuschto** [comment]
Okay, so we agreed on "windows" for device.platform and "win" as the prefix for the properties. I will close this issue once both issues are fixed.
