### ISSUE TITLE
Android Canvas error

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#802]
```java
03-15 11:05:16.689: D/Tabris(30683): WARNING Could not call method "draw" (reason: Attempt to invoke interface method 'void com.eclipsesource.tabris.android.internal.toolkit.view.gc.IGcOperation.execute(com.eclipsesource.tabris.android.internal.toolkit.view.GraphicalContext, com.eclipsesource.tabris.android.internal.toolkit.util.PrimitiveList)' on a null object reference)
```

fwiw, the same code works on iOS. will try to get repro code together but in general, its using three.js CanvasRenderer to just make some simple shapes on the tabris canvas

**Comment by mpost** [comment]
Sounds like a `draw`call is made that is not supported on Android. Most likely on iOS it is not supported either but the exception is swallowed. It would be interesting to know what call that is exactly.

Could you provide a snippet?

**Comment by bFlood** [comment]
it looks like setTransform() is causing the issue on android, works on iOS

**Comment by bFlood** [comment]
fyi - just adding a call to setTransform in any canvas example causes the error

**Comment by mpost** [comment]
@bFlood The transform is currently not supported on either platform. We will be more silent about ignoring the error.

**Comment by mpost** [comment]
We have improved the error message on Android to make it clearer what operation has not been supported.
