### ISSUE TITLE
Button misplaced on iOS

### ISSUE THREAD

**Issue by rherrmann** [eclipsesource/tabris-js#805]
A button should be attached to the right side of an input field like this:

``` Javascript
var clearActualPointsButton = tabris.create( "Button", {
  image: "src/clear.png",
  layoutData : {
    baseline: actualPointsInput,
    left: [ actualPointsInput, 20 ],
  }
} ).appendTo( page );
```

But the result looks like this:
![img_0007](https://cloud.githubusercontent.com/assets/607182/13955723/147c0f06-f046-11e5-8b82-8ab497a728fe.PNG)

The full source code is in `src/App.js` in this repository: https://github.com/rherrmann/class-tools
The same code looks OK on Android.

**Comment by cpetrov** [comment]
Could not reproduce with Tabris.js 2.0.0-rc2. Please reopen if you still have issues with the `baseline` property.

Used this updated snippet:

```js
const {Button, TextInput, TextView, ui} = require('tabris');

let label = new TextView({
  text: 'label',
  top: '10%', left: '10%'
}).appendTo(ui.contentView);

let input = new TextInput({
  left: [label, 10], width: 100,
  text: 'input',
  baseline: label
}).appendTo(ui.contentView);

new Button({
  text: 'button',
  baseline: input,
  left: [input, 20],
}).appendTo(ui.contentView);
``` 
![untitled](https://user-images.githubusercontent.com/2341769/27144468-46ee28ea-5132-11e7-8e60-5b944587540c.png)
