### ISSUE TITLE
Allow to add extra controls above keyboard

### ISSUE THREAD

**Issue by rherrmann** [eclipsesource/tabris-js#806]
Sometimes it would be useful to be able to extend the keyboard with context-specific actions. For example a _Clear_ button to reset the contents of the input field.

See [here](http://nnish.com/2013/12/02/adding-custom-buttons-to-ios-keyboard-in-c-xamarin/) for an example screen shot.

iOS seems to provide this with the [Input Accessory View](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIResponder_Class/index.html#//apple_ref/occ/instp/UIResponder/inputAccessoryViewController), for other platforms I don't know.

**Comment by ralfstx** [comment]
Meanwhile the `contentView` is resized when the keyboard opens. Hence, if you place a view right at the bottom of the contextView, it will appear on top of the keyboard.
