### ISSUE TITLE
Provide a tabris-angular npm module

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#811]
We should provide an npm module that integrates Angular2 with Tabris.js. This npm module would contain the custom renderer for Tabris and expose the Angular APIs together with a bootstrap method for Tabris.

I'd suggest to call it `tabris-angular`.

**Comment by tbuschto** [comment]
I wonder if we should close this as we are no longer perusing this strategy.

**Comment by mpost** [comment]
Closing as "not in scope".
