### ISSUE TITLE
Provide events appear and disappear on Tab

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#815]
The events `appear` and `disappear` are available on `Page` and can be used to initialize contents or to hook and unhook listeners.

Provide the same events also on `Tab` to facilitate tab-based navigation.

**Comment by bFlood** [comment]
until then, TabFolder "change:selection" works pretty well for this of scenario

**Comment by ralfstx** [comment]
right, only the initial tab doesn't trigger a change event.

**Comment by cpetrov** [comment]
IMO another use case of an "appear" event would be when a page containing a TabFolder appears. Then one would probably expect the active tab of the TabFolder to fire an "appear" event. Analogically for "disappear".

**Comment by cpetrov** [comment]
"appear" and "disappear" events on Tab will be available in the next Tabris.js release.

**Comment by dennisbappert** [comment]
I just updated to the latest version (2.4.0 - Android 8) and the events are not working:

```typescript
new Tab({
      title: "events",
    }).appendTo(this.tabFolder)
      .on("appear", (e) => console.error(`${e.target.title} appeared`));
```

**Comment by cookieguru** [comment]
@dennisbappert Can you provide a _complete_ snippet that reproduces the lack of event?  I just tried the [`TabFolder` snippet](https://github.com/eclipsesource/tabris-js/blob/master/snippets/tabfolder.js) on Android 8.0 with 2.4.0 and both events fired.
