### ISSUE TITLE
How can I create a half-Pixel Line? 

### ISSUE THREAD

**Issue by frh3ddy** [eclipsesource/tabris-js#816]
I want to create a thin divider, is it Possible to create a Half Pixel Line?

**Comment by cookieguru** [comment]
A pixel is not always a pixel.  You could create a `Composite` and set its height to `1px`.  Note the height is specified in [device independent pixels](https://en.wikipedia.org/wiki/Device_independent_pixel).  If 1 pixel is still too strong, you can make it subtler by specifying the color as `rgba()`.

**Comment by frh3ddy** [comment]
Thanks for your quick response @cookieguru, I try the approach that you suggested, but it did not give me the effect that I was looking for. instead I did something like this:

I used a composite with a height of 1, and then append a TexView with a background color.
 I set the bottom to .5, so it takes half the composite's height and it worked, 

I don't know if its a good practice to use a composite inside another composite, or use a textview. 

```javascript 
var dividerContainer = tabris.create("Composite", {
  layoutData: {top: 0, left: 0, right: 0},
  height: 1
}).appendTo(page);

var Divider = tabris.create("TextView", {
  background: "#dddfe6",
  layoutData: {top: 0, bottom: .5, left: 0, right: 0},
}).appendTo(dividerContainer);

I wanted a border similar to the toolbar. 
```

**Comment by mpost** [comment]
@frh3ddy You are able to use fractions for the layout parameters. So you could set `height` to `0.5` or to [`1 / device.scaleFactor`](https://tabrisjs.com/documentation/latest/api/device#scalefactor) to make it exactly one physical pixel high.

**Comment by frh3ddy** [comment]
I tried setting the height to 0.5 but it doesn't work. I tried before and it didn't work that is why I decided to ask.
It only works inside a collectionView Cell, but I also need it outside a collectionView. but for some reason it doesn't work. so I came up with the previous solution.

Am I doing something wrong?
```javascript 
var dividerTest = tabris.create("TextView", {
  background: "red",
  layoutData: {top: 10, left: 0, right: 0},
  height: 1 / window.devicePixelRatio
}).appendTo(page);
```

**Comment by mpost** [comment]
@frh3ddy i have just tried your snippet... it works as expected:

![image](https://cloud.githubusercontent.com/assets/73655/14107047/d1c03532-f5b5-11e5-8e70-dd46b585b9a8.png)

**Comment by frh3ddy** [comment]
did you test it on iOS or Android. I'm Using iOS 9.3,
Another question, when I set a type on a TextInput to be "multiline", the widget doesn't show at all. 
Tomorrow I will test it on an Android device and see what happens.

**Comment by patrykmol** [comment]
Half a pixel value will only work on retina device.

**Comment by frh3ddy** [comment]
Yes @patrykmol, I'm using an iPhone 5, but I also tested on an iPhone 6+,

**Comment by patrykmol** [comment]
@frh3ddy Try setting height/bottom constraint on dividerContainer. It has intrinsic size of 0 and therefore it's height is also set to 0 by auto layout. After this I can see .5 space at the bottom of screen.

**Comment by mpost** [comment]
@frh3ddy We have identified the an issue on iOS when setting the height to a fraction value and are working on a fix. Please stay tuned.

**Comment by frh3ddy** [comment]
Thanks.

**Comment by mpost** [comment]
@frh3ddy We have fixed the issue on iOS. Please give the latest nightly build a try.
