### ISSUE TITLE
Adding layout information to a tab widget causes a crash on Android

### ISSUE THREAD

**Issue by dbuschtoens** [eclipsesource/tabris-js#818]
When adding any property affecting layout to a tab widget, either in the constructor or using the set method, the application immediatly crashes. The properties left, right, top, bottom, width, height, centerX, centerY and layoutData display that behaviour.
On iOS setting these properties simply has no effect.

**Comment by mpost** [comment]
I think you are talking about the composite inside a tab rather than the tabfolder itself right? That is a known and unfortunate behavior.

**Comment by mpost** [comment]
Fixed at some point. Please reopen if still affected.
