### ISSUE TITLE
Server build with variables

### ISSUE THREAD

**Issue by michaeleparkour** [eclipsesource/tabris-js#819]
Trying to install https://github.com/Telerik-Verified-Plugins/Mapbox plugin. 
Used hook to set ACCESS_TOKEN variable similar to [tabris-maps-example](https://github.com/eclipsesource/tabris-maps-example/blob/master/config.xml) . Log shows ACCESS_TOKEN properly defined, but still have:
Error: Variable(s) missing (use: --variable ACCESS_TOKEN=value)
Anyone have advice?

**Comment by irbull** [comment]
Did you define a value on your build settings page?

**Comment by michaeleparkour** [comment]
@irbull sure, I see $export ACCESS_TOKEN=[secure] in log and console.log(process.env.ACCESS_TOKEN) shows the right value

**Comment by irbull** [comment]
Looking at your project (and comparing it to the map project), I wonder if the selector `.findall("plugin/[@name='https://github.com/Telerik-Verified-Plugins/Mapbox']")[0]` is having problems with the slashes. The tabris map example doesn't use a full URL but rather a dot-separated name.

**Comment by michaeleparkour** [comment]
It doesn't matter - as far I understand it just find by name in config, just need to be equal to plugin name in config.xml

**Comment by michaeleparkour** [comment]
Nevermind just used exec("cordova plugin add " + plugin_string) in hook. So we may close this one.
