### ISSUE TITLE
Support showing icon and label for empty TextInputs with type 'search'

### ISSUE THREAD

**Issue by luciandinu** [eclipsesource/tabris-js#820]
There is a bug on iOS if we set the TextInput to type:search.
- the clear button/icon is not working properly
- there is no search icon in the field

Examples of a search field:
http://photos.appleinsider.com/gallery/14323-9790-150919-Text-l.jpg
http://photos.appleinsider.com/gallery/14323-9791-150919-Text-2-l.jpg

**Comment by cpetrov** [comment]
The clear button works with the current Tabris.js version.

However, showing a centred message with a search icon when the text is empty is currently not possible.
