### ISSUE TITLE
statusBarTheme - transparent background

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#821]
statusBarTheme - transparent background, is this possible?

**Comment by bFlood** [comment]
what I want is the image in this issue: https://github.com/eclipsesource/tabris-js/issues/171

however, when I set displayMode:"fullscreen" the entire status bar disappears

**Comment by patrykmol** [comment]
It's impossible at the moment.

**Comment by bFlood** [comment]
@patrykmol can you think of any workarounds for this, I don't mind using a plugin and working with the root UIView somehow

thanks, the solid statusbar is bugging me for an otherwise good looking map app :)

**Comment by patrykmol** [comment]
No, we would have to implement this as a feature. There's no way for you to change this. I will present issue on next planning meeting.

**Comment by mpost** [comment]
Colorizing the statusbar will be included in Tabris.js 2.0.

**Comment by ralfstx** [comment]
The `background` property on `tabris.ui.statusBar` supports colors with an alphachannel such as `#00000033`.
