### ISSUE TITLE
Disposing of ImageViews too soon after loading causes a crash on Android

### ISSUE THREAD

**Issue by dbuschtoens** [eclipsesource/tabris-js#824]
The amount of time you have to wait before disposing correlates with image file size. A file size of 600kb caused problems when disposing less then 200ms after creation, a 5mb file increased the neccessary delay to over 1000ms.
I couldn't reproduce the problem on iOS.

**Comment by mpost** [comment]
Thanks for the input we will have a look.

**Comment by mpost** [comment]
The issue has been fixed on Android. It was a regression from the 1.7 release so the error never made it into a stable build.
