### ISSUE TITLE
Build service fails with tabris v1.5: Loading "Gruntfile.js" tasks...ERROR

### ISSUE THREAD

**Issue by sjini** [eclipsesource/tabris-js#825]
Hello,

My project build started to give this error today without any changes of code on my side (Full log in attachment):

Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Unexpected token ILLEGAL

I'm compiling with tabris v1.5.0.
Could you advise what can be an issue?

Thanks,
Sergi
[last_build_failing.txt](https://github.com/eclipsesource/tabris-js/files/222655/last_build_failing.txt)

**Comment by ralfstx** [comment]
There seems to be a current problem that affects version 1.5 and lower.

Could you try to build against a newer Tabris.js version? There shouldn't be any breaking changes.

**Comment by sjini** [comment]
Thanks ralfstx for the reply,

I have tried same with v1.6.0 and 1.7.0 and build fails, but now with different errors. Perhaps there is a incompatibility issue? Should I modify my any configs?

Full log attached. Last pieces of build log below:

FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':processReleaseResources'.
com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/local/android-sdk/build-tools/22.0.1/aapt'' finished with non-zero exit value 1
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: Error code 1 for command: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/gradlew with args: cdvBuildRelease,-b,/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true
Use --force to continue.
Aborted due to warnings.
travis_time:end:049a2fdc:start=1460960012131920462,finish=1460960092144837336,duration=80012916874
The command "grunt build deploy" exited with 6.
Done. Your build exited with 1.

[v1.7.0.txt](https://github.com/eclipsesource/tabris-js/files/223154/v1.7.0.txt)

**Comment by jonek** [comment]
Hi @sjini. I created a pull request to fix your build. See: https://github.com/sjini/DriverApp/pull/1
It seems your app icon was in the wrong place as well as the corresponding entry in the config.xml.
Could you please let us know if the build is working for you again?

**Comment by ralfstx** [comment]
@sjini Tabris 1.6 and higher are built with Cordova 6, which seem to expect some image in a different location, as @jonek pointed out. Moreover, you should ensure that your plugins are compatible with Cordova 6. We'll look into the build issue with 1.5, but nevertheless, it's probably a good idea to upgrade.

**Comment by cookieguru** [comment]
Also, regardless of Cordova version, you don't need to listen for
`deviceready`.

**Comment by sjini** [comment]
Many thanks @jonek and @ralfstx, that solved my problem! Build is ok now (v1.7.0). 
As for Cordova 6 compatibility, so far app is working as before.

@cookieguru thanks for hint, will try it.
