### ISSUE TITLE
The "navigate" event on WebView is not fired on anchor navigation

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#828]
Currently it is not possible to intercept a navigation via an anchor on the same page of a WebView. The navigate callback is fired but the value of `event.preventDefault` is ignored.

**Comment by ralfstx** [comment]
That's expected. `preventDefault` can only prevent loading a new page. An anchor navigation is triggered by JavaScript using the [browser history API](https://developer.mozilla.org/en-US/docs/Web/API/Window/history). This cannot be prevented.

The behavior is the same on iOS: the `navigate` event is fired on anchor navigation, and `event.preventDefault` is ignored.

**Comment by irbull** [comment]
Furthermore, on Android the navigation to the new anchor has already
happened by the time the event is fired. If this was desired, it would be
pretty hard to implement.

**Comment by mpost** [comment]
Closing this as "invalid".
