### ISSUE TITLE
Provide a SecureStorage

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#833]
Provide an additional storage API to store data in a trusted environment on the native client. On iOS this would be the iOS KeyChain. The API should be the same as [localStorage](https://developer.mozilla.org/en/docs/Web/API/Window/localStorage).

[This cordova plugin](https://github.com/Crypho/cordova-plugin-secure-storage) may be considered as an alternative.

**Comment by patrykmol** [comment]
This is implemented on iOS for 1.9.

**Comment by ralfstx** [comment]
There is a global object `secureStore` available on iOS. It's still not documented and considered internal.

**Comment by ralfstx** [comment]
We agreed to declare `secureStore` public API. Documentation has been added. Fixed with b0bc79d.
