### ISSUE TITLE
Don't get an iOS release built with debug mode=off

### ISSUE THREAD

**Issue by andreasmihm** [eclipsesource/tabris-js#837]
Hi,

we don't get an release build running for iOS (with debug=off).
With debug=on it works, The error message simply says:
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) were found.

I use an apple dev cert of type iOS development and the provisioning profile I use is also of type iOS development with two registered devices assigned,

What do I need to do to be able to build an iOS release? with debug=off

**Comment by cookieguru** [comment]
Try a production certificate.  See: https://github.com/eclipsesource/tabris-js/issues/581#issuecomment-134127135

**Comment by patrykmol** [comment]
You need a production certificate for release builds.
