### ISSUE TITLE
Missing Beta Entitlement for iOS builds

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#839]
how would I set this value for iOS builds? I think (not sure) it's done via the Entitlements.plist but maybe there's some cordova workflow to set it

thanks!

**Comment by patrykmol** [comment]
Try generating new provisioning profile. This error usually is generated with old provisioning profile. Apple changed structure of it at some point and it results with this error.

**Comment by bFlood** [comment]
I will try but its a pretty recent provisioning profile.

**Comment by mpost** [comment]
Closing as "resolved". @bFlood Plese reopen if you have anymore issues.
