### ISSUE TITLE
Support setting of fonts on canvas

### ISSUE THREAD

**Issue by jkrause** [eclipsesource/tabris-js#84]
Setting of fonts is currently ignored on canvas.

**Comment by trevorwat** [comment]
Hi, is this still an open issue... any idea when it will be fixed please?
Thanks

**Comment by mpost** [comment]
@trevorwat We will combine this with general support for setting third party fonts as described in: https://github.com/eclipsesource/tabris-js/issues/73

**Comment by anthonyvespoli** [comment]
been over 3 years.... still waiting on font support?

**Comment by cpetrov** [comment]
The upcoming Tabris.js release (2.3.0) supports custom fonts, which can also be used in the `Canvas` widget.
