### ISSUE TITLE
Map crashes app

### ISSUE THREAD

**Issue by iteearmah** [eclipsesource/tabris-js#840]
Below is my rep.
I followed the tutorial [https://github.com/eclipsesource/tabris-maps-example](url)
[https://github.com/iteearmah/lokate](url)

**Comment by mpost** [comment]
What do you mean by "crashes"? Could you provide more details about the platform and versions you are on?

**Comment by iteearmah** [comment]
its andriod, tabris verion is nightly build.

**Comment by iteearmah** [comment]
Want to know if I'm not doing something right....Can anyone try the map to see the results

**Comment by mpost** [comment]
I have created a local build and added the maps plugin:

`cordova plugin add https://github.com/eclipsesource/tabris-maps --variable API_KEY_FOR_ANDROID="<my-key>"`

The was shown as expected. Could you provide some information about your setup or even better a stacktrace of the crash?

**Comment by iteearmah** [comment]
Just did a release build of the [https://github.com/eclipsesource/tabris-maps-example](url) repo
I got the following error

````
Starting build
Preparing build environment
Using build template revision 0c1e7ba4b565a9b7d523a4bf5c19ca5c601765a3
Build environment created 57417d436508b0e45b609762
Cloning app from https://github.com/iteearmah/tabris-maps-example.git
Using app revision 3f8d68ec0c5a8aaeb8512050c77ffe6c5b6a9f1f
Processing App Directory
Applying config.xml
WARNING: The Tabris.js version used for the build (1.8.0) does not match the version configured in the package.json of your app (^1.5.x). This may cause runtime errors!
WARNING: A release build must disable the developer console. Change the preference "EnableDeveloperConsole" to "false" in your config.xml.
Writing Android keystore
Encrypting Android Passwords
These things will be built:
  App Id: com.eclipsesource.tabris.maps.example
  Tabris.js Version: 1.8.0
  Debug Mode: false
  Platform: ANDROID
  Plugins:
    https://github.com/eclipsesource/tabris-maps.git
Creating build job 11530d26cc2116b449ddddff7e5f6f85bae2362d
Scheduling job (57417d436508b0e45b609762). This may take a few minutes...
ERROR: Build failed. Please download the detailed log.
````

**Comment by cookieguru** [comment]
This isn't an app crash but is a build failure.
```plain
WARNING: The Tabris.js version used for the build (1.8.0) does not match the version configured in the package.json of your app (^1.5.x). This may cause runtime errors!
```
Update your `package.json` to set your `tabris` dependency to `^1.8.0`
```plain
WARNING: A release build must disable the developer console. Change the preference "EnableDeveloperConsole" to "false" in your config.xml.
```
I don't know if this will cause the build to fail but it's a good warning to heed--try fixing this as well.


If you continue to see this:
```
ERROR: Build failed. Please download the detailed log.
```
Please post the entire detailed log which can be obtained by clicking the "Detailed log" button immediately below this line of text.

**Comment by iteearmah** [comment]
````
Total time: 1 mins 29.563 secs
Built the following apk(s): 
	/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build/outputs/apk/android-release-unsigned.apk
Running "create-artifacts" task
Running "shell:sign_apk" (shell) task
jarsigner: Certificate chain not found for: mystore.  mystore must reference a valid KeyStore key entry containing a private key and corresponding public key certificate chain.
Warning: Command failed: /bin/sh -c jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -tsa https://timestamp.geotrust.com/tsa -keystore signing/android.keystore -storepass $TABRIS_ANDROID_STORE_PASSWORD -keypass $TABRIS_ANDROID_KEY_PASSWORD -signedjar build/platforms/android/build/outputs/apk/com.eclipsesource.tabris.maps.example-unaligned.apk build/platforms/android/build/outputs/apk/android-release-unsigned.apk $TABRIS_ANDROID_ALIAS
 Use --force to continue.
Aborted due to warnings.
travis_time:end:17826d70:start=1463909853711003349,finish=1463909953058978154,duration=99347974805

The command "grunt build deploy" exited with 6.
Done. Your build exited with 1.
````

**Comment by cookieguru** [comment]
Did you [upload a valid keystore](https://tabrisjs.com/iteearmah/keys)?  See:
http://docs.build.phonegap.com/en_US/signing_signing-android.md.html#Android%20Signing

**Comment by iteearmah** [comment]
Hi did now; I was able to build but closes and say " Unfortunately,
TabisMapExample  has stopped.

**Comment by mpost** [comment]
@iteearmah do you have access to the android crash stacktrace?

**Comment by iteearmah** [comment]
Kindly help me with how to get that.

On Wed, May 25, 2016 at 12:19 PM, Moritz Post <notifications@github.com>
wrote:

> @iteearmah <https://github.com/iteearmah> do you have access to the
> android crash stacktrace?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipsesource/tabris-js/issues/840#issuecomment-221556881>
>



-- 
Samuel Armah
Tel: 233248291829
Facebook <http://facebook.com/iteearmah> | Linkedin
<http://www.linkedin.com/profile/view?id=289834392> | Twitter
<https://twitter.com/iteearmah>

**Comment by mpost** [comment]
with the android sdk installed you can use the logcat tool or with android studio installed you can use the Android Monitor view.

**Comment by cookieguru** [comment]
http://stackoverflow.com/a/29200956

Also I believe apps like [Logcat](https://play.google.com/store/search?q=logcat&c=apps&docType=1) give you the same info without having to set up the Android SDK

**Comment by iteearmah** [comment]
Can I output [(https://github.com/mapsplugin/cordova-plugin-googlemaps)] in a Composite similar to DOM div?

**Comment by iteearmah** [comment]
Example

````
document.addEventListener("deviceready", function() {
  var mapDiv = document.getElementById("map_canvas");

  const GOOGLE = new plugin.google.maps.LatLng(37.422476,-122.08425);
  var map = plugin.google.maps.Map.getMap(mapDiv, {
    'camera': {
      'latLng': GOOGLE,
      'zoom': 17
    }
  });

  map.addEventListener(plugin.google.maps.event.MAP_READY, function() {

    map.addMarker({
      'position': GOOGLE,
      'title': "Hello GoogleMap for Cordova!"
    }, function(marker) {

      marker.showInfoWindow();

    });

  });
});

````

**Comment by iteearmah** [comment]
I can't seem to get the tabris map working on my Jelly Bean 4.1.2

**Comment by cookieguru** [comment]
> Can I output [cordova-plugin-googlemaps](https://github.com/mapsplugin/cordova-plugin-googlemaps) in a Composite similar to DOM div?

No, that plugin depends on the DOM and in [the docs](https://tabrisjs.com/documentation/latest/cordova#other-cordova-plugins):
> Tabris.js uses a native UI and no HTML5. As a result all Plug-Ins that manipulate the DOM will not work.

---

> I can't seem to get the tabris map working on my Jelly Bean 4.1.2

What error messages are you seeing?

**Comment by iteearmah** [comment]
can someone fork and build [https://github.com/eclipsesource/tabris-maps-example](url)

**Comment by iteearmah** [comment]
Do we need  Google Play Service to Use Google maps in Apps

**Comment by jonek** [comment]
Hi @iteearmah. I just verified, that tabris-maps-example builds fine with our build service at https://tabrisjs.com The app produced by that build is working as expected.
Please be sure to use a valid Google Maps API key in your build.
You have to associate the API key with either a production or debug key you use when building your app.
When you use a debug key, it has to be a key created by your own and registered with https://tabrisjs.com so the build services does not create a new debug key for each build under the hood (default behavior if you do not specify a key explicitly). 
Of course you can use tabris-maps-example as a starting point to make your own experiments.
Please let me know if this helps.

**Comment by iteearmah** [comment]
Can I use https://github.com/mapbox/mapbox-sdk-js in tabris

**Comment by iteearmah** [comment]
This is my apk http://s000.tinyupload.com/?file_id=02210187360703963462 
It says Unfortunately, TabrisMapsExample has stopped.

**Comment by iteearmah** [comment]
Hi Guys... I know I have been on this issue for a while now.
If anybody can give me a step by step guide to building and making it work, I will really I appreciate it.
Also it will help others too.
Thanks

**Comment by mpost** [comment]
@iteearmah What is your current problem state?

**Comment by iteearmah** [comment]
Same as stated above. U can download and install my apk link above

**Comment by mpost** [comment]
@iteearmah You mean the build problem you mentioned here? **https://github.com/eclipsesource/tabris-js/issues/840#issuecomment-220823214**

**Comment by iteearmah** [comment]
Yes please

**Comment by iteearmah** [comment]
Just tried the maps on an android 5.1 it opens the app. It shows the google app container. and the three buttons.
I'm thinking it add to do with my previous and android version Jelly Bean 4.1.2

**Comment by mpost** [comment]
@iteearmah Are you able to provide a crash log entry? Use `logcat` from the android sdk.

**Comment by iteearmah** [comment]
Unfortunately, I flashed my android device and replaced the 5.1

**Comment by mpost** [comment]
@iteearmah If you don't see a map than it is probably related to the API key not beieng properly inserted. Make sure to use a build hook to insert the api key: https://github.com/eclipsesource/tabris-maps-example/blob/master/hooks/api_key_hook.js

**Comment by mpost** [comment]
With the release of tabris-maps 2.0 this issue became invalid. https://github.com/eclipsesource/tabris-plugin-maps

Closing for now.
