### ISSUE TITLE
barcodescanner example not working anymore in tabrisjs developer app since 1.8. update

### ISSUE THREAD

**Issue by andreasmihm** [eclipsesource/tabris-js#841]
The barcodescanner example is not working anymore in tabrisjs developer app since 1.8. update

**Comment by andreasmihm** [comment]
gives typeError  cordova.plugins.barcodeScanner undefined

**Comment by mpost** [comment]
We are aware of this shortcoming and are working on a solution.

**Comment by sergio-doman** [comment]
This plugin is missing in the list of installed. So I created my own app with this plugin and when tried to compile it, I got error - 
```
:processReleaseManifest/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/AndroidManifest.xml:55:5-74 Error:
	uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [com.eclipsesource.tabris:tabris-android-launcher-js-utils:1.0.0] /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build/intermediates/exploded-aar/com.eclipsesource.tabris/tabris-android-launcher-js-utils/1.0.0/AndroidManifest.xml
```
Later I found this issue - https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/233

**Comment by cookieguru** [comment]
4.1.0 works with Tabris 1.8 but 5.0.0 does not.

**Comment by nmaas87** [comment]
4.1.0 is the last version with Android 2.3.3 and less support. After 4.1.0 (i.e. 5.0), Android 4.0+ is mandatory because of this file ( https://github.com/phonegap/phonegap-plugin-barcodescanner/blob/master/src/android/barcodescanner.gradle ) and the needed support for the aar, I think.

**Comment by mpost** [comment]
We have improved our cordova integration which will bring the `phonegap-plugin-barcodescanner` to work. Please see https://github.com/eclipsesource/tabris-js/issues/963#issuecomment-246394777
