### ISSUE TITLE
Download Links for Cordova Platforms Broken

### ISSUE THREAD

**Issue by aspidites** [eclipsesource/tabris-js#842]
Now that local builds is included in free developer accounts, I was anxious to try local builds as a means of speeding up the feedback loop while developing. Unfortunately, None of the links that I've tried work, all resulting in a 404:

- https://tabrisjs.com/api/v1/downloads/1.8.0/android
- https://tabrisjs.com/api/v1/downloads/1.7.0/android
- https://tabrisjs.com/api/v1/downloads/1.6.0/android
- https://tabrisjs.com/api/v1/downloads/0.9.3/android

As you can see, I've updated my profile to qualify for the Developer plan:
![2016-05-18-161743_940x75_scrot](https://cloud.githubusercontent.com/assets/93686/15373520/18b50ce4-1d14-11e6-9ba1-d469e7b151fb.png)

Do the links need to be updated? Is there more I need to do to gain access to these platforms so I can start building locally? Did I miss something in the announcement about when these downloads would be available?

**Comment by mpost** [comment]
Hi. You have to be logged in to tabrisjs.com when clicking those links.

**Comment by cookieguru** [comment]
@mpost The links fail for me as well, even when signed in to tabrisjs.com

The server's response has a Content-Type header of `application/octet-stream;charset=UTF-8` but in reality it returns HTML with the generic tabrisjs.com 404 page including links to sign in.

**Comment by aspidites** [comment]
Indeed. I was already logged into tabrisjs.com when I tried the links (which is how I was able to take the screen shot of my account status)

**Comment by gosia-eclipsesource** [comment]
Thanks for reporting, we are looking into the issue.

**Comment by shaialontabris** [comment]
Hi @aspidites ,
Sorry for the inconvenience. We will deploy a fix soon. Till then, you can download the binaries from here:
[tabris-android-1.8.0.zip](https://github.com/eclipsesource/tabris-js/files/272249/tabris-android-1.8.0.zip)
[tabris-ios-1.8.0.zip](https://github.com/eclipsesource/tabris-js/files/272255/tabris-ios-1.8.0.zip)
