### ISSUE TITLE
Slider grabber misaligned

### ISSUE THREAD

**Issue by cookieguru** [eclipsesource/tabris-js#844]
Certain heights of a `Slider` causes its grabber to be misaligned:

![screenshot_2016-05-18-23-26-45](https://cloud.githubusercontent.com/assets/1888809/15384609/a9d004b8-1d50-11e6-94d1-3e08be22165f.png)

```js
new tabris.Slider({
  left: 16, bottom: 0, right: 16, height: 88,
  minimum: 1,
  maximum: 8
});
```

**Comment by mpost** [comment]
Thanks for the heads up... what android version is that?

**Comment by cookieguru** [comment]
4.4.2

**Comment by mpost** [comment]
Thanks for the info. We will investigate the issue.

**Comment by mpost** [comment]
@cookieguru The issue should be resolved with the move to the material design slider on pre android 5. Could you verify?

**Comment by cookieguru** [comment]
@mpost Just did a nightly build built against the nightly JS.  This is with a slider height of 68.
![screenshot_2016-06-23-09-59-18](https://cloud.githubusercontent.com/assets/1888809/16312406/7e54b000-3929-11e6-9a98-7928aed78e08.png)

**Comment by mpost** [comment]
Ok thanks.

**Comment by cookieguru** [comment]
Both of these are TouchWiz ROMs:

![4.4.2](https://cloud.githubusercontent.com/assets/1888809/18223142/ca38b748-7162-11e6-86a8-afabe90fb4b7.png) ![6.0.1](https://cloud.githubusercontent.com/assets/1888809/18223143/ce127020-7162-11e6-8601-a0825a65ec88.png)

Left is 4.4.2 and right is 6.0.1

I've only tested against 1.9, but the workaround in 11696845c2e3424484f97f3a01c4fb4128c1ec7d is not necessary unless the slider's height is > 49

**Comment by mpost** [comment]
While we have improved upon the snippet the main advice is to always let the slider have its intrinsic height.

**Comment by cookieguru** [comment]
Makes sense.  If padding is needed a pair of Composites could be placed on either side.
