### ISSUE TITLE
ScrollView does initially not show content in some scenarios

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#846]
In iOS it is somehow possible to have a scrollview that does not show it's content until it's resized. For an example, take the weather app (https://github.com/eclipsesource/tabris-js/blob/master/examples/typescript-weather-app/src/app.ts), remove line 34 ("setTimeout(layoutUI);", the workaround for this issue) and compille/run it. After choosing a city nothing will appear until the device is rotated. It works fine in Android.

**Comment by dested** [comment]
Is this on track to be fixed in the next release?

**Comment by dested** [comment]
Was this resolved in 1.9?

**Comment by patrykmol** [comment]
This was not fixed for 1.9 release.

**Comment by dested** [comment]
Is there any workaround for this issue?

**Comment by cookieguru** [comment]
@dested Yes, see the issue description.

**Comment by mpost** [comment]
Closing as resolved. Please reopen if you have any more issues.
