### ISSUE TITLE
Empty TextView layout inconsistency among platforms

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#851]
Currently TextViews with _text_ property set to empty string are laid out differently on iOS compared to Android. 

On iOS, empty TextViews will be laid out with height `0`, while on Android they will have some initial height.

IMO iOS client's behavior makes sense as a sensible default, as one would usually not want empty text containers to take space in layout.

**Example:**

``` javascript
var page = new tabris.Page({
  title: "Hello, World!",
  topLevel: true
});

var textView = new tabris.TextView({
  left: 0, top: 0,
  text: ""
}).appendTo(page);

new tabris.Composite({
  top: textView, left: 0, right: 0, height: 300,
  background: "red"
}).appendTo(page);

page.open();
```

| iOS | Android |
| --- | --- |
| ![simulator screen shot 22 05 2016 11 35 34](https://cloud.githubusercontent.com/assets/2341769/15453311/60899f58-2011-11e6-9c6b-c2299ffd8828.png) | ![screenshot_20160522-112816](https://cloud.githubusercontent.com/assets/2341769/15453317/99c9612c-2011-11e6-87a3-7d07c56d5b90.png) |

**Comment by mpost** [comment]
On Android the empty `TextView` behaves similar to empty `InputText`in that it retains its height based on the font and padding.

**Comment by ralfstx** [comment]
I think the `TextView` should retain its height also when empty, as other widgets (Button, TextInput, etc.) also don't shrink.

**Comment by karolszafranski** [comment]
@ralfstx do I understand correctly, you want empty TextView to have specific height (defined by a font)?

**Comment by mpost** [comment]
@karolszafranski That is correct.
