### ISSUE TITLE
Widget references may modify layout in some cases

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#854]
On Android widgets referencing intrinsically-sized widgets based on percentage layout may modify their layout. Compare both screenshots, 1st one has the yellow composite commented, while in the 2nd one it is uncommented. Note that the top offset of the purple composite is different in both screenshots.

| 1  | 2 |
| --- | --- |
| ![screenshot_20160523-162303](https://cloud.githubusercontent.com/assets/2341769/15474002/151f4336-2103-11e6-85c0-871b22523398.png) | ![screenshot_20160523-162231](https://cloud.githubusercontent.com/assets/2341769/15474027/2b501aa4-2103-11e6-87ea-31a5aed8268c.png) |

``` javascript
var page = new tabris.Page({
  title: "Hello, World!",
  topLevel: true
});

var container = new tabris.Composite({
  top: 0, left: 0, right: 0,
  background: "red"
}).appendTo(page);

var square = new tabris.Composite({
  top: "20%", centerX: 0, width: 100, height: 100,
  background: "purple"
}).appendTo(container);

var square2 = new tabris.Composite({
  top: square, centerX: 0, width: 100, height: 100,
  background: "blue"
}).appendTo(container);

// var container2 = new tabris.Composite({
//   top: container, left: 0, right: 0, height: 100,
//   background: "yellow"
// }).appendTo(page);

page.open();
```

**Comment by mpost** [comment]
The issue has been resolved in the meantime. Closing as fixed.
