### ISSUE TITLE
Cannot select custom widgets by their type (ES6)

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#859]
Currently custom widgets extending Tabris.js widgets cannot be selected by their type, e.g.:

``` javascript
import {Page, Composite} from "tabris";

class CustomWidget extends Composite {
  //...
}
let page = new Page({topLevel: true});
new CustomWidget().appendTo(page);
page.find('CustomWidget'); // wont find our CustomWidget
page.open();
```

**Comment by ralfstx** [comment]
As there is no fixed class name in ES6, I wonder how this would be supposed to work.

When a class is exported by a *default export*, which seems to be a common pattern, it's up to the import statement to assign a name to the imported class. This name is just a lexical binding, not an feature of the class itself.

**Comment by ralfstx** [comment]
The selector API is now backed by the constructor name, so this works as expected.
