### ISSUE TITLE
Support custom emoji symbols

### ISSUE THREAD

**Issue by bev-on** [eclipsesource/tabris-js#860]
Is there any way to use custom emoji symbols in TextView widget? It's technically possible because many apps are using custom emoji symbols on both Android and iOS (WhatsApp for example).

Any ideas how can I do it in Tabris without WebView widget? 

![customemoji](https://cloud.githubusercontent.com/assets/11978242/15508963/4eb96bc6-21da-11e6-8087-efea7e599473.png)

**Comment by cookieguru** [comment]
#698 probably.

**Comment by shaialon** [comment]
Hi @bev-on ,
Could you explain what you mean by "Custom Emoji"? 
What you posted in the image is standard emoji in iOS.

Here is a simple snippet with two different options to show them:
![image](https://cloud.githubusercontent.com/assets/3126207/15702517/1948e7e0-27e9-11e6-8c02-e48b909bf3ba.png)

```
var page = new tabris.Page({
  title: "Emoji fun",
  topLevel: true
});

new tabris.TextView({
    layoutData: {top: "prev() 20", left: "20%"},
    text: "Hi \ud83d\ude00 tabris.js " + String.fromCodePoint(0x1F47B),
    font: "30px"
  }).appendTo(page);

page.open();
```

Note: This snippet currently has a bug #870 on Android, but will be fixed soon.

**Comment by bev-on** [comment]
Hi @shaialon ,

I know this emoji symbols on my screenshot are standard iOS emoji symbols, but screenshot I share is taken from WhatsApp on Android. WhatsApp somehow manage to integrate iOS emoji symbols on Android, I guess they have included all iOS emoji symbols in their apk and somehow using theme.

```
var mainUname = new tabris.TextView({
    layoutData: {top: 25, left: 56, height: 30},
    text: 'Test 🙀 test te😀st👻test',
    font: 'bold 16px',
    textColor: '#333' 
}).appendTo(userContainer);
```
this is what this code looks like on my iPad
![ipad](https://cloud.githubusercontent.com/assets/11978242/15708184/c8825ca2-2805-11e6-8490-e546d112c988.png)

and this is on Android
![note](https://cloud.githubusercontent.com/assets/11978242/15708194/df5e16f0-2805-11e6-8327-820560bfe643.png)
(BTW as you can see, there is no emoji bug you mentioned on my Android (6.0.1).)

By "custom emoji" I mean to add custom emoji library on my apk and use them to show same emoji symbols on any device like WhatsApp.

**Comment by bev-on** [comment]
Also I use WhatsApp and iOS emoji symbols on Android just for example. I don't want to use iOS emoji symbols, I want to use custom emoji symbols. This symbols are already used on my website and users are use to them, so if I replace them with standard iOS or Android emoji symbols, they won't be happy about it.

**Comment by mpost** [comment]
With the support for custom fonts this should be covered. In addition you would want to watch out for better font support in markup enabled texts. https://github.com/eclipsesource/tabris-js/issues/1761
