### ISSUE TITLE
RethinkDB module not supported

### ISSUE THREAD

**Issue by kanekotic** [eclipsesource/tabris-js#864]
i am trying to do an app that uses RethinkDB and this module seems not to be supported not suported

``` js
\\npm install rethinkdb
var r = require('rethinkdb');
```

**Comment by mpost** [comment]
It RethinkDB using websockets under the hood to keep connected to the databse? (ala firebase)

**Comment by kanekotic** [comment]
so as i haven't found their package in npm, it has been difficult to findhow this works. after a bit of digging around they are not using directly any package similar to ```sockets.io```, but regarding communication they seem to be using nodes ```net``` and ```tls``` packages. (plus other dependencies: ```cripto```, ```events```, and ```(npm) bluebird```). 

for you to have more info you will need to add to a node project the package of rethinkdb (```npm install rethinkdb```), and look inside node_modules.

**Comment by mpost** [comment]
@kanekotic Thanks for the details... i think there might be something missing in the dependend node packages. @ralfstx do you have any insights?

**Comment by ralfstx** [comment]
I don't know this module but it appears that the git repo involves a lot of C++ code. Does the npm module include binary code? If so, this would not run on the mobile platforms out of the box.

@kanekotic What is the exact symptom of not working? Do you get an exception?

**Comment by kanekotic** [comment]
@ralfstx The project that is a database is mostly C++ code, agreed. But the projects that use this db need an npm package that is purely javascript. It can be added to any node based project by:
```
npm install rethinkdb --save
```

This npm package to the extend of what i have seen by review it on the node_modules folder, it rely mostly in the node api. As per your question the symptom is when i run it shows on screen the message: ```cannot find the module net```. After reviewing the package code is this node library [net](https://nodejs.org/api/net.html). 

This error happens by just adding to the basic tabris project any of the next js codes:
```js
var r = require('rethinkdb');
```
```js
require("tabris-js-node");
var r = require('rethinkdb');
```

I have create a base [project](https://github.com/kanekotic/TabrisIn15)  if you want to clone it and try.

**Comment by ralfstx** [comment]
Right, the Node.js `net` module is not yet supported.

**Comment by ralfstx** [comment]
Closing as npm modules that include binary code (C++) can not be supported by Tabris.js.
