### ISSUE TITLE
Debounce event

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#866]
Along with on and once, it would be nice to have a debounce event, forcing a timeout between events firing. The use case is a button that the user clicks on multiple times, allowing the developer to define how long the user would have to wait before the click event will fire again.

**Comment by ralfstx** [comment]
There are libraries out there to debounce and filter streams of events (e.g. [RxJs](https://github.com/Reactive-Extensions/RxJS)). This seems to be a topic that does not require the assistance of the widget toolkit and can easily and more flexibly be handled by a third-party lib.

Please reopen if you disagree.
