### ISSUE TITLE
Selectable TextView

### ISSUE THREAD

**Issue by bev-on** [eclipsesource/tabris-js#868]
Please add selectable option to TextView widget, this will be really useful for apps with large texts where users may need to copy just small part of the text. Both Android and iOS natively support this option.

https://developer.android.com/reference/android/R.styleable.html#TextView_textIsSelectable
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITextView_Class/#//apple_ref/occ/instp/UITextView/selectable

Also if there is possibility to add event to TextView which will be triggered when user selects text and returns selected text or range.

Something like this will be great:

```
// return selected text

var exampleText = 'Hello World!';

new tabris.TextView({
    layoutData: {left: 10, top: 10, right: 10},
    alignment: 'left',
    selectable: true,
    text: exampleText
}).on('select', function(widget, selectedText){
    // if user selects "World", output will be "World"
    console.log(selectedText);
}).appendTo(page);

// or you can return selected range

new tabris.TextView({
    layoutData: {left: 10, top: 10, right: 10},
    alignment: 'left',
    selectable: true,
    text: exampleText
}).on('select', function(widget, selectedRange){ 
    // if user selects "World", output will be "[6, 11]" (start and end positions of selected text)
    console.log(selectedRange); // [6, 11]
    console.log(this.get('text').substring(selectedRange[0], selectedRange[1]); // World
}).appendTo(page);
```

Also select event can be added to TextInput widget.

**Comment by mpost** [comment]
That sounds like a good thing to have.

**Comment by bev-on** [comment]
@mpost any update on this feature?

This is really important feature and I'm forced to use WebView instead of native TextView because of this :(

Check out example from Gmail app:
![gmail](https://cloud.githubusercontent.com/assets/11978242/18359432/94a28d58-7602-11e6-8e90-2c01b66fe93e.jpg)

Is it hard to implement?

**Comment by mpost** [comment]
We still think it is a valuable addition. It is easy to [do on Android](https://developer.android.com/reference/android/widget/TextView.html#setTextIsSelectable(boolean)) but a little more complicated on iOS.

We currently base the tabris `TextView` on the iOS `UILabel` which does not support that behavior. We could however migrate that to `UITextField` that allows for a user selection.

**Comment by bev-on** [comment]
Thanks guys!

This feature is added in Tabrisjs 2. I will close this issue.

@mpost
