### ISSUE TITLE
TextInput has several bugs on iOS when type: `multiline`

### ISSUE THREAD

**Issue by shaialon** [eclipsesource/tabris-js#869]
In multiline mode there are 3 issues:
1. If height is not set, the textInput is not seen
2. The keyboard has a row on the top with a "Done" button that can't be hidden.
3. The 'message' does not to show up any more.
  
See below snippet:

```javascript
var page = new tabris.Page({
  title: "Text Input Multiline on iOS",
  topLevel: true
});

new tabris.TextInput({
  layoutData: {top: 20, left: "20%", right: "20%", height: 40}, // 1. If height is not set, the textInput is not seen
  type: "multiline", // 2. When the type is 'multiline', the keyboard has a row on the top with a "Done" button that can't be hidden.
  message: "Type here, then confirm22", // 3. The 'multiline' option causes the 'message' not to show up.
  
}).on("accept", function(widget, text) {
  new tabris.TextView({
    layoutData: {top: "prev() 20", left: "20%"},
    text: text
  }).appendTo(page);
}).appendTo(page);

page.open();
```

**Comment by bFlood** [comment]
+1

**Comment by jkrause** [comment]
1. When no height is set the textInput now gets a height of one line. The height will adjust to the amount of text.
2. Keyboard done Button cannot be hidden, we need to be able to distinguish between "new line" and "accept"
3. Message is not available on iOS for multi-line text inputs -> documentation has been adjusted
