### ISSUE TITLE
Emoji not working on Android

### ISSUE THREAD

**Issue by shaialon** [eclipsesource/tabris-js#870]
The bellow snippet renders nice Emoji on iOS:
![image](https://cloud.githubusercontent.com/assets/3126207/15702517/1948e7e0-27e9-11e6-8c02-e48b909bf3ba.png)

But not on Android (5):
![image](https://cloud.githubusercontent.com/assets/3126207/15702638/ce890518-27e9-11e6-9fdd-cc28ccc44046.png)

```
var page = new tabris.Page({
  title: "Emoji fun",
  topLevel: true
});

new tabris.TextView({
    layoutData: {top: "prev() 20", left: "20%"},
    text: "Hi \ud83d\ude00 tabris.js " + String.fromCodePoint(0x1F47B),
    font: "30px"
  }).appendTo(page);

page.open();
```

**Comment by bev-on** [comment]
@shaialon As I mentioned in another issue, this code works fine on my Android 6.0.1, but later I test it on my old device (Android 4.1.2) at I have same issue. Looks like there is some issue with older Android versions.

Android 6.0.1 (Samsung SM-N915F - Galaxy Note Edge)
![newandro](https://cloud.githubusercontent.com/assets/11978242/15708647/578e3ed2-2808-11e6-8320-ddfce7e6c00e.png)

Android 4.1.2 (Samsung GT-S5280)
![oldandro](https://cloud.githubusercontent.com/assets/11978242/15708676/8efa4f00-2808-11e6-8a14-b43780897f0e.png)

**Comment by mpost** [comment]
That could be the font used on the device. Maybe the icon is missing.

**Comment by bev-on** [comment]
@mpost Yeah, I just test same text on my old device and only weird ghost emoji is available.

![ooo](https://cloud.githubusercontent.com/assets/11978242/15710604/713ba206-2813-11e6-8186-757d53634ffd.png)

@shaialon can you check this GitHub issue from your device browser and check if you can see emoji symbols in following text?

----------------------------
Hi 😀 tabris.js 👻
----------------------------

If you can't see emoji in your browser as well, it means there is no tabrisjs emoji bug.

**Comment by cookieguru** [comment]
Just to add another data point, I ran @shaialon's snippet on 4.4.2 (SCH-I545) and I see this:

![screenshot_2016-06-01-11-57-45](https://cloud.githubusercontent.com/assets/1888809/15721986/6c584028-27f0-11e6-89fd-45bb9bb9df3e.png)

But @bev-on's comment above looks fine in Chrome on the device.

**Comment by shaialontabris** [comment]
@bev-on , I checked with the stock browser (not chrome) on Android 5.0.2 and it has the emoji like the ones you posted from 6.0.1

![image](https://cloud.githubusercontent.com/assets/16774265/15738141/9d5b033c-28b2-11e6-95a7-76394a55b090.png)

**Comment by mpost** [comment]
@irbull Isn't that fixed with the update to j2v8 4.2?

**Comment by irbull** [comment]
@mpost If the font is available on the phone it should work.

**Comment by mpost** [comment]
Closing this as resolved.
