### ISSUE TITLE
Provide locked property on app

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#873]
In addition to the `pause` and `resume` events, provide a property `paused` on `tabris.app` that indicates if the app is currently paused. This property should be true _before_ the `pause` event fires to be used by code that is executed on `pause` (such as a lock screen).

**Comment by mpost** [comment]
In the meantime we have introduced `background` and `foreground` app state events so a property on app should reflect those app lifecycle events as well.

**Comment by mpost** [comment]
With pause, resume, fore- and background events we should have covered most cases. Closing as resolved.
