### ISSUE TITLE
Provide isDevMode() method

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#874]
Provide a method that indicates whether the app currently runs in debug mode. I'd consider it in debug mode when the developer console is enabled.

This would allow us to handle errors differently during development than in the productive app. It could also be used to include additional UI used for debugging purposes.

**Comment by mpost** [comment]
I would agree... I'd rather call it dev mode (and maybe also bind the console to that flag) to not confuse it with the clients actually being debuggable. This could also be used to control things like chrome dev tools debugging etc.

**Comment by ralfstx** [comment]
:+1: for calling it "dev mode" and binding the console to this flag

**Comment by mpost** [comment]
With the addition of the `debugBuild` `App` property this should be covered.
