### ISSUE TITLE
Is there a way to set the TextInput.message color?

### ISSUE THREAD

**Issue by maxapps** [eclipsesource/tabris-js#875]
I see an old post [301](https://github.com/eclipsesource/tabris-js/issues/301) from 2015 which asked this same question and was linked to another post [523](https://github.com/eclipsesource/tabris-js/issues/523).

Both are marked as closed but, as far as I can tell, there still isn't a way to achieve this.

What am I missing?

**Comment by mpost** [comment]
@maxapps Currently that is not possible.

**Comment by mpost** [comment]
@maxapps There is actually a way to set the color (at least on Android). You can define your own custom Android theme and change the "hint" color in there. See this blog post to get started: http://eclipsesource.com/blogs/2015/07/03/tabris-js-1-1-sneak-peak-custom-themes-on-android/

**Comment by maxapps** [comment]
Unfortunately, I need a way to do this dynamically because the color scheme
is determined by the user. This is for a sport stat picking app and the
user would generally choose colors similar to their team.

**Comment by patrykmol** [comment]
`messageColor` property has been implemented to allow this functionality.
