### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by sand123** [eclipsesource/tabris-js#876]
Here https://tabrisjs.com/documentation/latest/types#dimension
```See also Layout``` is missing

**Comment by sand123** [comment]
Also here https://tabrisjs.com/documentation/latest/api/ImageView#image
Properties - tintColor markup fix needed

**Comment by mpost** [comment]
Thanks for pointing these out... @ralfstx Do you have an idea what is happening in the second link? I have added a fix for the first one.

**Comment by cookieguru** [comment]
@mpost @ralfstx Just need an extra `\n` at the end of the description for `none`

**Comment by mpost** [comment]
@cookieguru Yeah we will update the generator to put additional line breaks after headers.

**Comment by mpost** [comment]
The broken link is fixed via https://github.com/eclipsesource/tabris-js/commit/dfb1d488c61c19862057e42108f4fe7e5e6227c7. The generator still needs to be updated thought @ralfstx.
