### ISSUE TITLE
Unable to Compile org.apache.cordova.AndroidWebView for Local Build

### ISSUE THREAD

**Issue by wilsonna** [eclipsesource/tabris-js#878]
Sorry, I've edited my original post as I've resolved that problem by deleting my /platforms folder and re-adding it. But now I'm getting a compilation error for AndroidWebView:

```
:CordovaLib:compileDebugJavaWithJavacC:\projects\transport\platforms\android\CordovaLib\src\org\apache\cordova\AndroidWebView.java:61: error: AndroidWebView is not abstract and does not override abstract method getEngine() in CordovaWebView
public class AndroidWebView extends WebView implements CordovaWebView {
       ^
C:\projects\transport\platforms\android\CordovaLib\src\org\apache\cordova\AndroidWebView.java:129: error: constructor LoadUrlBridgeMode in class LoadUrlBridgeMode cannot be applied to given types;
        nativeToJsMessageQueue.addBridgeMode(new NativeToJsMessageQueue.LoadUrlBridgeMode(this, cordova));
                                             ^
  required: CordovaWebViewEngine,CordovaInterface
  found: AndroidWebView,CordovaInterface
  reason: actual argument AndroidWebView cannot be converted to CordovaWebViewEngine by method invocation conversion
```

**Comment by wilsonna** [comment]
Just an update, I got past the above by editing AndroidWebView and implementing an empty `clearCache()` and commenting out the line with `LoadUrlBridgeMode`.

Then I hit the below:

	Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

I resolved this by editing build.gradle to include the line `compile 'com.google.android.gms:play-services:9.0.2'` under `dependencies`.

That allowed me to finally complete the local build successfully. I hope I'm doing it right...

**Comment by mpost** [comment]
Yes that seams about right... Instead editing the build.gradle file you could also requrest a cordova dependency. Thereby you wouldn't need to alter the build script:

```xml
<platform name="android">
    <framework src="com.company:project:1.0.0" />
</platform>
```

**Comment by mpost** [comment]
Closing this as "resolved".
