### ISSUE TITLE
TextInput password keyboard bug

### ISSUE THREAD

**Issue by bev-on** [eclipsesource/tabris-js#879]
Password keyboard doesn't behaves natively on Android.

If word suggestions are enabled on android keyboard, suggestions are visible on password keyboard type as well. First of all this doesn't feels native because in browser and in other apps there is no suggestions on password keyboard and second, it can show your password as suggestion if you have personalized data enabled in your Android keyboard settings and it learns what you type. 

Password keyboard example in regular browser:

![browser](https://cloud.githubusercontent.com/assets/11978242/15802402/bd62eeac-2ab9-11e6-9ac3-7252c02c4f79.png)

Password keyboard example in Tabris.js app:

![tabris](https://cloud.githubusercontent.com/assets/11978242/15802406/dcdd7522-2ab9-11e6-8e65-510a4a400e0d.png)

As you can see, there is no suggestions in browser, but in tabris.js app, when I enter "test" as password, you can see suggestions related to password I entered.

This is problem on all Android versions I have tested, from Android 4.1.2 to Android 6.0.1. On iOS there is no bug, suggestions only works for normal keyboards and they disappear if you choose password as keyboard type.

**Comment by mpost** [comment]
Thanks for your feedback. We have deliberately added support to not show the suggestions but how keyboards interpret our suggestions is up them. We will look into that again. You are on a Galaxy Sx?

**Comment by bev-on** [comment]
@mpost Yes, I test it on 4 different Samsung devices and all of them have same issue with original Samsung keyboards. If I use Google keyboard, there is no suggestions, so it must be only Samsung keyboard issue, but problem is that Samsung has biggest market share on Android and this is really important issue.

For example if personalized data and auto correction is enabled from keyboard settings and your password is jOhndOe123, when you enter this password few times, it will automatically added to suggestions because you use it frequently and next time when you write SMS and you misspelled name John with for example Johnm, it may accidentally autocorrect Johnm with your password and you may send your password to someone if you click send fast enough before you realize what happened or didn't pay attention.

**Comment by mpost** [comment]
@bev-on Yes we recognize this as a problem and will fix asap.

**Comment by mpost** [comment]
@bev-on We have fixed the problem and it will be available in the next nightly build.

**Comment by cookieguru** [comment]
@mpost Any chance the hinting of suggestions can be brought to the JS side?  There are times when a `default` [keyboard](https://tabrisjs.com/documentation/latest/api/TextInput#keyboard) is appropriate but suggestions aren't wanted.

**Comment by mpost** [comment]
@cookieguru Currently that can not be controlled directly from js. Please open a new issue when you think this feature is valuable and is not covered by our various types.
