### ISSUE TITLE
Capturing UI Back button

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#880]
Is there any way to override the UI back button? I see tabris.app.on("backnavigation") but it only works for the android back button. Ideally I would like the same api for the navigation stack back button.

**Comment by mpost** [comment]
The pages have open and close events. You can not intercept the the navigation attempt though.

**Comment by dested** [comment]
Is there a specific reason or is the behavior too ambiguous to make it worth tackling at a framework level

**Comment by mpost** [comment]
on ios you can not intercept the back event once the user clicks on the navigation controller (or swipes).

**Comment by mpost** [comment]
Closing this as resolved.
