### ISSUE TITLE
XML HTTP Request - responseType

### ISSUE THREAD

**Issue by trevorwat** [eclipsesource/tabris-js#881]
Hi,
Is there a way to load raw binary data - I was trying     xhr.responseType = "arraybuffer" but it throws an error saying only text is supported.

I need a way to get at raw image files which I'll run through jpegjs before putting the imagedata into a canvas... essentially I'm working around the lack of a canvas context drawImage().

Thanks in advance.

**Comment by mpost** [comment]
That is a valid request. We are currently expanding our support for arraybuffers in multiple areas and this is definitely one of them (including binary upload). Please stay tuned.

**Comment by trevorwat** [comment]
Hi,
I managed to get the cordova file plugin to read the raw binary data in on Android then use JPEG.js to decode it before writing it onto a canvas.. I get an error running the same on IOS though.

This code :-

var fileReader = {};
//setup the ability to read a file
document.addEventListener('deviceready', onDeviceReady, false);  
function onDeviceReady() {  
    function readFromFile(fileName, callback) {
		window.resolveLocalFileSystemURL(fileName, function (fileEntry) {
            fileEntry.file(function (file) {
                var reader = new FileReader();

                reader.onloadend = function (e) {
                    console.log("file reading ended", this);
					callback(this.result);
                };
				
				console.log("file reading about to start", this);
                reader.readAsArrayBuffer(file);
				console.log("file reading about to started", this);
            }, fileReadErrorHandler.bind(null, fileName));
        }, fileReadErrorHandler.bind(null, fileName));
    }
	
	var fileReadErrorHandler = function (fileName, e) {  
		var msg = '';
		switch (e.code) {
			case FileError.QUOTA_EXCEEDED_ERR:
				msg = 'Storage quota exceeded';
				break;
			case FileError.NOT_FOUND_ERR:
				msg = 'File not found';
				break;
			case FileError.SECURITY_ERR:
				msg = 'Security error';
				break;
			case FileError.INVALID_MODIFICATION_ERR:
				msg = 'Invalid modification';
				break;
			case FileError.INVALID_STATE_ERR:
				msg = 'Invalid state';
				break;
			default:
				msg = 'Unknown error';
				break;
		};
		console.log('File Reading Error (' + fileName + '): ' + msg);
	}
	fileReader.readFromFile = readFromFile;
}

works just fine on Android but gives a nice big stack trace on IOS:-

**ReferenceError: Can't find variable: atob**
> base64ToArrayBuffer@file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/cordova.js:838:40
massageMessageNativeToJs@file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/cordova.js:840:36
createIOSMessage@file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/cordova.js:854:41
processIOSEvent@file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/cordova.js:864:35
file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/cordova.js:873:24
_callAll@http://192.168.1.129:8080/node_modules/tabris/tabris.min.js:32:9616
trigger@http://192.168.1.129:8080/node_modules/tabris/tabris.min.js:32:9441
_trigger@http://192.168.1.129:8080/node_modules/tabris/tabris.min.js:32:27721
_notify@http://192.168.1.129:8080/node_modules/tabris/tabris.min.js:32:10390
_notify
[native code]
call@http://192.168.1.129:8080/node_modules/tabris/tabris.min.js:32:15233
_nativeCall@http://192.168.1.129:8080/node_modules/tabris/tabris.min.js:32:28109
exec@file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/cordova.js:883:25
tabrisExec@file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/cordova.js:927:21
readSuccessCallback@file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/plugins/cordova-plugin-file/www/FileReader.js:142:13
readSuccessCallback@[native code]
readAsArrayBuffer@file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/plugins/cordova-plugin-file/www/FileReader.js:283:35
http://192.168.1.129:8080/modules/WelcomePage.js:29:41
file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/plugins/cordova-plugin-file/www/FileEntry.js:85:24
callbackFromNative@file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/cordova.js:293:63
processIOSEvent@file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/cordova.js:865:31
file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/cordova.js:873:24
_callAll@http://192.168.1.129:8080/node_modules/tabris/tabris.min.js:32:9616
trigger@http://192.168.1.129:8080/node_modules/tabris/tabris.min.js:32:9441
_trigger@http://192.168.1.129:8080/node_modules/tabris/tabris.min.js:32:27721
_notify@http://192.168.1.129:8080/node_modules/tabris/tabris.min.js:32:10390
_notify
[native code]
call@http://192.168.1.129:8080/node_modules/tabris/tabris.min.js:32:15233
_nativeCall@http://192.168.1.129:8080/node_modules/tabris/tabris.min.js:32:28109
exec@file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/cordova.js:883:25
tabrisExec@file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/cordova.js:927:21
file@file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/plugins/cordova-plugin-file/www/FileEntry.js:90:9
http://192.168.1.129:8080/modules/WelcomePage.js:20:27
file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/plugins/cordova-plugin-file/www/resolveLocalFileSystemURI.js:76:40
getFs@file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/plugins/cordova-plugin-file/www/fileSystems-roots.js:41:17
success@file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/plugins/cordova-plugin-file/www/resolveLocalFileSystemURI.js:70:38
callbackFromNative@file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/cordova.js:293:63
processIOSEvent@file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/cordova.js:865:31
file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/cordova.js:873:24
_callAll@http://192.168.1.129:8080/node_modules/tabris/tabris.min.js:32:9616
trigger@http://192.168.1.129:8080/node_modules/tabris/tabris.min.js:32:9441
_trigger@http://192.168.1.129:8080/node_modules/tabris/tabris.min.js:32:27721
_notify@http://192.168.1.129:8080/node_modules/tabris/tabris.min.js:32:10390
_notify
[native code]
call@http://192.168.1.129:8080/node_modules/tabris/tabris.min.js:32:15233
_nativeCall@http://192.168.1.129:8080/node_modules/tabris/tabris.min.js:32:28109
exec@file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/cordova.js:883:25
tabrisExec@file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/cordova.js:927:21
file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/plugins/cordova-plugin-file/www/resolveLocalFileSystemURI.js:86:13
readFromFile@http://192.168.1.129:8080/modules/WelcomePage.js:19:35
onScanSuccess@http://192.168.1.129:8080/modules/WelcomePage.js:154:26
callbackFromNative@file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/cordova.js:293:63
processIOSEvent@file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/cordova.js:865:31
file:///private/var/mobile/Containers/Bundle/Application/FD95D2B3-A20A-463F-880A-56F54AB0F701/tabris.js.app/www/cordova.js:873:24
_callAll@http://192.168.1.129:8080/node_modules/tabris/tabris.min.js:32:9616
trigger@http://192.168.1.129:8080/node_modules/tabris/tabris.min.js:32:9441
_trigger@http://192.168.1.129:8080/node_modules/tabris/tabris.min.js:32:27721
_notify@http://192.168.1.129:8080/node_modules/tabris/tabris.min.js:32:10390
_notify

**Comment by cookieguru** [comment]
While it's not going to solve your error, you can remove the listener for `ondeviceready`.  It's not necessary in Tabris.js

**Comment by mpost** [comment]
Support for `responseType` `arraybuffer` will be added in the Tabris.js 2.x release.

**Comment by mpost** [comment]
Related:
https://github.com/eclipsesource/tabris-js/issues/650
https://github.com/eclipsesource/tabris-js/issues/613

**Comment by ralfstx** [comment]
The responseType `arraybuffer` is supported as of 2.0.0 Beta 1. Blob is covered by #687.
