### ISSUE TITLE
Strange problem in Tabris.js Technical Preview (Windows 10)

### ISSUE THREAD

**Issue by bev-on** [eclipsesource/tabris-js#883]
Maybe it's too early to start reporting bugs for Windows version, but I was able to test few things in your technical preview and I really liked it.

Strange problem I mentioned in title is that every time I try to connect URL on same machine where Tabris.js Technical Preview is installed I get following error

![untitled](https://cloud.githubusercontent.com/assets/11978242/15908268/80c7d116-2dc9-11e6-8abc-f4ebe574e910.png)

For example my Windows 10 PC have assigned IP 192.168.0.102... If I try to connect http://192.168.0.102 or http://localhost or http://127.0.0.1 from Tabris.js app on same machine, I get this error. Strange thing is that I can connect to http://192.168.0.102 from another Win10 machine in same network. Same issue on all machines running Win10, so it's not isolated issue. Any Win10 PC can connect URL on another Win10 PC, but they can't connect URL on local machine.

**Comment by tbuschto** [comment]
Did you perhaps forget adding the port number? Fore me "http://127.0.0.1:8080" works, but "http://127.0.0.1" doesn't.

**Comment by ralfstx** [comment]
Assuming this is resolved. Please reopen if your problem persists.

**Comment by cookieguru** [comment]
For future reference, from [the docs](https://tabrisjs.com/tabris-js-docs/latest/windows-support.html):
> Loopback addresses (localhost, 127.0.0.1) do not work out-of-the-box. To allow the developer app to access a tabris http-server running on the same machine, you need to enable it once using this command in an admin command prompt window:
```Batchfile
CheckNetIsolation.exe LoopbackExempt -a -p="S-1-15-2-2113086592-2161398931-2814723024-3165814665-986162242-220195364-2881192403"
```
