### ISSUE TITLE
Cards widget

### ISSUE THREAD

**Issue by iteearmah** [eclipsesource/tabris-js#886]
Adding Cards display widget

**Comment by cookieguru** [comment]
Try this:
```js
var page = tabris.create("Page", {
  title: "Card",
  topLevel: true
});

var outside = tabris.create("Composite", {
  left: 10, top: 10, right: 10,
  height: 128,
  background: "#999999",
  cornerRadius: 2,
}).appendTo(page);

var inside = tabris.create("Composite", {
  left: 1, top: 1, bottom: 2, right: 1,
  background: "#FFFFFF",
  cornerRadius: 0,
  cornerRadius: 2,
}).appendTo(outside);

new tabris.TextView({
  left: 10, top: 10, right: 10,
  text: "Card content",
  alignment: "center"
}).appendTo(inside);

page.open();
```
I only have 4.x devices so I'm not sure how the corner radii look.


Combine that with [swipe-to-dismiss.js](https://github.com/eclipsesource/tabris-js/blob/master/examples/swipe-to-dismiss/swipe-to-dismiss.js) for a card-like UX.

**Comment by mpost** [comment]
+1 to @cookieguru comment. Although the general pattern of a card would not require a "border". Instead you could use the `elevation` (on Android 5+) to create a drop shadow.

**Comment by mpost** [comment]
Closing this as "solved".

**Comment by jokorivai** [comment]
Sorry for reopen this.
Just want to add a JS library for creating card in Cordova TabrisJS app:
[Cordova - TabrisJS CardView plugin](https://github.com/jokorivai/cordova-plugin-tabrisjs-card)

Hope this helps someone.

**Comment by mpost** [comment]
Looks nice. :)

You could try to stay more in line with the Material Design card pattern. Eg. No margin around the image, etc. https://material.google.com/components/cards.html

**Comment by jokorivai** [comment]
@mpost thank you.

**Comment by arjunmenon** [comment]
Hey @mpost
What versions of iOS supports `elevation`? In [the docs](https://tabrisjs.com/documentation/latest/api/Widget#elevation) it mentions only Android 5+
It tested in ipad 10.3.3. Does it support below this ios version?

**Comment by cookieguru** [comment]
@arjunmenon `elevation` is only supported on Android, as the docs indicate

**Comment by mpost** [comment]
In fact `elevation` is also supported on iOS in Tabris.js but only on Android 5.0+.

**Comment by arjunmenon** [comment]
@cookieguru I tried it in ios 10. It does show the elevation. Want to confirm what all versions.

**Comment by mpost** [comment]
We have updated the documentation to state that the `elevation` is also supported on iOS.
