### ISSUE TITLE
TextView alignment property not working with lineSpacing on iOS

### ISSUE THREAD

**Issue by bev-on** [eclipsesource/tabris-js#887]
If you set `lineSpacing` property to TextView, `alignment` doesn't works on iOS and text is automatically set to default alignment (left).

Try following snippet on iOS device for demo:

``` javascript
var page = new tabris.Page({
    title: "TextView test",
    topLevel: true
});

var txt = new tabris.TextView({
    layoutData: {left: 10, right: 10, centerY: 0},
    text: 'some random text',
    lineSpacing: 1.2,
    alignment: 'center'
}).appendTo(page);

page.open();
```

`lineSpacing` property is working, only affected property is `alignment` and only on iOS. Android/Windows doesn't have any issue with `lineSpacing`... Well, Tabris for Windows doesn't supports `lineSpacing` yet, but if you set `lineSpacing` anyway, `alignment` property is not affected.

**Comment by mpost** [comment]
The following snippet works as expected:

```js
new tabris.TextView({
  left: 10, right: 10, centerY: 0,
  background: 'red',
  text: 'some random text some random text some random textsome random textv  ',
  lineSpacing: 2.2,
  alignment: 'center'
}).appendTo(tabris.ui.contentView);
```
Closing as works as expected.
