### ISSUE TITLE
Apk Size - Option to chose ARM / X86

### ISSUE THREAD

**Issue by Enforcer007** [eclipsesource/tabris-js#888]
When I go for build service, I observe apk size for Hello-World App is about 10~12 MB, which is huge for a simple App, this may be because of platform dependent files for arm and x86 architectures. In India most of the android mobiles are based on arm architecture. I request the tabris team to let developers chose the architecture while going for online builds there by decreasing the size almost to half.

**Comment by cookieguru** [comment]
I took a look at the packed sizes of one of my recently-built APKs:

File | Size
------------ | -------------
x86 | 2,289,115
arm | 1,952,002
classes.dex | 2,543,107
*Everything else* | *2,611,956*
**Total** | **9,396,180**

Deleting the x86 lib resulted in an APK that is 7,106,937 bytes, or only a 24.3% reduction.

Have you tried doing a [local build](https://tabrisjs.com/documentation/latest/local-build) and modifying your build script to only produce an ARM apk?

**Comment by mpost** [comment]
You are right about the apk packaging. As @cookieguru suggested you can modify your local build to produce different artifacts. We are looking into making this available directly in the build service but for now you would have to do it yourself.

**Comment by mpost** [comment]
With the introduction of the Android app bundle it is now simpler to create smaller platform specific apps: https://developer.android.com/platform/technology/app-bundle/

**Comment by mpost** [comment]
Closing this as resolved from our side. Please use the app-bundles or provide cordova build switches to only support a specific architecture.

**Comment by cookieguru** [comment]
@mpost Are either of those usable in the online build service?

**Comment by mpost** [comment]
Not yet from inside the build service.

**Comment by cookieguru** [comment]
Would it be possible to add instructions to the build docs?

**Comment by mpost** [comment]
Yes that would make sense. :+1:
