### ISSUE TITLE
How to transform text uppercase/lowercase

### ISSUE THREAD

**Issue by exocom** [eclipsesource/tabris-js#891]
Hey tabris team,

Is there a way to transform the text to uppercase / lowercase. For example we would like to use apply/set to set all of our Buttons to be UPPERCASE text.

**Comment by cookieguru** [comment]
```js
var button = new tabris.Button({
  text: "Button".toUpperCase()
});
```
```js
button.set('text', button.get('text').toLowerCase());
```

**Comment by exocom** [comment]
@cookieguru That won't easily work when using translations. Hence the using .apply

We have all of the text in a external file. Parsing the json for specific text would be cumbersome.

en.json
```
{
  ".next": {
    "text": "next"
  }
}
```

app.js
```
var button = new Tabris.Button({class:"next"});         // Outputs next
var textInput = new Tabris.TextView({class:"next"}); // Outputs next
```

Hoping to have the Widget convert the text during the apply process, same as textColor, font, etc.

app.js
```
var button = new Tabris.Button({class:"next",textTransform:"uppercase"});   // Outputs NEXT
var textInput = new Tabris.TextView({class:"next"}); // Outputs next
```

**Comment by cookieguru** [comment]
What is your criteria for uppercasing and lowercasing?  Is it something you can determine on widget creation?

The [tabris-con](https://github.com/eclipsesource/tabris-con/) app has all uppercase text for buttons on Android; other platforms use the text as it is localized.  For example, the [Feedback page](https://github.com/eclipsesource/tabris-con/blob/8862365b6546f8578e4b84ef6ab54b101153bc88/src/pages/FeedbackPage.js#L30) has a submit button and even though the text is defined as "Submit" and "Abschicken" it will display as all caps on Android and in that case on other platforms.  There is no getter/setter necessary when creating/adding it to the page; only [where the widget is created](https://github.com/eclipsesource/tabris-con/blob/8862365b6546f8578e4b84ef6ab54b101153bc88/src/components/TabrisConButton.js).

**Comment by exocom** [comment]
@cookieguru That is one way to do it, however, I believe this would be a useful thing to have baked in. The same reason it is part of CSS, because it is extremely useful. Especially when dealing with data from a CMS. We have places we want to have uppercase and lowercase.

For the time being I think we'll do it in a similar approach to your example by extending the tabris Widget to support the property and thus add the functionality everywhere.

**Comment by mpost** [comment]
Closing as resolved.
