### ISSUE TITLE
localStorage does not support Object apis like browsers do

### ISSUE THREAD

**Issue by shaialon** [eclipsesource/tabris-js#892]
This creates various issues connecting with Third party SDKs.
For example:

The Backendless api uses:

``` javascript
if (!('Backendless' in storage)) {  //  storage is window.localStorage
```

on
[https://github.com/Backendless/JS-SDK/blob/master/libs/backendless.js#L659](https://github.com/Backendless/JS-SDK/blob/master/libs/backendless.js#L659)

This creates an unwanted side effect in Tabris.js  with the `if` statement passing even when there is something in the localStorage under ‘Backendless’.

Changing the line to `if (!(storage.getItem('Backendless'))) {` fixes the issue. 
I can issue a pull request for them, but would it not be better if we had support for `'someKey' in localStorage` like the browsers do (I assume Backendless are not the first SDK to do this)?

**Comment by shaialon** [comment]
Update: Backendless have merged [my PR](https://github.com/Backendless/JS-SDK/pull/35) so this issue is no longer relevant to the use case of their SDK. However I do think we should do this at some point to because other SDKs are probably also doing this.

**Comment by ralfstx** [comment]
We'd need native client support to obtain the list of keys for the storage.

**Comment by tbuschto** [comment]
Closed in favor of https://github.com/eclipsesource/tabris-js/issues/313
