### ISSUE TITLE
Add support for start and stop app lifecycle events

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#893]
In addition to the existing `pause` and `resume` events we should add support for `start`and `stop` as available on Android.

https://tabrisjs.com/documentation/latest/api/app#events

http://www.javatpoint.com/images/androidimages/Android-Activity-Lifecycle.png

Since there are no direct counterparts on iOS we could simply call the `start` and `stop` right after and before the `pause` and `resume` events.

**Comment by ralfstx** [comment]
The names `start` and `stop` are related to an Android activity, but in the context of `tabris.app`, they are misleading. These events are fired when the app enters the background or enters the foreground again. On iOS they're called something like "enterBackground" and "enterForeground".

**Comment by patrykmol** [comment]
iOS change is now in staging and new events are: `start`, `stop`, `foreground`, `background`.

**Comment by tbuschto** [comment]
So either foreground/background or start/stop. Honestly I think either is fine.
