### ISSUE TITLE
Disposing canvas 

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#895]
The following example eventually crashes the application, saying that it is out of memory. I believe this is due to the canvas or context not being properly disposed.

```js
var page = new tabris.Page({
    title: "Canvas",
    topLevel: true
});

function build(){
   page.children().dispose();
        var canvas = new tabris.Canvas({layoutData:{width:100,height:100}}).appendTo(page);
            var ctx = canvas.getContext("2d", 100, 100);
            ctx.fillText((Math.random()*1000|0)+"", 50, 50);
}
build();
page.open();
setInterval(build,10)
```

**Comment by mpost** [comment]
Are you seeing this on Android or iOS?

**Comment by dested** [comment]
Android, it seems to run forever successfully on IOS.

**Comment by mpost** [comment]
Thanks for the hint. We can confirm the issue and will fix it asap.

**Comment by mpost** [comment]
We have fixed the issue. Thanks for bringing it up.
