### ISSUE TITLE
Android M onRequestPermissionResult callback not being invoked in JAVA

### ISSUE THREAD

**Issue by exocom** [eclipsesource/tabris-js#898]
Just installed a plugin that has a requestPermissions check method so that the permissions can be granted for android M before attempting to use the plugin.

When using tabris the JAVA onRequestPermissionResult callback is never invoked, and in turn the context.success is never invoked. 

See offical docs for explanation
https://developer.android.com/reference/android/support/v4/app/ActivityCompat.OnRequestPermissionsResultCallback.html

**I've validated the same plugin works on vanilla Cordova Android 5.1.1 without issue.**

Here is what I've found, others had this issue, but I'm not sure where to go from here.

1 Possibly needing Android Support Library 23.3.0 or greater
http://stackoverflow.com/questions/33169455/onrequestpermissionsresult-not-being-called-in-dialog-fragment

2 Possibly related to fragments
http://stackoverflow.com/questions/32714787/android-m-permissions-onrequestpermissionsresult-not-being-called

3 Tried both runOnUI and getThread pool, no dice.
``` Java
cordova.getActivity().runOnUiThread(new Runnable() { })
cordova.getThreadPool().execute(new Runnable() { })
```

Here is the reduced version of the plugin. 
```java
class MyPermissionsPlugin extends CordovaPlugin {
    private final int REQUEST_PERMISSIONS_TRACKING_NUMBER = 59888; // Random number to track the permission request
    private CallbackContext permissionsCallback;

    @Override
    public boolean execute(String action, final JSONArray args, final CallbackContext callbackContext) throws JSONException {
        if (action.equals("requestPermission")) {
            cordova.getThreadPool().execute(new Runnable() {
                public void run() {
                    requestPermissionAction(callbackContext);
                }
            });
            return true;
        }
        return false;
    }

    public void requestPermissionAction(CallbackContext callbackContext) {
        String[] permissions = {
                Manifest.permission.READ_PHONE_STATE,
                Manifest.permission.RECEIVE_SMS,
                Manifest.permission.READ_SMS,
                Manifest.permission.ACCESS_NETWORK_STATE,
                Manifest.permission.ACCESS_WIFI_STATE,
                Manifest.permission.BLUETOOTH
        };

        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) {
            callbackContext.error("This only applies to android M");
            return;
        }

        permissionsCallback = callbackContext;
        cordova.requestPermissions(this, REQUEST_PERMISSIONS_TRACKING_NUMBER, permissions);
    }
    
    // NOTE : this method never gets invoked
    public void onRequestPermissionResult(int requestCode, String[] permissions, int[] grantResults) throws JSONException {
        // NEVER MAKES IT HERE
        if (permissionsCallback == null) {
            return;
        }
            boolean hasPermission = cordova.hasPermission(Manifest.permission.READ_PHONE_STATE);

        if (hasPermission) permissionsCallback.success("You have permission");
        else permissionsCallback.error("You've been denied by the user");
    }
}
```

**Comment by mpost** [comment]
Thanks for the research. What plugin are you actually including?

**Comment by mpost** [comment]
We have solved the issue. The result callback was not forwarded properly to the requesting plugin. Could you please try out the latest nightly builds?

**Comment by exocom** [comment]
I'll give this a try tonight and report back.

**Comment by exocom** [comment]
@mpost how do I get the nightly build for android?

**Comment by cookieguru** [comment]
@exocom Select "Nightly" for Tabris.js version in [build settings](https://tabrisjs.com/documentation/latest/build#settings).

There shouldn't be any changes on the JS side, but if you want the bleeding edge there too just update your `package.json` dependency for `tabris` to `https://tabrisjs.com/downloads/nightly/tabris.tgz`.

**Comment by exocom** [comment]
It works! Thanks!

**Comment by mpost** [comment]
@exocom Glad to hear that. Thanks for the feedback. :)

**Comment by mpost** [comment]
@cookieguru and thanks for explaining the update path
