### ISSUE TITLE
Issues rendering referenced text views with flexible width

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#901]
In the following layout there are two text views: 

* one with flexible width (rightText - `top: 10, right: 10`) 
* one referencing the edge of the first one (leftText - `left: 10, top: 10, right: [rightText, 10]`)

Symptoms:

1. Initially, right text view is not rendered at all. Rotating the device to landscape and back to portrait fixes this (partially).
2. In some cases the fix from [1] doesn't work for all items. For some cells `rightText` is not visible.
3. When leftText is too long (try changing length of `randString` to 150), right text will never get rendered, independently of whether the device was been rotated or not.

```javascript
var page = new tabris.Page({
  title: "Collection View",
  topLevel: true
});

new tabris.CollectionView({
  left: 0, top: 0, right: 0, bottom: 0,
  items: Array.apply(null, Array(100)).map(function(){
    return {
      rightText: "123", 
      leftText: randString(50)
    };
  }),
  itemHeight: 48,
  initializeCell: function(cell) {
    var rightText = new tabris.TextView({
      top: 10, right: 10
    }).appendTo(cell);
    var leftText = new tabris.TextView({
      left: 10, top: 10, right: [rightText, 10],
      maxLines: 1
    }).appendTo(cell);
    cell.on("change:item", function(widget, item) {
      rightText.set("text", item.rightText);
      leftText.set("text", item.leftText);
    });
  }
}).on("select", function(target, value) {
  console.log("selected", value.firstName);
}).appendTo(page);

function randString(x){
  var s = "";
  while(s.length<x&&x>0){
    var r = Math.random();
    s+= (r<0.1?Math.floor(r*100):String.fromCharCode(Math.floor(r*26) + (r>0.5?97:65)));
  }
  return s;
}

page.open();
```

**Comment by jkrause** [comment]
Fixed with https://github.com/eclipsesource/tabris-ios/commit/59daa0095646007771963d607416a0594ee6ddc8
