### ISSUE TITLE
strange issue with my android version test and APK

### ISSUE THREAD

**Issue by Homoola** [eclipsesource/tabris-js#903]
Hello
I met strange issue.
I Have made my code on my macBook .
when I test it with tabtisjs app for debugging it work with my motorola nexus 6 (marshmelow version 6.0.01) as expected.
but it is not working with my other phone HTC  (android 5.0.2 lollipop ).
this version use fetch to request for a Json, I have another version works for both phones but it has no http fetch (just a local json file).

I have mad an APK version as debugging version it works for the nexus v6 and not for HTC v5.
the full code is uploaded on my account on Tabrisjs portal.

kindly I need your help 

thanks in advance

![screenshot_2016-06-22-18-14-36](https://cloud.githubusercontent.com/assets/19804549/16278243/124f0660-38ae-11e6-9d59-2b22abd225df.png)
![screenshot_20160622-181907](https://cloud.githubusercontent.com/assets/19804549/16278325/6e64802e-38ae-11e6-8172-893820f77223.png)

**Comment by mpost** [comment]
Could you create a snippet that shows a fetch request that does not work on your htc device?

**Comment by Homoola** [comment]
hello, mpost 
in fact I found the problem in HTC phone language it is french 
the problem were in calling lang file :(
tanks for your  help

**Comment by mpost** [comment]
Glad you could solve the problem.
