### ISSUE TITLE
Application Icon Not Changing

### ISSUE THREAD

**Issue by wilsonna** [eclipsesource/tabris-js#905]
It has always been a hit and miss for me regarding the Application Icon. I can't seem to figure out how to change it consistently. No matter what I do, it will always remain as the previous one until one day, for reasons I've yet to figure out (could be something I've done to trigger it), it would suddenly recognise the new image. I thought that it should be as simple as replacing the image. I've tried using a different file name, changing the application version etc. Anyone else encountering this problem?

Currently, this is how my app icon is defined currently in my context.xml.

    <icon src="www/img/icon-app.png" />

**Comment by cookieguru** [comment]
Android or iOS?  See also:

https://github.com/eclipsesource/tabris-js/issues/768#issuecomment-188774085

**Comment by wilsonna** [comment]
Oops, sorry, it's Android.

**Comment by cookieguru** [comment]
Are you using `context.xml` or `config.xml`?  Do you have a a `density` paramater on each `<icon>` with mdpi, hdpi, xhdpi, xxhdpi, or xxxhdpi?

**Comment by wilsonna** [comment]
Argh, must be the lack of sleep... it's `config.xml`, not `context.xml`.

No, I do not have a density parameter. There is only one `<icon>` tag and according to Cordova's documentation (https://cordova.apache.org/docs/en/latest/config_ref/images.html), it should apply to all platforms.

**Comment by cookieguru** [comment]
It's not very clear in their docs (an unfortunate recurring trend) but I believe the density parameter being optional is just from a schema validation standpoint.  It is only used on Android and therefore cannot be considered required.
If you aren't specifying the density parameter the app isn't going to know what size the icon is, and AFAIK the device won't resize an icon to make it fit to its resolution.

Try coping the Android sample from the Cordova docs or see [`config.xml` in the tabrjs-js-template-app](https://github.com/eclipsesource/tabris-js-template-app/blob/master/cordova/config.xml) for a working example.

**Comment by wilsonna** [comment]
Hey, it worked! tabrisjs.com is still showing my old icon, but at least the icon in my device is updated. Thanks @cookieguru !
