### ISSUE TITLE
APK Size Increased by 2-3 MB from version 1.6 to 1.7

### ISSUE THREAD

**Issue by wilsonna** [eclipsesource/tabris-js#906]
I recall the file size was reduced starting version 1.4 (around 7-8 MB, #539), but it seemed to have reverted to the pre-1.4 versions where the size is around 10 MB. Was this intentional?

**Comment by mpost** [comment]
The jump in apk size stems from an updates j2v8 implementation. In the 1.6 version we were on an older v8 version (before the 4.x stream) and now we are pretty much on top of the HEAD. This increased the apk size from 2.2 to 3.7 times 2 (x86/arm).

**Comment by wilsonna** [comment]
I see, thanks for clarifying.

**Comment by natanraj** [comment]
I am doing both local & cloud build. It is in the upwards of 13MB even for just 2 pages with 1 small 300Kb image file. Any help to optimize this to 3MB etc?

**Comment by cookieguru** [comment]
If you don't need to target x86 devices you could build without the x86 binary.  Note that the ARM binary of J2V8 is 9.2 MB (3.3 packed) so a target size of 3MB is probably not attainable.  However as mentioned in #888 you could do a local build and target x86 and ARM separately which would reduce the size of each by 3-4MB.
You could also build your own [J2V8](https://github.com/eclipsesource/J2V8) binary and remove some of the features your app doesn't use.

**Comment by mpost** [comment]
As pointed out by @cookieguru the biggest size in the app comes from the j2v8 library that ships with arm and x86 binaries. You could use the cordova build to only build for one platform.
