### ISSUE TITLE
Update CollectionView on data changes

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#91]
Currently, the List widget does not detect changes to the `items` array. Even worse, when only a single element is removed from the array and the array is set again, all ListItems will be destroyed and re-created.

We should implement a mechanism to update only the affected item widgets, i.e. remove rows for deleted data items, create rows for new data items, and update rows for changed items.

One option is to add support for [Backbone collections](http://backbonejs.org/#Collection), another option could be implementing a change detection mechanism such as the one used in [d3.js](https://github.com/mbostock/d3/wiki/Selections#data).

**Comment by jkrause** [comment]
https://github.com/eclipsesource/tabris-js/issues/271

**Comment by ralfstx** [comment]
We didn't want to introduce a dependency to Backbone nor to provide a List type of our own at this point.

In order to support dynamic updates, we've implemented a low-level API to modify a CollectionView's items using the methods `insert` and `remove` (commit 27fa3bf15d5bc7be9cd8af628c35ad7911637b97).

**Comment by tbuschto** [comment]
Since we have insert/remove implemented and a separate bug for data binding (https://github.com/eclipsesource/tabris-js/issues/671), we can close this issue.
