### ISSUE TITLE
Provide an API to set fetch timeout

### ISSUE THREAD

**Issue by ifurnadjiev** [eclipsesource/tabris-js#910]
```
var start = Date.now();
fetch('http://www.eclipsesource.com:1234').then(function(){
  var end = Date.now();
  console.log("Resolved! " + (end - start) );
}).catch(function(){
  var end = Date.now();
  console.log("Rejected!" + (end - start));
});
```

The snippet above give different results on Android and iOS. On Android fetch rejects in 127 sec, on iOS is 75 sec. These numbers are reproducible all the time.

**Comment by mpost** [comment]
Is there a difference when making a direct XHR request?

**Comment by ralfstx** [comment]
Out fetch implementation doesn't set a timeout, so *No*.

See https://github.com/github/fetch/search?q=timeout

**Comment by cookieguru** [comment]
Timeout isn't in the [fetch spec](https://fetch.spec.whatwg.org/).  Additionally, it's easy to add timeout support with some straightforward wrapper code: https://github.com/github/fetch/issues/175#issuecomment-125779262

**Comment by cookieguru** [comment]
`timeout` parameter now available in [2.0.0 RC 1](https://github.com/eclipsesource/tabris-js/releases/tag/v2.0.0-rc1)  :smiley:

**Comment by mpost** [comment]
Hurray :)

**Comment by ralfstx** [comment]
Right, after wrapping `fetch` in a timeout-promise one too many times, we realized that this property is really needed.
```js
fetch(url, {
  timeout: 5000 // request timeout in ms
}).then(...);
```
