### ISSUE TITLE
I only see folder structure when accessing the local server

### ISSUE THREAD

**Issue by minagawah** [eclipsesource/tabris-js#911]
I maybe doing it wrong but I'm sure I followed exactly what it says in "Getting Started".
As I type `hs` to start the local server, opened my Chrome browser for:
http://localhost:8080/
All I see is "Index of /" followed by the actual folder structure I have for the project...
Seems like it is not even reading `package.json`.
I have "myapp.js" specified for *main* in `package.json`
which is physically there in my project folder.

Am I making mistakes?
Or, do I need some special configurations for Windows?

I am on:
Web browser: Chrome v50.0
OS: Windows 10

**Comment by cookieguru** [comment]
Tabris.js is a framework for mobile devices; there is nothing to see in a browser.  You'll want to download the Tabris.js developer app for [Android](https://play.google.com/store/apps/details?id=com.eclipsesource.tabris.js) or [iOS](https://appsto.re/de/sIsa4.i).  Ensure that your computer and device are on the same network (WiFi) and once you are signed in, navigate to the URL tab and enter the URL of your computer.

**Comment by minagawah** [comment]
Oh... I totally misunderstood.
Thanks, @cookieguru
