### ISSUE TITLE
Update documentation for tintColor

### ISSUE THREAD

**Issue by exocom** [eclipsesource/tabris-js#912]
Greetings,

1. It looks like the ImageView documentation page has an error as you can see 3 # (hashes) before tintColor. I believe this should be on a new line.

2. Also it seems tintColor doesn't work on Android 4.2.2. Can you please update the doc to reflect the min version of android required for this property, I'm going to guess it is 5.0, but i'm not sure. You have this for other properties on the widget page like borderRadius: Currently only supported on Android 5.0+.

https://tabrisjs.com/documentation/latest/api/ImageView

**Comment by cookieguru** [comment]
1. Looks like @ralfstx hasn't updated it yet.  https://github.com/eclipsesource/tabris-js/issues/876#issuecomment-224183670
2. I believe you are correct with 5.0.  https://github.com/eclipsesource/tabris-js/issues/897#issuecomment-227686800

**Comment by mpost** [comment]
@exocom You are right about point 2. We will update the docs accordingly. We are will also update the docs in accordance with the comments form @cookieguru.

**Comment by cookieguru** [comment]
Add to the list:
Unnecessary `#` prefixing rgb and rgba in the examples for Color in `doc/types.md`

**Comment by ralfstx** [comment]
@mpost the aforementioned update on Android 5.0 is still pending.

**Comment by mpost** [comment]
All documentation artifacts mentioned here have been edited. Closing for now.

**Comment by maxapps** [comment]
Documentation for **tintColor** also incorrectly states:
> Set to null to remove the effect.

Attempting this returns an error stating null is not a valid value.

Luckily, the [**ImageView tintColor** snippet](https://tabrisjs.com/snippets#imageview-tintcolor) shows that the correct method:
`widget.set('tintColor', 'initial');`

**Comment by mpost** [comment]
@maxapps Thanks for the heads up. We have corrected the docs.
