### ISSUE TITLE
[Android] Setting font to 'initial' in constructor prints warning

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#918]
Warning says "Could not create object "tabris.TextView" on tabris.TextView (Reason: Attempt to invoke virtual method 'boolean com.eclipsesource.tabris.client.core.model.Font.isBold()' on a null object reference)"

May or may not also prevent the widget from appearing on screen.

**Comment by mpost** [comment]
Fixed for the 1.9 release
