### ISSUE TITLE
TextInput auto capitalize on each word/sentence

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#919]
Is there any way to capitalize at the start of input, and potentially with each new word that is typed? This behavior is pretty normal on Android, but I don't see a way to enable it in a TextInput

**Comment by cookieguru** [comment]
The [autoCapitalize](https://tabrisjs.com/documentation/latest/api/TextInput#autocapitalize) property?

**Comment by dested** [comment]
Sorry, to clarify, I want the first letter of each word capitalized, not every letter.

**Comment by mpost** [comment]
Android has the `EditText` property `textCapSentences` that is used for such functionality. It is currently not exposed as API though. We will consider it for a future release.

**Comment by mpost** [comment]
Implemented via http://docs.tabris.com/latest/api/TextInput.html#autocapitalize
