### ISSUE TITLE
Finalize canvas

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#92]

**Comment by gosia-eclipsesource** [comment]
Would be good to support a library for maps from multiple sources other than Google Maps (already supported by the Cordova plugin) - e.g. OpenLayers, since it is based on HTML5 canvas API. Possible alternatives: Kartograph, Polymaps.

**Comment by ralfstx** [comment]
Since we have separate issues for the missing functionality, I think we can close this umbrella issue.
