### ISSUE TITLE
open event for Drawer

### ISSUE THREAD

**Issue by sand123** [eclipsesource/tabris-js#920]
I put container with some realtime data in `Drawer` - and I need to update it only when it's opened by user - it's obviously useless to do when it is collapsed.

I tried to use inherited events from `Widget` - but still missing how to do it

**Comment by mpost** [comment]
@sand123 Currently the drawer does not have an `open` event.

**Comment by mpost** [comment]
We agreed to create api with the events `open` and `close` that will be fired when the widget has reached that state.
