### ISSUE TITLE
Node module loading another module sometimes returns package.json instead of main file

### ISSUE THREAD

**Issue by cookieguru** [eclipsesource/tabris-js#921]
I'm trying to parse some HTML from a remote site and use the output to drive my app.  This works great via command-line node:
```js
var text = "<html><body><b>Hello</b>World!</body></html>";
var cheerio = require("cheerio");
var $ = cheerio.load(text);

try {
  $("b").remove();
} catch(e) {
  console.log(e.stack);
}

console.log($.html()); //Outputs "<html><body>World!</body></html>"
```
This snippet does not work in Tabris.js
```js
var page = new tabris.Page({
  title: "Cheerio",
  topLevel: true
});

var text = "<html><body><b>Hello</b>World!</body></html>";
require("tabris-js-node");
var cheerio = require("cheerio");
var $ = cheerio.load(text);

try {
  $("b").remove();
} catch(e) {
  console.log(e.stack);
}

new tabris.TextView({
  text: $.html() //Shows "<html><body><b>Hello</b>World!</body></html>"
}).appendTo(page);

page.open();
```

Calling `remove()` (or any other Cheerio function that needs to find an element) throws a TypeError with stack trace:
```
TypeError: select is not a function
    at exports.find (./node_modules/cheerio/lib/api/traversing.js:33:21)
    at module.exports (./node_modules/cheerio/lib/cheerio.js:81:18)
    at new initialize (./node_modules/cheerio/lib/static.js:26:20)
    at initialize (./node_modules/cheerio/lib/static.js:23:14)
    at ./app.js:17:2
    at Object.defineProperty.get (<anonymous>:1:1413)
    at Object.i.require (<anonymous>:1:1617)
    at g (<anonymous>:1:2993)
    at Channel.fire (./cordova.js:822:23)
    at ./cordova.js:231:49
```
`select` is indeed not a function; it's an object.  `select` is defined 31 lines above:
```js
var select = require('css-select')
```
I would expect this to be the exported interface that the `css-select` package exposes in its `module.exports`, however, it's actually the object representation of `node_modules/css-select/package.json`.  I thought this might be a problem with Apache, so I switched to `http-server` and saw the same behavior.

Interestingly, adding `DirectoryIndex index.js` to Apache config (which makes Apache serve up index.js if it exists instead of an HTML directory index) caused my app to hang at `require("cheerio");`

--

Here is the [full request log](http://pastebin.com/raw/9nR2T1PE) output from `http-server`.

Here is the `package.json` that I am using for my app:
```json
{
  "main": "app.js",
  "dependencies": {
    "cheerio": "^0.20.0",
    "tabris": "^1.8.0",
    "tabris-js-node": "^0.1.0"
  }
}
```

As a last resort I tried renaming `node_modules/css-select/index.js` to `index2.js` and modifying `node_modules/css-select/package.json` accordingly but `require('css-select')` still returns an Object representing its `package.json`.

**Comment by cookieguru** [comment]
Still seeing this issue with nightly JS and nightly Android.

**Comment by tbuschto** [comment]
Yeah, some further work on the clients is needed.

**Comment by tbuschto** [comment]
It should work now.

**Comment by cookieguru** [comment]
Confirmed, thank you!
