### ISSUE TITLE
Disposed checks may lead to unexpected results in asynchronous situations

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#922]
Currently invoking following methods on a disposed widget will throw an `Object is disposed` error: 
- `on`
- `off`
- `once`
- `set`
- `get`
- `append`
- `appendTo`
- `insertBefore`
- `insertAfter`
- Invoking widget methods interacting with the native bridge, e.g. `CollectionView.refresh()`

A common use case is to send a HTTP request, wait for the results and then modify the UI. If the user closes the page to be modified before a response is received, the HTTP request callback will try to interact with disposed widgets resulting into an exception being thrown.

Instead of throwing an exception, one could make those methods no-op instead. This would prevent having to write boilerplate app code checking whether a widget is disposed or not before using it.

**Comment by mpost** [comment]
While noop could be a viable solution that could lead to strange behaviors when you think you would `get` some value but you would actually receive `null` because you are not attached.

The described scenario is very common in mobile development. A classic solution is to decouple these async calls from the ui by the means of some event bus. The ui only subscribes to the event when it is opened and unsubscribes when diposed.

**Comment by ralfstx** [comment]
In Tabris 2.0, the methods defined on *NativeObject*, that is `on()`, `off()`, `once()`, `trigger()`, `set()`, and `get()` do not throw on disposed widgets anymore. Setting a native property on a disposed widget won't have any effect and getting a native property will yield `undefined`. This seems intuitive as a disposed widget is a "dead" object, decoupled from the native. This behavior should help with simple cases where the result of an async operation is set on a already disposed widget.

However, *Widget* methods that modify the UI tree, i.e. `append()`, `appendTo()`, `insertBefore()`, `insertAfter()`, and `detach()`, still throw errors on disposed widgets, as in these cases the application code tries to *constuct* a UI with dead widgets.
