### ISSUE TITLE
console.error() and exceptions are visualised in release builds

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#923]
If an exception is thrown or if `console.error()` is called, on both platforms a toast is shown with the message of the error/exception, regardless whether a release or a debug version of the app is built.

Per default it is expected no console output to be visualised at all .

**Comment by mpost** [comment]
Errors are not shown anymore in release builds on Android.

**Comment by mpost** [comment]
Errors are not shown anymore in release builds on Android and iOS.
