### ISSUE TITLE
Android plugin @Override onActivityResult never gets called/invoked.

### ISSUE THREAD

**Issue by exocom** [eclipsesource/tabris-js#924]
This seems really similar to a previous issue #898 

The facebook plugin https://github.com/Telerik-Verified-Plugins/Facebook is passing the current activity via cordova.getActivity() to facebook android sdk. In turn the facebook sdk is supposed to be calling the onActivityResult method on the Plugin, but it never fires.

ConnectPlugin.java line 260
```Java
@Override
    public void onActivityResult(int requestCode, int resultCode, Intent intent) {
        Log.d("Never makes it here :(");
        super.onActivityResult(requestCode, resultCode, intent);
        Log.d(TAG, "activity result in plugin: requestCode(" + requestCode + "), resultCode(" + resultCode + ")");
        callbackManager.onActivityResult(requestCode, resultCode, intent);
    }
```

**Comment by mpost** [comment]
Thanks for reporting the issue... I don't think it is quite the same thing as #898 but we would have to look at it more closely. Is the facebook sdk actively calling the activity method `onActivityResult`? or is the Android system return a value from a facebook activity?

**Comment by exocom** [comment]
I'm not 100% sure, but it looks like it gets passed around in the SDK and essentially the SDK invokes it directly.  Hopefully the code taken from the SDK below is helpful.


```java
/**
     * Registers a login callback to the given callback manager.
     * @param callbackManager The callback manager that will encapsulate the callback.
     * @param callback The login callback that will be called on login completion.
     */
    public void registerCallback(
            final CallbackManager callbackManager,
            final FacebookCallback<LoginResult> callback) {
        if (!(callbackManager instanceof CallbackManagerImpl)) {
            throw new FacebookException("Unexpected CallbackManager, " +
                    "please use the provided Factory.");
        }
        ((CallbackManagerImpl) callbackManager).registerCallback(
                CallbackManagerImpl.RequestCodeOffset.Login.toRequestCode(),
                new CallbackManagerImpl.Callback() {
                    @Override
                    public boolean onActivityResult(int resultCode, Intent data) {
                        // I'm pretty sure that at this point LoginManger.this == cordova.getActivity()
                        return LoginManager.this.onActivityResult(
                                resultCode,
                                data,
                                callback);
                    }
                }
        );
    }
```

**Comment by mpost** [comment]
@exocom We have looked into the issue but couldn't fully figure out the problem from the code above and in the plugin. If the facebook callback manager uses `activity.startActivityForResult(..)` to call some facbook sdk specific activity the return call to `activty.onActivityResult` would be properly returned to the plugin manager. If the caller calls the `activity.onActivityResult` directly it would also properly delegate to the callback manager.

The only thing that will currently not work is to directly invoke org.apache.cordova.CordovaInterface#setActivityResultCallback`. We channel the activity result from the activity to the callback a little different.

**Comment by exocom** [comment]
Just had time to look at this again today. Yes it is using cordova.setActivityResultCallback(this);

Is there a work around?

**Comment by mpost** [comment]
Current if you call `startActivityForResult(CordovaPlugin, ..)` this plugin will be the receiver of the returned value. The `setActivityResultCallback` will not be honored.

To broaden the cordova support though it makes sense to allow this alternative method as well and we will update the tabris-android platform accordingly. This change will be in after the 1.9 release though.

**Comment by mpost** [comment]
We have updated the cordova-android platform to also support the `setActivityResultCallback` Please give the nightly build a try.

**Comment by mpost** [comment]
Be aware thought that we are still on cordova-android 5.1.x which means that you can only have one concurrent request. This has changed with cordova-android 5.2.x https://issues.apache.org/jira/browse/CB-10963

**Comment by exocom** [comment]
@mpost I had a change to try this with the nightly build, but it still didn't work for me. I'm not going to have time to look back into this for awhile. When I do have time I'll try throwing it into an empty build.

Just an fyi, I'm pretty sure all my facebook setup is correct as the iOS version works without issue.

Let me know if you are able get this working as this is huge for our users! We've got a ton of people on facebook and the native login is much better than oauth. We've had to drop in the oauth version which opens a browser and then the user has to login to facebook. Its pretty ghetto but it gets us by for the short term.

**Comment by dested** [comment]
We are having the same issue with the plugin https://github.com/dariosalvi78/cordova-plugin-health. We are never getting the success callback in android where as we are in ios and non tabris android. Is this a use-case that tabris intends to support?

**Comment by gosia-eclipsesource** [comment]
@dested In general we should support this for cross-platform compatibility. We will try to give some update next week. Please stay tuned.

**Comment by mpost** [comment]
@exocom @dested We have updated the cordova integration to properly dispatch the activity result to the plugin. Please try with the latest nightly build.

We have actually used the `cordova-plugin-health` plugin to sign in with the google api client and to retrieve the current step count. The turn around worked as expected. Thanks @dested for the hint.
