### ISSUE TITLE
Provide dialogs as part of the core tabris API

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#927]
While dialogs are not as frequently used in mobile UIs as in desktop UIs, i think about every second app has at least one. IMHO using the cordova plug-in does not provide the optimal development and user experience. It's also does not provide good windows support or more complex dialogs like a menu - both of which are problems for the project I'm working on.  Implementation should be pretty simple considering much of the code already exists internally.

The cordova plugin I was mainly talking about:
https://github.com/apache/cordova-plugin-dialogs

Another plugin that provides a good menu in windows, but only HTML on other paltforms:
https://github.com/filfat-Studios-AB/cordova-plugin-context-menu/

And another that provides a menu, but it's more a picker (with check/radio boxes and "done" button) and has no windows support:
https://github.com/roberthovhannisyan/PhoneGap-Plugin-ListPicker

**Comment by tbuschto** [comment]
Possibly a dup of  #619 and/or #747?

**Comment by wilsonna** [comment]
I think that applies to the Toast plugin as well.

**Comment by sand123** [comment]
Maybe it's better to have curated list of 3rd party cordova plugins compatible with Tabris.js and provide simple API wrappers ? 

And then for every plugin in DOCS\Plugins documentation

Step 1. Add ```<plugin name="cordova-plugin-vibration" />``` to ```config.xml``` \
Step 2. Now you can use ```tabris.plugins.vibration.short()```

I tried these plugins and they work fine with Tabris.js and cloud build service

ActionSheet https://github.com/EddyVerbruggen/cordova-plugin-actionsheet
Local notifications https://github.com/katzer/cordova-plugin-local-notifications
Toast https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin
Dialogs https://github.com/apache/cordova-plugin-dialogs
Dial phone number https://github.com/Rohfosho/CordovaCallNumberPlugin

**Comment by cookieguru** [comment]
@sand123 I think that's what the [compatibility cordova](https://github.com/eclipsesource/tabris-js/issues?q=label%3A%22compatibility%20cordova%22%20) tag is for.

Agree with @wilsonna, it's another good candidate.  With #923 we know that the toast code is in the release builds and it seems suboptimal that it's necessary install a plugin to reach around to that API.

Exposing a simple dialog with `alert()` on the JS side would be a welcome improvement; it's a quick and easy to bring up a dialog.  For anything more involved (customizable title, callbacks, multiple buttons) I would say that diving in to a plugin isn't horrific.  But the status quo of having to include a plugin for _any_ type of user notification seems a little over the top.

**Comment by ralfstx** [comment]
With `AlertDialog` available in 2.0, I think we can close this issue.

Opened #1104 for toast messages. Please open separate issues for other dialogs when needed or `alert`.
