### ISSUE TITLE
Calling tabris.ui.get('textColor') generates a warning

### ISSUE THREAD

**Issue by maxapps** [eclipsesource/tabris-js#928]
In version 1.8.0, calling tabris.ui.get('textColor') works but generates a warning which states:

> Could not get property "foreground" (reason: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference)

This can be verified by console.log(tabris.ui.get('textColor'));

**Comment by mpost** [comment]
The problems originates from the fact the colors has never been set. We will return the theme colors in that scenario. Same goes for the `background` colors property.

**Comment by mpost** [comment]
We have fixed the issue for the 1.9 release.
