### ISSUE TITLE
Backendless MBAAS works with Tabris.js

### ISSUE THREAD

**Issue by maxapps** [eclipsesource/tabris-js#929]
For anyone attempting to replace Parse (or still waiting for Firebase to work), you might want to take a look at [Backendless](https://backendless.com/). I've just started messing with it but so far it seems pretty robust and all that's needed is to include a reference to the NPM module in the package.json file and then a require statement in your code.

**Comment by gosia-eclipsesource** [comment]
@maxapps We did some experimenting with Backendless too, with very good results. A blog post and a documented example is coming up soon. Please stay tuned :)

**Comment by maxapps** [comment]
That's good to hear. Please put some time into testing the ability to "remember" a user who has previously logged in. There are some problems that I haven't quite worked out but are almost certainly bugs in the node.js version of the backednless JS library. Specifically, the **Backendless.UserService.getCurrentUser()** function does not work. This understandable because it cannot be called asynchronously.

According to [this post](http://support.backendless.com/topic/current-user-returns-null-android), the proper way to handle the situation is a combination of calls to **Backendless.UserService.isValidLogin()** and **Backendless.UserService.loggedInUser()**. The isValidLogin() method appears to work (even though it is not asynchronous) but, in my limited experimentation, the loggedInUser() method returns null even after isValidLogin() returns true.

I have a couple ideas about how to get around this issue but haven't a chance to try them out yet. Looking forward to seeing what you guys come up with.

**Comment by maxapps** [comment]
Here is how I finally managed to check for a previously logged in user:

```
Backendless.UserService.isValidLogin().then(function(bValid) {
  if (bValid) {
    var sId = Backendless.UserService.loggedInUser();
    Backendless.Persistence.of(Backendless.User).findById(sId).then(function(oUser) {
      Backendless.UserService.setCurrentUser(oUser);
    }).catch(function(oError) {
      console.log(JSON.stringify(oError));
    });
  } else {
    console.log('No valid user!');
  }
}).catch(function(oError) {
  console.log(JSON.stringify(oError));
});
```
The key was to use
``Backendless.Persistence.of(Backendless.User).findById(sId)``
instead of
``Backendless.UserService.findById(sId)``
as is specified in [this post](http://support.backendless.com/topic/current-user-returns-null-android) from the backendless support forum.

**Comment by mpost** [comment]
Closing this issue for now. Feel free to reopen if you have more insights to contribute.
