### ISSUE TITLE
WebView navigate not getting called for localhost

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#930]
I have modified the oauth.io plugin to use a new page with a webview in it as opposed to window.open(...) All is working smoothly until the last step when I get this error. Oauth.io uses this final redirect to bubble the data up to whoever is calling it using something like the following on url change.

`if (url.substr(0, 17) === "http://localhost/") { 
//read url and extract data` 

Unfortunately webview.on('navigate') never gets this final call because it seems to be handled internally some other way. Is there a way to either allow the navigate to fire even in this instance, or give us some sort of error handling so I can still implement this functionality. 

![image](https://cloud.githubusercontent.com/assets/822784/16936453/9dea782c-4d1b-11e6-849b-01deb83340a8.png)

**Comment by cookieguru** [comment]
What happens when you listen with the `load` event?

**Comment by dested** [comment]
Same issue, I never get a callback for the localhost page change.

**Comment by cookieguru** [comment]
Do you have the ability to set it to a different URL?  From the Tabris.js developer app:
```js
new tabris.WebView().on("navigate", function (view, event) {
  if (event.url.indexOf("tabris-connect://authorization") === 0) {
    //...
  }
});
```
So it would seem a "valid" URL is not necessary.
I'm not seeing `tabris-connect` in `AndroidManifest.xml`, but then again I'm looking at the compiled version.

**Comment by mpost** [comment]
@dested So basically you are facing the problem that regular urls to the outside worls are intercepted by the `navigate` event but `http://localhost` is not passed to the callback?

**Comment by dested** [comment]
@cookieguru  I attempted this but it seems the oauth.io system uses localhost in a special way in code I cannot modify. When I change the redirect from localhost to something else it simply navigates to that site. It's just an implementation decision they have made.

@mpost, correct. It seems when the webbrowser navigates to a url that is connection refused it does not bubble up to tabris-js either through the navigate or load events.

**Comment by mpost** [comment]
@dested wild shoot but in tabris.js 1.10 we have introduced the `download` event. Could you try that callback?

**Comment by mpost** [comment]
I am closing this issue as resolved. @dested please reopen if the `download` event did not solve your problem or the issue persists.
