### ISSUE TITLE
Action button sometimes misplaced

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#932]
Action button is initially misplaced in bookstore demo (right margin too big). Opening and closing a page fixes its position (2nd picture).

![img_0669](https://cloud.githubusercontent.com/assets/2341769/16992272/ea3f97f0-4e9e-11e6-9cb3-b2a48d585d2c.jpg)
![img_0670](https://cloud.githubusercontent.com/assets/2341769/16992275/ec0ff566-4e9e-11e6-8014-1361743dc341.jpg)

**Comment by patrykmol** [comment]
Action is position correctly in latest 2.0 nightly.
