### ISSUE TITLE
ScrollView without explicit size scales according to its children on Android and not on iOS

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#936]
Given a `ScrollView` without `layoutData` (Tabris.js 2.x):

``` js
var scrollView = new tabris.ScrollView({
  left:0, top: 0
}).appendTo(tabris.ui.contentView);

new tabris.TextView({
  text: 'hello world'
}).appendTo(scrollView);
```

On iOS a `ScrollView` does not grow with its children.

We should bring this behavior in line.

**Comment by patbenatar** [comment]
I'm experiencing similar issues with `Composite` — when a height is not specified, on Android it will fit the intrinsic height of its contents but on iOS it will have a height of 0 and therefore its contents are invisible

**Comment by mpost** [comment]
@patbenatar The problem on `Composite` should be fixed but the problem remains on `ScrollView`.

**Comment by patbenatar** [comment]
Thanks @mpost — do you know what version it is fixed in?

**Comment by mpost** [comment]
@patbenatar I can't pinpoint a specific version but at least in the `2.0.0-beta1`.

**Comment by anthonyvespoli** [comment]
any idea when this issue will be fixed? this is a pretty annoying issue when you need to be able to dynamically append to a scroll view

**Comment by mpost** [comment]
Working as expected now. Closing as resolved.
