### ISSUE TITLE
any example for carousel ?

### ISSUE THREAD

**Issue by newhow** [eclipsesource/tabris-js#940]
I cannot figure out any tabris way to implement a carousel like http://getbootstrap.com/javascript/#carousel 

The most related example provided by tabris is "swipe to dismiss". But I am not smart enough to get a carousel work even with the help of that one.

**Comment by cookieguru** [comment]
Are you just looking to duplicate something where elements slide left and right when a certain element is tapped?
Or do you want something similar but using swiping to advance between elements?

If the first, it should be relatively easy to add a tap listener to a pair of elements that control a central element by animating `translationX`.
If the second, and you don't need wrapping, try a [TabFolder](https://tabrisjs.com/documentation/latest/api/TabFolder#tabfolder).

**Comment by newhow** [comment]
Thanks a lot. Using TabFolder is a good idea.

**Comment by natanraj** [comment]
@cookieguru When you suggest tabFolder to be used, are you expecting this tabFolder be used in 'hidden' setting and each tab content is actually a carousal type of content ?

**Comment by cookieguru** [comment]
@natanraj I could've sworn I posted this earlier this morning, but here was my idea for an example.

```js
var page = new tabris.Page({
  title: "Photos",
  topLevel: true
});

var tabFolder = new tabris.TabFolder({
  left: 0, top: 0, right: 0, bottom: 0,
  paging: true,
  tabBarLocation: 'hidden'
}).appendTo(page);

images = ['holger.jpg', 'ian.jpg', 'jochen.jpg', 'jordi.jpg', 'markus.jpg', 'moritz.jpg', 'tim.jpg'];
for (var i = 1; i < images.length; i++) {
  createTab(images[i]);
}

function createTab(filename) {
  var tab = new tabris.Tab().appendTo(tabFolder);
  new tabris.ImageView({
    centerX: 0, centerY: 0,
    image: 'https://raw.githubusercontent.com/eclipsesource/tabris-js/master/examples/animation/images/' + filename
  }).appendTo(tab);
}

page.open();
```
