### ISSUE TITLE
Allow to set an image instead of title on a Page

### ISSUE THREAD

**Issue by mknauer** [eclipsesource/tabris-js#941]
At the moment it is possible to set a string property `title` on a [Page](https://tabrisjs.com/documentation/1.9/api/Page) but it should be possible to set an `image` that is shown instead.

**Comment by maxapps** [comment]
+1

**Comment by cookieguru** [comment]
Similar to #897

**Comment by mpost** [comment]
This has been implemented for the 1.10 release.
