### ISSUE TITLE
Starting app with url e.g. Tabris Developer App with "tabris:"

### ISSUE THREAD

**Issue by mrtinb** [eclipsesource/tabris-js#942]
It would be great to be able to start the Tabris Developer App with a URL link from a mail.

Even better, support for link to app. e.g. tabris://raw.githubusercontent.com/mrtinb/test/master will load the app: https://raw.githubusercontent.com/mrtinb/test/master/package.json .

This will make it possible to share apps with a simple mail with link to download the Tabris Developer App and a text explaining to click another link in the e-mail, after the Tabris Developer App has been installed.

This way small association or small organisations can create app without the Apple Developer Fee $99/year, that might be high price for small not-profit organisations.

**Comment by mpost** [comment]
@mrtinb That is an interesting idea. At least for the dev app.

**Comment by mpost** [comment]
You could build your own app and use a cordova plugin like https://github.com/EddyVerbruggen/Custom-URL-scheme to register a custom scheme.

**Comment by ralfstx** [comment]
Since a cordova plugin exists, I think we can close this issue for now. Please reopen if anyone has a strong point for an API in Tabris.js.
