### ISSUE TITLE
Longpress event for CollectionView

### ISSUE THREAD

**Issue by sand123** [eclipsesource/tabris-js#943]
`CollectionView` should fire `longpress` event with the same listener signature like `select` event: widget, item, options

Currently, you can listen for `longpress` event on cell, but index is missing

**Comment by mpost** [comment]
You could attach the current item index to the view you are long pressing. Since it will be recycled and updated it is always up to date.

**Comment by sand123** [comment]
Sorry, I didn't get it.

```javascript
initializeCell: function(cell){
	var text = new tabris.TextView({
		layoutData: {left: 5, top: 3, right: 5, bottom: 3}
	}).appendTo(cell);

	cell.on("change:item", function(widget, item) {
		text.set("text", item);
	});

	cell.on("longpress", function(widget, gesture){
		if(gesture.state !== 'end') return;
		var item = cell.get("item")
		/*index here? */
	});
};
```

**Comment by sand123** [comment]
I didn't found any docs reference that you can get index simply by `cell.get("itemIndex")`

**Comment by cookieguru** [comment]
It's documented on [`Cell`](https://tabrisjs.com/documentation/latest/api/Cell#itemindex)
