### ISSUE TITLE
Application crash with button.on("tap")

### ISSUE THREAD

**Issue by sand123** [eclipsesource/tabris-js#945]
``` javascript
var page = new tabris.Page({
    topLevel: true,
    title: "Page"
});

var btn = new tabris.Button({
    text: "HEY!"
});

btn.on("tap", function(){
    console.log("HERE")
});

btn.appendTo(page);

page.open();
```

Crashes app on button click. 
Android 6.0.1 Sony D5803, compiled online with debug=on, 1.9.0 version

**Comment by mpost** [comment]
You are probably aware that the correct usage is `on("select")` but the crash is not desirable none the less.

**Comment by sand123** [comment]
Exactly. I was playing with some kind of `ImageButton` and listen `tap` event on `tabris.ImageView` as user interaction, than switched back to `tabris.Button` missing old event name. And bumped into this

**Comment by cpetrov** [comment]
A fix will be released with the next Tabris.js version.
