### ISSUE TITLE
Provide multi-touch and gesture API

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#95]
This is a follow-up to issue #78. 

The existing touch events are besed on mouse events. As a result, they don't bubble, don't allow for multi-touche/gesture events and don't offer "cancel" or "tap" events to recognize if an element was released outside it's bounds.

Here is a draft for "real" multi-touch events in tabris-js, inspired mostly by HTML5 (http://www.w3.org/TR/touch-events/). Changes are bold. Note that there is also a effort by MS to get their own pointer/gesture events to be standarized (http://www.w3.org/TR/pointerevents/, http://msdn.microsoft.com/en-us/library/windows/apps/xaml/hh441180.aspx#properties).

<pre>
  {
    type: "touchstart" | "touchmove" | "touchend" | <b>"touchcancel" </b>
    time: number
    <b>capture</b> : fn, // ignore other listeners for these touches
    touches : [ { x: number, y: number, <b>id: string</b> }, ... ], // <b>all touches on this widget</b>, oldset first
    <b>target:</b> widget, // See issue #93
  } 
</pre>

<b>X and Y should be relative to the current target widget</b>. 

In the first draft I had "cancelBubble", but that isn't really what we need. I propose that event's don't "bubble" like they do in HTML (the event objects have to be different for different targets anyway), but introduce a "capture" flag or function that causes all other listener to recieve a "touchcancel" and then no more events form these touches.

HTML DOM also has "changedTouches". Those are not needed since "touchstart" and "touchend" always add/remove only one touch, and that is the first/last in the touches array. "targetTouches" is also not needed sincei it's the same as out "touches" array.

In addition to these "low-level" events there are usually gesture events, however those are very differently implemented on all platforms. I suggest to introduce simple one-touch gesture events fired after a touch session, like <b>"tap"</b>, "longpress" (already exists) and <b>possibly double-top and/or fling.</b> (MS calls it "InertiaStart"). These may require some intelligence since only of of them should be fired per touch session, even if there are multiple available targets. Multi-touch gesture will very likely require a more complex API than simple listener, like gesture recognizer.

**Comment by ralfstx** [comment]
The new gesture API (#274) supports multi-touch.

**Comment by fax1ty** [comment]
> :point_right: Since multiple touches are currently not supported, the touches array always has one element.

https://docs.tabris.com/latest/touch.html#touch-events

Is this still the case? On Android, only 1 object in the array is always returned to me

**Comment by mpost** [comment]
This description is still correct 👍

**Comment by fax1ty** [comment]
@mpost Are there plans to support multiple touches in the near future? Is there any easy way to get around this restriction?

**Comment by mpost** [comment]
There is no immediate plan to support them in the next release. What is your use-case atm?
