### ISSUE TITLE
Cordova plugin with custom onActivityResult requestCode

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#950]
I am attempting to use the InAppBilling plugin (https://github.com/j3k0/cordova-plugin-purchase) for android, and it is using a custom requestCode in the onActivityResult callback. It is a random number (10001) in this case, but all that seems to be returned to the onActivityResult callback is 0. Am I missing something in the implementation? Is this plugin doing something non-standard that tabris does not support?

Any help on this is appreciated.

**Comment by mpost** [comment]
In general that should work. There were some comments on the result not being passed here: https://github.com/eclipsesource/tabris-js/issues/924. Maybe it is related.

**Comment by dested** [comment]
It does seem to be a related issue, is there a roadmap to a resolution?

**Comment by mpost** [comment]
@dested Yes. I will look into it.

**Comment by dested** [comment]
Thank you. This issue is critical to our application as we have a number of plugins we've experienced callback issues with. 

https://github.com/j3k0/cordova-plugin-purchase
https://github.com/Telerik-Verified-Plugins/Facebook 
https://github.com/dariosalvi78/cordova-plugin-health

**Comment by mpost** [comment]
@dested thanks for the pointers
