### ISSUE TITLE
Type definitions for 1.9.0

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#951]
The tabris.d.ts still shows as 1.8.0 in the 1.9.0 release.

**Comment by mpost** [comment]
@dested Thanks for the feedback. We missed to update the typescript definitions for the release. Sorry about that. We will update them asap.

**Comment by mpost** [comment]
cc @ralfstx

**Comment by ralfstx** [comment]
@dested You're referring to the comment at the top of the file, right?

    // Type definitions for Tabris.js v1.8

The typescript definitions are mostly auto-generated, only the comment has been overlooked.

**Comment by dested** [comment]
Yes, that is what I figured

**Comment by karolszafranski** [comment]
sorry I did refer to the wrong repo in the commit message
