### ISSUE TITLE
Rotation Lock in IOS9

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#952]
What is the preferred method of locking the screen rotation in IOS9?

**Comment by mpost** [comment]
@dested You could use a plugin like https://github.com/apache/cordova-plugin-screen-orientation

**Comment by dested** [comment]
My use case is not necessarily to manage orientation throughout the lifetime of the app, more to just lock the orientation initially. Is there any way to handle this from within the tabris or xcode configuration?

**Comment by patrykmol** [comment]
@dested Check out orientation section in https://cordova.apache.org/docs/pl/latest/config_ref/

**Comment by dested** [comment]
@patrykmol Thanks, but unfortunately this is not honored by Tabris as far as I can tell

**Comment by dested** [comment]
I have attempted to use https://github.com/apache/cordova-plugin-screen-orientation on IOS9 and it has no effect. Im not sure if there is something different about the way cordova is creating activities vs tabris that may cause this plugin not to work.

**Comment by patrykmol** [comment]
I will investigate this issue and let you know.

**Comment by patrykmol** [comment]
@dested Issue is now resolved in latest nightly. It works with the solution I have posted above.

**Comment by dested** [comment]
I will give it a try, thanks for your help!
