### ISSUE TITLE
Allow blocking back navigation in tabris.ui

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#954]
In android we can block block navigation by listening to the app event "backnavigation", but that doesn't work in android. Also, when we have multiple instances of the page container (what currently is tabris.ui) in tabris.js 2.0 that event may not work anymore also.

I need this for the tabris-js-remote project.

**Comment by mpost** [comment]
We have agreed that the newly introduced `NavigationView` consums the back event by default but it can be intercepted by the `backnavigation` event. 

@tbuschto Can we close this issue?

**Comment by ralfstx** [comment]
As stated before, the `backNavigation` event on `tabris.app` can be intercepted and invalidated using `event.preventDefault()`.
