### ISSUE TITLE
How to post requests with JSON to WebServices

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#957]
I am having plans of implementing a JSON object submitted to my server side. how to do this ? My understanding of Fetch / XMLHttpRequest doesn't give this a feasibility

**Comment by ralfstx** [comment]
There are plenty of examples to learn about fetch and XHR: https://www.google.com/?#q=fetch+post+json

**Comment by natanraj** [comment]
Sorry, if it is a dump question. Examples for fetch() api work in the tabris.js dev app (through scratchpad). but the same code once built on local, does it fire the request (i checked the logs in server). Am I have to do any npm install ?

**Comment by cookieguru** [comment]
`fetch` is built in to the Tabris.js JS engine.  So long as you are building against 1.7.0 or newer you will be able to use fetch without having to install anything else.

Are you receiving any JS errors in the client?  Can you add some logging to determine if the code that calls your fetch statement is actually being executed?

**Comment by natanraj** [comment]
page.on('appear', fetchProducts);

function fetchProducts(){
    textView.set("text", "To fire "+url + ''+ fetch);
  fetch(url).then(function(response) {
  return response.json();
}).then(function(json) {
    console.log(json);
  	textView.set("text", "Returned "+json.results.length);
});
} 

The above text is printed that is it going to fetch that URL.. Even seeing the 'fetch' js contents. But not going through.

**Comment by ralfstx** [comment]
The code snippet you posted looks good. But you should always add a `.catch(function(err) { ... })` statement, otherwise errors will be swallowed. This might also help track down the problem.
