### ISSUE TITLE
install of npm module "pouchdb" in ./www/node_modules results in corona build fail

### ISSUE THREAD

**Issue by oxitech239** [eclipsesource/tabris-js#958]
I've tested this twice and it appears to be non-fixable.

Fase 1 : corona build android = ok
* Install cordova
* add tarbis-android as a platform

Fase 2 : cd www/node_modules && npm install pouchdb --save
corona build now fails

I cannot find a way to have the module pouchdb compiled, tried a few things but i lack experience.

please help

JL

**Comment by cookieguru** [comment]
Tabris.js doesn't use a www folder

**Comment by dested** [comment]
I believe this is due to the fact that pouchdb has to compile binaries for it to run, which means it will only run on a desktop. Tabris.js does not support node packages that use native binaries, only pure javascript ones.

**Comment by oxitech239** [comment]
In the meantime i've found my approach to be wrong. PouchDB can be simply downloaded as a javascript library and be included as such. No need to install a module using node
