### ISSUE TITLE
Change Android desktop icon

### ISSUE THREAD

**Issue by DinHere** [eclipsesource/tabris-js#959]
Hi there. I have currently released my first app in Google Play Store using tabrisjs. My promblem is that I havent found some way to change the icon that appears on the phones' desktop.  This icon is set to a default when I click the "create app" button at "my apps" tab as you see at the sreenshots below. Do you know how can I substitute this default icon with an icon of my choice?
Thanks in advance!
![eikask](https://cloud.githubusercontent.com/assets/20650935/18086643/9b4b7b88-6eb9-11e6-91d6-1ca292f2fff1.jpg)

![screenshot_1](https://cloud.githubusercontent.com/assets/20650935/18087152/5538d11a-6ebc-11e6-8244-70a4e01e0b78.jpg)

**Comment by sand123** [comment]
Edit `cordova\config.xml` and put your icons inside `cordova` folder
More https://cordova.apache.org/docs/en/6.x/config_ref/images.html

**Comment by DinHere** [comment]
I have already icluded the icon plugin into my config.xml as you can see in the screenshots below but nothing change. What did I possibly do wrong?
![screenshot_1](https://cloud.githubusercontent.com/assets/20650935/18087956/61e1e682-6ec0-11e6-9f3e-68ae65f43f74.jpg)
![screenshot_2](https://cloud.githubusercontent.com/assets/20650935/18087958/62d8ad50-6ec0-11e6-9e63-1ce3a3fe236e.jpg)

**Comment by mpost** [comment]
As pointed out by @sand123 You have to provide the image with the correct paths.

**Comment by DinHere** [comment]
So I have to move my .png image to a specific folder? If yes,to what folder ?

**Comment by gosia-eclipsesource** [comment]
@DinHere Please create a cordova folder in the root of your app and move config.xml there. Then put your images in cordova/res/android

In your config.xml it should look like this:
```xml
  <platform name="android">
    <icon src="res/android/mipmap-ldpi/ic_launcher.png" density="ldpi" />
    <icon src="res/android/mipmap-mdpi/ic_launcher.png" density="mdpi" />
    <icon src="res/android/mipmap-hdpi/ic_launcher.png" density="hdpi" />
    <icon src="res/android/mipmap-xhdpi/ic_launcher.png" density="xhdpi" />
    <icon src="res/android/mipmap-xxhdpi/ic_launcher.png" density="xxhdpi" />
    <icon src="res/android/mipmap-xxxhdpi/ic_launcher.png" density="xxxhdpi" />
  </platform>
```

**Comment by DinHere** [comment]
@gosia-eclipsesource Issue solved thanks for your fast and accurate answer.Although for me the  "/mipap-something" direction didnt work.I got an error there so I deleted it and then the icon appeared.
Thanks for your help again :+1: :100:

**Comment by gosia-eclipsesource** [comment]
@DinHere You're welcome and congrats on your first Tabris.js app :)
