### ISSUE TITLE
GPS geolocation support

### ISSUE THREAD

**Issue by danielpclark** [eclipsesource/tabris-js#960]
I need accurate GPS location for an app.  So geolocation by IP won't do.  I see that you may use cordova plugins such as [cordova-plugin-geolocation](https://github.com/apache/cordova-plugin-geolocation).

But looking at the documentation for doing this myself is a bit vague.  It talks about building locally and requiring Xcode which I would be unable to do on my Linux system.  It also talks about a `config.xml` for including plugins.  Could this possibly be all I need to do to include the cordova plugin?  Do I need to build it myself, or map methods?  I'm under the impression that builds can be done with the press of a button.

I've got a working node.js server running with the tabris.js app working on both Android and iPhone for some simple user interaction.  How difficult would including native GPS data be?  Alternatively I could perhaps use the in-app-browser to use W3C standards of trying to access GPS data.

This is my first few days with tabris.js so some direction would be greatly appreciated.

**Comment by dested** [comment]
When trying to solve this problem for our tabris project we realized that since tabris is not using the browser to execute javascript on android, but rather a pure javascript engine, we did not have access to the normal location services. Because of this we lean on https://github.com/louisbl/cordova-plugin-locationservices for android, and cordova-plugin-geolocation for ios. This does force you to branch your code a bit based on platform, but returns reliable results on both. 

If you have any further questions let me know.

**Comment by danielpclark** [comment]
When you say "branch my code a bit".  How is that?  Is it simple like an **if** statement in the code to check for the Android OS, or is it more or less maintaining two separate code bases?

And I'm assuming by your narrow response that I'm on the right path and  the `config.xml` is where I include the dependencies.  I'm going to see if they'll work in the test apps for both OSes.  Unless you're kind enough to stop me from doing something that won't work.

**Comment by dested** [comment]
Yes just a simple if statement. Yes just the config XML changes.

**Comment by cookieguru** [comment]
To include a plugin, as dested mentioned you just add the appropriate line to your `config.xml`.  Once you've done that, you can head over to the "My Apps" section of [https://tabrisjs.com/](tabrisjs.com) and kick off a build for Android or iOS.

**Comment by danielpclark** [comment]
Thank you!

**Comment by gosia-eclipsesource** [comment]
Feel free to reopen this issue if needed.
