### ISSUE TITLE
ImageView not working with images 

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#962]
This is the sample code i took from Snippets and built on myown using Cloud Build. Only difference  i made is - the image target_200.png, is downloaded from same Snippets (https://github.com/eclipsesource/tabris-js/blob/v1.9.0/snippets/imageview-as-a-button).  I am able to see the Header -"Using an Image view as Button", but **not the image**.

_var page = new tabris.Page({
  title: "Using an image view as a button",
  topLevel: true
});

var touched = 0;
new tabris.ImageView({
  layoutData: {centerX: 0, centerY: 0},
  image: {src: "images/target_200.png"},
  highlightOnTouch: true
}).on("tap", function() {
  touched++;
  page.set("title", "touched " + touched + " times");
}).appendTo(page);

page.open();_

**Comment by cookieguru** [comment]
From [the docs](https://tabrisjs.com/documentation/latest/types#image):
> Relative paths are resolved relative to `package.json`

So in your case you'd want to change `src` to `"src/images/target_200.png"`

**Comment by natanraj** [comment]
Wow. Thanks. it helps and image is shown now

**Comment by natanraj** [comment]
Closing the issue
