### ISSUE TITLE
Barcode scanner when scanned second time (on the example) shows Cancelled

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#963]
I am testing this barcode scanner for my own purpose. Even through Dev App, the barcode scanner once scanned, shows the scanned text. When  scan again another bar code, the result shows 'Scan cancelled'.

Some inherent issue?

**Comment by dested** [comment]
If this is on Android only try using tabris nightly. They retooled the callbacks for a very specific workflow that this plugin may be using.

**Comment by mpost** [comment]
We are seeing a problem with the plugin in the latest nightly and will investigate. When using 1.9 the plugin should work.

**Comment by cookieguru** [comment]
Which versions of Tabris.js and Barcode Scanner?  Barcode scanner has been flakes in the last few versions: #841

**Comment by cookieguru** [comment]
@natanraj What version of Barcode Scanner, not Cordova (in fact you don't even need to install Cordova).  It's specified in `cordova/config.xml`.  Or if you aren't specifying a version you'll get the latest, which is [currently](https://www.npmjs.com/package/phonegap-plugin-barcodescanner) 6.0.1.

**Comment by mpost** [comment]
Some update on the barcode scanner plugin:

With the update to cordova-android 5.2.2 they have fixed a bug that allowed us enforce the min sdk version to be 16. This means that the barcode scanner plugin that wants to enforce min sdk version 15 can now be overruled. So `phonegap-plugin-barcodescanner` (6.0.2) is the one that should be used (and will be used in the Tabris.js developer app).

In addition we have fixed a bug in the tabris integration with the cordova-android platform  where the request codes were not handled correctly. (illegal request code range used by plugins, http://stackoverflow.com/a/33332468/271877)

**Comment by mpost** [comment]
We have reports of successful scans so i am closing this issue.
