### ISSUE TITLE
how not to learn TabrisJS

### ISSUE THREAD

**Issue by oxitech239** [eclipsesource/tabris-js#964]
After having spent some time in the 'Documentation' section i feel as lost as before. Here's why, i hope to reflect correctly what i've experienced.
- code style is quite liberal yet learning from snippets is not that hard
- writing code with TabrisJS may be thé fastest way to create an app
- learning TabrisJS is not just a challenge, due to the state of documentation it seems impossible
- I've built a menu with a drawer very easy but adding a switch ended in disaster for two reasons
  a) the drawer cannot be set to open from the right or the documentation is lacking
  b) how to configure a switch is completely not documented in a human readable way

I hope i don't have to abandon working with TabrisJS because i very much like the way it's conceived.

**Comment by cookieguru** [comment]
There is no option to open the `Drawer` from the right.

Can expand on what you mean by "configure a switch"?  Or provide a snippet and describe what you're trying to accomplish?

**Comment by oxitech239** [comment]
It's alright, i found it's not possible indeed. I wanted to implement a switch in the drawer which the user could flip to have the drawer op at the right. I assumed it would be handy for left-handed people.

Anyway, in the meantime i've come to understand better the available documentation but it remains a bit sparse. I'm pretty sure it's because i'm rusty on OOP terminology and such i misunderstand what is required, what is possible etc.

**Comment by oxitech239** [comment]
Do you know by any chance of  a way to make the drawer scale to it's contents ? It's massive, the width of the screen almost. I don't see how to make it more elegant/less wide.

**Comment by cookieguru** [comment]
I don't believe that's possible at the moment.  I tried the following, which had no effect on Android:
```js
drawer.set("width", 20);
```

**Comment by oxitech239** [comment]
Yeah, no effect indeed. I suppose it should be altered or so in the native bridge code.

**Comment by mpost** [comment]
You can not set the drawer `width` as of now. On Android we actually use some calculation to find the optimal size in accordance with the material design guidelines.

https://material.google.com/patterns/navigation-drawer.html#navigation-drawer-specs

The same is not true for the dev console which has a hard width atm (we should make that more flexible as well).

**Comment by gosia-eclipsesource** [comment]
Hi @oxitech239, sorry that you had bad experience with the docs. As @cookieguru said it's not currently possible to scale the drawer. I opened an issue for that: #965.

By the way, we also have a [Getting Started ebook](https://tabrisjs.com/downloads/ebook/tabrisjs-1.9.pdf) that shows you how to build a simple app. It's more detailed than the quick getting started in the docs and it will introduce you to app structure, modules, deployment etc. If you have more questions always feel free to open issues here on GitHub.

**Comment by oxitech239** [comment]
Thanks. In the meantime i've built a basic app, with drawer. 

Most of my 'challenges' come from a lack of experience with JavaScript. I've downloaded the ebook as a PDF and it did prove somewhat helpful. The available API documentation is mostly a single level reference. While the provided examples and snippets provide some depth to a novice like me.

I expect to use the app i'm writing as a way to maybe document some of the challenges i faced and share this information as something of a tutorial.

**Comment by mpost** [comment]
Closing this for now. @oxitech239 Feel free to reopen this issue or create new ones if questions arise.
