### ISSUE TITLE
Enable scaling the drawer to its contents

### ISSUE THREAD

**Issue by gosia-eclipsesource** [eclipsesource/tabris-js#965]
As requested in #964. The drawer is quite wide and stays the same regardless of the contents. It would be good to be able to scale it down.

**Comment by oxitech239** [comment]
request to have the drawer targettable as left - right - up - down

**Comment by cookieguru** [comment]
Note that all of the above requests can already be achieved with Composite widgets.  See [Tray in the animation example](https://github.com/eclipsesource/tabris-js/blob/master/examples/animation/tray.js) for implementation.

**Comment by oxitech239** [comment]
thanks, that i missed completely
