### ISSUE TITLE
target a website instead of an app

### ISSUE THREAD

**Issue by oxitech239** [eclipsesource/tabris-js#966]
Dear,

I'm looking to have single code base run as a website as well. This does not seem to work with TabrisJS but does (supposedly) work with Cordova. I've searched for documenation on what is required to do such with Cordova/TabrisJS  but seem to be lacking resources. Is this at all possible ? Would it run on any browser ?

**Comment by cookieguru** [comment]
This is currently not possible.  However it is technically feasible; see my comments on #961 for a similar question.

**Comment by oxitech239** [comment]
Thanks. It's a shame really since it breaks the promise of TabrisJS extending Cordova.

On a positive note. Given i'm not at all used to writing code i came to writing a simple app in about two days. Though at first it's looking for the forest by staring at the trees once it catches on TabrisJS is one powerfull framework. It needs some polish but it's worth sticking around thus far.

**Comment by oxitech239** [comment]
Ah, just reviewed the issue referenced. I'll have a look using NPM.

For the moment it's a bit confusing since i installed TabrisJS using NPM and now i'm pointed back to NPM on a functionality which is not there but is feasible. I've tried --serve but that's not working for now. 

I asusme all it takes reconfiguring a copy of the code to work with an index.html pointing at the .js code.

**Comment by oxitech239** [comment]
unfortunately i'm just a guy, i lack funding to subscribe to the 'organization plan'

**Comment by cookieguru** [comment]
If you're just going to be adapting the JavaScript written for the Tabris.js JavaScript framework in to HTML there's nothing that says you'll need an Organization plan.  All the JS code is open source.

**Comment by mpost** [comment]
Closing this for now. Feel free to reopen if additional discussion is required.
