### ISSUE TITLE
offline / online event

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#967]
Do we have offline / online event triggers when the mobile Data network goes off and on ?

**Comment by sand123** [comment]
Use this cordova plugin https://github.com/apache/cordova-plugin-network-information
Plugin provides online / offline events and current connection type enum `navigator.connection.type` as NONE, WIFI, 4G, etc. - see docs

**Comment by natanraj** [comment]
Hi. Thanks. But the eventListners are for document.addEventListeners, which are more DOM based. How can we do this for tabris like native ?

`document.addEventListener("offline", onOffline, false);`

**Comment by mpost** [comment]
@natanraj Tabtris.js provides the DOM event API so if the plugin fires the events correctly it should work as described.

**Comment by natanraj** [comment]
Wow. Great. It works
