### ISSUE TITLE
Tabris launch screen shown when not overridden

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#968]
If launch screens are not overridden in `config.xml`, the default Tabris.js launch screens are shown. 

This is not expected for production apps and the default configuration should be suitable for production.

**Comment by patrykmol** [comment]
I would say this is more of a build service problem than platform. Also it could be considered as a programming error on the developer side.

**Comment by mpost** [comment]
https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-splashscreen/

**Comment by ralfstx** [comment]
Every app must override launch screens / icons. We should leave a pointer to the list of resources to replace in the build documentation.

**Comment by mpost** [comment]
Closing as resolved.
