### ISSUE TITLE
Implement proxy.once

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#97]
There are many cases where the developer is only interested in the next event that will be fired, like finishing an animation or the first appear event. We should support a backbone-like "once" method for this.

(NOTE: Originally I proposed to use Promise for this, but my research indicated that no one uses promises in this general way. Usually a promise is only returned for specifically asynchrouneous operations or "thenable" objects, not any random event.)

**Comment by ralfstx** [comment]
Implemented in 2dbfa07ad57d0f62f48b5369ac82865c121ca9ef.
