### ISSUE TITLE
Tap on TextView with highlightOnTouch is flakey 

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#970]
`new tabris.TextView({
            highlightOnTouch: true,
            alignment: 'center',
            font: '16px',
            text: 'Tap to Select'
        }).on('tap',
            (widget, item) => {
            })`

Quite often if you tap this too quickly, you will get the "highlight on touch" animation, but no tap fired. Should I be using touchEnd so that if one fires the other will definitely fire, or is this a bug with tap?

**Comment by cookieguru** [comment]
Android or iOS?

**Comment by mpost** [comment]
What android version are you seeing that on?

**Comment by dested** [comment]
Marshmallow on a Nexus 5X. What is happening is I very quickly tap the TextView. I am getting the appropriate ripple, but my tap event never fires I assume because it did not meet the criteria for a "tap" (too short?). While I understand, it is not the desired behavior as the user assumes the action has occurred. I assume this is because ripple happens on touchstart and the tap does not. 

Any recommendation on how to remedy this?

**Comment by mpost** [comment]
i just made an experiment with the emulator and clicking with the mouse very rapidly... i do get all the tap events even when clicking very fast and the ripple does its thing as well (android 7).

Do you get no tap at all or are just some dropped?

**Comment by dested** [comment]
Some are dropped. It seems to be much harder to execute in the emulator than on a real device. I now believe what is actually happening isn't related to time of tap, but rather a slight movement in the touch potentially causing it to be a very slight fling instead of a tap. Perhaps adding more leniency to tap is the right approach.

**Comment by mpost** [comment]
@dested The tap that we send is the confirmed tap after the user let go. You could be right about the timing. You could however use the [touch events](https://tabrisjs.com/documentation/latest/touch#touch-events). These are the uninterpreted "raw" events.

**Comment by mpost** [comment]
Closing this for now. @dested Feel free to reopen if you still have issues.
