### ISSUE TITLE
Improve console.log for objects

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#971]
This is kind of a long standing bug, but it should be noted that if you console.log an object, it does not automatically "stringify" the way it does in the browser. This is a problem both in tabris console as well as when using chrome inspector to connect to the cordova application.

Platform: Android
Tabris: nightly

**Comment by mpost** [comment]
@dested Agreed. The "stringification" you see in the browser has to be done "manually" by tabris. It is not provided by v8.

**Comment by dested** [comment]
Ideally, any array or object that gets passed to any console arguments would be stringified, maybe even with '\t' passed as the third argument. The issue you're going to run into is circular references crashing the traditional JSON.stringify. This would also be extremely helpful in the chrome inspect debugger, as 90% of the results just show up as [Object].

**Comment by mpost** [comment]
Circular dependencies is indeed an area where even chrome cuts off. The output given to the chrome debugging tools is actually not the same as the one printed in the dev console. @irbul correct me if i am wrong. We could at least use the same stringify implementation for console and chrome debug tools but i guess that there is more to the chrome debug tools than just stringify.

**Comment by dested** [comment]
While there is more to it, the simple stringify would help a tremendous amount. The circular reference would just need to cut off at the point that it's noticed, the hard part is determining that in an efficient way.

**Comment by ralfstx** [comment]
When calling `console.log` or `console.error` with an `Error`, Node.js prints the stack trace (available in `error.stack`) instead of just the error message:
```
> console.error(new Error('bang'))
Error: bang
    at repl:1:13
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:513:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
```
If the Tabris clients could do so as well, that would be helpful. As an additional improvement, the error toast should only contain the `error.message` (the first line of the stack trace).

**Comment by ralfstx** [comment]
I'd suggest to do wrap the native console in JS and handle stringification in a single place for all platforms.

**Comment by ralfstx** [comment]
Right, this issue is now tracked by #1459. Thanks @cookieguru.
