### ISSUE TITLE
collectionview is stuttering

### ISSUE THREAD

**Issue by oxitech239** [eclipsesource/tabris-js#972]
The collectionview i'm using is almost op copy off the code as presented on the website.

Now i've come to test the APK generated on my tablet which is quite powerfull. The images are admittedly high-res yet black and white, still when sliding the slide seems to stutter. As the image is not or repeatedly redrawn, or at least it appears so. Given the images are not displayed full size i assumed the image would not consume as much resources as when displaying higher resolution.

What is the way to go for testing here ? Is the stuttering a known issue ?

**Comment by mpost** [comment]
We are using picasso for image loading. If you load very large images these images could get evicted from the cash when a new smaller version is requested.

**Comment by gosia-eclipsesource** [comment]
@oxitech239 Regarding testing, you can use Android SDK platform-tools to measure UI performance:
https://developer.android.com/training/testing/performance.html

**Comment by oxitech239** [comment]
Superb, thanks, i'll see what i can make from this. I planned on including multiple image resolutions anyway.

What is picasso ?

**Comment by oxitech239** [comment]
The image size is about 2400x1500 pixels

**Comment by mpost** [comment]
Picasso is a library for image loading: http://square.github.io/picasso/

**Comment by cookieguru** [comment]
Note also that on Android the CollectionView is implemented as a [RecyclerView](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.html) which means the cells are getting reused and the content is recreated as the data comes in to view.

**Comment by oxitech239** [comment]
Thanks, i assume this may explain the 'stutter' or recreate/redraw of the images

**Comment by mpost** [comment]
Closing as "resolved".
