### ISSUE TITLE
Repeat animation forever

### ISSUE THREAD

**Issue by sergioradovcic** [eclipsesource/tabris-js#973]
Is there a way to repeat an animation indefinitely? I tried a very large number but it seems to crash immediately on iOS. It would be nice to be able to pass something like -1 to have it repeat forever.

**Comment by mpost** [comment]
That is a valid request. What number did you use on iOS?

**Comment by dested** [comment]
I think the number used was like 100000. It locked up the UI initially and I am not certain why as it doesnt on Android.

**Comment by mpost** [comment]
Ok thanks for letting us know. @patrykmol is there a hard limit on the repeats?

**Comment by patrykmol** [comment]
None that I know of. I will investigate this.

**Comment by patrykmol** [comment]
@sergioradovcic Can you provide a snippet that reproduces this bug?

**Comment by peeeeeter** [comment]
Any progress on this feature?

**Comment by mpost** [comment]
@patrykmol Could you investigate what happens with the 100000 repeats?
