### ISSUE TITLE
[Android] : Preferences Not Available to Plugins

### ISSUE THREAD

**Issue by 509dave16** [eclipsesource/tabris-js#974]
I have been attempting to use the cordova-plugin-code-push alongside tabris-android. Unfortunately the "codepushdeploymentkey" preference along with other preferences are not being parsed/passed to the plugin during initialization. The debug logging statements below demonstrate what is happening:

```
09-11 05:17:38.153  6517  6517 D logging preferences parsed: {loglevel=DEBUG, codepushdeploymentkey=lhZoVI0z5UWn3GKr6O2_ROTUy-wYVyFgmvTob} 

09-11 05:17:38.450  6517  6517 D logging preferences passed to appView.init: {loglevel=DEBUG, codepushdeploymentkey=lhZoVI0z5UWn3GKr6O2_ROTUy-wYVyFgmvTob}

09-11 05:17:38.450  6517  6517 D logging preferences received in CordovaWebViewImpl.init: {loglevel=DEBUG, codepushdeploymentkey=lhZoVI0z5UWn3GKr6O2_ROTUy-wYVyFgmvTob}

09-11 05:17:39.010  6517  6517 D logging preferences received in to TabrisWebView.init: {}

09-11 05:17:39.010  6517  6517 D logging preferences received in CordovaWebViewImpl.init: {}
```

My assumption is that the TabrisActivity.java, which I don't have access to, is not parsing and passing the preferences to plugins that are being initialized. I would appreciate any advice you can give me regarding this, if you are unable to make the preferences available to plugins in a pr.

**Comment by cookieguru** [comment]
Tabris.js has the built-in ability to [patch your app](https://tabrisjs.com/documentation/latest/patch).  Is there something specific in the `cordova-plugin-code-push` plugin that Tabris.js doesn't provide?

**Comment by 509dave16** [comment]
@cookieguru The following Android preference in my config.xml is not made available to the plugin "cordova-plugin-code-push", which depends on the CodePushDeploymentKey preference.
```
   <platform name="android">
        <allow-intent href="market:*" />
        <preference name="CodePushDeploymentKey" value="<my deployment key>" />
    </platform>
```
When Plugins are instantiated by the PluginManager in Java, they receive a WebView with a getPreferences method that returns CordovaPreferences, which should contain a HashMap of all the preferences. However the TabrisWebView as shown above does not have access to any preferences. The CordovaPreferences that is passed in has an empty HashMap, which I logged using a statement like this:
```
Log.D("logging preferences ...", preferences.getAll().toString())
```

**Comment by cookieguru** [comment]
@509dave16 That's not what I asked.
> Is there something specific in the `cordova-plugin-code-push` plugin that Tabris.js doesn't provide?

**Comment by 509dave16** [comment]
@cookieguru My apologies for initially misinterpreting the questions you asked. After reading over Tabris.js Patching in contrast to CodePush, I think that Tabris.js falls short in not providing a service that does the following:
1) Diffs your cordova/www files to determine the only files that need to  be a part of a Patch
2) Provides a release mechanism to release the changed files to somewhere in the cloud
3) Provides a client mechanism to Patch  the app files if a new release has occurred otherwise do nothing

Essentially, CodePush handles a lot of the tasks that you would normally have to do yourself when doing Patching with Tabris.js .

**Comment by cookieguru** [comment]
@509dave16 You are absolutely correct; Tabris.js is not a hosting platform.  However, assuming you are able to provide the hosting, I believe Tabris.js' built-in functionality can solve all the other scenarios.

To give an implementation example, you might store a version number inside the app, for example `1.0.1`.  Upon launch, the app can [fetch](https://tabrisjs.com/documentation/latest/w3c-api#fetch) a remote document to determine the most up-to-date version of the code.  If the client has a copy that is older than what that document specifies, then it would call the `installPatch` method.  This would actually be a lot faster than CodePush's methodolgy of running a diff on every single file in your app.  Additionally it provides extra functionality in that you could theoretically patch one of your JavaScript dependencies in `node_modules`.

For more background on patching in Tabris.js check out [this blog post](http://eclipsesource.com/blogs/2015/07/29/patching-mobile-apps-in-tabris-js/).

**Comment by 509dave16** [comment]
@cookieguru Thanks for the example! I was starting to think along those same lines. I will have to explore Tabris.js patching some more. Appreciate the time you took today to address my issue.
