### ISSUE TITLE
Android cordova callback issue in nightly with facebook4

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#975]
https://github.com/jeduan/cordova-plugin-facebook4

So while nightly fixed many edge cases regarding callbacks to the cordova plugin, I found an instance that no longer works. Login with facebook using the above plugin never fires the callback. In doing some research I have found the following that I hope will help debug

CordovaInterfaceImpl.java -> Line 51
            int originalRequestCode = requestCodes.get( requestCode );
            activity.getWidgetToolkit().getRequestCodePool().returnRequestCode( requestCode );
            activityResultCallback.onActivityResult( originalRequestCode, resultCode, intent );

It makes it here with requestCode = 64206, which is the code that the plugin is anticipating. originalRequestCode is then set to 0, which when passed to facebook it simply ignores.  

When control is given back to the tabris app, if I click the facebook login button again I get the following error: "The request code pool already contains code 64206" and the restarts. Upon restarting I get the same error message again and the app seems to crash.

Please let me know if there is any more research I can do on the matter.

**Comment by mpost** [comment]
Interesting. That is correctly debugged.

We made changes to that part where we use a different request code than what is original used by the plugin. The reason for that is that our TabrisActivity extends the `AppCompatActivity` from the support library that does only allow the lower 8 bits to be set in the request code where as the regular `Activity` that is used by cordova does not make that check.

That being said, could it be that the facebook app/framework hangs on to the same request code that it received the first time?

We could remove the hard check on the `returnRequestCode` method but we should try to narrow down what is really going on.

**Comment by dested** [comment]
Digging deeper, facebook sdk has this crazy callback manager class:
https://github.com/facebook/facebook-android-sdk/blob/master/facebook/src/main/java/com/facebook/internal/CallbackManagerImpl.java

They're registering a callback with this manager with a request code, in the case of login 64026. OnActivityResult passes the request code straight through to this:
```callbackManager.onActivityResult(requestCode, resultCode, intent);```

Since the request code no longer matches what they initiated it is not finding it in the Map of callbacks, and simply invoking nothing. 

Hope this helps. While this probably isn't the most common usecase, it is a pretty pervasive plugin in the mobile ecosystem :-/

**Comment by mpost** [comment]
Thanks for looking into that again. We will have to experiment with the plugins ourselfs to fully see what the flow is. Since it would work with regular cordova we are very anxious to also make it work with tabris.

**Comment by dested** [comment]
Hey guys, just pinging for an update on the timeline for this issue. Is it anticipated that it will roll into an upcoming nightly build?

**Comment by mpost** [comment]
Sorry haven't delved deeper into it yet. It is still on our list though.

**Comment by dested** [comment]
Just looking for an updated timeline on this. With the release of 1.10 I was disheartened to see this still broken. I am experiencing issues with about 1 in 10 cordova plugins.

**Comment by mpost** [comment]
@dested Thanks for the heads-up. Unfortunately you are right about the bug not being fixed in the 1.10 release.

But on a high note... the bug has been fixed in the latest nightly build. :) Please give nightly (1.11) a try a let us know if it works for you. 

On a technical note you were right about your previous observations of the way that the facebook plugin sidetracks the cordova mechanism to start another activity. We have adjusted our integration accordingly, which will also benefit other plugins that have a similar implementation.

**Comment by dested** [comment]
**Incredible.** All the plugins I had issues with now work flawlessly. This is a huge milestone for tabris in my eyes. We currently have 31 cordova plugins in our app that all now work without issue. Thank you for the incredible support. I feel confident enough to close this issue.

**Comment by mpost** [comment]
@dested We are happy to hear that. :) Care to share what app you are working on?

**Comment by cookieguru** [comment]
@dested Also the list of _31_ working plugins would be awesome!

**Comment by dested** [comment]
We are working on STYR Labs, a nutrition and wearable company. 

https://itunes.apple.com/us/app/styr/id1106975895?mt=8
https://play.google.com/store/apps/details?id=com.styr.app&hl=en
https://styr.com/


com.adjust.sdk
com.batch.cordova
com.hutchind.cordova.plugins.streamingmedia
com.litekey.cordova.plugins.heartbeat
com.oauthio.plugins.oauthio
com.plotprojects.cordova
com.xmartlabs.cordova.market
cordova-custom-config
cordova-plugin-android-permissions
cordova-plugin-bluetoothle
cordova-plugin-compat
cordova-plugin-datepicker
cordova-plugin-device
cordova-plugin-dialogs
cordova-plugin-facebook4
cordova-plugin-geolocation
cordova-plugin-globalization
cordova-plugin-health
cordova-plugin-inappbrowser
cordova-plugin-intercom
cordova-plugin-listpicker
cordova-plugin-locationservices
cordova-plugin-network-information
cordova-plugin-screen-orientation
cordova-plugin-spinner-dialog
cordova-plugin-whitelist
cordova-plugin-x-socialsharing
cordova-plugin-x-toast
es6-promise-plugin

**Comment by mpost** [comment]
@dested Ah yeah sorry... You mentioned the app already. Great work. Looks really pleasing. :)

**Comment by ethanj** [comment]
@mpost 

We are having this same issue with 1.10.0. We are not ready to upgrade to 2.0, so how do I get the mythical v1.11?

**Comment by cookieguru** [comment]
@ethanj On tabrisjs.com under My Apps, select the app and head to the Settings tab.  In the General section, set "Tabris.js Client Version" to nightly.  While it is probably not needed for this specific issue, you'll want to update your `tabris` JS dependency as well.  Instead of specifying a semver string in `package.json` pop `https://tabrisjs.com/downloads/nightly/tabris.tgz` in there instead.

**Comment by ethanj** [comment]
@cookieguru 

We are using cordova , not the tabrisjs.com online app builder, so I need a link to the tabris download for the android and ios platforms. I tried https://tabrisjs.com/api/v1/downloads/latest/android but that is now giving us the 2.0 version.

**Comment by mpost** [comment]
@ethanj You can get all previous version in the archive: https://tabrisjs.com/download/archive

**Comment by ethanj** [comment]
@mpost The archive only has v1.10.0 which apparently does not contain the fix discussed. It seems I need v1.11 , which was perhaps a nightly build, but in either case is not in the archive.

**Comment by mpost** [comment]
@ethanj oh sorry. switching to `nightly` as [suggested by cookieguru](https://github.com/eclipsesource/tabris-js/issues/975#issuecomment-279874214) will give you the nightly builds for the 1.x stream.

**Comment by cookieguru** [comment]
@mpost How would @ethanj acquire 1.x nightly for the Android and iOS platforms for doing a local build?

**Comment by mpost** [comment]
@cookieguru You are right. We should advertise the nightly platform builds on the website as well. Atm you  can get them here:

- https://tabrisjs.com/api/v1/downloads/nightly/android
- https://tabrisjs.com/api/v1/downloads/nightly/ios

**Comment by mpost** [comment]
Similarly you can get the 2.x nightlies here:

- https://tabrisjs.com/api/v1/downloads/2.x-nightly/android
- https://tabrisjs.com/api/v1/downloads/2.x-nightly/ios

We should update the "nightly" link in the previous post to be "1.x-nightly" in the future.
