### ISSUE TITLE
Is WebRTC supported?

### ISSUE THREAD

**Issue by ohenepee** [eclipsesource/tabris-js#976]
I would like to build an app that uses Webtorrent [nodejs modules]... but I'd first of all want to know if the appropraite Web API for this is supported before I get started with Tabris

**Comment by cookieguru** [comment]
https://tabrisjs.com/documentation/latest/w3c-api

**Comment by ohenepee** [comment]
Thanks... its not supported

**Comment by oxitech239** [comment]
Sorry to intrude on this already closed thread. Is webrtc not entirely browser-based ? Adding a javascript would permit handlig webrtc though it would not be taken into account by TabrisJS since it is not supported. But one may effectively make use of webrtc this way. Or not ?

**Comment by dested** [comment]
No, webrtc requires a special form of communication that the browser engine facilitates. This communication protocol would have to be implemented in tabris.

**Comment by mpost** [comment]
As already said before it is not implemented in Tabris.js. Support for it would need to be provided in a native form on the clients (probably by some third party library).
