### ISSUE TITLE
Add possiblility to control Button left/right native padding

### ISSUE THREAD

**Issue by ifurnadjiev** [eclipsesource/tabris-js#978]
We are currently implementing a custom keyboard where the text in the buttons is just a single letter or image. For small in width devices (iPhone 4 with 340 in width) the text in the buttons (even it's just a single letter) is cut-off, because the native padding from left/right is too big.

**Comment by mpost** [comment]
Padding is on our list of features. Closing this one as a duplicate of https://github.com/eclipsesource/tabris-js/issues/1017
