### ISSUE TITLE
Cordova With TabrisJS Subsequent Camera Plugin Calls Fail

### ISSUE THREAD

**Issue by jokorivai** [eclipsesource/tabris-js#979]
Sorry for my English.
I have tested Cordova with TabrisJS and they worked as expected. Now I'm facing problem that `cordova-plugin-camera` only works at first call to `navigator.camera.getPicture(onSuccess, onError, Options);`. Subsequent calls always fail with _Camera cancelled_ during app lifecycle. Closing the app (not pausing) and reopen it brings the plugin to work, but again, fails on subsequent call. No error log found when using Chrome Remote Debugging.
I also tested this plugin with several HTML5 frameworks (Onsen UI, Phonon, plain html+js) without TabrisJS  and they worked succesfully, so I'm pretty sure this is TabrisJS issue.
I'm requesting advice on this.

Project Specs:
Cordova 6.3.1 with TabrisJS 1.9, cordova-plugin-camera 2.3 (the only plugin used), camera permission (not necessary though).
My JS Code:

`var page = new tabris.Page({`
`  title: 'Example App',`
`  topLevel: true`
`});`
` `
`var button = new tabris.Button({`
`  centerX: 0, top: 10`,
`  text: 'Snap a Pic!'`
`}).appendTo(page);`
` `
`var textView = new tabris.TextView({`
`  id: 'txtView',`
`  centerX: 0, top: [button, 50],`
`  font: '24px'`
`}).appendTo(page);`
` `
`var img = new tabris.ImageView({`
`	id: "imgFoto",`
`	background: "rgb(220, 220, 220)",`
`	scaleMode: 'fit',`
`	image: {src: 'images/001.jpg', scale: 1},`
`	layoutData: {left:10, top: '#txtView 10', right:10, height:200}`
`}).appendTo(page);`
` `
`button.on('select', function() {`
`  navigator.camera.getPicture(function onSuccess(uri) {`
`		img.set('image', {src: uri, scale:1});`
`		textView.set('text', uri);`
`	}, function(msg){`
`		textView.set('text', 'Cancelled...');`
`	}, {`
`		targetWidth: 1024`
`		, targetHeight: 1024`
`		, destinationType: window.Camera.DestinationType.FILE_URI`
`		, sourceType: Camera.PictureSourceType.CAMERA`
`		, encodingType: Camera.EncodingType.JPEG`
`		, cameraDirection: Camera.Direction.BACK`
`		, quality: 80`
`		// , allowEdit: true`
`		// `
`	});`
`});`
` `
`page.open();`

Please help me. Any recomendation and suggestion are welcome. Thank you.

**Comment by mpost** [comment]
Thanks for your detailed description. We made some changes in the cordova integration recently. These improvements are available in the nightly build when you build on tabrisjs.com. Could you try to run your snippet against the nightly?

**Comment by jokorivai** [comment]
Thank you @mpost  I'm going to test it now. Be back soon to report.

**Comment by jokorivai** [comment]
I built the code using TabrisJs online build. Apk generated but not camera plugin available.
I'm figuring out how to add plugin to online build service.

**Comment by gosia-eclipsesource** [comment]
@jokorivai You need to add the plugin in your `config.xml`.

Example:

```xml
<?xml version='1.0' encoding='utf-8'?>
<widget
    id="my.first.app"
    version="1.0.0"
    xmlns="http://www.w3.org/ns/widgets"
    xmlns:cdv="http://cordova.apache.org/ns/1.0">
    ...
  <plugin name="cordova-plugin-camera" spec="1.2.0" />
  <plugin name="cordova-plugin-dialogs" spec="1.1.1" />
</widget>
```

**Comment by jokorivai** [comment]
Thankyou.
I did that but the build failed. I tested several times and couldn't get it work.
Back to local build, I replace cordova-plugin-camera with cordova-plugin-nativecamera (not wezka's fork) and it works.
