### ISSUE TITLE
phonegap barcode scanner build issue

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#984]
Getting this error when I started using PhoneGap barcode scanner since today on **Cloud build**.
 ? I could resolve this in local by forcing minSdkVersion to 16. 

But in CLoud build - Any help on how to fix this?

_uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [com.eclipsesource.tabris:tabris-android-launcher-js-utils:1.0.0] /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build/intermediates/exploded-aar/com.eclipsesource.tabris/tabris-android-launcher-js-utils/1.0.0/AndroidManifest.xml_

**Comment by cookieguru** [comment]
Are you building against nightly?  https://github.com/eclipsesource/tabris-js/issues/963#issuecomment-246394777

**Comment by natanraj** [comment]
still getting failure after adding the spec. Am I missing something 
**<plugin name="phonegap-plugin-barcodescanner" spec="6.0.2"></plugin>**

**Comment by cookieguru** [comment]
@natanraj Use the `version` attribute:
```xml
<plugin name="phonegap-plugin-barcodescanner" version="6.0.2" />
```

**Comment by natanraj** [comment]
Still getting the same error. Below are my plugins.. Not used anything outside these....
`<plugin name="cordova-plugin-whitelist" spec="1" />
    <plugin name="phonegap-plugin-barcodescanner" version="6.0.2"></plugin>
    `

**Comment by mpost** [comment]
@natanraj as pointed out before you have to build against nightly to circumvent the barcode scanner min sdk requirement.

**Comment by natanraj** [comment]
Nightly of Tabris.js or phonegap ? Can you please help how to do it ? (Somewhat new to this CI)

**Comment by mpost** [comment]
@natanraj when building on Tabrisjs.com you have to select "nightly" in the dropdown box of your targeted tabris.js client version. This will use the latest nightly cordova platform version that is able to cope with the min sdk version.

![image](https://cloud.githubusercontent.com/assets/73655/18829411/69d9b05a-83dc-11e6-9b4f-e9c4fbfd106b.png)

**Comment by natanraj** [comment]
Cool. Thanks. this resolved my issue
