### ISSUE TITLE
Question - On local notifications

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#987]
Planning to give a Local Alert to user from the App. I earlier heard of local-notifications plugin from Cordova. (cordova-plugin-local-notifications)

Is there any better alternative to this ? (I am planning to show reminders... My vision is to show it as a Big Panel on the UI when the time for reminder is come.. But I guess local-notification will only show on StatusBar type notifications)

**Comment by cookieguru** [comment]
Can you expand on what you mean by "a Big Panel"?  Perhaps you're referring to [Heads-up notifications](https://developer.android.com/guide/topics/ui/notifiers/notifications.html#Heads-up)?

**Comment by natanraj** [comment]
You are almost bang on.. Yes.. this can somewhat meet my purpose. Any guess which cordova plugin / tabris module can help me ?

**Comment by cookieguru** [comment]
Looks like the aforementioned plugin might do the trick
https://github.com/katzer/cordova-plugin-local-notifications/issues/339

**Comment by natanraj** [comment]
I guess it is not impleted  #https://github.com/katzer/cordova-plugin-local-notifications/issues/1044

**Comment by natanraj** [comment]
Closing this.

**Comment by natanraj** [comment]
@cookieguru  http://microsoft.github.io/ace/ is a native widget type plugin on Cordova. I am going to try this. Anyone have tried this earlier.
