### ISSUE TITLE
Question - Best Plugin for Push notification

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#989]
I have gone through quite amount of past issues on Push Notification. Unable to finalize which is good. Is phongap-plugin-push uses webview ?
I am unsuccessful with this so far.

 May you suggest one good plugin for push notification compatible with our tabris.js . yes. it is our tabris.js :-)

**Comment by mpost** [comment]
You could try https://github.com/eclipsesource/phonegap-plugin-push which we have forked for some minor fixes.
