### ISSUE TITLE
Provide a tabris CLI

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js#990]
A CLI could be used to:
### init a tabris project
- could delegate to yeoman
### start an application (serve files and folders)

In contrast to an HTTP server, the CLI could offer more capabilities
- take care of caching modes
- serve also snippet files without the need for a `package.json`
- transpile ES6 or typescript on the fly
- keep track of changes and notify the client
### build locally
- prepare cordova folder layout in build folder
- copy transpiled sources
- start cordova build

**Comment by mpost** [comment]
The tabris cli development is happening in this repo: https://github.com/eclipsesource/tabris-js-cli

**Comment by cpetrov** [comment]
A first version of the Tabris CLI has been released. We will track development in the [Tabris CLI](https://github.com/eclipsesource/tabris-js-cli) repo.
