### ISSUE TITLE
page.set ('backgroundImage') not working

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-js#991]
The background Image is not set in any of these codes (i tried all). Please help
The image png is very much there.

`page.set('backgroundImage', {src: 'src/images/background.jpg'});`
`page.set('backgroundImage', {src: '.src/images/background.jpg'});`
`new tabris.page({title:'Mytitle', backgroundImage: {src: '.src/images/background.jpg'}).open();`

But src pointing to some jpg in some webserver url is picked up if provided.
`new tabris.page({title:'Mytitle', backgroundImage: {src: '<httpurl>'}).open();`

**Comment by mpost** [comment]
could you provide the folder structure you are using?

**Comment by cookieguru** [comment]
I tried this snippet and it works:
```js
page.set('backgroundImage', {
  src: 'https://tabrisjs.com/assets/img/tabris-connect-medium.png'
});
```
Remember that when the [`src` attribute](https://tabrisjs.com/documentation/latest/types#image) specifying a relative path (i.e. not a URL) are resolved relative to 'package.json'.

On your second two examples it's looking for a folder literally named `.src`.  You probably meant `./src`

**Comment by natanraj** [comment]
when i posted here i made a mistake - but i rightly coded './src/images/background.jpg'.  the src is from the relative path of root where package.json is located.

By the by someother Imageview with similar image.src path works. Would there be any issues if we test jpg's downloaded from net.. Like any copyright ?

**Comment by natanraj** [comment]
appars to be an issue with the image .. an PNG works. Not sure if the background.jpg is copy right protected

**Comment by natanraj** [comment]
Can you please kindly help. if you could set this as backgroundImage ? I was never successful..just shows a black background. `backgroundImage, {src: './src/images/background_1.png'}`
![background_1](https://cloud.githubusercontent.com/assets/11765325/19019900/0dabfcce-88b5-11e6-8bb6-f62c45ab6bf3.png)

**Comment by natanraj** [comment]
Atlast resolved this by setting some width & height properites under backgroundImage. That solved all the issues
