### ISSUE TITLE
Real Applications on Tabris-js?

### ISSUE THREAD

**Issue by rigerous** [eclipsesource/tabris-js#992]
Can you provide examples of real applications on tabris-js?

**Comment by gosia-eclipsesource** [comment]
The app for GEV, a German spare parts wholesaler, is used by retailers worldwide:
https://itunes.apple.com/us/app/gev-app/id794532530?mt=8
https://play.google.com/store/apps/details?id=com.gevonline.shop

Also check out the EclipseCon North America app:
http://eclipsesource.com/blogs/2016/03/03/plan-your-eclipsecon-na-with-the-conference-app/
We are currently updating it for the upcoming EclipseCon Europe.

There's more, including large enterprise but I can't give away more details just yet.

**Comment by sergioradovcic** [comment]
Our highly rated app, STYR is written entirely with Tabris. It does BLE device syncing, push, geo fencing, and much more without a hiccup. You can find it by searching for STYR in Google Play or App Store.

**Comment by mpost** [comment]
@sergioradovcic The app looks very nice. Thanks for sharing. :)

**Comment by mpost** [comment]
Closing this for now.
