### ISSUE TITLE
New line character rendered as new line when markup enabled

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#994]
In HTML the `<br/>` tag should be used for line breaks. The new line character `\n` gets rendered as a space.

This is the behavior on Android. On iOS, new lines get rendered at `\n` characters:

``` js
var page = new tabris.Page({topLevel: true});

new tabris.TextView({
  left: 10, top: 30, right: 10,
  text: "<b>Some text</b>\nNew line 1\nNew line 2",
  markupEnabled: true
}).appendTo(page);

page.open();
```

| Android | iOS |
| --- | --- |
| ![screenshot_1475573381](https://cloud.githubusercontent.com/assets/2341769/19069506/90227c0a-8a27-11e6-8d11-87b66a77ff80.png) | ![simulator screen shot 04 oct 2016 11 29 40](https://cloud.githubusercontent.com/assets/2341769/19069469/64fe2f24-8a27-11e6-800d-117a9c2dc6ee.png) |

Currently, when enabling the `markupEnabled` property, we allow for a subset of HTML tags to use in the TextView _text_. We don't specify how characters like `\n` are processed. It would be useful if `\n` would be rendered as in the browser, as this would make the `markupEnabled` functionality a better drop-in replacement for arbitrary HTML data.

**Comment by natanraj** [comment]
@cpetrov new line character for HTML is <br> not \n. Not sure why android alone takes up this way.

**Comment by patrykmol** [comment]
This issue has been already fixed on iOS.
