### ISSUE TITLE
Setting TextInput or TextView text property to null sets the text to "null"

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#996]
The following snippet shows the text as null instead of resetting it to the "empty string".

``` js
new tabris.TextInput({
  text: null
}).appendTo(tabris.ui.contentView);
```

**Comment by ralfstx** [comment]
Currently, we translate non-string values to strings, which is quite common for JS APIs. However, I agree that it would be more intuitive to reserve `null` for *resetting* a property. That would have to changed for all widget properties. It might even lead to inconsistencies for properties that support `null`, but do not default to `null` (if those properties exist).
